### ISSUE TITLE
Echo bot won't start

### ISSUE THREAD

**Issue by mcorning** [MicrosoftDocs/bot-docs#1001]
I was almost done with a detailed critique of this quickstart. I made the mistake of clicking a link above. poof. start over with my feedback.
in summary, setting up an Echo bot fails:
&gt; my-chat-bot@1.0.0 start C:\Users\michael\Documents\GitHub\SovrinSecours\tutorial\Bot Framework\my-chat-bot
&gt; tsc --build && node ./lib/index.js

[botInitializationError]: Error: Missing LUIS configuration. Please follow README.MD to create required LUIS applications.

given my bot file, I have an echo bot, not a basic bot, right?

{
    "name": "my-chat-bot",
    "services": [
        {
            "type": "endpoint",
            "name": "development",
            "endpoint": "http://localhost:3978/api/messages",
            "appId": "",
            "appPassword": "",
            "id": "1"
        }
    ],
    "padlock": "",
    "version": "2.0"
}

so what gives? answer that, and I'll rewrite my original comments to improve this quickstart out of box experience.

In the meantime, I may delete the bot folder and start from the beginning of this quickstart knowing a successful outcome is far from certain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaad3f2-75c5-e958-4734-8925d03d95c6
* Version Independent ID: 8d98b390-5368-1fa4-8cce-3b0cff252eaa
* Content: [Create a bot using Bot Framework SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0&viewFallbackFrom=azure-bot-service-3.0#feedback)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
You may have an old copy of the page cached in your browser or are using an outdated bookmark. When I clicked the article link in this issue, I was forwarded to the [v4 JavaScript quickstart topic](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0) page, which seems to be in order. I followed the directions and ended up with a working Echo bot (with no LUIS error).

Let me know if this fixed the problem for you or not.

**Comment by mcorning** [comment]
I followed your link, and I’m fairly sure you and I are on the same page because my feedback entry from yesterday is visible.

I was going to try the exercise again trying to pay more attention, but my calendar is conspiring against me. Still, I will let you guys know my experimental results as soon as I can.

Thanks for reaching out.



Rwap
^m

**Comment by JonathanFingold** [comment]
Closing for now. Please open if the original issue is not solved.
