### ISSUE TITLE
Reuse ChoicePrompt Dialog

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/bot-docs#1002]
I have some prompt dialogs that I want to reuse them in my program.

Assume I have a ChoicePrompt to get the user gender.
Whenever I want to ask the user about his gender, I need to redefine the `options` that are passed to `ChoicePrompt`.

That's why I tried to expand the `ChoicePrompt` class by inheritance, but I can not figure out how I can set the `options` within an instance of `ChoicePrompt` or higher.

Where do I set his `Choices` or `Actions` as permanent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9577ff-cf56-e5de-84c3-bfe10aab5368
* Version Independent ID: b5d62753-f87b-4673-b09b-a5a3fd9360e8
* Content: [Reuse dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=csharp#define-the-check-in-component-dialog)
* Content Source: [articles/v4sdk/bot-builder-compositcontrol.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-compositcontrol.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by baruchiro** [comment]
I override the `BeginDialogAsync` from `Prompt`:

```csharp
public override async Task<DialogTurnResult> BeginDialogAsync(DialogContext dc, object options,
    CancellationToken cancellationToken = default(CancellationToken))
{
    return await base.BeginDialogAsync(dc, options ?? this.myConstOptions, cancellationToken);
}
```

(Of course, the better way is to inject only the `options.Choices`)

**Comment by JonathanFingold** [comment]
Prompts are designed to work well from within another dialog, so there is some wiring that may seem extraneous at first:
- The call to `DialogContext.PromptAsync` in the enclosing dialog calls the prompt instance's `BeginDialogAsync`.
- The abstract `Prompt` class implements `BeginDialogAsync` to call its abstract `OnPromptAsync` method.
- The `ChoicePrompt` class implements the `OnPromptAsync` method to use the choices from the prompt options parameter.

You could derive your prompt class from `ChoicePrompt`:
- Either hard code your prefered options in the class or allow them to be set in the constructor (the `myConstOptions` in your example).
- Override `OnPromptAsync`

For example, this code seems to work (with having done only superficial testing):
```csharp
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Builder.Dialogs.Choices;

    public class DefaultChoicesPrompt : ChoicePrompt
    {
        protected readonly List<Choice> _defaultChoices;

        public DefaultChoicesPrompt(
            string dialogId,
            List<Choice> defaultChoices = null,
            PromptValidator<FoundChoice> validator = null,
            string defaultLocale = null)
            : base(dialogId, validator, defaultLocale)
        {
            _defaultChoices = defaultChoices;
        }

        protected override Task OnPromptAsync(
            ITurnContext turnContext,
            IDictionary<string, object> state,
            PromptOptions options,
            bool isRetry,
            CancellationToken cancellationToken = default(CancellationToken))
        {
            // Determine what behavior you want if choices are specified when the prompt is called.
            // Do you want them to be ignored, replace the default choices, or add to them?
            // This could be an additional option in the constructor or just coded directly here.
            // Here, I let them replace the default choices.
            // Note that we're modifying the options object here, since that is what the dialog system
            // is putting on the stack and what will get persisted between turns.
            options.Choices = options.Choices ?? _defaultChoices;

            return base.OnPromptAsync(turnContext, state, options, isRetry, cancellationToken);
        }
    }
```

**Comment by JonathanFingold** [comment]
Another way to do this is to wrap the choice prompt up in a component dialog, with the fixed choice list, and then reuse the component dialog.
