### ISSUE TITLE
Dont see botfile being created anymore

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/bot-docs#1004]
With the latest Azure webapp bot deployments.. I am not seeing bot files.. is this new norm...? lot of documentation need to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by joseali93** [comment]
do you have some solution? because i m trying to understand bot framework but that .bot isnt generate and all de documentation talk about it.

**Comment by iMicknl** [comment]
Related to #1005

**Comment by Kaiqb** [comment]
Refer to [Manage bot resources](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp) and [Deploy your bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp).

The bot file is going away, and the rest of the changes for our samples and articles are coming shortly, but the links above should give you enough to go on for now.
