### ISSUE TITLE
Not seeing .bot file in deployment

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/bot-docs#1005]
I created a web app bot resource today using v4 framework and C#.. no longer seeing a bot file.. wasted lot of time on this article... if the bot files are not being generated for C#, please make sure to update documentation first before you making such changes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by iMicknl** [comment]
It looks like this article hasn't been updated after the 4.3 release, [which deprecated the use of .bot files](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp)... If you would like to create a QnAMaker bot, have a look at this [updated article](https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/tutorials/create-qna-bot) for the time being.

**Comment by joseali93** [comment]
But that its a tutorial in c#, ther is tutorial updated of nodejs? and that is for QnA there is something for luis??

**Comment by Kaiqb** [comment]
The instructions were updated last week. Check out [quickstart](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0), [manage bot resources](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp), and [deployment](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp) topics.
