### ISSUE TITLE
.bot file deprecated

### ISSUE THREAD

**Issue by mphacker** [MicrosoftDocs/bot-docs#1006]
With SDK 4.3+ the .bot file has been deprecated.  This documenation needs to be updated to represent the correct way to build a QnA Maker bot without the .bot file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by Kaiqb** [comment]
The docs, sample, and templates (VS, Yeoman) will be released during the first week of May. We are currently working on getting things ready.

**Comment by BeigeBadger** [comment]
@Kaiqb so what are we do to until the first week of May - use the older SDK?
