### ISSUE TITLE
Visual Studio 2017 minimum version

### ISSUE THREAD

**Issue by mahomedalid** [MicrosoftDocs/bot-docs#1007]
Hi, a partner had some weird issues trying to run the bot framework until we figure it out was due to an outdated version of Visual Studio 2017 (15.4). Updating to 1.59 worked. We guess it's because some netcore support. It would very helpful to know the minimum version required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Framework SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
We recommend using the latest released version of VS.
