### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by xanatzar** [MicrosoftDocs/bot-docs#1008]
"Note" at the top has incorrect information. Although the current page is for SDK v4 it says it is for SDK v3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c82d523-dd41-d6ec-a288-07a0015d767d
* Version Independent ID: 70a165b9-7501-d727-8ddd-f6bdff922778
* Content: [Create task automation bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-task-automation?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-design-pattern-task-automation.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-pattern-task-automation.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by ivorb** [comment]
fixed, will be pushed live with our next publishing cycle. Thanks for reporting!
