### ISSUE TITLE
Efforts in hours needed to implement LUIS dispatcher

### ISSUE THREAD

**Issue by rohitblue28** [MicrosoftDocs/bot-docs#1009]
I want to know how much efforts(in person hours) would be required to implement LUIS dispatcher. For example i have two different LUIS apps as of now and may get extended to four later on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
I think you can base your estimate by doing steps that are outlined in the dispatcher topic.
