### ISSUE TITLE
How is appsettings.json related to web app settings(configuration now)

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/bot-docs#1011]
Its confusing for users to understand what does app settings of webapp mean when appsettings.json is available and how they are related..

with webapp app settings we can integrate keyvault seamlessly.. can the same be done with appsettings.json?

How to secure my secrets used in bot with keyvault along with usage of awesome modern features provided by WebApp platform team in integrating app settings with keyvault references and MSI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8cc826-fa2f-5521-ead7-b771ad527269
* Version Independent ID: 91bc6ab6-e909-e8da-74aa-4a178559c290
* Content: [Manage resources with a .bot file - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-file-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-file-basics.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
If you are in the Azure portal, you'll see settings for Web App that are named App Settings. If you are talking about bot project in C#, the appsettings.json file is used for keeping id/pwd etc. For security reasons, you should be able to KeyValut.
