### ISSUE TITLE
Emulator no longer working

### ISSUE THREAD

**Issue by ryanleung96** [MicrosoftDocs/bot-docs#1012]
The Emulator V4 is no longer working, it kept asking for config the ngork service. After serval attempts, it stays not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa3a3039-9b21-fcb9-3fd7-4ae8c69bce93
* Version Independent ID: 36ceb86e-828a-03d7-3245-44ab6ea4c09a
* Content: [Test and debug bots using the Bot Framework Emulator - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-debug-emulator.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-debug-emulator.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
You can [log an issue](https://github.com/Microsoft/BotFramework-Emulator/issues) in the emulator repo with steps to repro.
