### ISSUE TITLE
Syntax issue and confusing instructions

### ISSUE THREAD

**Issue by jayallenmsft** [MicrosoftDocs/bot-docs#1013]
"Note that these first few lines were moved from the body of the services.AddBot&lt;QnaBot&gt;(options =&gt; call come to before it."

1. Line is not grammatical English.
2. Instruction is confusing. What code should be placed where inside of the existing ConfigureServices code? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by Kaiqb** [comment]
I am trying to understand the issue you are facing. Did you complete the first topic [[1. Create and deploy a basic bot]](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp) before doing the second one?

**Comment by turbozapekanka** [comment]
I don't understand this sentence too
The code example is not aligned with what I have out of the template.
The template has the following code: public QnaBot(ConversationState conversationState, ILoggerFactory loggerFactory)

So it has ConversationState in place of QnaBotAccessors

ConfigureServices method is also not following the template.

The result is after I followed the examples (both topics) it works locally but does not work in Production

**Comment by jayallenmsft** [comment]
> I am trying to understand the issue you are facing regarding where should the code go. Did you complete the first topic [[1. Create and deploy a basic bot]](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp) before doing the second one?

Yes, I did the first tutorial. My issue is that it's not clear how the final function is supposed to look. What code gets pasted where? What gets replaced and what gets kept from the function I'm editing? I tried to figure it out on my own and I ended up with a broken bot.

**Comment by DanDev33** [comment]
This article was reworked and published for v4.4.x on Friday. Please reopen this if you still have an issue.
