### ISSUE TITLE
Unable to access the Github repo for source code.

### ISSUE THREAD

**Issue by skrishnapuram** [MicrosoftDocs/bot-docs#1014]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8802814f-136c-afef-7710-63a0a83d8069
* Version Independent ID: 403cc45b-d39e-293f-3e91-bf76a6908da3
* Content: [Conduct audio calls with Skype - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-audio-calls?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/dotnet/bot-builder-dotnet-audio-calls.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-audio-calls.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
The SDK v3 samples are [here](https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp).
