### ISSUE TITLE
Update documentation to reflect SDK 4.3

### ISSUE THREAD

**Issue by BeigeBadger** [MicrosoftDocs/bot-docs#1016]
Examples of how to use the appsettings.json or .env file to integrate a Knowledge Base, along with the C# code would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Sub-service: **cognitive-services**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
This will be published with our next release, with all article code and corresponding samples updated to current best practices.
