### ISSUE TITLE
Download code is incomplete

### ISSUE THREAD

**Issue by lafe** [MicrosoftDocs/bot-docs#1017]
The downloaded code is incomplete and cannot be compiled (it is missing at least the "main"-method). Therefore, this approach cannot be used as the base for a custom bot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9e2e6-b901-9e27-d070-701922396a4c
* Version Independent ID: c29a68b2-886d-2cec-0ce7-c49c586d7ea8
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by ivorb** [comment]
Can you give more information? It looks like you were creating a bot in the Azure portal then downloading it... in what language? When you tried to run it, what happened? This runs on a framework so you won't see a "main" method per se.

**Comment by lafe** [comment]
Basically, I followed the steps outlined in the [Download Code](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0#download-code) link:
- I created a QnA Bot in C#
- In Azure I clicked on the "Build" button in the "Web App Bot" resource
- There I clicked on "Download Bot Source Code". It asked me, if I want to include the secrets which I confirmed.
- I extracted the ZIP file locally, opened it in Visual Studio 2019 and clicked "Run". Visual Studio tried to compile the code but was unable to, because the main method was missing. 
- After I analyzed it and compared it with the [samples for the BotBuilder](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/11.qnamaker) there seem to be additional files missing.

**Comment by ivorb** [comment]
When I follow the link to create a web app bot, I don't see the option to create a QnA bot - instead it links me off the docs page about QnA. I'm seeing that it will either create a Basic bot (a core bot with dialogs and LUIS) or an Echo bot - both of which won't match the QnA sample in the BotBuilder repo.

All of that is an aside, as the bot should work when you download it, regardless of if you chose the Echo or Basic bot. Have you verified you have the necessary prerequisite .NET libraries are installed to run locally? I'll give these steps a shot myself here shortly and see what happens for me.

**Comment by lafe** [comment]
The Bot has been created through the QnA Maker Web Service. After I published a Knowledge Base, there is an option to create a Bot. This option creates the Bot in Azure which is a normal "Web App Bot" - the only difference seems to be that the template cannot be selected and that the API Key of the associated QnA Web Service has to be included.

**Comment by Kaiqb** [comment]
Is this a Bot Framework SDK v3 bot?

**Comment by Kaiqb** [comment]
This is a bug. It's been reported to the QnA team. Thanks!

**Comment by lafe** [comment]
@Kaiqb Thank you :)
