### ISSUE TITLE
Publish step uses --proj-name which has been deprecated, it should use --proj-file-path

### ISSUE THREAD

**Issue by BeigeBadger** [MicrosoftDocs/bot-docs#1024]
Warning message: Option '--proj-name' has been deprecated and will be removed in version '2.1.0'. Use '--proj-file-path' instead.

az bot publish -g YOUR-BOT-NAME -n YOUR-BOT-NAME --proj-name YOUR-BOT-NAME.csproj --version v4

should something like

az bot publish -g YOUR-BOT-NAME -n YOUR-BOT-NAME --proj-file-path PATH-TO-YOUR-BOT/YOUR-BOT-NAME.csproj --version v4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81426100-ac60-c692-0906-f9199deb2a6c
* Version Independent ID: f9aa4064-fe22-71c8-6ac3-93b0d0fa1bdd
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-getting-started?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-getting-started.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-getting-started.md)
* Service: **bot-service**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by Kaiqb** [comment]
This topic was updated. Please refer to https://github.com/microsoft/botframework-solutions/tree/master/docs for help on VA.
