### ISSUE TITLE
Same tutorial for Basic bot with Language Understanding ?

### ISSUE THREAD

**Issue by smarcon** [MicrosoftDocs/bot-docs#1025]
Any tutorial on the basic bot with LUIS option?

I can't find anything and I have some trouble with the initial configuration (when doing a first test the bot has a default booking system conversation that I can't figure out how to get rid of...)

![image](https://user-images.githubusercontent.com/7058783/56225958-25761f00-6027-11e9-891d-c19bcd5b687e.png)

![image](https://user-images.githubusercontent.com/7058783/56226095-6f5f0500-6027-11e9-89a3-f5142a994f96.png)

Thanks!

**Comment by Kaiqb** [comment]
Take a look at this [topic](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs) that uses the Basic Bot.
