### ISSUE TITLE
Avoid Auth Card if already have token from the hosted site

### ISSUE THREAD

**Issue by vikramdadwal** [MicrosoftDocs/bot-docs#1026]
What is we do not want to prompt for Auth card if we already have AAD token with us, basically avoiding the user to again login in the BOT window ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
There is an updated sample that shows how to do this. The updated topic is scheduled to be published in a week or two. Here's a preview of the part you're asking about:

---
Within a dialog step, use BeginDialogAsync to start the OAuth prompt, which asks the user to sign in.
If the user is already signed in, this will generate a token response event, without prompting the user.
Otherwise, this will prompt the user to sign in. The Azure Bot Service sends the token response event after the user attempts to sign in.
```csharp
return await stepContext.BeginDialogAsync(nameof(OAuthPrompt), null, cancellationToken);
```
Within the following dialog step, check for the presence of a token in the result from the previous step. If it is not null, the user successfully signed in.
```csharp
// Get the token from the previous step. Note that we could also have gotten the
// token directly from the prompt itself. There is an example of this in the next method.
var tokenResponse = (TokenResponse)stepContext.Result;
if (tokenResponse != null)
{
```

**Comment by vikramdadwal** [comment]
Thanks @JonathanFingold for the reply. One thing which I do not understand here is, if my bot app is just a Asp core API only (i.e. no index page)  how it would get the previous token ?

**Comment by JonathanFingold** [comment]
If I understand correctly, the bot connector service uses the bot's app ID to manage that handshake. The user would have to sign in once via the bot before the bot and service would have the token.

**Comment by JonathanFingold** [comment]
I think that there is some work in progress to support a more integrated single-sign on experience, but it is still in the works.

**Comment by vikramdadwal** [comment]
This feature is really needed here as we do not want our users already logged in (with their AAD account in the hosted site) to click another button to login (As that would be bad user experience). Do we have any timelines for this feature. Thanks.

**Comment by aschemel** [comment]
I agree with @vikramdadwal - This feature should be implemented soon. Makes no sense from a user perspective to login twice within the same application or site the bot is being exposed on.

@JonathanFingold Could you confirm that there is WIP for this? If so, any roadmap we can follow or when can we expect to have it... Thanks!

**Comment by JonathanFingold** [comment]
There are no plans to work on this in the immediate future. However, if you are using Direct Line and WebChat, you should be able to create a SSO experience using one of the patterns documented. (You can also find additional information about WebChat in the [BotFramework-WebChat](https://github.com/Microsoft/BotFramework-WebChat) repo.)

For other channels we aren’t working on anything (so no SSO for Skype, Teams, Cortana, etc.).

You can submit a feature request. Refer to the table in the BotBuilder repo for [Issues and feature request](https://github.com/Microsoft/BotBuilder#issues-and-feature-requests) for which repo to open the issue in.

**Comment by aschemel** [comment]
@JonathanFingold, yes, I'm using DirectLine and WebChat, but can't find any resources that take me in this direction. Could you please share these documented patterns, I searched in BotFramework-WebChat, but didn't manage to map those examples with this "SSO Workaround"

Thanks!

**Comment by JonathanFingold** [comment]
Here are the resources currently available (the docs are getting a refresh this week):
1. [Embed a Web Chat control in your web site](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0#embed-the-web-chat-control-in-your-website).
1. Blog posts:
   1. [Enhanced Direct Line Authentication Features](https://blog.botframework.com/2018/09/25/enhanced-direct-line-authentication-features/)
      Posted on September 25, 2018 by The Bot Framework Team
   1. [Using WebChat with Azure Bot Service’s Authentication](https://blog.botframework.com/2018/09/01/using-webchat-with-azure-bot-services-authentication/)
      Posted on September 1, 2018 by The Bot Framework Team
   1. [Sign-In experiences](https://blog.botframework.com/2018/08/28/sign-in-experiences/)
      Posted on August 28, 2018 by The Bot Framework Team

And the following, soon to be published guidance:

There are a couple of important security issues to consider when you use Azure Bot Service authentication with Web Chat.

1. Prevent impersonation, where an attacker makes the bot think they're someone else. In Web Chat, an attacker can impersonate someone else by changing the user ID of his Web Chat instance.

    To prevent this, make the user ID unguessable. When you enable enhanced authentication options in the Direct Line channel, Azure Bot Service can detect and reject any user ID change. The user ID on messages from Direct Line to your bot will always be the same as the one you initialized Web Chat with. Note that this feature requires the user ID to start with `dl_`.

1. Ensure the correct user is signed in. The user has two identities: their identity in a channel and their identity with the identity provider. In Web Chat, Azure Bot Service can guarantee that the sign-in process is completed in the same browser session as Web Chat itself.

    To enable this protection, start Web Chat with a Direct Line token that contains a list of trusted domains that can host the bot's Web Chat client. Then, statically specify the trusted domain (origin) list in the Direct Line configuration page.

---

We plan on getting the content from these blog posts into the documentation in the next month or so.

**Comment by JonathanFingold** [comment]
@vikramdadwal , @aschemel , Are you unblocked? Can I close this issue?

**Comment by vikramdadwal** [comment]
@JonathanFingold : I would like to keep this issue open till we get this feature implemented just for tracking purpose.

**Comment by brvaland** [comment]
@JonathanFingold @vikramdadwal - We are having similar issue and would like to know if you managed to get it done. I have two application i.e. website and bot using same identity provider. Can i pass user's access token to bot and authenticate without prompting user?

I had read on the "Sign-In experiences" document posted on 28 Aug 2018 which states
"A third option, called Single Sign-On (SSO), is in development and is where the client UI takes the client’s user token for the client app and exchanges it for a different token that can be used with the same identity provider, but a different app/scopes. For now, it is possible to create a similar user experience using WebChat by using technique #1 above."

It is abit confusing so i would appreciate someone could clarify ?

**Comment by EricDahlvang** [comment]
@brvaland  We have a recently released WebChat SSO sample you can find here: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/19.a.single-sign-on-for-enterprise-apps

**Comment by hansmbakker** [comment]
@EricDahlvang @JonathanFingold my scenario is as follows:
I am building a chatbot that I want to provide to client companies as a service. I believe this classifies it as a multi-tenanted app. The idea is that on their intranet they add the webchat code that connects to the bot APIs I provide them with. I want to use e.g. Microsoft Graph API to get some end user context.

What is not clear to me from the README in the provided samples, is
- where to do the Bot Registration --> only in my Azure AD or also in the client organizations' Azure AD?
- can the client organization use my Bot Registration to give consent for the Graph API scopes, or should I have another app registration / bot registration in their Azure AD?
- Do I need to set up additional things like Azure AD B2B, federation or guest users?

**Comment by mmiele** [comment]
@vikramdadwal If this is still an issue, and perhaps you already know, the SSO feature was released. You can find the related documentation here: [Single sign on](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-sso?view=azure-bot-service-4.0).
