### ISSUE TITLE
Re-publishing the bot does not update the .bot file in Azure

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/bot-docs#1028]
This makes "qna" element missing in the bot file uploaded to azure, thus it does not work in Production (but works in Development)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by DanDev33** [comment]
We are currently working on this issue. As of SDK v4.3 the .bot file is no longer created or used in Azure. Your C# bot now uses appsetting.json to provide connectivity information, your JS bot uses a .env file. There is an article we are working on getting online that describes how to do this with these new files. Are you trying to publish a C# or nodeJS bot?

**Comment by turbozapekanka** [comment]
I'm publishing a C# bot.

**Comment by DanDev33** [comment]
OK, the new article has this working end-to-end. Hopefully we'll get this up for you asap!

**Comment by ivorb** [comment]
As of yesterday, the new docs have been published, removing the need of the bot file - that should solve your issue! Please open a new issue if you're still running into problems.
