### ISSUE TITLE
Node.js version

### ISSUE THREAD

**Issue by hinojosachapel** [MicrosoftDocs/bot-docs#1029]
It would be nice to also have the **Differences between the v3 and v4 Node.js SDK** version. The same for **Migrate a Node.js SDK v3 bot to v4**. Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09f6b021-efb3-761f-6f00-cbd679e39dfc
* Version Independent ID: 72806cd3-23c7-6e60-d54d-3ecc0e4bc371
* Content: [Differences between the v3 and v4 SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/migration/migration-about?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/migration/migration-about.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/migration/migration-about.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by Kaiqb** [comment]
Take a look at [this ](https://docs.microsoft.com/en-us/azure/bot-service/migration/javascript-migration-quickreference?view=azure-bot-service-4.0)and [this](https://docs.microsoft.com/en-us/azure/bot-service/migration/conversion-javascript?view=azure-bot-service-4.0).
