### ISSUE TITLE
Code Samples etc. need to be updated for botframework 4

### ISSUE THREAD

**Issue by JohnGalt1717** [MicrosoftDocs/bot-docs#1030]
The samples link hasn't been updated in 2 years and is out of date and not functional. As a result it is mostly useless at this point.  The code needs to be updated and the issues with it fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1ea3ca-002b-5114-df1d-fb50b0e103e2
* Version Independent ID: b393f465-9b91-7f96-aaf8-e6f023eab8e4
* Content: [Transition conversations from bot to human - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-handoff-human?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-design-pattern-handoff-human.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-pattern-handoff-human.md)
* Service: **bot-service**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by Kaiqb** [comment]
Please open the issue in [Bot Builder Samples](https://github.com/Microsoft/BotBuilder-Samples/issues) repo for tracking this issue.

**Comment by JohnGalt1717** [comment]
That's fine and all as evidenced by the dozens of requests there. But that doesn't address the abysmal documentation that basically says "You can do this, read the sample code" instead of doing what documentation is supposed to do, which is teach you how to do it with sample code backing the instruction.
