### ISSUE TITLE
Bot file is obsolete but still has documentation in article "How bots work"

### ISSUE THREAD

**Issue by corinagum** [MicrosoftDocs/bot-docs#1031]
I think the section on bot files should be removed from this article to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf8a24b-7029-247b-3c5c-3902befe0ccf
* Version Independent ID: bcd01444-d332-29e6-2b81-5558bb2d576b
* Content: [How bots work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=js#feedback)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by Kaiqb** [comment]
@corinagum -  we'll be updating docs at the end of the month. The reason it is there is because users might have .bot file and all of our samples also have .bot file.
