### ISSUE TITLE
Bot publishing issue, changes in az bot CLI

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/bot-docs#1033]
Besides the deprecated `--proj-name` issue which is reported in https://github.com/MicrosoftDocs/bot-docs/issues/1024, I'm getting warnings mentioning `SCM_DO_BUILD_DURING_DEPLOYMENT` since recently and my publishing step fails in CI/CD.

On https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#bot-service I see there were some relevant changes in the `az bot` behaviour but it does not explain what it means for users.
- what is `az bot prepare-deploy` needed for?
- do we need to do something with `SCM_DO_BUILD_DURING_DEPLOYMENT` now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81426100-ac60-c692-0906-f9199deb2a6c
* Version Independent ID: f9aa4064-fe22-71c8-6ac3-93b0d0fa1bdd
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-getting-started?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-getting-started.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-getting-started.md)
* Service: **bot-service**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by Kaiqb** [comment]
@darrenj - please look into this issue.

**Comment by hansmbakker** [comment]
This is discussed in https://github.com/Azure/azure-cli/pull/8834 and https://github.com/Microsoft/botbuilder-tools/issues/985#issuecomment-484912981

**Comment by Kaiqb** [comment]
This content no longer exists. The Enterprise template was with replaced with the new [Virtual Assistant template](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-virtual-assistant-introduction?view=azure-bot-service-4.0).
