### ISSUE TITLE
Command for "dispatch add -t qna" must be changed to get sample 14.nlp-with-dispatch to run properly

### ISSUE THREAD

**Issue by Zerryth** [MicrosoftDocs/bot-docs#1034]
Per email conversation, currently the command to add the child qna service to dispatch that's shown in tutorial is this "dispatch add -t qna -i "&lt;knowledge-base-id&gt;" -n "&lt;knowledge-base-name&gt;" -k "&lt;your-cognitive-services-subscription-id&gt;"

Change it to add the argument --intentName q_sample-qna, so that the intent name in the bot matches the intent name that automatically gets generated from the dispatch add/dispatch create commands

new command:
"dispatch add -t qna -i "&lt;knowledge-base-id&gt;" -n "&lt;knowledge-base-name&gt;" -k "&lt;your-cognitive-services-subscription-id&gt; --intentName q_sample-qna"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&branch=pr-en-us-1325&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
@DanDev33 - please look into this.

**Comment by DanDev33** [comment]
Updated the article in my branch.
