### ISSUE TITLE
Invocation Guidelines Link Incorrect

### ISSUE THREAD

**Issue by cjh15hub** [MicrosoftDocs/bot-docs#1035]
The invocation guidelines link in the troubleshooting section of the Test a Cortana Skill page is incorrect.

Check if your invocation name meets the guidelines.
https://docs.microsoft.com/en-us/cortana/skills/invocation-guidelines

**Comment by Kaiqb** [comment]
@cjh15hub - could provide the topic that has this link?

**Comment by JonathanFingold** [comment]
@Kaiqb , looks like it's our aka link for the invocation guidelines. I'll find the correct target and update the link.

**Comment by JonathanFingold** [comment]
Fixed in branch. Should go live with the next doc push.
