### ISSUE TITLE
Samples of V4 includes .Bot file ?

### ISSUE THREAD

**Issue by vikramdadwal** [MicrosoftDocs/bot-docs#1036]
Here in this document, it is mentioned to move away from .BOT file. But the samples in the github all are using .BOT file only ? Can we please update the samples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8cc826-fa2f-5521-ead7-b771ad527269
* Version Independent ID: 91bc6ab6-e909-e8da-74aa-4a178559c290
* Content: [Manage resources with a .bot file - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-file-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-file-basics.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
The updated samples are [here](https://github.com/Microsoft/BotBuilder-Samples/tree/samples-work-in-progress/samples). We are planning to merge these into the master branch in a few weeks.
