### ISSUE TITLE
Rich UI samples

### ISSUE THREAD

**Issue by vikramdadwal** [MicrosoftDocs/bot-docs#1039]
I have seen so many bots which are build on top of Microsoft bot framework and they have got a very rich ui experience on top. 

My question is how we do that, e.g a skin on top of adaptive cards etc. 

Please help us here with some samples. Also we have used adaptive cards but still we are not able to modify the look and feel ?

Please look at this example : https://m.flyasiana.com/C/US/EN/index#section01

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79129724-5f90-ac8d-6918-d5801a4e2001
* Version Independent ID: 08e19b7b-2ec6-95da-2f5a-d534e761f5da
* Content: [Create your own prompts to gather user input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-primitive-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-primitive-prompts.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by Kaiqb** [comment]
@vikramdadwal - take a look at the Web Chat control which allows customizations. https://github.com/Microsoft/BotFramework-WebChat
