### ISSUE TITLE
Better examples for conversation creation in C# for V4

### ISSUE THREAD

**Issue by lucascrandle** [MicrosoftDocs/bot-docs#1040]
Trying to create new conversations for Human handoffs.
This is documented in V3 but I'm getting errors in V4 framework, we need examples for how to do this.
https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-connector?view=azure-bot-service-3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1ea3ca-002b-5114-df1d-fb50b0e103e2
* Version Independent ID: b393f465-9b91-7f96-aaf8-e6f023eab8e4
* Content: [Transition conversations from bot to human - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-handoff-human?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-design-pattern-handoff-human.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-pattern-handoff-human.md)
* Service: **bot-service**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by hshahbaz** [comment]
Hi @lucascrandle , I am working on creating a bot with LUIS, QnAMaker and bot-to-human handoff. I have used dipatch bot in bot samples for LUIS and QnaMaker. I am looking to start implementing a bot to human handoff by opening a channel in MS Teams. 

I was wondering where to start for the handoff...this is like a customer service scenario where the agents will be using MS Teams on their end to reply to customers.

**Comment by JonathanFingold** [comment]
We don't yet have a sample for this, and I haven't tried to implement such a bot. Here's guess at how to do this:
1. The humans to whom the bot can hand off messages to will need to have initiated at lease one conversation with the bot that the bot can use to forward messages to.
1. Use proactive notification to forward messages from one conversation to the other.

To request such a sample, please open an issue in the [BotBuilder-Samples](https://github.com/Microsoft/BotBuilder-Samples) repo.

**Comment by lucascrandle** [comment]
Thanks @JonathanFingold . I will open an issue there
