### ISSUE TITLE
Generate per bot redirect url

### ISSUE THREAD

**Issue by sagilo** [MicrosoftDocs/bot-docs#1048]
Some services (like Azure DevOps) don't accept existing redirect URL's.
For best experience, provide a per-bot callback URL
Currently, this authentication method can't be used with Azure DevOps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d80e0b-f1b7-175b-128d-0fb12f17ae36
* Version Independent ID: 1ed9006a-bf0b-9aaa-d180-9d2cb0c09524
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/bot-builder-tutorial-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tutorial-authentication.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **JonathanFingold**

**Comment by JonathanFingold** [comment]
@sagilo The article you referenced is for v3 of the SDK. We have a new process for the v4 SDK, see the how to [Add authentication to your bot via Azure Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp%2Cbot-oauth) article.

Please let me know if there's an issue with the v4 content. (We are not supporting development of new v3 bots at this time.)

**Comment by JonathanFingold** [comment]
Please reopen (or open a new issue), if you still have questions. Thanks.
