### ISSUE TITLE
Still using the emulator locally

### ISSUE THREAD

**Issue by jchomarat** [MicrosoftDocs/bot-docs#1054]
I am not sure if I missed something, but if I want to still run my bot locally, with a local web server, in the emulator, I also had to update the .bot file to add the appId and appPassword I got from the Web App Bot. This seems to be missing in the section "Update your local appsettings.json or .env file"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Hi Julien,
Creating a Web App Bot in Azure no longer produces a .bot file. Instead your username/password info is store in either an appsettings.json (C#) or .env (JavaScript) file. You can use these values to run locally against a bot residing in Azure or on your localhost.  Your emulator can still produce and save a .bot file, but it is not required.
