### ISSUE TITLE
V3V4 migraiton doc link is broken

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/bot-docs#1055]
The following link is broken:
URL/section: https://docs.microsoft.com/en-us/azure/bot-service/migration/conversion-framework?view=azure-bot-service-4.0#update-the-root-dialog
Link: Implement sequential conversation flow

### Consider link
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp

**Comment by scheyal** [comment]
The link below *gather user input using a dialog prompt* is also broken

**Comment by JonathanFingold** [comment]
Thanks for catching this. A fix has been submitted and should go live in a few days.
