### ISSUE TITLE
ContosoChatBot example code diverged from documentation

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/bot-docs#1057]
The git example [ContosoHelpdeskChatBot](https://github.com/Microsoft/intelligent-apps/tree/master/ContosoHelpdeskChatBot) has diverged from the documentation for [V3V4 migration example](https://docs.microsoft.com/en-us/azure/bot-service/migration/conversion-framework?view=azure-bot-service-4.0).
### Recommendation: 
* Re-align documentation to latest code base
* Add guidance in repo to ensure alignment with documentation

**Comment by EricDahlvang** [comment]
It would be good if this sample is updated to use the ActivityHandler pattern used in the latest Bot Builder samples: https://github.com/Microsoft/BotBuilder-Samples/tree/samples-work-in-progress

**Comment by JonathanFingold** [comment]
This has been updated live.
