### ISSUE TITLE
bot.js and .bot file is missing

### ISSUE THREAD

**Issue by sunnysharma03** [MicrosoftDocs/bot-docs#1058]
Hi, 
     I think azure has changed the bot creation, now there is no option of azure storage and after deployment of resource there is no .bot file and no bot.js file which has luis code. Please check and update this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e8c5d2-bf2d-fc99-e813-bf9dd49eb9bb
* Version Independent ID: 830e4542-cdd8-3b64-f1df-2acae1ca3a88
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
Azure did update their templates early. Updated documentation will be going out alongside the 4.4 release in a few days.

**Comment by sunnysharma03** [comment]
thanks for the update.

**Comment by kaushalgautam** [comment]
@JonathanFingold, how many days would that be?

**Comment by JonathanFingold** [comment]
We try to be vague, because schedules slip, but it should be live by tonight.

**Comment by kaushalgautam** [comment]
@JonathanFingold, thanks for the quick response. Does this include all the quick start guides and cognitive services guides? I'm trying to build a basic bot on Node using the latest botbuilder. I failed because the guides are not properly synced and there's missing information after the latest releases. I hope they are in order soon.

**Comment by JonathanFingold** [comment]
The reference docs are currently synced to the live 4.3 packages. Everything else under Azure Bot Service documentation will be synced to the 4.4 packages, which are also going out today, as are updated bot samples. I don't have insight into documentation for other Azure services.
