### ISSUE TITLE
Building Bots in C#

### ISSUE THREAD

**Issue by erichilarysmithsr** [MicrosoftDocs/bot-docs#1059]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 134459a0-37b2-3111-06e2-71feb2b45e3c
* Version Independent ID: 3efc8cdb-f0a0-40ae-577c-348890233aa4
* Content: [Debug a bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-bot?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-debug-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-debug-bot.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by xtianus79** [comment]
yes as a javascript developer I rather learn how to build bots in c# and javascript

**Comment by erichilarysmithsr** [comment]
Is this possible to use C# in Microsoft Cortana
