### ISSUE TITLE
AutoSaveStateMiddleware not documented

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/bot-docs#1060]
On this page, `SetAsync` and `SaveAsync` are discussed. However it turns out that there is also middleware that can do this: `AutoSaveStateMiddleware`.

It is explained in https://github.com/Microsoft/AI/issues/1168 but not documented on this documentation page.
It would improve this page if you would explain the pros/cons/how to use it etc of the different approaches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c94a4c9-e988-3b42-a7db-3634d15e9c47
* Version Independent ID: 68765289-1d77-6e4a-c6fb-1abbc067fcbd
* Content: [Save user and conversation data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
At the bottom of the article, in [**Additional resources**](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp#additional-resources), we say that, "you should get, set, and save state as close together in your bot as possible." Saving state in middleware is an option, but not recommended at this point.

There are other potential issues with saving state in middleware, and the dev team currently recommends against using this, even if the folks maintaining the enterprise template like it.

I realize this is not ideal, but until the middleware and state features are more mature, we've decided not to document the auto-save state middleware.

**Comment by JonathanFingold** [comment]
Got confirmation from the dev team, "We do not recommend using it, as it makes behavior under error conditions unpredictable." I think the enterprise templates will be migrating away from this middleware after the 4.4 release of the SDK.

**Comment by hansmbakker** [comment]
Thank you for the clarification
