### ISSUE TITLE
Direct Line Speech Preview does not need SDK 4.5 Preview

### ISSUE THREAD

**Issue by Jeffders** [MicrosoftDocs/bot-docs#1061]
**Describe the bug**
Direct Line Speech Preview documentation says you need to use Bot Framework SDK 4.5 Preview, and this is not true. It will work with any SDK 4.3+.

**To Reproduce**
https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-3.0&branch=pr-en-us-1453

Test is in the "In this article" section.

**Comment by Kaiqb** [comment]
Fixed.
