### ISSUE TITLE
[Bugbash] the qnamaker tutorial should reference the qna doc that creates a bot out of an existing qnamaker service

### ISSUE THREAD

**Issue by Andrea-Orimoto** [MicrosoftDocs/bot-docs#1070]
this doc
https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&branch=pr-en-us-1325&tabs=csharp

should link this doc, maybe at the beginning?
https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/tutorials/create-qna-bot

**Comment by DanDev33** [comment]
created and added link https://aka.ms/azure-create-qna to article prerequisites
