### ISSUE TITLE
[BugBash] vsix projects should not be creating a new ConfigurationCredentialProvider

### ISSUE THREAD

**Issue by EricDahlvang** [MicrosoftDocs/bot-docs#1071]
**Describe the bug**
Each project has a ConfigurationCredentialProvider, yet there is already one in the integration libraries:

https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/ConfigurationCredentialProvider.cs

https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ConfigurationCredentialProvider.cs

**To Reproduce**
1. Create a project using one of the vsix templates
2. Notice the ConfigurationCredentialProvider class

**Expected behavior**
Use the ConfigurationCredentialProvider from the integration library

**Comment by ivorb** [comment]
Please open this against the samples repo, as they are responsible for the content of the VSIX template
