### ISSUE TITLE
[bugbash] Visual Studio 2017 or 2019?

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1072]
The Visual Studio 2017 prerequisite links to the latest Visual Studio download (2019): https://visualstudio.microsoft.com/downloads/

![image](https://user-images.githubusercontent.com/41968495/56928670-6856de80-6a8c-11e9-953d-db153966a0bc.png)

It should probably say "Visual Studio 2017 or later" or something like that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&branch=pr-en-us-1325&tabs=csharp#deploy-your-bot)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
changed 2017 to "2017 or later"
