### ISSUE TITLE
[Bugbash] A new user doesn't need to know about the existence of the .bot file

### ISSUE THREAD

**Issue by Andrea-Orimoto** [MicrosoftDocs/bot-docs#1073]
https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&branch=pr-en-us-1325&tabs=csharp

Reword the highlighted sentence, as a new user I don't want to know about something that is not there anymore.

![image](https://user-images.githubusercontent.com/17152540/56928662-62f99400-6a8c-11e9-8008-be19e743d608.png)

**Comment by DanDev33** [comment]
The missing .bot file has been a source of numerous issues & bug reports from our users. I think it is important to keep this available for now to let people know why they are "missing" the .bot file they used to get.

**Comment by DanDev33** [comment]
This is going to be retained "as is" for the current release to assist existing bot developers. Will be removed in a future release. Thanks for providing this feedback.
