### ISSUE TITLE
[Bugbash] qna app settings in appsettings.json are incorrect

### ISSUE THREAD

**Issue by Andrea-Orimoto** [MicrosoftDocs/bot-docs#1074]
the appsettings in this doc seem to be incorrect, they should be consistent with those that are created through the portal.
https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&branch=pr-en-us-1325&tabs=csharp#add-knowledge-base-information-to-your-bot
![image](https://user-images.githubusercontent.com/17152540/56928887-fcc14100-6a8c-11e9-96a6-1e5f6a35e0b3.png)

If you deploy a qna bot in the portal the appsettings look like this
![image](https://user-images.githubusercontent.com/17152540/56928834-df8c7280-6a8c-11e9-8b83-2abdf9470c77.png)

**Comment by DanDev33** [comment]
Updated naming for both C# & JS
