### ISSUE TITLE
[Bug Bash] Troubleshooting auth suggests going to dev.botframework.com

### ISSUE THREAD

**Issue by jameslew** [MicrosoftDocs/bot-docs#1075]
**Describe the bug**
Currently we still tell people to go to dev.botframework.com.  Almost everyone should be going to Azure portal for any config operations.

![image](https://user-images.githubusercontent.com/5997512/56928964-3bef9200-6a8d-11e9-95cd-3a84f041208a.png)

**To Reproduce**
1. https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0&branch=pr-en-us-1325

**Expected behavior**
Send people to azure portal to make config changes.

**Comment by DanDev33** [comment]
changed to https://portal.azure.com
