### ISSUE TITLE
[Bug Bash] We're still telling people that they need to provision storage in docs

### ISSUE THREAD

**Issue by jameslew** [MicrosoftDocs/bot-docs#1079]
**Describe the bug**
We're still telling people that we provision storage during bot creation; we no longer do that.

**To Reproduce**
Read content here; check screen shot of Azure Blade: https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?branch=pr-en-us-1325&view=azure-bot-service-4.0

**Expected behavior**
We no longer provision storage for users during template creation

**Comment by DanDev33** [comment]
provision of storage removed
