### ISSUE TITLE
[bugbash] Echo Bot VSIX template description should say "echoes"

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1083]
The plural of echo is spelled echoes and not echos

![image](https://user-images.githubusercontent.com/41968495/56929801-7823f200-6a8f-11e9-9aca-1870ba123ddc.png)

**Comment by ivorb** [comment]
Not an issue in our docs. Opened a bug in VSIX to track it.

https://github.com/Microsoft/BotBuilder-Samples/issues/1466
