### ISSUE TITLE
Bugbash: Topic on Online Code Editor is no longer relevant

### ISSUE THREAD

**Issue by jameslew** [MicrosoftDocs/bot-docs#1084]
**Describe the bug**
While the Online Code Editor exists, I think we're deprecating our support for it.  As such the document on it is no longer valid: https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-build-online-code-editor?view=azure-bot-service-4.0&branch=pr-en-us-1325 

Confirm with Andrea.

**Comment by DanDev33** [comment]
That would be sad. It's a really useful tool I use all the time.

**Comment by ivorb** [comment]
If we're depreciating it, we should say as much. As long as it's still valid, however, I suggest we leave the documentation in place.

**Comment by ivorb** [comment]
fixed
