### ISSUE TITLE
[Bug Bash] In the Deploy your bot tutorial section change the info on paying for use

### ISSUE THREAD

**Issue by CezaryMarcjan** [MicrosoftDocs/bot-docs#1086]
https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&branch=pr-en-us-1325&tabs=newrg

Replace the "Deploying your bot to Azure will involve paying for the services you use" with something else (at the bottom maybe) since the tutorial uses a "free subscription".

**Comment by Kaiqb** [comment]
Fixed.
