### ISSUE TITLE
Bugbash: Sending devs to dev.botframework.com in the Develop Locally topic

### ISSUE THREAD

**Issue by jameslew** [MicrosoftDocs/bot-docs#1088]
**Describe the bug**
This link in the develop locally topic sends developers to dev.botframework.com:

![image](https://user-images.githubusercontent.com/5997512/56929949-07310a00-6a90-11e9-817d-e5c2d5ced01b.png)

Doc link:

https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0&branch=pr-en-us-1325

**Comment by ivorb** [comment]
The section pictured above is in a "Test your bot in the cloud" section. If you still see an issue, please let us know with more details on where the issue is.
