### ISSUE TITLE
[Bugbash] SDK v3 is not needed as an option to the "Applies to" at the top of all pages

### ISSUE THREAD

**Issue by Andrea-Orimoto** [MicrosoftDocs/bot-docs#1089]
![image](https://user-images.githubusercontent.com/17152540/56930076-698a0a80-6a90-11e9-880a-7859d72cc3d7.png)

**Comment by ivorb** [comment]
@Kaiqb

**Comment by ivorb** [comment]
Keeping it consistent across all our pages
