### ISSUE TITLE
Bugbash: We never send developers to Azure Support from the support options page

### ISSUE THREAD

**Issue by jameslew** [MicrosoftDocs/bot-docs#1090]
**Describe the bug**
We have a support options page that's been there quite a while.  We have no links on it though that tell people to create a support ticket in the Azure Portal.  not sure if there's a permalink or not.

**To Reproduce**
https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-links-help?view=azure-bot-service-4.0&branch=pr-en-us-1325

**Comment by JonathanFingold** [comment]
Add a link to the table for Azure Help + Support.
