### ISSUE TITLE
[BugBash] EchoWithCounterBot.cs is not created by any of the vsix samples

### ISSUE THREAD

**Issue by EricDahlvang** [MicrosoftDocs/bot-docs#1091]
**Describe the bug**
This section: https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-bot?view=azure-bot-service-4.0&branch=pr-en-us-1325#debug-a-c-bot-using-breakpoints-in-visual-studio

Says:

> In the Solution Explorer, click EchoWithCounterBot.cs. This file defines your main bot logic.Set breakpoint as necesary. 

However, none of the templates create an EchoWithCounterBot.cs file.

**Comment by DanDev33** [comment]
Hi Eric,
The EchoBotWithCounter sample is being deprecated in this release.
