### ISSUE TITLE
Bugbash: Deep link to conversational analytics takes you to a rando file on github

### ISSUE THREAD

**Issue by jameslew** [MicrosoftDocs/bot-docs#1092]
**Describe the bug**
Clicked a link on Troubleshooting bot HTTP 500 errors and ended up on a random location on github.

https://github.com/Microsoft/AI/blob/master/solutions/analytics/ConversationalAnalyticsSample_4_4.pbit

![image](https://user-images.githubusercontent.com/5997512/56930344-33995600-6a91-11e9-957c-ee6623be0791.png)

This should take you to a page with a description or at least a readme.md in that folder.

**Comment by jameslew** [comment]
Link to content: https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-500-errors?view=azure-bot-service-4.0

**Comment by JonathanFingold** [comment]
Updated the link to point to: https://github.com/Microsoft/AI/blob/master/docs/analytics/README.md
