### ISSUE TITLE
[Bug Bash] In the Deploy your bot section the password requirements are not clear

### ISSUE THREAD

**Issue by CezaryMarcjan** [MicrosoftDocs/bot-docs#1093]
In https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&branch=pr-en-us-1325&tabs=newrg

The password requirements include:
"... must contain at least 1 upper or lower case alphabetical character, ..."

Should this be:
this: "... must contain at least 1 upper and lower case alphabetical character, …"
or this: "... must contain at least 1 alphabetical character, …"

Can the "alphabetical character" be simply "letter"?

**Comment by CezaryMarcjan** [comment]
Also, what is a "special character" in the password requirements? are all "characters" allowed in the password?

**Comment by stevengum** [comment]
> _this: "... must contain at least 1 upper and lower case alphabetical character, …"_

This is the correct statement. For special characters we'd have to verify with the AD team.

FWIW, here's what I received when I tested with a bad password:
```bash
C:\>az ad app create --display-name hellow --password 222222
The password must be at least 16 characters long, contain at least 1 upper or lower case alphabetical
character, and contain at least 1 special character. paramName: PasswordCredentials, paramValue: ,
objectType: Microsoft.Online.DirectoryServices.Application
```

**Comment by Kaiqb** [comment]
Updated the description to match error message. Fixed.

**Comment by yugangw-msft** [comment]
I can confirm the error message communicates the right policy which is being enforced on Microsoft.com tenant
