### ISSUE TITLE
Bugbash: Still point people to the Channel Inspector on the troubleshooting page

### ISSUE THREAD

**Issue by jameslew** [MicrosoftDocs/bot-docs#1094]
**Describe the bug**
The Channel Inspector has been deprecated as should this reference be in the documentation.

![image](https://user-images.githubusercontent.com/5997512/56930495-b7ebd900-6a91-11e9-9fc4-8a5443976aed.png)

https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-bot-configuration?view=azure-bot-service-4.0&branch=pr-en-us-1325

**Comment by JonathanFingold** [comment]
This now points to our channel reference in the resources section.
