### ISSUE TITLE
Bugbash: Sending people to dev.botframework.com on general troubleshooting page

### ISSUE THREAD

**Issue by jameslew** [MicrosoftDocs/bot-docs#1095]
**Describe the bug**
We should send customers to the azure portal for configuration settings, not the Dev.botframework.com portal.

![image](https://user-images.githubusercontent.com/5997512/56930853-efa75080-6a92-11e9-883c-abcb4b3507cf.png)

https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-general-problems?view=azure-bot-service-4.0&branch=pr-en-us-1325

**Comment by DanDev33** [comment]
fixed along with issue #1098
