### ISSUE TITLE
Bugbash: Assume FAQ reference about state store is no longer valid

### ISSUE THREAD

**Issue by jameslew** [MicrosoftDocs/bot-docs#1097]
**Describe the bug**
We have an FAQ about the state store in the troubleshooting guide that's no longer valid as we no longer support the state store.

![image](https://user-images.githubusercontent.com/5997512/56931138-d81c9780-6a93-11e9-9616-efbcb3191d2a.png)

Article link: 

https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-general-problems?view=azure-bot-service-4.0&branch=pr-en-us-1325#is-there-a-limit-on-the-amount-of-data-i-can-store-using-the-state-api

**Comment by DanDev33** [comment]
removed
