### ISSUE TITLE
Bugbash: Two references to dev.botframework.com on Troubleshooting pagethat are no longer valid

### ISSUE THREAD

**Issue by jameslew** [MicrosoftDocs/bot-docs#1098]
**Describe the bug**
On the troubleshooting page: https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-general-problems?view=azure-bot-service-4.0&branch=pr-en-us-1325

We have multiple references to dev.botframework.com that should be the Azure portal.  Note, this is limited to the first two cases; the migration case is still valid.

**Comment by DanDev33** [comment]
Fixed 3 instances.
