### ISSUE TITLE
Retrieve or create necessary IIS/Kudu files: Need to add more information on requirements (must be run inside project folder, etc)

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/bot-docs#1099]
Consult with Steven - this command should be run in a specific project folder afaik. 
Documentation should lead the user to not get into error path.

**Comment by Kaiqb** [comment]
This is a dupe of another issue that you raised. Corrected the instruction to indicate that the user needs to be **in** the folder before zipping the file.
