### ISSUE TITLE
[BugBash] ConversationUpdate is NOT sent for channels

### ISSUE THREAD

**Issue by EricDahlvang** [MicrosoftDocs/bot-docs#1100]
**Describe the bug**
The image on https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&branch=pr-en-us-1325&tabs=csharp shows two conversationUpdate activities.  One for the channel, and one for the bot.  However, the channel does not join the conversation, only the bot and the user.

**Expected behavior**
The graphic should how the bot ConversationUpdate, and the user ConversationUpdate.  There is no channel ConversationUpdate.

**Screenshots**
![image](https://user-images.githubusercontent.com/11055362/56931167-f84c5680-6a93-11e9-9276-a584c6f4d8e8.png)

**Additional context**
This is important, considering the historical level of confusion around ConversationUpdate.

**Comment by JonathanFingold** [comment]
Fixed in the MVC branch.
