### ISSUE TITLE
BugBash: Multiple instances of Bot Framework should be Azure Bot Service on this page

### ISSUE THREAD

**Issue by jameslew** [MicrosoftDocs/bot-docs#1101]
**Describe the bug**
https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-identifiers-guide?view=azure-bot-service-4.0&branch=pr-en-us-1325

We are referring to Bot Framework; but the place they registered their bot is the Azure Bot Service.  Anywhere we talk about portals and registration in the present tense should be Azure Bot Service now.

**Comment by DanDev33** [comment]
changed portal and registration Bot Framework references to Azure Bot Service
