### ISSUE TITLE
REST Params for Conversation Creation are incorrect

### ISSUE THREAD

**Issue by jmnsf** [MicrosoftDocs/bot-docs#1105]
The [Create a Conversation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#create-conversation) endpoint mentions that the body for the request should be a [Conversation object](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#conversation-object). In turn, this object mentions having an `activity` object in it which contains a `channelData` object in it. This is incorrect, as the `channelData` object should be at the top level of the body request.

Sending the request as described in these docs results in a 400 error:
```json
{"error":{"code":"BadSyntax","message":"Could not parse tenant id"}}
```

[Related docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#example) for the Microsoft Teams API have a working example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36ddb50-9e44-96e3-2df3-174166efa75d
* Version Independent ID: 68ac4b64-6616-2216-3519-e0b33d3a53e4
* Content: [API reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by v-kydela** [comment]
Hi @jmnsf 

I just opened a related issue: https://github.com/MicrosoftDocs/bot-docs/issues/1214

I believe there is no such thing as a `Conversation` object and that it should say `ConversationParameters` instead

**Comment by JonathanFingold** [comment]
This body should be a `ConversationParameters` object. I'll update the documentation presently.

**Comment by JonathanFingold** [comment]
This is fixed in a PR and will go live soon.

**Comment by jmnsf** [comment]
Thanks @JonathanFingold 👌
