### ISSUE TITLE
How to use emulator now.bot files are gone ? 

### ISSUE THREAD

**Issue by cxputcm** [MicrosoftDocs/bot-docs#1106]
Hi,

How am i supposed to use the emulator now that.bot files are gone ? , many thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f67913-4b16-2967-6044-4feb7be1f99b
* Version Independent ID: e3d2800a-d7b7-da55-4399-9586deaf4c9e
* Content: [Test and debug bots using the Bot Framework Emulator - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-debug-emulator.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-debug-emulator.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
Install the latest [release version](https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.3.3) of the emulator.
