### ISSUE TITLE
Sample completely out of date

### ISSUE THREAD

**Issue by JohnGalt1717** [MicrosoftDocs/bot-docs#1108]
Just as the title says. It uses Bot Framework v3, no updated to V4 code and the sample in question is overly complex.

Given that this is a basic function, this sample needs to be updated to V4 immediately and simplified massively.  This should be part of the core Azure Bot Service samples as well.

Further there is no example code of relying messages, adding a new user to a conversation etc., all of which should be directly on the text of this article not just dumping the user into an out-of-date sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 818b8a18-3321-4f50-f2e3-3d254806c958
* Version Independent ID: 0514154e-5d18-19fd-58e2-ec356509b19e
* Content: [Transition conversations from bot to human - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-handoff-human?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-design-pattern-handoff-human.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-pattern-handoff-human.md)
* Service: **bot-service**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by JohnGalt1717** [comment]
And the sample is NODE only. C# is a first class citizen and there should be a C# sample.

**Comment by Kaiqb** [comment]
Please open this issue in the [Bot Builder Samples repo](https://github.com/Microsoft/BotBuilder-Samples/issues).
