### ISSUE TITLE
sample in GitHub not found

### ISSUE THREAD

**Issue by Wobyn** [MicrosoftDocs/bot-docs#1109]
The Knowledge Bot sample in GitHub (https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/20.qna-with-appinsights) was not found in GitHub (3 May 2019)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d57659-6fcb-285c-0b26-06dc8fed57e3
* Version Independent ID: 1f53c0e8-d310-acc9-e023-98ee0111ef31
* Content: [Design knowledge bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-knowledge-base?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-design-pattern-knowledge-base.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-pattern-knowledge-base.md)
* Service: **bot-service**
* Sub-service: **cognitive-services**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by Kaiqb** [comment]
Fixed.

**Comment by Kaiqb** [comment]
Fixed
