### ISSUE TITLE
Incomplete instructions

### ISSUE THREAD

**Issue by kaushalgautam** [MicrosoftDocs/bot-docs#1110]
In the tutorial to deploy a basic bot, it's mentioned to use the yeoman generator to generate a bot but there is no deploymentTemplates folder that was created. What do I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg#additional-information)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
Did you update yeoman and generator-botbuilder? Content and the templates were just released last night, and they should all have deploymentTemplates. Creating one this morning based off those new bits worked as expected.

Could you verify which version of generator-botbuilder you have?

**Comment by kaushalgautam** [comment]
Yes! I updating yeoman and generator-botbuilde solved it for me. But for some reason, I can't publish the app to azure now. That's for a different channel though. Thanks for your help @ivorb
