### ISSUE TITLE
Please update to use the new App registrations panel

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1111]
The steps described in this article apply to App registrations (legacy)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp%2Cbot-oauth#feedback)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by v-kydela** [comment]
Actually it looks like only the Azure AD v1 steps apply to App registration (legacy). I'm not sure what the Azure AD v2 steps refer to, but it's not the current design.

**Comment by v-kydela** [comment]
![image](https://user-images.githubusercontent.com/41968495/57152179-9dfb1080-6d87-11e9-8606-a8bae91d7cc9.png)

There is no "Add an App," no "Application Secrets," no "Generate Password," no "Platforms," and no "Add Platform"

![image](https://user-images.githubusercontent.com/41968495/57152317-00541100-6d88-11e9-81b7-be795b60e8c2.png)

**Comment by JonathanFingold** [comment]
Looks like Azure updated their interface. I'll review and update the article.

**Comment by JonathanFingold** [comment]
Quick update. A draft of the updated article is in review and should go live in a couple days. I'll close this issue when the associated PR is pushed.

**Comment by JonathanFingold** [comment]
The updated article is live. Please open a new issue if the new article has any flaws.
