### ISSUE TITLE
Bot ARM deployment: Need a message about missing capabilities (in progress)

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/bot-docs#1112]
A couple of Bot Service ARM deployment capabilities are missing
* Arm template export is missing bot service resources
    * Consider alternative. E.g. in the meantime export, edit as follows (or we don’t have a workaround at the moment)?
* Service update via Arm template is not working. In the meantime, please use az cli commands to update Azure resources.

Related:  BUG 29052.

**Comment by Kaiqb** [comment]
@scheyal - not clear what the ask is here. Could you submit a PR with the changes you'd like to see?

**Comment by Kaiqb** [comment]
Closing per email conversation w/ Eyal.
