### ISSUE TITLE
Did you have this message??

### ISSUE THREAD

**Issue by mtmoreiranovabase** [MicrosoftDocs/bot-docs#1113]
I made the deploy tutorial and in the step where i deploy code to Azure with a zip

az webapp deployment source config-zip --resource-group "<new-group-name>" --name "<name-of-web-app>" --src "code.zip"

i think i made everything right and these step gave a error.

![image](https://user-images.githubusercontent.com/50206696/57168752-1d75f780-6dfb-11e9-8ef5-9a2762704e43.png)

i try to run that command but it doesnt help

![image](https://user-images.githubusercontent.com/50206696/57168808-6d54be80-6dfb-11e9-8ef1-79f9f4476b4e.png)

**Comment by Kaiqb** [comment]
@mtmoreiranovabase - when you zip the files, you need to be inside the folder that has .csproj file or index.js. That where you need to select all the files and zip them.

**Comment by DanDev33** [comment]
Closing this on the assumption that Kamran's solution solved your issue. (building your zip file at the same level as the .csproj file)
