### ISSUE TITLE
Telemetry sample links are dead.

### ISSUE THREAD

**Issue by kaushalgautam** [MicrosoftDocs/bot-docs#1115]
Samples cannot be found. Can you please update the samples for telemetry, app insights in Node? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db892de5-e60e-1d4f-505b-11b1cdb73323
* Version Independent ID: f7263014-b8fa-9a20-71aa-e4217b2821ee
* Content: [Add telemetry to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0&tabs=javascript#feedback)
* Content Source: [articles/v4sdk/bot-builder-telemetry.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-telemetry.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by kaushalgautam** [comment]
@DanDev33, any update on this? This page needs to be updated too, with complete documentation for Node, in a proper and informed way.

**Comment by ivorb** [comment]
We're actively working on making this page more useful, including a sample. Stay tuned

**Comment by kaushalgautam** [comment]
@ivorb, any timeframe? We are counting on it.

**Comment by jttaynton** [comment]
@ivorb - any samples/examples in node for adding app insights logging would be great.  I have tried adding it and I am getting an error - this.telemetryClient.trackEvent is not a function

**Comment by kaushalgautam** [comment]
@ivorb, been 2 months. Any progress?

**Comment by kaushalgautam** [comment]
@ivorb, we need the examples in this page in Node as well. Can this be taken up now? It's been too long.

**Comment by Kaiqb** [comment]
The updated content on Telemetry is [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0). Note that we only have C# sample at this time.

**Comment by kaushalgautam** [comment]
@Kaiqb, that's not fair. The framework supports both languages. Why not update the Node samples and guide? I refuse to close this issue. Please push for it, we have been waiting for too long to have you just remove it altogether.
