### ISSUE TITLE
Node JS documentation missing. 

### ISSUE THREAD

**Issue by kaushalgautam** [MicrosoftDocs/bot-docs#1116]
@ivorb, when is this getting done? It's been on the backlog for 3 months, considering that it is one of the most important parts of a product that is being widely used, it should be taken up on priority. Not to mention that MS has stable releases for only Node and C#, out of which a lot of documentation for Node is absent. Please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 409c8f0a-6388-574b-5443-a09c160962a7
* Version Independent ID: efc9e777-18e8-bcf2-204e-b395ce2e9f90
* Content: [Implement custom storage for your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-custom-storage?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-custom-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-custom-storage.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
@kaushalgautam , the dev team has not implemented the JavaScript version of the sample yet. You can open an issue in the [BotBuilder-Samples](https://github.com/Microsoft/BotBuilder-Samples) repo to request that they expedite this.

**Comment by Shon-Elias** [comment]
@kaushalgautam  
any update?
