### ISSUE TITLE
Mismatch between values in CLI man page and documentation

### ISSUE THREAD

**Issue by os2tux** [MicrosoftDocs/bot-docs#1118]
In the section "Retrieve or create necessary IIS/Kudu files" it specifies that you can use Typescript or Javascript as arguments to the --lang flag:

>Retrieve or create necessary IIS/Kudu files

>For C# bots
>cmd

>az bot prepare-deploy --lang Csharp --code-dir "." --proj-file-path "MyBot.csproj"

>You must provide the path to the .csproj file relative to --code-dir. This can be performed via the 
>--proj-file-path argument. The command would resolve --code-dir and --proj-file-path to >"./MyBot.csproj"

>For JavaScript bots
>cmd

>az bot prepare-deploy --code-dir "." --lang Javascript

>This command will fetch a web.config which is needed for Node.js apps to work with IIS on Azure App >Services. Make sure web.config is saved to the root of your bot.

>For TypeScript bots
>cmd

>az bot prepare-deploy --code-dir "." --lang Typescript

>This command works similarly to JavaScript above, but for a Typescript bot.

This is not correct, as the help page for the  --lang flag states: 

`[joseph@epiphytelcl ~]$ az bot prepare-deploy --help`

`Command
    az bot prepare-deploy : Add scripts and configuration files to your local source code directory
    to be able to publish back using `az webapp deployment source`

`Arguments
    --lang [Required] : The language or runtime of the bot.  Allowed values: Csharp, Node.`

Running the command as specified in the documentation results in the following behavior:

`[joseph@epiphytelcl ~]$ az bot prepare-deploy --code-dir "." --lang Typescript
az bot prepare-deploy: 'Typescript' is not a valid value for '--lang'. See 'az bot prepare-deploy --help'.
[joseph@epiphytelcl ~]$ az bot prepare-deploy --code-dir "." --lang Javascript
az bot prepare-deploy: 'Javascript' is not a valid value for '--lang'. See 'az bot prepare-deploy --help'`

Proposed Solution: 

Please update the documentation to reflect the values of the CLI man page, or update the code to reflect the documentation
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
@os2tux - what is the version of az cli you are using?

**Comment by os2tux** [comment]
Iqbal:

I’m using v2.0.63 of the Azure CLI. Please let me know if you need anything else from me regarding this.

Thanks!

PS /home/joseph> az --version
azure-cli                         2.0.63 *

Respectfully,

Joseph Shelby

Sr. DevOps Engineer, EPS/Platform Architecture
zoom: https://asurion.zoom.us/my/joseph.shelby | slack: @jcshelby
voice: 615.445.1240 | mobile: 615.210.6139
mail: Asurion I 648 Grassmere Park, Nashville, TN 37211
www.asurion.com<http://www.asurion.com/> I Twitter<https://twitter.com/Asurion> I Facebook<https://www.facebook.com/Asurion>

**Comment by nstejaswini** [comment]
@os2tux You should be using 2.0.64 version of azure cli to use TyepScript and JavaScripts with prepare-deploy command.

**Comment by ivorb** [comment]
@os2tux For updates of the man page (which I agree should list all available languages, and give more information than you were receiving). Would you log an issue with the [az cli](https://github.com/Azure/azure-cli/issues)? Feel free to also mention the issues you have with versioning numbers etc.

Once the CLI info matches what we have, it should be much clearer for users. Thanks for the feedback!
