### ISSUE TITLE
How to reference services after migration from .bot file to appsettings?

### ISSUE THREAD

**Issue by michaelbrunner** [MicrosoftDocs/bot-docs#1119]
We use a master-child bot pattern. Until now we registered the childbots as generic services in the .bot file. The Bot Configuration handled parsing of services very well.
What is the best way to register childbots (or services in general) with the new approach?

**Comment by ivorb** [comment]
Try taking a look at this article: https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp. Should cover what you're interested in?

**Comment by michaelbrunner** [comment]
Thanks for this hint, but I know this page. It doesn't cover my question. We used the services in the bot file to register childbots at a masterbot.
The Bot Framework parsed the entries under services and put it into a collection, where we can easily loop over child bot registrations. This approach is very dynamic. I don´t have to parse by hand and don't have to use fix config keys.
This is what I miss in approach with appsettings. Appsettings could do this in the same way, but I miss framework helpers to handle dynamic configs.

**Comment by Kaiqb** [comment]
I am not aware of any other solution that's similar to what bot file offered.
