### ISSUE TITLE
New NuGet package does not work on Mac

### ISSUE THREAD

**Issue by alopix** [MicrosoftDocs/bot-docs#1121]
When trying to use the new Speech connector it's not possible to develop the bot in VisualStudio running on macOS. It worked on Windows.
Cannot copy the Error as VS does not allow that on macOS either and I will not type 100 lines of error stacktrace…

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0b8671-359e-6026-fd3a-39331cea73f3
* Version Independent ID: 29bab4ad-243a-fb0a-99ed-d8336a92f648
* Content: [Develop DirectLine Speech Bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0#option-2-update-your-net-core-bot-code-if-your-bot-uses-addbot-and-usebotframework-instead-of-a-botcontroller)
* Content Source: [articles/directline-speech-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/directline-speech-bot.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by alopix** [comment]
![image](https://user-images.githubusercontent.com/124467/57290913-4ece1c00-70b6-11e9-99e3-d5c81c36986e.png)

**Comment by JonathanFingold** [comment]
@alopix , for Bot Framework SDK issues or suggestions, please open an issue in the [botframework-sdk](https://github.com/microsoft/botframework-sdk) repo.
