### ISSUE TITLE
Subscription ID did not work for me. I had to use the use the cognitive services key since I've only one subscription

### ISSUE THREAD

**Issue by avidunixuser** [MicrosoftDocs/bot-docs#1126]
**Describe the bug**
Addiging Intent using **your-cognitive-services-subscription-id** did not work.
"dispatch add -t qna -i "knowledge-base-id" -n "knowledge-base-name" -k "your-cognitive-services-subscription-id --intentName q_sample-qna"

If failed with the following exception -

QnA kb id:4a8fc4e5-6a7b-4c8f-b71d-183a45182b36, name:kfqna, subscription key:0c9ca8c4-a7be-4a66-a8b2-10b180fc0ca9 added to luis.dispatch
Exporting services for dispatch...
Exporting Weather LUIS application...
Exporting Home Automation LUIS application...
Exporting kfqna QnA kb...

ERROR
One or more errors occurred. (The remote server returned an error: (401) Access Denied.)

Request url: https://westus.api.cognitive.microsoft.com/qnamaker/v4.0/knowledgebases/4a8fc4e5-6a7b-4c8f-b71d-183a45182b36/Test/qna
Response: { "error":{ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }}
------
I instead used cognitive services key to make it work.

"dispatch add -t qna -i "knowledge-base-id" -n "knowledge-base-name" -k "your-cognitive-services-key --intentName q_sample-qna"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by DanDev33** [comment]
Thank you for your feedback. I have changed our documentation to now describe this key as: 
"qna-maker-resource-key" throughout the article. This matches the QnA Maker documentation and should avoid future confusion. This update will be available online in the near future.
