### ISSUE TITLE
Documentation doesn't match up with current azure behaviour

### ISSUE THREAD

**Issue by kaushalgautam** [MicrosoftDocs/bot-docs#1128]
Instead of 5 resources, only three are created in Azure when you follow the guide for Javascript/Node (idk if it's the same for C#).
Application Insights and Storage account are not created. Would be nice to know how to integrate App Insights and how to use it now that it's not being created by default. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp%2Cnewrg)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by nstejaswini** [comment]
@kaushalgautam In the new version SDKv4 only three resources will be created for bot C# and JS. The app insights will be created if you turn it on while creating the bot.
![Screenshot (116)_LI](https://user-images.githubusercontent.com/39872221/57690820-2ae37b00-7660-11e9-85f4-1bc08be84dc2.jpg)

**Comment by kaushalgautam** [comment]
@nstejaswini, but we made/deployed the bot using azure cli. The document doesn't require us to go to the azure portal.

**Comment by nstejaswini** [comment]
@kaushalgautam You mentioned that "Instead of 5 resources, only three are CREATED in Azure when you follow the guide for Javascript/Node (idk if it's the same for C#)."  Using Azure cli or VS or azure portal only three resources will be deployed by default for the new version.

**Comment by kaushalgautam** [comment]
@nstejaswini, It is to be noted that this is a v4 guide that follows the creation/deployment procedure using CLI. I understand your input, but then the documentation should be changed to state the same. Since it still says (Under heading "Additional Resources") that 5 resources are created when we deploy the bot.

**Comment by ivorb** [comment]
Added to private, will be pushed live shortly

**Comment by kaushalgautam** [comment]
@ivorb, thanks!
