### ISSUE TITLE
After AUTH_PROMPT step, the next step is not executed

### ISSUE THREAD

**Issue by yaleidong** [MicrosoftDocs/bot-docs#1129]

**Comment by yaleidong** [comment]
followed the steps prescribed in docs and downloaded code and filled out .env. When testing in Emulator, the login prompts and then pick up an account, seems signed in, but the next step is NOT executed. there is NO "You are now logged in".

**Comment by nstejaswini** [comment]
@yaleidong Can you please explain more about the issue you are facing, such as in which sample you are facing the error and during which step etc.

**Comment by Kaiqb** [comment]
closing issue due to lack in activity. feel free to reopen if needed.
