### ISSUE TITLE
Link for  "add the bot to the Cortana channel" links to a non-existant page

### ISSUE THREAD

**Issue by rbnswartz** [MicrosoftDocs/bot-docs#1130]
In the sample for the roller bot it has a link for "add the bot to the Cortana channel" that points to https://aka.ms/bot-cortana-channel which gives a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6675779-4a28-8783-ac2a-4f7bd1c1c3ce
* Version Independent ID: 72850126-f113-7ee3-eb94-0d329fb27e19
* Content: [Build a Cortana skill using .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-cortana-skill?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-cortana-skill.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-cortana-skill.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kaiqb**

**Comment by DanDev33** [comment]
Hi Reuben,
Thanks for your feedback! I have changed this link to point to the correct page.
