### ISSUE TITLE
Please add information for the target "signInAudience" in the app manifest, if choosing "common" as the TenantId

### ISSUE THREAD

**Issue by afrischk** [MicrosoftDocs/bot-docs#1131]
Please lose some words on the "signInAudience" in the app manifest file. If you choose "common" in the bot OAuth Connection Settings as TenantId, I expect the "signInAudience" to be at least "AzureADMultipleOrgs" in the app manifest file during the creation of the app registration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp%2Cbot-oauth#feedback)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
With the recent change in how to register an Azure AD app, the guidance will no longer suggest the use of the common tenant. This change to the doc should go live in a couple days.
