### ISSUE TITLE
Insufficient privileges to complete the operation.

### ISSUE THREAD

**Issue by brynetwork** [MicrosoftDocs/bot-docs#1133]
I'm getting this error while following "Create an App registration" process.
What account privileges do I need to continue the deployment process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg#create-an-app-registration)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
Have you made sure you're logged into Azure, and the subscription is set? Do you have access to that subscription to add services? You can log into the [Azure portal](https://portal.azure.com/) and try to create an app registration manually to test it out if you aren't sure.

**Comment by brynetwork** [comment]
Yes. I already login in and set the subscription but I still get this error.

I already tried also creating the bot in the azure portal; it works fine.
Is there a way to update the source code I created in the azure portal to the source code that I created locally? I think this will a better solution to my problem, since the resource is already created using the azure portal.

**Comment by ivorb** [comment]
Curious why you're getting the error, especially if it works through the portal just fine, but yes - you can update the code there with your local bot. Try skipping the steps in the deployment article where you create the bot in Azure, and just prepare your deployment, zip it up, and deploy it into the resource you already created via the portal

**Comment by brynetwork** [comment]
Thanks
