### ISSUE TITLE
Visual Studio 2019?

### ISSUE THREAD

**Issue by JohnStraumann66** [MicrosoftDocs/bot-docs#1134]
Hi: Any chance you folks could update this content for VS 2019? I ran the VSIX file, but do not see the "Bot Framework" project types when I start Visual Studio?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Framework SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by nstejaswini** [comment]
@JohnStraumann66 Please reinstall the VSIX file, and restart the system. Then you will be able to find the new bots framework in VS2019 as in the picture.
![Screenshot (114)](https://user-images.githubusercontent.com/39872221/57687470-1d76c280-7659-11e9-98f2-2ea08dfa96f8.png)

**Comment by ivorb** [comment]
If that doesn't fix it for you @JohnStraumann66 do let us know.

**Comment by JohnStraumann** [comment]
> If that doesn't fix it for you @JohnStraumann66 do let us know.

Nope, no joy.

**Comment by nstejaswini** [comment]
@JohnStraumann66 Did you follow the steps given above and check?

**Comment by JohnStraumann** [comment]
> @JohnStraumann66 Did you follow the steps given above and check?

Yes of course I did, did the steps twice. No luck. I'll try again one more time tomorrow morning as I m travelling today.

**Comment by nstejaswini** [comment]
> @JohnStraumann66 Did you follow the steps given above and check?
> 
> Yes of course I did, did the steps twice. No luck. I'll try again one more time tomorrow morning as I m travelling today.

Okay. Then please check if you have selected the required resources while installing the VS2019. You can view it in the VS installer->modify. If not, please install them. And also check the version of VS, if it is 16.0.3 or above. If not please update it. Let me know if it works after trying the above.
![Screenshot (117)](https://user-images.githubusercontent.com/39872221/57849600-4d5ccc00-77f9-11e9-93b6-c668c9dd350e.png)

**Comment by JohnStraumann** [comment]
Well for some reason installing and restarting a 2nd time did it, I think I am good. Thank you for the replies!

**Comment by nstejaswini** [comment]
@JohnStraumann Glad to know it is working for you.

**Comment by JohnStraumann** [comment]
> @JohnStraumann Glad to know it is working for you.

Do you know of a more extensive tutorial that builds on this one and creates a real conversational bot?
