### ISSUE TITLE
"Managa a bot" still references the bot file

### ISSUE THREAD

**Issue by Andrea-Orimoto** [MicrosoftDocs/bot-docs#1135]
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-overview?view=azure-bot-service-4.0

![image](https://user-images.githubusercontent.com/17152540/57544596-a239a780-730c-11e9-8a7d-f83a9c83219b.png)

**Comment by ivorb** [comment]
fixed in private, will be published soon
