### ISSUE TITLE
Need a new (or updated) doc that explains how to create the MIcrosoft App Id and Password in the Azure portal

### ISSUE THREAD

**Issue by Andrea-Orimoto** [MicrosoftDocs/bot-docs#1136]
We will soon change the all links in the UX from the old app registration portal, to the new registration flow in Azure, so the docs should be updated accordingly. I can help if needed.

We need a page that clearly explains how to create the App Id and how to create the Secret (Password). Also, it should highlight that the user HAS to chose "Accounts in any organizational directory and personal Microsoft accounts (e.g. Skype, Xbox, Outlook.com)", when creating the app, otherwise the bot won't work. 
![image](https://user-images.githubusercontent.com/17152540/57544948-b8943300-730d-11e9-99fd-26b897e626b9.png)

In our docs I only found this page that needs changing, not sure if there are others.
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-3.0&viewFallbackFrom=azure-bot-service-4.0#bot-channels-registration-password

As a reference, the Azure documentation on this is
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app
https://docs.microsoft.com/en-us/azure/active-directory/develop/app-registrations-training-guide#keyscertificates--secrets

**Comment by jiruss** [comment]
We need to get this change documented ASAP please.

**Comment by mmiele** [comment]
Andrea, could you please review the updated article staged at this location: [ Register a bot with Azure Bot Service](https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-3.0&branch=pr-en-us-1647)? Please, make sure that the description about appId and appSecret is correct?

**Comment by Andrea-Orimoto** [comment]
@mmiele where can I add my comments? is there  Pull Request I can look at?

**Comment by mmiele** [comment]
Andrea, this is the PR: https://github.com/MicrosoftDocs/bot-docs-pr/pull/1647. 
Thanks

**Comment by mmiele** [comment]
Fixed affected article.
