### ISSUE TITLE
Typo in Deploy via ARM template (with existing Resource Group) command snippet

### ISSUE THREAD

**Issue by dmvtech** [MicrosoftDocs/bot-docs#1139]
Missing a quote before location in the appServicePlanLocation parameter.

appServicePlanLocation=&lt;location&gt;"

Should be:

appServicePlanLocation="&lt;location&gt;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=erg#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
Fixed, will be pushed live shortly. Thanks!
