### ISSUE TITLE
luisResult.ConnectedServiceResult return null

### ISSUE THREAD

**Issue by jok-gf** [MicrosoftDocs/bot-docs#1140]
Hi, I have followed instructions to use Dispatch using C# (DotNet@2.2.204 and botdispatch@1.4.5)
I have published the dispatch model JSON  (section --> Create the dispatch model, step --> 6) but when I tried to request it, I am not getting ConnectedServiceResult attribute in the response, see response below:
```
{
  "query": "whats the weather in redmond washington",
  "topScoringIntent": {
    "intent": "l_Weather",
    "score": 0.9999997
  },
  "intents": [
    {
      "intent": "l_Weather",
      "score": 0.9999997
    },
    {
      "intent": "l_HomeAutomation",
      "score": 5.263155E-07
    },
    {
      "intent": "None",
      "score": 7.7E-09
    },
    {
      "intent": "q_sample-qna",
      "score": 6.090909E-10
    }
  ],
  "entities": [
    {
      "entity": "redmond washington",
      "type": "Location_PatternAny",
      "startIndex": 21,
      "endIndex": 38,
      "role": ""
    }
  ]
}
```
That response is causing null reference in code (ProcessHomeAutomationAsync method).

Do I need additional steps for associate child Luis models with parent(dispatch) or am I missing something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by shankarvrp1** [comment]
I have the same problem as well with the sample no.14. Here is the result with ConnectedServiceResult as **null**

{
  "luisResponse": {
    "alteredQuery": null,
    "compositeEntities": null,
    "connectedServiceResult": null,
    "entities": [],
    "intents": [
      {
        "intent": "l_Weather",
        "score": 0.9567824
      },
      {
        "intent": "l_HomeAutomation",
        "score": 0.0269946959
      },
      {
        "intent": "q_sample-qna",
        "score": 0.007982737
      },
      {
        "intent": "None",
        "score": 0.002110852
      }
    ],
    "query": "will it rain this weekend",
    "sentimentAnalysis": null,
    "topScoringIntent": {
      "intent": "l_Weather",
      "score": 0.9567824
    }
  }
}****

**Comment by DanDev33** [comment]
I am wondering if this is somehow a versioning problem. Is your code built using nuget packages:
Microsoft.Bot.Builder   v4.4.3  ?
Microsoft.Bot.Builder.AI.Luis  v4.4.3  ?
The Raw Response I receive back from Luis begins as follows:
{
  "luisResponse": {
    "alteredQuery": null,
    "compositeEntities": null,
    "connectedServiceResult": {
      "alteredQuery": null,
      "compositeEntities": null,
      "connectedServiceResult": null,
      "entities": [
        {
          "endIndex": 11,
          "entity": "rain",
          "score": 0.9989228,
          "startIndex": 8,
          "type": "condition"
        },
        {
          "endIndex": 22,
          "entity": "seattle",
          "score": 0.9998036,
          "startIndex": 16,
          "type": "location"
        }
      ],

Notice that there is a curly brace around the outer connectedServiceResult,
"connectedServiceResult": {
So everything inside this brace, including the entities and intents that were returned, would be included when the following call was made by method ProcessHomeAutomationAsync( )

var result = luisResult.ConnectedServiceResult;

I do not see that inclusive curly brace, or in the first example, even a connectedServiveResult at all. So either:
1. Luis is returning a malformed response (less likely).
2. The Luis response is not being properly processed (a version mismatch could cause this).

Please take a look at your nuget packages in your code and let me know if this is possibly the problem.

**Comment by jok-gf** [comment]
Hi @DanDev33,
I am using following nuget packages:
Microsoft.Bot.Builder v4.4.3
Microsoft.Bot.Builder.AI.Luis v4.4.3
You're right, I am not receiving connectedServiceResult property in raw response at all.

**Comment by jok-gf** [comment]
I have tested the same code and I am getting the connectedServiceResult property in the json response. I did not change anything in my code, probably some issues with LUIS service but they are fixed now, thanks!

**Comment by xtianus79** [comment]
Haha I knew it. Try hard coding the new LuisApplication configuration settings with the strings from the applicationsettings.json file.  See if that fixes the issue.  I am having a very similiar issue that is related to this.

**Comment by duvarajan** [comment]
I too have the same error. I too get null. I'm using Microsoft.Bot.Builder.AI.Luis v4.6.3. By the way how to get the raw response of the result in JSON as someone ("DanDev33") has given earlier. I generated JSON file using Dispatch command and imported to LUIS. Please help me to fix the issue. Its bit Urgent!

**Comment by duvarajan** [comment]
I too have the same error. I too get null. I'm using Microsoft.Bot.Builder.AI.Luis v4.6.3. By the way how to get the raw response of the result in JSON as someone ("DanDev33") has given earlier. I generated JSON file using Dispatch command and imported to LUIS because "Dispatch Create" command was throwing error. Please help me to fix the issue. Its bit Urgent!
