### ISSUE TITLE
QnA maker resource key does not work in dispatch command.

### ISSUE THREAD

**Issue by rp-dev** [MicrosoftDocs/bot-docs#1142]
Using the &lt;qna-maker-resource-key&gt; from 'Authorization: EndpointKey &lt;qna-maker-resource-key&gt;' does not work in dispatch command. It gives the following error: 
{ "error":{ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }}

Need to use the key from 'CognitiveServices' resource and it was a guid without dashes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by nstejaswini** [comment]
@rp-dev In the command "dispatch add -t qna -i "<knowledge-base-id>" -n "<knowledge-base-name>" -k "<qna-maker-resource-key>" --intentName q_sample-qna"  
The "qna-maker-resource-key" will be found in Keys section under Cognitive Services in Azure(from the qnamaker you created) as you said.

If you get the error because of using the wrong value, please delete the .dispatch file and the folder named "data" that got created. Then run all the commands again "dipatch init" and the three "dispatch -add" for successful deployment.

**Comment by rp-dev** [comment]
I meant that the qna-maker-resource-key from Postman sample did not work.

**Comment by rp-dev** [comment]
Documentation seemed to suggest that it'd work.

**Comment by nstejaswini** [comment]
@rp-dev In the appsettings.json/.env file, for QnAAuthKey="<qna-maker-resource-key>", give the value from the deployment details after publishing your KB, that is Authorization: EndpointKey: <value>. If you give the key value from Cognitive resources, it won't work.

**Comment by DanDev33** [comment]
Our docs were updated to clear up this issue, but this has not yet gone live. Here is the pertinent info taken from this doc update:

QnAKnowledgebaseId: The knowledge base ID that the QnA Maker portal generated for you.
QnAAuthKey: The endpoint key that the QnA Maker portal generated for you.
QnAEndpointHostName: The host URL that the QnA Maker portal generated. Use the complete URL, starting with https:// and ending with /qnamaker. The full URL string will look like "look like "https://< >.azure.net/qnamaker".

We are working to get this article updated online. Please let me know if this does NOT address your issue.

**Comment by DanDev33** [comment]
The updated articles describing exactly which key to use, and when, is scheduled to go live today.
Thanks for your feedback.
