### ISSUE TITLE
Channel Support

### ISSUE THREAD

**Issue by michaelbrunner** [MicrosoftDocs/bot-docs#1144]
In your documentation you mention that postBack is not supported by all channels. I miss an overview to channel/feature support matrix. 
E.g. when I look at the Facebook Channel integration, I can nothing find about postBack support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b809442-7e1a-0186-e59b-0e4d587104ac
* Version Independent ID: 694d8c3e-37f8-100e-cffa-1634b883b3dc
* Content: [Add suggested actions to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-suggested-actions?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/nodejs/bot-builder-nodejs-send-suggested-actions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-send-suggested-actions.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by ivorb** [comment]
While it doesn't cover postBack directly (each channel implements that differently), is this article what you're looking for?

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0
