### ISSUE TITLE
Basic structure of a Bot project.

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/bot-docs#1147]
A month ago, I wrote a C# Bot with v4.3. It was with a `.bot` file, and the [`AddBot`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.integration.aspnet.core.servicecollectionextensions.addbot?view=botbuilder-dotnet-stable#Microsoft_Bot_Builder_Integration_AspNet_Core_ServiceCollectionExtensions_AddBot__1_Microsoft_Extensions_DependencyInjection_IServiceCollection_System_Action_Microsoft_Bot_Builder_Integration_BotFrameworkOptions__) extension method.

Now, I see there is a change in v4.4, and I looking for documentation for that, but I can't find.

If I open the EchoBot template with Visual Studio 19, I see a different structure than I know. I notice that in version 4.4 the bot is back under the normal controller.
Where is there an explanation for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp%2Cnewrg)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
There is an explanation in the [Manage bot resources](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp) article.
