### ISSUE TITLE
No way to download bot code despite documentation indicating that I should do that

### ISSUE THREAD

**Issue by Diruuo** [MicrosoftDocs/bot-docs#1150]
**Describe the bug**
The expected way to download bot code via Azure is nowhere to be found, despite what the documentation claims at https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp The Build: button in the Bot Channels Registration does nothing and the Build Section on the left is nowhere to be seen. The "wwwroot" (the whole web app) can be downloaded via Kudu but that does not produce the result that the documentation talks about. I get the exact same empty appsettings.json file that I have locally. 

**To Reproduce**
1. Look at any bot channels registration associated with a live App Service
2. Observe that clicking on the "Build:" button does nothing.
3. Download via Kudu, observe that appsettings.json is not populated as the documentation describes

**Expected behavior**
As per the documentation this action should allow me to download the bot's code or at least provide some descriptive error explaining why I can't interact with this section of the Bot registration at all. 

Also the documentation about transferring from one method of working (.bot files) to another (appsettings/.env) should be more clearer. I see no issue with the team just providing an example appsettings.json file with all of the relevant entries, even if it is self-explanatory and straight forward. But there's still msbot documentation everywhere that makes no mention of the deprecation of the .bot files and the documentation indicating how to adjust your project is inaccurate.

1. Documentation should be corrected and should be more detailed. 
2. There should be examples of the current recommended way of working the same way there was a plainly defined .bot file back in the day. In fact, there is still a fully defined sample bot file in the botbuilder-tools repo. https://github.com/microsoft/botbuilder-tools/blob/master/packages/MSBot/docs/sample-bot-file.json. The closest I got was the one in the NLP-with-Dispatch sample. That still does not have all entries that I would expect. 
3. If there is no longer an encryption mechanism for these keys that should be mentioned somewhere. I haven't been able to find anything to replace the encryption of .bot files. 

Ultimately the change simplifies management of bots and provides a more standard way of defining services, but the transition and documentation is not of the standard that I would expect.

**Comment by DanDev33** [comment]
Hi Stefan,
Would you please check if this is still the case? I encountered a similar situation several days ago, but now the Build option seems to have been restored as well as the online code editor that I noticed had previously been removed. We will add a deprecation warning concerning this to the docs, but at the moment this functionality seems to have returned.
Please let me know if you to are seeing this restored functionality. And thanks for you feedback!

**Comment by Diruuo** [comment]
The Build button still does nothing for me. I don't see the online code editor anywhere either. 

Just to make sure we're on the same page - we're talking about the Build button within the bot channels registration associated with a specific messaging endpoint/bot? So a bot channels registration that corresponds to a live bot hosted in an App Service? 

It's a bit bizarre to me that I would download the code through that instead of through the app service that is the actual deployment, but I believe this is what the above documentation instructed me to do. 

I'm still a little lost as to what the documentation intends me to do and I've been working with the Bot Framework and the Azure deployments for a while now. I can't imagine how this is for people less familiar with the process.

**Comment by DanDev33** [comment]
I'm glad you asked that question Stephan. We were in fact talking about different Azure interfaces. I began by creating a new resource "Web App Bot" not a new "Bot Channels Registration." Build works properly for the Web App Bot, but it appears to do nothing for a new Bot Channels Registration. The current documentation found here: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0 , has you create a Web App Bot which can be downloaded with username & password values from Azure. 
If you start from a local sample and then follow the deployment steps here, https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg , this produces a Web App Bot that can viewed with the online code editor and down loaded again with username and password using Build.
I will look into why using a bot channels registration is not providing you with this same download capability from Azure.

**Comment by DanDev33** [comment]
This issue has been raised with our development team.

**Comment by DanDev33** [comment]
Azure team is fixing functionality of the Build button associated with a Bot Channels Registration. Thanks for helping us uncover this issue.
