### ISSUE TITLE
ChoicePrompt with ActionCards

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/bot-docs#1152]
[Original issue](https://github.com/MicrosoftDocs/msteams-docs/issues/656).

I would like more detailed documentation regarding the proper use of `ChoicePrompt` with `ActionCards`.

There seems to be a duplicate when `Choice` contains an `ActionCard`, and it seems that their behavior is unpredictable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9577ff-cf56-e5de-84c3-bfe10aab5368
* Version Independent ID: b5d62753-f87b-4673-b09b-a5a3fd9360e8
* Content: [Reuse dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-compositcontrol.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-compositcontrol.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by baruchiro** [comment]
From original issue:

Sure. I remember this from V4.3, but I can't find the code right now.

![image](https://user-images.githubusercontent.com/17686879/57921862-104f1300-78a7-11e9-87c1-61cd937bb062.png)

![image](https://user-images.githubusercontent.com/17686879/57921963-47252900-78a7-11e9-9ffd-a2b00b4a56e0.png)

I used "very very" because a one "very" is still a card.

JSON for the short message:

``` json
{
  "attachments": [],
  "channelId": "emulator",
  "conversation": {
    "id": "3e91a080-7a59-11e9-b27e-b7f2dc2a2f8f|livechat"
  },
  "entities": [],
  "from": {
    "id": "2",
    "name": "Bot",
    "role": "bot"
  },
  "id": "4279fe40-7a59-11e9-99a0-d9c48d8a8fbc",
  "inputHint": "acceptingInput",
  "localTimestamp": "2019-05-19T20:12:19+03:00",
  "locale": "",
  "recipient": {
    "id": "d1ff7fc6-7de6-4208-bed8-0dd025aaaa26",
    "role": "user"
  },
  "replyToId": "4240ece0-7a59-11e9-99a0-d9c48d8a8fbc",
  "serviceUrl": "https://a943a825.ngrok.io",
  "suggestedActions": {
    "actions": [
      {
        "title": "short title",
        "type": "imBack",
        "value": "recommendations"
      }
    ]
  },
  "text": "Hi, select what you want",
  "timestamp": "2019-05-19T17:12:19.748Z",
  "type": "message"
}
```

JSON for the long title:
``` json
{
  "attachments": [],
  "channelId": "emulator",
  "conversation": {
    "id": "9476c340-7a59-11e9-b916-434698c80b5d|livechat"
  },
  "entities": [],
  "from": {
    "id": "2",
    "name": "Bot",
    "role": "bot"
  },
  "id": "9a384dd0-7a59-11e9-a6cb-c56ac337ce96",
  "inputHint": "acceptingInput",
  "localTimestamp": "2019-05-19T20:14:46+03:00",
  "locale": "",
  "recipient": {
    "id": "d1ff7fc6-7de6-4208-bed8-0dd025aaaa26",
    "role": "user"
  },
  "replyToId": "99fea030-7a59-11e9-a6cb-c56ac337ce96",
  "serviceUrl": "https://8b80b63c.ngrok.io",
  "text": "Hi, select what you want\n\n   1. A very very long title",
  "timestamp": "2019-05-19T17:14:46.956Z",
  "type": "message"
}
```

And this is how I create the `PromptOptions` dialog:

``` csharp
internal PromptOptions CreateChoicesPromptOptions(string text, IDictionary<string, string> keyToTitle)
{
    return new PromptOptions
    {
        Prompt = MessageFactory.Text(text),
        Choices = keyToTitle.Select(v =>
            new Choice(v.Key)
            {
                Action = new CardAction(ActionTypes.ImBack, v.Value, value: v.Key)
            })
            .ToList()
    };
}
```

**Comment by JonathanFingold** [comment]
I'm not sure I understand your issue. Does the following information help?

If you make this change in the C# [05.multi-turn-prompt](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/05.multi-turn-prompt) sample:

In **.\Bots\DialogBot.cs**, line 37

```csharp
AddDialog(new ChoicePrompt(nameof(ChoicePrompt)) { Style = ListStyle.List });
```

The bot formats the choice as a list:
![image](https://user-images.githubusercontent.com/35047199/58115802-b5236600-7baf-11e9-8559-4256ada11107.png)

**Comment by baruchiro** [comment]
But even I set `Style = ListStyle.SuggestedAction`, **if the choices are too long**, it will be shown as a list.

**Comment by JonathanFingold** [comment]
I understand that the documentation on how to use prompts is not complete.

What behavior are you trying to get from the choice prompt? Are you trying to force it to always use suggested actions?

**Comment by JonathanFingold** [comment]
Closing. Please reopen if the issue still exists.
