### ISSUE TITLE
ZipDeploy step

### ISSUE THREAD

**Issue by AAATechGuy** [MicrosoftDocs/bot-docs#1154]
Provide exact command line to help zip binaries... 

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=erg#zip-up-the-code-directory-manually

In the attached link, you are talking about how to deploy zip, but, not how to create zip!!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=erg#zip-up-the-code-directory-manually)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by nstejaswini** [comment]
@AAATechGuy How to zip the folder is given right below "Zip up the code directory manually" section under IMPORTANT header. It says that, you need to zip the folder that contains the .csproj file for C# bots and app.js/index.js file for JS bots.

**Comment by DanDev33** [comment]
On a Windows 10 machine: 
1. use File Explorer to move to the appropriate folder.
2. select all files.
3. Right Click with your Mouse and choose "Send To", Compressed (zipped) folder.
4. Choose a name and location for your new zipped file.
For other OS versions, Google "How to create a zip file for ___ "

**Comment by AAATechGuy** [comment]
Thanks!

You could just re-write as... 

```
Zip all files in your project folder.  (this direct statement is missing, in my opinion)

Important!
Before zipping your project files, make sure that you are in the correct folder.
```

@nstejaswini 
it doesn't say ... "you need to zip the folder that contains the .csproj file for C# bots and app.js/index.js file for JS bots." it says "Before zipping your project files, make sure that you are in the correct folder". That's where the confusing part is, I guess.

**Comment by nguyenlamlll** [comment]
I fell into the same trap... I did not know what to zip.

The document is confusing indeed. In my opinion, the two sections `Retrieve or create necessary IIS/Kudu files` and `Zip up the code directory manually` need some rephrasing works.

- Firstly, the part saying `Kudu assumes by default that deployments from zip files are ready to run and do not require additional build steps during deployment` makes me feel like I should publish my project to binaries.

- Secondly, there is a part which says `As such, it is important to include your built code`. We usually refer `built code` to what lies inside `bin` directory, or at least with the publish output of `dotnet publish`, not the entire project. 


Another minor point: `Retrieve or create...` section does not point out that a `.deployment` file will be created. This might be confusing for newcomers.
