### ISSUE TITLE
REST API:  Create Conversation , Can provide a demo?

### ISSUE THREAD

**Issue by XimenaWang** [MicrosoftDocs/bot-docs#1155]
![image](https://user-images.githubusercontent.com/30890958/58090280-baff5400-7b7b-11e9-8017-ec5a0ce1e260.png)
I can't correctly fake the "Conversation" object , so always receive error 400, can you provide one, Thanks!

"error": {

		"code":   "BadSyntax",

		"message":   "Incorrect conversation creation parameters"

	}

**Comment by JonathanFingold** [comment]
In general, the service generates the conversation object for you. What is the scenario you are trying to support?

**Comment by Kaiqb** [comment]
Closed due to lack of activity.
