### ISSUE TITLE
Zip deployment failing 

### ISSUE THREAD

**Issue by cxputcm** [MicrosoftDocs/bot-docs#1157]
Hi, Im having to run az webapp log tail as my zip deployment is failing with no error message - can you advise why ? i've executed the last command in the list as stated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp%2Cnewrg)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by nstejaswini** [comment]
@cxputcm It might be because of not zipping the files properly or not giving the proper path directory in console when you run the az webapp command. 
Make sure that you 
1) zip all the project files with .deployment/web.config file ( select all the files-> right click-> send to->compressed(zipped) folder->name the zipped file)
2) In console before giving the az webapp command make sure you are pointing to the directory where zipped folder is present.
For example,
In the screen shot the path(as the zipped file is present in this location) present in the address bar is the path to be given in the console before running the az webapp command. 
![Screenshot (123)](https://user-images.githubusercontent.com/39872221/58227601-15014480-7d49-11e9-888e-50dfcfd816f7.png)

**Comment by ivorb** [comment]
@cxputcm please let us know if that didn't work.

**Comment by MisinformedDNA** [comment]
I'm running into this issue as well:

> C:\Repos\example> az webapp deployment source config-zip --resource-group "XXXX" --
> name "XXXX" --src "code.zip"
> Getting scm site credentials for zip deployment
> Starting zip deployment. This operation can take a while to complete ...
> Configuring default logging for the app, if not already enabled
> Zip deployment failed. {'id': '2575a831561a4f8c95f4d583a2cf7338', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2019-06-03T18:43:28.9250029Z', 'start_time': '2019-06-03T18:43:30.5498265Z', 'end_time': '2019-06-03T18:44:17.7345699Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://XXXX.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://XXXX.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'XXXX', 'provisioningState': None}. Please run the command az webapp log tail
>                            -n XXXX -g XXXX
> 
> C:\Repos\example> ls code.zip
> 
> 
>     Directory: C:\Repos\example
> 
> 
> Mode                LastWriteTime         Length Name
> ----                -------------         ------ ----
> -a----         6/3/2019   1:41 PM        1428755 code.zip
>

**Comment by cxputcm** [comment]
hi both, sorry for the wait, i'll try now

**Comment by nstejaswini** [comment]
@MisinformedDNA Did you follow the above prescribed steps to zip you code and where to run the az webapp command?

**Comment by Kaiqb** [comment]
Please feel free to re-open if the issue is still happening.

**Comment by GitDruid** [comment]
Hi,
I'm facing the same issue while redeploying a bot.
First deploy worked well. Then I made some changes to the dialog logic and now the deploy does not work anymore.

az webapp deployment source config-zip --resource-group "MyResourceGroup" --name "YYYApp" --src "./YYY.zip"

Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
Configuring default logging for the app, if not already enabled
Zip deployment failed. {'id': 'XXX', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'ZipDeploy', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2020-06-26T13:17:55.9723541Z', 'start_time': '2020-06-26T13:17:57.3346388Z', 'end_time': '2020-06-26T13:18:02.3108777Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://YYY.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://YYY.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'YYY', 'provisioningState': None}. Please run the command az webapp log deployment show
                           -n YYYApp -g MyResourceGroup

**Comment by LeThai98** [comment]
> @cxputcm It might be because of not zipping the files properly or not giving the proper path directory in console when you run the az webapp command.
> Make sure that you
> 
> 1. zip all the project files with .deployment/web.config file ( select all the files-> right click-> send to->compressed(zipped) folder->name the zipped file)
> 2. In console before giving the az webapp command make sure you are pointing to the directory where zipped folder is present.
>    For example,
>    In the screen shot the path(as the zipped file is present in this location) present in the address bar is the path to be given in the console before running the az webapp command.
>    ![Screenshot (123)](https://user-images.githubusercontent.com/39872221/58227601-15014480-7d49-11e9-888e-50dfcfd816f7.png)

Yeah. Thank you very much. I success with your instruction
