### ISSUE TITLE
CreateReply is only available on ITurnContext

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/bot-docs#1161]
It should be noted that `CreateReply` only exists on the base interface `ITurnContext`. If you have `ITurnContext&lt;T&gt; turnContext`, you will need to cast it to `ITurnContext` to work.

```csharp
protected override async Task OnMembersAddedAsync(IList&lt;ChannelAccount&gt; membersAdded, ITurnContext&lt;IConversationUpdateActivity&gt; turnContext, CancellationToken cancellationToken)
{
    // var reply = turnContext.Activity.GetReply();  // won't compile
    var reply = (turnContext as ITurnContext).Activity.GetReply();  // compiles
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 607856cb-baae-c401-5b34-876b5018771d
* Version Independent ID: 77df1de7-7b2e-a546-1280-a66121039a94
* Content: [Add media to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-add-media-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-media-attachments.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
@MisinformedDNA , can you provide more context? I can't find in this article the code that you cite.

Also, you mention the `CreateReply` method, but the code snippet uses a non-existent `GetReply` method.

**Comment by JonathanFingold** [comment]
PS. With a given turn, the `Activity` property of `ITurnContext<T>` and `ITurnContext` should return the same object.

**Comment by JonathanFingold** [comment]
Please reopen if you need more help with this issue.

**Comment by MisinformedDNA** [comment]
The linked article says

> The Attachments property of the Activity object contains an array of Attachment objects that represent the media attachments and rich cards attached to the message. To add a media attachment to a message, create an Attachment object for the reply activity (that was created off the activity with CreateReply()) and set the ContentType, ContentUrl, and Name properties.

And you said 

> the `Activity` property of `ITurnContext<T>` and `ITurnContext` should return the same object.

Not true. `ITurnContext` returns an `Activity` and `ITurnContext<T>.Activity` returns T, where T must inherit from `IActivity`, but not necessarily from `Activity`.

Since `CreateReply` is defined on `Activity and not on `IActivity`. `ITurnContext<T>` cannot (always) access `CreateReply` through the `Activity` property unless `ITurnContext<T>` or `T` are cast to a type that inherits from `Activity`.

The reason I ran into this is because the EchoBot sample (generated from Azure Portal) uses `ITurnContext<T>` where T is always an interface.
