### ISSUE TITLE
Connecting to telephony

### ISSUE THREAD

**Issue by Unders0n** [MicrosoftDocs/bot-docs#1162]
Would be cool to have examples of how to connect direct line speech to some telephony, Twilio for example. thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0b8671-359e-6026-fd3a-39331cea73f3
* Version Independent ID: 29bab4ad-243a-fb0a-99ed-d8336a92f648
* Content: [Develop DirectLine Speech Bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0)
* Content Source: [articles/directline-speech-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/directline-speech-bot.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Unders0n** [comment]
@ivorb any updates on that? also please check this thread : https://stackoverflow.com/questions/56340032/is-new-ms-botbuilder-directline-speech-good-fit-for-call-center-scenario/56482584#56482584

**Comment by Kaiqb** [comment]
There is some work we are doing to enable a bot receive phone calls, but that is still being designed and not available for consumption.
