### ISSUE TITLE
Training Dispatcher and other skill specific LUIS models

### ISSUE THREAD

**Issue by aforank** [MicrosoftDocs/bot-docs#1170]
Please describe the best practices to review endpoint utterances if we have a dispatcher and multiple skill specific LUIS models. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by DanDev33** [comment]
Hi Ankit,
There are several ways to do this. (I'm using the code DispatchBot.cs from Sample 14.nlp-with-dispatch as an example)  While debugging you can set a breakpoint on each call to OnMessageActivityAsync( ) and look at the value passed in from turnContext.Activity.Text.  This should contain the utterance that was passed in from your user. When running, you could use the _logger.LogInformation( ) to write each of these utterances into your log, preserving a record you can then go back and review. 

Of course beyond this you could create a more elegant solution that captured and wrote all user utterances out to their own file for later review, but the steps above should easily provide you with access to all of your users' utterances as they are received.
