### ISSUE TITLE
Update command for IIS/Kudu for Javascript Node

### ISSUE THREAD

**Issue by dmvtech** [MicrosoftDocs/bot-docs#1171]
az bot prepare-deploy --code-dir "." --lang JavaScript

doesn't work. 

Seems like it needs to be:
az bot prepare-deploy --code-dir "." --lang Node

which worked for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=erg)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by nstejaswini** [comment]
@dmvtech Please update you az cli version to 2.0.64. Then you will be able to use JavaScript with prepare-deploy command.
Sometimes the update might not work, so please uninstall and reinstall the az cli and make sure your az cli version is updated( you can input the command "az --version" in your console).
