### ISSUE TITLE
ARM template creates a Bot Channels Registration

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/bot-docs#1173]
I created two bot systems, one via the ARM template (which I got from a new VS bot project) and one via the Azure Portal. The one created via the ARM template gave me (among other services) a "Bot Channels Registration" service. The one created via the portal gave me a "Web App Bot" service instead of the "Bot Channels Registration". Why are these different? Is the ARM template wrong?

![image](https://user-images.githubusercontent.com/1784452/58644802-a3387600-82c7-11e9-9a35-b7672a8283ca.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Consolidated with Issue #1150.
