### ISSUE TITLE
Unable to send a reply in a teams channel via Rest

### ISSUE THREAD

**Issue by Alexp2019** [MicrosoftDocs/bot-docs#1176]
**Describe the bug**
Receive an Error 401: "message":"Authorization has been denied for this request."}
When trying to post a conversation.

Im also unable to get conversations, I receive 401's on this also.

 I am able to write messages in teams other situations. i.e. using session.send.
When trying via the API I receive the 401. 

The ServiceURL is:https://smba.trafficmanager.net/au/
I
I have tried both these URL's
https://smba.trafficmanager.net/au/v3/conversations/19:thread/activities/replytoID
"https://smba.trafficmanager.net/au/v3/conversations/19:threadid@thread.skype;messageid=msgid/activities

TOken Permissions:
`["Chat.UpdatePolicyViolation.All",
    "Calls.JoinGroupCall.All",
    "OnlineMeetings.Read.All",
    "OnlineMeetings.ReadWrite.All",
    "User.ReadWrite.All",
    "Application.ReadWrite.OwnedBy",
    "People.Read.All",
    "Application.ReadWrite.All",
    "Calls.InitiateGroupCall.All",
    "Group.Read.All",
    "Calls.JoinGroupCallAsGuest.All",
    "Sites.Read.All",
    "Sites.ReadWrite.All",
    "Group.ReadWrite.All",
    "Sites.Manage.All",
    "User.Invite.All",
    "User.Read.All",
    "Chat.Read.All",
    "ChannelMessage.Read.All",
    "User.Export.All",
    "Chat.ReadWrite.All",
    "ChannelMessage.UpdatePolicyViolation.All",
    "Member.Read.Hidden",
    "Calls.AccessMedia.All",
    "Sites.FullControl.All",
    "Calls.Initiate.All"`
Thanks

**Comment by mdrichardson** [comment]
This sounds like it's possibly a [TrustServiceUrl Issue](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp#avoiding-401-unauthorized-errors) (despite the 500 vs 401 error message).

You can fix it by adding all of your ServiceUrls to the list of trusted URLs:

```
private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
{
     var activity = await result as Activity;
     var serviceUrl = activity.ServiceUrl;
     MicrosoftAppCredentials.TrustServiceUrl(serviceUrl);
     var reply = activity.CreateReply();
     reply.Text = "Hi there";
     await context.PostAsync(reply);
}
```

This should ensure that your bot "trusts" the ServiceUrl of any message that it receives.

Let me know how that goes. I'm 90% sure this is the issue, but it might not be.

**Comment by CoHealer** [comment]
Resolving as closed. @Alexp2019, if this does not address your issue feel free to reopen.
