### ISSUE TITLE
The functionality just doesn’t make sense, (Add natural language understanding to your bot)

### ISSUE THREAD

**Issue by babak-kobari** [MicrosoftDocs/bot-docs#1177]
**Describe the bug**
Here is the conversation detail between me and the bot. you can test it yourself
Me: Hello
Bot: What can I help you with today? Say something like “Book a flight from Paris to Berlin on March 22, 2020”
Me: How are you
Bot: **Where would you like to travel to?** _(The response is wrong as the intent is not "Book_flight"_
Me: How is the life?
Bot: **Where are you traveling from?** _(The response is wrong as the airport entity is not recognized, it deal with LUIS and recheck the entry within the dialog)_
...

According to me, the sample is just useful to understand how to connect to LUIS and making a helper to quarry from it, but the flow of Dialog and how to use the returned value from LUIS just makes no sense

**Comment by ivorb** [comment]
Which sample are you running? I agree, this doesn't seem useful from the dialog standpoint, even if it does show how to connect to LUIS we should have a logical dialog structure.

**Comment by babak-kobari** [comment]
I ran "Add natural language understanding to your bot"  with [this ](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=csharp) link

**Comment by Kaiqb** [comment]
You should look at the dialog topics that cover more complex conversations.
