### ISSUE TITLE
"Get conversations" documentation missing

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1179]
The "get conversations" API is documented in the SDK reference for .NET and Node.

.NET: https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.connector.conversationsextensions.getconversationsasync
Node: https://docs.microsoft.com/en-us/javascript/api/botframework-connector/conversations?view=botbuilder-ts-latest#getconversations-conversationsgetconversationsoptionalparams-

It should be in the REST API reference as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36ddb50-9e44-96e3-2df3-174166efa75d
* Version Independent ID: 68ac4b64-6616-2216-3519-e0b33d3a53e4
* Content: [API reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-3.0#conversation-operations)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
@v-kydela - please submit a PR with the fix.

**Comment by v-kydela** [comment]
While investigating this, I've just discovered that "Delete Conversation Member" and "Send Conversation History" are also missing so I will also include those in the PR
