### ISSUE TITLE
Tool for codeMap/codeDiagram

### ISSUE THREAD

**Issue by AviralGarg1993** [MicrosoftDocs/bot-docs#1181]
What tool was used to create these codeMap/codeDiagram (Javascript)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 534e4b75-75fe-bdf9-5978-e75852a66390
* Version Independent ID: 92b81bb4-b10c-ca88-ed2f-a1537f460075
* Content: [Send welcome message to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=javascript#feedback)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DanDev33
* Microsoft Alias: **v-dashel**

**Comment by JonathanFingold** [comment]
We use nomnoml markup to generate the JavaScript diagrams.
