### ISSUE TITLE
[minor] typo `inindex.js` should be `in index.js`

### ISSUE THREAD

**Issue by AviralGarg1993** [MicrosoftDocs/bot-docs#1182]
here: https://docs.microsoft.com/en-us/azure/bot-service/migration/javascript-migration-quickreference?view=azure-bot-service-4.0#v4-3

(in javascript section)
`inindex.js` should be `in index.js`

Preview:
![image](https://user-images.githubusercontent.com/12901566/58842926-2c7fdd80-8625-11e9-9b8f-b8971790d54a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dc19058-d861-8d28-f14f-98517058c9a3
* Version Independent ID: b913f984-fe7d-b88f-2435-a8b097cb7b04
* Content: [JavaScript v3 to v4 migration quick reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/migration/javascript-migration-quickreference?view=azure-bot-service-4.0#v4-3)
* Content Source: [articles/v4sdk/migration/javascript-migration-quickreference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/migration/javascript-migration-quickreference.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
Thanks. Fix is in a pull request and should go live soon.
