### ISSUE TITLE
Is it possible to assign a task to bot from Planner. And update the task progress details/notifications from bot to teams app.  

### ISSUE THREAD

**Issue by joicepj11** [MicrosoftDocs/bot-docs#1183]

**Comment by Kaiqb** [comment]
Take a look at the proactive [topic ](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp)to see if it helps.

**Comment by joicepj11** [comment]
Can you give some simple example for this?
