### ISSUE TITLE
Choice based dialog bot with luis

### ISSUE THREAD

**Issue by jnaman509** [MicrosoftDocs/bot-docs#1185]
how we can create choice based or confirm option based dialog bot with luis integration. because when i am integrating luis in choice based dialog bot it again checks the data on luis. so how i can disable luis until one dialog bot conversation ends and when new conversation start then luis enable using node js and sdk version 4.

**Comment by nstejaswini** [comment]
@jnaman509 Can you please specify you doubt in detail? And which document are you referring?

**Comment by jnaman509** [comment]
i want to create dialog bot integrated with luis. when a user search any information firstly it search on luis and after matching intent it call dialog bot class so that conversation will start and when conversation end and user search a new intent then it will again call luis. i don't want luis interruption in between conversation flow.

**Comment by nstejaswini** [comment]
@jnaman509 I guess you are using the Core bot. I guess you can give a for/while logic with a count, where when exceeds 1 will no more hit the luis. And only when new conversation starts, it will hit the luis for the first time.

**Comment by DanDev33** [comment]
Looking at your question, I believe that you can find what you want using a combination of dialog branching and looping.
1. Upon receipt of information back from LUIS, branch your dialog control to a secondary step.
2. In the secondary step, (which does not call LUIS, loop until your user is finished.
3. Upon your user finishing, then use endDialog() to finish the dialog and the user turn logic.
The next user interaction will find the dialog stack empty and once again send a request off to LUIS.
Info on dialog branching and looping can be found here:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow?view=azure-bot-service-4.0&tabs=javascript#branch-and-loop

**Comment by DanDev33** [comment]
Closing this. Please reopen if our suggestions don't help you move forward.
