### ISSUE TITLE
System.ArgumentException: '"" is not a valid LUIS application id. 

### ISSUE THREAD

**Issue by jchen706** [MicrosoftDocs/bot-docs#1187]
Below is a sample of what I have. It says System.ArgumentException: '"" is not a valid LUIS application id. I don't know where to go next the Id is valid. I checked.

Dispatch = new LuisRecognizer(new LuisApplication(
                configuration["4c1921311xx2131321xxe-888-5485-xxxx-xxxxxxxxxxx"],
                configuration["xxxxxxxxxxxxxxxxxxxxx"],
                $"https://{configuration["westus"]}.api.cognitive.microsoft.com"),
                new LuisPredictionOptions { IncludeAllIntents = true, IncludeInstanceData = true },
                true);

**Comment by fullcapsbro** [comment]
what was the solution?
