### ISSUE TITLE
Please explain how to get reply variable before using it

### ISSUE THREAD

**Issue by AskYous** [MicrosoftDocs/bot-docs#1188]
I got really confused on where `reply` came from. I just came from the previous tutorial which doesn't have it, and it's not shown until the user scrolls down, so this confuses the user. I know the document says "reply activity (that was created off the **activity** with CreateReply())," but I didn't know where to get the **activity** from.

Also, I tried this, but it errored:

```
protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
{
     var reply = turnContext.Activity.CreateReply();
}
```
The error is:

> IMessageActivity' does not contain a definition for 'CreateReply' and no accessible extension method 'CreateReply' accepting a first argument of type 'IMessageActivity' could be found (are you missing a using directive or an assembly reference?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 607856cb-baae-c401-5b34-876b5018771d
* Version Independent ID: 77df1de7-7b2e-a546-1280-a66121039a94
* Content: [Add media to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-add-media-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-media-attachments.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by AskYous** [comment]
The documentation is confusing. It says to use the `Activity` object of the turn context and call `CreateReply()`, but that doesn't work because the data type of turn context is `ITurnContext<IMessageActivity>`. If the datatype is just `ITurnContext` without `<MessageFactory>`, I can then call `CreateReply()`.

But when I change the datatype to `ITurnContext`, a new error comes up, which is that then `OnMessageActivityAsync()` function doesn't have that call signature. So I can't actually change the datatype.

My colleague found a workaround, which is to cast the activity to another type: `var reply = ((Activity)context.Activity).CreateReply();`. Why does this work? Does this mean an `Activity` has the `CreateReply()` function but a `IMessageActivity` can't? It seems like a `IMessageActivity` does indeed have the `CreateReply()` function. But I don't know.

**Comment by JonathanFingold** [comment]
We didn't include the complete method body here, as we are referencing code from the [Handling Attachments](https://aka.ms/bot-attachments-sample-code) sample. For example, [OnMessageActivityAsync](https://github.com/microsoft/BotBuilder-Samples/blob/84e3c1622a272e99e1e1bf04bbf9268d5404cf8b/samples/csharp_dotnetcore/15.handling-attachments/Bots/AttachmentsBot.cs#L30-L37) and [ProcessInput](https://github.com/microsoft/BotBuilder-Samples/blob/84e3c1622a272e99e1e1bf04bbf9268d5404cf8b/samples/csharp_dotnetcore/15.handling-attachments/Bots/AttachmentsBot.cs#L82-L100) in the **Bots\AttachmentsBot.cs** file.

As to what's going on:

* The `Activity` class implements the `IActivity` interface.
* However, the `CreateReply` method is defined on the class, but not on the interface.
* I think this is a bug in the SDK, and I'll open an issue in the botbuilder-dotnet repository.

**Comment by JonathanFingold** [comment]
PS. Turns out both the samples and the documentation are out of date on this front. Hopefully, we'll get this sorted out by the next release. In the mean time, you can do something like the following:

```csharp
var reply = new Activity
{
    Type = ActivityTypes.Message,
    Text = "<replay message>",
    Attachments = new List<Attachment>
    {
        // Add attachments...
    },
};
```

**Comment by AskYous** [comment]
Thanks @JonathanFingold. We can use the example you provided in the meantime.
