### ISSUE TITLE
Insufficent instructions on ARM templating

### ISSUE THREAD

**Issue by jwiley84** [MicrosoftDocs/bot-docs#1190]
This doc assumes the user has a measure of knowledge on how ARM templates and deployments work. If they do not, it is very easy to get lost during a deployment, especially when errors are as short as 'Expecting value: line 1 column 1 (char 0)'. I recommend that we include a link near the top to "https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-overview" that explains how ARM templates and az CLI work under the hood. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Thanks for your feedback Jessica. We've added an Azure resource manager link into the article prereqs.
You should see this change the next time our documentation updates go live.
