### ISSUE TITLE
StateManagementBot.cs [!code-csharpOnTurnAsync] 

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/bot-docs#1191]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/bot-docs.zh-cn/issues/3

@SugarGuan commented yesterday
The code sample in the page is not loaded

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e18bc52f-7eaf-a473-1cba-9b7c83bd0025
* Version Independent ID: c1b6cf03-c236-cfbf-aa4b-96961b816bc3
* Content: [Save user and conversation data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by CeciAc** [comment]
They are referring this code which replicates in the localized versions:
![imagen](https://user-images.githubusercontent.com/26746247/59132294-32d6c800-894b-11e9-9222-b093e27447ec.png)

I asked the engineer team about this issue and they said: "this is a source issue that seems to be generated by side by side and the include's call."

**Comment by JonathanFingold** [comment]
@CeciAc , I'm not seeing this issue in the en-us version of the page. It renders like this (even after clearing my browser cache and refreshing the page.)

![image](https://user-images.githubusercontent.com/35047199/59214751-968c0b80-8b6c-11e9-8ef2-9bb28f5115bd.png)

Can you provide more context?

**Comment by JonathanFingold** [comment]
PS. The Markdown also looks clean:

```markdown
[!code-csharp[UserProfile](~/../BotBuilder-Samples/samples/csharp_dotnetcore/45.state-management/UserProfile.cs?range=7-11)]
```

**Comment by CeciAc** [comment]
Hi @JonathanFingold 
We investigated the issue with the engineer team and resolved the issue is still visible for localized versions becuase it was already fixed in the source but we update is still on queue and will be fixed then
I'm closing this issue an reopen the original to follow up from there.

thank you very much!
