### ISSUE TITLE
Typo in `bots/dialogWandWelcomeBot.js`

### ISSUE THREAD

**Issue by AviralGarg1993** [MicrosoftDocs/bot-docs#1192]
Should be `bots/dialogAndWelcomeBot.js`
![image](https://user-images.githubusercontent.com/12901566/59160922-b0582080-8a90-11e9-9f1f-487eb8a12382.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6606cce-8a4e-587b-ded2-bd775a4cd7c7
* Version Independent ID: 6f637bca-8cc0-a526-4cbd-9c5f9f94ca2b
* Content: [Create advanced conversation flow using branches and loops - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow?view=azure-bot-service-4.0&tabs=javascript#feedback)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
Thanks! Fixed in PR, should go live in a few days.
