### ISSUE TITLE
NextAsync(-1, cancellationToken)

### ISSUE THREAD

**Issue by babak-kobari** [MicrosoftDocs/bot-docs#1193]
NextAsync(-1, cancellationToken) 

It is mentioned in the [tutorial ](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)that -1 will skip the next step.

Unfortunately[ SDK reference manua](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.waterfallstepcontext.nextasync?view=botbuilder-dotnet-stable#Microsoft_Bot_Builder_Dialogs_WaterfallStepContext_NextAsync_System_Object_System_Threading_CancellationToken_)l doesn't have any explanation about anything on the possible options for the first parameters,
 Where can i find details about possible options of the first parameter

**Comment by JonathanFingold** [comment]
Fix in PR. Changes to the reference documentation should go live with the 4.5 release.
