### ISSUE TITLE
Use "you're" instead of your. 

### ISSUE THREAD

**Issue by roythompsonuno** [MicrosoftDocs/bot-docs#1194]
Original: 
"Automotive Industry: Voice enabled Personal Assistant integrated into the car providing end users the ability to perform traditional car operations (e.g. navigation, radio) along with productivity focused scenarios such as moving meetings when your running late"

Revise to: 
"Automotive Industry: Voice enabled Personal Assistant integrated into the car providing end users the ability to perform traditional car operations (e.g. navigation, radio) along with productivity focused scenarios such as moving meetings when you're running late"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 407d006a-ea07-e01e-ffe6-a424137b06d6
* Version Independent ID: 01c82543-c632-f008-a23f-e3f13eac88ff
* Content: [Virtual Assistant Overview - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-virtual-assistant-introduction?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/bot-builder-virtual-assistant-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-virtual-assistant-introduction.md)
* Service: **bot-service**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by emgrol** [comment]
Thanks for catching this error! The docs are now updated.
