### ISSUE TITLE
Is there a VS template to to build a bot for full .net framework

### ISSUE THREAD

**Issue by gregorvilkner** [MicrosoftDocs/bot-docs#1195]
Hi there, I need to reference some full .net resources (yes, sharepoint online csom sdk). Is there a way to get a bot going targeting full .net framework? All the VS templates target .net core I believe. Thanks and kind regards, Gregor

**Comment by JonathanFingold** [comment]
For now, we have one .NET Framework sample that you could repurpose, the [csharp_webapi/13.core-bot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_webapi/13.core-bot).

Let me know if this is sufficient. If not, I can flag this so someone in support can help out.

**Comment by gregorvilkner** [comment]
Ah. Perfect. I had overlooked that one in the repo. This should do the trick.Thank you very much. Kind regards,GregorOn Jun 12, 2019 6:23 PM, Jonathan Fingold <notifications@github.com> wrote:For now, we have one .NET Framework sample that you could repurpose, the csharp_webapi/13.core-bot.
Let me know if this is sufficient. If not, I can flag this so someone in support can help out.
