### ISSUE TITLE
Add V3 migration message to 'How Bot Works' page

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/bot-docs#1196]
### Add V3 migration page to 'How Bot Service Works' Page V3

Some other services such as Cortana point to the V3 page:
[How Bot Service works V3](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-readme?view=azure-bot-service-3.0)

Consider adding same message as in the below page to the page referenced above:

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-3.0

See for example referencing  page from Cortana:

https://docs.microsoft.com/en-us/cortana/skills/get-started

**Comment by DanDev33** [comment]
Thanks for your feedback. A migration document is currently being worked on that will do this.
