### ISSUE TITLE
Wrong *rg.json file name in cmd window

### ISSUE THREAD

**Issue by dargilco** [MicrosoftDocs/bot-docs#1197]
In "Option 2: New App Service Plan" in the cmd window is should say "template-with-new-rg.json" (instead of "template-with-preexisting-rg.json").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp%2Cerg#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by dargilco** [comment]
Also, instead of appServicePlanLocation it should be newAppServicePlanLocation. Otherwise I get an unrecognized template parameter error.

**Comment by nstejaswini** [comment]
@dargilco In Option 2 that is after creating an app registration, there are two tabs, one is for Deploy via ARM template(With new resource group) and the second tab for Deploy via ARM template( with existing resource group).
So, please make sure what you want to opt. If you want to use a new resource group, click the first tab or else the second one.

**Comment by dargilco** [comment]
Thank you, you are right about the resource group. My second comment about appServicePlanLocation being used instead of newAppServicePlanLocation still stands (under "New App Service Plan"), and I'll open a new comment on that one so I can close this issue.
