### ISSUE TITLE
Choice Prompts unable to provide choices in a card and button format.

### ISSUE THREAD

**Issue by Stikemanley** [MicrosoftDocs/bot-docs#1198]
**Issue**
In building a waterfall dialog, choice prompts are difficult for end users to understand and look unprofessional. Choices are only available to be shown in numbered lists or suggested actions. Suggested Actions look better, however, are unsupported in Microsoft Teams which is a major channel for our bot.

**Expected behavior**
I would like choices to be available in a card, similar to a hero/adaptive card. We do use these as a replacement to a choice prompt in many places, however we have to handle the response with middleware. It would be much preferable to be able to display choice prompt options in a card and button format.

**Comment by JonathanFingold** [comment]
To format a choice prompt as a hero card, use the `Style` property. When adding a choice prompt to a component dialog, for example:
```csharp
            AddDialog(new ChoicePrompt("my-id") { Style = ListStyle.HeroCard });
```

We are working on a topic that will cover prompts in more detail, but for now, let me know if this solves your problem.

**Comment by Stikemanley** [comment]
Hello,

Thank you for your response!

I'm coding my choice prompt as follows, can you help me implement your
suggestion?

this.addDialog(new ChoicePrompt('choicePrompt'){Style = ListStyle.HeroCard
});

this.addDialog(new WaterfallDialog('waterfallDialog', [
this.chooseDialog.bind(this),
this.gotoDialog.bind(this)
]))

this.initialDialogId = 'waterfallDialog'
} //this is the end of the constructor

async run(turnContext, accessor) {
const dialogSet = new DialogSet(accessor);
dialogSet.add(this);

const dialogContext = await dialogSet.createContext(turnContext);
const results = await dialogContext.continueDialog();
if (results.status === DialogTurnStatus.empty) {
await dialogContext.beginDialog(this.id);
}
}

async chooseDialog(step) {
console.log("STEP " + JSON.stringify(step.context))
let LUISResults = await this.luisRecognizer.recognize(step.context)
console.log("LUIS RESULTS: " + JSON.stringify(LUISResults,null,4))
let intentChoices = Object.keys(LUISResults.intents).slice(0,3)
let listChoices = []
for (var i in intentChoices) {
listChoices.push(GenUtils.intentArray[intentChoices[i]])
}
console.log('Intent Choices: ' + intentChoices)
console.log('List Choices ' + listChoices)
return await step.prompt('choicePrompt', {
prompt: "I'm not sure what you want to do, please type the number
cooresponding to what you'd like me to do",
choices: ChoiceFactory.forChannel(listChoices)
})

This is part of a Component Dialog.

Thank you!
Mike

**Comment by JonathanFingold** [comment]
The `ChoicePrompt` object that you added to the dialog takes care of recognizing the user's input and returning their selection. I'm not completely clear on what you're trying to do. It looks like you are running LUIS and asking the user to select from the top four recognized intents. Try updating your chooseDialog step to look something like this (the ChoiceFactory can take a list of strings or a list of `Choice` objects. See the ref topic on the [forChannel](https://docs.microsoft.com/en-us/javascript/api/botbuilder-dialogs/choicefactory?view=botbuilder-ts-latest#forchannel-string---turncontext--string---choice----string--string--choicefactoryoptions-) method for the correct parameter list.)

```JavaScript
async chooseDialog(step) {
    //...
    return await step.prompt('choicePrompt', {
        prompt: "I'm not sure what you want to do, please choose for this list:",
        choices: ChoiceFactory.forChannel('WebChat', intentChoices ),
    });
}
```

You would then retrieve the result in the following step:

```javascript
async gotoDialog(step) {
    const choice = step.result.value;
    // Determine which child dialog or process to start based on the result.
    return await step.beginDialog('<id-of-child-dialog-to-start>');
}
```

**Comment by JonathanFingold** [comment]
Closing for now. Please reopen if you're still having issues with this code.
