### ISSUE TITLE
Issue with Start the Emulator and connect your bot

### ISSUE THREAD

**Issue by erhopf** [MicrosoftDocs/bot-docs#1199]
In the section start the emulator and connect your bot, it doesn't say that you need to alter the url shown in the terminal. For example, the terminal says: restify listening to http://[::]:3978. If you add this to your configuration, you get issues where it thinks the bot is remote. If you change it to localhost:3978, it the remote error is resolved. However, the messages still don't work. It's only after you set the endpoint URL to localhost:3978/api/messages, that the echo bot works as designed. We should update the docs to provide additional details for setting this up. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c86f2-9c0d-015b-d44f-58914fed2deb
* Version Independent ID: 85fe7f0c-002a-e449-55cb-712d92874b19
* Content: [Create a bot using Bot Framework SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by nstejaswini** [comment]
@erhopf It is true that we need to specify that in http://[::]:3978 should be edited with localhost for javascript bots. The addition of /api/messages is specified in emulator where we give the bot url. And also if the format is wrong the emulator won't allow the user to connect to the bot.

**Comment by DanDev33** [comment]
Thanks for your feedback! This information was included in previous versions of the article.
We have added back the following detail to both the Dotnet & JavaScript quickstarts:
"Fill out the fields for your bot. Use your bot's welcome page address (typically http://localhost:3978) and append routing info '/api/messages' to this address."
This will become available once our latest document updates go live.
