### ISSUE TITLE
appServicePlanLocationshould be replaced by newAppServicePlanLocation.

### ISSUE THREAD

**Issue by dargilco** [MicrosoftDocs/bot-docs#1203]
In "Deploy via ARM template, with existing resource group", in the tab "Option 2: New App Service Plan", in the cmd window, appServicePlanLocationshould be replaced by newAppServicePlanLocation. Otherwise I get an unrecognized template parameter error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp%2Cerg#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by nstejaswini** [comment]
@dargilco Please update your azure cli version and check once. Let me know if that works.

**Comment by mmiele** [comment]
Made the requested changes. They can be found [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp%2Cerg#feedback).
