### ISSUE TITLE
We need to document that only 1 WebSocket per conversation is supported

### ISSUE THREAD

**Issue by Jeffders** [MicrosoftDocs/bot-docs#1204]
On this page about receiving activities:

https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-receive-activities?view=azure-bot-service-4.0

We need to add a statement to the 'Receive activities via WebSocket stream' section that says something like:

- There can only be 1 connected WebSocket per conversation.

**Comment by Jeffders** [comment]
Ah, we can also document that additional websockets might be closed by Direct Line with a reason value of 'collision'.

**Comment by JonathanFingold** [comment]
Added the following note just after the 2nd paragraph of the topic:

The service allows only 1 WebSocket connection per conversation. Direct Line may close additional WebSocket connections with a reason value of `collision`.

Changes should go live in a few days. Please reopen if I need to change the text.
