### ISSUE TITLE
authentication incorrectly spelled in navigation

### ISSUE THREAD

**Issue by pjsummersjr** [MicrosoftDocs/bot-docs#1205]
In the left-hand navigation, this section is spelled "User anthentication" rather than "User authentication".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf2089c-a313-0abf-2ed3-8d7db5c4f677
* Version Independent ID: f0b3a9ce-b1e3-7b3d-15a9-0b9e032aa4bd
* Content: [User authentication in the Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-authentication?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/bot-builder-concept-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-authentication.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
Thanks for catching that. I'll fix it presently. Changes should go live in a few days.
