### ISSUE TITLE
Followed steps, but am being blocked at the sign in step.

### ISSUE THREAD

**Issue by ding-harrison** [MicrosoftDocs/bot-docs#1207]
I've followed the tutorial on getting this to work, step by step. However, the extent of how much this authentication bot works stops after sending me the OAuthPrompt with the Sign In Card. When I click on the Sign in card, I get the login prompt, but after logging in, nothing happens. There is no response on logging in, and the bot no longer responds to anything as well.

Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp%2Cbot-oauth)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
I think you may have hit a [known bug](https://github.com/microsoft/BotFramework-Emulator/issues/1544) in the v4 Emulator. I'll try to get someone from support to help you out.

**Comment by hdg97** [comment]
@JonathanFingold Does Azure Bot Service have the same problem? I tried running the code on BotFramework Emulator v4.4.0, and things worked correctly, as per the suggestion on the bug post. 
However, deploying the app results in a similar problem, where I am unable to sign in through a chat service. In this case, I am using Teams. Is there something more I am supposed to do to enable authentication through teams? I have already added a connection in my deployed Bot Channels Registration, changed the microsoftAppId and MicrosoftAppPassword in the appsettings, and am able to get my Token through "Test Connection". 
Let me know if you have any documentation that I missed on deploying with authentication. I've already used the standard "Deploy to Azure" documentation that is given in the samples, but things don't seem to work.

Thanks.

**Comment by JonathanFingold** [comment]
I don't think the current authentication samples work correctly with Teams, but I'll need to do some research.

**Comment by JonathanFingold** [comment]
There is a planned Teams sample with authentication that may make it into the upcoming 4.5 release.

**Comment by hdg97** [comment]
So does the current authentication samples work for any chat services currently outside of the Bot emulator?

**Comment by jwiley84** [comment]
I regularly use Facebook when checking my OAuth settings, and I believe Slack works as well (and I believe it's faster to configure).

**Comment by JonathanFingold** [comment]
Web Chat also works, it is the channel the Emulator uses. I believe samples 18 and 24 should work for most channels other than Cortana and Teams.

**Comment by hdg97** [comment]
Using the Web Chat, the sample gives me this for the sign in Oauth Card:
[File of type 'application/vnd.microsoft.card.oauth']

Can't click on it to log in. Is there another webchat you are talking about other than the one that is on the Bot Channels Registration?

Will give Slack a try though.

**Comment by JonathanFingold** [comment]
I was thinking of [embed the web chat control in a website](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0#embed-the-web-chat-control-in-your-website), but I have not tried to do so with either of the auth samples.

**Comment by jwiley84** [comment]
@hdg97 How are you using webchat? The 'Test in WebChat' option in Azure does not work, as it uses a different version of webchat.

**Comment by ltwlf** [comment]
In the emulator you have to configure ngrok and to uncheck "Bypass ngrok for local address".

**Comment by CoHealer** [comment]
@jwiley84, do you have an update?

**Comment by jwiley84** [comment]
@ding-harrison Are you still having this issue?

**Comment by ding-harrison** [comment]
@jwiley84 So I am currently able to use Slack to test my application, since the OAuth flow does work correctly on Slack. On Teams, however, it still doesn't allow me to sign in. Not too sure why, and I was hoping that I didn't need multiple codebases for each chat channel, since that seems to be the purpose of Azure Bot Service. At the very least, though, I am capable of testing my code currently through Slack.

**Comment by jwiley84** [comment]
On teams, does it show the OAuth card. but when you click it, nothing happens?

**Comment by ding-harrison** [comment]
Yeah, there is nothing that occurs when I click it, but the OAuth card does show up.

**Comment by ltwlf** [comment]
When you use the OAuth card in Teams you have to deploy the Bot as a Teams App and add a trusted url token.botframework.com or *.botframework.com. If an url is not trusted you click a button and

**Comment by jwiley84** [comment]
In Teams, you can use the App Studio to help make a manifest.json. That's where you put the trusted URLs.

**Comment by jwiley84** [comment]
@ding-harrison : did adding the app manifest help with the teams issue?

**Comment by ding-harrison** [comment]
@jwiley84 Yeah. It now allows me to go to sign in. However, the dialog doesn't continue after signing in. I'm not exactly sure what is occurring here.

On a similar note, I am having trouble dealing with authentication from other users. I've created an issue here: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-authentication?view=azure-bot-service-4.0, since that seems to be more suitable for the problem I am facing. If you have any insight on it, it would help a bunch.

A basic overview is that I am able to login and get an AAD token, but when I ask someone else to try authenticating with the bot, they receive a bad request with the URL provided in the issue I created. This is weird because the application that my Bot channels registration is connected to should have the correct permissions set.

**Comment by jwiley84** [comment]
What error message are you receiving when you debug and it doesn't go on to the next dialog step?

**Comment by ding-harrison** [comment]
That's the thing. I don't see an error message anywhere. I think I never receive a response after logging in.

**Comment by jwiley84** [comment]
Can you share the code with dialog for these steps, or are you using the sample (and if so, which sample are you using)?

**Comment by ding-harrison** [comment]
It is very similar to https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/18.bot-authentication/Dialogs/MainDialog.cs the sample shown here.

**Comment by jwiley84** [comment]
When you say very similar, what changes have you made?

**Comment by ding-harrison** [comment]
None regarding how sign in works. Only difference is I have two functions similar to DisplayTokenPhase1 since I need the access token twice. However, other than that, there is basically no difference in authentication.

Only difference in codebase is what I need in my project.

**Comment by ding-harrison** [comment]
Is there supposed to be something I should do in the Connector on AppStudio's manifest to enable authentication to work? I'm not sure if I missed up step on that. If all we need is *.botframework.com in the valid domains, then I'm not sure what I am missing (if things should just work).

**Comment by ltwlf** [comment]
That’s all in Teams App Studio. When your dialog sticks after the o365 pop up. The callback / event is not routed appropriately in the background. Teams behaves a little differently than other channels and the auth callback is not very well handled in the ActivityHandler class. That’s why there is now a special Teams example https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/46.teams-auth

**Comment by jwiley84** [comment]
@ding-harrison Have you made your app manifest? Or are you still having this issue?

**Comment by CoHealer** [comment]
@ding-harrison do you still require assistance or should we close the issue?
