### ISSUE TITLE
ConfigureServices Typo

### ISSUE THREAD

**Issue by darosas** [MicrosoftDocs/bot-docs#1208]
In step 7 of Option #1, it says to update some code in the ConfigureServices method, but it should probably say Configure method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0b8671-359e-6026-fd3a-39331cea73f3
* Version Independent ID: 29bab4ad-243a-fb0a-99ed-d8336a92f648
* Content: [Develop DirectLine Speech Bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/directline-speech-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/directline-speech-bot.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Thanks for your feedback.
This typo was fixed and the change will be visible the next time our document updates go live.
