### ISSUE TITLE
What is a roadmap for dev.botfrework.com portal?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/bot-docs#1209]
We have customers who were using [Bot Developer portal](https://dev.botframework.com) and now they are being directed to Azure Portals. However, was there any announcement done about the future of Bot Developer Portal? Should the developer continue to use it for V3.0 Bot ? What are the recommendations here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c880b347-30ea-d472-a4eb-9dc8e24dac82
* Version Independent ID: ce1278bc-c9cb-6944-2269-d1ca16e3defb
* Content: [Migrate your bot to Azure - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-migrate-bot?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-migrate-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-migrate-bot.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by nstejaswini** [comment]
@Anand-Moghe It is better to use the V4 bots. Bot Framework SDK v3 lifetime support will end 12/31/2019,

**Comment by Anand-Moghe** [comment]
@nstejaswini Thanks. **Was there any announcement** in Azure Cloud Service [Update](https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-monitor-your-logic-apps-oms) for Azure Bot Service for V4 SDK that indicates that Developer Portal is only for V3 SDK and all new development for V4 has to happen using Azure Portal? 

I came across [this](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-migrate-bot?view=azure-bot-service-3.0) article in Aure Docs. But this is not very intuitive for someone who is searching on Internet to look for a clue to what is happening with Bot Framework developer portal.
And Developer Portal itself does not give any information about which SDK it is supporting (or may be I am missing something). Only when someone try to create a new Bot service on developer portal they get redirected to Azure Portal and this is confusing experience for new and some existing customers.

So some hint or notice in Azure Update or in Azure docs for Bot Service in this regard about this transition will be nice. Or if there is a documents available in this regard, please share it as I may have overlooked it.

**Comment by nstejaswini** [comment]
@Anand-Moghe In https://apps.dev.microsoft.com/#/appList it is specified in the above that "We will no longer support registering and managing converged and Azure AD applications here starting May 2019.."
For more information about the new SDK visit https://docs.microsoft.com/en-us/azure/bot-service/what-is-new?view=azure-bot-service-4.0

**Comment by EricDahlvang** [comment]
@Anand-Moghe  bots created in the dev portal using https://dev.botframework.com/bots/new are Registration Only Bots, and are not associated with any SDK version.  This page https://docs.microsoft.com/en-us/azure/bot-service/bot-service-migrate-bot is about moving the registration Azure Resource into your personal subscription.  If you are looking for docs related to SDK migration, please look here: https://docs.microsoft.com/en-us/azure/bot-service/migration/migration-about
