### ISSUE TITLE
AppSettings QNA relatd keys are different as keys access in code form configuration

### ISSUE THREAD

**Issue by MarekLani** [MicrosoftDocs/bot-docs#1211]
Please put AppSettings QNA key in pair with the ones in code:
ApPSettings:
  "QnA-sample-qna-kbId": "&lt;knowledge-base-id&gt;",
  "QnA-sample-qna-endpointKey": "&lt;your-endpoint-key&gt;",
  "QnA-sample-qna-hostname": "&lt;your-hostname&gt;"

Code:
var qnaMaker = new QnAMaker(new QnAMakerEndpoint
{
    KnowledgeBaseId = _configuration["QnAKnowledgebaseId"],
    EndpointKey = _configuration["QnAAuthKey"],
    Host = _configuration["QnAEndpointHostName"]
},

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Sub-service: **cognitive-services**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Thank you for your feedback Marek.
The JS Tab had updated names to reflect the new naming in the sample code, but our C# tab missed this change. It has been updated and will be seen when our next set of documentation changes goes live.
