### ISSUE TITLE
Add command

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/bot-docs#1212]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/bot-docs.ja-jp/issues/3
The contributor is requesting additions to the original documentation

@Miura55 commented 15 hours ago
I would like to add a command line on how to add nuget package

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp#add-knowledge-base-information-to-your-bot)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
Adding a command line example for the first NuGet package. Also, adding a link to the NuGet Docs.

**Comment by JonathanFingold** [comment]
Fix is in PR; should go live in a few days.
