### ISSUE TITLE
What are the state operations for?

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1213]
The [state operations](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-3.0#state-operations) don't seem to work, and the SDK doesn't seem to use them. Is that how the deprecated bot state service was used? https://blog.botframework.com/2018/04/02/reminder-the-bot-framework-state-service-has-been-retired-what-you-need-to-know/

If so, we should either mention that or get rid of the section altogether.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36ddb50-9e44-96e3-2df3-174166efa75d
* Version Independent ID: 68ac4b64-6616-2216-3519-e0b33d3a53e4
* Content: [API reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-3.0#state-operations)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
@v-kydela that's correct, these should now be listed as "sunlit". There's now a section in the docs under **how-to/migrate/** that discusses changes from v3 to v4. @EricDahlvang can clarify if necessary.

I will try to switch to generating the REST API reference topics from the Swagger files soon, with v4.6. That will introduce new headaches, but will hopefully be an overall benefit.

In the meantime, I'll update this topic to mark these as retired and no longer available. I'll close this once I have a PR ready.

**Comment by JonathanFingold** [comment]
The PR is marked to be merged.

**Comment by v-kydela** [comment]
@JonathanFingold - The state operations are still on the page, so it doesn't look like the PR removed them
