### ISSUE TITLE
Redundancies in the schema

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1214]
`Conversation`, `Identification`, and `AttachmentUpload` are not actual types in the Bot Framework source code. Should they be removed, since their identical or near-match counterparts (`ConversationParameters`, `ResourceResponse`, and `AttachmentData` respectively) are already in this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36ddb50-9e44-96e3-2df3-174166efa75d
* Version Independent ID: 68ac4b64-6616-2216-3519-e0b33d3a53e4
* Content: [API reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-3.0#objects)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by v-kydela** [comment]
In addition to the redundancies, I've also noticed that a lot of Bot Schema types are missing from this document. A thorough update using the current schema would be a good idea.

**Comment by v-kydela** [comment]
https://github.com/MicrosoftDocs/bot-docs/pull/1215

My pull request should be merged before any work is done on this issue

**Comment by JonathanFingold** [comment]
@v-kydela I'm clobbering the object definitions in our docs and replacing that section with a link to the activity spec. See #1213 for more information.
