### ISSUE TITLE
Having trouble to locate steps in Register your Azure AD application with your bot

### ISSUE THREAD

**Issue by lastactionhero** [MicrosoftDocs/bot-docs#1216]
Hi Team,
I am trying to locate  "OAuth Connection Settings" under AAD v1 or v2 on azure portal. I am may be missing something here. Can you please explicitly share detailed steps for OAuth setting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp%2Cbot-oauth#feedback)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
In the recently updated Azure Active Directory flow, there is no longer a distinction made between Azure AD v1 and v2 when you [create your app registration](https://docs.microsoft.com/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp%2Cbot-oauth#create-your-azure-ad-application). However, when you [configure the connection setting](https://docs.microsoft.com/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp%2Cbot-oauth#register-your-azure-ad-application-with-your-bot), you still select whether you will use the v1 or v2 endpoints. (Step 4b)

**Comment by lastactionhero** [comment]
Hi @JonathanFingold thanks for your time.
I can see only following options and have no clue where to configure connection setting. 
![AzureAAD](https://user-images.githubusercontent.com/13007919/59634590-01f15280-9104-11e9-9bf8-c22d124da0ff.jpg)

**Comment by JonathanFingold** [comment]
It looks like the Azure team has modified the portal again. The OAuth connection settings had been in the resource settings for your bot, but is now missing. I'm trying to track this down.

**Comment by JonathanFingold** [comment]
Turns out that this feature was temporarily disabled to fix a bug. It should be available again tomorrow.

Once it's been enable again, you should be able to follow the how to. The option will be towards the bottom of the bot's settings page:

![image](https://user-images.githubusercontent.com/35047199/59636314-0d467d00-9108-11e9-86da-acc518459d2b.png)

**Comment by lastactionhero** [comment]
Great @JonathanFingold for your quick reply, appreciate your efforts. Its keeping my interest alive to implement this authentication feature :)

**Comment by ameetkonnur** [comment]
Try the cli option to it till it get deployed to the Portal.
az bot authsetting create .....
it worked for me.

**Comment by AskYous** [comment]
Mine is also gone. Waiting for it to come back. They seriously need to put some sort of message explaining what happened. This causes serious confusion.

**Comment by JonathanFingold** [comment]
I got word that the feature has been re-enabled on Azure. It shows up at the bottom of the settings page for your bot.

**Comment by JonathanFingold** [comment]
Closing for now. Please open a new issue if you encounter other problems with this article.
