### ISSUE TITLE
az ad app create: '--identifier-uris' is required for creating an application

### ISSUE THREAD

**Issue by jayallenmsft** [MicrosoftDocs/bot-docs#1217]
I get the error in the title when running the az ad app create command. If I try and feed a fake URI (e.g., https://myawesomebot1), I get: 

Host name in property identifierUris is not on any verified domain of the company or its subdomain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp%2Cnewrg#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by nstejaswini** [comment]
@jayallenmsft When you just use the "az ad app create" command, what error is returning? Can you please explain it more, what you are trying to do and what is happening.

**Comment by drmcghee** [comment]
I get the same error. this is just calling az ad app create --display-name ....

**Comment by drmcghee** [comment]
update to newest azure CLI fixed

**Comment by zxyanliu** [comment]
Hi - I wonder if you have updated to the newest azure CLI and if you have solved this issue? 
Please let us know.

**Comment by jayallenmsft** [comment]
Yep, that fixed it. Thanks!
