### ISSUE TITLE
Error in adding QnA Maker in the Waterfall Dialog

### ISSUE THREAD

**Issue by brynetwork** [MicrosoftDocs/bot-docs#1221]
Hi, I tried adding QnA Maker in the waterfall dialog but I getting this error: "[onTurnError]: TypeError: context.sendActivity is not a function".
Here's the code:
Initialize WaterFall Dialog in the constructor:

        this.addDialog(new WaterfallDialog(TEST_WFDIALOG, [
            this.askQuestion.bind(this),
            this.answerQuestion.bind(this)
        ]));
        this.initialDialogId = TEST_WFDIALOG;

async Functions:
    async askQuestion(stepContext){
        return await stepContext.prompt(TEXTPROMPT, `Type your Question: `);
    }
    async answerQuestion(stepContext){
        const qnaResults = await this.qnaMakerMemberKB.getAnswers(stepContext.result);
        return await context.sendActivity(`${ qnaResults[0].answer }`);
        return await stepContext.endDialog();
    }

the above code is only use to simplify the problem, since I need to get a few information to the user before asking letting the user input the question, then feedback the answer base on the QnA Maker result.

If there is some incorrect implementation of the code, kindly let me know and why I'm getting the above error.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c5adf9-272a-e0f1-10f1-c8365e76035b
* Version Independent ID: 1982af41-5a06-4398-0e95-abcc50864e0d
* Content: [Implement sequential conversation flow - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
It's less clear in JavaScript, but in your code:
```JavaScript
async answerQuestion(stepContext) {
    const qnaResults = await this.qnaMakerMemberKB.getAnswers(stepContext.result);
    return await context.sendActivity(${ qnaResults[0].answer });
    return await stepContext.endDialog();
}
```

Use `stepContext.context` to access the turn's context object. The scope within a dialog step does not have access to the bot's turn context object directly.

Hope that helps.

**Comment by nstejaswini** [comment]
@brynetwork  The following code for async answerQuestion( ) has been tested and is working. You can use this,

 async answerQuestion(stepContext) {
        const qnaResults = await this.qnaMaker.getAnswers(stepContext.context);
        return await stepContext.context.sendActivity(qnaResults[0].answer);
        return await stepContext.endDialog();
    }

**Comment by DanDev33** [comment]
Closing following Tejaswini's working code update.

**Comment by brynetwork** [comment]
@JonathanFingold  and @nstejaswini .

Thank you!
