### ISSUE TITLE
Need Deployment Info for Existing AppId/AppPass

### ISSUE THREAD

**Issue by mdrichardson** [MicrosoftDocs/bot-docs#1223]
Per: https://github.com/microsoft/botframework-sdk/issues/5429

Some users are not able to create an app registration and must use an existing one. A quick note about using the following command for existing app registrations would be helpful:

```bash
az bot create --kind webapp --resource-group "&lt;existingRG&gt;" --name "&lt;anything&gt;" --appid "&lt;existingAppId&gt;" --password "&lt;existingPass&gt;" --lang &lt;Javascript|Csharp&gt;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
@mdrichardson - submit a pr with the change.
