### ISSUE TITLE
Git hub link not working for payment bots

### ISSUE THREAD

**Issue by rajurh** [MicrosoftDocs/bot-docs#1225]
Git hub sample link not working for payment bot.

In the below url documentation mentions about source code link for payment but its not functioning 
https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-request-payment?view=azure-bot-service-3.0

I cross checked in the BotBuilder-Samples from the below url and still couldn't find the same. 

Please provide the right url for the Payment bot sample.

**Comment by DanDev33** [comment]
The v3 samples were moved to a separate folder and are not being updated. But you may find the payment sample you are looking for here: 
https://github.com/microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp/sample-payments

**Comment by DanDev33** [comment]
Please reopen if this is not what you were looking for.

**Comment by rajurh** [comment]
How about the same sample for v4? Also wanted to check with V4 I am trying to create new bot but it always create in Asp.net core is it intended? I am not able to create in normal .net framework

**Comment by rajurh** [comment]
> The v3 samples were moved to a separate folder and are not being updated. But you may find the payment sample you are looking for here:
> https://github.com/microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp/sample-payments

How about the same sample for v4? Also wanted to check with V4 I am trying to create new bot but it always create in Asp.net core is it intended? I am not able to create in normal .net framework
