### ISSUE TITLE
Latest version of nuget package Microsoft.Bot.Builder not supported by .net framework version 4.6

### ISSUE THREAD

**Issue by vidyakdil** [MicrosoftDocs/bot-docs#1226]
While migrating the solution from Bot framework V3 to V4, if the .net framework version is 4.6(less than 4.6.1), the nuget packageMicrosoft.Bot.Builder and Microsoft.Bot.Builder.Integration.AspNet.WebApi is not compatiable. This is not mentioned in the Botframework migration documentation.

**Comment by nstejaswini** [comment]
@vidyakdil When you try downloading or updating the Nuget versions with .netframewrok version 4.6, it shows an error that the version is not capable, which is helpful to understand that the .netframework version must be updated.

**Comment by DanDev33** [comment]
Thanks for your feedback. We are currently working on an update to our migration documentation and will make sure this is addressed.
