### ISSUE TITLE
The case studies link leads nowhere

### ISSUE THREAD

**Issue by Winnak** [MicrosoftDocs/bot-docs#1237]
In the next steps
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-4.0#feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6838575c-d2fc-65e3-98c2-0b35992c10b2
* Version Independent ID: 2b5dc3fc-49c0-7cd2-e6e1-4ced8da6c5f9
* Content: [Azure Bot Service Introduction - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-overview-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-overview-introduction.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by nstejaswini** [comment]
@Winnak The Case studies link directs to https://azure.microsoft.com/en-in/services/bot-service/ .
