### ISSUE TITLE
Configured new channel in my working BOT for Twilio - Doesn't work. 

### ISSUE THREAD

**Issue by scottker** [MicrosoftDocs/bot-docs#1239]
I have configured a new channel in my working BOT for Twilio. I'm trying to do text message response for a BOT. Everything seems to be configured correctly until I send a message and get the following error in Twilio. 

Msg	"Bad Gateway"
sourceComponent	"14100"
ErrorCode	"11200"
EmailNotification	"false"
httpResponse	"502"
LogLevel	"ERROR"
url	"https://sms.botframework.com/api/sms"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b76e08-962a-2a8e-2453-87fb917d68ec
* Version Independent ID: 937798fb-8f76-683c-e146-55dcd79622e1
* Content: [Connect a bot to Twilio - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-twilio?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-twilio.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-twilio.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by nstejaswini** [comment]
@scottker Is the bot replying in emulator/webchat. Did you test it there and check?

**Comment by scottker** [comment]
We can close this. Twilio does not allow you to sms/voice dial numbers not in the valid number list when you are in Trial mode. Took me a while to figure it out because it throws a generic 502 with bad gateway instead of a more friendly message, but lesson learned.

**Comment by zubairshahzad** [comment]
@scottker  have you  fixed  this  issue ?

**Comment by christian-colon** [comment]
I'm having the same error code "11200". My phone number is in the verified list but I keep getting the error.

**Comment by scottker** [comment]
@zubairshahzad @christian-colon make sure you are on a paid Twilio account. The trial accounts require text messages from "verified caller id's"/ known phone numbers when it's in the trail/unpaid mode. If you don't want to pay to test, you can build a list of validated phone numbers in the Twilio UI (See image) but then you can only test from those numbers.
![Capture](https://user-images.githubusercontent.com/1173297/62144334-389bba80-b2b7-11e9-8479-6a0264af072b.jpg)

**Comment by christian-colon** [comment]
I have the number from which I am testing in that list but it is still not working. I've doubled check to see if there is another mistake in configuration but no luck yet. Everything is done as the document says. Thank you for your reply.

**Comment by lfernando2091** [comment]
Yes I have the same error ErrorCode	"11200"
I have paid Twilio account, but when I am testing it is still not working

**Comment by lfernando2091** [comment]
I solved this activating the Geo Permissions on Programable SMS for my country.

**Comment by zubairshahzad** [comment]
i have paid  account  and registered number twilio number with whatsapp... its working on on custom chatbot url ..  but   by  using this  
https://sms.botframework.com/api/sms  azure chatbot not  working

**Comment by zubairshahzad** [comment]
Msg	"Not Found"
sourceComponent	"14100"
ErrorCode	"11200"
EmailNotification	"false"
httpResponse	"404"
LogLevel	"ERROR"
url	"https://sms.botframework.com/api/sms"

**Comment by zubairshahzad** [comment]
what  i enter  in     A MESSAGE COMES IN

**Comment by zubairshahzad** [comment]
i am  doing  for whatsapp

**Comment by dikson88512-ai** [comment]
At this date it does not work, I have the same error

**Comment by nboussarsaracn** [comment]
Still not working
