### ISSUE TITLE
QnAMakerEndpoint not connecting

### ISSUE THREAD

**Issue by SethuSP** [MicrosoftDocs/bot-docs#1240]
var results = await EchoBotQnA.GetAnswersAsync(turnContext);

The endpoint returns no host even though my QnA KB is present.

try
            {
                var results = await EchoBotQnA.GetAnswersAsync(turnContext);
                if (results.Any())
                {
                    await turnContext.SendActivityAsync(MessageFactory.Text("QnA Maker Returned: " + results.First().Answer), cancellationToken);
                }
                else
                {
                    await turnContext.SendActivityAsync(MessageFactory.Text("Sorry, could not find an answer in my knowledge base."), cancellationToken);
                }
            }
            catch (System.Exception e)
            {
                await turnContext.SendActivityAsync(MessageFactory.Text(e.Message), cancellationToken);
                throw;
            }

e returns - No such host is known

**Comment by dmvtech** [comment]
@sethusp What is the format of your QnAEndpointHostName in your config? It should work with  `https://<host>.azurewebsites.net/qnamaker`

But not:
- `https://<host>.azurewebsites.net`
- `<host>.azurewebsites.net`

**Comment by dmvtech** [comment]
Closing due to no response/follow up. Please reopen if you are still having this issue.
