### ISSUE TITLE
Not sure how to develop locally 

### ISSUE THREAD

**Issue by michaelkuzmin** [MicrosoftDocs/bot-docs#1243]
It states "you can continue to develop the bot locally on your machine.". But how do I do that? Can a link be included in this documentation? For example, some tutorials are referring to some .bot file, but no such file is found inside the code zip file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e8c5d2-bf2d-fc99-e813-bf9dd49eb9bb
* Version Independent ID: 830e4542-cdd8-3b64-f1df-2acae1ca3a88
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0&branch=Ignite2018#feedback)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
The link to download the code that you created in the Azure portal is at the bottom of the topic. Once you download the code, you can continue to develop your bot locally. If you are using SDK v4.4 or higher, you will not get .bot file as it has been deprecated. The bot file discussion for users who were using earlier version of the SDK.
