### ISSUE TITLE
Guide doesn't is no longer accurate for latest version of Microsoft.Bot.Builder.Azure

### ISSUE THREAD

**Issue by kedestin** [MicrosoftDocs/bot-docs#1246]
There is no TableBotDataStore class in v4.4.5 of Microsoft.Bot.Builder.Azure, so this guide can't be followed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dca9a7d8-4a99-8d04-4fbb-490e9d2018c3
* Version Independent ID: 058e84b5-85fa-5680-470b-99b28a5f2be6
* Content: [Manage custom state data with Azure Table storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state-azure-table-storage?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-state-azure-table-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-state-azure-table-storage.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kaiqb**

**Comment by Kaiqb** [comment]
This content is for the older version of the SDK (v3.x). The new content for SDK v4.x is [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp).
