### ISSUE TITLE
`Settings > Basic` step might be outdated.

### ISSUE THREAD

**Issue by AviralGarg1993** [MicrosoftDocs/bot-docs#1250]
`Settings &gt; Basic` step might be outdated. It doesn't show up when I am following these steps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0199d414-87e1-e32d-b528-ee9d2e03c54e
* Version Independent ID: f88f4b08-0977-baee-5226-844695828b95
* Content: [Connect a bot to Facebook Messenger - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-facebook.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-facebook.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @RobStand
* Microsoft Alias: **RobStand**

**Comment by mmiele** [comment]
Aviral, thank you for contacting us.
If you are still experiencing problems, would you mind to provide more details about the specific step in the documentation? If you have a screenshot it would be useful.

**Comment by AviralGarg1993** [comment]
Hey! I did this last month and I remember that the details were a little different. I don't have screenshots but if you create a new HelloWorld app and follow those steps you would see the difference early on.

**Comment by mmiele** [comment]
Aviral, the updated documentation will be available at the EOD Pacific time. 
We suggest that you visit https://stackoverflow.com/questions/tagged/botframework for related issues.
