### ISSUE TITLE
Lack of document - Botbuilder - NodeJS - Implement custom storage for bot

### ISSUE THREAD

**Issue by BhuvaneshwaranR** [MicrosoftDocs/bot-docs#1252]
Hi!
There is a lack of documentation to implement custom storage for a bot in NodeJS.
Here are the few threads related to the same issue ( #626  #1116  #849  ) which has been pending for a long time. Could you provide the relevant document?

**Comment by Kaiqb** [comment]
I can't transfer this issue to the correct repo. Please file a request in the [samples repo](https://github.com/microsoft/botbuilder-samples).
