### ISSUE TITLE
Missing- Implement a custom storage solution in the NodeJS SDK-v4.

### ISSUE THREAD

**Issue by BhuvaneshwaranR** [MicrosoftDocs/bot-docs#1253]
Is there is any documents and examples are available for implementing a custom storage state in NodeJS SDK v4?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 409c8f0a-6388-574b-5443-a09c160962a7
* Version Independent ID: efc9e777-18e8-bcf2-204e-b395ce2e9f90
* Content: [Implement custom storage for your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-custom-storage?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/bot-builder-custom-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-custom-storage.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by Kaiqb** [comment]
I can't transfer this issue to the correct repo. Please open an issue in the [samples repo](https://github.com/microsoft/botbuilder-samples). Thanks

**Comment by mdrichardson** [comment]
Re-opening as there is no documentation for Node custom storage, although there is C#. This is more of a DCR for the docs than a support issue. I'll answer the support side in the other thread.

**Comment by Kaiqb** [comment]
There is not sample for Node that is why. Adding the code to the doc can happen once the sample is done.

**Comment by josephwccheng** [comment]
Requesting for a solution for custom storage in Node.js as well.
