### ISSUE TITLE
Limitations and way to get around

### ISSUE THREAD

**Issue by saikumaru** [MicrosoftDocs/bot-docs#1256]
`When implementing proactive messages in your bot, don't send several proactive messages within a short amount of time. Some channels enforce restrictions on how frequently a bot can send messages to the user, and will disable the bot if it violates those restrictions.`

Please can someone advice on the limits around this quoted clause
1. the number of proactive messages that can be sent
2. in what duration of time
3. Over respective channels - Skype and Teams

Also, please can you highlight how these can be overcome or managed to alter these limits to avoid the bot being disabled.

Your quick reply can help us a lot as we are waiting for an implementation decision to be made based on this feature clause outcome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521a9f9a-025c-c55b-c939-d9d4efc5c6d0
* Version Independent ID: 3bcafb54-f7eb-54f5-1d78-5f2087e2e2dc
* Content: [Send proactive notifications to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by Kaiqb** [comment]
The information about throttling from Bot Framework team is listed [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0#rate-limiting). We don't have information for other channels like Facebook, Slack, etc.
