### ISSUE TITLE
"Deploy your bot" page doesn't have instructions for non-default (public) Azure clouds

### ISSUE THREAD

**Issue by hristp** [MicrosoftDocs/bot-docs#1257]
The page says to log in to Azure like this:
az login

For non-public clouds (e.g. US Gov), the page should also add to select the cloud before "az login":
az cloud set --name AzureUSGovernment

And if the user wants to go back to public cloud, run this:
az cloud set --name AzureCloud

**Comment by zxyanliu** [comment]
Hi Hristina, thanks for your feedback. Yes, our current deploy articles are focused on deploy a bot to Azure. If we have a chance to document on deploy a bot to non-Azure cloud in the future, we would happy to take your advice. 
Let us know if you have any further questions. 
Thanks.

**Comment by zxyanliu** [comment]
Hi - thanks for your suggestion. We just updated the content as you suggested. You should be able to see it soon.
Thanks again for your feedback. We really appreciate it.

**Comment by zxyanliu** [comment]
Hi - we have updated the content as you suggested. Please check here in the [deploy your bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg%2Ccsharp) article. 

Thanks again for your feedback to help use improve. We really appreciate it.
