### ISSUE TITLE
Mismatch between registration bot in doc and web app bot in linked sample

### ISSUE THREAD

**Issue by hristp** [MicrosoftDocs/bot-docs#1258]
In the "Add authentication to your bot via Azure Bot Service" doc (https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp%2Cbot-oauth), it says to create a registration bot.

However, the doc then tells users to run the Bot Authentication sample (https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/18.bot-authentication), which assumes a web app bot, NOT a registration bot.

Should update the doc to create a web app bot instead of a registration bot.

**Comment by emgrol** [comment]
Hi @hristp , I've removed the following line from the article.
> These authentication features work with other types of bots, too. However, this article uses a registration-only bot.

If there are any other sections that add to this confusion about creating a web app bot vs. a registration bot let me know,

**Comment by emgrol** [comment]
Closing this issue, feel free to open a new one if the confusion re: this topic persists.
