### ISSUE TITLE
 Roller sample (GitHub) link is 404

### ISSUE THREAD

**Issue by HemantGaur** [MicrosoftDocs/bot-docs#1259]
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/demo-RollerSkill

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fd1fac-45fe-1a18-9dfd-a15e69536c47
* Version Independent ID: 1a32e7e1-dcc9-4756-f3d4-d3d5870e2766
* Content: [Add speech to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-text-to-speech?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/nodejs/bot-builder-nodejs-text-to-speech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-text-to-speech.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
The v3 samples were moved. The correct location of this sample is: https://github.com/microsoft/BotBuilder-Samples/tree/v3-sdk-samples/Node/demo-RollerSkill.
