### ISSUE TITLE
(Minor Issue) - Spell mistake in 'Building a bot' section 

### ISSUE THREAD

**Issue by srtweb** [MicrosoftDocs/bot-docs#1262]
'Framework' misspelled. - Azure Bot Service and Bot "Framewrk" offer..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6838575c-d2fc-65e3-98c2-0b35992c10b2
* Version Independent ID: 2b5dc3fc-49c0-7cd2-e6e1-4ced8da6c5f9
* Content: [Azure Bot Service Introduction - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-4.0#building-a-bot)
* Content Source: [articles/bot-service-overview-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-overview-introduction.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for catching this spelling mistake! The docs will be updated today.
