### ISSUE TITLE
Bot.Builder.Community.Dialogs.Formflow Not Installable in a NET Framework Project

### ISSUE THREAD

**Issue by LanceMcCarthy** [MicrosoftDocs/bot-docs#1263]
In Step 4 of the https://docs.microsoft.com/en-us/azure/bot-service/migration/conversion-framework?view=azure-bot-service-4.0#update-and-install-nuget-packages section at the opening of the article, the instructions are to install the Bot.Builder.Community.Dialogs.Formflow package.

However, this package isn't supported with most projects that were originally created using the v3 SDK. This is because the default version of .NET is 4.6 for those ASP.NET (MVC5) project templates.

Therefore, I recommend a small note in step 4 that will save a ton of headache. For example, here's some text you can borrow:

`Note: If your project targets .NET Framework 4.6, you'll need to update it to 4.6.1 or later because Bot.Builder.Community.Dialogs.Formflow is a .NET Standard 2.0 library.`

Thanks!

[EDIT] Fixed min version number suggestion  of .NET Framework

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e377673-b61a-aa61-2015-8c65c528060d
* Version Independent ID: 2fc8e645-3497-5a4c-8307-37b2ffdc64a4
* Content: [Migrate an existing bot within the same .NET Framework project - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/migration/conversion-framework?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/migration/conversion-framework.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/migration/conversion-framework.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by EricDahlvang** [comment]
Hi @LanceMcCarthy 

Thank you for pointing this out.  We will update the doc to include a note about the minimum requirement being .net 4.6.1

Reference:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

**Comment by mmiele** [comment]
Added note suggested by Lance and reference suggested by Eric. The fix should be in the upcoming release.

**Comment by mmiele** [comment]
It did not make into yesterday release; sorry. I'll keep it open for now.

**Comment by Kaiqb** [comment]
Looks like this was fixed.

**Comment by mmiele** [comment]
Added note to the [Update and install NuGet packages](https://docs.microsoft.com/en-us/azure/bot-service/migration/conversion-framework?view=azure-bot-service-4.0#update-and-install-nuget-packages) section.
