### ISSUE TITLE
Access to Microsoft Teams Bot in app - Alias

### ISSUE THREAD

**Issue by rodrigomoro** [MicrosoftDocs/bot-docs#1266]
Hi there,

I have configured the Bot Channels Registration with the Teams channel and that works perfectly. The app accesses to the Bot like a common contact by using the embed code URL.
I also experience to access to the Bot by using the MicrosoftAppId (uuid) in the contacts bar.

I am wondering if there is another way to access to the Bot from the Teams app with an alias like "myBot@myOrganization.com" which internally represents the uuid.

I would appreciate any answer.
Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e31fe2a-ac8e-815c-f33e-2f08fd554915
* Version Independent ID: e4b7dd0b-e9c9-00d8-41ea-f2ecbbb68752
* Content: [Connect a bot to Teams - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/channel-connect-teams.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/channel-connect-teams.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by jwiley84** [comment]
Can you clarify what you mean by accessing the bot? Do you mean starting that initial conversation? Or do you mean @mentioning the bot in a team conversation?

**Comment by rodrigomoro** [comment]
I mean, start talking with the bot like a common contact or colleague.
If I type the MicrosoftAppId, I can reach the bot:

![image](https://user-images.githubusercontent.com/5593177/62370988-ea471f80-b533-11e9-89a3-d6ce1a618c08.png)


I am looking for something like this:
![image](https://user-images.githubusercontent.com/5593177/62370479-8839ea80-b532-11e9-8887-219db7c077c1.png)

Thank you so much!

**Comment by dmvtech** [comment]
I haven't found one yet, but am looking into it further.

**Comment by iMicknl** [comment]
I faced the same issue a while and came up with the following 'work around', but wasn't able to test it yet.

@dmvtech what about creating a [company wide team](https://support.office.com/en-us/article/create-a-company-wide-team-037bb27a-bcc9-48fe-8d72-44d9482420a3) with just one channel, and configure [Allow only team owners to post to the General channel](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team#allow-only-team-owners-to-post-to-the-general-channel). In this team you can sideload your bot, which is created using the [Teams App Studio](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio). It should be visible now for all users in the channel, when they search for the bot name in the search box.

**Comment by billbliss** [comment]
This is actually straightforward, but not obvious if you start from Bot Framework. You need to create an app package that references your bot and then load it. You can then load it to a team or make it available to your entire company. I would not recommend a company-wide team for that though.

Discussed here:
- [Use App Studio for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-design)
- [Create an app package for your Microsoft Teams app](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-package)
- [Accessing your uploaded bot](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload)
- [Making a bot accessible to everyone in a tenant](https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams)

**Comment by iMicknl** [comment]
@billbliss Thanks! I didn't know that adding it to the Tenant Apps Catalog, would make it show up in the search box.

**Comment by rodrigomoro** [comment]
Hi @billbliss and @iMicknl ,

I already have a Bot-WebApp with a Bot Channels Registration service working in Azure. 
I'm understanding that I don't have to create a new bot, just a Teams App referencing my existing WebApp. Am I right?

Thank you so much!

**Comment by rodrigomoro** [comment]
Hi again,

I tested the proposed approach and it works perfectly!
I would have liked to have this behavior without the TeamsApp stuffs to avoid future maintenance, permissions in office portal, etc but It looks very good!

Thank you very much for your support and ideas.
