### ISSUE TITLE
Security protocol from Bot connector to Bot

### ISSUE THREAD

**Issue by pdnguyen92** [MicrosoftDocs/bot-docs#1267]
Hello,

The current Bot Connect's OpenID  document does not have as much information as the MSA's OpenID metadata, specifically the id_token for the "response_types_supported", this prevents the ability to setup the External ID Token Authentication ( OIDC ) for Rest APIs. Are there plans on updating the Security protocol from Bot connector to Bot to use the MSA's OpenID instead?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58bf70a-3263-93a1-5bc2-085431a7aa6b
* Version Independent ID: c5e3de2f-58ad-1c6a-e0f3-93489d013114
* Content: [Authenticate requests - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/rest-api/bot-framework-rest-connector-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-authentication.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
For question about the SDK roadmap, please log them in the [botframework-sdk](https://github.com/Microsoft/botframework-sdk/issues) repo.
