### ISSUE TITLE
Cannot reconcile HTTP Details section with Adapter in Echo Bot

### ISSUE THREAD

**Issue by alexsab1** [MicrosoftDocs/bot-docs#1268]
Hello, HTTP Details sections says "Activities sent from the bot to the channel are sent on a separate HTTP POST to the Bot Framework Service. This, in turn, is acknowledged with a 200 HTTP status code.".

I cannot grasp this idea when I'm developing bot locally. Or does this statement apply only to Azure Bot Service?

In the case of a local bot, HTTP POST request is received on the BotController, then passed to the adapter, than passed to the bot, which responds back and thus controller responds back with a message. 

Could you help me to reconcile and clarify this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ccf81d0-a7a0-1e2a-5b35-8cfd723c1225
* Version Independent ID: e3ebe0a1-a22f-1535-c649-3f79158b4ece
* Content: [How bots work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
The diagram describes the communication between a channel and a bot deployed to Azure.

The controller wraps the HTTP service side of things. Does that help clarify?

**Comment by JonathanFingold** [comment]
Please reopen if you need additional information.
