### ISSUE TITLE
Can this code and code in linked article be used as it is?

### ISSUE THREAD

**Issue by hshahbaz** [MicrosoftDocs/bot-docs#1270]
Hi,

I am new to bot framework and I am learning how QnA and Luis interact and work.  I have followed the tutorial in the document called "Use multiple LUIS and QnA models".

Can i use the code snippets given in the article as is or would they need further changes and addition (given I have followed the tutorial exactly)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by xtianus79** [comment]
@hshahbaz all the code you need except for the specific app id's and keys for luis and the qna services are in the github 14 bot samples package which is in the link at the top of this article.

**Comment by hshahbaz** [comment]
@xtianus79 so basically I only need to set my environment (already done) and create a dispatch file? The code can be run as is? I am asking this because I do not see "protected override async Task OnMessageActivityAsync" method in DispatchBot.cs file.

**Comment by diberry** [comment]
@hshahbaz This code specifically names the intents. You would need to change the code if your intents are named differently.

**Comment by hshahbaz** [comment]
@diberry I know that. Thank you for clarification.
