### ISSUE TITLE
Parameters for deployment are poorly documented

### ISSUE THREAD

**Issue by dalemyers** [MicrosoftDocs/bot-docs#1271]
The parameters for deployment are almost entirely useless/redundant currently. Examples:

* `newAppServicePlanName` is the name of App Service Plan.
* `newWebAppName` is the name of the Web App you are creating. 
* `groupName` is the name of the Azure resource group you are creating. 
* `groupLocation` is the location of the Azure resource group. 
* `newAppServicePlanLocation` is the location of the App Service Plan.

All of these are clearly named, but the description just explains the name, not what it is. I know that `groupLocation` is the location of the Azure resource group, but what does that _mean_? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp%2Cnewrg#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
These are standard Azure parameters that we are using in the CLI for deployment - nothing specific to bots. This topic has a link at the bottom to the [terminology ](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-overview#terminology) that should help.

**Comment by dalemyers** [comment]
Sure, but the job of the documentation isn't to be technically correct, it's to make development easier for developers. Adding explanations would make it easier, even if it is also documented elsewhere. At the very least, a link to that page would go a long way. 

Remember: People reading the documentation don't know it as well as your team does. They don't know that they can just go to that other page and find what they need. Anything we can do to help, we should be doing.
