### ISSUE TITLE
Bot Channels Registration Issue

### ISSUE THREAD

**Issue by dcmesh** [MicrosoftDocs/bot-docs#1272]
I've been having issues getting OAuth sign-in to work with my bot, so I tried starting from scratch with the Bot Authentication with MS Graph tutorial (the dotnet core one). After cloning the sample repo, I began following these directions, but got stuck on the creation of a Bot Channels Registration resource in my Azure portal. I created one in the portal, but there was no Application Settings blade under the App Service Settings tab, and I thus have no way to access the client secret that I just created. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp%2Cbot-oauth)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by dcmesh** [comment]
After doing a little more digging, I discovered that a Bot Channels Registration is only necessary if the Bot is hosted outside of Azure. If it is not, then this resource is not required. However, the way that it is described makes it seem that you have to create a new Bot Channels Registration, even if your Bot is in Azure.

The documentation should be changed to address this discrepancy, with something like:
**Create your bot resource on Azure**

Create a Bot Channels Registration using the Azure Portal.
_Note: This step is unnecessary if the Bot is hosted in Azure._

Record your bot's app ID and password. To gather this information, see Manage a bot.

**Comment by mmiele** [comment]
Fixed issue as requesetd.
