### ISSUE TITLE
No such host is known

### ISSUE THREAD

**Issue by hshahbaz** [MicrosoftDocs/bot-docs#1273]
I used the walkthrough from here: h[ttps://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs](url)

Everything works great locally in emulator but when I deploy my code to my bot in azure using publishing feature in VS. I get the following error:

**To run this sample make sure you have the LUIS and QnA models deployed.  
 No such host is known**

Am i missing something? If you want any code snippet or files ask away!

**Comment by zxyanliu** [comment]
Hi - Thanks for your question. May I ask which instruction did you use to deploy your bot? Please let us know this so that we can better answer your question.

**Comment by hshahbaz** [comment]
![image](https://user-images.githubusercontent.com/32860200/62081390-53165b00-b207-11e9-94cd-8caf0261366a.png)


Hi @zxyanliu I have attached the image. I use the publish profile feature in Visual Studio 2017 to deploy the code to my bot in azure. 

This is my configuration in Azure:
 
![image](https://user-images.githubusercontent.com/32860200/62081645-e94a8100-b207-11e9-97d0-90c0917937da.png)

This is my appsetting.json for the bot:

![image](https://user-images.githubusercontent.com/32860200/62081913-78f02f80-b208-11e9-9d8c-7fc20adacf51.png)


I have made  sure the values match for AppId's and Keys. Is there a different way to do deployment for sdk 4.x

**Comment by zxyanliu** [comment]
Hi - Thanks for your reply. For bot deployment, you can also refer to this article: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg
Please let me know if it solves your problem. 

Best,

**Comment by hshahbaz** [comment]
This could be the worst way to do deployment with CLI interface. there are so many things that could go wrong. I used another way by deploying my code on azure dev ops and deploying it from there. I am getting a different error now.
