### ISSUE TITLE
GetAnswerAsync method does not give follow up prompts data.

### ISSUE THREAD

**Issue by AkshayLokare** [MicrosoftDocs/bot-docs#1274]
Hi,

I want to use or display qna maker follow up prompts in bot but the getAnswerAsync method does not return follow up question data. How to get that data.
Please help
thanks in advance

**Comment by JonathanFingold** [comment]
I'm not sure which article this issue refers to. Have you had a chance to read the [Use QnA Maker to answer questions](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0)? Please reopen this issue with more information if that does not answer your question.
