### ISSUE TITLE
Missing code for connecting with Direct Line Speech endpoint in javascript

### ISSUE THREAD

**Issue by mitulsuthar** [MicrosoftDocs/bot-docs#1275]
I searched a lot but couldn't find any documentation on how to connect with the direct line voice chat api. What is the endpoint for connecting to direct line speech api? Existing docs mention only direct line chat api.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4cb4da-ca0e-fc7f-686c-f3510bf9af0b
* Version Independent ID: e20d2896-dcec-8e46-2f50-2227def34250
* Content: [Connect a bot to Direct Line Speech (Preview) - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-directlinespeech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directlinespeech.md)
* Service: **bot-service**
* Sub-service: **bot-service**
* GitHub Login: @trrwilson
* Microsoft Alias: **travisw**

**Comment by mmiele** [comment]
Hi Mitul,
you might want look at this article : [Connect a bot to Direct Line Speech (Preview)](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0).

**Comment by mmiele** [comment]
Mitul, thank you for contacting us.
Are you having problems with this article: [Connect a bot to Direct Line Speech (Preview)](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0)? You mention also "direct line voice chat api". Could you please clarify the kind of issue you are experiencing?

**Comment by mmiele** [comment]
Please, refer to the new doc version at  [Connect a bot to Direct Line Speech (Preview)](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0). The technology is still in preview mode and we are continuously updating the related docs.
