### ISSUE TITLE
Version 4 documentation is not available for attachments

### ISSUE THREAD

**Issue by iMicknl** [MicrosoftDocs/bot-docs#1278]
Link is broken and there is no Bot Builder SDK v4 documentation for attachments, only the REST API reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb25ab38-47e7-3b4e-3d59-5502b6979111
* Version Independent ID: 8aa1133b-f8c1-ae67-cf18-9ff9d6aeaa7b
* Content: [Send and receive attachments - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-receive-attachments?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/nodejs/bot-builder-nodejs-send-receive-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-send-receive-attachments.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by mmiele** [comment]
Mick, could you specify which link is broken? Also, there is new V4 documentation at this location: [Add media attachments to messages](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-media-attachments?view=azure-bot-service-4.0).
Thanks

**Comment by iMicknl** [comment]
>This topic applies to SDK v3 release. You can find the documentation for the latest version of the SDK v4 [here](https://docs.microsoft.com/azure/bot-service/?view=azure-bot-service-4.0).

The URL in the text above (Note) doesn't work for me, it redirects to the homepage.
As noted, there is no documentation for the Bot Builder SDK v4. Your link is the REST API reference, which doesn't show how to achieve it using our .NET / NodeJS SDK.

**Comment by mmiele** [comment]
Please see the v4 article: [Add media to messages/send attachments](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp#send-attachments),

**Comment by iMicknl** [comment]
@mmiele thanks! Could you make the redirect link on the v3 documentation point to the v4 article?

**Comment by mmiele** [comment]
@iMicknl This particular kind of links do not point to specific articles. I'll bring up the issue.
Thanks you for your feedback.
