### ISSUE TITLE
Disagreement between text and code

### ISSUE THREAD

**Issue by ripone07** [MicrosoftDocs/bot-docs#1280]
(Edit: this thread refers to nodejs samples) On chapter `Define and implement the interruption logic` at the first paragraph :
```In the CancelAndHelpDialog class the onBeginDialog and onContinueDialog methods call the interrupt method to check...```
However, in the actual class of the given sample, `onBeginDialog` is not overridden and this can lead to misconceptions of how to implement a globally working conversation cancellation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef4ea5a-1364-5432-dcbb-b39b7145028a
* Version Independent ID: f4b4a848-3ce4-7978-a72d-2c3952a3ab1b
* Content: [Handle user interruptions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-handle-user-interrupt?view=azure-bot-service-4.0&tabs=javascript#define-and-implement-the-interruption-logic)
* Content Source: [articles/v4sdk/bot-builder-howto-handle-user-interrupt.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-handle-user-interrupt.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
The body should contain a `ConversationParameters` object, according to the botframework-channel.json Swagger file. I'll update the documentation presently.

**Comment by emgrol** [comment]
Thanks for pointing this out, updates to the documents will be made shortly!
