### ISSUE TITLE
Telefonica customer story link broken

### ISSUE THREAD

**Issue by aamalhot** [MicrosoftDocs/bot-docs#1281]
[Telefonica customer story](https://customers.microsoft.com/en-us/story/telefonica-media-telco-cognitive-services-azure) link on Bot Framework [website](https://dev.botframework.com/) is broken.

![image](https://user-images.githubusercontent.com/53205984/61682696-4dfd6b80-ad30-11e9-9d50-5097448f45ec.png)

![image](https://user-images.githubusercontent.com/53205984/61682716-64a3c280-ad30-11e9-949c-521231e6ddbe.png)

**Comment by Kaiqb** [comment]
@Andrea-Orimoto - please have someone fix the link.

**Comment by Andrea-Orimoto** [comment]
The fix should be deployed either mid next week or in two weeks at the latest.

**Comment by Andrea-Orimoto** [comment]
The fix has been deployed. If you are still seeing the issue it might still being replicated worldwide, give it a few more hours.
Thanks for reporting the issue.
