### ISSUE TITLE
Section on validating endorsements of signing key seems out of place

### ISSUE THREAD

**Issue by ericrrichards** [MicrosoftDocs/bot-docs#1282]
In the section "Authenticate requests from the Bot Connector Service to your bot" in Step 3 it is saying that you should check that the key used to sign the token has an endorsement value matching the channelId of the Activity sent to the bot.

Maybe I'm doing this wrong, but it seems to me that that validation step should be part of Step 4, after you have unwrapped the bearer token and verified that it is signed with a valid key, because you would want to make sure that the key that was used to sign the token actually has the endorsement that corresponds to your activity.

Maybe I am not understanding how this is supposed to be done, but it does appear to be the flow that is implemented in the BotConnector JwtTokenExtractor class -&gt; https://github.com/microsoft/BotBuilder-V3/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/JwtTokenExtractor.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58bf70a-3263-93a1-5bc2-085431a7aa6b
* Version Independent ID: c5e3de2f-58ad-1c6a-e0f3-93489d013114
* Content: [Authenticate requests - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0#connector-to-bot)
* Content Source: [articles/rest-api/bot-framework-rest-connector-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-authentication.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Hi Eric,
thanks for contacting us. 
I would like to ask some clarifications

The sentences you refer to is in section 3 and state: 

_You should require that any Activity object sent to your bot with that channel ID is accompanied by a JWT token that is signed with an endorsement for that channel
If the endorsement is not present, your bot should reject the request by returning an HTTP 403 (Forbidden) status code._

Are you suggesting to move it in section 4 as follows?
…..
7. _The token contains a "serviceUrl" claim with value that matches the servieUrl property at the root of the Activity object of the incoming request.
If the token does not meet all of these requirements, your bot should reject the request by returning an HTTP 403 (Forbidden) status code._

**You should require that any Activity object sent to your bot with that channel ID is accompanied by a JWT token that is signed with an endorsement for that channel.
If the endorsement is not present, your bot should reject the request by returning an HTTP 403 (Forbidden) status code.**

Thanks

**Comment by ericrrichards** [comment]
Hi Michael,

Correct, I think that would be clearer, assuming that the way that I am
interpreting the document is correct. That does appear to be consistent
with the way that the authentication is implemented in the official Bot
Connector code.

**Comment by mmiele** [comment]
Moved endorsement information to the proper section.
