### ISSUE TITLE
Test in Web Chat

### ISSUE THREAD

**Issue by JPalmerDev** [MicrosoftDocs/bot-docs#1283]
The section for testing in web chat is not very clear.

First is the usage of the phrase 'bot blade', which isn't a term I have seen before.
I thought it meant go to the Web App section and to look for the 'Bot Management' and 'Test in Web Chat' options. Those options do not exist inside of the Web App section.

The path that would actually be recommended is to go into the Resource Group and then go into the Bot Channels Registration. This is where the Bot Management section and following steps are.

I would recommend updating that section to better reflect where you are looking.

I also would find it helpful if there was more description in regards to what a Bot Channel Registration even is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=erg#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by mmiele** [comment]
Made the requested changes. They can be found [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=erg#3-test-in-web-chat).
