### ISSUE TITLE
Need information on where to get the IActivityLogger interface

### ISSUE THREAD

**Issue by AskYous** [MicrosoftDocs/bot-docs#1284]
I tried to implement step one in my current bot, which was to make the class that extends the `IActivityLogger` class. But when I started coding, I received the error message that it cannot find the `IActivityLogger` interface. Can you please insert it into the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8de1be0-19df-c8e9-9a80-e8f6df9dc362
* Version Independent ID: 92ae3a1e-10a1-1911-70b2-b8fd6142ba4f
* Content: [Intercept messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-middleware?view=azure-bot-service-3.0#intercept-and-log-messages)
* Content Source: [articles/dotnet/bot-builder-dotnet-middleware.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-middleware.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
The document you referenced is for the older version of the SDK (v3). Are you using SDK v3 or v4?

**Comment by AskYous** [comment]
Ah ok. I'm using v4. Is there documentation for this for v4 I can read?

**Comment by JonathanFingold** [comment]
I'm unfamiliar with v3's IActivityLogger, but you have a number of options in v4:
- Use the built-in [logging](https://docs.microsoft.com/aspnet/core/fundamentals/logging/) features in ASP.NET
- [Add telemetry to your bot](https://docs.microsoft.com/azure/bot-service/bot-builder-telemetry)
- [Debug a bot with inspection middleware](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-inspection-middleware)

Please reopen if you need more information.
