### ISSUE TITLE
Nitpicking: GA Availability

### ISSUE THREAD

**Issue by JPalmerDev** [MicrosoftDocs/bot-docs#1285]
GA stands for 'General Availability', so saying 'GA Availability' is 'General Availability Availability'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b30881c5-a087-aa49-9dbe-3c8772de5851
* Version Independent ID: a9fab212-bcaf-6eaa-af2e-2d960ff4cf0e
* Content: [About Direct Line channel - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline.md)
* Service: **bot-service**
* Sub-service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by emgrol** [comment]
Thanks for pointing this out! I've updated the docs.
