### ISSUE TITLE
Web App and Bot Channel Registration appear to have been split apart

### ISSUE THREAD

**Issue by JPalmerDev** [MicrosoftDocs/bot-docs#1286]
In the section **Enable the Bot Framework Protocol Streaming Extensions**
It asks you to go to the Settings section to enable the Streaming Endpoint., which is currently located in the Bot Channel Registration.
Then in the next section it is telling you to go to the App Service Settings -&gt; Configuration. That is located within the App Service (so not the Bot Channel Registration) and then within its Settings divider and then the Configuration.
This could use better language or visual breakdown.

It also appears the screenshots are out of date and not accurate with the azure interfaces I am seeing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4cb4da-ca0e-fc7f-686c-f3510bf9af0b
* Version Independent ID: e20d2896-dcec-8e46-2f50-2227def34250
* Content: [Connect a bot to Direct Line Speech (Preview) - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-directlinespeech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directlinespeech.md)
* Service: **bot-service**
* Sub-service: **bot-service**
* GitHub Login: @trrwilson
* Microsoft Alias: **travisw**

**Comment by JonathanFingold** [comment]
Thanks for the feedback. The Azure UI changes periodically, and we don't always catch discrepancies. We'll update the screenshots, and we'll review the descriptions for clarity.

**Comment by mmiele** [comment]
Jonathan, I did update the article and it should be ready soon.

**Comment by mmiele** [comment]
The article has been published with the suggested fixes.
