### ISSUE TITLE
Telemetry for QnA is not like LUIS as the docs mention

### ISSUE THREAD

**Issue by AskYous** [MicrosoftDocs/bot-docs#1288]
The docs say: "You can apply these same principles to other services like QnA Maker." But I've found this to not be true.

```C#
TelemetryClient = telemetryClient;
// works
luisApplication = new LuisRecognizer(
    new LuisApplication(
        "XXX",
        "XXX",
        "https://westus2.api.cognitive.microsoft.com"
    ),
    new LuisPredictionOptions()
    {
        TelemetryClient = telemetryClient // Works
    }
);

// doesn't work
qnA = new QnAMaker(new QnAMakerEndpoint
{
    KnowledgeBaseId = "XXX",
    EndpointKey = "XXX",
    Host = "https://flexqna2.azurewebsites.net/qnamaker",
})
{
    TelemetryClient = telemetryClient // Doesn't work. Errors saying this is a read-only property
};
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db892de5-e60e-1d4f-505b-11b1cdb73323
* Version Independent ID: f7263014-b8fa-9a20-71aa-e4217b2821ee
* Content: [Add telemetry to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0#enabling-telemetry-to-capture-usage-data-from-other-services-like-luis-and-qna-maker)
* Content Source: [articles/v4sdk/bot-builder-telemetry.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-telemetry.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
Hi- we'll be adding content for QnA when additional samples are added. In the meantime, we'll update the line that is causing the confusion.

**Comment by Kaiqb** [comment]
QnA telemetry article published.
