### ISSUE TITLE
dotenv.load(); needs to be replaced with dotenv.config();

### ISSUE THREAD

**Issue by seanbetts** [MicrosoftDocs/bot-docs#1289]
Please update the documentation to state:
// initialized to access values in .env file.
var dotenv = require('dotenv');
dotenv.config();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
Hi- we did not find the line you mentioned in the topic. The samples are maintained in a different repo, and we can't transfer this issue automatically. For samples, log issue in the [botbuilder-samples](https://github.com/microsoft/botbuilder-samples) repo. Thanks!
