### ISSUE TITLE
update doc

### ISSUE THREAD

**Issue by AntonioEspinosa** [MicrosoftDocs/bot-docs#1291]
below 
Create LUIS apps in the examples
you should update

8. Once completed, Train and Publish both your LUIS weather app and your **LUIS dispatch** app (for **LUIS weather app** ) by repeating the above steps for 'Weather.json' file.

this can be confusing for new people

**Comment by Kaiqb** [comment]
We can slightly tweak the instructions. Thanks for reporting.
