### ISSUE TITLE
Getting a Bad Request when trying to connect with an application registration

### ISSUE THREAD

**Issue by ding-harrison** [MicrosoftDocs/bot-docs#1293]
So I am doing user authentication with the OAuth prompt, and currently, the authentication works for me. However, for some time, this did not work and I continuously got a bad request from my application.
https://token.botframework.com/.auth/web/redirect?error=invalid_request&error_description=AADSTS90008%3a+The+user+or+administrator+has+not+consented+to+use+the+application+with+ID+%2&lt;App ID here. Removed for security issues&gt;.+This+happened+because+application+is+misconfigured%3a+it+must+require+access+to+Windows+Azure+Active+Directory+by+specifying+at+least+%27Sign+in+and+read+user+profile%27+permission.%0d%0aTrace+ID%3a+&lt;Trace ID here&gt;%0d%0aCorrelation+ID%3a+&lt;Correlation ID here&gt;+%0d%0aTimestamp%3a+2019-07-30+17%3a36%3a16Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d90008&state=1eff6eaa5b8e40ae91024b4623cb99e5

This is the URI I get, and it doesn't really make sense, since this now works for me, but does not work for other people trying to login. Would anyone happen to understand what is going on and why this is showing up, even when the application given provides AAD Sign in and Read user profile permissions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf2089c-a313-0abf-2ed3-8d7db5c4f677
* Version Independent ID: f0b3a9ce-b1e3-7b3d-15a9-0b9e032aa4bd
* Content: [User authentication in the Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-authentication?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-authentication.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by ding-harrison** [comment]
Never mind. This appears to stop occurring after a few minutes of waiting from the first attempt. Not sure why it occurred, and will close this issue for now. Will test with other users, and if it is recurring, will reopen.

**Comment by sindhugururaj** [comment]
Hi ,

Am getting the same "Bad request" in Sign In window. Please help. Am using the authentication code in Git hub.
