### ISSUE TITLE
Parameters list

### ISSUE THREAD

**Issue by BeMor81** [MicrosoftDocs/bot-docs#1295]
For the command az deployment create it would be great to have a list of possible parameters along with directions on the scope of the template file is and what its role is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
Azure Resource Manager Template parameters are documented [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates). If you are looking for the Azure CLI parameters, those are listed in the Azure CLI [documentation](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest).

**Comment by BeMor81** [comment]
The template document is useful however I was referring to the deployment parameters for Bots. Is the table a full list? In the document regarding az deployment it just states " --parameters
Supply deployment parameter values." https://docs.microsoft.com/en-us/cli/azure/deployment?view=azure-cli-latest#az-deployment-create
