### ISSUE TITLE
Changing supported account types

### ISSUE THREAD

**Issue by scottjt** [MicrosoftDocs/bot-docs#1296]
Regarding this:

"Important

In the Supported account types, select the Accounts in any organizational directory and personal Microsoft accounts (e.g. Skype, Xbox, Outlook.com) radio button. If any of the other options are selected, bot creation will fail."

Why is this?  I need to make my bot available to my organization only, it seems like this would be the way to do it.  How else can I limit access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253d4e99-7fc5-cc8d-5b07-29bf2d78687a
* Version Independent ID: cdc0528d-cf1a-e015-1d8a-31ed062648f8
* Content: [Bot Service Frequently Asked Questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-resources-bot-framework-faq.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-resources-bot-framework-faq.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by jwiley84** [comment]
This is outdated. 

You can select any of the three options, but bear in mind, for the first two, you will simply need your tenant admin to approve your app. When you try to log in or test your connection, you'll see the following alert:

![image](https://user-images.githubusercontent.com/17333688/62393520-42275b80-b51f-11e9-93e6-060cba0bb4aa.png)

For some, it's easier to test their AADv2 oauth connection by creating a quick outlook.com email and selecting the 'andpersonal' option. This does not require admin approval of the app, and is efficient for testing purposes.

A more comprehensive doc on how to add OAuth to your bot is here: [Add authentication to your bot via Azure Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp%2Cbot-oauth)
