### ISSUE TITLE
TypeError: Cannot read property of "map" of undefined. 

### ISSUE THREAD

**Issue by cbtham** [MicrosoftDocs/bot-docs#1297]
The QnAmaker endpointKey is from publish page in QnAmaker after you publish a kb. It is NOT the one from Azure portal. The Azure portal key is required ONLY for creating dispatcher.

The section to make it clearer is:-
Authoring Key - found in the Azure portal, for the QnA Maker resource, under the Keys. You only need one of the keys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=js#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by cbtham** [comment]
![image](https://user-images.githubusercontent.com/5702935/62210316-797bf800-b3b9-11e9-9669-0cdccdd31d0e.png)

**Comment by diberry** [comment]
@cbtham Thank you for letting us know this section of the document needs clarification. #in-progress

**Comment by cbtham** [comment]
you're welcome. If you need additional information, ping me on Teams.

**Comment by diberry** [comment]
@cbtham This doc is updated. Please send the following [change](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs#dispatch-app-needs-read-access-to-existing-apps) noted in the image. 
![image](https://user-images.githubusercontent.com/41597107/63121870-5b39fe80-bf5a-11e9-95f8-aa50e5a8931c.png)

#please-close

**Comment by JonathanFingold** [comment]
Thanks @diberry , closing.

@cbtham , please reopen or open a new issue if this is not resolved.
