### ISSUE TITLE
Cross partition query is required but disabled.

### ISSUE THREAD

**Issue by MrLokeshV** [MicrosoftDocs/bot-docs#1299]
Hi Team,

Before we have cosmosdb Collection without Partition key to store Bot Conversation data.
Now we have created the new DB Collection with partition Key on UserID.
But now we are getting the below error. please help.
Cross partition query is required but disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
This is related to the [issue](https://github.com/microsoft/botbuilder-dotnet/issues/1247) reported in the SDK repo that was addressed.
