### ISSUE TITLE
Set Speak Field on Activities

### ISSUE THREAD

**Issue by JPalmerDev** [MicrosoftDocs/bot-docs#1300]
In the '[Set the Speak Field](https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0#set-the-speak-field-on-activities-you-want-spoken-to-the-user)' section, where do you add this code to?
Which class?
I'm working off of an EchoBot and was able to find the spots to handle the other steps, but not this one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0b8671-359e-6026-fd3a-39331cea73f3
* Version Independent ID: 29bab4ad-243a-fb0a-99ed-d8336a92f648
* Content: [Develop DirectLine Speech Bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0)
* Content Source: [articles/directline-speech-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/directline-speech-bot.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
@JPalmerDev The sample code just demonstrates one way of setting the `Speak` property of a generated activity. You would do this for any activity your bot is sending that you want spoken to the user.

**Comment by JPalmerDev** [comment]
So I'd do something like add this function to EchoBot, and then have OnMessageActivityAsync call Speak before echoing the text message?

**Comment by JPalmerDev** [comment]
Thanks for your response, I was a bit stuck on this.

I think this tutorial could benefit from a bit of information pointing the user towards the concept of an Activity and where/how it's used. I'm approaching this content from 'Making a Speech Bot' perspective and have not used the Bot Framework before.

I think I've got what I need, now checking the deploy to azure to make sure its right.

**Comment by JonathanFingold** [comment]
I'll add to this article links to the articles on how to send activities and set input hints. Glad I could help.

**Comment by omroczkowski** [comment]
Is there any possibility to use Speak in PromtAsync?
