### ISSUE TITLE
For [Retrieve/Create IIS/Kudu files] section, why not also use a Tabs views?

### ISSUE THREAD

**Issue by JPalmerDev** [MicrosoftDocs/bot-docs#1301]
Nitpicking layout, but why not use tab breakdown like whats done in the 'Deploy via ARM template' section above.

It improves readability and decreases confusion for readers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by zxyanliu** [comment]
Hi Jonathan, we just updated the format as you suggested. You should be able to see it shortly.
Thanks again for your feedback, we really appreciate it.

**Comment by zxyanliu** [comment]
Hi - I believe the new format is already shown in the article [Deploy your bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg%2Ccsharp).

Thanks again for your feedback.
