### ISSUE TITLE
Missing instructions for creating a workplace premium account

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1302]
The link to instructions for creating a workplace premium account just links to the workplace home page and doesn't contain any instructions for creating a workplace premium account: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0#create-a-facebook-workplace-premium-account

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0199d414-87e1-e32d-b528-ee9d2e03c54e
* Version Independent ID: f88f4b08-0977-baee-5226-844695828b95
* Content: [Connect a bot to Facebook Messenger - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0#create-a-facebook-workplace-premium-account)
* Content Source: [articles/bot-service-channel-connect-facebook.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-facebook.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @RobStand
* Microsoft Alias: **RobStand**

**Comment by mmiele** [comment]
Work in progress.
See PR: https://github.com/MicrosoftDocs/bot-docs-pr/pull/1706.

**Comment by mmiele** [comment]
@v-kydela Added missing information. Please, review the staged document: https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-3.0&branch=pr-en-us-1706#connect-a-bot-to-facebook-workplace.

**Comment by mmiele** [comment]
Updated documentation published.
