### ISSUE TITLE
retryPrompt in js has unlimited amounts of attempts

### ISSUE THREAD

**Issue by MaartenBlomer** [MicrosoftDocs/bot-docs#1305]
Is it possible to set a counter on the amounts of retries the user gets when failing to provide the correct age?

JS snippet:
```
const promptOptions = { prompt: 'Please enter your age.', retryPrompt: 'The value entered must be greater than 0 and less than 150.' };
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c5adf9-272a-e0f1-10f1-c8365e76035b
* Version Independent ID: 1982af41-5a06-4398-0e95-abcc50864e0d
* Content: [Implement sequential conversation flow - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=javascript#feedback)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
There is a built-in counter that was introduced recently, the [PromptValidatorContext<T>.AttemptCount Property](https://docs.microsoft.com/dotnet/api/microsoft.bot.builder.dialogs.promptvalidatorcontext-1.attemptcount?view=botbuilder-dotnet-stable).

Here's some sample code that uses a helper function to check the number of retries, and then. The only tricky thing here is that the validator needs to return true for the prompt to not reprompt the user on the next turn. I have a couple extra helper methods to set and check for a flag in the turn context.

```csharp
        private async Task<bool> AgeValidatorAsync(
            PromptValidatorContext<int> promptContext,
            CancellationToken cancellationToken)
        {
            var options = promptContext.Options.Validations;
...
            // On success, return true;
            if (success && value >= options.Min && value <= options.Max)
            {
                return true;
            }

            // Otherwise, this attempt failed; call helper method.
            return await FailValidation(promptContext, options, cancellationToken);
        }

        private static async Task<bool> FailValidation<T>(
            PromptValidatorContext<T> promptContext,
            ValidationOptions options,
            CancellationToken cancellationToken)
        {
            // If the input failed too many times, allow the prompt to succeed, but set a failure flag.
            // This allows the prompt dialog to exit and return control to the parent dialog.
            if (promptContext.AttemptCount >= 3)
            {
                FlagPromptFailure(promptContext);
                return true;
            }

            // If we have a default error message, send that to the user...

            // Signal that this attempt failed, and that the user should be re-prompted for input.
            return false;
        }

        private static void FlagPromptFailure<T>(PromptValidatorContext<T> promptContext)
        {
            promptContext.Context.TurnState[Ids.PromptFailure] = true;
        }

        private static bool DidPrmptFail(WaterfallStepContext stepContext)
        {
            return stepContext.Context.TurnState.TryGetValue(Ids.PromptFailure, out var obj)
                && obj is bool failure
                && failure;
        }
```

**Comment by JonathanFingold** [comment]
PS. Sorry I didn't notice you were asking about the JavaScript SDK at first. Here's a link to the corresponding JavaScript property, [attemptCount](https://docs.microsoft.com/en-us/javascript/api/botbuilder-dialogs/promptvalidatorcontext?view=botbuilder-ts-latest#attemptcount). I don't yet have sample JavaScript code for this, but the logic should translate pretty well. Let me know if you have questions.

**Comment by MaartenBlomer** [comment]
Thanks for clarifying Jonathan. I should be able to proceed from here.
