### ISSUE TITLE
Sending a proactive message in v4 of the SDK?

### ISSUE THREAD

**Issue by RobRoseKnows** [MicrosoftDocs/bot-docs#1308]
This page is for v3 of the SDK, but the link for v4 documentation doesn't go to any specific page, just the general documentation. Is there a guide for sending proactive messages in v4 of the Bot Framework SDK?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da604d3a-5623-8092-9d4e-774177748d73
* Version Independent ID: ee9da6a5-2b55-d309-4a3a-b619583eeb3a
* Content: [Send proactive messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-proactive-messages?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/dotnet/bot-builder-dotnet-proactive-messages.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-proactive-messages.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi - Thanks for your feedback.

Please check this link [send proactive notifications to users](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp) for v4 documentation on this topic. We will update the link soon. 

Please let us know if it resolves your issue. 

Thanks.
