### ISSUE TITLE
We could not connect to the bot before sending a message.

### ISSUE THREAD

**Issue by mxxmusic** [MicrosoftDocs/bot-docs#1310]
get the message from bot channel issues:
"We could not connect to the bot before sending a message."
and from my app run the speech sdk get the message:

"
 CANCELED: Reason=1
CANCELED: ErrorCode=5
CANCELED: ErrorDetails=Connection was closed by the remote host. Error code: 1011. Error details: We could not connect to the bot before sending a message.
CANCELED: Did you update the subscription info?
"

why? 
I according to this page to setting my bot and my speech key region is westus2.

Please help?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4cb4da-ca0e-fc7f-686c-f3510bf9af0b
* Version Independent ID: e20d2896-dcec-8e46-2f50-2227def34250
* Content: [Connect a bot to Direct Line Speech (Preview) - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-directlinespeech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directlinespeech.md)
* Service: **bot-service**
* GitHub Login: @trrwilson
* Microsoft Alias: **travisw**

**Comment by JonathanFingold** [comment]
This, #1309, and #1311, all relate to the same topic, **Connect a bot to Direct Line Speech (Preview)**.

**Comment by mdrichardson** [comment]
@mxxmusic Can you verify that you checked the ["Enable Streaming Endpoint"](https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client#BotChannelRegistration) box and/or [toggled "Web sockets"](https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client#ToggleWebSocket) to On.

Make sure your Azure App Service is running. If it is, try restarting your App Service.

**Comment by mdrichardson** [comment]
@mxxmusic Were you able to get this resolved?

**Comment by mdrichardson** [comment]
Closing due to lack of response

**Comment by Batta32** [comment]
Hi @mdrichardson !  I have the same issue, I tried restarting the `App Service` but nothing has changed.

![image](https://user-images.githubusercontent.com/11904023/65269656-03aa2800-daf0-11e9-9012-3789a0dd1643.png)

I'm using [botbuilder-streaming-extensions](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder-streaming-extensions) to have the **WebSocket functionality**, and testing with [Direct Line Speech Client](https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client).
Also, i have the Direct Line Speech channel configured correctly.

Could be a problem of the bot?
Thanks!
