### ISSUE TITLE
Where is ConversationParameters object.

### ISSUE THREAD

**Issue by 404UsernameNotFound404** [MicrosoftDocs/bot-docs#1312]
I can only find the C# class ConversationParameters, but no reference to what this means in terms of the Bot Framework REST APi.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36ddb50-9e44-96e3-2df3-174166efa75d
* Version Independent ID: 68ac4b64-6616-2216-3519-e0b33d3a53e4
* Content: [API reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#create-conversation)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by 404UsernameNotFound404** [comment]
My goal is to post a conversation to a channel.

**Comment by JonathanFingold** [comment]
I'll need to add this back into the topic, since it is not described in the Bot Framework Activity schema.

description: | Parameters for creating a new conversation
-- | --
isGroup | Boolean
bot | ChannelAccount
members | Array of ChannelAccount
topicName | Optional, string - topic of the conversation (if supported by the channel)
tenantId | Optional, string - the tenant ID in which the conversation should be created
activity | Activity object
channelData | Optional, a channel-specific payload for creating the conversation.

**Comment by 404UsernameNotFound404** [comment]
Thanks for the quick response. I am still having some trouble creating the conversation.
How I am doing this is first messaging the bot, and getting the tenant ID of that person, and also saving the service URL, conversation reference. I then fire a get request to my bot to trigger the creation of the conversation.
The Error:
Error: Request failed with status code 400

Code:
server.get("/api/test", async (request, res) => {
  let configForPro = {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${saveChannelData.authToken}`
    }
  }
  await axios.post( `${saveChannelData.responseJson.serviceUrl}/v3/conversations`, {
   members: [{id: tennantIds[0].id}],
   activity: {text: 'first'},
   isGroup: false,
   bot: {id: 'd758d482-7ae7-425b-92a4-f849f8b57321'}
}, configForPro)
  .then(async (res) => {
    console.log(`statusCode: ${res.statusCode}`);
    console.log('ASDKASDA:KSKD IT WORKED');
   // for debugging purposes
    await adapterNew.createTeamsConversation(tennantIds[0].convoRef, tennantIds[0].id ,async 
    context => {
      await context.sendActivity(`This is a success sort of`);
    });
   //--------------------------
  })
  .catch(async (error) => {
    console.error('error')
    console.log(error);
 //for debugging purposes
    await adapterNew.createTeamsConversation(tennantIds[0].convoRef, tennantIds[0].id ,async 
    context => {
      await context.sendActivity(`This is def a error \n ${error}`);
    });
 //-------------------------
  })
  res.end();
});

**Comment by JonathanFingold** [comment]
The Bot Connector REST API is intended to be called from your bot code, as opposed to from your client/channel code. See the Direct Line topic on how to [start a conversation](https://docs.microsoft.com/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-start-conversation) from the client-side.

**Comment by 404UsernameNotFound404** [comment]
I don't know if that is the best option for me. I am trying to create a bot that can take a post request process the request, and create a new conservation in a teams conversation tab containing the post request data.

**Comment by JonathanFingold** [comment]
Here's the documentation for POST /v3/converstations from the Swagger file, with some annotations

Creates a new Conversation. [Bot is actually requesting that the channel creates the conversation, as the bot can't do so directly.]

POST to this method with a

- Bot being the bot creating the conversation
- IsGroup set to `true` if this is not a direct message (default is `false`)
- Array containing the members to include in the conversation
- An optional activity with which to seed the conversation

The return value is a `ResourceResponse` which contains a conversation ID which is suitable for use
in the message payload and REST API uris.

Most channels only support the semantics of bots initiating a direct message conversation. An example of how to do that would be:
```csharp
var resource = await connector.conversations.CreateConversation(
	new ConversationParameters() {
		Bot = bot,
		members = new ChannelAccount[] { new ChannelAccount("user1")
	});
await connect.Conversations.SendToConversationAsync(resource.Id, new Activity() ... );
```

However, if you're using the C# SDK, you can do this directly off a Bot Framework adapter: [BotFrameworkAdapter.CreateConversationAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.botframeworkadapter.createconversationasync?view=botbuilder-dotnet-stable). There is also a corresponding method in the JavaScript SDK.

**Comment by 404UsernameNotFound404** [comment]
Thanks that got it working.
