### ISSUE TITLE
localization for botframework v4

### ISSUE THREAD

**Issue by brynetwork** [MicrosoftDocs/bot-docs#1315]
Is there a documentation how to implement localization for botframework v4 [NodeJS]. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e9b932b-8f31-e07b-7ac3-9298047bccb1
* Version Independent ID: fbc204fc-4ab0-f370-043a-6bae9b4b7fd2
* Content: [Support localization - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-localization?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-localization.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-localization.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by JonathanFingold** [comment]
@brynetwork We don't explicitly cover this yet in the v4 docs. I'll let you know when we have some information available.

**Comment by brynetwork** [comment]
@JonathanFingold, Is there any reference that I can use to implement localization in botframework v4?

**Comment by JonathanFingold** [comment]
@brynetwork , channels should set the locale of message activities they send to the bot, available in the activity's _locale_ property. You can use this along with localized resources to localize your bot. The built-in prompts (such as the choice and confirm prompts) have support for the following languages already:
- de-de
- en-us
- es-es
- fr-fr
- ja-jp
- nl-nl
- pt-br
- zh-cn

**Comment by JonathanFingold** [comment]
@brynetwork The team is working on a [language generation](https://github.com/Microsoft/BotBuilder-Samples/tree/master/experimental/language-generation#readme) preview feature.

**Comment by JonathanFingold** [comment]
Closing, as there will be specific guidance adding within the next few release cycles.
