### ISSUE TITLE
Documentation is not clear enough for not advanced users

### ISSUE THREAD

**Issue by warnov** [MicrosoftDocs/bot-docs#1317]
Even when the command and parameters name used are correct, the context given to the reader is poor, specially in the deployment section. You should explain first to the reader what are you going to do before start shooting commands. Also there are some instructions that are not clear such as:
"Select all the files and zip them up while in that folder, then run the command while still in that folder." What command?
The hierarchy of this section is not well structured. The title: Retrieve or create necessary IIS/Kudu files appears to be inside: Deploy via ARM template (with existing Resource Group). This confuses a lot, because it belong more to the part of deploying the code of the bot to an already prepared resource group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi - thanks for your feedback. 

To answer your questions: 

1.	Some explanation to commands. 
We were wondering if you could tell us which specific commands you want us to explain? 

2.	Command to execute when “Select all the files and zip them up while in that folder, then run **the command** while still in that folder." 

**The command** refers to the Deploy code to Azure command mentioned in the next section. After you zip up the file, you execute the command as follows: 

```cmd
az webapp deployment source config-zip --resource-group "<new-group-name>" --name "<name-of-web-app>" --src "code.zip"
```  
3.	Hierarchy of this section (IIS/Kudu files appears to be inside: Deploy via ARM template). 
I think the IIS/Kudu files and Deploy via ARM template should be on the same level in Hierarchy and the confusion you had comes from the different font size. We will update the font size soon. 

Thanks again for your feedback. We really appreciate it. 
Please let us know if it helps.

**Comment by zxyanliu** [comment]
Hi - 

We also see your pr #1319 associated with this issue in MicrosoftDocs/bot-docs. We are currently looking into it and will get back to you soon. 

Thanks again for your feedback. We really appreciate it. 

Best, 

Yan

**Comment by zxyanliu** [comment]
Hi -

We are closing this issue due to duplication of #1319. 

We are currently working on your suggestions, please see [#1659](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1659). 

Thanks again for feedback. We really appreciate it. 

Best,

Yan
