### ISSUE TITLE
Which method is preferred to add video

### ISSUE THREAD

**Issue by wilmol** [MicrosoftDocs/bot-docs#1320]
So you can add with media URL or VideoCard, which is preferred?

I see there is also AdaptiveCard and TaskModule. 

So 4 ways for my bot to send video.

I guess the answer is "it depends?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b3009c-7efa-e1bb-fa2d-516d134b3a96
* Version Independent ID: e91d90a7-8478-a1d3-2d0b-89cbdaff275c
* Content: [Add media attachments to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-media-attachments?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/rest-api/bot-framework-rest-connector-add-media-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-add-media-attachments.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by v-kydela** [comment]
Hi @wilmol 

You are correct that the preferred method does depend on a few things. Task modules are only available in Teams, and they have a very different appearance from attachments. They are more like modal dialogs than messages. Adaptive Cards added support for video in 1.1, so channels that don't support Adaptive Cards 1.1 cannot use video in Adaptive Cards. As with everything, it's strongly recommended that you test your video option in every channel client you're targeting, no matter which option you choose.

Does this resolve your issue?

**Comment by wilmol** [comment]
@v-kydela yes, thank you.

**Comment by zxyanliu** [comment]
Hi@wilmol thanks for bringing up this issue, and @v-kydela thanks for your quick response.
