### ISSUE TITLE
No Javascript telemetry example

### ISSUE THREAD

**Issue by iMicknl** [MicrosoftDocs/bot-docs#1325]
Page is missing a Javascript example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db892de5-e60e-1d4f-505b-11b1cdb73323
* Version Independent ID: f7263014-b8fa-9a20-71aa-e4217b2821ee
* Content: [Add telemetry to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-telemetry.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-telemetry.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by scheyal** [comment]
Can you please update status on this?

**Comment by WashingtonKayaker** [comment]
I think I can start on this early next week.

**Comment by iMicknl** [comment]
Any update? I was looking for this content (again) and realised it still hasn't been added...

**Comment by niks3089** [comment]
Unable to use telemetry without this

**Comment by iMicknl** [comment]
@garypretty do you know if this is still necessary with all the changes coming, or is my request obsolete already.

**Comment by asp1egui** [comment]
for javascript you can use this example https://docs.microsoft.com/en-us/azure/azure-monitor/app/nodejs, there is a doc for python too. Don't know why they put there when they could have put it here tho

**Comment by WashingtonKayaker** [comment]
Sorry for the delays, the JavaScript sample is available and the [Add telemetry to your bot](https://docs.microsoft.com/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0&tabs=javascript) article has been updated to include information on how to add telemetry to your bot developed using JavaScript.
