### ISSUE TITLE
New conversation started after every 21 messages

### ISSUE THREAD

**Issue by arnoldpistorius** [MicrosoftDocs/bot-docs#1326]
Hi,

I have expanded the echo bot to have the Speak field set to the incoming message. When I use the Direct Line Speech Client v1.0.0 I can speak a message to the bot and the bot repeats the message. Okay, so far, so good! When I continue the conversation, after the 21st message I send, a new Conversation is received in the bot, causing the bot to start at the beginning of the flow. 

At first I thought it was a mistake in my code, but the official demo application has the same behavior.

Is this some Preview limitation (or bug perhaps?) or will this behavior also be in production?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4cb4da-ca0e-fc7f-686c-f3510bf9af0b
* Version Independent ID: e20d2896-dcec-8e46-2f50-2227def34250
* Content: [Connect a bot to Direct Line Speech (Preview) - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-directlinespeech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directlinespeech.md)
* Service: **bot-service**
* GitHub Login: @trrwilson
* Microsoft Alias: **travisw**

**Comment by stevkan** [comment]
Can you list any changes, if any, that you made to the Echo bot, including updating of Nuget packages, addition of a SpeechConfig, etc.? Also (without revealing any keys/secrets) can you list what settings you have in the Direct Line Speech Client?

Out of curiosity, is this behavior specific to using the Direct Line Speech service? Have you tested sending multiple text utterances through the bot via other channels (Emulator, web chat, etc.) to be certain it is specific to Direct Line Speech?

**Comment by arnoldpistorius** [comment]
Hi,

Thanks for your reply. The changed code of the Echo bot is attached below. I've tried also to send only text messages by typing them in the bar where the recognized text is displayed. This seems to work, the same conversation is still going on after 30 messages. However when I try it again, but with speech (pressing the mic) after 21st message I get the "Hello and welcome" message. The conversation ID is also changed when debugging the bot.

```
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Schema;

namespace EchoBotSpeech.Bots
{
    public class EchoBot : ActivityHandler
    {

        private static List<ITurnContext> _log = new List<ITurnContext>();

        protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            if (turnContext.Activity.Type == ActivityTypes.Message)
            {
                var msg = MessageFactory.Text($"Echo: {turnContext.Activity.Text}");
                msg.Speak = turnContext.Activity.Text;
                await turnContext.SendActivityAsync(msg, cancellationToken);
            }
        }

        #region Overrides of ActivityHandler

        /// <inheritdoc />
        public override Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = new CancellationToken())
        {
            _log.Add(turnContext);
            return base.OnTurnAsync(turnContext, cancellationToken);
        }

        #endregion

        protected override async Task OnMembersAddedAsync(IList<ChannelAccount> membersAdded, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {

            foreach (var member in membersAdded)
            {
                if (member.Id != turnContext.Activity.Recipient.Id)
                {
                    var msg = MessageFactory.Text($"Hello and welcome!");
                    msg.Speak = "Hello and welcome!";

                    await turnContext.SendActivityAsync(msg, cancellationToken);
                }
            }
        }

        #region Overrides of ActivityHandler

        /// <inheritdoc />
        protected override Task OnUnrecognizedActivityTypeAsync(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            return base.OnUnrecognizedActivityTypeAsync(turnContext, cancellationToken);
        }

        #endregion
    }
}
```

**Comment by arnoldpistorius** [comment]
@stevkan Do you need more information?

**Comment by stevkan** [comment]
Can you list the speech client settings you have configured? I’d like to replicate this as closely as possible.

Also, if you could list the nugget package versions, I would appreciate it.

**Comment by arnoldpistorius** [comment]
Hi @stevkan 

See the information below.

packages.config:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AdaptiveCards" version="1.2.0" targetFramework="net461" />
  <package id="AdaptiveCards.Rendering.Wpf" version="1.2.0" targetFramework="net461" />
  <package id="AdaptiveCards.Rendering.Wpf.Xceed" version="1.2.0" targetFramework="net461" />
  <package id="BuildTools.FxCop" version="1.0.1" targetFramework="net461" />
  <package id="Extended.Wpf.Toolkit" version="3.5.0" targetFramework="net461" />
  <package id="Jot" version="1.4.1" targetFramework="net461" />
  <package id="Microsoft.Bot.Schema" version="4.4.5" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.FxCopAnalyzers" version="2.9.2" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.VersionCheckAnalyzer" version="2.9.2" targetFramework="net461" />
  <package id="Microsoft.CodeQuality.Analyzers" version="2.9.2" targetFramework="net461" />
  <package id="Microsoft.CognitiveServices.Speech" version="1.6.0" targetFramework="net461" />
  <package id="Microsoft.CSharp" version="4.5.0" targetFramework="net461" />
  <package id="Microsoft.MarkedNet" version="1.0.13" targetFramework="net461" />
  <package id="Microsoft.NetCore.Analyzers" version="2.9.2" targetFramework="net461" />
  <package id="Microsoft.NetFramework.Analyzers" version="2.9.2" targetFramework="net461" />
  <package id="NAudio" version="1.9.0" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="12.0.2" targetFramework="net461" />
  <package id="SourceLink.Create.CommandLine" version="2.8.3" targetFramework="net461" developmentDependency="true" />
  <package id="StyleCop.Analyzers" version="1.1.118" targetFramework="net461" developmentDependency="true" />
</packages>
```

Screenshots of my settings:

![image](https://user-images.githubusercontent.com/6072267/63687182-27859100-c804-11e9-8d4a-32fb5ced5cc4.png)

![image](https://user-images.githubusercontent.com/6072267/63687213-3d935180-c804-11e9-83d7-a2bc9acf1be7.png)

**Comment by stevkan** [comment]
@arnoldpistorius, thank you for your patience while I try and work through this. There are a few configuration points that I'm trying to manage. I hope to have something to report to you before much longer. In the mean time, are you logging any errors when the conversation resets?
Also, as only the subscription key and region are required, does this problem persist if you remove the values for "User From Id:" and "Language:" fields?

**Comment by CoHealer** [comment]
@arnoldpistorius, it's been a couple of weeks. Do you still require assistance or should the issue be closed?

**Comment by arnoldpistorius** [comment]
No, the issue remains even when leaving from Id and Language fields blank.

**Comment by stevkan** [comment]
I'm not able t o replicate the issue as you have described it. I did notice that there is a variation in the code you supplied compared to the Echo bot sample provided in the Experimental/directline-speech folder, located [here](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/directline-speech/csharp_dotnetcore/02.echo-bot).

Can you download and run this sample, as-is, and see if it persists for you? This sample is already configured for DL Speech. The only item you will need to change is the appsettings.json file by including your bot's AppId and AppPassword.

**Comment by CoHealer** [comment]
@arnoldpistorius, do you still require assistance? To keep the issue open we need activity on the thread.

**Comment by stevkan** [comment]
Closing issue due to a lack of activity. If the issue persists or you have new information to provide regarding this issue, please feel free to reopen.
