### ISSUE TITLE
Link broken: 

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/bot-docs#1330]
Doc:  https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-recognize-intent-messages?view=azure-bot-service-3.0

Text:  
Use **RegExpRecognizer** to detect the user's intent using a regular expression. You can pass multiple expressions to the recognizer to support multiple languages.

Points to: https://docs.botframework.com/node/builder/chat-reference/classes/_botbuilder_d_.regexprecognizer.html

Whic is not resolved.

**Comment by JonathanFingold** [comment]
Looks like this is the correct target. Will fix this soon.

https://docs.microsoft.com/javascript/api/botbuilder/regexprecognizer?view=botbuilder-ts-3.0

**Comment by JonathanFingold** [comment]
Addressed in PR. Fix should go live soon.
