### ISSUE TITLE
Why do media cards allow multiple media URL's?

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1336]
This document suggests that media cards (animation, audio, video) play multiple files one after the other. The documentation in the Swagger file suggests that the multiple files are meant to be the same content in different formats: https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-protocol/botframework-channel.json

This should be investigated to see what really happens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36ddb50-9e44-96e3-2df3-174166efa75d
* Version Independent ID: 68ac4b64-6616-2216-3519-e0b33d3a53e4
* Content: [API reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#animationcard-object)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
See **bot-docs-pr** [PR 1698](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1698) for more context.

**Comment by mmiele** [comment]
Work in progress.
See PR: https://github.com/MicrosoftDocs/bot-docs-pr/pull/1712

**Comment by mmiele** [comment]
You can find the staged document at this location: https://review.docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-3.0&branch=pr-en-us-1712

**Comment by mmiele** [comment]
Issue resolved. See also spec definition: https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-cards.md#media-card-media.
The updated article will be available in the next doc build.
