### ISSUE TITLE
Please update with all 7 card action properties

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1337]
The properties are channelData, displayText, image, text, title, type, and value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4df548-56f2-4601-31d8-58a3237fd867
* Version Independent ID: ec4ede13-b432-61bb-5de8-1ed88bf36e17
* Content: [Add rich card attachments to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-rich-cards?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-add-rich-cards.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-add-rich-cards.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
See **bot-docs-pr** [PR 1698](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1698) for more context.

**Comment by emgrol** [comment]
Article has been updated in [PR 1703](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1703).  Closing this issue, the changes will go live this afternoon.
