### ISSUE TITLE
Broken links in the What's new page

### ISSUE THREAD

**Issue by gabog** [MicrosoftDocs/bot-docs#1338]
The underlying aka.ms links for the testing pages are broken in the What's new page (they return 404s)

https://aka.ms/testing-framework
https://aka.ms/corebot-test
https://aka.ms/js-core-test-sample

![image](https://user-images.githubusercontent.com/12264946/63911852-c7f0d680-c9f9-11e9-99c0-c5f90f922702.png)

**Comment by mmiele** [comment]
Gabo would you mind to send the article link? Thanks

**Comment by JonathanFingold** [comment]
@mmiele [What's new](https://docs.microsoft.com/en-us/azure/bot-service/what-is-new?view=azure-bot-service-4.0)

@gabog The dev team must have moved these within the last two weeks. Do you know what the new targets are?

**Comment by gabog** [comment]
I exchanged some IMs with @mmiele, but just for the record:

- http://aka.ms/bot-test-package points to https://www.nuget.org/packages/Microsoft.Bot.Builder.Testing/ that is just C#, there is also an npm package for JS
- https://aka.ms/testing-framework  should point to https://docs.microsoft.com/en-us/azure/bot-service/unit-test-bots
- https://aka.ms/corebot-test should point to https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/13.core-bot.tests (there is also an https://aka.ms/cs-core-test-sample that points to the right location, it may be better to use that one in the future but it will require a docs update).
- https://aka.ms/js-core-test-sample seems to be fine (there is also an https://aka.ms/js-core-test-sample that points to the right location, it may be better to use that one in the future but it will require a docs update).

**Comment by emgrol** [comment]
Hi @gabog, I've addressed these links in [PR 1701](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1701). Here's a short summary of the changes I made:

- I removed the bot-test-package URL and added new ones for the npm and NuGet botbuilder-testing packages: https://aka.ms/npm-botbuilder-testing and https://aka.ms/nuget-botbuilder-testing. I've updated the What's New article to reference both.
-  https://aka.ms/testing-framework points to the [correct](https://aka.ms/testing-framework) page now.
- corebot-test has been removed and https://aka.ms/cs-core-test-sample is now used throughout the docs.
- Didn't see the duplicate here (same vanity name, js-core-test-sample, mentioned both times). I don't see any other vanity names pointing to that URL either, so no changes there.

**Comment by gabog** [comment]
thanks @emgrol, I reviewed the changes and they look good, I think they can be merged into master.

**Comment by emgrol** [comment]
Glad to hear it @gabog, and thanks for reviewing the PR! Closing this issue now that the content is updated (changes will go live tonight).
