### ISSUE TITLE
Insert bot token

### ISSUE THREAD

**Issue by ThanosX1980** [MicrosoftDocs/bot-docs#1340]
You did not explain exactly where you insert the bots token. Where??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 260c283c-f5e9-e00d-19ec-ee9df18335e5
* Version Independent ID: d1525408-36d3-6575-2331-a16379744a59
* Content: [Create a bot for Telegram - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-telegram?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-telegram.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-telegram.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Hi @ThanosX1980, I agree it's not exactly clear where to put the bot token. I'm currently working on figuring out where that field is and will let you know once the docs are updated.

**Comment by emgrol** [comment]
Closing this issue now that the updated instructions are live.
