### ISSUE TITLE
Could you reduce number of nuget packages mentioned? We need just 1 and it will reference 2 others

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/bot-docs#1342]
Could you reduce number of nuget packages mentioned? We need just 1 and it will reference 2 others
Microsoft.Bot.Builder.Integration.ApplicationInsights.Core is just enough. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db892de5-e60e-1d4f-505b-11b1cdb73323
* Version Independent ID: f7263014-b8fa-9a20-71aa-e4217b2821ee
* Content: [Add telemetry to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-telemetry.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-telemetry.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

![image](https://user-images.githubusercontent.com/578954/64328628-77b7dc80-cfd6-11e9-88fe-10f03f9f6061.png)

**Comment by emgrol** [comment]
Thanks for the suggestion @SychevIgor. I've updated the article in this [PR](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1720); the changes will go live later today.
