### ISSUE TITLE
Missing V4 page for: Recognize user intent from message content

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/bot-docs#1344]
We need equivalent documentation (& capability) for V4. Link is broken:

https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-recognize-intent-messages?view=azure-bot-service-3.0
…

This topic applies to SDK v3 release. You can find the documentation for the latest version of the SDK v4 **_here_** (link broken).

**Comment by emgrol** [comment]
Hi @scheyal, the link isn't actually broken, it should be pointing to our docs home. 

We point to [v4 docs](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-recognize-intent-luis?view=azure-bot-service-3.0) in the second note on the page.  I think the old methods for intent recognition are deprecated so I'm not sure if we need new articles, but do let me know if I'm mistaken.

**Comment by JonathanFingold** [comment]
Closing, as the banner with associated link is no more, now that the v3 docs are archived.
