### ISSUE TITLE
The Channel Inspector is gone

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1345]
We shouldn't be trying to link to a tool we deprecated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bd6cc54-ac88-582c-08d7-2d15ebea70ef
* Version Independent ID: 80052090-93be-0674-59d4-4c676fd22bd9
* Content: [Add suggested actions to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-suggested-actions?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-add-suggested-actions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-add-suggested-actions.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out, @v-kydela. I've opened a [PR](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1742) that shows all mentions of Channel Inspector have been removed from the article.

**Comment by emgrol** [comment]
The changes are live, closing this issue now.
