### ISSUE TITLE
The Adaptive Card sample should not use Action.Http

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1346]
[Action.Http](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card#actionhttp) is only for Outlook actionable messages. [This is confusing some customers.](https://github.com/MicrosoftDocs/bot-docs/issues/1343) Please replace this with a card that follows the [Adaptive Cards schema](https://adaptivecards.io/explorer/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4df548-56f2-4601-31d8-58a3237fd867
* Version Independent ID: ec4ede13-b432-61bb-5de8-1ed88bf36e17
* Content: [Add rich card attachments to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-rich-cards?view=azure-bot-service-3.0#adaptive-card)
* Content Source: [articles/rest-api/bot-framework-rest-connector-add-rich-cards.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-add-rich-cards.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out @v-kydela. Do you think the Adaptive Card on [the Schema Explorer](https://adaptivecards.io/explorer/AdaptiveCard.html) works, or would you recommend another card?

**Comment by v-kydela** [comment]
@emgrol - Yes, I believe that standard sample card is fine. Thanks for asking!

**Comment by emgrol** [comment]
Updated the card and text describing it. Closing now that the changers are merged.
