### ISSUE TITLE
Proactive messages Timer Example

### ISSUE THREAD

**Issue by esanchezlMBT** [MicrosoftDocs/bot-docs#1347]
Is there any example to send a proactive message to notify a user when a timer expires.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521a9f9a-025c-c55b-c939-d9d4efc5c6d0
* Version Independent ID: 3bcafb54-f7eb-54f5-1d78-5f2087e2e2dc
* Content: [Send proactive notifications to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=javascript#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by RICKROSSWIFEINGRIDE** [comment]
MEEK MILL SAID GET THE FREAK OF MY MUTHA FREAKING APPS YOU COCKROCHES
