### ISSUE TITLE
Partially working for me

### ISSUE THREAD

**Issue by r3dr4gon** [MicrosoftDocs/bot-docs#1348]
I did everything this page said but, when I run the chatbot locally and use the emulator:
1. I can only use the mic once, after i do and it recored the answer I can not click the mic again (maybe this is emulator bug?!)
2. I can't seems to make the the bot speak, I have the base of a QnA bot and I modified the line in OnMessageActivityAsync func to: 
await turnContext.SendActivityAsync(Speak(response[0].Answer), cancellationToken);
Which for my understanding should result in the bot speaking all the answers back to me, but so far I hear nothing back (I do still see written responses though).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0b8671-359e-6026-fd3a-39331cea73f3
* Version Independent ID: 29bab4ad-243a-fb0a-99ed-d8336a92f648
* Content: [Develop DirectLine Speech Bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/directline-speech-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/directline-speech-bot.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@r3dr4gon Thank you for contacting us.

Could you please send us more details. specifically:

1) The link to the example bot you are using. Are you using the example listed in this article: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs?
2) Are you using a microphone with your example?
3) How are you using the direct line that you refer from this article https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0? 
4) Please send any additional information that could help.

**Comment by r3dr4gon** [comment]
Sorry for the delay.

What I did was:
1. using the QA bot example provided by microsoft (I did use it and test it locally and everything worked). which located in here:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp
2. modifyed the bot code to according to:
https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/directline-speech-bot.md
(option 1)
3. ran the bot locally.
4. open the bot emulator and interact with the bot.

I can say that so far:
1. if i try to test my bot in azure, it won't even load (the test option of "test in web chat" under the web app bot resource).
2. I have almost the same problem when using the JS client see:
https://github.com/microsoft/BotFramework-WebChat/issues/2405
3. I tried also:
https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client
this works perfectly (I can recored and make the bot speak using the same bot as before).
I think the only "different" is that in this example it use the direct line speech channel directly, as oppose to the JS client (which seems to have a bug when using subscription and not token), and as oppose to the local bot which I have no idea what "channel" he connects to.

**Comment by r3dr4gon** [comment]
The problem I had with the JS chat was solved, as you can see here:
https://github.com/microsoft/BotFramework-WebChat/issues/2405

However, the emulator has still the same problems, i.e., recored my speech one time answer without voice, and won't let me use the mic anymore (I also only see 200 in the debug menu.)

**Comment by dargilco** [comment]
May I ask what is your application? Do you want voice input/voice output communication with your bot? If so, you can use Direct Line Speech channel, and use the Speech SDK in your client application to set up the connection with the channel and you bot. This is what the Direct Line Speech Client sample app on GitHub did. That seemed to be working for you.

**Comment by r3dr4gon** [comment]
Hey @dargilco, Well my end result is a bot that works only via voice usage.
However, the bot will be run via electron app (so JS), and as far as I saw direct line speech doesn't work with JS, so that is too bad for me...
I did manage to make my javascript chat working in the end as you can see with the link i posted, I'm just sticking to this post to maybe try help and fix this bug if it is indeed there (and it is not my mistake).

**Comment by dargilco** [comment]
You should be able to write a JS bot that support streaming extension and register it with Direct Line Speech channel. The npm packages for JS streaming extension are all published and [there is sample code](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/directline-speech/javascript_nodejs/02.echo-bot). We need to update [our documentation](https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0) to mention support for JS as well as C#.
If for some reason you cannot get it to work I would like to hear about it and we will investigate.
Darren

**Comment by RICKROSSWIFEINGRIDE** [comment]
YOU #1FRAUd

**Comment by r3dr4gon** [comment]
Hey @dargilco, I think I was unclear (or i did not understand you). So I will try to rephrase myself.
My bot is written in c# and hosted on azure. The bot client will is written in JS (as part of electron app).

Honestly, I'm a bit confuse about the difference between direct line speech and direct line. Right now I have a JS client that use both speech and my QnA bot (to do so I use direct line key).
I basically implemented this sample:
https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.c.cognitive-services-speech-services-js
Is there other way to do it that would use direct line speech that would be better?

**Comment by dargilco** [comment]
Speech SDK does not yet have a JS implementation for the Microsoft.CognitiveServices.Speech.Dialog namespace. We know there is strong demand for it and we are looking into it.  So unfortunately at this time you cannot use Direct Line Speech from a JS client.

**Comment by mmiele** [comment]
Documentation updated to reflect current Direct Line Speech preview. The updated documentation will be in the next doc build.

**Comment by mmiele** [comment]
The updated documentation that reflects the latest Direct Line Speech preview will be available in the next doc build. Informed the proper team about the emulator issue.

**Comment by dargilco** [comment]
Thanks!
