### ISSUE TITLE
Typescript Bot Tutorial zip guidance unclear

### ISSUE THREAD

**Issue by georgeedwards** [MicrosoftDocs/bot-docs#1350]
Following on from the discussion on PR #1319 - When following the guidance for a bot with typescript, the  project root and the folder with `index.js` are different. 

In response to your last comment: 

@zxyanliu Thank you very much for coming back to me. I think this is getting at the issue. When following the tutorial (if using Typescript and the yo generator). Then the root project file loooks like this:

[![enter image description here][1]][1]

So following the guidelines of the tutorial which say:
```
Before zipping your project files, make sure that you are in the project folder.

For C# bots, it is the folder that has the .csproj file.
For JS bots, it is the folder that has the app.js or index.js file.
```

I think this is an issue? Or have I missunderstood something? 

  [1]: https://i.stack.imgur.com/GfWgS.png

**Comment by zxyanliu** [comment]
Hi @georgeedwards Thanks for reaching out. 

This is my understanding of your issue before I help. Please correct me if I am wrong. 
- You have a TypeScript bot developed on your local machine using yo generator and you wanted to deploy the bot to Azure. 
- You followed the steps in this [deploy](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)  article. 
- When it came to the step of zipping up the project folder, you found details in regard to TypeScript bot missing. 

Please let me know if i understand your issue correctly so that I can start addressing it.

Best, 

Yan

**Comment by georgeedwards** [comment]
@zxyanliu Hi Yan,

Yes - that is the issue. Or at least, When it came to the step of zipping up the project folder, I found there should be different instructions for Typescript as the project structure is different from the JS version.

**Comment by zxyanliu** [comment]
Hi @georgeedwards,
Thanks for your clarification. We are currently looking into this issue.
May I ask which tutorial did you follow to create your Typescript bot using yo template? 

Yan

**Comment by georgeedwards** [comment]
@zxyanliu Sure - [this](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=javascript) one

**Comment by zxyanliu** [comment]
Hi @georgeedwards 
I have reproduced your issue and got my TypeScript bot deployed with success. 

FYI. Here are the steps I followed in this [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=typescript). 

1. Created a TypeScript bot using yo template in this [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=javascript) and tested in emulator with success. 

2. Azure login, set up subscription, and created Azure app registration.  

3.  Deploy via ARM template with new Resource Group 
![image](https://user-images.githubusercontent.com/32497439/65449042-fc846200-ddee-11e9-9d62-8769a71cc2c7.png)

4. Zip up your project folder - this is where @georgeedwards got stuck. 
- In your bot's project folder, run the following command:
`az bot prepare-deploy --code-dir "." --lang Typescript`

- After you run this command, you will have a _web.config_ file in the project folder and the src folder. 

![image](https://user-images.githubusercontent.com/32497439/65460560-0c0fa500-de07-11e9-9494-e20d74dd73f5.png)

![image](https://user-images.githubusercontent.com/32497439/65460562-0f0a9580-de07-11e9-8dbb-adfaab544ec7.png)

- Within the bot's project folder, you select all files and zip them up. You will have a _.zip_ file generated within your project folder. The name of the _.zip_ file may differ.  

![image](https://user-images.githubusercontent.com/32497439/65460593-22b5fc00-de07-11e9-9227-2fe2ecf31f90.png)

- Then, you run the command to deploy your code. 

`az webapp deployment source config-zip --resource-group "yl-TypescriptBot" --name "yl-TypescriptBot" --src "src.zip"`

5. Tested in web chat 

![image](https://user-images.githubusercontent.com/32497439/65460738-6f013c00-de07-11e9-8bf0-3c7553bf4e83.png)

Please try again and let me know if you have further questions. 

Yan Liu

**Comment by zxyanliu** [comment]
Updated contents alive and therefore closing the issue.
