### ISSUE TITLE
Does Microsoft Teams support multi-turn?

### ISSUE THREAD

**Issue by jwatkin** [MicrosoftDocs/bot-docs#1351]
Will Microsoft Teams support QnA Maker's multi-turn feature without having to write any code? When I tried this quick test method in Microsoft Teams, my multi-turn prompts don't appear. What did you mean when you wrote, "Adding a bot by GUID, for anything other than testing purposes, is not recommended. Doing so severely limits the functionality of a bot." Will multi-turn work if I package this as an app? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e31fe2a-ac8e-815c-f33e-2f08fd554915
* Version Independent ID: e4b7dd0b-e9c9-00d8-41ea-f2ecbbb68752
* Content: [Connect a bot to Teams - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0)
* Content Source: [articles/channel-connect-teams.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/channel-connect-teams.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by clearab** [comment]
For the question about adding a bot by GUID: If you do not install your bot as part of a Teams app (in an app package), you will not have access to any Teams-specific information or API calls, and authentication will not work. Use the App Studio app inside of Teams to quickly create an app package and install it. See: [Getting Started with App Studio](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio).
