### ISSUE TITLE
Why is Active directory not listed

### ISSUE THREAD

**Issue by xtianus79** [MicrosoftDocs/bot-docs#1353]
Should active directory be listed here? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58bf70a-3263-93a1-5bc2-085431a7aa6b
* Version Independent ID: c5e3de2f-58ad-1c6a-e0f3-93489d013114
* Content: [Authenticate requests - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/rest-api/bot-framework-rest-connector-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-authentication.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@xtianus79 The term AAD refers to Azure Active Directory. I've asked a developer for further clarification. I'll update the article to be more clear on this point once I hear back from the dev.

**Comment by JonathanFingold** [comment]
@xtianus79 A fix is in PR and should go live within a couple days. Please reopen if this does not address your issue.
