### ISSUE TITLE
Next Steps link missing

### ISSUE THREAD

**Issue by AbhasBrahma** [MicrosoftDocs/bot-docs#1354]
Next Steps link missing in https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-principles?view=azure-bot-service-4.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2129465a-984b-4420-c3a4-1a8587df7cd1
* Version Independent ID: 331eb5d6-edf6-c2b1-6efb-84ace29256ae
* Content: [Principles of bot design - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-principles?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-design-principles.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-principles.md)
* Service: **bot-service**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by emgrol** [comment]
Thanks for bringing this to our attention @AbhasBrahma. I've update the article in [PR 1738](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1738).

**Comment by emgrol** [comment]
The changes are live, closing this issue now.
