### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by XiaolouT** [MicrosoftDocs/bot-docs#1355]
When I tried to access https://&lt;your_app_service&gt;.azurewebsites.net/.bot, and got
{ "k": true, "ib": false, "ob": false, "initialized": true }

what does this mean？  Is there something wrong? Could you share the whole sample code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72c259-a864-9e1c-b585-562d6bca80ff
* Version Independent ID: 30a3fce8-d236-5c7b-88a0-003c971f2819
* Content: [.NET bot with direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@XiaolouT Thank you for contacting us.
Try to enter https://<your_app_service>.azurewebsites.net/.bot/ with forward slash "/" after "bot". Obviously, replace "<your_app_service>" with your actual address. Let us know if this solves the problem.

**Comment by marthinsteyn** [comment]
Hi. I'm getting the same issue.  Do you have any feedback on this?

**Comment by ysisco** [comment]
Hi, i have the same problem , i have two bot service, both are running but one work correctly for moments the other dont work. somebody resolve it?

**Comment by ysisco** [comment]
> @XiaolouT Thank you for contacting us. Let me look into this.

hi, i have the same problem using Directline app service extension, do you solve this situation?

**Comment by ysisco** [comment]
> Hi. I'm getting the same issue. Do you have any feedback on this?

HI, I have the same issue too, do you can resolve it? how you resolve it? , thanks

**Comment by mmiele** [comment]
Added missing information. The updated article will be available in the next doc build.

**Comment by mmiele** [comment]
This is the information you obtain when **everything works correctly**, so nothing is wrong; where
 
- **k** determines whether Direct Line App Service Extension (ASE) can read an extension key from its configuration. 

- **initialized** determines whether Direct Line ASE can use the extension key to download the bot metadata from Azure Bot Service

- **ib** determines whether Direct Line ASE can establish an inbound connection with the bot.

- **ob** determines whether Direct Line ASE can establish an outbound connection with the bot.

**Comment by thirumaran007** [comment]
We are getting this issue again ,{ "k": true, "ib": false, "ob": false, "initialized": true }. Not sure where we need to check ob and ib. Please advice on this , thanks!
