### ISSUE TITLE
this phrasing is misleading

### ISSUE THREAD

**Issue by xtianus79** [MicrosoftDocs/bot-docs#1356]
QnA Maker	In the QnA Maker portal, for the knowledge base, in the Manage settings, use the key value shows in the Postman settings for the Authorization header, without the text of EndpointKey. 

it is not in the manage settings of the qna maker portal?  it is in the azure portal for the service. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@xtianus79 - Thank you for creating this issue - can you be more specific with what you think is incorrect? #in-progress

**Comment by xtianus79** [comment]
@diberry Hi Dina :) Yes, the using of the phrase endpoint key is something it actually wants from the azure service as opposed to the authoring endpoint key that is given in the Azure portal.  That is what hung me up for a while.  Specifically it is where one should obtain the key that would fix all understanding from my perspective.

**Comment by diberry** [comment]
@xtianus79 Thank you for clarifying. The better explanation is in the QnA Maker docs - I'll link to that. https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/set-up-qnamaker-service-azure#types-of-keys-in-qna-maker.

**Comment by diberry** [comment]
Fixed - #please-close

**Comment by dkonyayev** [comment]
Can we get a recommendation on how to build a script file with CLI commands? I tried to build the regular file.bat and run it in command prompt, but it would stop executing on first dispatch command.

**Comment by diberry** [comment]
@dkonyayev which operating system and flavor of command prompt are you using?

**Comment by dkonyayev** [comment]
@diberry I was able to resolve this. Added "call" command before "dispatch"

**Comment by diberry** [comment]
This second issue seems to be resolved. #please-close

**Comment by diberry** [comment]
@emgrol please-close
