### ISSUE TITLE
"Activity class" link is broken 

### ISSUE THREAD

**Issue by dargilco** [MicrosoftDocs/bot-docs#1358]
The "Activity class" link under "Additional resources" is broken.
Thanks,
Darren

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 122e1e45-a823-4acd-c082-60041e9e3584
* Version Independent ID: e2dd9c08-1951-b3b9-9f67-a3d948b26732
* Content: [Activities overview - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-activities?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-activities.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-activities.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for bringing this to our attention @dargilco. I've update the link in [PR 1737](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1737), and the changes should go live within a day.

**Comment by emgrol** [comment]
The changes are live, closing this issue now.
