### ISSUE TITLE
'Longitude' name twice

### ISSUE THREAD

**Issue by rudifus** [MicrosoftDocs/bot-docs#1364]
'Longitude' name twice in the list of geoCoordinates, just to mention :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53617abe-a774-a211-390b-b2f0261c5bb6
* Version Independent ID: f1533f6c-f340-f838-d95b-ca5b6cd4b6dd
* Content: [Entities and activity types - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-activities-entities?view=azure-bot-service-4.0&tabs=cs#feedback)
* Content Source: [articles/bot-service-activities-entities.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-activities-entities.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out @rudifus! I've updated the table in [PR 1752](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1752) and the changes will go live tonight.

**Comment by emgrol** [comment]
Closing this now that the changes are live.
