### ISSUE TITLE
This isn't how we want developers to prompt users for input

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1365]
This document contains great information in that it explains how we would have to implement prompts if we didn't have the dialogs library, thus demonstrating the need for the dialogs library. However, it's very confusing to present this as "how to prompt users for input" when this isn't actually how we want developers to prompt users for input. I think this document should be renamed to something more like "prompting users without dialogs" and it should go somewhere other than the how-to section, like the concepts section perhaps. Maybe we need to create a new subsection for more abstract background information like this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79129724-5f90-ac8d-6918-d5801a4e2001
* Version Independent ID: 08e19b7b-2ec6-95da-2f5a-d534e761f5da
* Content: [Create your own prompts to gather user input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-primitive-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-primitive-prompts.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@v-kydela Given this topic's history, I think we need to keep it close to where it is. There was a rather forceful demand for this specific topic. As to proper framing, I agree that we could do a much better job in the intro, and basically tell devs to move on to the conversation flow topic unless they want to "roll their own".

Marking as backlog for now.

**Comment by shikshik** [comment]
I must admit it also made everything confusing for me as I'm new to this framework.
Examples and tutorials should express real-life applications.

Other than that, the framework is awesome, but docs really need more updates.
Cheers!

**Comment by robertwood62** [comment]
I agree that this isn't exactly what I was looking for.  I'd like to see documentation on deriving from the Prompt class to create your validation.  For example, validating an address.  I'd also like to see the prompt handle scenarios such as 1) address not found, retry.  2) Single address found (confirm with yes/no) 3) Multiple addresses found, pick one.  It's also not clear what the event lifecycle is for OnPromptAsync and OnRecognizerAsync and what code should go where.

**Comment by JonathanFingold** [comment]
@robertwood62 
- See [Implement sequential conversation flow](https://docs.microsoft.com/azure/bot-service/bot-builder-dialog-manage-conversation-flow) for an example of using prompts within dialogs.
- For more complex data structures, you could create a component dialog. See [Reuse dialogs](https://docs.microsoft.com/azure/bot-service/bot-builder-compositcontrol) for an example.
- The other two main dialog how-to articles may also be helpful, for managing more complex conversation flow:
  - [Create advanced conversation flow using branches and loops](https://docs.microsoft.com/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow)
  - [Handle user interruptions](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-handle-user-interrupt)

**Comment by mplwork** [comment]
I couldn't agree more with @v-kydela who opened this thread. `Handle user interruptions` is where I came from and I am none the wiser how to provide help instructions for individual Waterfall steps. Maybe other topics here will.

**Comment by JonathanFingold** [comment]
We will review how this article shows up, is presented, or if it is even included when we do the next major doc overhaul in the next couple months.
