### ISSUE TITLE
The bot emulator gives an trace error when connecting to the emulator using the correct key and id for qna maker

### ISSUE THREAD

**Issue by xtianus79** [MicrosoftDocs/bot-docs#1369]
here is the error
Unable to find a QnA Maker service with Knowledge Base ID xxxxxxx-e166-44ea-94bf-xxxxxx. Please add a QnA Maker service to your bot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by JonathanFingold** [comment]
@support Please let the doc team know if we need to update the article.

**Comment by JonathanFingold** [comment]
Closing as a duplicate.

**Comment by xtianus79** [comment]
@jwiley84 thanks! where is the duplicate just in case anyone finds there way here
