### ISSUE TITLE
Email channelData object

### ISSUE THREAD

**Issue by v-bekif** [MicrosoftDocs/bot-docs#1371]
the Email example is fairly different than what's actually returned: only the internal channelData object is used, and the children need to be updated as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1170b28d-13ae-2e47-e14b-7cd9af0c61d3
* Version Independent ID: 506a2fe7-420f-9b76-53db-c89f4a977849
* Content: [Implement channel-specific functionality - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-channeldata?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-channeldata.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-channeldata.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Jim Lewallen should know what the schema is for email channel data.

**Comment by mmiele** [comment]
The updated documentation will be in the next available build.
