### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by v-bekif** [MicrosoftDocs/bot-docs#1372]
channelData object is outdated/incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db64bd62-cf60-5d73-c1a1-37f480ec59bd
* Version Independent ID: f20bc448-a105-d242-0ec0-369ceba1044e
* Content: [Connect a bot to Office 365 email - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-email?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-email.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-email.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
Will track as part of  #1371
