### ISSUE TITLE
Issue when run `dispatch create`

### ISSUE THREAD

**Issue by taqabubaker** [MicrosoftDocs/bot-docs#1373]
I'm trying to follow the article but I'm facing an issue when I run the command `dispatch create`. The command starts working till it reach to the part where it is trying to import the model which has the same name of my .dispatch file e.g.
`Importing dispatch model...`
then I get following error:
`ERROR
Failed importing dispatch app - {                                                                                                                  "error": {
    "code": "BadArgument",
    "message": "Import operation has failed."
  }
}`
Note I called my .dispatch file *dispatch*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@taqabubaker  - What was the name of the file with the extension? `dispatch`, `dispatch.dispatch`, or some other variant?

**Comment by JonathanFingold** [comment]
@diberry Please let us know if the docs need updating.

**Comment by RenanCarso** [comment]
I'm facing the same issue! No matter if I just create a with QnA kb, Luis kb or both.

**Comment by diberry** [comment]
#in-progress

**Comment by chrimc62** [comment]
@tsuwandy can you verify this if this caused by the new version of dispatch?

**Comment by martinlarosa** [comment]
I don't remember ever updating the dispatch tool and same thing happened to me last night, with refresh and create. It deleted my QA Luis app, good thing I had a backup.

**Comment by tsuwandy** [comment]
@taqabubaker, @martinlarosa could you email me a copy of your .dispatch file?  I was able to repro when my dispatch has only QnA sources and when my LUIS app has only patterns (no utterances).  Thanks!

**Comment by damianvc31** [comment]
Same problem here, first when i tried to refresh an existing LUIS dispatcher. i got a similar error, then i tried to create a new one and this exact error happened. Any help?

**Comment by martinlarosa** [comment]
I don't have the file handy now, but I would imagine something changed on the API. I didn't update de tool and it was working fine on Wednesday.

**Comment by tsuwandy** [comment]
@martinlarosa , no worries, I was able to repro so sent the failing app json to LUIS team, they are looking into it at the moment.

**Comment by taqabubaker** [comment]
@diberry the current file I have is `dispatch.dispatch` but I already tried other names like `dispatch-bot.dispatch` and it didn't work.

@tsuwandy What is your email address?

**Comment by bharti-semwal** [comment]
I am also facing the same issue all of a sudden.The same code worked absolutely fine  earlier

**Comment by tsuwandy** [comment]
@taqabubaker, my email is tien.suwandy@microsoft.com. Thanks!  

@bharti-semwal, LUIS team is taking a look at this issue at the moment.

**Comment by taqabubaker** [comment]
@tsuwandy email sent!

**Comment by damianvc31** [comment]
@tsuwandy Great! Thanks. What time is that, aproximately? In UTC

**Comment by taqabubaker** [comment]
@tsuwandy Thanks for your support.

**Comment by tsuwandy** [comment]
@damianvc31, I was told that it should be before 10/8/19 5PM PST (12AM UTC).  Thanks!

**Comment by mayank-chaturvedi** [comment]
@tsuwandy  Hi, Any  specific time when it would be rolled out. Super critical operation stuck ?

**Comment by tsuwandy** [comment]
@mayank-chaturvedi, I was told before end of day PST but it should be deployed  before then hopefully.

**Comment by ThomasPe** [comment]
I'm still seeing this issue, any chance the deployment got delayed?

**Comment by RenanCarso** [comment]
Just tested and it's working. :)

**Comment by tsuwandy** [comment]
yes, fix was deployed ~10 minutes ago.

**Comment by bharti-semwal** [comment]
Yes it works :)

**Comment by martinlarosa** [comment]
Thanks!

**Comment by diberry** [comment]
#please-close
