### ISSUE TITLE
The information about "NONE" intents is kind of confusing 

### ISSUE THREAD

**Issue by xtianus79** [MicrosoftDocs/bot-docs#1374]
The statement below is a bit confusing and may need some revision.  The none intent is passed onto the dispatch application from the corresponding luis application. so that renders that portion of the article inaccurately. 

&gt; Resolving incorrect top intent from Dispatch
Once your bot is running, it is possible to improve the bot's performance by removing similar or overlapping utterances between the dispatched apps. For example, let's say that in the Home Automation LUIS app requests like "turn my lights on" map to a "TurnOnLights" intent, but requests like "Why won't my lights turn on?" map to a "None" intent so that they can be passed on to QnA Maker. These two utterances are too close for the dispatch LUIS app to determine if the correct child app is the LUIS app or the QnA Maker app.

&gt; When you combine the LUIS app and the QnA Maker app using dispatch, you need to do one of the following:

&gt; Remove the "None" intent from the child Home Automation LUIS app, and instead add the utterances from that intent to the "None" intent in the dispatcher app.
Add logic in your bot to pass the messages that match the Dispatch LUIS app's "None" intent on to the QnA maker service. Compare the score of the Dispatch LUIS app's score and the score of the QnA Maker app. Use the highest score. This effectively removes QnA Maker from the Dispatch cycle.
Either of the above two actions will reduce the number of times that your bot responds back to your users with the message, 'Couldn't find an answer.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=js#service-endpoint-keys)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by JonathanFingold** [comment]
@xtianus79 I'm looking into this now. I'll let you know when I have updated guidance.

**Comment by JonathanFingold** [comment]
Removing most of the problematic content. Updating this section to more simply read:

> Once your bot is running, it is possible to improve the bot's performance by removing similar or overlapping utterances between the dispatched apps. You can use the [Dispatch](https://aka.ms/dispatch-command-line-tool) command-line tool to test and evaluate your dispatch model.

Let me know if more is needed here, or if this addresses your issue appropriately.

**Comment by JonathanFingold** [comment]
Fix has been pushed live and should be visible in a day or so. Please reopen with comments if there are still issues with this article.
