### ISSUE TITLE
It would be nice to have information about updating a dispatched luis application model in general 

### ISSUE THREAD

**Issue by xtianus79** [MicrosoftDocs/bot-docs#1375]
What is best practice and what does and does not need updated when changes are made to an underlying luis model or qna model

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=js#service-endpoint-keys)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by emgrol** [comment]
I agree @xtianus79 that the information you suggested should be added to that page. I'm reaching out now to get more information, and will update the page ASAP.

**Comment by dkonyayev** [comment]
One more vote to get this updated for maintaining dispatch service.

**Comment by diberry** [comment]
@emgrol @xtianus79 @dkonyayev This is on backlog - @emgrol - If you would like to move faster on this - please talk to Tien for best practices on Dispatch.

**Comment by dkonyayev** [comment]
@diberry @emgrol Thanks for following up on this. I already have users asking if they need to manage and retrain dispatch or base LUIS service. If they maintain dispatch does it get overwritten when we run the dispatch scripts.

**Comment by tsuwandy** [comment]
@xtianus79 , @dkonyayev, simply run "dispatch refresh" to update the same Dispatch LUIS app when underlying models (LUIS or QnA) are updated.  "dispatch refresh" command is basically the same as "dispatch create" command but it'll simply update the same Dispatch LUIS app (no new LUIS app id is created).

**Comment by dkonyayev** [comment]
@tsuwandy  Thanks, I started to run "dispatch refresh". Just to confirm - if I added new utterances to dispatch does the refresh process retain them?

**Comment by tsuwandy** [comment]
@dkonyayev, if utterances were added directly in luis.ai, they won’t be retained.  To keep those extra utterances in the Dispatch app, one would need to add those utterances in a text file (one utterance per line), then add the file to dispatch, “dispatch add -t file -f <<filePath>> —intentName <<target intent name, ie l_General>>.

Once file with extra utterances are added to dispatch,  the utterances will stay with every refresh.

I’ll check Dispatch readme and add this information if not already there.  Would be great to add this to the best practices documentation.  Thanks!

**Comment by dkonyayev** [comment]
@tsuwandy So in other words we should not be managing Dispatch on luis.ai, since any changes will be overwritten with dispatch refresh.

Just to confirm, the format of the file is something like below, with space between utterance and intent?

hi l_greeting
hello l_greeting
help l_help

**Comment by tsuwandy** [comment]
@dkonyayev, correct.  One file per target intent.  In your example, one would have to create two files to add to l_greeting and l_help intents, then add both files to dispatch (one time only unless there are utterances added to different Dispatch intents).  Utterances can continuously be added to the files and "dispatch refresh" will take care of updating the dispatch LUIS app.

**Comment by emgrol** [comment]
I've update the article with both information re: `dispatch refresh` and how to keep utterances added in LUIS between refreshes in [this PR](https://github.com/MicrosoftDocs/bot-docs/issues/1375). Thanks for the help @tsuwandy, and let me know if anything is unclear or incorrect.

**Comment by emgrol** [comment]
Closing this now that @tsuwandy approved the [changes](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1802/files/6c32f0ea0c5d7c12d1ab7b48b5b65f25708d000b).
