### ISSUE TITLE
JS snippet for 'Set up the QnA Maker instance' is malformed

### ISSUE THREAD

**Issue by teehill** [MicrosoftDocs/bot-docs#1376]
On https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs#set-up-the-qna-maker-instance

I'm seeing:

```}

// If a new user is added to the conversation, send them a greeting message
this.onMembersAdded(async (context, next) => {
    const membersAdded = context.activity.membersAdded;
```

Expecting to see a way to create a new QnAMaker instance (similar to the C# snippet). Something like this code:

https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/11.qnamaker/bots/QnABot.js#L12

**Comment by emgrol** [comment]
Thanks for pointing this out @teehill. The article should be update shortly.

**Comment by teehill** [comment]
looks good 👍
