### ISSUE TITLE
Need admin approval message at sign in page

### ISSUE THREAD

**Issue by Rykimaruh** [MicrosoftDocs/bot-docs#1377]
I hit this message obstacle when I try to test the connection. From my understanding, the delegated permissions chosen in this article do not require admin consent. Yet I am, why is that? I can't test out connection because of this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp%2Cbot-msgraph-auth#feedback)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by saikumaru** [comment]
Just to add, I am facing the same issue. Can anyone please suggest?

**Comment by mmiele** [comment]
@Rykimaruh Thank you for contacting us. Would you send additional information about your testing, perhaps a screenshot? Thanks

**Comment by mmiele** [comment]
@Rykimaruh When you created the connection and requested the API permissions to the MS Graph, did you verify that the operations required the admin consent? Please, check. For testing purpose just try _User.Read_. Let me know if this helps.

**Comment by Jeffders** [comment]
This has to do with the tenant under which you created your application. Some tenants require admin consent for any new application that is created in order for users to be able to log into this application. This is not something specific to using the application with your bot (any use of the app to sign in would result in the admin consent challenge).

**Comment by mmiele** [comment]
As explained in the previous comments some tenants require admin consent for any new application that is created in order for users to be able to log into this application. Please, check with your admin team.
