### ISSUE TITLE
How to create a continuous deployment?

### ISSUE THREAD

**Issue by r3dr4gon** [MicrosoftDocs/bot-docs#1378]
It is a bit unclear from this document how this should be done. Can I just create a build pipeline for the project, then deploy the output to the web app using "web app deploy" action?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@support, please let the doc team know if we need to add anything to the docs.

**Comment by dmvtech** [comment]
@r3dr4gon This article is more for provisioning/deploying the intial resources. But yes, you can do that approach for (continuously) deploying the bot code to the Web App/App Service. As long as the other bot resources (Web App bot/Bot registration) exist and are already provisioned/deployed, then that will work. 

[This documentation ](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0) is meant to be a very quick and simple example on how to utilize continuous deployment for a bot's App Service with GitHub repo. But of course there are many different options and approaches for continuous deployment with Azure App Services.
