### ISSUE TITLE
Screenshots doesn't match the current service

### ISSUE THREAD

**Issue by salavala** [MicrosoftDocs/bot-docs#1379]
[Enter feedback here]
I tried to follow the document but can't find QNA bot. 
![image](https://user-images.githubusercontent.com/8204815/66568443-6fa00f00-eb37-11e9-98cd-13bbc5148a5e.png)

Also, issue an error without a message.
![image](https://user-images.githubusercontent.com/8204815/66568559-b3931400-eb37-11e9-98cd-695236b5b1b6.png)

Please update the documentation to make it current.

Thanks,
Srini

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e8c5d2-bf2d-fc99-e813-bf9dd49eb9bb
* Version Independent ID: 830e4542-cdd8-3b64-f1df-2acae1ca3a88
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/abs-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/abs-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/abs-quickstart.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@salavala Would you mind to send the actual document you are using instead of the screenshot? Also, did you try the follow the steps described in this article:[ Tutorial: Use QnA Maker in your bot to answer questions](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp)?

**Comment by mmiele** [comment]
Please, follow the steps described in the article: [Tutorial: Use QnA Maker in your bot to answer questions](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp).
