### ISSUE TITLE
Small correction on method name for WaterfallStepContext method

### ISSUE THREAD

**Issue by dmvtech** [MicrosoftDocs/bot-docs#1383]
Re: "Additionally, the next method continues to the next step of the waterfall dialog within the same turn, enabling your bot to skip a certain step if needed."

The method name is NextAsync:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.waterfallstepcontext.nextasync?view=botbuilder-dotnet-stable

So, should be:
"Additionally, the NextAsync method continues to the next step of the waterfall dialog within the same turn, enabling your bot to skip a certain step if needed."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d405d76-b17a-dbe9-c2f2-734fa34b0e8b
* Version Independent ID: 3acc3fa8-b98d-a5f1-8bea-e823c3efec14
* Content: [Dialogs within the Bot Framework SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-dialog.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-dialog.md)
* Service: **bot-service**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by emgrol** [comment]
Thanks for catching this @dmvtech, I've opened a [PR](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1797) and the changes should be changed merged later today.

**Comment by emgrol** [comment]
Closing this now that the changes have been merged.
