### ISSUE TITLE
Microphone doesn't appear on "Test in WebChat" in Azure Bot Service

### ISSUE THREAD

**Issue by mapoitras** [MicrosoftDocs/bot-docs#1385]
I have followed all the instructions noted above.  I created a basic Virtual Assistant Bot that has all the coding details mentioned here:  https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0

When I deploy and test the bot, I don't see the Microphone icon either in "Test in WebChat" in Azure Bot Service or the Bot Emulator.  What Am I missing.

Template I used:  https://microsoft.github.io/botframework-solutions/tutorials/csharp/create-assistant/1_intro/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4cb4da-ca0e-fc7f-686c-f3510bf9af0b
* Version Independent ID: e20d2896-dcec-8e46-2f50-2227def34250
* Content: [Connect a bot to Direct Line Speech (Preview) - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-directlinespeech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directlinespeech.md)
* Service: **bot-service**
* GitHub Login: @trrwilson
* Microsoft Alias: **travisw**

**Comment by mmiele** [comment]
@mapoitras Thank you for pointing out the issue. The team is aware of the problem and is working to fix it. 
If you want to test a Bot with voice input and voice output, please check the [Direct Line Speech Client](https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client) on GitHub.

**Comment by mmiele** [comment]
If you want to test a Bot with voice input and voice output, please check the [Direct Line Speech Client](https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client) on GitHub.
