### ISSUE TITLE
Send proactive notifications to users how to persist conversation references in database

### ISSUE THREAD

**Issue by rungsoso** [MicrosoftDocs/bot-docs#1386]
From https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp

Note: In a real-world scenario you would persist conversation references in a database instead of using an object in memory.

How to do this?

**Comment by JonathanFingold** [comment]
See [Managing state](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0) for a conceptual overview of how state and storage are handled in the Bot Framework SDK.

We have three main how-to articles on state and storage, in increasing level of complexity:
- [Save user and conversation data](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0)
- [Write directly to storage](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0)
- [Implement custom storage for your bot](https://docs.microsoft.com/azure/bot-service/bot-builder-custom-storage?view=azure-bot-service-4.0)

Let me know if this helps.

**Comment by rungsoso** [comment]
@JonathanFingold 

I use "Write directly to storage" to store conversation references in cosmos db. It work for me
thank you
