### ISSUE TITLE
The input bar didn't show up by using Teams Authentication Bot Sample 

### ISSUE THREAD

**Issue by agladboy** [MicrosoftDocs/bot-docs#1387]
I followed the instruction above and authored the myApp by using MS Team Studio, and installed the myApp to the MS Teams through MS Team Studio, the installation succeeded and the message "Welcome to TeamsBot. Type anything to get logged in. Type 'logout' to sign-out" showed up, however there is no input bar at the bottom of the MS Team, once I changed to the other app the input bar showed up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=javascript%2Cbot-oauth)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by clearab** [comment]
That sounds like you've flagged the bot as a "notification only" bot. In App Studio, open your app manifest. On the Bot tab click Edit next to your bot. Make sure the checkbox "My bot is a one-way notification only bot" is not checked.

**Comment by clearab** [comment]
You'll need to re-install the bot once you've made a change to the app manifest.

**Comment by agladboy** [comment]
@clearab Thank you very much, It works!
