### ISSUE TITLE
According to IntelliSense documentation, dialogs inherit TelemetryClient when added using AddDialog

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/bot-docs#1388]
According to IntelliSense documentation, dialogs inherit TelemetryClient when added using ComponentDialog.AddDialog:
```
// Remarks:
//     Adding a new dialog will inherit the Microsoft.Bot.Builder.IBotTelemetryClient
//     of the ComponentDialog.
```

This conflicts with the documentation that you need to add it manually to all dialogs:
&gt; When adding each dialog using the AddDialog method, set the TelemetryClient value:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db892de5-e60e-1d4f-505b-11b1cdb73323
* Version Independent ID: f7263014-b8fa-9a20-71aa-e4217b2821ee
* Content: [Add telemetry to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-telemetry.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-telemetry.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@hansmbakker In this case, the IntelliSense is correct. While the sample code as currently structured works fine, it does extra work, with respect to setting the telemetry client on child dialogs. We need to coordinate with a couple other teams, so we'll let you know when a full fix is in place.

**Comment by WashingtonKayaker** [comment]
@hansmbakker Thanks for taking the time to report this.  The change to the sample app is on the backlog, once the updated sample is ready we will update the article as well.
