### ISSUE TITLE
Getting 401 errors 

### ISSUE THREAD

**Issue by vikramdadwal** [MicrosoftDocs/bot-docs#1391]
I have followed the 401 practice as mentioned above. But somehow when I am hitting the controller using an Azure Function it is throwing 401 unauth error. But when I hit the same controller with POSTMAN things are working fine. This has blocked us, please assist.

![image](https://user-images.githubusercontent.com/10174566/67609550-3b853a80-f742-11e9-8939-6cd787d98d95.png)

**NOTES:**
1. Our BOT API is hosted in multi region with Traffic Manager in Front
2. Also in one of our (staging) environment, things are working fine. But in this specific environment it never works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521a9f9a-025c-c55b-c939-d9d4efc5c6d0
* Version Independent ID: 3bcafb54-f7eb-54f5-1d78-5f2087e2e2dc
* Content: [Send proactive notifications to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
For troubleshooting help, post your question on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework).
