### ISSUE TITLE
Connection Problems: Wrong name

### ISSUE THREAD

**Issue by MaxMueller0815** [MicrosoftDocs/bot-docs#1392]
On this page stands to write your env. file with:
"QnAAuthKey"
But it must be "QnAEndpointKey" like it is stated later in the code.
I couldnt find the solution for 2 hours.
Pls, correct the documentation. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=js#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@MaxMueller0815 Thanks for catching this. I'm in the process of fixing the code snippets.
