### ISSUE TITLE
V4 Node.js Documentation

### ISSUE THREAD

**Issue by MaxMueller0815** [MicrosoftDocs/bot-docs#1393]
Hi,
Is there a V4 documentation page for "Recognize intent with LUIS" with a node.js example?
The link provided in the beginning leads to no specific site (https://docs.microsoft.com/azure/bot-service/?view=azure-bot-service-4.0)
When searching for "Recognize intent with LUIS" there is only V3 documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f0f2ff1-f19c-c66d-53ac-b9569e0a4601
* Version Independent ID: 0ef27a09-09cf-e09a-ec40-9c86b1150bde
* Content: [Recognize intents and entities with LUIS - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-luis-dialogs?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-luis-dialogs.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-luis-dialogs.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
The LUIS topic for v4 is [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=csharp).
