### ISSUE TITLE
AppID Changes on dispatch on rerun

### ISSUE THREAD

**Issue by dkonyayev** [MicrosoftDocs/bot-docs#1396]
It seems that AppID changes every time the Dispatch command is ran. This would definitely cause issues in our applications since we have to update the config files. Is there a way to provide the AppID to the dispatch command? Alternatively, how can we refresh dispatch without deleting the dispatch app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@tsuwandy Can you provide details?

**Comment by dkonyayev** [comment]
Sure, we created a batch file with CLI commands indicated in this article. When we modify underlying QnA KB or LUIS App we rerun the batch file. This seem to delete the LUIS Dispatch and create a new one, with new AppID.

I maybe following a wrong process but this is how we "manage" dispatch if changes occur to underlying sources.

**Comment by tsuwandy** [comment]
@dkonyayev, use "dispatch refresh" to update dispatch when child sources (LUIS/QnA are updated).  The refresh command will keep the Dispatch app id the same.

**Comment by diberry** [comment]
Docs now have dispatch refresh information. #please-close
