### ISSUE TITLE
Proposal: Consider an e2e roadmap tutorial section that references samples in expertise order

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/bot-docs#1397]
## Roadmap Organization
A proposal for another view/organization of content to help users ramp up. The idea is to have a roadmap/rampup/tutorial section so that one doesn't get overwhelmed with the quantity of samples and being unsure how to navigate through them. 

I was wondering whether we can maybe have a crawl walk run model that tackles the fundamentals in a shorter progressive build-up into an end to end tutorial. The strategy I imagine is inspired by how I picked up Razor Pages web app with ASP.NET Core.  I think the idea is to consolidate and turn the samples into one cohesive story. 

Here's an example:

### Novice: 0 to 60's in Tesla speed: 
* Click, click, click: Download sample, build, run, provision, deploy, use
* Discovery & introduction: docs, samples with cohesive one path discovery from novice to expert (reduce dilemmas)
### Advanced:
* Integrate cognitive services
* Integrate multi-turn dialog flow
* Automate code to deploy workflow
* Use pre-canned skills
* Integrate (cognitive) collaboration interfaces (luis, qna)
* SDLC Automation, Tooling, and Uniformity
### Expert:
* Use auth/z 
* Develop & integrate skills
* Scale, performance & conversation quality monitoring

**Comment by erhopf** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, and tracking this internally as part of customer journey mapping and TOC reorganization. #please-close
