### ISSUE TITLE
Unable to locate Secret Keys of DLS Channel after Registration

### ISSUE THREAD

**Issue by wilsonlapwong** [MicrosoftDocs/bot-docs#1412]
Hi, 
After registering my bot with the Direct Line Speech Channel, I was unable to locate Secrets Keys in SpeechQnABot-BotRegistration resource in Azure Portal.  

I had followed the instructions in the document.  My Location of Speech Cognitive Services is West US.  

Please advise.

Regards,
Wilson  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4cb4da-ca0e-fc7f-686c-f3510bf9af0b
* Version Independent ID: e20d2896-dcec-8e46-2f50-2227def34250
* Content: [Connect a bot to Direct Line Speech (Preview) - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-directlinespeech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directlinespeech.md)
* Service: **bot-service**
* GitHub Login: @trrwilson
* Microsoft Alias: **travisw**

**Comment by trrwilson** [comment]
Hello, Wilson! Thank you for reaching out. We'll have a documentation update available soon, but I'm happy to say that what you see here is a new improvement to the authentication experience that went live a little before the information did.

The idea here is that you'll now only need to use your speech subscription key to connect to your bot, as the channel will be linked to the subscription from that drop-down you see in the new channel registration page.

The upcoming release of the Speech SDK will make this change a clear part of the API, but it's also backwards compatible with the existing v1.7 release at this time: simply provide any non-empty value as the channel secret in DialogServiceConfig (e.g. via the box at the top of the DLSpeech client) together with your associated speech subscription key and the value will be ignored to instead use the association you established at channel registration. So if this worked before:

DialogServiceConfig.FromBotSecret("your_secret", "your_subscription", "your_region")

Then that should *continue* to work after the registration change, also becoming equivalent to:

DialogServiceConfig.FromBotSecret("foobar", "your_subscription", "your_region")

Please note that the secret parameter can't be null or empty, as those will fail validation on the device before contacting the service. v1.8 will include a simpler factory method that doesn't require the first parameter.

Thanks for discovering this so promptly and please let us know if this approach isn't working for you!

**Comment by wilsonlapwong** [comment]
Hello Travis,

Thank for your prompt response.  Your approach is working for me.

Thanks.

Regards,
Wilson

Travis Wilson <notifications@github.com> 於 2019年10月30日週三 下午2:48寫道：

**Comment by mmiele** [comment]
@trrwilson Travis is there any need to put a note in the article? Please advice. Thanks

**Comment by mmiele** [comment]
Closing based on @terrwilson comments.
