### ISSUE TITLE
Send Proactive Message javascript code is incorrect

### ISSUE THREAD

**Issue by EricDahlvang** [MicrosoftDocs/bot-docs#1415]
The following is the code containing **continueConversation**:

```js
// Listen for incoming notifications and send proactive messages to users.
server.get('/api/notify', async (req, res) =&gt; {
    for (const conversationReference of Object.values(conversationReferences)) {
        await adapter.continueConversation(conversationReference, async turnContext =&gt; {
            await turnContext.sendActivity('proactive hello');
        });
    }

    res.setHeader('Content-Type', 'text/html');
    res.writeHead(200);
    res.write('&lt;html&gt;&lt;body&gt;&lt;h1&gt;Proactive messages have been sent.&lt;/h1&gt;&lt;/body&gt;&lt;/html&gt;');
    res.end();
});
```

From: https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/16.proactive-messages/index.js#L68

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521a9f9a-025c-c55b-c939-d9d4efc5c6d0
* Version Independent ID: 3bcafb54-f7eb-54f5-1d78-5f2087e2e2dc
* Content: [Send proactive notifications to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Thanks! @EricDahlvang We will fix it.

Yan

**Comment by zxyanliu** [comment]
Actually, @JonathanFingold is fixing this one here [#1798](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1798)

**Comment by JonathanFingold** [comment]
Fixed in PR and merged into master. Fix should go live next time we merge master into live.
