### ISSUE TITLE
This topic is missing from the v4 docs

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1416]
Please make a typing-indicator doc for v4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a79c4cc-6f80-91ad-6a88-81874f7154a1
* Version Independent ID: ac8f6181-1f8a-8911-5e3d-6421bfb2c94d
* Content: [Send a typing indicator - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-typing-indicator?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-send-typing-indicator.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-send-typing-indicator.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Closing this now that instructions for adding typing indication to v4 C#, Javascript, and Python bots have been added to the Send and receive text message [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-send-messages?view=azure-bot-service-4.0&tabs=csharp#send-a-typing-indicator).
