### ISSUE TITLE
ALM process overview

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/bot-docs#1417]
Would be nice to have an overview of the Application life cycle management processes and tools that are recommended on each step.
The howto sections here in these docs explains how to do do individual things but we don't see a full picture of the process.
Also some tools are replaced with others (e.g. luisGen is deprecated and new BF CLI tools are available)
It would be nice to see what are current tools available on each step and use recommendations on when to use which tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6838575c-d2fc-65e3-98c2-0b35992c10b2
* Version Independent ID: 2b5dc3fc-49c0-7cd2-e6e1-4ced8da6c5f9
* Content: [Azure Bot Service Introduction - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-overview-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-overview-introduction.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by erhopf** [comment]
We are tracking this internally as part of customer journey mapping. #please-close
