### ISSUE TITLE
Unable to Send Messages to Bot embedded in web application

### ISSUE THREAD

**Issue by wilsonlapwong** [MicrosoftDocs/bot-docs#1423]
Hi,
I had created a bot with QnA, Speech to Text and Text to Speech features.  Moreover, the bot had been tested successfully in both Emulator and Direct Line Speech Client.

However, when I embedded the bot in my web application running on local IIS on Windows 10, I failed to send messages to the bot.

Details:
*************************************
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;body&gt;
  &lt;iframe id="chat" style="width: 400px; height: 400px;" src=''&gt;&lt;/iframe&gt;
&lt;/body&gt;
&lt;script&gt;

    var xhr = new XMLHttpRequest();
    xhr.open('GET', "https://webchat.botframework.com/api/tokens", true);
    xhr.setRequestHeader('Authorization', 'BotConnector ' + 'Tl1VGLoPrpk.8De4Vnsi2bNiudv13a2rtlFvSwk2aKXZECEvwc_uTt0');
    xhr.send();
    xhr.onreadystatechange = processRequest;

    function processRequest(e) {
      if (xhr.readyState == 4  && xhr.status == 200) {
        var response = JSON.parse(xhr.responseText);
        document.getElementById("chat").src="https://webchat.botframework.com/embed/FAQBot-Bot?t="+response
      }
    }

  &lt;/script&gt;
&lt;/html&gt;

*************************************
Please advise.  Thanks.

Regards,
Wilson

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d54408c-bfbc-9d2c-a642-ec54f375475f
* Version Independent ID: 5b06e016-1aa8-a13b-179c-ec6700b8287c
* Content: [Connect a bot to the Web Chat channel - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-webchat.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-webchat.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by dmvtech** [comment]
@wilsonlapwong Do you get any errors or exceptions?

**Comment by wilsonlapwong** [comment]
Hi,

I got the following exception in Channel of Web App Bot:
There was an error sending this message to your bot: HTTP status code Unauthorized

Please advise.

Regards,
Wilson

**Comment by dmvtech** [comment]
That's typically an appid/password configuration issue. 

- You've got the webchat client embedded in your local website running in IIS, but is your bot running locally as well, or deployed to Azure? 
- Is your bot configured with appid/password or were you testing via emulator without those values?

**Comment by wilsonlapwong** [comment]
Hi,
I have verified that my bot is accessible and functional on localhost when security is disabled, confirmed that my bot's app ID and password are valid, and verified that my bot is accessible and functional on localhost when security is enabled. 

However, after publishing my bot to Azure portal successfully by Visual Studio 2019.  Then I test my bot in Web Chat in Azure, there is no response from my bot.  Also, the following exception is recorded in Web Chat channel of my bot:

There was an error sending this message to your bot: HTTP status code Unauthorized

Please advise.  Thanks.

Regards,
Wilson

**Comment by dmvtech** [comment]
Is your appid/password configured in the `appsettings.json`/`.env` file? or have you configured in the app services configuration settings? I would recommend setting up in both (at least for now/troubleshooting). When setting up in the app services's config settings, the key names must be correct (`MicrosoftAppId`,`MicrosoftAppPassword`)

**Comment by wilsonlapwong** [comment]
Hi Dana,

Thank for your email.  Both keys(MicrosoftAppId,MicrosoftAppPassword) are
configured in appsettings.json.

Moreover, failed request tracing logs have been enabled in Azure portal and
I find that there are 401 and 400 HTTP code error events.

Please refer the enclosed and advise.  Thank you.

Regards,
Wilson

Dana V <notifications@github.com> 於 2019年11月19日週二 上午2:14寫道：

**Comment by dmvtech** [comment]
> However, after publishing my bot to Azure portal successfully by Visual Studio 2019. Then I test my bot in Web Chat in Azure, there is no response from my bot.

Really strange. 

> Thank for your email.  Both keys(MicrosoftAppId,MicrosoftAppPassword) are
> configured in appsettings.json.

That _should_ be enough, but can you just test by setting them in the app services' configuration? Another thing you might want to try is creating a new password/secret for the ADapp/bot.

**Comment by dmvtech** [comment]
@wilsonlapwong Were you able to test by setting the properties in the app service config?

**Comment by wilsonlapwong** [comment]
After setting id and password in configuration, test in web chat is working.

Thanks.

在 2019年11月26日週二 03:12，Dana V <notifications@github.com> 寫道：
