### ISSUE TITLE
The Channel Inspector has been gone for a while so the docs should not refer to it

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1424]
https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-create-messages?view=azure-bot-service-4.0#message-text-and-formatting

> Message text can be formatted using plain, markdown, or xml. The default format for the textFormat property is markdown and interprets text using Markdown formatting standards. The level of text format support varies across channels. To see if a feature you want to use is supported on the channel you target, preview the feature using Channel Inspector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: affd2f4d-3114-882c-5311-890e87ab0925
* Version Independent ID: ce93eb01-f631-18ab-a126-1778f52ac46d
* Content: [Create messages with the Bot Connector API - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-create-messages?view=azure-bot-service-4.0#message-text-and-formatting)
* Content Source: [articles/rest-api/bot-framework-rest-connector-create-messages.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-create-messages.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
The PR got merged and the content will go live soon. Closing this issue. Thanks again for your report.
