### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by dmvtech** [MicrosoftDocs/bot-docs#1425]
In this section:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=csharp#how-cancellation-works-for-component-dialogs

In the C# code sample, it shows:
Bots\DialoBot.cs

Should be:
Bots\DialogBot.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9577ff-cf56-e5de-84c3-bfe10aab5368
* Version Independent ID: b5d62753-f87b-4673-b09b-a5a3fd9360e8
* Content: [Reuse dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=csharp#how-cancellation-works-for-component-dialogs)
* Content Source: [articles/v4sdk/bot-builder-compositcontrol.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-compositcontrol.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out, I've opened up a [PR](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1901) that fixes this typo. The changes should go live soon.

**Comment by emgrol** [comment]
Closing this now that the typo has been fixed.
