### ISSUE TITLE
More information needed

### ISSUE THREAD

**Issue by LindaLawton** [MicrosoftDocs/bot-docs#1427]
parameters	Provide deployment parameter values. appId value you got from running the az ad app create command. 
Would you please supply more information on to what these parameters are and what should be their values?   I have spent the last hour googling around trying to figure out how to find a group name and an app service plan location.  I am still not sure what values should be in here So far all i get is errors when submitting the request.

> appSecret is the password you provided in the previous step. The botId parameter should be globally unique and is used as the immutable bot ID. It is also used to configure the display name of the bot, which is mutable. botSku is the pricing tier and can be F0 (Free) or S1 (Standard). newAppServicePlanName is the name of App Service Plan. newWebAppName is the name of the Web App you are creating. groupName is the name of the Azure resource group you are creating. groupLocation is the location of the Azure resource group. newAppServicePlanLocation is the location of the App Service Plan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Closing this issue since it is addressed. Thank you!

**Comment by zxyanliu** [comment]
Hi @LindaLawton 

FYI. 
`az add app create` is an Azure CLI command to create a web application. Read details of this command [here](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-create). 
`az deployment create` is an Azure CLI command to start a deployment. Read details of this command [here](https://docs.microsoft.com/en-us/cli/azure/deployment?view=azure-cli-latest#az-deployment-create).

As to the `parameters` you mentioned in the `az deployment create` command, here is a table listing some specifics. I hope it is helpful for you. 

| parameter         | description  | example | 
| ------------ | ---------------------------------------------------------- | ------------- | 
| `appId` | The ID number generated when you create the app registration in the "Create an App Registration" step | xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx | 
|`appSecret` | The password you created in the "Create an App Registration" step.  | AtLeastSixteenCharacters_0 | 
|`botId` | An identifiable ID of your bot. You specify this value. | your-bot-id | 
|`botSku` | The pricing tier. Can be F0 (Free) or S1 (Standard). | F0 | 
|`newAppServicePlanName` | The name you give to the new app service plan. | my-new-service-plan | 
|`newWebAppName` | The name you give to the new web app you are creating. | my-new-web-app | 
|`groupName` | The name you give to the new resource group you are creating. | my-new-resource-group | 
|`groupLocation` | The location you select for the new Azure resource group | westus | 
|`newAppServicePlanLocation` | The location you select for the new app service plan | westus | 

Please try again and if you encounter further issues, feel free to follow in this thread, and ideally with screenshots of the errors you encounter. 

Please let us know. : ) 

Yan

**Comment by zxyanliu** [comment]
Hi @LindaLawton 
I was wondering if you have resolved this issue? Did you try again? 
Please let us know. 

Thanks.

Yan

**Comment by LindaLawton** [comment]
I did a lot of trial and error spamming it with random values until I got it to work.

I posted this after the fact so that otheres wouldn't have the same issue

**Comment by zxyanliu** [comment]
Thanks! Do you think providing a table listing all parameters will be helpful? If so, we will update the [doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp) soon to avoid similar confusion. Please let us know.

**Comment by zxyanliu** [comment]
Closing. please reopen this issue if you still have questions. thanks!
