### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by jona888** [MicrosoftDocs/bot-docs#1429]
4. second bullet
"Your will..."--&gt;"You will..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2e431c-e5ab-e733-ef58-8d9c450c0d75
* Version Independent ID: c3bbe2ec-5b6a-71f8-e465-e0bd760b66d5
* Content: [Bot review guidelines - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-review-guidelines?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-review-guidelines.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-review-guidelines.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Thanks for pointing out the typo. Fixing in PR [1828](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1828)

**Comment by zxyanliu** [comment]
Closing this issue because it is fixed. Thanks!
