### ISSUE TITLE
No Response from My Bot in Web Chat of Azure Portal

### ISSUE THREAD

**Issue by wilsonlapwong** [MicrosoftDocs/bot-docs#1430]
Hi,
I have verified that my bot is accessible and functional on localhost when security is disabled, confirmed that my bot's app ID and password are valid, and verified that my bot is accessible and functional on localhost when security is enabled. 

However, after publishing my bot to Azure portal successfully and testing my bot in Web Chat in Azure, there is no response from my bot.  Also, the following exception is recorded in Web Chat channel of my bot:

There was an error sending this message to your bot: HTTP status code Unauthorized

Please advise.  Thanks.

Regards,
Wilson

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc8a0643-f219-a48f-666e-95bc9f0f351c
* Version Independent ID: 81578919-249c-b3e7-b367-183d70135890
* Content: [Troubleshooting Bot Framework Authentication - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-troubleshoot-authentication-problems.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-troubleshoot-authentication-problems.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by jwiley84** [comment]
how are you deploying your bot?

**Comment by jwiley84** [comment]
Do you still need help?

**Comment by wilsonlapwong** [comment]
Hi Jessica,

I have created Direct Line channel by following the document:

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat-speech?view=azure-bot-service-3.0
<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbot-service%2Fbot-service-channel-connect-webchat-speech%3Fview%3Dazure-bot-service-3.0&data=02%7C01%7Czhiqwan%40microsoft.com%7Cabb6ae2f66504c83a7f808d77314c34f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637104407019555112&sdata=t7hdUTH93NoUKINR4L%2BssKR4F4vXTMdMUyvjVuES79w%3D&reserved=0>


The Web Chat with Speech is working well except that I have difficulty to
change the default input speech language from English(en-us) to
Cantonese(zh-HK).  The related html file is attached.  *Please advise me
how to do so*.  Thanks.

Regards,

Wilson

在 2019年11月27日週三 04:52，Jessica Wailes <notifications@github.com> 寫道：

**Comment by jwiley84** [comment]
That describes how you add a channel, but doesn't answer the question of 'how are you deploying your bot?' I need that to be able to figure out why your bot is coming back with an 'Unauthorized' error.

**Comment by wilsonlapwong** [comment]
Hi Jessica,

Thank for your email.  I publish my SDK v4 bot to Azure via Visual Studio
2019.  The unauthorized error of Web Chat was fixed by recreating the Web
Chat channel.

However, I have encountered Speech to Text problem in Direct Line channel.
I expected that I speak to the bot in Cantonese and the bot translated my
speech to traditional Chinese in text in Web Chat.  But it did not work.

Please advise.

Regards,
Wilson


Jessica Wailes <notifications@github.com> 於 2019年12月3日週二 上午2:59寫道：

**Comment by jwiley84** [comment]
Ok, that is a totally different problem, and will need many more details then you've outlined here.  I'm not 100% certain that the scenario you've outline is possible. Are you using webchat or directline speech? Can I get the app ID of your bot, please?

Also, I didn't receive any attachment. Please post your HTML here in the issue so I can look it over.

**Comment by CoHealer** [comment]
Closing, @wilsonlapwong please reopen if you still need assistance.
