### ISSUE TITLE
Outdated instructions

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/bot-docs#1431]
Screenshots and instructions are slightly outdated for the "Connect a bot to Facebook Messenger" part

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0199d414-87e1-e32d-b528-ee9d2e03c54e
* Version Independent ID: f88f4b08-0977-baee-5226-844695828b95
* Content: [Connect a bot to Facebook Messenger - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-facebook.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-facebook.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @turbozapekanka Thanks for reporting the issue. If you are looking for information about using Facebook adapter, please check [here](https://www.npmjs.com/package/botbuilder-adapter-facebook). Also, [docs for Facebook adapter](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1908) will be available soon.

**Comment by zxyanliu** [comment]
FYI. Docs for custom sdk adapters (Facebook / Twilio) are WIP in PR [#1923](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1923)

**Comment by zxyanliu** [comment]
[PR 1923](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1923) was merged and closing the issue.
