### ISSUE TITLE
Trust Service URL using MicrosoftAppCredentials in Bot Framework (Node.js)

### ISSUE THREAD

**Issue by PeterChen1105** [MicrosoftDocs/bot-docs#1434]
**Problem Description**

When I want to send proactive messages to Facebook & Line channel, similar errors occur as this issue (https://github.com/Microsoft/botbuilder-js/issues/714).

However, the error message I received is not (the error I receive is just [onTurnError]: Error without any details)

> [onTurnError]: Error: Authorization has been denied for this request

But I am still thinking the problem is related to MicrosoftAppCredentials, so can the error message returned be more specific in this situation?

**To Reproduce**

After restarting, I can't send a proactive message to users that I've previously communicated with (until there has been some activity on the channel).

0. Bot is restarted
1. Bill chats with my bot in Facebook Messenger [Everything is good & reference is saved]
2. Sally chats with my bot in Facebook Messenger [Everything is good & reference is saved]
3. Bot is restarted
4. Try to send a proactive message to Bill -- ERROR
5. Try to send a proactive message to Sally -- ERROR
6. Bill (or any user, even someone not Bill or Sally) sends a message to my Bot [this will work]
7. Try to send a proactive message to Bill -- NOW WORKS
8. Try to send a proactive message to Sally -- NOW WORKS

**Other Issue**

I am using the Core Bot template for developing the bot application. Based on the template, we use the `BotFrameworkAdapter` from `botbuilder` to process activities.

```
// Create bot framework adapter.
const adapter = new BotFrameworkAdapter({
  appId: process.env.MicrosoftAppId,
  appPassword: process.env.MicrosoftAppPassword
});
```

However, as mentioned in the proactive messaging documentation, we need to use `MicrosoftAppCredentials` from `botframework-connector` to trust service URLs. When I execute the following commands to trust service URLs, error occurs:

```
var BotConnector = require('botframework-connector');
BotConnector.MicrosoftAppCredentials.trustServiceUrl('https://facebook.botframework.com/');
```

So what is the proper way of trusting the service urls using `MicrosoftAppCredentials` in this context? Am I missing something which eventually generates the error?

**Comment by mdrichardson** [comment]
@PeterChen1105 Can you include the code you're using to send the proactive message? I've seen this error occur if appId and password are not passed into the ConnectorClient or Adapter that's sending the activity.

And is `trustServiceUrl()` being called prior to sending the message?

**Comment by PeterChen1105** [comment]
@mdrichardson I didn't include the **MicrosoftAppId** & **MicrosoftAppPassword** in the local .env file, since in the local environment if I add these two environment variables, the application will not be able to execute successfully.

![Bot App Configuration](https://user-images.githubusercontent.com/53604754/69392310-b9c90280-0d29-11ea-8129-b835db86942b.png)

The application logic for sending the proactive message is as follows:

1. Create the bot framework adapter

```
const { BotFrameworkAdapter } = require("botbuilder");

const adapter = new BotFrameworkAdapter({
  appId: process.env.MicrosoftAppId,
  appPassword: process.env.MicrosoftAppPassword
});
```

2. Create the bot connector and add trusted service URLs

```
const BotConnector = require("botframework-connector");
const credentials = new BotConnector.MicrosoftAppCredentials(
  process.env.MicrosoftAppId,
  process.env.MicrosoftAppPassword
);

BotConnector.MicrosoftAppCredentials.trustServiceUrl(
  "https://facebook.botframework.com/"
);
BotConnector.MicrosoftAppCredentials.trustServiceUrl(
  "https://line.botframework.com/"
);
```

3. The adapter will be responsible for processing the activities

```
server.post("/api/messages", (req, res) => {
  adapter.processActivity(req, res, async turnContext => {
  //
});
```

4. I defined a Firebase Firestore observe to listen to the changes made on a setting reference document and trigger broadcasting messages

```
settingRef.onSnapshot(
  async docSnapshot => {
    // Retrieve the previous setting information
    var previousSetting = docSnapshot.data().Previous_Setting;
    const uploadFlag = docSnapshot.data().Upload;

    // Update the previous setting & send broadcast messages accordingly
    if (uploadFlag && uploadFlag !== previousSetting.Upload) {
      previousSetting.Upload = uploadFlag;
      settingRef.update({ Previous_Setting: previousSetting });
      await broadcastMessage("Upload");
    }
);
```

5. Sending broadcasting messages by retrieving the conversation references that I stored in Firebase

```
async function broadcastMessage(stage) {
  // Retrieve all conversation references from Firebase
  const allConversationReferences = await getAllConversations();

  for (const conversationReference of Object.values(
    allConversationReferences
  )) {
    await adapter.continueConversation(
      conversationReference,
      async turnContext => {
        await turnContext.sendActivity(CONSTANTS.BROADCAST_MESSAGE[stage]);
      }
    );
  }
}
```

Currently, the broadcasting message can be sent through to the Line Channel. However, in the Facebook Messenger Channel, I will receive the following error and not being able to send the messages. The error message will disappear when any user from the Facebook Channel sends an user-initiated message to the bot.

> [onTurnError]: Error: Facebook API error

**Comment by mdrichardson** [comment]
@PeterChen1105 Are you receiving this error when the bot is hosted locally, deployed, or both? I'm relatively certain that you *must* have AppId and Pass set in order for `TrustServiceUrl` to work. 

You *should* be able to develop locally with those specified, provided that you pass those values to Emulator. If you can't, there's a whole different issue we need to deal with.

I believe your code looks okay, however, provided that your `conversationReferences` are set appropriately.

**Comment by PeterChen1105** [comment]
@mdrichardson Based on your comment:

1. The `[onTurnError]: Error: Facebook API error` is received when the application is deployed, and in the deployment environment, I am sure that the AppId & AppPassword have been set properly.

2. However, in the local environment, I receive the 401 Unauthorized Access Error. But I am also sure that the AppId & AppPassword has been enabled when passing as the parameter for the adapter and connector to use.

<img width="936" alt="Unauthorized Access" src="https://user-images.githubusercontent.com/53604754/69464221-db7dc480-0dd1-11ea-8bdf-20721ee61417.png">

3. In terms of the last thing you mentioned, I followed the BotBuilder Samples (https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/16.proactive-messages/bots/proactiveBot.js). The sample code is not using `ApplyConversationReference`, and `isIncoming` variable is also not applied. So do you have any reference or sample of using the `ApplyConversationReference` method?

I modified the conference references in both the `onConversationUpdate` & `onMessage` listener in the bot that I defined. And the code is the same as the sample provided, so I am not sure which part results in the error.

```
this.onConversationUpdate(async (context, next) => {
      this.addConversationReference(context.activity);
      await next();
});
```

```
this.onMessage(async (context, next) => {
      this.addConversationReference(context.activity);

      // Run the Dialog with the new message Activity.
      await this.dialog.run(context, this.dialogState);

      // By calling next() you ensure that the next BotHandler is run.
      await next();
});
```

```
async addConversationReference(activity) {
    const conversationReference = TurnContext.getConversationReference(
      activity
    );

    this.conversationReferences[
      conversationReference.conversation.id
    ] = conversationReference;

    // Update the conversation details in Firebase
    console.log("Current Activity: ", activity);
    const userId = activity.from.id;
    const userName = activity.from.name;
    const channel = activity.channelId.toUpperCase();
    if (userName !== undefined)
      await postConversation(
        channel,
        userId,
        conversationReference.conversation.id,
        conversationReference
      );
}
```

**Comment by mdrichardson** [comment]
@PeterChen1105 Where is the code that sends the proactive message? And why not store the entire ConversationReference in Firebase? Some channels need quite a bit of information on the ConversationReference in order for a proactive message to be successful (especially Teams, not sure about Facebook). Can you set a breakpoint or console.log the conversationReference before it gets sent to show me what data you're using to send the proactive message?

Also note: SMS channels (like Line) are meant to accept pretty much any proactive message because that's generally how SMS works. Other channels tend to need additional, valid data.

**Comment by PeterChen1105** [comment]
@mdrichardson I think I have provided the code for sending the proactive messages above.

1. I defined a Firebase Firestore observer to listen to the changes made on a setting reference document and trigger broadcasting messages

```
settingRef.onSnapshot(
  async docSnapshot => {
    // Retrieve the previous setting information
    var previousSetting = docSnapshot.data().Previous_Setting;
    const uploadFlag = docSnapshot.data().Upload;

    // Update the previous setting & send broadcast messages accordingly
    if (uploadFlag && uploadFlag !== previousSetting.Upload) {
      previousSetting.Upload = uploadFlag;
      settingRef.update({ Previous_Setting: previousSetting });
      await broadcastMessage("Upload");
    }
);
```

2. Sending broadcasting messages by retrieving the conversation references that I stored in Firebase

```
async function broadcastMessage(stage) {
  // Retrieve all conversation references from Firebase
  const allConversationReferences = await getAllConversations();

  for (const conversationReference of Object.values(
    allConversationReferences
  )) {
    await adapter.continueConversation(
      conversationReference,
      async turnContext => {
        await turnContext.sendActivity(CONSTANTS.BROADCAST_MESSAGE[stage]);
      }
    );
  }
}
```

I do store the complete conversation reference in Firebase, I just separated them into different channels for future usage. The conversation references that I stored in Firebase is as follows:

<img width="1072" alt="Conversation Reference" src="https://user-images.githubusercontent.com/53604754/69590202-ceb3d780-1042-11ea-9802-a4e2e20dbaf4.png">

And the conversation reference that I used before sending the messages is just the conversation reference object that I stored in Firebase.

**Comment by mdrichardson** [comment]
I was able to get this working on Facebook without Firebase, so there is definitely something going wrong on your end or with the way you have this set up. Try this and let me know how it goes.

1. Start with a fresh copy of [the Proactive Sample](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/16.proactive-messages/)
2. Add your AppId and AppPassword
3. [Set up ngrok so you can debug locally](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/). Make sure you set your endpoint to your ngrok address
4. Set a breakpoint in `proactiveBot.js` on line 43 so you can capture `conversationReference`. Use `JSON.stringify(conversationReference)` so you can convert that to JSON.
5. Run your bot and send a message to it from Facebook. When it hits the breakpoint, copy down the JSON of `conversationReference`
6. In `index.js`, change the last function, `server.get('/api/notify'...` to:

```js
server.get('/api/notify', async (req, res) => {
    const ref = <your JSON conversationReference>

    try {
        MicrosoftAppCredentials.trustServiceUrl(ref.serviceUrl);
        await adapter.continueConversation(ref, async turnContext => {
            await turnContext.sendActivity('proactive hello');
        });
    } catch (err) {
        console.error(err);
    }

    // for (const conversationReference of Object.values(conversationReferences)) {
    //     await adapter.continueConversation(conversationReference, async turnContext => {
    //         await turnContext.sendActivity('proactive hello');
    //     });
    // }

    res.setHeader('Content-Type', 'text/html');
    res.writeHead(200);
    res.write('<html><body><h1>Proactive messages have been sent.</h1></body></html>');
    res.end();
});
```
7. Add `const { MicrosoftAppCredentials } = require('botframework-connector');` to the top of `index.js`

7. Restart your bot and visit [`http://localhost:3978/api/notify`](http://localhost:3978/api/notify)

I did exactly this and I received the proactive message without any issues. If this works for you, there's something wrong with your code and I would need a copy of it to really debug it.

**Comment by PeterChen1105** [comment]
@mdrichardson After I convert the conversation reference into JSON format before pushing to Firebase, and parse the JSON object before continue the conversation, the problem seems to be fixed. Thx!

I will close this issue now, cheers!

**Comment by dupuis2387** [comment]
i'm wondering if I can also chime in here... since, i'm having this same issue, but on the skype channel. It seems that when i started using the JS bot framework (v4.0ish), the docs/github comments, might have said you could just do 

`MicrosoftAppCredentials.trustServiceUrl('https://smba.trafficmanager.net/apis/', new Date(8640000000000000));` 

once, before you start sending/receiving messages, like as part of your main server.js file, as a "set it and forget it" thing (where your url would differ, depending on what channels you're using).  


But it seems that now, seeing issues reported with stuff like:    

> "message": "Authorization has been denied for this request.",
>  "statusCode": 401,


that `trustServiceUrl` call, has become a thing you're meant to do before every single call to `continueConversation`.... is that the case?

**Comment by mdrichardson** [comment]
@dupuis2387 I believe Skype uses a lot of different serviceUrls based on the user's region. It would be best to grab the serviceUrl from the activity/conversationReference and `trustServiceUrl` right before sending the proactive message, just to be sure. Also, if this happens to be for Skype for Business, that should have [stopped working at the end of October](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-skypeforbusiness?view=azure-bot-service-4.0).
