### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by CealClem** [MicrosoftDocs/bot-docs#1435]
"nain dialog"
should it be main dialog?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Add natural language understanding to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out, I've opened up a [PR](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1901) that fixes this typo. The changes should go live soon.

**Comment by emgrol** [comment]
Closing this now that the typo has been fixed.
