### ISSUE TITLE
Grammar fix - "It's" to "Its"

### ISSUE THREAD

**Issue by roythompsonuno** [MicrosoftDocs/bot-docs#1436]
&gt; Be sure to await any activity calls so the primary thread will wait on the generated activity before finishing it's processing and disposing of the turn context.

Change to: "...generated activity before finishing **its** processing..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ccf81d0-a7a0-1e2a-5b35-8cfd723c1225
* Version Independent ID: e3ebe0a1-a22f-1535-c649-3f79158b4ece
* Content: [How bots work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by zxyanliu** [comment]
Closing because the bug is fixed. Thanks!
