### ISSUE TITLE
Dispatch Source Code

### ISSUE THREAD

**Issue by dkonyayev** [MicrosoftDocs/bot-docs#1437]
Is dispatch source code available? We may need to create a custom dispatch solution that will read from configuration what KBs to add to dispatch. This is useful for us when migrating from DEV to higher environments as KB IDs will change.

**Comment by Kaiqb** [comment]
You can find the Dispatch source code [here](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Dispatch).
