### ISSUE TITLE
Facebook adapter instructions needed

### ISSUE THREAD

**Issue by q00u** [MicrosoftDocs/bot-docs#1438]
I have an existing botbuilder bot running on azure. It worked on the facebook channel, so I know everything is configured and working correctly.

However, the facebook channel is going away soon, and it needs to be converted to working with the adapter.

Unfortunately, I can't find a single working instance of a botbuilder bot working with the facebook adapter. It might work with botkit, but not botbuilder. It can't be tested locally with the emulator (Invalid signature on incoming request). When running on a server, Facebook's webhook callback URL can't connect (possibly related to the previously mentioned bug?)

The current integrations are going away in less than a month. Where is the support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0199d414-87e1-e32d-b528-ee9d2e03c54e
* Version Independent ID: f88f4b08-0977-baee-5226-844695828b95
* Content: [Connect a bot to Facebook Messenger - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-facebook.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-facebook.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
This [page](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-additional-channels?view=azure-bot-service-4.0) has information about adapters and links to Facebook Messenger content.

**Comment by q00u** [comment]
That page doesn't help if the adapter isn't working.

And we can't know if the adapter isn't working if it can't be tested.

And it can't be tested.

**Comment by q00u** [comment]
Your answer is a non-answer. Did you read my question? I don't need generalities on what the difference is between a channel and an adapter.

I have a working existing botbuilder bot using the Facebook channel.

**The Facebook channel is going away in less than a month.**

**There's no working Facebook adapter example for botbuilder.**

Please show me where on your answer the solution to this is.
