### ISSUE TITLE
Facebook adapter instructions needed

### ISSUE THREAD

**Issue by q00u** [MicrosoftDocs/bot-docs#1439]
**The Facebook channel is going away in less than a month.**

**There's no working Facebook adapter example for botbuilder.**

(Please note, nobody is asking what an adapter is, or what is the difference between an adapter and a channel. We just need ONE working example for botbuilder.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0199d414-87e1-e32d-b528-ee9d2e03c54e
* Version Independent ID: f88f4b08-0977-baee-5226-844695828b95
* Content: [Connect a bot to Facebook Messenger - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-facebook.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-facebook.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
We'll follow up with the team and get back to you.

**Comment by Kaiqb** [comment]
We are working on adding adapters for other channels and will update documentation as those adapters become available. If you are using JS, you can take a look at this [topic](https://botkit.ai/docs/v4/platforms/) about using botbuilder-adapter-facebook.

**Comment by marcasmar94** [comment]
> 
> 
> **The Facebook channel is going away in less than a month.**
> 
> **There's no working Facebook adapter example for botbuilder.**
> 
> (Please note, nobody is asking what an adapter is, or what is the difference between an adapter and a channel. We just need ONE working example for botbuilder.)
> #### Document Details
> 
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
>     * ID: 0199d414-87e1-e32d-b528-ee9d2e03c54e
> 
>     * Version Independent ID: f88f4b08-0977-baee-5226-844695828b95
> 
>     * Content: [Connect a bot to Facebook Messenger - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0#feedback)
> 
>     * Content Source: [articles/bot-service-channel-connect-facebook.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-facebook.md)
> 
>     * Service: **bot-service**
> 
>     * GitHub Login: @Kaiqb
> 
>     * Microsoft Alias: **kamrani**

What do you mean the Facebook channel is going away? Does this apply to all Bot framework bots connected to a normal facebook page messenger or only WorkPlace ?

**Comment by aishwarya-u** [comment]
Do we have to configure any adapters for the C# code?

**Comment by JonathanFingold** [comment]
An update to the Facebook article should go live soon ([PR 1923](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1923)). You can look at the **Facebook adapter** sample: [C#](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/61.facebook-adapter) or [JavaScript](), for an example of how to connect to Facebook with the new Facebook adapter.

**Comment by turbozapekanka** [comment]
Is The Facebook channel is going away? I thought it is only Facebook Workplace which will stop working, but Facebook messenger will still be supported.
