### ISSUE TITLE
v4 SDK update

### ISSUE THREAD

**Issue by evandropomatti** [MicrosoftDocs/bot-docs#1442]
Please add State Management documentation for version 4 of the SDK for Node.js.

Table storage is no longer available. It seems that the options are now BlobStorage or Cosmos DB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee04844e-a1c9-9011-50f7-90b59d329caa
* Version Independent ID: 51d48e6f-dd2e-3289-f38e-c943c6c53cad
* Content: [Manage custom state data with Azure Table storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state-azure-table-storage?view=azure-bot-service-3.0&viewFallbackFrom=azure-bot-service-4.0#feedback)
* Content Source: [articles/nodejs/bot-builder-nodejs-state-azure-table-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-state-azure-table-storage.md)
* Service: **bot-service**
* GitHub Login: @ducvo
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@evandropomatti - does the [Cosmos DB](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0#using-cosmos-db) section of the **Write directly to storage** article contain the information you're looking for?

**Comment by evandropomatti** [comment]
Yes, it does. Indeed it was my stupidity for seeing that there is a JavaScript tab in there. Thanks.

**Comment by JonathanFingold** [comment]
No worries, glad to help.
