### ISSUE TITLE
Can't find Cosmos DB reference for V4

### ISSUE THREAD

**Issue by evandropomatti** [MicrosoftDocs/bot-docs#1443]
When I go the V4 SDK for Node JS I can't find the instructions on how to configure it for Cosmos DB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 432edb74-c60c-6416-c568-69fcbe0a768e
* Version Independent ID: 06e3a7a0-263c-9654-d328-8d573c0552ea
* Content: [Manage custom state data with Azure Cosmos DB - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state-azure-cosmosdb?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-state-azure-cosmosdb.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-state-azure-cosmosdb.md)
* Service: **bot-service**
* GitHub Login: @ducvo
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@evandropomatti - is this a duplicate of #1442?

**Comment by evandropomatti** [comment]
Yes it is, sorry.
