### ISSUE TITLE
"Create the Dispatch Model" Section

### ISSUE THREAD

**Issue by roythompsonuno** [MicrosoftDocs/bot-docs#1450]
This may be a result of my novice with using bot framework/bot service, but some clarification may be helpful. 

I followed the https://microsoft.github.io/botframework-solutions/ tutorials using the virtual assistant and skill C# templates through Visual Studio. No Cognitive Models folder is generated. I'm not sure what I need to do, or if this document does not apply to my use case. I may be going down the wrong path on what documentation I'm using, but if something is out of date an update would be great. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs#create-the-dispatch-model)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by roythompsonuno** [comment]
Another question that this article left me with that might be valuable to new users, like me:

If I'm using Luis to dispatch to a skill that uses a QnA model, do the intent's example utterances need to be more or less the same as the QnA knowledgebase questions? In other words, do I need to copy the questions in the knowledge base over to the Luis intent for the recognizer to work?

**Comment by diberry** [comment]
@tsuwandy Can you provide details to help this customer?

**Comment by tsuwandy** [comment]
@roythompsonuno, regarding using LUIS to dispatch to skill using QnA kb question, are you using Dispatch CLI to dispatch to multiple skills?  https://github.com/microsoft/botbuilder-tools/tree/master/packages/Dispatch

If so, you won't have to copy the questions over as the Dispatch tool will do it for you.  The output of the tool is a LUIS app which helps dispatch user utterances to the sub models/skills.  Hope this helps.

**Comment by HowdySys** [comment]
This helps! Thank you @diberry and @tsuwandy!
