### ISSUE TITLE
Package source asks for login

### ISSUE THREAD

**Issue by Cage-e** [MicrosoftDocs/bot-docs#1453]
Trying to follow the steps [on this page](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0) but the package source asks for login info. Can public access this source?

I'm basically trying to create a client to use in a Xamarin project. We cannot use web chat as we have a lot of customization and functionalities on top of the chat view. Am I on the right track?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c463a003-c709-b516-ce1b-6c45537de3b2
* Version Independent ID: 8ca42668-23ac-6dca-054d-d183b0fb5b0b
* Content: [Create .NET client to connect to direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-directline-extension-net-client.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-client.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mdrichardson** [comment]
@Cage-e The feed is now public. There were a few packages that got merged into the main SDK and the whole experimental feed was mistakenly closed instead of just a few packages.
