### ISSUE TITLE
Cant access DL ASE Preview, even after adding account on botbuilder.myget.org

### ISSUE THREAD

**Issue by DarrenThurman** [MicrosoftDocs/bot-docs#1454]
I have created an account on botbuilder.myget.org and logged in.
When I try to access the link given in the article, I get "You are not allowed to access this feed."

What do I need to do to get access the the ASE preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c463a003-c709-b516-ce1b-6c45537de3b2
* Version Independent ID: 8ca42668-23ac-6dca-054d-d183b0fb5b0b
* Content: [Create .NET client to connect to direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-directline-extension-net-client.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-client.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mdrichardson** [comment]
@DarrenThurman The feed is now public. There were a few packages that got merged into the main SDK and the whole experimental feed was mistakenly closed instead of just a few packages.
