### ISSUE TITLE
Can not change bot channel display name.

### ISSUE THREAD

**Issue by TheCSir** [MicrosoftDocs/bot-docs#1455]
I tried to change the bot channel registration display name in azure web portal shown in this document, but it changes back to the previous one once I click save. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b527247b-38f8-0bc0-6eda-af6382d8f1af
* Version Independent ID: e1c371cc-9183-1138-69e3-77a096a9f964
* Content: [Configure bot settings - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-settings?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-manage-settings.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-manage-settings.md)
* Service: **bot-service**
* GitHub Login: @v-royhar
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@jameslew - is that a bug?

**Comment by zxyanliu** [comment]
I just tried and the display name cannot be changed. I believe it is a bug of Azure. @Kaiqb Should I update the [doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-settings?view=azure-bot-service-4.0)?

**Comment by cube32chris** [comment]
Also tried to change display name and it reverted back to previous.

**Comment by zxyanliu** [comment]
Right, I had the same experience. Thanks for reporting the bug. @cube32chris

**Comment by MarkLeiSource** [comment]
I faced the same problem, I need to follow the process of the bug. When will it get fixed?

**Comment by alexmanie** [comment]
Same here :(

**Comment by cube32chris** [comment]
Spoke to my guy on the inside, they know about it but there's been a code freeze around thanksgiving, should be sorted soon.

**Comment by zxyanliu** [comment]
Hi @cube32chris, thanks for the info.

**Comment by alexmanie** [comment]
The error changing Display name seems to be fixed

**Comment by cube32chris** [comment]
Tried on two bot registrations this morning. Worked great for me. Thanks!

**Comment by MarkLeiSource** [comment]
Worked great for me too, thanks a lot.

**Comment by zxyanliu** [comment]
Yes. I just tested it and the bug is fixed. Thanks for the updates @cube32chris @alexmanie @MarkLeiSource. Now that the Azure bug is fixed and there is nothing I should update in the [doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-settings?view=azure-bot-service-4.0), I am closing this issue. :)

**Comment by mayureshjaiswal** [comment]
Hi There,

I'm facing this issue from last 2 days, previously i was able to change the name and icon, but from last 2 days i'm trying to change it but the changes are not getting reflected. Can you please help on this.
