### ISSUE TITLE
Changing the default input speech language from English(en-us) to Cantonese(zh-HK)

### ISSUE THREAD

**Issue by wilsonlapwong** [MicrosoftDocs/bot-docs#1459]
Hi,
I have created Direct Line channel by following the document:
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat-speech?view=azure-bot-service-3.0  

The Web Chat with Speech is working well except that I have difficulty to change the default input speech language from English(en-us) to Cantonese(zh-HK).  Please advise me how to do so.  Thanks.

Regards,
Wilson

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c80aea9-056c-2248-9f6a-e4d821a1719a
* Version Independent ID: 7005835c-74b4-3a5f-ec35-a77c1a6cfc3b
* Content: [Enable speech in Web Chat - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat-speech?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-channel-connect-webchat-speech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-webchat-speech.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by stevkan** [comment]
The article you reference is for using [BotChat](https://github.com/microsoft/BotFramework-WebChat/tree/v3#microsoft-bot-framework-web-chat) (i.e., BotFramework-WebChat **v3**). This version is currently deprecated. Is v3 the version you are using or did you mean [v4 Web Chat](https://github.com/Microsoft/BotFramework-WebChat#bot-framework-web-chat)?

**Comment by wilsonlapwong** [comment]
Hi Steven,

I mean v4 Web Chat.  Thanks.

Regards,
Wilson

Steven Kanberg <notifications@github.com> 於 2019年12月5日週四 下午6:18寫道：

**Comment by stevkan** [comment]
Hi @wilsonlapwong, thank you for your patience. If you reference sample [06.g.select-voice](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.g.select-voice) from the BotFramework-WebChat repo, this demonstrates how to set the speech voice / language based on the user's locale.

In the snippet below, if the user's locale is `de-DE` (i.e. Germany), then German will be spoken using the "Stefan" or "Karsten" as the voice. If you are wanting to override the user's actual locale, you can pass that value in, as well (commented out).

```js
window.ReactDOM.render(
  <ReactWebChat
    directLine={ directLine }
    // locale={'fr-FR'}
    selectVoice = {( voices, activity ) =>
    activity.locale === 'de-DE' ?
      voices.find( ( { name } ) => /Stefan-Apollo/iu.test( name ) )
      :
      voices.find( ( { name } ) => /Stefan-Apollo/iu.test( name ) )
      || voices.find( ( { name } ) => /Karsten/iu.test( name ) )}
    webSpeechPonyfillFactory={webSpeechPonyfillFactory}
  />,
  document.getElementById( 'webchat' )
);
```

Does this help?

**Comment by wilsonlapwong** [comment]
Hi Steven,

Thank for your feedback.  It really helps.

Regards,
Wilson

Steven Kanberg <notifications@github.com> 於 2019年12月13日週五 上午7:01寫道：
