### ISSUE TITLE
Where is Azure Bot Service?

### ISSUE THREAD

**Issue by Robotbae** [MicrosoftDocs/bot-docs#1461]
Hello  - I'm curious, I am trying to make a case that Azure Bot Service is held only in a particular region and all information is secure. I've found a couple things that I want to clarify : 

On this [link ](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0#how-can-i-migrate-azure-bot-service-from-one-region-to-another)

How can I migrate Azure Bot Service from one region to another?
Azure Bot Service does not support region move. It’s a global service that is not tied to any specific region.

My first question is : What is meant by global service? 

To help understand further, another piece of info got me curious. When creating a Web App Bot and creating a new resource group just for lols, this came up in the 'additional info', the word global came up again 

Second question: Where can I obtain more detail on non-content data being stored and where is it being stored? Highlighting on the term : Routing data, registration data and design data **globally** 

![image](https://user-images.githubusercontent.com/50206076/69814377-fb572300-11eb-11ea-9e76-8b703acedf41.png)

Just wanted to get more detail to show that when a bot is being deployed on Teams, the information transfer between Azure Bot Service and MS Teams is secure

**Comment by Robotbae** [comment]
Hiya - any luck?

**Comment by Robotbae** [comment]
Hello again - any luck on the question? I am happy to rephrase it if easier?

**Comment by jwiley84** [comment]
Hi @Robotbae!

>How can I migrate Azure Bot Service from one region to another?
Azure Bot Service does not support region move. It’s a global service that is not tied to any specific region.

I'm not certain how to break that down any more. For load balancing, and similar purposes, ABS is not set to one region. Your client will call the ABS by interacting with your bot, and then the ABS routes this traffic to the web app, but not through any particular data center, to which ever data center your bot is hosted in.

**Comment by Robotbae** [comment]
Hello! Thanks for your response. Essentially I was trying to draw out what is meant by “global service” 

How do we ensure that the called bot service remains in one particular region if we know both the client and the web app is both in one single region? If even possible to ensure the data does not leave that one region 

What does routing data, design data and registration data entail?

**Comment by dmvtech** [comment]
> Essentially I was trying to draw out what is meant by “global service”

This is really referring to the Bot Channels Registration (one resource, created as part of a Web App Bot if not created on it's own). This consists of the information (in settings) that points to the bot endpoint (where your bot code is), as well as information about what channels the bot is configured for, etc. These resources are deployed to every region.


> Second question: Where can I obtain more detail on non-content data being stored and where is it being stored? Highlighting on the term : Routing data, registration data and design data globally

> Just wanted to get more detail to show that when a bot is being deployed on Teams, the information transfer between Azure Bot Service and MS Teams is secure


>How do we ensure that the called bot service remains in one particular region if we know both the client and the web app is both in one single region? If even possible to ensure the data does not leave that one region


>What does routing data, design data and registration data entail?

I'm not sure about these. I'll see if there is any more information available.

**Comment by Robotbae** [comment]
Thank you for getting back to me - yes please do quite keen on keeping the ABS to route and is only in and about one region

**Comment by dmvtech** [comment]
@Jeffders is looking into this. It may be a bit until we have any sort of information/answer for you @Robotbae

**Comment by CoHealer** [comment]
Adding @Jeffders  to comment when he looks at this after returning after holiday.

**Comment by Robotbae** [comment]
Thanks for keeping me in the loop! Happy New Year!

**Comment by Robotbae** [comment]
Hi all - any update on this ? Cheers

**Comment by dmvtech** [comment]
Closing as stale.

To reiterate; bot resources (bot channels registration, web app bot, azure bot) are global/non-regional. This does not include the supporting resources such as web app/app service, storage account, app service plan, etc, etc. 

https://azure.microsoft.com/en-us/global-infrastructure/services/?products=bot-services
