### ISSUE TITLE
Action support by channel is difficult to understand

### ISSUE THREAD

**Issue by psbds** [MicrosoftDocs/bot-docs#1462]
Hi,

Is difficult to understand the meaning of the "Action Support ny channel" table, as it is showing numbers, instead of icons like the tables above in the same document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60950444-cdcc-f0b9-aa21-c99894e26b50
* Version Independent ID: 0bd14221-e030-f9d8-41e6-1a52c9a76440
* Content: [Channels reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#action-support-by-channel)
* Content Source: [articles/bot-service-channels-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channels-reference.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by EricDahlvang** [comment]
Hi @psbds 

Those numbers are from https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs

Maybe the title of this section should be: "The following table shows total Card Actions and Suggested Actions supported by channel."

**Comment by EricDahlvang** [comment]
Closing, since this has been addressed by @WashingtonKayaker https://github.com/MicrosoftDocs/bot-docs-pr/pull/1905
