### ISSUE TITLE
Payment Request out of use? why?

### ISSUE THREAD

**Issue by mvgoffin** [MicrosoftDocs/bot-docs#1469]
Hi,
I also found in this documentation that "Request Payment" service was deprecated on December 1, 2019, why? Is there a way to integrate a Payment capabilities into Azure bot or Virtual Agents? Many thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60950444-cdcc-f0b9-aa21-c99894e26b50
* Version Independent ID: 0bd14221-e030-f9d8-41e6-1a52c9a76440
* Content: [Channels reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channels-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channels-reference.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@mvgoffin - you might be able to use 3rd party service.

**Comment by mvgoffin** [comment]
Thanks Kaiqb
