### ISSUE TITLE
Global Message Handlers sample (GitHub) page is not found

### ISSUE THREAD

**Issue by okulygin** [MicrosoftDocs/bot-docs#1472]
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-GlobalMessageHandlers 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b69f4105-9442-84c9-5fb3-2064f5856973
* Version Independent ID: 5c63b35f-f9cd-3ad4-af89-47062d5e7ec3
* Content: [Implement global message handlers - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-global-handlers?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-global-handlers.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-global-handlers.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Closing this issue because it is addressed. @okulygin Thanks again!
