### ISSUE TITLE
Disabling activity logging in app insights

### ISSUE THREAD

**Issue by anishjaindev** [MicrosoftDocs/bot-docs#1473]
How can we disable activity logging in custom events in application insights. I still may need app insights on for diagnostic information of the server but not require to log activity logs. If we wipe out the keys information from settings page, will the activity logging be disabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6120c4f2-ec78-8909-5fd8-46ec6fc8f434
* Version Independent ID: c5f17144-c914-e77c-628b-7be593f0570c
* Content: [Bot analytics - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-manage-analytics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-manage-analytics.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
Please see [Enabling / disabling activity event and personal information logging](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0#enabling--disabling-activity-event-and-personal-information-logging) in the Azure Bot Service Documentation.

**Comment by anishjaindev** [comment]
Thanks @WashingtonKayaker . The above documentation page refers to C# implementation. Is there any plans to upload how it can be done using Node.Js

**Comment by JonathanFingold** [comment]
@anishjaindev Sorry for the long delay. Does the [Add telemetry to your bot](https://docs.microsoft.com/azure/bot-service/bot-builder-telemetry) article contain the information you're looking for?

**Comment by JonathanFingold** [comment]
Please reopen if your issue has not been addressed.
