### ISSUE TITLE
.Net Framwork instructions missing

### ISSUE THREAD

**Issue by ignaciobe** [MicrosoftDocs/bot-docs#1474]
Since the bot integration with no longer work using azure channel, there are instructions for integrate it using javascript/node js.

What about existing integrations using .Net Framework or .Net Core? Is it there an example to integrate it now?

Thanks

**Comment by zxyanliu** [comment]
What did you mean by "no longer work using azure channel"? What specifically are you trying to accomplish? Is there any doc you are referring to? We need more details to answer your question. Thank you!

**Comment by zxyanliu** [comment]
Hey, please provide us with more information as asked in the last thread so that we can better help you.

**Comment by ignaciobe** [comment]
Hi I misunderstood the message added to the documentation. It says that workplace for facebook is which has no longer support. Facebook messenger will still working.
