### ISSUE TITLE
429 HTTP Status Code Issue for Chat Bot 

### ISSUE THREAD

**Issue by MarkLeiSource** [MicrosoftDocs/bot-docs#1476]
Hi dear,

I am developing a chat bot app on MS Teams platform, when I testing my broadcast feature of the bot, I got the 429 HTTP status code error, the broadcast feature need to send one common message text to more than 150 Teams app users at the same time, I found maybe 65 users' broadcast messages had been rejected by 429 Error,  so my questions are:

1.What is the rate limit for my case ?
2.If 150 messages in one second is too many, what is the best practice for the amount?
3. Is there any other solution or workaround for my case other then split the users into many groups and add some sleep time between each groups, or add some back-off retry logic?

Many thanks,

**Comment by WashingtonKayaker** [comment]
Hi Mark, There is an article in the Teams documentation titled [Optimize your bot: rate limiting and best practices in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit) that should help you resolve this.  Basically you will need to either handle the 429's through incremental backoffs, or send the messages slow enough that you don't receive 429's.

You might find the company communicator app template helpful as well. The Company Communicator is a custom Teams app that enables you to create and send messages intended for multiple teams or large number of employees over chat. It implements a full backoff and retry strategy, for more information please refer to its [readme](https://github.com/OfficeDev/microsoft-teams-company-communicator-app#company-communicator-app-template) on GitHub, you can download it from there as well.

**Comment by CoHealer** [comment]
Removing support label in lieu of the solution presented. Mark, if the Teams docs mentioned above do not resolve you issue please feel free to reopen the issue.
