### ISSUE TITLE
Twilio Card Support

### ISSUE THREAD

**Issue by mdrichardson** [MicrosoftDocs/bot-docs#1477]
My mistake on the "Card Support by Channel" table.

All of the cards for Twilio that are currently ✔ should actually be 🌐

I'd submit a PR for this, myself, but [the public version](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channels-reference.md) doesn't appear to be up-to-date with this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60950444-cdcc-f0b9-aa21-c99894e26b50
* Version Independent ID: 0bd14221-e030-f9d8-41e6-1a52c9a76440
* Content: [Channels reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-3.0#card-support-by-channel)
* Content Source: [articles/bot-service-channels-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channels-reference.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
I updated the article with these changes (PR1903).
