### ISSUE TITLE
How to pass trusted Origin in .net Token Controller

### ISSUE THREAD

**Issue by satyansh-sagar** [MicrosoftDocs/bot-docs#1478]
Hi team, 
I'm working on a direct line channel with Bot framework. I don't want the Magic code to be shown to user. As per the document we need to pass trusted origins in direct-line client. How to do that in token controller?

Someone please help me out?
@msft-jinayoon  @msft-shahins  @msftbrking

**Comment by stevkan** [comment]
Hi @satyansh-sagar,

You can pass trusted origins within the Direct Line channel blade. Simply select the channel in your Azure bot settings, click 'enable' on 'Enhanced authentication options', and add the trusted origin and click 'Done'.

Let me know if this doesn't work for you.

![image](https://user-images.githubusercontent.com/18403946/71125793-7634ad80-219c-11ea-8146-55b47cb7ebbc.png)

**Comment by stevkan** [comment]
Closing as resolved.
