### ISSUE TITLE
This package is no longer existing: Microsoft.Bot.Builder.StreamingExtensions

### ISSUE THREAD

**Issue by xieofxie** [MicrosoftDocs/bot-docs#1479]
It is only 4.5.1 https://www.nuget.org/packages/Microsoft.Bot.Builder.StreamingExtensions/4.5.1-preview1
However, sdk is 4.7 now https://www.nuget.org/packages/Microsoft.Bot.Builder/
Does it still work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72c259-a864-9e1c-b585-562d6bca80ff
* Version Independent ID: 30a3fce8-d236-5c7b-88a0-003c971f2819
* Content: [.NET bot with direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @xieofxie Thanks for reporting this issue. I have been actively contacting our engineers regarding this issue and I apologize for replying to you late. 

FYI. `Microsoft.Bot.Builder.StreamingExtensions v4.5.1` was a preview package and is not going to be updated. The streaming code is actually in the `SDK` now (not a separate library). Read [here](https://github.com/microsoft/botbuilder-dotnet/tree/master/libraries/Microsoft.Bot.Builder/Streaming). 

I think we will update the [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0) soon.

**Comment by zxyanliu** [comment]
Also, FYI. I just tested using `Microsoft.Bot.Builder.StreamingExtensions v4.5.1` against `SDK v4.7`. It seems that it works.
