### ISSUE TITLE
This documentation is old

### ISSUE THREAD

**Issue by cwhd** [MicrosoftDocs/bot-docs#1480]
For the latest on this you should reference this:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=JavaScript

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a43a9bfa-a69a-ffb2-31a6-d06d78517671
* Version Independent ID: 6bcbbcbf-79f2-9b81-7d03-b9bd8d6286a1
* Content: [Send proactive messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-proactive-messages?view=azure-bot-service-3.0&viewFallbackFrom=azure-bot-service-4.0#feedback)
* Content Source: [articles/nodejs/bot-builder-nodejs-proactive-messages.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-proactive-messages.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Hi @cwhd, there is a link at the top of the page that points to the v4 docs as you can see below:
![title](https://user-images.githubusercontent.com/9682548/71203606-2107a300-2253-11ea-92f8-f0e75bf809f5.png)


The link abover is automatically generated to point to our v4 docs homepage. The v3 SDK will be deprecated soon as well so we don't expect customers to visit this page frequently.
