### ISSUE TITLE
Customer Doesn't Want to Whitelist "*.botframework.com"

### ISSUE THREAD

**Issue by gamullen** [MicrosoftDocs/bot-docs#1481]
Our customer's security team won't let them whitelist a URL with an asterisk; only concrete URLs or a concrete range of IPs.

Can one of those be provided for "botframework.com"?

Thanks, Gary

**Comment by zxyanliu** [comment]
Hi @gamullen Thanks for reporting. I was wondering if there is a document you or your customer's security team is referring to?

**Comment by gamullen** [comment]
Sorry, not sure how that comment didn't get associated with the page. This: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0

**Comment by zxyanliu** [comment]
Hi! Thanks for your reply. We are coordinating with our engineering team for this issue. Will let you know shortly.

**Comment by mdrichardson** [comment]
@gamullen `*.botframework.com` is preferred and certainly more future-proof (in case we change the names or something), but you should be able to get away with using `token.botframework.com` and `<channel>.botframework.com`, where `<channel>` is equal to every channel that your bot uses, for example:

* `directline.botframework.com`
* `slack.botframework.com`
* etc

That *should* cover your needs, but it might be worthwhile to watch traffic over your firewall while testing the bot to make sure something else isn't getting blocked.

**Comment by gamullen** [comment]
Great, thanks! Will that be making its way into the documentation?

**Comment by zxyanliu** [comment]
I can add the content into the documentation. @gamullen @mdrichardson

**Comment by CoHealer** [comment]
@zxyanliu , is there an eta on the document update so we can close this issue?

**Comment by zxyanliu** [comment]
Hi @CoHealer 
Yes, it is fixed in [PR 1927](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1927). @mdrichardson helped a lot and reviewed the PR. I will close this issue when 1927 get merged.

**Comment by CoHealer** [comment]
Great, thanks

**Comment by zxyanliu** [comment]
Closing the issue since the PR is merged and content will go live soon. @gamullen Thanks again!
