### ISSUE TITLE
Unclear what "Reuse dialogs" document is for

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1483]
The [dialogs library](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0#component-dialog) documentation links to this document as though it explains what component dialogs are all about. However, component dialogs are not about "reusing dialogs" as the title would suggest. If we wanted a document about reusing dialogs then it would make more sense to have it be about prompts since you can reuse a prompt dialog many times and pass in different prompt options to prompt with each time. Then again, this document is kind of already about prompts, but the prompt dialogs in the given sample aren't reused.

The document has a lot more to do with how to use waterfalls than how to use component dialogs or how to reuse dialogs, but even then it's not really framed as a coherent waterfall guide either. It's hard to know how to improve this document without knowing what its intended purpose is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9577ff-cf56-e5de-84c3-bfe10aab5368
* Version Independent ID: b5d62753-f87b-4673-b09b-a5a3fd9360e8
* Content: [Reuse dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=javascript#feedback)
* Content Source: [articles/v4sdk/bot-builder-compositcontrol.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-compositcontrol.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by stevejwebb** [comment]
I am trying to work out how to use multiple waterfall conversations and this does not give me any insight
