### ISSUE TITLE
This topic applies to SDK v3 release. You can find the documentation for the latest version of the SDK v4 here.

### ISSUE THREAD

**Issue by DavidStrickland0** [MicrosoftDocs/bot-docs#1484]
No you cant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a79c4cc-6f80-91ad-6a88-81874f7154a1
* Version Independent ID: ac8f6181-1f8a-8911-5e3d-6421bfb2c94d
* Content: [Send a typing indicator - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-typing-indicator?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-send-typing-indicator.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-send-typing-indicator.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Hi @DavidStrickland0, that link at the top of the page is part of a boilerplate message at the top of all v3 docs. We are currently working on the v4 article for this topic.

**Comment by JonathanFingold** [comment]
@DavidStrickland0 , If you have a process that will take a while, you can just periodically send a simple { type: 'typing' } object. However, the request will timeout after 15 seconds. So, if the process is in danger of running long, consider sending a simple acknowledgement immediately and a proactive message later, when the process finishes. Here's an updated echo bot that sends a typing activity:

```javascript
const { ActivityHandler } = require('botbuilder');
const { ActivityTypes } = require('botbuilder-core');

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

class EchoBot extends ActivityHandler {
    constructor() {
        super();
        // See https://aka.ms/about-bot-activity-message to learn more about the message and other activity types.
        this.onMessage(async (context, next) => {
            if (context.activity.text === 'wait') {
                await context.sendActivity({ type: ActivityTypes.Typing });
                await sleep(3000);
                await context.sendActivity('Finished typing');
            } else {
                await context.sendActivity(`You said '${ context.activity.text }'. Say "wait" to watch me type.`);
            }
            await next();
        });

        this.onMembersAdded(async (context, next) => {
            const membersAdded = context.activity.membersAdded;
            for (let cnt = 0; cnt < membersAdded.length; ++cnt) {
                if (membersAdded[cnt].id !== context.activity.recipient.id) {
                    await context.sendActivity('Hello and welcome!');
                }
            }
            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });
    }
}
```

**Comment by emgrol** [comment]
Closing this now that instructions for adding typing indication to v4 C#, Javascript, and Python bots have been added to the Send and receive text message [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-send-messages?view=azure-bot-service-4.0&tabs=csharp#send-a-typing-indicator).
