### ISSUE TITLE
Codeblocks need update.

### ISSUE THREAD

**Issue by Crare** [MicrosoftDocs/bot-docs#1485]
For example there is no "TextBlock"-class, I think it is "AdaptiveTextBlock" and so on..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c205b864-640c-a101-8468-6227d8f2e7cb
* Version Independent ID: a8c5bdba-01f3-46ec-1c73-a8fabd4ccf0f
* Content: [Add rich card attachments to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-rich-card-attachments?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/dotnet/bot-builder-dotnet-add-rich-card-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-add-rich-card-attachments.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Thanks for reporting, we will update shortly.

**Comment by zxyanliu** [comment]
Hi, any luck?

**Comment by zxyanliu** [comment]
Hi, I am closing this issue now. Please feel free to reopen it when necessary.
