### ISSUE TITLE
O365 Accounts with MFA enabled don't work

### ISSUE THREAD

**Issue by mahamr** [MicrosoftDocs/bot-docs#1487]
It may helpful to others to note that any account with MFA enabled on it, cannot be configured for the email channel. MFA for that specified account needs to be disabled first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db64bd62-cf60-5d73-c1a1-37f480ec59bd
* Version Independent ID: f20bc448-a105-d242-0ec0-369ceba1044e
* Content: [Connect a bot to Office 365 email - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-email?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-email.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-email.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi! Thanks for reporting this issue. We will work on it and get back to you soon.

**Comment by zxyanliu** [comment]
Closing because the PR is merged and content will go live soon. @mahamr Thanks again for pointing out the bug and help us improve.

**Comment by anthonyarmatasMS** [comment]
It appears with the addition of Oauth to the mail channel that O365 Accounts with MFA now works. The Doc should be updated to reflect that. Thanks.
