### ISSUE TITLE
Please let us know how to add Telemetry in "49. qnamaker-all-features" sample code

### ISSUE THREAD

**Issue by duvarajan** [MicrosoftDocs/bot-docs#1488]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db892de5-e60e-1d4f-505b-11b1cdb73323
* Version Independent ID: f7263014-b8fa-9a20-71aa-e4217b2821ee
* Content: [Add telemetry to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/bot-builder-telemetry.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-telemetry.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi! Please read the [add telemetry to your QnA bot article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-qnamaker?view=azure-bot-service-4.0).

**Comment by duvarajan** [comment]
Hi, I had read the link earlier but there was no mention about what changes we need to do in the files like "QnAMakerBaseDialog.cs", "RootDialog.cs" and "QnABot.cs". Also, please provide me a sample query to view the telemetry log data in Application insights. I wish to store the user conversations too so that I can store in a database for your future reference. Please help me on this too! Thank you!

**Comment by duvarajan** [comment]
I still did not get any response for my issue mentioned earlier here. 
Now can anyone could tell me how I can get more than 1 answer for a question irrespective of scores. Currently I could get only one answer as there was a command   response.Answers.First(). Please help me what command I need to provide to get multiple answers. Where do I need to do the change. I'm using "49.qnamaker-all-features" sample code.

**Comment by zxyanliu** [comment]
Hi, Sorry about that! Our colleague who is specialized in telemetry is on vacation and will come back very soon. We apologize for the inconvenience. Will come back to solve your issue very soon.

**Comment by JonathanFingold** [comment]
@duvarajan There are two ways to manage the responses you get back from QnA Maker:
1. When you create the [QnAMaker](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.ai.qna.qnamaker?view=botbuilder-dotnet-stable) instance, use the `Top` and `ScoreThreshold` properties of the [QnAMakerOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.ai.qna.qnamakeroptions?view=botbuilder-dotnet-stable) class to limit the results you get back.
1. Filter the results collection after the call to `QnAMaker.GetAnswersAsync`. Each [QueryResult](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.ai.qna.queryresult?view=botbuilder-dotnet-stable) has a confidence `Score`. You can use that to pick the top few responses to present to the user.

**Comment by JonathanFingold** [comment]
With respect to querying the telemetry data, we have a new article [Analyze your bot's telemetry data](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-analytics-queries?view=azure-bot-service-4.0).

**Comment by JonathanFingold** [comment]
Closing for now. Please reopen if your questions are not answered.

**Comment by buddeshya** [comment]
@duvarajan @JonathanFingold 
Hi, were you able to add telemetry in "49. qnamaker-all-features".
I am trying to add telemetry, but it's not clear which file requires changes. 
I want to store the conversation of the user and bot. 
Can you please help?
Thanks
