### ISSUE TITLE
About pre-deploy builds from zip files

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/bot-docs#1494]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/bot-docs.ja-jp/issues/9

The comments below were machine-translated

@tfukumori commented 11 hours ago — with docs.microsoft.com
&gt; "Kudu assumes by default that you are ready to perform a deployment from a zip file and that no additional build steps such as npm install or dotnet restore / dotnet publish are required during deployment."

As you might guess from the above, you might be able to state that the build will be done in Release.

When using Debug build "only" for testing with Bot Emulator, the following problems occurred only when Japanese was used for the message. (There was no problem with sample English)

Error deploying from zip file
Garbled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by anusharavindrar** [comment]
@tfukumori can you please elaborate more on what you are trying to do and add the steps to repro?

**Comment by tfukumori** [comment]
The reproduction procedure is described in this URL, so please check it
https://github.com/projectkudu/kudu/issues/3103

**Comment by anusharavindrar** [comment]
@tfukumori thanks for the link to the related issue. Just to be more clear, so when you use the code which has the message in English("Hello and welcome!") as well as in Japanese("こんにちは"), the deployment is successful, but when you use ("いらっしゃいませ。テストボットです。"), the deployment fails? Also, as per the above linked issue, the issue appears to be resolved. Did the problem reappear?

**Comment by tfukumori** [comment]
Thank you for your answer.
Below are the answers and detailed steps.

# Answer

> Just to be more clear, so when you use the code which has the message in English("Hello and welcome!") as well as in Japanese("こんにちは"), the deployment is successful, but when you use ("いらっしゃいませ。テストボットです。"), the deployment fails? Also, as per the above linked issue, the issue appears to be resolved. Did the problem reappear?

If the solution configuration at the time of build was "Debug" and the message used Japanese ("いらっしゃいませ。テストボットです。"), The Zip deployment failed.

## Table showing conditions

|No|Solution Configuration|Message|Local Bot Emulator|Zip Deployment|
|:--|:--|:--|:--|:--|
|1|Debug|"Hello and welcome!"|Success|Success|
|2|Debug|"いらっしゃいませ。テストボットです。"|Success|Fail|
|3|Debug|"こんにちは"|Success|Success. But Garbled. <br>"?±?n?E???I"|
|4|Release|"Hello and welcome!"|Success|Success|
|5|Release|"いらっしゃいませ。テストボットです。"|Success|Success|
|6|Release|"こんにちは"|Success|Success|

# Environments

- Visual Studio: 2019 Community 16.4.0
- Azure CLI: azure-cli-2.0.78

# Detailed steps

1. Create sample project according to [documentation](https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp).
2. Change the Solution Configuration to "Debug" from the toolbar. Select a project in Solution Explorer and clean.
3. Change the Solution Configuration to "Release" from the toolbar. Select a project in Solution Explorer and clean.
4. Change the Solution Configuration according to the table above from the toolbar. Change the message according to the table above. Select a project in Solution Explorer and build.

# Request

Could you please add the following note to [document](https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp).

"Zip deployment may fail if the Solution Configulation at build is Debug"
"ビルド時のソリューション構成がデバッグの場合、Zip deploymentが失敗する場合があります"

**Comment by CoHealer** [comment]
@JonathanFingold / @emgrol , can either one of you help with the doc update request above and close the issue?

**Comment by JonathanFingold** [comment]
@CoHealer One of use will update the docs this week. Thanks.

**Comment by CoHealer** [comment]
Thanks Jonathan

**Comment by JonathanFingold** [comment]
@CeciAc , @tfukumori , I've added a fix to a pull request 1965, which should get merged next week. The text reads:

> This procedure uses a ZIP file to deploy your bot. In C#, this may fail if the solution configuration at build is set to **Debug**. In Visual Studio, make sure that the solution configuration is set to **Release** and perform a clean rebuild of the solution before continuing.

Please reopen with a comment if this does not address the issue.
