### ISSUE TITLE
Question about enhanced authentication

### ISSUE THREAD

**Issue by xieofxie** [MicrosoftDocs/bot-docs#1496]
&gt; This means the user ID (Activity.From.Id) on messages from Direct Line to your bot will always be the same as the one you initialized the Web Chat with.

Does it mean one can't use another user id after a channel secret is initialized with a user id or one can't use another secret for a use id after it is used in a channel secret?

It looks like the first case but one could still acquire a new channel secret for a previous user id. Thanks~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd0bdf8-7cb8-1f26-65a1-3876ea84351f
* Version Independent ID: bda6ce3a-f006-baaf-db50-82bd79afa6ab
* Content: [Authentication - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-authentication.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by EricDahlvang** [comment]
Hi @xieofxie 

When a User.Id is provided while exchanging a secret for a token, that User.Id is embedded in the token.  DirectLine will ensure the messages sent to the bot have that id as the activity's From.Id.  If a client sends a message to DirectLine having a different From.Id, it will be changed to the Id in the token before forwarding the message to the bot.  

This is correct: 

> one can't use another user id after a channel secret is initialized with a user id

**Comment by xieofxie** [comment]
Oh, thanks!
