### ISSUE TITLE
Analytics link is broken (404)

### ISSUE THREAD

**Issue by sebastianzolg** [MicrosoftDocs/bot-docs#1498]
The Analytics link [https://aka.ms/bfs-analytics](https://aka.ms/bfs-analytics) above is broken and goes 404. 

I think it should point to [https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a178d6a6-8037-940c-e8fb-aad548203b92
* Version Independent ID: 181758cf-3495-6848-5808-9dc8234140ab
* Content: [Overview of the Virtual Assistant Template - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-virtual-assistant-template?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/bot-builder-virtual-assistant-template.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-virtual-assistant-template.md)
* Service: **bot-service**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by darrenj** [comment]
Hi @Kamran<mailto:Kamran.Iqbal@microsoft.com> – looks like you own https://aka.ms/bfs-analytics? Can you repoint to this URI please? https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.github.io%2Fbotframework-solutions%2Fsolution-accelerators%2Ftutorials%2Fview-analytics%2F1-intro%2F&data=02%7C01%7Cdarrenj%40microsoft.com%7C9c3ee75b7e964562911608d7940c018b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637140651597768665&sdata=Ta6oZ28LEZgeCxGSiA2kll1DSextQSHdqpyZWQoIPuw%3D&reserved=0>
@Ryan<mailto:Ryan.Lengel@microsoft.com> FYI.

**Comment by darrenj** [comment]
Done. Also added you as the owner.

From: Darren Jefford <darrenj@microsoft.com>
Sent: Wednesday, January 8, 2020 4:02 AM
To: MicrosoftDocs/bot-docs <reply@reply.github.com>; MicrosoftDocs/bot-docs <bot-docs@noreply.github.com>; Kamran Iqbal <Kamran.Iqbal@microsoft.com>; Ryan Lengel Isgrig <Ryan.Lengel@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/bot-docs] Analytics link is broken (404) (#1498)


Hi @Kamran<mailto:Kamran.Iqbal@microsoft.com> – looks like you own https://aka.ms/bfs-analytics? Can you repoint to this URI please? https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.github.io%2Fbotframework-solutions%2Fsolution-accelerators%2Ftutorials%2Fview-analytics%2F1-intro%2F&data=04%7C01%7CKamran.Iqbal%40microsoft.com%7Cc15dce8977e048cc75bd08d79432853e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637140817059803074%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=GEc%2B%2FZym%2BNv6Jb9HkezkUJVCpFjKftla2eUm7bi40BA%3D&reserved=0>
@Ryan<mailto:Ryan.Lengel@microsoft.com> FYI.

**Comment by JonathanFingold** [comment]
Link is fixed now. Thanks.
