### ISSUE TITLE
Missing example for Enhanced authentication options 

### ISSUE THREAD

**Issue by martinlarosa** [MicrosoftDocs/bot-docs#1499]
There's no explanation on how to use Enhanced authentication optioons. I want to know how to make sure that the bot is only being contacted from a certain website. I think I've done it right but Direct Line still allows me to chat even when the bot is not talking from the site that I put in the portal as a trusted origin. An example would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71081bf9-a44f-7f24-040a-fcc6bc6dca02
* Version Independent ID: d5f6d9e6-9522-5915-0bbe-28b9b7f4725f
* Content: [Connect a bot to Direct Line - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directline?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-directline.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directline.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@martinlarosa Martin if you are still having problems did you look at what @v-kydela said? I am repeating it below:
- Did you add the trusted origins in your Direct Line channel configuration in the Azure portal?
- Did you provide the trusted origins to your call to the Direct Line tokens endpoint according to these instructions?
- Do you see your trusted origins when you view the decoded token?

**Comment by martinlarosa** [comment]
Hi! It was solved in this one: https://github.com/microsoft/BotFramework-Services/issues/160
Apparently for now, this only works if you are trying to log the user in. I wanted to use it regardless of loging the user in or not. 
I belive the documentation should at least state that to avoid wasted time.

Thanks for reaching back to me.

**Comment by mmiele** [comment]
@martinlarosa You are welcome trying to do our job. 
Would you mind to put together a couple of sentences and tell me the correct spot in the article where I can add a note? Thanks

**Comment by mmiele** [comment]
Added requested information.
