### ISSUE TITLE
Difference between channel available in the Azure Bot Service and Facebook adapter

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/bot-docs#1504]
This page shows two ways to connect a bot to Facebook but does not explain the difference between the two. Please elaborate a bit on when should one method be used or another.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0199d414-87e1-e32d-b528-ee9d2e03c54e
* Version Independent ID: f88f4b08-0977-baee-5226-844695828b95
* Content: [Connect a bot to Facebook Messenger - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0#connect-a-bot-to-facebook-using-the-facebook-adapter)
* Content Source: [articles/bot-service-channel-connect-facebook.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-facebook.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Partial explanation added in PR. @turbozapekanka - Please let us know if more clarification is required.

**Comment by turbozapekanka** [comment]
Where do I see it?

**Comment by JonathanFingold** [comment]
Here's the updated note at the top of the **Connect a bot to Facebook using the Facebook adapter** section:

> [!NOTE]
> On December 16, 2019, Workplace by Facebook changed its security model for custom integrations. Prior integrations built using Microsoft Bot Framework v4 need to be updated to use the Bot Framework Facebook adapters prior to February 28, 2020.
>
> Facebook will consider only integrations with limited access to Workplace data (low sensitivity permissions) eligible for continued use until December 31, 2020 if such integrations have completed and passed Security RFI and if the developer reaches out before January 15, 2020 via [Direct Support](https://my.workplace.com/work/admin/direct_support) to request continued use of the app.
>
> The instructions below cover the C# implementation of the Facebook adapter. For instructions on using the JS adapter, part of the BotKit libraries, [see the BotKit Facebook documentation](https://botkit.ai/docs/v4/platforms/facebook.html).

**Comment by turbozapekanka** [comment]
This says about Facebook Workplace which is confusing. We do not use Workplace and only interact with facebook users via page messages. Will Facebook channel continue to work in this scenario or I have to update integration to use the Facebook adapter?

**Comment by JonathanFingold** [comment]
My understanding is that Messenger will work with either the Facebook channel or the Facebook adapter, but that Workplace will now work with just the Facebook adapter.
