### ISSUE TITLE
Several pages in this section still refer to the Bot Framework Portal

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1505]
Shouldn't we be referring people to Azure instead of dev.botframework.com?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43810dc2-1b1b-b807-4950-6402abeae0bb
* Version Independent ID: fbf7feaf-0d94-4e20-93af-4e0e55325bcd
* Content: [Key concepts in the Bot Framework Direct Line API 3.0 - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-concepts?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-concepts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-concepts.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out @v-kydela, I'll take a look through the section and see where the links need updating.

**Comment by emgrol** [comment]
Closing this now that the mentions and links updates are [live](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-concepts?view=azure-bot-service-4.0#authentication).
