### ISSUE TITLE
Please add documentation how to deploy bot to IIS

### ISSUE THREAD

**Issue by OliverZ** [MicrosoftDocs/bot-docs#1509]
Please add documentation how to deploy the bot to IIS and create the required https-certificate for the chatbot and all other stuff if required to run the bot locally via IIS

[Tutorial: Create and deploy a basic bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@OliverZ Oliver is there a particular reason why you want to use IIS?  Azure account is free can serve users daily within the free quota. 
Maybe this can help:  https://stackoverflow.com/questions/40482022/can-we-deploy-microsoft-bot-application-in-iis-for-hosting-without-azure

**Comment by OliverZ** [comment]
I want to host the bot in a local network due to corporate network restrictions.

How can I deploy the bot to be able to use LUIS while the bot is hosted in IIS and not available public? 

I found this solution but it would require a public hostname for the certificate: https://stackoverflow.com/a/40889296

**Comment by mmiele** [comment]
Would it be possible to use Azure for the public hostname and then for the **Messaging endpoint** you would use your IIS address?  Give it a try let me know if it works.

**Comment by OliverZ** [comment]
I don't know how this should be done.

Is there a free Azure Dev Certificate available?

I found the code snippet below from "Load Certificate in Windows Apps" at: https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code#load-certificate-in-windows-apps 

Where should this code be inserted inside the bots code?

	using System;
	using System.Security.Cryptography.X509Certificates;

	...
	X509Store certStore = new X509Store(StoreName.My, StoreLocation.CurrentUser);
	certStore.Open(OpenFlags.ReadOnly);
	X509Certificate2Collection certCollection = certStore.Certificates.Find(
	                            X509FindType.FindByThumbprint,
	                            // Replace below with your certificate's thumbprint
	                            "E661583E8FABEF4C0BEF694CBC41C28FB81CD870",
	                            false);
	// Get the first cert with the thumbprint
	if (certCollection.Count > 0)
	{
	    X509Certificate2 cert = certCollection[0];
	    // Use certificate
	    Console.WriteLine(cert.FriendlyName);
	}
	certStore.Close();
	...

**Comment by mmiele** [comment]
@OliverZ I recommend to direct your questions to one of the resources you can find here: [Bot Framework additional resources](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-links-help?view=azure-bot-service-4.0). In particular to https://stackoverflow.com/questions/tagged/botframework. 
Hopefully, you can fidn the annswer you are loooking for.
