### ISSUE TITLE
Please mention Skype deprecation

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1510]
The Skype channel configuration contains the following message:

> As of October 31, 2019 the Skype channel no longer accepts new Bot publishing requests. This means that you can continue to develop bots using the Skype channel, but your bot will be limited to 100 users. You will not be able to publish your bot to a larger audience. Current Skype bots will continue to run uninterrupted. [Learn more](https://support.skype.com/en/faq/fa12091/why-are-some-features-not-available-in-skype-anymore)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 486e6e6d-a7aa-2876-dfec-edc9d8a0d1ef
* Version Independent ID: aa6e5bfa-bbda-39ad-559e-62c92cbf5f86
* Content: [Connect a bot to Skype - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-skype?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-skype.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-skype.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Closing this now that the [note is live](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-skype?view=azure-bot-service-4.0).
