### ISSUE TITLE
Update to 4.7 references + Python

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/bot-docs#1517]
This article needs to be updated to note the 4.7 release and GA for Python

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9ad2ff5-0669-6023-d1ae-8fb47c08ffac
* Version Independent ID: 6d2f8ae5-dd96-f969-5df8-b6577d1dfcb4
* Content: [What's new - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/what-is-new?view=azure-bot-service-4.0)
* Content Source: [articles/what-is-new.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/what-is-new.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@clearab - the note is in the article. It says, "Python SDK (GA) - We are pleased to announce the general availability of the Python SDK. The SDK supports core bot runtime, connectors, middleware, dialogs, prompts, Language Understanding (LUIS), and QnA Maker."

Is there anything else you are looking for?

**Comment by clearab** [comment]
Huh, that's odd. The GitHub view of this page is different than the published live page? The live page looks correct, not sure what's up with the difference.

![image](https://user-images.githubusercontent.com/1139814/72845170-e4b0d380-3c52-11ea-8fb0-fd794ed3ba75.png)

**Comment by clearab** [comment]
Ah, live-sync-work is the actual live branch?
