### ISSUE TITLE
Teams libraries not listed in SDK resources

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/bot-docs#1519]
In the reference documentation for both the JavaScript and .NET SDKs the Microsoft.Bot.Builder.Teams and Microsoft.Bot.Schema.Teams namespaces are not listed/documented.

**Comment by mmiele** [comment]
@clearab A couple of questions:
1. Do the comments exist in the related code and the only thing we miss are the namespaces in the onboarding request for the ref docs generation?
1. Do the .NET and JS namespaces have the same names?

**Comment by mmiele** [comment]
Current status.
The current reference documentation contain the Teams classes, please see:
- (.NET) https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Bot.Builder.Teams?branch=smoke-test&view=botbuilder-dotnet-stable
- (JS) https://review.docs.microsoft.com/en-us/javascript/api/botbuilder/8.0-preview.97252.teamsactivityhandler?view=botbuilder-ts-latest&branch=master

While the JS version contains some documentation (code comments), the .NET does not contains any.
Priorities must be defined to when the reference documentation (code comments) must be added.

**Comment by JonathanFingold** [comment]
@clearab Here's a quick overview of the process:
1. Packages are built and released (NuGet, npm, PyPi, etc.). These contain the doc comments embedded within them.
1. Doc team opens a request with the publishing team to build the ref docs based on a list of packages from which to build the docs.
1. Publishing team builds the ref docs and posts them to their review site.
   - If for some reason the docs can't be built, they notify the doc team, and we try to get that sorted out and an new set of packages published.
1. Once the docs team signs off on the build, the publishing team pushes it live. (Until then, the live docs site will continue to show content from the previous release.)

**Comment by JonathanFingold** [comment]
For example, here is the review link for the C# [Microsoft.Bot.Builder.Teams namespace](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.teams?view=botbuilder-dotnet-stable&branch=smoke-test).

**Comment by JonathanFingold** [comment]
And here is the review link for all of the [JS library](https://review.docs.microsoft.com/en-us/javascript/api/botbuilder/?view=botbuilder-ts-latest&branch=master).

**Comment by mmiele** [comment]
This is what Kamran said: 
API comments is one of the things Scott and I have talked about doing in R10 IIRC.

**Comment by JonathanFingold** [comment]
The 4.7 ref docs have now been pushed live for all three languages:
- [C#](https://docs.microsoft.com/en-us/dotnet/api/?view=botbuilder-dotnet-stable)
- [JavaScript](https://docs.microsoft.com/en-us/dotnet/api/?view=botbuilder-dotnet-stable)--you need to drill into the modules to find the Teams classes.
- [Python](https://docs.microsoft.com/en-us/python/api/botbuilder-core/botbuilder.core.teams?view=botbuilder-py-latest)--there are some other issues here that we're trying to sort out separately.
