### ISSUE TITLE
Additional Information code has typo

### ISSUE THREAD

**Issue by morgdalaine** [MicrosoftDocs/bot-docs#1520]
should be UseNamedPipe**s**

```cs
// Allow bot to use named pipes.
app.UseNamedPiped();
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72c259-a864-9e1c-b585-562d6bca80ff
* Version Independent ID: 30a3fce8-d236-5c7b-88a0-003c971f2819
* Content: [.NET bot with direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0#additional-information)
* Content Source: [articles/bot-service-channel-directline-extension-net-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
A fix is in [PR 1948](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1948) and should go live shortly after the PR is merged. Thanks.

**Comment by JonathanFingold** [comment]
PR should get merged soon and the live site updated within a day or so.
