### ISSUE TITLE
Slack referenced in several places

### ISSUE THREAD

**Issue by AngryVirginian** [MicrosoftDocs/bot-docs#1522]
Reference to Slack - "The instructions below cover the C# implementation of the Slack adapter" and "services.AddSingleton&lt;SlackAdapter, WebexAdapterWithErrorHandler&gt;();" - are present in the article.  Looks like they were unintended. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e61be5-e537-8678-f907-10f27ea7bf90
* Version Independent ID: e2a9d88e-0819-9de5-d6f8-48bf7b270685
* Content: [Connect a bot to Webex Teams - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-adapter-connect-webex?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-adapter-connect-webex.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-adapter-connect-webex.md)
* Service: **bot-service**
* GitHub Login: @garypretty
* Microsoft Alias: **gapretty**

**Comment by JonathanFingold** [comment]
Looks like a copy-paste error. Thanks.

**Comment by JonathanFingold** [comment]
Fix is in bot-docs-pr PR 1951. Update should go live in a day or to.
