### ISSUE TITLE
Update 'Select the Supported account types for your application. (Any of these options will work with this sample.)' part

### ISSUE THREAD

**Issue by xieofxie** [MicrosoftDocs/bot-docs#1523]
According to this [issue](https://github.com/microsoft/botframework-solutions/issues/2887#issuecomment-576238396), any will work is not always the case. Please investigate these options and update the document.
Thanks~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43340ba9-4fc5-1202-e2c1-f901f33dc7c7
* Version Independent ID: 236be49b-6c2e-5353-de90-720fd7690a1c
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0&tabs=aadv1#register-an-application-in-azure-ad)
* Content Source: [articles/bot-builder-tutorial-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tutorial-authentication.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@xieofxie Please, let me know what you found.

**Comment by xieofxie** [comment]
@mmiele A further reading suggests that it should be updated here https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-3.0&tabs=csharp#use-bot-credentials perhaps?

Here is what happens: when app's supported account is set to single tenant, if one uses personal subscription instead of MS account, the emulator would report `The bot's Microsoft App ID or Microsoft App Password is incorrect.`. 

In this case,  supported account types should be changed to Multitenant.

**Comment by mmiele** [comment]
See PR: https://github.com/MicrosoftDocs/bot-docs-pr/pull/1954

**Comment by mmiele** [comment]
Resolved. Fixed documentation.
