### ISSUE TITLE
The most links redirects me to the home page

### ISSUE THREAD

**Issue by HeinPauwelyn** [MicrosoftDocs/bot-docs#1524]
On this page https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-rich-cards?view=azure-bot-service-3.0 at the sections _"Types of rich cards"_ and _"Additional resources"_, only links _"Adaptive Card"_, _"Channels reference"_ and _"How to send attachments"_ works the rest of the links redirects me to [the home page](https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed5a1c8d-c61b-4130-1ecb-e25d7b8cc4ad
* Version Independent ID: ba796614-7173-b45f-f9eb-6a3c3fe55b09
* Content: [Add rich card attachments to messages (v3 JS) - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-rich-cards?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/nodejs/bot-builder-nodejs-send-rich-cards.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-send-rich-cards.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Thanks for reporting. I'll track down the correct links and update the page.

**Comment by JonathanFingold** [comment]
Fix is in PR and changes should make it live in a day or two.
