### ISSUE TITLE
POST /v3/conversations results in 403 BotNotInConversationRoster error

### ISSUE THREAD

**Issue by andreaswittig** [MicrosoftDocs/bot-docs#1527]
**Describe the bug**

My chatbot needs to start a new conversation/reply chain in a public Microsoft Teams channel by using the Bot Framework REST API.

When I try to do so  by sending a POST request to /v3/conversations the API returns a 403 with code `BotNotInConversationRoster`.

`{"error":{"code":"BotNotInConversationRoster","message":"The bot is not part of the conversation roster."}}

As far as I understand all users and bots of a team are by default part of any public Microsoft Teams channel. Therefore, I do not understand the error message. Unfortunately, I could also not find any hints in the documentation.
`
**To Reproduce**

The following POST via curl can be used to reproduce the issue.

```
curl -X POST -H "Authorization: Bearer XXX" -H "Content-Type: application/json" https://smba.trafficmanager.net/de/v3/conversations -d '{"activity":{"text":"Test","type":"message"},"channelData":{"channel": {"id": "19:62fb45ddd8b2447082e5d1694ce8d735@thread.skype"}}}
```

Make sure to fill in an access token as well as a valid channel ID.

**Expected behavior**

I'm expecting a 2XX and a message posted to the public Microsoft Teams channel.

**Screenshots**
n/a

**Additional context**

My chatbot asks for the `personal`, `team`, and `groupchat` scope and is installed as a custom application within my Microsoft Teams team. The chatbot uses the following `manifest.json`.

```
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
    "manifestVersion": "1.5",
    "version": "1.0.0",
    "id": "2726f46d-b5df-445e-a0f0-efaa23c37edd",
    "packageName": "io.marbot.teams",
    "developer": {
        "name": "marbot",
        "websiteUrl": "https://marbot.io",
        "privacyUrl": "https://marbot.io/privacy-policy.html",
        "termsOfUseUrl": "https://marbot.io/imprint.html"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "marbot-dev",
        "full": "marbot (Development)"
    },
    "description": {
        "short": "Incident Management for AWS",
        "full": "..."
    },
    "accentColor": "#3E11F2",
    "bots": [
        {
            "botId": "cd4aa3e7-99e5-4125-8d25-cc147f643c4a",
            "scopes": [
                "personal",
                "team",
                "groupchat"
            ],
            "commandLists": [
                {
                    "scopes": [
                        "personal"
                    ],
                    "commands": [
                        {
                            "title": "help",
                            "description": "..."
                        }
                    ]
                },
                {
                    "scopes": [
                        "team"
                    ],
                    "commands": [
                        {
                            "title": "help",
                            "description": "..."
                        }
                    ]
                },
                {
                    "scopes": [
                        "groupchat"
                    ],
                    "commands": [
                        {
                            "title": "help",
                            "description": "..."
                        }
                    ]
                }
            ],
            "supportsFiles": false,
            "isNotificationOnly": false
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "marbot.io"
    ]
}
```

**Comment by clearab** [comment]
Hello - Unfortunately bots are not automatically added to teams. Before your bot can send a message to a particular channel or group chat it needs to be installed there. This is because consent is given at install time for the bot to have access to a particular scoped context. For an individual (personal) conversation the conversation needs to be created between the bot and your user before you can post messages to it.

It is possible to use the Graph APIs to proactively install your bot see: 
- For 1:1 conversations: https://docs.microsoft.com/en-us/graph/teams-proactive-messaging
- For channels: https://docs.microsoft.com/en-us/graph/api/teamsappinstallation-add?view=graph-rest-beta&tabs=http

You may also find the documentation on proactive messaging specific to the Teams channel useful:
- https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet

**Comment by andreaswittig** [comment]
Thanks for the explanations and your help. I had installed the bot and invited it to the channel.

Fixed the issue by recreating the app/bot with App Studio. After that, I was able to start a conversation.
