### ISSUE TITLE
Bot Doc Incorrectly States Bot Service Manages Token Refresh

### ISSUE THREAD

**Issue by CoHealer** [MicrosoftDocs/bot-docs#1528]
**Describe the bug**
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-authentication?view=azure-bot-service-4.0#about-the-bot-framework-token-service states:

“Managing the token life-cycle, **_including trying to refresh tokens_**.” 

The bot service does not actually refresh tokens. The bot itself is responsible for the following logic when a token is expired: 
-	Log out the user (call adapter.SignOutUser)
-	Perform the Sign In flow again

**To Reproduce**
1. Create a bot (e.g. teams channel)
2. Log in successfully 
3. Let conversation sit stale until the token expires 
4. Go back into the conversation after the token expiration 
 
**Expected behavior**
Per the current documentation, the service should “Managing the token life-cycle, **_including trying to refresh tokens_**.”

**Actual behavior**
Triggering the login always returns the same expired token; not refreshed

**Additional context**
https://icm.ad.msft.net/imp/v3/incidents/details/169293013/home

**Comment by mmiele** [comment]
See PR https://github.com/MicrosoftDocs/bot-docs-pr/pull/1955

**Comment by mmiele** [comment]
Resolved. Fixed documentation.
