### ISSUE TITLE
Westeurope redirection to Dispatch luis app

### ISSUE THREAD

**Issue by BillLeBoquet** [MicrosoftDocs/bot-docs#1529]
When you create a Dispatch luis application hosted in westeurope (eu.luis.ai), clicking in "View in LUIS portal" from Summary.html try to open your application in westus, you end up with a 400 error in the console and an infinite Loading page. You should be redirected thanks to the region specified in your dispatch file.

**Comment by mdrichardson** [comment]
@BillLeBoquet [I've opened this in the CLI repo](https://github.com/microsoft/botframework-cli/issues/490) and will close it here, for better tracking.

I'll start looking into this.
