### ISSUE TITLE
Format issue in the Add knowledge base information to your bot section

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/bot-docs#1531]
There is appears to be a formatting issue where the text renders as "| QnAKnowledgebaseId | The knowledge base ID that the QnA Maker portal generated for you. | | QnAAuthKey (QnAEndpointKey in Python) | The endpoint key that the QnA Maker portal generated for you. | | QnAEndpointHostName | The host URL that the QnA Maker portal generated. Use the complete URL, starting with https:// and ending with /qnamaker. The full URL string will look like "look like "https://&lt; &gt;.azure.net/qnamaker". |" within the "Add knowledge base information to your bot" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=javascript#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Fixed in PR. Update should go live in a day or two. Thanks for reporting.

**Comment by nuno1000** [comment]
i'm having an issue exactly in this section..
i followed the instructions to add the knowledge base information in the .env file, but when i tested the bot locally it gives me this error: 
"[onTurnError] unhandled error: TypeError: Cannot read property 'endsWith' of undefined"

also, if i comment this part in the code and just send an echo message (for example) it works well..

this are an example of the parameters i'm using:
QnAKnowledgebaseId:"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
QnAAuthKey:"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
QnAEndpointHostName:"https://xxxxxx.azurewebsites.net/qnamaker"

i'm wondering if this could be an issue in the KB data format

**Comment by nuno1000** [comment]
well, the issue was solved, probably it was a word mistype.. nothing to do with KB data format
