### ISSUE TITLE
Docs link in skills section

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/bot-docs#1532]
The Docs link in the Skills section seems to be pointing at this page. I think it is supposed to point here: https://docs.microsoft.com/en-us/azure/bot-service/skills-conceptual?view=azure-bot-service-4.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9ad2ff5-0669-6023-d1ae-8fb47c08ffac
* Version Independent ID: 6d2f8ae5-dd96-f969-5df8-b6577d1dfcb4
* Content: [What's new - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/what-is-new?view=azure-bot-service-4.0)
* Content Source: [articles/what-is-new.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/what-is-new.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
I updated the AKA link so it points to the About skills page. Closing this issue now that the link has been update.
