### ISSUE TITLE
Direct Line App Service Extension Live Does Not Match This Repo

### ISSUE THREAD

**Issue by mdrichardson** [MicrosoftDocs/bot-docs#1533]
[.NET bot with direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0#update-net-bot-to-use-direct-line-app-service-extension) does not match [articles/bot-service-channel-directline-extension-net-bot.md from this repo](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)

The real issue is that on the live site, the [Additional Information section](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0#additional-information) is incorrect and should be removed, entirely.

I would've submit a PR, but the mismatch makes it difficult to do so.

See [this ICM](https://icm.ad.msft.net/imp/v3/incidents/details/171486889/home) for details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72c259-a864-9e1c-b585-562d6bca80ff
* Version Independent ID: 30a3fce8-d236-5c7b-88a0-003c971f2819
* Content: [.NET bot with direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0#update-net-bot-to-use-direct-line-app-service-extension)
* Content Source: [articles/bot-service-channel-directline-extension-net-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Deleted "Additional information" section.

**Comment by mmiele** [comment]
@mdrichardson I deleted the section "Additional information". Please. take a look at the staged site and confirm that the problem has been fixed. Thanks
https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-3.0&branch=pr-en-us-1964

**Comment by mdrichardson** [comment]
@mmiele LGTM for now, at least. DL Extension is pretty new and changing a lot so don't be surprised if this needs another update soon. But for now, I'd say it's accurate.
