### ISSUE TITLE
404 Error on all Sample list links

### ISSUE THREAD

**Issue by mkulgeorge** [MicrosoftDocs/bot-docs#1537]
Hi Team,

I am getting 404 Error on all the Sample list links. Please check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8fcc136-2176-535a-05f4-6423bfafbd67
* Version Independent ID: e0636491-0acf-5577-0313-80d3c9006131
* Content: [Web Chat overview - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-webchat-overview?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-webchat-overview.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-webchat-overview.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@mkulgeorge Apologies for the inconvenience and thank you for flagging this issue. We'll fix the problem.

**Comment by mmiele** [comment]
The corrected documentation will be ready in the next build.

**Comment by mmiele** [comment]
Fixed documentation in the next available build.
