### ISSUE TITLE
Python Echo Template link is not valid

### ISSUE THREAD

**Issue by thediveshsoni** [MicrosoftDocs/bot-docs#1538]
https://github.com/microsoft/botbuilder-python/releases/download/Templates/echo.zip

**Comment by emgrol** [comment]
HI @thediveshsoni, can you elaborate on what you mean by not valid? I just tested the link and was able to successfully download the template and use it to create an echo bot.

**Comment by emgrol** [comment]
Closing since the link and template are functional.
