### ISSUE TITLE
Deployment steps are ambiguous/confusing

### ISSUE THREAD

**Issue by modnarb** [MicrosoftDocs/bot-docs#1546]
The instructions under step 4 "Deploy via ARM template" are confusing, at some points unclear in what is needed. For example, I was following the steps under "Option 2: New App Service Plan" and the command line expects several parameters that I wasn't sure what to use. Some I found are provided in the output from the step before, but the names don't correlate; In the previous step I'm making a password, which is also called 'client secret', but then in the next step I'm supposed to provide an app secret. Some things do correlate in between steps, like "appId", so that compounds the confusion when the same name doesn't carry over. Also, it is unclear which parameters I'm supposed to provide and which ones I'm creating, like "botId". I found answers to these looking in the "closed issues" but until I discovered that, the provided instructions were very confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp&source=docs#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@modnarb The updated version of the article **Deploy your bot - Bot Service - Bot Service** will be in the next available doc build. I'll let you know. Thank you for your feedback.

**Comment by amankhandelwal-ideaspark** [comment]
@mmiele when is the next doc build likely to go live? I need more information regarding deployment of python bots. The documentation has very limited information for it.
