### ISSUE TITLE
app.UseBotFrameworkNamedPipe() doesn't exist in Builder SDK 4.7.2

### ISSUE THREAD

**Issue by mahamr** [MicrosoftDocs/bot-docs#1547]
Hello, I'm going through these instructions to try it out. In an EchoBot template that has been updated to Bot.Builder 4.7.2, there is no app.UseBotFrameworkNamedPipe() method. There is an app.UseNamedPipes() however. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72c259-a864-9e1c-b585-562d6bca80ff
* Version Independent ID: 30a3fce8-d236-5c7b-88a0-003c971f2819
* Content: [.NET bot with direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0#confirm-direct-line-app-extension-and-the-bot-are-initialized)
* Content Source: [articles/bot-service-channel-directline-extension-net-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mahamr** [comment]
when I use app.UseNamedPipes(), the ASE does work as expected. I believe UseBotFrameworkNamePipe() was the old one before it was rolled into the BotBuilder SDK?

**Comment by mmiele** [comment]
Fixed documentation is in the next available build.
