### ISSUE TITLE
Please verify azure search is up, restart the WebApp and try again

### ISSUE THREAD

**Issue by msdpalam** [MicrosoftDocs/bot-docs#1550]
After provisioning a QnA Maker service (that automatically creates the search service), when I try Create knowledge base, I get the error - "Please verify azure search is up, restart the WebApp and try again", while search service status shows "running", the restart of the web app for the QnA maker doesn't help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 122e1e45-a823-4acd-c082-60041e9e3584
* Version Independent ID: e2dd9c08-1951-b3b9-9f67-a3d948b26732
* Content: [Activities overview - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-activities?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/dotnet/bot-builder-dotnet-activities.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-activities.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by eduardpaul** [comment]
Hi all! We are having the same problem in production right now. Any steps to get diagnostic information?

**Comment by abhi23arora** [comment]
Hi.. did anybody solve this issue?

**Comment by StevieBleeds** [comment]
I've been receiving this error as of this morning and have changed absolutely nothing.

**Comment by zxyanliu** [comment]
Hi @msdpalam, it seems that [this](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-activities?view=azure-bot-service-3.0) is not the article you followed for the reported issue. I was wondering which article did you follow? Please let us know so that we can help. Thanks!

**Comment by eduardpaul** [comment]
After this issue and its evolution, I would not suggest using Microsoft QnA in business-critical applications. :(

**Comment by dmvtech** [comment]
For issues with the QnA Service or portal, please create a UserVoice issue through the qnamaker.ai portal. This documents repro is for issues with the documentation itself.

![image](https://user-images.githubusercontent.com/43397658/92292228-f2108a80-eed0-11ea-883a-3d63e43631b7.png)

**Comment by Hiran-Battina** [comment]
In case this issue occurs again, "Qnamaker build failed: Please verify azure search service is up, restart the WebApp and try again." Restarting the qna maker related app service and publishing the KB manually helped. 
The issue got resolved after these two steps.
