### ISSUE TITLE
Instructions have changed

### ISSUE THREAD

**Issue by jwiley84** [MicrosoftDocs/bot-docs#1554]
Slack has altered how to add bots to their workspaces. I'll update this with the new steps as soon as I successfully add a bot to slack.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs#feedback)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by jwiley84** [comment]
https://github.com/microsoft/BotFramework-Services/issues/179

**Comment by CoHealer** [comment]
@jwiley84 , is there an ETA on getting the steps updated?

**Comment by jwiley84** [comment]
Slack has changed a bit of their configuration, and the following changes need to be made to the instructions on connecting a bot to Slack:

The instructions up to (but not including) the line 'Create a Slack Bot User' are correct and can be followed as is.

The section headed 'Create a Slack Bot User' is outdated. This option is no longer there on the Api.Slack.com page, and that section can be removed. Instead, the following steps are taken to add a bot token:

1. Select the **OAuth & Permissions** tab.
2. Scroll down to **Scopes**.
3. In the **Bot Token Scopes** section, click **Add an OAuth Scope**
4. Add the following scopes:
- app_mentions:read
- channels:history
- channels:read
- chat:write
- groups:history
- groups:read
- im:history
- mpim:history 

![image](https://user-images.githubusercontent.com/17333688/75068367-e533c880-54a3-11ea-8daa-e0c382ccc1ab.png)


5. Select the **App  Home** tab.
6. Toggle **Always Show My Bot as Online**.

![image](https://user-images.githubusercontent.com/17333688/75068276-bc133800-54a3-11ea-8325-b138832d39fb.png)


Everything after that is correct.

**Comment by mmiele** [comment]
@jwiley84 Jessica, I just started looking into this. So far I have created my Slack account. I'll keep you posted on the progress and doc update. Thanks

**Comment by mmiele** [comment]
@jwiley84 Jessica, if I understand correctly the 'Create a Slack Bot User' is obsolete and must be deleted.
Should I replace it with the instructions you described in your comment above? 
If so, what is the best heading for this section? 
Thanks

**Comment by jwiley84** [comment]
Good morning! I just reread my post, and yeah, I could have made that more clear. Sorry.

You can remove the 'Create a Slack Bot User' section and replace it with my instructions. A good heading might be : 'Add Bot Token Scopes'.

**Comment by mmiele** [comment]
Jessica, thank you for your answer. 
The updated documentation will be in the next published build.

**Comment by mmiele** [comment]
Changed merged in the doc master branch. 
he updated documentation will be in the next published build.
