### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by vp393001** [MicrosoftDocs/bot-docs#1556]
In the Microsoft App ID and password row, please modify "egistration" to "registration"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e8c5d2-bf2d-fc99-e813-bf9dd49eb9bb
* Version Independent ID: 830e4542-cdd8-3b64-f1df-2acae1ca3a88
* Content: [Create a bot with Azure Bot Service - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/abs-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/abs-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/abs-quickstart.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for catching this typo @vp39300.

**Comment by emgrol** [comment]
Thanks for catching this typo @vp393001.

**Comment by emgrol** [comment]
Closing now that typo fix is live.
