### ISSUE TITLE
Severe lack of information on how to properly setup dialogs in a realistic manner.

### ISSUE THREAD

**Issue by scch1002** [MicrosoftDocs/bot-docs#1557]
**Describe the bug**
There is a severe lack of information on how to properly setup a bot using dialogs in realistic manner. There does not seem to be any information on how to properly nest dialogs to allow for multiple turns in the conversation.

**Comment by JonathanFingold** [comment]
@scch1002 The four dialog-centric how-to articles are:
1. [Implement sequential conversation flow](https://docs.microsoft.com/azure/bot-service/bot-builder-dialog-manage-conversation-flow)
1. [Reuse dialogs](https://docs.microsoft.com/azure/bot-service/bot-builder-compositcontrol)
1. [Create advanced conversation flow using branches and loops](https://docs.microsoft.com/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow)
1. [Handle user interruptions](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-handle-user-interrupt)

Articles 2 and 3 probably have the information you're looking for. Let me know if you have more specific questions.
