### ISSUE TITLE
Not able to initialize bot conversation using Xamarin Forms DirectLine Client with Typescript based Bot.

### ISSUE THREAD

**Issue by Edwardfelix08** [MicrosoftDocs/bot-docs#1558]
We are having a Typescript bot deployed and it is having DirectLine channel enabled.
We are trying to access the DirectLine channel via a Xamarin Forms app. 

**To Reproduce**
Deploy a Typescript VA. and try to connect to the VA using Xamarin Forms app via the DirectLine channel, the welcome message is not been displayed.

Packages used in Xamarin.
Microsoft.Bot.Connector.DirectLine - 3.0.2
Xamarin.Forms - 4.3.0.908675
Microsoft.Rest.ClientRuntime - 2.3.21

**Expected behavior**
Displays the welcome message in the app.

**Exception :- **
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'MethodNotAllowed'

Thanks,
Edward

**Comment by jwiley84** [comment]
Hi @Edwardfelix08 

Going to try to repro this. Are you following [this](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/typescript/1-intro/) for your creation and deployment? Are you using newly created, or previously created cognitive services like LUIS, and how are you implementing your Directline in the Xamarin app? Do you get this error if you test your bot in the emulator or any other channel?

**Comment by Edwardfelix08** [comment]
HI @jwiley84 
i was able to connect to the bot via the direct line now.

Thanks.
