### ISSUE TITLE
Should mention which Cognitive Service is required

### ISSUE THREAD

**Issue by Zerryth** [MicrosoftDocs/bot-docs#1559]
Small improvement recommended to this doc. It's noted in the docs that using Direct Line Speech "requires a Cognitive Service resource", but fails to mention which type of cognitive service. Should take the guess work out and just mention that it requires a SPEECH Cognitive Service resource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4cb4da-ca0e-fc7f-686c-f3510bf9af0b
* Version Independent ID: e20d2896-dcec-8e46-2f50-2227def34250
* Content: [Connect a bot to Direct Line Speech - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-directlinespeech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directlinespeech.md)
* Service: **bot-service**
* GitHub Login: @trrwilson
* Microsoft Alias: **travisw**

**Comment by geo-msft** [comment]
Thank you very much for your feedback. 

We should mention in the prerequisites or add a separate link explaining: 

Create Speech cognitive service in the Azure portal: 
1.	Search for Speech 
2.	Then press create 

![image](https://user-images.githubusercontent.com/57954688/74737896-7a458000-525e-11ea-8b5f-3a7d9c3e0ec1.png)

3.     Note down the key and endpoint values to use them later when you add the channel to the bot.

![image](https://user-images.githubusercontent.com/57954688/74737946-947f5e00-525e-11ea-8be4-f28bb3b434da.png)

**Comment by mmiele** [comment]
Changes merged in the doc master branch.
The updated documentation will be in the next published build.
