### ISSUE TITLE
There is no mention about slack commands needed to be configured before running the example 

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/bot-docs#1560]
@a2glukhov commented 8 hours ago

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by ticianaciminari** [comment]
Hi Team,

Could you please check the issue from user?

Kind regards, 
Microsoft DOCS International Team

**Comment by mmiele** [comment]
@jwiley84 This is the issue we talked about. Please, take a look when you have a chance and let me know the doc impact. Thanks

**Comment by mmiele** [comment]
@ticianaciminari Could you ask the customer to provide more details or the scenario where the issue was found? Thanks

**Comment by mmiele** [comment]
Documentation has been updated to eliminate some confusion.
