### ISSUE TITLE
How to unit test suggested actions

### ISSUE THREAD

**Issue by robertwood62** [MicrosoftDocs/bot-docs#1569]
I'm trying to test suggested actions which use the Post-back action type as they contain complex data.  How do I send post-back Object data correctly.  Could you provide a sample for how to do this?  I tried setting the Activity.Value property with the object to send back to the Bot but that didn't seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afcaa01f-5e9c-8b11-9dbe-9f9740a45397
* Version Independent ID: b24363df-987f-75c3-a8b8-eab8509aa13c
* Content: [Unit test bots - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/unit-test-bots?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/unit-test-bots.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/unit-test-bots.md)
* Service: **bot-service**
* GitHub Login: @gabog
* Microsoft Alias: **ggilaber**

**Comment by JonathanFingold** [comment]
I'm not sure I understand your scenario. The `postBack` action type is designed to send a text message to the bot when the user clicks the button. For information about card actions, see the [process events within rich cards](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-add-media-attachments#process-events-within-rich-cards) section in the how to **add media to messages** article.

That said, you might be able to add channel data to each card action. See the Activity Schema for information about [channel data](https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#channel-data).

**Comment by JonathanFingold** [comment]
Closing. Please reopen if you need more assistance.
