### ISSUE TITLE
appid and password or null?

### ISSUE THREAD

**Issue by AskYous** [MicrosoftDocs/bot-docs#1571]
On step 1, it says to edit the app settings file to make it null for nodejs, but to have the app id actually coded in for .Net. This makes me suspicious that they really meant to say to make the app ID and password into NULL, just like they said that for Nodejs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc8a0643-f219-a48f-666e-95bc9f0f351c
* Version Independent ID: 81578919-249c-b3e7-b367-183d70135890
* Content: [Troubleshooting Bot Framework Authentication - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0#step-3-enable-security-and-test-on-localhost-)
* Content Source: [articles/bot-service-troubleshoot-authentication-problems.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-troubleshoot-authentication-problems.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Good catch. Fixing in PR 2013.
