### ISSUE TITLE
Teams: What does it mean to "add bot by GUID"?

### ISSUE THREAD

**Issue by AskYous** [MicrosoftDocs/bot-docs#1572]
This page gives us instructions on how to add our bot to MS Teams. But then it warns from adding by GUID. What is that? Is that what we just did in this page? This page needs to clarify what that is if it's going to warn against it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e31fe2a-ac8e-815c-f33e-2f08fd554915
* Version Independent ID: e4b7dd0b-e9c9-00d8-41ea-f2ecbbb68752
* Content: [Connect a bot to Teams - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0)
* Content Source: [articles/channel-connect-teams.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/channel-connect-teams.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thank for bringing this to our attention @AskYous, we'll update the docs accordingly.

**Comment by emgrol** [comment]
Closing now that the changes are live.
