### ISSUE TITLE
Endpoint and Keys instructions don't match website

### ISSUE THREAD

**Issue by jbgh2** [MicrosoftDocs/bot-docs#1573]
The Manage tab in luis.ai doesn't have a 'Keys and Endpoints' entry on the left hand side.
If you have migrated to the new preview.luis.ai then you might have a custom endpoint rather than a region.

Please update the documentation to match usage of the current websites

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Add natural language understanding to your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=javascript#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing out the mismatch in information @jbgh2. The updated instructions and screenshot in [PR 2041](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2041).

**Comment by emgrol** [comment]
Closing now that the changes are live.
