### ISSUE TITLE
Broken link "Conversations"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/bot-docs#1575]
![bot-builder-telemetry-analytics-queries](https://user-images.githubusercontent.com/40815708/75409420-02610f00-595c-11ea-9023-57fd6174b380.png)

en-us:https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-analytics-queries?view=azure-bot-service-4.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdfeb662-d60b-d832-9290-c4d03233e84d
* Version Independent ID: e736a8ef-67cd-72b1-9d74-d542beeefed8
* Content: [Analyze the telemetry data from your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-analytics-queries?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-telemetry-analytics-queries.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-telemetry-analytics-queries.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
Thank you for reporting this, the AKA link was missing the last character, fixed. This link now works.
