### ISSUE TITLE
Could not open conversation

### ISSUE THREAD

**Issue by fdaiello** [MicrosoftDocs/bot-docs#1578]
I could not open the conversation using the suggested endpoint:
     endpoint = "https://&lt;YOUR_BOT_HOST&gt;.azurewebsites.net/.bot/".

In my case, endpoint was this:
    endpoint = "https://mrbot-2020.azurewebsites.net/.bot/"

Although my Bot is published and running, this URL returns a 404 error.
Then, conversation gets Null value at this line:

var tokenClient = new DirectLineClient(
    new Uri(endpoint),
    new DirectLineClientCredentials(secret));
var conversation = await tokenClient.Tokens.GenerateTokenForNewConversationAsync();

I am using same DirectLineSecret that is working on another DirectLine client ( without sreaming ) that I have working with version 3.02.

Any ideas? I am missing something?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c463a003-c709-b516-ce1b-6c45537de3b2
* Version Independent ID: 8ca42668-23ac-6dca-054d-d183b0fb5b0b
* Content: [Create .NET client for direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-directline-extension-net-client.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-client.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by joeka-N** [comment]
you have to configure the stream extension in your bot application.
check this link : 

> https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0

**Comment by fdaiello** [comment]
Hi,

Thanks for your reply.
This link explains how to implement the direct line CLIENT using stream.
But it does not explain how to configure stream extension on the BOT application.
Could you please check  and send us the paper that has this explanation? How to enable the BOT to answer using Stream?

Thanks!

**Comment by mmiele** [comment]
@fdaiello Thank you for contacting us. 
Let me look into this issue and I'll come back to you.

**Comment by joeka-N** [comment]
@fdaiello once you add the nuget package to your bot project 

> Microsoft.Bot.Builder.StreamingExtensions

you have to add the below in your startup class:

> using Microsoft.Bot.Builder.StreamingExtensions;
and app.UseBotFrameworkNamedPipe(); //in he configure method

**Comment by mmiele** [comment]
@fdaiello I was able to make this [example](https://github.com/Jeffders/DirectLineAppServiceExtensionPreview/tree/master/samples/CSharpNetCore_DirectLine_Client) work.
Make sure that you do the following:

1. On the bot side in Azure follow the steps described in this article [Update .NET Bot to use Direct Line App Service Extension](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0). 

1. On the client side, this is an [example](https://github.com/Jeffders/DirectLineAppServiceExtensionPreview/tree/master/samples/CSharpNetCore_DirectLine_Client) make sure you assign these values:

var endpoint = "https://<your bot app>.azurewebsites.net/.bot/";
var secret = "<web default key>";

You obtain the web default key following the steps described in this article: [Create .NET Client to Connect to Direct Line App Service Extension](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0).

PS
It is a good idea to regenerate the keys, on the bot and client, before using them.

Let me know if this solves your problem,

**Comment by mmiele** [comment]
Fixed documentation.

**Comment by Santhosh0505** [comment]
> @fdaiello once you add the nuget package to your bot project
> 
> > Microsoft.Bot.Builder.StreamingExtensions
> 
> you have to add the below in your startup class:
> 
> > using Microsoft.Bot.Builder.StreamingExtensions;
> > and app.UseBotFrameworkNamedPipe(); //within the Configure method

This package has been deprecated, Can you please suggest me an updated reference ?
