### ISSUE TITLE
Build on Release mode

### ISSUE THREAD

**Issue by diegoriera** [MicrosoftDocs/bot-docs#1579]
Is important to add a TIP saying to build it on Release mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for bringing this to our attention @diegoriera. Updating the article now.

**Comment by emgrol** [comment]
Closing now that the changes are live.
