### ISSUE TITLE
Python script link give a 404 error

### ISSUE THREAD

**Issue by mdhruv1** [MicrosoftDocs/bot-docs#1581]
Please have we have link fixed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a20df2-727c-1afd-2b87-836ea1ea4f7a
* Version Independent ID: 157fc262-fb1f-f12d-0890-e90119feb444
* Content: [Create a bot using Bot Framework SDK for Python - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/python/bot-builder-python-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/python/bot-builder-python-quickstart.md)
* Service: **bot-service**
* GitHub Login: @emgrol
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing out the broken link; I'll investigate where it went and update the article.

**Comment by emgrol** [comment]
The article has been updated but is not yet live. Here is the link to the updated template location: 
https://github.com/microsoft/BotBuilder-Samples/tree/master/generators/python/app/templates/echo

**Comment by emgrol** [comment]
Closing now that the updated link is live.
