### ISSUE TITLE
DirectLine.JS not working for react based applications.?

### ISSUE THREAD

**Issue by thirumaran007** [MicrosoftDocs/bot-docs#1585]
DirectLine.JS not working for react based applications. is that expected behaviour? if not could you please share directline extension sample codes for react based applications ?

**Comment by compulim** [comment]
Could you send us error logs or anything for diagnostics?

We use DLJS intensively in Web Chat and it's built using React. You can check out some of our samples here, https://microsoft.github.io/BotFramework-WebChat.

**Comment by mmiele** [comment]
@compulim  Please, let me know if there is any impact on the Bot Framewrok SDK docs.
Thank you

**Comment by mmiele** [comment]
Customer did not respond.
