### ISSUE TITLE
Slack API error

### ISSUE THREAD

**Issue by Deon-v** [MicrosoftDocs/bot-docs#1588]
After Following the instructions [Use Azure Bot Service portal to connect your bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs) even with the ammended changes due to the changes in slacks side.
When i send a message from slack i get an error in my Slack channel "Slack API error".
The /api/messages controller is reached fine when I install the app onto the workspace, but posting messages gives the error.

![image](https://user-images.githubusercontent.com/61790571/75996379-b252f100-5ef5-11ea-9c7d-84b51b18fd78.png)

![image](https://user-images.githubusercontent.com/61790571/75996410-be3eb300-5ef5-11ea-93c0-ffa126d0c936.png)

I would expect the message to reach my server and echo it back to the client.

I am hosting the bot from a logal machine using ngrok, but i beleive the issue is the Bot Channel on Azure.

Web chat test works fine.

**Comment by mmiele** [comment]
@jwiley84 Jessica, let me know if you have any suggestion on this. Thanks

**Comment by mmiele** [comment]
@Deon-v Could you please provide the BotId so we could look in the logs and see what's going on.
Thanks

**Comment by goodprogrammist** [comment]
> @Deon-v Could you please provide the BotId so we could look in the logs and see what's going on?
> Thanks
Hello!
App ID AU0J6B007 (I have same issue http://i.imgur.com/DlrD8Nv.png)
Thanks!

**Comment by Deon-v** [comment]
@mmiele Sorry for the delayed response on this, I deleted the app, would the logs still exist if i canget the App Id from my deployments list?

**Comment by mmiele** [comment]
@Deon-v Thank you for your update. Would it be possible for you to reproduces the problem?  Or perhaps, give us more details on how you encountered it?

**Comment by Deon-v** [comment]
@mmiele 

Create a bot service channel registration

1. Create bot channel registration **NOT** a new bot
2. Follow the steps indicated on the documentation
3. Create an API and setup for bot use and host with ngrok

I don't know what else to give you, because the above steps was all i did to try and get the bot working.

**Comment by mmiele** [comment]
@Deon-v My apologies for the delay. I did follow the steps as described in the article and I did not get any error. Anyway, I fixed the documentation so it is easier to read and the steps are easier to follow. The updated version should be made public soon. I'll let you know as soon as it happens.

**Comment by dipbanik** [comment]
@mmiele  
I faced the same or similar issue when I did the Slack channel registration. I cleared the errors and they did not reappear. I thought that I might have made some config error while creating the channel or registering on Slack, but now I am having second thoughts. Anyhow, it worked fine for me although it registered those errors/issues initially. But since I was hosting using ngrok, the bot is not active anymore.
Also, when you say botid, do you mean the app id?

**Comment by mmiele** [comment]
Documentation has been updated.
