### ISSUE TITLE
Bot tools capabilities

### ISSUE THREAD

**Issue by Akshaydirisala** [MicrosoftDocs/bot-docs#1589]
This page does not show the end to end capabilities for Bot tools, It does not tell is LUIS SDK capable of retrieving the data from databases likes SQL and providing the results to clients.Please update this information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6838575c-d2fc-65e3-98c2-0b35992c10b2
* Version Independent ID: 2b5dc3fc-49c0-7cd2-e6e1-4ced8da6c5f9
* Content: [Azure Bot Service Introduction - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-overview-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-overview-introduction.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
The article you refer to is an introduction, so it contains general information.

- If you want more detailed information about LUIS. please refer to the [case studies](https://azure.microsoft.com/services/bot-service/) link at the end of the article.

- You can also ask questions on StackOverflow; for example, check this post: [How to connect the data retrieved from SQL database in activity method to luis intent and display the data using luis intent](https://stackoverflow.com/questions/43797062/how-to-connect-the-data-retrieved-from-sql-database-in-activity-method-to-luis-i).

- Finally check these [Bot Framework additional resources](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-links-help?view=azure-bot-service-4.0).
