### ISSUE TITLE
NodeJS(TypeScript)Bot deployment failure

### ISSUE THREAD

**Issue by tanetrail** [MicrosoftDocs/bot-docs#1591]
Created the bot using **Create a bot with the Bot Framework SDK**. by choosing typescript option

Node version: 10.16.0

once after building the bot and successfully executing it on the local system(Mac). tried to follow the **deploy bot to azure** and uploaded the zip file to azure as per the instructions and getting below error (changed the nodejs version(10.16.3) using WEBSITE_NODE_DEFAULT_VERSION and languageWorkers:node:defaultExecutablePath and also updated the appservice to 64bit as suggested in other issues )

![image](https://user-images.githubusercontent.com/61951630/76173208-68734080-616b-11ea-8656-12f0bb4ccb42.png)

Even tried to install the bot using deploy.sh to linux appservice but no luck. Could you please update the detail steps to deploy the Typescript bot created using quick start

**Comment by anusharavindrar** [comment]
@tanetrail, can you please link the documentation you have followed? Also, can you elaborate on the steps? What macOS version are you on?

**Comment by anusharavindrar** [comment]
Closing the issue due to no response. Feel free to reopen if you have need to get this resolved.
