### ISSUE TITLE
Add configuration information - Python

### ISSUE THREAD

**Issue by rvinothrajendran** [MicrosoftDocs/bot-docs#1596]
In Add configuration information ( Section 1) - Python in the sample code Add the following information to your bot.py file area 
Header is wrong -&gt; Header should be Python not JavaScript :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Write directly to storage - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=python#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for catching this @rvinothrajendran. I've updated the header in [PR 2040](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2040).

**Comment by emgrol** [comment]
Closing now that the changes are live.
