### ISSUE TITLE
Unable to "Read" from Cosmos DB

### ISSUE THREAD

**Issue by josephwccheng** [MicrosoftDocs/bot-docs#1598]
I've followed the steps on setting up CosmoDB and also creating the echo bot on node.js. I realise that the code can only "Write" to the database but unable to "Read" From it.
I.e. in this example if I were to send "hi1" and "hi2", the end result does not store "hi1" as it did not read it from the database.
How can I resolve this? Thank you.

---
#### Detalji dokumenta

⚠ *Ne uređujte ovu sekciju. Ona je neophodna za povezivanje problema slijedom docs.microsoft.com ➟ GitHub.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Write directly to storage - Bot Service - Bot Service](https://docs.microsoft.com/bs-latn-ba/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript#using-cosmos-db)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
CosmosDbStorage is deprecated, instead you should use [CosmosDbPartitionedStorage](https://github.com/microsoft/botbuilder-dotnet/blob/dd34f0a8067750bce06b9f4f79abdc3d82210968/libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs). You can read more in the Azure documentation about how to [partition Azure Cosmos DB](https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview).

**Comment by emgrol** [comment]
Closing now that the changes have been merged live.
