### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jwiley84** [MicrosoftDocs/bot-docs#1601]
Nothing big, nothing to worry about, but there's a typo on the last line 

&gt;For more infrmation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ccf96a4-40b0-459b-b75b-716937b38ed4
* Version Independent ID: 0d5ee288-feb5-4cbb-c1dd-ec1774d90e49
* Content: [Bot Framework REST APIs  - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-overview?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-overview.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-overview.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing out this out @jwiley84. I've fixed the typo in [PR 2040](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2040).

**Comment by emgrol** [comment]
Closing now that the changes are live.
