### ISSUE TITLE
Deprecation of Skype and Skype for Business

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1602]
Please mention the deprecation of Skype and Skype for Business on this page, since it currently makes it look like these are supported channels

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3882e9d-ce18-408f-194c-7d973000b3a7
* Version Independent ID: 1017b42b-84de-1827-bb7e-0ca7270c1a0f
* Content: [Configure a bot to run on one or more channels - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-channels?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-manage-channels.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-manage-channels.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for mentioning this @v-kydela. I'm updating that article and any others that mention Skype/Skype for Business in [PR 2041](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2041).

**Comment by emgrol** [comment]
@v-kydela Do you have the date for when Skype will be deprecated? I read that Skype for Business will be retired [July 2021](https://docs.microsoft.com/en-us/microsoftteams/faq-journey) but didn't see any dates for Skype.

**Comment by v-kydela** [comment]
@emgrol - Thank you for addressing this. I'm sorry but I don't know of any plans to deprecate Skype as a whole. I was referring to the Skype bot deprecation that has already happened, and I think that's what we should be mentioning here. It would be similar to the work you did for this issue: https://github.com/MicrosoftDocs/bot-docs/issues/1510

**Comment by emgrol** [comment]
Closing now that the changes are live.
