### ISSUE TITLE
Seems like about half of this documentation is missing.

### ISSUE THREAD

**Issue by DavidStrickland0** [MicrosoftDocs/bot-docs#1607]
1) Starts off by explaining the Cancel And Help Dialog.
2) Talks about how the MainDialog works
3) Then discusses Handling Errors
4) Then Says to tests by "send messages as shown below"
Then Ends
Where \ How does the CancelAndHelpDialog tie in?.
Theres nothing below the line that says
"Start the emulator, connect to your bot, and send messages as shown below."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef4ea5a-1364-5432-dcbb-b39b7145028a
* Version Independent ID: f4b4a848-3ce4-7978-a72d-2c3952a3ab1b
* Content: [Handle user interruptions - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-handle-user-interrupt?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-handle-user-interrupt.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-handle-user-interrupt.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by DavidStrickland0** [comment]
Case anyone else comes across this and misses how this all ties in together. The explanation here assumes that BookingDialog isa CancelAndHelpDialog.

**Comment by JonathanFingold** [comment]
I'll post an update to the article, but probably won't be able to get to it till next week.

**Comment by JonathanFingold** [comment]
Updating the statement about the `` class to read:

We begin by implementing the `CancelAndHelpDialog` class to handle user interruptions. The cancellable dialogs, `BookingDialog` and `DateResolverDialog` derive from this class.
