### ISSUE TITLE
Teams link is broken

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1608]
I'm unsure if there's an aka.ms for this, but you may want to link here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots

Or here: https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feeaef38-ead4-3ce5-c19e-6bf545abf148
* Version Independent ID: 1b3f4b1d-66ff-a073-ed98-125a2e58d95f
* Content: [Connect a bot to Skype for Business - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-skypeforbusiness?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-skypeforbusiness.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-skypeforbusiness.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing out this broken link @v-kydela. I've update the link in [PR 2045](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2045).

**Comment by emgrol** [comment]
Closing now that the changes are live.
