### ISSUE TITLE
Change Bot Icon and Display Name by code

### ISSUE THREAD

**Issue by floushee** [MicrosoftDocs/bot-docs#1611]
Is it possible to change the icon or display name in a programatically way? We will need to provide an automated deployment for customers and including manual steps is a bit inconvinient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b527247b-38f8-0bc0-6eda-af6382d8f1af
* Version Independent ID: e1c371cc-9183-1138-69e3-77a096a9f964
* Content: [Configure bot settings - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-settings?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-manage-settings.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-manage-settings.md)
* Service: **bot-service**
* GitHub Login: @v-royhar
* Microsoft Alias: **kamrani**

**Comment by floushee** [comment]
You can close it. Was a bit hard fo find, but I got this https://docs.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest#az-bot-update

**Comment by emgrol** [comment]
Thanks for mentioning this @floushee. I added a link to the command you referenced since it is helpful in this context and that content shouldn't be hard to find.
