### ISSUE TITLE
Unclear how to install an app for the Slack adapter

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1613]
The Slack adapter portion of this document and the Slack adapter sample (60) readme both say this:

"Navigate to the Install App page under the Settings menu and follow the instructions to install your app into a Slack team."

This is unclear because the instructions say that features or scopes need to be added in order to install an app, and we're not saying what features or scopes to add. Perhaps we should tell people to add the same scopes that are in the Azure portal instructions, or perhaps we should copy those scopes into the Slack adapter instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=adapter)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@v-kydela  Hi Kyle, I did address the issue you described. Please, take a look a the following section 
[Gather required configuration settings for your bot](https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-3.0&branch=pr-en-us-2042&tabs=adapter#gather-required-configuration-settings-for-your-bot) on the review site. Specifically, look at step 5. Let me know if it solves the problem you mentioned. Thanks

**Comment by v-kydela** [comment]
@mmiele - I'm sorry but it doesn't look like I have access to the review site. The PR looks okay though.

**Comment by mmiele** [comment]
Documentation has been updated.

**Comment by shram2k** [comment]
I could not make https://1940e052.ngrok.io/api/slack in slack api portal. It says "Your URL didn't respond with the value of the challenge parameter."
