### ISSUE TITLE
Need to select version 2.1.1 of Microsoft.Extensions.Configuration package

### ISSUE THREAD

**Issue by ssemyan** [MicrosoftDocs/bot-docs#1616]
When adding the Microsoft.Extensions.Configuration NuGet package, it will default to the latest version which is 3.x. Because the Visual Studio bot project defaults to .net core 2.1.1, you need to manually select version 2.1.1 of the Microsoft.Extensions.Configuration package or you get an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by ssemyan** [comment]
Actually it seems this package is not required to be added as it exists already in the project.

**Comment by JonathanFingold** [comment]
@ssemyan - I'll check with the team on this. There is some discussion as to whether all the samples are migrating to .NET Core 3.1 or not.

**Comment by JonathanFingold** [comment]
@ssemyan - The .NET samples now target Core 3.1. Researching further.

**Comment by JonathanFingold** [comment]
I think this issue is fixed in bot-docs-pr [PR 2059](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2059)
