### ISSUE TITLE
Failed Email Delivery From O365 Account 

### ISSUE THREAD

**Issue by TranKennyK** [MicrosoftDocs/bot-docs#1618]
**Describe the bug**
My bot receives the following non-delivery email report from O365 when attempting to send outbound email in response to an inbound email.

Initially, I believed my O365 account has been added to the spam block list because it is a new account and does not have an email sending history; however, I am able to send emails from it manually through Outlook application. Therefore, the issue is specific to sending outbound emails from the Azure Bot server. 

**Delivery has failed to these recipients or groups:**
**name@emailaddress.com**
**Your message wasn't delivered because the recipient's email provider rejected it.**

**Diagnostic information for administrators:**
**Generating server: DM6PR11MB3804.namprd11.prod.outlook.com**
**name@emailaddress.com**
**Remote Server returned '550 5.7.501 Service unavailable. Spam abuse detected from IP range. For more information please go to http://go.microsoft.com/fwlink/?LinkId=526653. S(2017052602) [DM6PR11MB2729.namprd11.prod.outlook.com]'**

Below is the issue displayed by Channels tab of my Web Bot service in Azure Portal.
**Message: There was an error sending this message to your bot: HTTP status code InternalServerError 
ID: |RW3ZkVpQyas=.927c7a19_**

**Comment by dmvtech** [comment]
Hi @TranKennyK Have you gone through your O365 Exchange settings? You need to figure out why it is blocking it (is it a frequency thing, something in the content, etc). Then once you know that, you should be able to change something in either the Exchange settings or in the bot code/behavior.

Regardless, this is an O365/Exchange issue.
