### ISSUE TITLE
Having /Commands seems to break the botframework

### ISSUE THREAD

**Issue by jhueppauff** [MicrosoftDocs/bot-docs#1619]
Hi,

I configured the bot like this documentation.
The inital message from my bot is comming through. But if you try /command it seems telegram or the botframework do not like this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 260c283c-f5e9-e00d-19ec-ee9df18335e5
* Version Independent ID: d1525408-36d3-6575-2331-a16379744a59
* Content: [Create a bot for Telegram - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-telegram?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-telegram.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-telegram.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Hi @jhueppauff, I just created a Telegram bot and haven't had any issues running /commands. I'm adding the Support label to get further assistance since this doesn't seem to be a documentation issue.

**Comment by jhueppauff** [comment]
I just doubled checked.. seems like it took some time or there was an issue with the channel. 
Thanks.
