### ISSUE TITLE
Login with something other than Graph

### ISSUE THREAD

**Issue by nastassiar** [MicrosoftDocs/bot-docs#1622]
I'm trying to retrieve a token a use to login Dynamics (via a Teams Messaging extension). I have a v1 AAD App that I gave delegated permission. I expected to be able to just set the resource as my Dynamics and then use the token once I retrieved it, but I keep getting permissions errors. Are there steps that are missing to have it work with something other than than Graph? Also when I do get the token via my Messaging Extension in Teams and then pass it into jwt.ms the aud value is graph.com but when I test the connection via the Bot service the aud is Dynamics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by nastassiar** [comment]
*** I solved the Issue by recreating my connection. It appears that the connections can't really be edited? I originally created it with Graph as the resource and then went back and updated it to dynamics after I'd gotten the sample working. I tried changing the resource multiple times with no success. I don't know if it is a bug in the portal or something else but it was very frustrating.

**Comment by emgrol** [comment]
Closing since the issue was resolved.
