### ISSUE TITLE
Include examples of using state inside dialogs

### ISSUE THREAD

**Issue by jbgh2** [MicrosoftDocs/bot-docs#1623]
This example send activities directly to the user. Most bots use dialogs to interact with the user. Please include an example of getting/setting state inside a dialog.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e18bc52f-7eaf-a473-1cba-9b7c83bd0025
* Version Independent ID: c1b6cf03-c236-cfbf-aa4b-96961b816bc3
* Content: [Save user and conversation data - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@jbgh2 Please see the how-to article [Implement sequential conversation flow].
