### ISSUE TITLE
Microsoft Bot Framework

### ISSUE THREAD

**Issue by aayush-scalex** [MicrosoftDocs/bot-docs#1626]
Question - Bots on "Microsoft Teams" are developed using "Microsoft Bot Framework" only, can we directly interact with "Microsoft Teams"  SDKs? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253d4e99-7fc5-cc8d-5b07-29bf2d78687a
* Version Independent ID: cdc0528d-cf1a-e015-1d8a-31ed062648f8
* Content: [Bot Service Frequently Asked Questions - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/bot-service-resources-bot-framework-faq.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-resources-bot-framework-faq.md)
* Service: **bot-service**
* GitHub Login: @scheyal
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @aayush-scalex Thanks for reaching out. Here is an [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics-teams?view=azure-bot-service-4.0&tabs=csharp) that might help answer your question.
