### ISSUE TITLE
Add GetConversationMember documentation

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/bot-docs#1627]
We need to add documentation for this new endpoint. An example of the REST call can be found here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=json#get-single-member-details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36ddb50-9e44-96e3-2df3-174166efa75d
* Version Independent ID: 68ac4b64-6616-2216-3519-e0b33d3a53e4
* Content: [API reference - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@clearab - I'm looking at the [Microsoft Bot Connector API - v3.0](https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-protocol/botframework-channel.json) Swagger file, which is what this page documents. I don't see any new end point in our schema for the new Teams endpoint .

**Comment by clearab** [comment]
Hi,
This is the new endpoint: https://github.com/microsoft/botframework-sdk/blob/8e20eafae34bc9ddf3b830d6bea7424b46acf2dc/specs/botframework-protocol/botframework-channel.json#L671

It isn’t specific to Teams.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JonathanFingold** [comment]
Note's from our discussion off-line:
- The Swagger file is out of date. Andrew is checking with Dan about updating the copy on the botframework-sdk repo.
- I'll start drafting a section based on the Teams sample and the `Conversations.GetConversationMemberWithHttpMessagesAsync` method, which is the wrapper for the new endpoint.
