### ISSUE TITLE
Facebook channel: Create custom integration UI 

### ISSUE THREAD

**Issue by geo-msft** [MicrosoftDocs/bot-docs#1630]
**Describe the bug**
This is not a product bug; rather a lack of recent doc. 

The instructions for creating a custom integration seem to have changed. 
How do I create a bot for workplace? 

I am not able to see the blue button in this step: Create custom integration 
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0#create-a-custom-integration 

I only see this: 
![image](https://user-images.githubusercontent.com/57954688/77775712-999dad00-7055-11ea-87b3-e118e3ebcd24.png)

Also, as a general feedback, I find it useful to have Workplace in a separate page from the Facebook messenger (for easier reading). 

Thank you!

**Comment by geo-msft** [comment]
Hi, I created a new Workplace trial and I have visible the admin panel now. 

The UI is changed a bot, but I see the button "Create custom integration" [all good]. 
 
![image](https://user-images.githubusercontent.com/57954688/78023776-f05dfc00-735f-11ea-82bb-0c58294c27ea.png)

I still find it useful to separate the Facebook messenger integration from the Facebook workplace integration, for better following the steps. Thank you.

**Comment by JonathanFingold** [comment]
Following up with a dev. Sorry for the long silence on this issue.

**Comment by mmiele** [comment]
The corrected article will be available in the next documentation update.
