### ISSUE TITLE
Why isn't Step.4 an article?

### ISSUE THREAD

**Issue by tsubaki961** [MicrosoftDocs/bot-docs#1631]
[Enter feedback here]
Because Step.4 is not an article, this step's link not exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0b8671-359e-6026-fd3a-39331cea73f3
* Version Independent ID: 29bab4ad-243a-fb0a-99ed-d8336a92f648
* Content: [Develop DirectLine Speech Bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/directline-speech-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/directline-speech-bot.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing out the typo @tsubaki961, a fix for it will go live soon.

**Comment by emgrol** [comment]
Closing now that the link fix is live.
