### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by nathanbisges** [MicrosoftDocs/bot-docs#1637]
Missing a word in the 'Secrets and Tokens' section.

"the default behavior because allows Direct "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd0bdf8-7cb8-1f26-65a1-3876ea84351f
* Version Independent ID: bda6ce3a-f006-baaf-db50-82bd79afa6ab
* Content: [Authentication - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0#secrets-and-tokens)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-authentication.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for letting us know about this grammatical mistake @nathanbisges. I've opened a [PR](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2070) to fix it, the change should go live soon.

**Comment by emgrol** [comment]
Closing now that the fix is live.
