### ISSUE TITLE
Cards through SlackAdapter

### ISSUE THREAD

**Issue by dipbanik** [MicrosoftDocs/bot-docs#1639]
I am trying to enable Prompts and Cards by using the Slack Adapter in C#. The article describes only about echo bot. Is there a way to enable them or is it still in the pipeline for development?

If there is, can someone redirect me to a reference article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=adapter#feedback)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
This article outlines how to use the Slack adapter, along with the Bot Framework adapter. The adapters manage traffic between a bot and a channel, but do not include the bot's business logic.

The steps in this article can be used with any bot to add support for the Slack channel. Once you have created the Slack adapter, created the Slack controller, and updated Startup.cs; you can follow any of the how-to articles for adding features to your bot.

- See how-to [Add media to messages](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-add-media-attachments) for information on sending cards.
- See how-to [Implement sequential conversation flow](https://docs.microsoft.com/azure/bot-service/bot-builder-dialog-manage-conversation-flow) for information about using prompts within dialogs.
- See the [Channel reference](https://docs.microsoft.com/azure/bot-service/bot-service-channels-reference) for information about which features (including card types) are supported on each channel.

**Comment by dipbanik** [comment]
I modified the Handling attachments Bot (https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/15.handling-attachments) from the sample projects to use it with the Slack Adapter. I also used it with the Bot Channel Registration through Azure without making the Slack Adapter changes. 
So I think the basic business logic to cover the prompts and a Hero Card was covered there as I could see it when I used the Channel Registration. 
But when using the slack adapter, it does not appear. 
My guess is that I am not doing the configuration at the Slack app end correctly. It might be the Interactivity Request URL which I have currently set as "https://{myboturl}/api/slack". This was set as "https://slack.botframework.com/api/Actions" when using the Bot Channel Registration. Can you confirm what the request URL should be set to for interactivity when using the Slack Adapter?

**Comment by JonathanFingold** [comment]
One thing to try would be to add conditional code into your bot. If the activity came in on the Slack channel, then use a Slack-specific attachment; otherwise, use the Bot Framework hero card.

**Comment by dipbanik** [comment]
I understand your solution, however, my question is different - When I attach a Hero Card to a reply to a Slack Adapter, will I be able to visualize it in the slack app?

Currently I have two bots in slack -
1. one slack app connected to the slack adapter endpoint of my code.
2. second slack app connected to the Azure Bot Channel Registration endpoint of my code.

Both endpoints are subscribed to the same events and have the same codebehind bot associated with them.

But the Slack Adapter bot is not able to render the Hero Card. It is only rendering the IM messages. The Azure Channel bot is however able to render the hero card.

So, will I be able to render the hero card to the user using the Slack Adapter?

**Comment by JonathanFingold** [comment]
This might be a bug in the SlackAdapter, then. I'll create an issue in the SDK repo and cross link it.

**Comment by JonathanFingold** [comment]
@dipbanik There is an existing issue that might be affecting you: botbuilder-dotnet [3593](https://github.com/microsoft/botbuilder-dotnet/issues/3593).

@v-kydela Can you comment on the issue in this thread?

**Comment by v-kydela** [comment]
@dipbanik - The Slack adapter does not convert any Bot Framework cards to Slack blocks. You can see in the [source code](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs#L55-L67) that the Slack adapter only accepts attachments that are already Slack blocks, and if an attachment isn't in Block Kit form then only the thumbnail image is used and the content is ignored:

```c#
if (att.Name == "blocks")
{
    message.Blocks = (List<Block>)att.Content;
}
else
{
    var newAttachment = new SlackAPI.Attachment()
    {
        author_name = att.Name,
        thumb_url = att.ThumbnailUrl,
    };
    attachments.Add(newAttachment);
}
```

If you want hero cards to be automatically converted to Slack blocks then you will need to use the Azure Bot Service Slack connector instead of the Bot Builder SDK Slack adapter. Otherwise, you can refer to this sample to see how to use Block Kit in your bot: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/60.slack-adapter

**Comment by dipbanik** [comment]
Thank you for the clarification.
