### ISSUE TITLE
Test your bot instructions don't match current Azure portal

### ISSUE THREAD

**Issue by jbgh2** [MicrosoftDocs/bot-docs#1642]
Instructions for testing bot in Azure are:

Ensure that your bot has been successfully deployed and is running.
Sign in to the Azure Portal.
Click My Bots.
Select the bot that you want to test.

Please update to match new portal UI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc8a0643-f219-a48f-666e-95bc9f0f351c
* Version Independent ID: 81578919-249c-b3e7-b367-183d70135890
* Content: [Troubleshooting Bot Framework Authentication - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-troubleshoot-authentication-problems.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-troubleshoot-authentication-problems.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out @jbgh2. The updated instructions should go live soon.

**Comment by emgrol** [comment]
Closing now that changes are live.
