### ISSUE TITLE
Could you add the steps to debug a bot using VS Code and C# ?

### ISSUE THREAD

**Issue by dipbanik** [MicrosoftDocs/bot-docs#1648]
I would like to debug my bot using VS Code rather than Visual Studio. I would love to see the steps listed down on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 134459a0-37b2-3111-06e2-71feb2b45e3c
* Version Independent ID: 3efc8cdb-f0a0-40ae-577c-348890233aa4
* Content: [Debug a bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-debug-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-debug-bot.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for the suggestion @dipbanik. I added a section about debugging C# bots in [PR 2163](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2163). The update should go live soon, here are the steps:
1. Launch VS Code and open your bot project folder.
1. Set breakpoints as necessary. You can set breakpoints by hovering your mouse over the column to the left of the line numbers. A small red dot will appear. If you click on the dot, the breakpoint is set. If you click the dot again, the breakpoint is removed.
1. From the menu bar, click **Run** and then click **Start Debugging**. Your bot will start running in debugging mode from the Terminal in Visual Studio Code.
1. Start the Bot Framework Emulator and connect to your bot as described in the [Debug with the Bot Framework Emulator](https://docs.microsoft.com/azure/bot-service/bot-service-debug-emulator) article.
1. From the emulator, send your bot a message (for example, send the message "Hi"). Execution will stop at the line where you place the breakpoint.

**Comment by dipbanik** [comment]
@emgrol This is highly appreciated. I was also looking for some documentation on how to kickstart a bot template from scratch using VS code. Any reference document or steps to that?

**Comment by emgrol** [comment]
Hi @dipbanik,  in the [**Create a bot with the Bot Framework SDK for .NET** ](https://docs.microsoft.com/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0&tabs=vc) article the are instructions for how to create a C# bot in VS Code.

**Comment by dipbanik** [comment]
@emgrol I was able to run it while editing on VS Code and C# starting sometime in July I believe. Thanks for the doc! I'm sure it'll help a lot of people!

**Comment by emgrol** [comment]
Thanks @dipbanik! Closing this issue now that all questions have been resolved.
