### ISSUE TITLE
Send Proactive msg when user is idle

### ISSUE THREAD

**Issue by jnaman509** [MicrosoftDocs/bot-docs#1649]
I am using bot framework sdk 4 in which i need to send message to user in between the conversation if user is idle or user is in sleep mode from last 30 sec. so how can i do this using proactive message. or is there any other way to do this. i hope you understood my problem.

**Comment by JonathanFingold** [comment]
Have you looked at the how to [send proactive notifications to users](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-proactive-message) article already?

Your solution will depend on the environment in which your bot is deployed. One way to do this would be to define a separate service that your bot can log user activity to. The service would have the timer logic and notify the bot when it needs to send a proactive message to a given user.
