### ISSUE TITLE
`state.botframework.com` Entry in whitelist URLs FAQ

### ISSUE THREAD

**Issue by nebhagat** [MicrosoftDocs/bot-docs#1650]
`state.botframework.com` is listed under [FAQ](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0#which-specific-urls-do-i-need-to-whitelist-in-my-corporate-firewall-to-access-bot-framework-services) **Which specific URLs do I need to whitelist in my corporate firewall to access Bot Framework services** 

bot framework state service is retired according to https://blog.botframework.com/2018/04/02/reminder-the-bot-framework-state-service-has-been-retired-what-you-need-to-know/ . 

It may no longer needed in the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253d4e99-7fc5-cc8d-5b07-29bf2d78687a
* Version Independent ID: cdc0528d-cf1a-e015-1d8a-31ed062648f8
* Content: [Bot Service Frequently Asked Questions - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-resources-bot-framework-faq.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-resources-bot-framework-faq.md)
* Service: **bot-service**
* GitHub Login: @scheyal
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@nebhagat `state.botframework.com` may still be needed by some older bots for backwards compatibility. I'll update the FAQ to be clear on that point, to be less confusing.

**Comment by nebhagat** [comment]
Thanks!
