### ISSUE TITLE
Whitelist bot framework URLs to access Bot Framework services

### ISSUE THREAD

**Issue by nebhagat** [MicrosoftDocs/bot-docs#1651]
`*.botframework.com` is listed under [FAQ](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0#which-specific-urls-do-i-need-to-whitelist-in-my-corporate-firewall-to-access-bot-framework-services) **Which specific URLs do I need to whitelist in my corporate firewall to access Bot Framework services**

Getting below response from the below urls's from unix server- open network .
 `msteams.botframework.com` --> curl: (22) The requested URL returned error: 503 Service Unavailable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253d4e99-7fc5-cc8d-5b07-29bf2d78687a
* Version Independent ID: cdc0528d-cf1a-e015-1d8a-31ed062648f8
* Content: [Bot Service Frequently Asked Questions - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0#which-specific-urls-do-i-need-to-whitelist-in-my-corporate-firewall-to-access-bot-framework-services)
* Content Source: [articles/bot-service-resources-bot-framework-faq.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-resources-bot-framework-faq.md)
* Service: **bot-service**
* GitHub Login: @scheyal
* Microsoft Alias: **kamrani**

**Comment by dmvtech** [comment]
Hi @nebhagat 

To clarify; you want to have a list of specific hostnames to whitelist instead of the wildcard `*.botframework.com` ?

Regarding the 503; was that an error you were getting previously before whitelisting `msteams.botframework.com`?

**Comment by biswanathptr2424** [comment]
Before white-listing the error was , 
**curl: (6) Could not resolve host: msteams.botframework.com; Unknown error**

**Comment by dmvtech** [comment]
Hi @biswanathptr2424 

Please clarify; you were receiving the error before whitelisting, but after whitelisting; it works. Correct?

Did you whitelist `*.botframework.com` or `msteams.botframework.com`?

I'm unclear on what you are asking for.

**Comment by biswanathptr2424** [comment]
Hi,
From open network msteams.botframework.com was used .

**Comment by dmvtech** [comment]
After more investigation, msteams.botframework.com will not work. Each Teams tenant will have it's own endpoint and will vary. Teams will use `smba.trafficmanager.net` will be what is used, least some cases, so whitelisting `*.botframework.com` certainly isn't a whole story/solution.

I'll see if i can find more info.

@emgrol I think documentation should be revised for this scenario (MS Teams)? Maybe update the note to say something regarding teams?

**Comment by dmvtech** [comment]
You can try using the following to test smba:
`curl https://smba.trafficmanager.net/ping`

To successfully whitelist for teams, you could whitelist `*.botframework.com` and `smba.trafficmanager.net`
