### ISSUE TITLE
WebEx instructions appear to be wrong..

### ISSUE THREAD

**Issue by arizonawayfarer** [MicrosoftDocs/bot-docs#1653]
In order to create the webhook so the bot will receive messages and do stuff with them, you have to use a POST, not a PUT.  PUT is for updating an existing webhook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e61be5-e537-8678-f907-10f27ea7bf90
* Version Independent ID: e2a9d88e-0819-9de5-d6f8-48bf7b270685
* Content: [Connect a bot to Webex Teams - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-adapter-connect-webex?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-adapter-connect-webex.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-adapter-connect-webex.md)
* Service: **bot-service**
* GitHub Login: @garypretty
* Microsoft Alias: **gapretty**

**Comment by JonathanFingold** [comment]
@arizonawayfarer Looks like the article was updated without updating this thread. Please let us know if you find any other issues.
