### ISSUE TITLE
Can you guys please git rid of the ARM section. It is completely confusing and I don't understand why it's not realized

### ISSUE THREAD

**Issue by xtianus79** [MicrosoftDocs/bot-docs#1654]
Again, I keep alerting you guys that the directions don't take into consideration that you could already have an app id setup or how to even setup one in the portal. 

I literally came back and did the same mistake I did a year ago

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=typescript)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@xtianus79 Thank you for contacting us and for your persistence. 
Would you mind to elaborate more on the issue you are describing? It will help us to address the problem better. Thanks

**Comment by xtianus79** [comment]
@mmiele thanks for your reply. The problem and since i've done it twice i can assure you this is the confusion. The problem is when you go and create a bot from a different tutorial and it goes through the portal is already creates an app registration and it already creates the service and service plan. So when you go down these instructions that aren't portal based at all you may not realize you've already done a part of it.

Here's why including portal information is important. 1. Someone have already created these services. 2. There are important things in the portal that should have attention drawn to them i.e. the environment variables because that is what those things are. 

Imagine if I create something and then attach env variables to it and then go through these instructions because I am trying to deploy something. 

It's just QA'ing the use case. 

If I need to deploy the bot and everything is setup. What would be those instructions. 

1. create the web config
2. zip the files up. 
3. deploy 
4. check the environment variables in the portal at these specific places and make sure you have these params. And your app should work.

**Comment by mmiele** [comment]
@xtianus79  Apologies for the delay. We'll do some revising of the article [Deploy your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=typescript). In the meantime we suggest not to mix Azure portal with Azure CLI deployment.
