### ISSUE TITLE
Python is now GA

### ISSUE THREAD

**Issue by meetshamir** [MicrosoftDocs/bot-docs#1655]
This needs correction
(SDKs for Java and Python are under development.) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6838575c-d2fc-65e3-98c2-0b35992c10b2
* Version Independent ID: 2b5dc3fc-49c0-7cd2-e6e1-4ced8da6c5f9
* Content: [Azure Bot Service Introduction - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-overview-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-overview-introduction.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out @meetshamir, the doc will be updated soon.

**Comment by emgrol** [comment]
Closing now that changes are live.
