### ISSUE TITLE
Bug in the image?

### ISSUE THREAD

**Issue by meetshamir** [MicrosoftDocs/bot-docs#1656]
Activities arrive at the bot from the Bot Framework Service via an HTTP POST request. The bot responds to the inbound POST request with a 200 HTTP status code. Activities sent from the bot to the channel are sent on a separate HTTP POST to the Bot Framework Service. This, in turn, is acknowledged with a 200 HTTP status code.

The above section explains that activities sent from the bot to the BFS is on a new HTTP POST but the image shows that POST is from the BFS to the bot?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ccf81d0-a7a0-1e2a-5b35-8cfd723c1225
* Version Independent ID: e3ebe0a1-a22f-1535-c649-3f79158b4ece
* Content: [How bots work - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
The image is correct, as far as it goes. What it doesn't show clearly is that the Azure Bot Service (the Bot Framework Service) is an intermediary between the channel and your bot. The service forwards messages and response from the channel to the bot and back again.

Does that explanation help?

**Comment by NSouth** [comment]
> The image is correct, as far as it goes. What it doesn't show clearly is that the Azure Bot Service (the Bot Framework Service) is an intermediary between the channel and your bot. The service forwards messages and responses between the channel and the bot.

The diagram makes it look like the "Adapter, Turn Context" layer posts directly to the channel. But it sounds like this layer _actually_ posts to the Bot Framework Service, which forwards the message to the channel. **Is this correct?**

What confuses me is that it's not clear whether Bot Framework Service is a _layer of my bot app_ (like, a middleware component or something else on the same host as my bot app) or a _service in front of my bot app_. If it is a service in front of my bot app (a separate endpoint), I would expect the diagram to show HTTP communication between it and my bot app. **Is the Bot Framework Service a separate service sitting in front of the bot app, communicating with both the channel and the bot app via web protocols?** It sounds like clients don't ever make direct calls to the web service which hosts my bot.

**Comment by JonathanFingold** [comment]
Ah, sorry for the confusion. Yes, in this scenario, the adapter in your bot app sends the response (outgoing activity) to the Bot Framework Service, which forwards it to the channel and the user. It does so in a separate session from the one that is handling in the incoming activity from the user.

The Bot Framework Service is indeed a separate service sitting in front of the bot app. The Bot Framework Service is a REST API that the adapter makes a call to to send the response, so the service is not part of your application's code.

There is a somewhat new set of channel adapters which you can use to connect directly to the channel, without using the Bot Framework Service as an intermediary, so I'll need to update this topic to clarify all of this.

**Comment by JonathanFingold** [comment]
We hope to address this soon.
