### ISSUE TITLE
dotnet publish --configuration Release --runtime win-x86 --self-contained issue

### ISSUE THREAD

**Issue by heyyudao** [MicrosoftDocs/bot-docs#1659]
Hi, when i run command dotnet publish --configuration Release --runtime win-x86 --self-contained 
i get MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
this issue. anyone can help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@heyyudao Did you build the project before running the `dotnet publish` command?

**Comment by mmiele** [comment]
Fix available in the next published documentation.
