### ISSUE TITLE
Several JS samples have odd module import practice

### ISSUE THREAD

**Issue by ryanvolum** [MicrosoftDocs/bot-docs#166]
In several samples, modules are imported on multiple lines:
```
const {MessageFactory} = require('botbuilder');
const {CardFactory} = require('botbuilder');
```
Should look like:
```
const {MessageFactory, CardFactory} = require('botbuilder');
```

**Comment by Kaiqb** [comment]
@ryanvolum - added to our backlog.

**Comment by ryanvolum** [comment]
Please reopen until bug is resolved.

**Comment by Kaiqb** [comment]
@ryanvolum - most of these were resolved back in August. The remaining issue in one topic has been resolved. Feel free to open this issue if you find anymore.
