### ISSUE TITLE
az deployment create is being deprecated, please update the deployment step based on MS feedback.  When I deploy based on what's provided, I get the warning below.

### ISSUE THREAD

**Issue by rmillman** [MicrosoftDocs/bot-docs#1660]
This command has been deprecated and will be removed in a future release. Use 'deployment sub create' instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Work in progress. It might be a duplication of issue [1724](https://github.com/MicrosoftDocs/bot-docs/issues/1724.)

**Comment by zxyanliu** [comment]
Hey, the doc is updated and merged. The content will go live soon. Thanks again for your feedback.

**Comment by rmillman** [comment]
Thanks.

**Comment by zxyanliu** [comment]
@rmillman You are very welcome!
