### ISSUE TITLE
Full list of terminal Dispatch commands

### ISSUE THREAD

**Issue by Zerryth** [MicrosoftDocs/bot-docs#1661]
We should include a link to the full list of Dispatch commands that the SDK team published on the botbuilder-tools repo somewhere in this document.

Specifically this is because a customer reached out to the SDK team, asking if there was even a command that existed that could update an existing Dispatch file [#1429](https://github.com/microsoft/botbuilder-tools/issues/1429), as after reading this article he believed there was not. 
The link included in this article currently that specifies to update the dispatch file leads to some Virtual Assistant doc that doesn't link to the full set of terminal commands for Dispatch either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs#create-the-dispatch-model)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by Zerryth** [comment]
Update: I see now that this article DOES mention the "dispatch add" command! Which is great. :D
I suppose just a reference link to the botbuilder-tools is still "useful" but not dire then :)

**Comment by emgrol** [comment]
Hi @Zerryth, in the introduction of the article there's a link to Dispatch in [botbuilder-tools](https://github.com/microsoft/botbuilder-tools/tree/master/packages/Dispatch). Is that link adequate, or should I update the link?

**Comment by Zerryth** [comment]
That link works perfectly. Didn't realize it was there earlier? (Or perhaps it was updated?)

In any case, looks good to me :) Thank you
