### ISSUE TITLE
When does the 6 digit code get created vs not?  I would like control or awareness of this

### ISSUE THREAD

**Issue by xtianus79** [MicrosoftDocs/bot-docs#1662]
Is there a way to know if the 6 digit code is coming up for this because the UI is horrible and the user has no idea what it means. The UI / UX could use a serious update. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Cjavascript#additional-information)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by xtianus79** [comment]
@JonathanFingold it's the 6 digit code returning for verification rather than the token being received automatically. it seems random.

**Comment by mmiele** [comment]
Added note in the listed article explaining the use the "magic code". The updated documentation will be in the next available build.
