### ISSUE TITLE
Order of the steps is confusing

### ISSUE THREAD

**Issue by pauldj54** [MicrosoftDocs/bot-docs#1663]
Hi everyone, 
even when I find this tutorial great, I will reorganize it. 
For instance:
- First of all I would install the cookiecutter module and download the code
- After that I would install all the dependencies
- You are telling to find the last line of a command you issue in a later step
Hope that helps, 
Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=python%2Ccsharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for the suggestion @pauldj54, and I agree that reordering the steps is a good idea. The update to the article will go live shortly.

**Comment by emgrol** [comment]
Closing now that the changes are live.
