### ISSUE TITLE
Errors using Node JS

### ISSUE THREAD

**Issue by NathofGod** [MicrosoftDocs/bot-docs#1667]
I have a bot up and running using MS Teams using the Node TS SDK. Going through the instructions here the messages never hit the backend, is there something I need to do.

There are no "Slack Adapters" that I can see for Node JS?

**Comment by JonathanFingold** [comment]
For now, the slack adapter is only available in the C# SDK. I'm not sure what the schedule is for porting it to the other languages. You can submit a feature request in the **microsoft/botbuilder-js** repo using the [issues](https://github.com/Microsoft/botbuilder-js/issues) tab.

I'll update the Slack article to mention this limitation.
