### ISSUE TITLE
Using adaptive cards to accept user inputs

### ISSUE THREAD

**Issue by dipbanik** [MicrosoftDocs/bot-docs#1669]
I am searching for a way to use cards to accept user text field inputs. While conversational user inputs are great, there are cases where we would want the user to simply fill out a form in the chat. For example, I want to collect the Name, age and phone number of the user. Having a form would be an efficient way of communicating, saving multiple turns.
What would be the recommended way to implement a form of such kind? Some samples would be great!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79129724-5f90-ac8d-6918-d5801a4e2001
* Version Independent ID: 08e19b7b-2ec6-95da-2f5a-d534e761f5da
* Content: [Create your own prompts to gather user input - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-primitive-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-primitive-prompts.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
This is still an open question in the SDK ([botbuilder-dot-net issue 614](https://github.com/microsoft/botbuilder-dotnet/issues/614)). However, there is some sample code in that discussion for using an Adaptive Card within a dialog.

With the next release of the Bot Framework, you should be able to use the new adaptive dialogs to accomplish this. You can read about the preview features in the botframework-sdk repo, see [Bot Framework SDK v4 preview features](https://github.com/microsoft/botframework-sdk#bot-framework-sdk-v4-preview-features).
