### ISSUE TITLE
Unable to follow the steps mentioned in the doc, since the Microsoft.Bot.Builder.StreamingExtensions is depricated.

### ISSUE THREAD

**Issue by Santhosh0505** [MicrosoftDocs/bot-docs#1670]
According to the documentation and previous issues mentioned on this doc, it is showing that I need to use Microsoft.Bot.Builder.StreamingExtensions in my Bot Framework Project, but as per the current status it is depricated and I am not able to run the example solution which @mmiele has mentioned. Can you please update the documentation steps as per the current status of it. So that I can connecct my bot using Microsoft.Bot.Connector.Directline

And the endpoint u r trying to mention with the directline client it is accepting this url "https://directline.botframework.com/" instead of "https://<YOUR_BOT_HOST>.azurewebsites.net/.bot/" . 
Can you please tell me the reason why it is behaving like this and let me know if any changes need to made to avoid it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c463a003-c709-b516-ce1b-6c45537de3b2
* Version Independent ID: 8ca42668-23ac-6dca-054d-d183b0fb5b0b
* Content: [Create .NET client for direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-client.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-client.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by alextse** [comment]
same here

**Comment by JonathanFingold** [comment]
Sorry for the long delay. The Microsoft.Bot.Streaming library was released, and I'm guessing this is why the StreamingExtensions library is deprecated. I'll review the article and make updates.

**Comment by Santhosh0505** [comment]
Thank you for the update, please post the update here once you confirm.

**Comment by mmiele** [comment]
@Santhosh0505 I am looking into this. Some documentation updates are needed. In the meantime, please refer to this article: [Configure .NET bot for extension](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0).

**Comment by Santhosh0505** [comment]
@mmiele Okay, Thankyou for the reference.
