### ISSUE TITLE
Web Chat in Internet Explorer 11 link broken

### ISSUE THREAD

**Issue by pfjtaylor** [MicrosoftDocs/bot-docs#1671]
Hi, in 'Browser Compatibility', the link for 'Web Chat in Internet Explorer 11' is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8fcc136-2176-535a-05f4-6423bfafbd67
* Version Independent ID: e0636491-0acf-5577-0313-80d3c9006131
* Content: [Web Chat overview - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-webchat-overview?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/bot-builder-webchat-overview.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-webchat-overview.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing out this broken link @pfjtaylor. I updated it in [PR 2086](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2086), the change should go live shortle. Here's a link to the [ES5 bundle](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/c.es5-bundle) and [demo](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/c.es5-bundle/) in the mean time.

**Comment by emgrol** [comment]
Closing now that changes are live.
