### ISSUE TITLE
Virtualenv

### ISSUE THREAD

**Issue by linceaerian** [MicrosoftDocs/bot-docs#1672]
Hello,
Should you not recommend to use a virtualenv in place of installing the pip packages ?

virtualenv -p `which python3` venv
source venv/bin/activate 

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a20df2-727c-1afd-2b87-836ea1ea4f7a
* Version Independent ID: 157fc262-fb1f-f12d-0890-e90119feb444
* Content: [Create a bot using Bot Framework SDK for Python - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/python/bot-builder-python-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/python/bot-builder-python-quickstart.md)
* Service: **bot-service**
* GitHub Login: @emgrol
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Hi @linceaerian, a virtual environment is recommended but not necessary. I'll add a suggestion to the article.

**Comment by emgrol** [comment]
Added a suggestion to use virtual environments in [PR 2096](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2096).

**Comment by emgrol** [comment]
Closing now that the changes are live.
