### ISSUE TITLE
At least one non-microsoft OAuth example should be included

### ISSUE THREAD

**Issue by Jay-study-nildana** [MicrosoftDocs/bot-docs#1673]
[Enter feedback here]

I just spent what seems like an entire day trying to get a simple google login to work for the bot framework with Google as a OAuth provider. If you dont want to use a non-Microsoft service, at least, include an example for Github login. 

I am surprised that the tutorial talks nothing about linking to a user flow on B2C., either really, just not cool :( I see this in a ton of other tutorials too. the authentication part is almost always ignored. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service - Bot Service](https://docs.microsoft.com/en-in/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by Jay-study-nildana** [comment]
Quick Update

I was able to get Google and GitHub working (not in the original tutorials). More details available here. 

https://github.com/microsoft/BotFramework-Emulator/issues/2134

However, these solutions bypass Azure B2C, which is what I really would like to use. If that can be included, especially linking to a user flow, (so then we can use any flow we want as per our requirement), that would be the best. I am also investigating how to make this happen on my own, and will post any code updates here once I have a solution.

**Comment by mmiele** [comment]
@Jay-study-nildana  My apologies for the long delay. 
I published a post that might answer your questions. Please, take a look at [Bot Authentication using GitHub as the Identity Provider](https://blog.botframework.com/2020/06/22/bot-authentication-using-github-as-the-identity-provider/).

**Comment by Jay-study-nildana** [comment]
@mmiele 

no apology neccessary at all :) thank you for the new post. I have currently moved away from this, building my own auth servers, but I will look into it. glad that the post is up and running now :)
