### ISSUE TITLE
Add Python

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/bot-docs#1676]
We should add a Python tab for these.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a7a652-1a73-79a8-515e-5d1cc1de47fb
* Version Independent ID: b1668900-477b-c2f6-9a06-33171bd911ab
* Content: [How bots for Microsoft Teams work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics-teams?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-basics-teams.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics-teams.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@clearab The fix is ready, pending your review (of PR 2162).

**Comment by JonathanFingold** [comment]
The fix will go live with the next push from master to live.
