### ISSUE TITLE
Does the Token Service handle token refreshing as well ?

### ISSUE THREAD

**Issue by garylirocks** [MicrosoftDocs/bot-docs#1679]
Hi, trying to understand how the Token Service works, the document says it caches a token, does it handle token refreshing as well ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf2089c-a313-0abf-2ed3-8d7db5c4f677
* Version Independent ID: f0b3a9ce-b1e3-7b3d-15a9-0b9e032aa4bd
* Content: [User authentication in the Azure Bot Service - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-authentication?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/bot-builder-concept-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-authentication.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
The Token Service does not auto-refresh expired tokens at this time.
