### ISSUE TITLE
How to Enable telemetry for Dispatcher LUIS model

### ISSUE THREAD

**Issue by Chekrii** [MicrosoftDocs/bot-docs#1680]
Hi All,

I have followed the documentation:- [Link][1] to enable telemetry in Dialogs and Luis application.
But the model we are using is Dispatcher Luis Model, so if I am using LuisRecognizerOptionsV3,
and enable telemetry, In [powerBI  dashboard][2] of Virtual assistant it is showing only Child Luis apps as Intent than the actual Intent.(example:- I_ChidLUISIntet than GenericGreetingHI, GenericGreetingBye)

So is there a way where I can Log child app LUIS top intents using for Dispatcher Model in the PowerBI template of Virtual assistant.

Code I am using to call Luis :
```
public virtual async Task<RecognizerResult> RecognizeAsync(string DispatcherEndpoint, ITurnContext turnContext, IBotTelemetryClient telemetryClient, CancellationToken cancellationToken)
        { 
            LuisRecognizer  recognizer;
            var luisApplication = new LuisApplication(DispatcherEndpoint);
            var recognizerOptions = new LuisRecognizerOptionsV3(luisApplication)
            {
                
               IncludeAPIResults = true,
               TelemetryClient = telemetryClient,
                PredictionOptions = new Microsoft.Bot.Builder.AI.LuisV3.LuisPredictionOptions()
                {
                    IncludeAllIntents = true,
                    IncludeInstanceData = true,
                },
                LogPersonalInformation = true
            };
            recognizer= new LuisRecognizer(recognizerOptions);
            var LuisResuli=  await  recognizer.RecognizeAsync(turnContext, cancellationToken);
            return LuisResuli;
        }
 ```
Thanks

  [1]: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0#enabling-telemetry-to-capture-usage-data-from-other-services-like-luis-and-qna-maker
  [2]: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0#enabling-telemetry-to-capture-usage-data-from-other-services-like-luis-and-qna-maker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db892de5-e60e-1d4f-505b-11b1cdb73323
* Version Independent ID: f7263014-b8fa-9a20-71aa-e4217b2821ee
* Content: [Add telemetry to your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-telemetry.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-telemetry.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by dmvtech** [comment]
Hello @Chekrii 

I apologize for the long delay in a response to this. There was some unforeseen issues. Are you still needing assistance on this?


Anyhow, I would suggest taking a look at the [NLP sample](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/14.nlp-with-dispatch/Bots/DispatchBot.cs) and how it breaks down the dispatch intents from the child indents.

For example, there is a primary/main `DispatchToTopIntentAsync` that will be called to determine the child intents (essentially what you have), but then it will switch on that and call other/child intents. I believe the telemetry client can be implemented there to specifically trace the child/actual intents. Let us know if you still need help and I can see if I can get a sample.

**Comment by dmvtech** [comment]
Closing. Let us know if you need further assistance.
