### ISSUE TITLE
Wrong link for conversationUpdate

### ISSUE THREAD

**Issue by manutero** [MicrosoftDocs/bot-docs#1681]
At **Additional resources**, the link **conversationUpdate** is pointing to `https://docs.botframework.com/node/builder/chat-reference/interfaces/_botbuilder_d_.iconversationupdate.html` which ends up at the index page of the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec233fe-c1dc-ad1e-bc7c-33c8c9a3f317
* Version Independent ID: fa903c55-1449-e923-d107-3530e9a5b10b
* Content: [Handle user and conversation events  - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-handle-conversation-events?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/nodejs/bot-builder-nodejs-handle-conversation-events.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-handle-conversation-events.md)
* Service: **bot-service**
* GitHub Login: @ducvo
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Here's a link to [IConversationUpdate](https://docs.microsoft.com/en-us/javascript/api/botbuilder/iconversationupdate?view=botbuilder-ts-3.0). I'll fix the article.

**Comment by JonathanFingold** [comment]
PR 2144 will fix the broken links. Thanks.
