### ISSUE TITLE
Errors following Connecting a bot to Twilio

### ISSUE THREAD

**Issue by BetaLixT** [MicrosoftDocs/bot-docs#1682]
I'm following the connecting to a bot to twilio document

> https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-twilio?view=azure-bot-service-4.0

I managed to install the Microsoft.Bot.Builder.Adapters.Twilio nuget package however when I try creating the controller this line 
`await _adapter.ProcessAsync(Request, Response, _bot);`
Gives me an error saying
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'cancellationToken' of 'TwilioAdapter.ProcessAsync(HttpRequest, HttpResponse, IBot, CancellationToken)'	EchoBot	C:\Users\<username>\Desktop\02.echo-bot\Controllers\BotController.cs	59	Active
`
Did I do something wrong? Is there a work around?

**Comment by v-kydela** [comment]
Thank you for the questions, @BetaLixT 

It seems the code snippet in the doc will not work after this commit from November: https://github.com/microsoft/botbuilder-dotnet/commit/1c5b14e84bccbca4ee879053d63aedb22b1bd585

That means it the code snippet is for package versions earlier than 4.7.0. It's unclear if the change should be reverted or if the doc should be updated. @garypretty - Can you comment?

In the meantime, I suspect you will be fine if you follow [the code in the samples repo](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/63.twilio-adapter/Controllers/TwilioController.cs):

```c#
await _adapter.ProcessAsync(Request, Response, _bot, default(CancellationToken));
```

**Comment by BetaLixT** [comment]
Hi thank you for the reply, I did find this earlier and can confirm that it works as expected

**Comment by v-kydela** [comment]
@emgrol - If we want to fix these docs, do we merge into live or live-sync-work?

**Comment by garypretty** [comment]
@BetaLixT Thanks for flagging this issue.  As pointed out above, there were some changes made to the adapter in November and the docs do need updating to reflect this.  Also, another thing to clarify, is that the adapters (Twilio / Facebook / Slack) are currently still in preview. 

The 4.8 and 4.9 adapter packages reflected this with a -preview tag, but for some reason it would appear that the 4.7 package did not have this tag.  I wanted to ensure that you were aware of this.

We are not expecting any significant change in the adapters in terms of behavior, but there may be some minor changes between now and bringing them out of preview (hopefully in 4.10). Just something to be aware of as and when you update your packages.
