### ISSUE TITLE
Tip to subscribe to Bot Events in Slack is misleading

### ISSUE THREAD

**Issue by haacked** [MicrosoftDocs/bot-docs#1683]
In [the docs for adding a bot to Slack](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs), there's the following tip.

> Your bot handle is the name of your bot. To find a bot's handle, visit Azure portal. Select the bot app service you created, and record the name of the bot.

This is misleading because the bot handle isn't in the _App Service_, it's in the _Settings_ pane for the __Bot Channels Registration__. It took me a while to realize this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by shram2k** [comment]
I am trying to use events for slack. I was following slack adapter using ngrok locally. After Enable Events toggle On, I was setting up Request Url as https://1940e052.ngrok.io/api/slack but slack portal says "Your URL didn't respond with the value of the challenge parameter.". Could you please help?

**Comment by emgrol** [comment]
Thanks for the suggestion @haacked, I'll add some clarifying language to that section.

@shram2k  Can you please file a separate issue? Your issue isn't related enough to this one to address it in a single issue.

**Comment by emgrol** [comment]
Closing now that changes are live.
