### ISSUE TITLE
New Workplace Bot

### ISSUE THREAD

**Issue by kesavanpurushothaman** [MicrosoftDocs/bot-docs#1684]
New custom integration app created in Workplace is disabled by Workplace citing Azure Bot Services is not supported now.

What are the steps to create new Workplace bot using this facebook adapter.? 
Please confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0199d414-87e1-e32d-b528-ee9d2e03c54e
* Version Independent ID: f88f4b08-0977-baee-5226-844695828b95
* Content: [Connect a bot to Facebook Messenger - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-facebook.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-facebook.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by kesavanpurushothaman** [comment]
![image](https://user-images.githubusercontent.com/43205631/81255559-8ebe3b00-904b-11ea-87bf-6f5fceca3116.png)
Reason from Workplace.

**Comment by JonathanFingold** [comment]
For now, you should use the Facebook custom adapter for Workplace bots. Currently, however, the custom adapter is available only in the .NET SDK: `Microsoft.Bot.Builder.Adapters.Facebook.FacebookAdapter`.

**Comment by kesavanpurushothaman** [comment]
Thanks for the update.
Post discussion with Workplace tech team, they won't allow any new integration with Azure Bot Framework even after using this Facebook Adapter. Is this true? Please confirm.

**Comment by JonathanFingold** [comment]
@kesavanpurushothaman I'm asking for confirmation within the team. I'll let you know as soon as I have a response.

**Comment by jameslew** [comment]
Hi @kesavanpurushothaman.  The reason we've moved developers from the Bot Service to the adapter is that it removes the service-to-service authentication dependency until we can rewrite the Bot Service to use their new authentication path.

The Adapter does not depend on that authentication mechanism, so I'm unaware of any other reason that you'd be unable to use the SDK + Adapter in your bot to interact with Facebook.  IE you're not using us as a platform in this solution just as some open source running within your own context.

If that's not the case I'd be happy to follow up further.

**Comment by kesavanpurushothaman** [comment]
Thanks for the update - this will open up our doors.
I hope the same mechanism is applicable common to both Facebook and Workplace.

I request you to help me with the below two queries.

> Also, I could see the .Net Facebook Adapter Package is still in preview. Can we use it for our Production bot?

> The URL we are going to configure in Custom Integration of Workplace - should that necessarily an custom URL from our domain or .azurewebsites is also allowed.

Thank you.

**Comment by jameslew** [comment]
Hi @kesavanpurushothaman .  You should be able to use for both.  That said, your bot should also be able to load the bot framework adapter and the facebook for workplace adapter as well so that you can handle requests through whatever path they arrive.

The adapter is in preview as they determined there was a change that needed to be made that would slightly adjust the signature (ie it wouldn't be compile time backward compatible).  You can get the new signature now in the daily builds, and it will finalize in a GA build in about 5 weeks.

The URL should be whatever domain you prefer, so long as you can apply whatever security requirements Facebook might require to that URL (certs or whatever).  They may have no such requirements.

**Comment by kesavanpurushothaman** [comment]
Thanks for the update. Will work on the integration using the Facebook Adapter Preview Package and request if there are any issue.

**Comment by kesavanpurushothaman** [comment]
Hi, We started testing the Workplace Bot using the Facebook Adapter Package you have suggested and found that Cards are not rendered in the Chat.
Earlier in Bot Service FB Channel, Adaptive Cards without actions are down rendered as Images, but using this Adapter approach Cards are not rendering (not even as image). Can you please help me on this issue?
