### ISSUE TITLE
System.Net.WebSockets.WebSocketException: 'Unable to connect to the remote server' when connecting to standalone Azure App Service (bot application)

### ISSUE THREAD

**Issue by js1016** [MicrosoftDocs/bot-docs#1686]
I followed the document to create the .NET client to connect to Direct Line App Service Extension.
It works fine with my Web App Bot where its App Service was created as a template when I created the Web App Bot: (https://joji-load-test-bot.azurewebsites.net/.bot/)

But it throws error: System.Net.WebSockets.WebSocketException: 'Unable to connect to the remote server' when connecting to a standalone Bot App Service which was created using below steps:

1. Create App Service on Azure Portal.
2. Create local EchoBot project from Bot SDV V4 template, deploy it to Azure App Service
2. Create a Bot Channel Registration, link it to the standalone Bot App Service I created before: https://joji-bot.azurewebsites.net/api/messages
4. Ensure the EchoBot is working fine in "Test in WebChat"
5. Configure all the settings that are required for DirectLine extension: enable Web Socket, configure the variables...
6. Access https://joji-bot.azurewebsites.net/.bot and get expected result: {"v":"1.0.0.0.55fa54091a1e3b168628d4000ee2b06a88bbc2ac","k":true,"ib":true,"ob":true,"initialized":true}
7. Connect to https://joji-bot.azurewebsites.net/.bot in console application and get error: System.Net.WebSockets.WebSocketException: 'Unable to connect to the remote server'

Is there any configuration I am missing here for standalone Bot App Service that was not created through Web App Bot template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c463a003-c709-b516-ce1b-6c45537de3b2
* Version Independent ID: 8ca42668-23ac-6dca-054d-d183b0fb5b0b
* Content: [Create .NET client for direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-client.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-client.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by stevkan** [comment]
@js1016, are you still needing assistance with this issue? If so, in item #7, which console application are you using? Also, `https://joji-bot.azurewebsites.net/.bot` isn't the messaging endpoint. Instead, you should be connecting to your bot using `https://joji-load-test-bot.azurewebsites.net/api/messages` in order to send messages.

The `/.bot` endpoint is part of the DL ASE API used for requesting a token as well as setting the domain in your `DirectLine.DirectLine()` object in Web Chat.

**Comment by js1016** [comment]
> @js1016, are you still needing assistance with this issue? If so, in item #7, which console application are you using? Also, `https://joji-bot.azurewebsites.net/.bot` isn't the messaging endpoint. Instead, you should be connecting to your bot using `https://joji-load-test-bot.azurewebsites.net/api/messages` in order to send messages.
> 
> The `/.bot` endpoint is part of the DL ASE API used for requesting a token as well as setting the domain in your `DirectLine.DirectLine()` object in Web Chat.

Of course I know the `/.bot` isn't the endpoint. If you follow the steps, you can reproduce the issue. But never mind, my customer chose to create the Bot using template rather than Bot Channel Registration, closing this issue.
