### ISSUE TITLE
Azure BotService serves adaptive card png at public url when sent to Slack(and probably other channels rendered to png as well)

### ISSUE THREAD

**Issue by adamist521** [MicrosoftDocs/bot-docs#1688]
I am sending Adaptive card to Slack via Azure Bot Service.
Problem is that adaptive-card rendered image is served publicly when Azure bot service sends adaptive-card image to Slack.

Is there anyway I could secure information sent via adaptive card so that only people who can see the image is the people who can see it on Slack?
I thought it should be at least mentioned at document.

Following should be the step which Azurebotservice sends adaptive-card to Slack.

1. Azure Bot service renders adaptive card to PNG and serves png in following url format.
https://slack.botframework.com//v3/attachments/[token?]/views/original
2. Azure bot service converts adaptive card to block-kit message and send it slack.
3. Slack receives public url of image and render at block-kit

I know there is restriction on block-kit message that it only accepts public url but I can't use Bot service adaptive-card rendering until this issue is solved...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=adapter)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by v-kydela** [comment]
Thank you for the question, @adamist521 

I understand that you're trying to send an Adaptive Card to Slack and you're okay with the card getting converted to an image but you're not okay with this image having a public location. Is there a reason you want to use Adaptive Cards here, which you can see Slack does not support? Why not just use a Bot Framework card that doesn't get converted to an image?

**Comment by v-kydela** [comment]
@adamist521 - Are you still working on this?

**Comment by adamist521** [comment]
@v-kydela 
sorry for late response.

I wanted to use adaptive card because I'm already sending same thing to teams and wanted the changes to be minimum when supporting slack platform.

I just did a work around by following. 
- convert adaptive card to html 
- covert html to png
- upload to slack as png (this way requires slack authentication to see image)
- send actions via blockkit json


Could you give me example links for the cards which wouldn't be rendered as image?
I think I'm not exactly following what you are talking about...

**Comment by v-kydela** [comment]
If you're using the Azure Bot Service and not the Slack adapter, you can send hero cards etc. to Slack and they will automatically be converted to Slack blocks.

Here is an old document explaining Bot Framework rich cards: https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-cards.md

You can find more information and links to card samples here: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments

I'm glad you resolved your issue.
