### ISSUE TITLE
Instructions for multitenant apps are incorrect

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/bot-docs#1690]
"When creating the Azure AD app if you selected either Accounts in this organizational directory only (Microsoft only - Single tenant) or Accounts in any organizational directory(Microsoft Azure AD directory - Multi tenant) enter the tenant ID you recorded earlier for the AAD app."

- For "Accounts in any organizational directory", this won't work, because this will ask the user in the other tenant log in to the tenant that the app was registered in, and they don't have an account in that tenant. That is, if the app was registered in the Contoso tenant, the hypothetical user user@northwindtraders.com will be taken to login.microsoftonline.com/contoso.onmicrosoft.com, and they won't be able to log in as "user@northwindtraders.com".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp#azure-ad-v2-1)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@aosolis Thank you for discovering this incorrect statement. Would you mind to suggest what could be a better description that would fix the issue? Thanks

**Comment by mmiele** [comment]
Fixed the information in the listed article explaining the use the "tenant ID". The updated documentation will be in the next available build.
