### ISSUE TITLE
Instructions Aren't Working

### ISSUE THREAD

**Issue by EddieGranados** [MicrosoftDocs/bot-docs#1691]
Create a bot section requires to install -r requirements.txt but file hasn't been placed in folder and this throws an error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=python%2Ccsharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Hi @EddieGranados, I can see the steps are out of order. You need to run `pip install -r requirements` _after_ your bot has been created. I updated the article in [PR 2096](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2096) to address the confusing steps. The changes should go live soon.

**Comment by emgrol** [comment]
Closing now that changes are live.
