### ISSUE TITLE
Section Update, Step 3 Isn't working

### ISSUE THREAD

**Issue by EddieGranados** [MicrosoftDocs/bot-docs#1692]
It is asking to modify  BOT = MyBot() to BOT = MyBot(APP.config), causing an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=python#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by mjmlp** [comment]
I have the same problem, if I don't edit this section I still get an error TypeError: __init__() missing 1 required positional argument: 'config'

**Comment by zxyanliu** [comment]
@mjmlp and @EddieGranados Thanks for reporting the issue. We are currently working on it. 
Also, FYI. We have a QnA bot sample in Python here: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/python/11.qnamaker

**Comment by zxyanliu** [comment]
The content is updated and will be live soon. Thanks!
