### ISSUE TITLE
Outdated content

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/bot-docs#1698]
The repositories linked to in the sections described below all appear to be dead projects. I believe these sections should be removed from this doc:

- [x] What are some community-authored dialogs?
  - BotAuth - Azure Active Directory authentication
  - BestMatchDialog - Regular expression-based dispatch of user text to dialog methods
- [x] What are some community-authored templates?
  - ES6 BotBuilder - ES6 Bot Builder template

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253d4e99-7fc5-cc8d-5b07-29bf2d78687a
* Version Independent ID: cdc0528d-cf1a-e015-1d8a-31ed062648f8
* Content: [Bot Service Frequently Asked Questions - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0#what-keeps-my-bot-secure-from-clients-impersonating-the-bot-framework-service)
* Content Source: [articles/bot-service-resources-bot-framework-faq.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-resources-bot-framework-faq.md)
* Service: **bot-service**
* GitHub Login: @scheyal
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@clearab , do we have replacement content, or should I just remove these two topics from the FAQ?

**Comment by clearab** [comment]
I'm not sure, I think they are just dead? @sgellock do you know what these are?

**Comment by clearab** [comment]
@tomlm do you know what these are?

**Comment by JonathanFingold** [comment]
🦗 🦗 @tomlm or @sgellock do we have replacement content, or should I just remove these two topics from the FAQ?

**Comment by JonathanFingold** [comment]
Just commenting out the two questions for now (in PR 2278). Let me know if there is ever some replacement content to add in its place.

**Comment by JonathanFingold** [comment]
Just removed the questions from the FAQ.
