### ISSUE TITLE
Standard way to have dispatch work for 2 languages

### ISSUE THREAD

**Issue by pranjalpandey22** [MicrosoftDocs/bot-docs#1699]
Hey, I have a LUIS app and 2 QnAMaker resources. The second QnAMaker resource has language culture of Arabic - I want to know the best practices when it comes to managing such an architecture using dispatch. I know that dispatch itself is a LUIS app with its own culture, hence I can't simply use a single dispatcher which sits on top of the 3 aforementioned resources. 
Kindly let me know!

**Comment by JonathanFingold** [comment]
The new adaptive dialogs have support for multiple locales. See [Introduction to adaptive dialogs](https://docs.microsoft.com/azure/bot-service/bot-builder-adaptive-dialog-introduction) and [Recognizers in adaptive dialogs](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-adaptive-dialog-recognizers). We don't yet have a multi-language sample, but you could request one by opening **Samples Feature request** in the [Samples repo](https://github.com/microsoft/BotBuilder-Samples/issues).

Beyond that, I'm not certain how to accomplish the same thing using dispatch.

**Comment by v-kydela** [comment]
@pranjalpandey22 - Can you give us more information about what you're trying to do? Are the other two resources in English? Will the bot know which language the user is communicating with, or are you asking how to perform language detection? Since this is the docs repo, can you link to the specific document that led you here?

**Comment by v-kydela** [comment]
@pranjalpandey22 - Are you still working on this?

**Comment by pranjalpandey22** [comment]
Hey, apologies for being away!

I setup 2 separate dispatchers, one for English and the other for Arabic. I
am triggering them by using Microsoft Text Analytics API's Language
detection which returns the language ID in real time.
So far things have worked just fine!

**Comment by v-kydela** [comment]
@pranjalpandey22 - I'm glad to hear it. I will close this issue now.
