### ISSUE TITLE
unable to start API server using this code let server = restify.createServer();

### ISSUE THREAD

**Issue by satheeshWMS** [MicrosoftDocs/bot-docs#1702]
node version 10.14.0 

```json
    "bluebird": "^3.4.7",
    "botbuilder": "^3.30.0",
    "botbuilder-azure": "^4.9.0",
    "dotenv-extended": "^1.0.4",
    "restify": "^4.3.0"
```

```js
var adapter = new botbuilder.BotFrameworkAdapter({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword
});
 
// Create HTTP server.
let server = restify.createServer();
server.listen(3978, function () {
    console.log(`\n${server.name} listening to ${server.url}`);
    console.log(`\nGet Bot Framework Emulator: https://aka.ms/botframework-emulator`);
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96480c73-7d45-884e-ba91-41597d465da0
* Version Independent ID: e677d278-e69f-bff7-0db3-3dc0835aa136
* Content: [Bot Framework SDK for Node.js - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-overview?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/nodejs/bot-builder-nodejs-overview.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-overview.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by v-kydela** [comment]
Hello @satheeshWMS 

You've said that you're unable to start an API server using the code `let server = restify.createServer();`. Can you explain what you mean by that? What happens when you try it? Are you getting an error message? Have you imported `restify` in that JavaScript file?

**Comment by v-kydela** [comment]
@satheeshWMS - Are you still working on this?

**Comment by satheeshWMS** [comment]
Right Now no
