### ISSUE TITLE
Outdated "Python samples for Bot Framework SDK"

### ISSUE THREAD

**Issue by tracyboehrer** [MicrosoftDocs/bot-docs#1705]
The document at:

https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-samples?view=azure-bot-service-4.0

Refers to outdated info.  Python Preview instructions.

**Comment by JonathanFingold** [comment]
Fix is in PR. I've [fully] retired this page and redirected to the samples repo, which is what the node in the current TOC does.
