### ISSUE TITLE
Unclear what you mean by UUID

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1706]
Under [Test your bot locally](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-inspection-middleware#test-your-bot-locally) it says:

> 4. At this point you will see a UUID (`/INSPECT attach <identifier>`) in your debugging emulator. Copy the UUID and paste it to the chat box of the first emulator. 

I am interpreting UUID as GUID, which would mean the 16-byte identifier. Pasting the UUID does not seem to have an effect on the debugger. Did you mean for us to paste the entire command rather than just the UUID?

You might have meant to imply that the entire command including the `/INSPECT attach` _is_ the UUID, but that would be misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3680526e-63bf-e7a8-9bef-355562590bdd
* Version Independent ID: bd094bae-f4f6-c1c6-3039-23254129c495
* Content: [Debug a bot with inspection middleware - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-inspection-middleware?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-service-debug-inspection-middleware.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-debug-inspection-middleware.md)
* Service: **bot-service**
* GitHub Login: @zxyanliu
* Microsoft Alias: **v-liyan**

**Comment by zxyanliu** [comment]
Hi @v-kydela 
Thanks for reporting the issue. Let me look into it (has been a while...) and get back to you soon.

**Comment by zxyanliu** [comment]
@v-kydela I think both UUID and GUID are 128-bit (16-byte) numbers and they seem to be quite similar. However, I saw some [comments on their similarities/differences](https://stackoverflow.com/questions/246930/is-there-any-difference-between-a-guid-and-a-uuid) where people say that "In Microsoft-speak they are called GUIDs, but call them UUIDs when not using Microsoft-speak". 

To avoid confusion to the readers, I think it's a good idea to change the term to be less technical such as "A unique ID number" instead of "UUID" or "GUID"? or what do you suggest? 

Thanks and please let me know so that we do not confuse our readers.

**Comment by v-kydela** [comment]
Now that you've clarified that UUID and GUID do indeed mean the same thing, I am unconcerned with which one you pick. But the screenshot in step 5 shows the debugger window. It does not show anything having been pasted anywhere.

**Comment by zxyanliu** [comment]
I was wondering if you see step  4. 
> At this point you will see a UUID (/INSPECT attach <identifier>) in your debugging emulator. Copy the UUID and **paste it to the chat box of the first emulator**. 
Did you paste it to the chat box of the first emulator?

**Comment by v-kydela** [comment]
@zxyanliu - Please read the step and my post more carefully. In the step it says "Copy the UUID" and not "Copy the whole command." In my post it says:

> Pasting the UUID does not seem to have an effect on the debugger. Did you mean for us to paste the entire command rather than just the UUID?

I understand that you are supposed to copy the command from the debugging Emulator and paste it into the first Emulator. I am trying to help you improve the misleading documentation that does not say to do that. You had mentioned that the screenshot shows what you're supposed to copy and paste, but it does not because it doesn't show the correct Emulator which you're supposed to paste something into. When you run the Emulator in debug mode, it doesn't even allow pasting. In order to disambiguate with a screenshot whether you're supposed to paste the UUID or the whole command, you'd need to show the window where the actual pasting has been done.

**Comment by zxyanliu** [comment]
Hey @v-kydela 
I am sorry for the confusion. I have made some updates in [PR2147](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2147). 

Thanks again for your report to help us improve. : -)

**Comment by zxyanliu** [comment]
Closing because the updated content is live. Thanks.
