### ISSUE TITLE
I get {"v":"*****","k":true,"ib":false,"ob":false,"initialized":true}

### ISSUE THREAD

**Issue by fifteenjoy** [MicrosoftDocs/bot-docs#1707]
[Enter feedback here]
After following the document.
I got 
{"v":"****","k":true,"ib":false,"ob":false,"initialized":true}
**ib and ob is false**

Can anyone tell me how to fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72c259-a864-9e1c-b585-562d6bca80ff
* Version Independent ID: 30a3fce8-d236-5c7b-88a0-003c971f2819
* Content: [.NET bot with direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by anusharavindrar** [comment]
@fifteenjoy, If everything is correct, the page will return this JSON content: {"k":true,"ib":true,"ob":true,"initialized":true}. This is the information you obtain when everything works correctly, where

**k** determines whether Direct Line App Service Extension (ASE) can read an App Service Extension Key from its configuration.
**initialized** determines whether Direct Line ASE can use the App Service Extension Key to download the bot metadata from Azure Bot Service
**ib** determines whether Direct Line ASE can establish an inbound connection with the bot.
**ob** determines whether Direct Line ASE can establish an outbound connection with the bot.

Can you double-check if you missed any of the steps? Did you save the settings in the app service configuration page?

**Comment by anusharavindrar** [comment]
@fifteenjoy, do you still need help?

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to reopen if the issue persists.

**Comment by jtg5122** [comment]
Hello.  I am having the same issue.  I've tried to repeat these steps multiple times.
