### ISSUE TITLE
Missing url that needed to be whitelisted

### ISSUE THREAD

**Issue by ammarh85** [MicrosoftDocs/bot-docs#1709]
Under he FAQ Question: "Which specific URLs do I need to whitelist in my corporate firewall to access Bot Framework services?"
There is a domain missing which we had to whitelist when trying to call the bot service:
 - login.windows.net

Assuming this domain too is needed and has to be whitelisted, it would be very useful to update this doc to reflect the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253d4e99-7fc5-cc8d-5b07-29bf2d78687a
* Version Independent ID: cdc0528d-cf1a-e015-1d8a-31ed062648f8
* Content: [Bot Service Frequently Asked Questions - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-resources-bot-framework-faq.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-resources-bot-framework-faq.md)
* Service: **bot-service**
* GitHub Login: @scheyal
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out @ammarh85. I added the url to the page, the change should go live soon.

**Comment by ammarh85** [comment]
Hello,

Thanks fro the update! Here are some of the additional URLs that I later
found and had to whitelist as well:

login.windows.net
 login.microsoft.com
 sts.windows.net
 smba.trafficmanager.net

**Comment by emgrol** [comment]
Closing now that changes are live.
