### ISSUE TITLE
Any nodeJS SSO sample

### ISSUE THREAD

**Issue by jonathanhotono** [MicrosoftDocs/bot-docs#1710]
Sample is only in C#. Anything for NodeJS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab060f59-0fc6-d90d-6b71-a0756f1a8aa0
* Version Independent ID: f7574aeb-0002-5e07-47ed-3d135a42f4ce
* Content: [Add Single sign on to a bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml#feedback)
* Content Source: [articles/v4sdk/bot-builder-authentication-sso.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication-sso.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by jonathanhotono** [comment]
Also with SSO, is it still required for user to click on the "sign in" card beforehand to perform the handshake on MS teams?

**Comment by JonathanFingold** [comment]
@jonathanhotono There is not yet a JavaScript/Node.js version of this sample. You can request one by filing a **Samples Feature request** issue in the [samples repo](https://github.com/microsoft/BotBuilder-Samples/issues).

**Comment by mmiele** [comment]
@jonathanhotono There is no time line yet for JavaScript/Node.js version. But it is on the TODO list. 
​Thank you for asking.
