### ISSUE TITLE
Documentation on Adaptive Dialogs has broken links to samples

### ISSUE THREAD

**Issue by haacked** [MicrosoftDocs/bot-docs#1712]
The link to the C# samples on the documentation [Create a bot using adaptive dialogs] has an incorrect link the C# and JavaScript samples.

The C# sample links to: https://github.com/microsoft/BotBuilder-Samples/tree/vishwac/r9/js/experimental/adaptive-dialog/csharp_dotnetcore/01.multi-turn-prompt

That link 404s. I assume it was supposed to link to https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/05.multi-turn-prompt

I tried to click "Edit this page" so I could submit a fix via a pull request, but the Edit This Page link is also broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f287f901-82a5-ab1f-20cf-647aca8eeb06
* Version Independent ID: 35231719-4d9e-f789-dd98-94ce09c0f45f
* Content: [Create a bot using adaptive dialogs   - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialogs-adaptive?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialogs-adaptive.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialogs-adaptive.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@haacked The problem has been solved. The fix will be in the next published documentation.  
Thank you for your feedback.

**Comment by mmiele** [comment]
@haacked The problem has been solved. The fix will be in the next published documentation.
Thank you for your feedback.
