### ISSUE TITLE
The instructions to copy the "id field to use as the value for the registration subscription id in the next step" is unclear.

### ISSUE THREAD

**Issue by hansonlam1** [MicrosoftDocs/bot-docs#1714]
There is the instruction:
"From the resulting JSON output, copy the value of the id field to use as the value for the registration subscription id in the next step."

It is unclear where this id is used in the subsequent steps.  I did not see anywhere where the registration subscription id is set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Yes, I agree, and thanks for reporting the confusion. The following is my understanding:

In [step 3-create-the-application-registration](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=javascript#3-create-the-application-registration), after you run the following command `az ad app create --display-name "displayName" --password "AtLeastSixteenCharacters_0" --available-to-other-tenants`, you will see a JSON output in your terminal. In the JSON file, you will find the **`appId`** value in the format of "00000000-0000-0000-0000-000000000000". 

Then, in [step-4-create-the-bot-application-service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=javascript#4-create-the-bot-application-service), you will need the `appId` value generated in step 3 to run the command to deploy via arm template. See the command: 

![image](https://user-images.githubusercontent.com/32497439/83102553-9af55100-a069-11ea-8479-fac5c8b09a45.png)

Please let us know if it helps. Thanks!

**Comment by zxyanliu** [comment]
Updated the content which will get live soon, so closing this issue. Thanks again for your report.
