### ISSUE TITLE
URL for testing the setup should be trailed with slash

### ISSUE THREAD

**Issue by compulim** [MicrosoftDocs/bot-docs#1715]
This URL in the doc is incorrect, https://<your_app_service>.azurewebsites.net/.bot. Instead, it should be, https://<your_app_service>.azurewebsites.net/.bot/.

The trailing slash is required because in the `web.config`, it has the trailing slash as well:

```
<add name="aspNetCore" path="*/.bot/*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 206a361d-42ef-ed02-9c1d-5775395aa7a9
* Version Independent ID: d122568b-a72e-7087-03db-a0aa386094b9
* Content: [Node.js bot with direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-node-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-node-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-node-bot.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **dev**

**Comment by emgrol** [comment]
Thanks for pointing this out @compulim. I fixed the path in the article, the change should go live soon.

**Comment by emgrol** [comment]
Closing now that changes are live.
