### ISSUE TITLE
Custom storage samples for Python, Node and Java

### ISSUE THREAD

**Issue by geo-msft** [MicrosoftDocs/bot-docs#1717]
[Enter feedback here]

Hi, 

I see that this page shows C# code for bots. 
I believe code samples for other languages in the bot builder SDK (such as Python, Java and Node.js) would be helpful. 

Thank you. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 409c8f0a-6388-574b-5443-a09c160962a7
* Version Independent ID: efc9e777-18e8-bcf2-204e-b395ce2e9f90
* Content: [Implement custom storage for your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-custom-storage?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-custom-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-custom-storage.md)
* Service: **bot-service**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
Agreed. Currently, we have a Python version of this sample, but not a JavaScript one.
- I'll look at adding Python to the current article.
- I'll open an issue in the samples repo to add a JavaScript sample.

**Comment by JonathanFingold** [comment]
I've also opened samples issue [2435](https://github.com/microsoft/BotBuilder-Samples/issues/2435),
as the Python and C# samples have discrepancies.

**Comment by JonathanFingold** [comment]
Unfortunately, samples for this in other languages have not been prioritized by the dev team. Please open an issue in the [Microsoft/BotBuilder-Samples](https://github.com/Microsoft/BotBuilder-Samples) repo to help prioritize this.
