### ISSUE TITLE
Botframework Authentication page: males -> makes

### ISSUE THREAD

**Issue by michal-turzynski** [MicrosoftDocs/bot-docs#1718]
In the below sentence,  change 'males' to 'makes'

> When a User.Id is provided while exchanging a secret for a token, that User.Id is embedded in the token. DirectLine males sure the messages sent to the bot have that id as the activity's From.Id.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd0bdf8-7cb8-1f26-65a1-3876ea84351f
* Version Independent ID: bda6ce3a-f006-baaf-db50-82bd79afa6ab
* Content: [Authentication - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-3.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-authentication.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @michal-turzynski Thanks for your report! A nice catch!
I have fixed it in [PR2155](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2155) and the content will go live soon.
