### ISSUE TITLE
What does "Suggestions" mean?

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1719]
Can the samples be cleaned up a bit? In most cases it looks like an activity structure is supposed to follow the activity schema but activities have no `Suggestions` property.

```
# AskForAge.prompt
[Activity
> With '|' you are making attachments a list.
        Attachments = ${HeroCard()} |
> You can use '\' as an escape character
        Suggestions = 10 \\| cards | 20 \\| cards
]
```

This property also shows up in the [example](https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/StructuredTemplate.lg) from the .NET repo. What does it mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2461558-78a0-8e49-f407-4e3e26576d86
* Version Independent ID: 12312202-7838-137c-22d9-ae24feb43b87
* Content: [Structured response template - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/language-generation/language-generation-structured-response-template?view=azure-bot-service-4.0)
* Content Source: [articles/language-generation/language-generation-structured-response-template.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/language-generation/language-generation-structured-response-template.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
The activity schema seems to indicate that [suggested actions](https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#suggested-actions) can be a payload on a message activity. However the section you cite in the article doesn't describe how this will render. I think the `\\|` might be a markdown error. I will investigate.

**Comment by v-kydela** [comment]
@JonathanFingold - Are you saying `Suggestions` is an alias for `SuggestedActions`?

**Comment by JonathanFingold** [comment]
I am not yet up to speed on LG templates, but that is my...belief. I will test the template before updating the article.

**Comment by JonathanFingold** [comment]
@v-kydela - @emgrol will work on this, as there are many issues in the current set of samples.

**Comment by emgrol** [comment]
Initial fixes are in [PR 2258](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2258).

**Comment by v-kydela** [comment]
@emgrol - I can see that you've deleted a few backslashes, but what about the question of what Suggestions means?

**Comment by emgrol** [comment]
@v-kydela I fixed the mentions of Suggestions to SuggestedActions. Closing now that the updates are live.
