### ISSUE TITLE
Adaptive card input controls not rendering in WeChat integration

### ISSUE THREAD

**Issue by chandermi** [MicrosoftDocs/bot-docs#1720]
Hi ,

We are creating an IBot to integrate with WeChat. The normal adaptive cards are rendering fine but not with the submit buttons and Input controls 

Below is the json we have created which is working fine on adaptive designer but not with WeChat app.

{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.2",
  "fallbackText": "Click to view",
  
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": 2,
          "items": [
            {
              "type": "TextBlock",
              "text": "Update BAQ : erpcool_02",
              "weight": "Bolder",
              "size": "Medium"
            },
            {
              "type": "Container",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "Company",
                  "wrap": true
                },
                {
                  "type": "Input.Text",
                  "id": "OrderHed_Company",
                  "placeholder": "Company"
                }
              ]
            },
            {
              "type": "Container",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "OrderNum",
                  "wrap": true
                },
                {
                  "type": "Input.Number",
                  "id": "OrderHed_OrderNum",
                  "placeholder": "OrderNum"
                }
              ]
            },
            {
              "type": "Container",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "OrderHeld",
                  "wrap": true
                },
                {
                  "type": "Input.Toggle",
                  "id": "OrderHed_OrderHeld",
                  "placeholder": "OrderHeld"
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Submit"
    }
  ]
}

---
#### Document Details
* ID: 3a26d6f7-2453-f514-a812-f87916b6c724
* Version Independent ID: 806e3815-cee0-cfc7-9af5-e3a23270644c
* Content: [Connect a bot to WeChat - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-wechat?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-wechat.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-wechat.md)
* Service: **bot-service**
* GitHub Login: @seaen
* Microsoft Alias: **egorn**

**Comment by zxyanliu** [comment]
@seaen I was wondering if you could help with this issue. Should Adaptive Card work with WeChat app in this case? Thanks a lot!

**Comment by zxyanliu** [comment]
Hi @chandermi, Adaptive Cards will not work in this case. You can read Adaptive Card support in [this article](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#card-support-by-channel) and Adaptive Card docs [here](https://docs.microsoft.com/en-us/adaptive-cards/resources/partners).
