### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by roberi** [MicrosoftDocs/bot-docs#1721]
The link  05.a.multi-turn-prompt-with-language-fallback sample is broken (https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/language-generation/csharp_dotnetcore/05.a.multi-turn-prompt-with-language-fallback). It leads to a 404 page on GitHub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59573a90-7a7a-418c-f661-90f53a00e47d
* Version Independent ID: cec084c0-0823-0c68-887c-bc660ac109cc
* Content: [Language Generation - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-language-generation?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-concept-language-generation.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-language-generation.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for letting us know @roberi. Here is the [link to the sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/language-generation/05.a.multi-turn-prompt-with-language-fallback).

**Comment by emgrol** [comment]
Closing now that the changes are live.
