### ISSUE TITLE
Dispatch model not returning correct intents

### ISSUE THREAD

**Issue by kellyhopkins** [MicrosoftDocs/bot-docs#1722]
Hi,
I'm not sure if this is the proper channel for this but I'm having trouble with the dispatch model after following the "Use multiple LUIS and QnA models" page. I set everything up, but instead of getting 'l_HomeAutomation' or 'q_sample-qna' as the value being passed to the intent variable in the switch case, I'm getting the top intent value from the LUIS response instead. This results in an error message from the emulator saying 'Dispatch unrecognized intent.' Do I need to tweak the template code at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by anusharavindrar** [comment]
@kellyhopkins, can you attach a screenshot of the error on the emulator? Do you get any additional information when you click on the log item to inspect activity on the emulator? Also, can you double-check if you missed any of the steps mentioned in the documentation?

**Comment by anusharavindrar** [comment]
@kellyhopkins, are you still working on this?

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to reopen if the issue persists.
