### ISSUE TITLE
Issues validating during deployment - Are these instructions outdated?

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/bot-docs#1724]
Something appears to be wrong with either the steps outlined here, or the ARM template that gets packaged with the samples.

Or

Something is wrong with the underlying validation check within Azure.

I can manually deploy these services just fine, but using the steps and template included with the bot sample I get the following error when attempting to deploy to an EXISTING app service plan

`{'additionalProperties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'Nymbus' is not valid according to the validation procedure. The tracking id is 'cd282e74-c315-4734-aee0-30126022bd5b'. See inner errors for details.", 'target': None, 'details': [{'additionalProperties': {}, 'code': 'ValidationForResourceFailed', 'message': "Validation failed for a resource. Check 'Error.Details[0]' for more information.", 'target': None, 'details': [{'additionalProperties': {}, 'code': 'ServerFarmNotFound', 'message': 'The specified app service plan was not found.', 'target': None, 'details': None, 'additionalInfo': None}], 'additionalInfo': None}], 'additionalInfo': None}`

Nymbus definitely exists as a service plan. I also tried to feed ID as opposed to name to try and satisfy the parameter but got this error:

`{'additionalProperties': {}, 'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'The template resource '/subscriptions/<GUID-purposfully-obfuscated>/resourceGroups/thinkbusy/providers/Microsoft.Web/serverfarms/nymbus' for type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Common.Entities.TemplateGenericProperty`1[System.String]' at line '83' and column '47' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'.", 'target': None, 'details': None, 'additionalInfo': [{'additionalProperties': {}, 'type': 'TemplateViolation', 'info': {'lineNumber': 83, 'linePosition': 47, 'path': 'properties.template.resources[0].type'}}]}`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @jebalert Thanks for reporting the issue. Let me make sure I understand your question: 

Did you try to deploy a [sample bot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples) via ARM template to an existing resource group and service plan (Nymbus) and get the error you listed above? 

FYI. When you run the following command, make sure you provide the path to the template-with-preexisting-rg.json file, e.g. the path may look like this: 
C:\Users\02.echo-bot\DeploymentTemplates\template-with-preexisting-rg.json

This is the command: 
```
az group deployment create --resource-group "<name-of-resource-group>" --template-file "<path-to-template-with-preexisting-rg.json>" --parameters appId="<app-id-from-previous-step>" appSecret="<password-from-previous-step>" botId="<id or bot-app-service-name>" newWebAppName="<bot-app-service-name>" existingAppServicePlan="<name-of-app-service-plan>" appServicePlanLocation="<region-location-name>" --name "<bot-app-service-name>"
```

**Comment by jebalert** [comment]
Hi @zxyanliu I was able to deploy to a new app service plan, but not an existing one. So my path was correct when I executed. Have you recently tried to deploy to an existing app service plan with the provided templates in a sample bot? Also.. experiencing some major bugs now that I've got my bot deployed. Will open an issue on that in the sdk.

**Comment by zxyanliu** [comment]
Hey @jebalert, I just tried, and got an error: `Azure Error: InvalidTemplateDeployment`, how did you solve it? Please let me know so that I can update the doc. Thanks a lot!

**Comment by zxyanliu** [comment]
@jebalert The bug was just fixed and nothing needs to be updated in the doc at this moment. Thanks again for your report.
