### ISSUE TITLE
No `ResourceResponse` object for `POST /v3/conversations/{conversationId}/activities` request

### ISSUE THREAD

**Issue by siddharthpant92** [MicrosoftDocs/bot-docs#1726]
[Enter feedback here]
When attempting to send a POST request to create a conversation using the `POST /v3/conversations/{conversationId}/activities` request (https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#send-to-conversation) with a `card attachment object` and a `text` field in the request body, i get a 202 response code. The card and the text message gets sent to the users chat, but we don’t get any response object in postman once the request is successful. 
If i remove the card attachment and send only a text message then i get a valid response object.
Similarly if i remove the text field and send only a card attachment object then i get a valid response object.
Could you provide some clarification on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36ddb50-9e44-96e3-2df3-174166efa75d
* Version Independent ID: 68ac4b64-6616-2216-3519-e0b33d3a53e4
* Content: [API reference - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#send-to-conversation)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @siddharthpant92 Thanks for your feedback. Let you know that we are currently investigating your issue and will get back to you soon. : -)

**Comment by v-kydela** [comment]
@siddharthpant92 - This is expected behavior in Teams. What channel are you using?

**Comment by v-kydela** [comment]
@siddharthpant92 - Are you still working on this?

**Comment by siddharthpant92** [comment]
@v-kydela We have used a work-around. But it would be nice if we can get some response message along with the 202 status code.

**Comment by v-kydela** [comment]
@siddharthpant92 - Yes that would be nice, but right now the schema is only set up to include one ID in a resource response. Teams expects you to send only text or only attachments in a message, and if you include both then it will split them into multiple activities with a different ID for each. If you'd like the behavior to change then you can provide feedback through Teams directly. I will close this issue now.
