### ISSUE TITLE
"Create dispatch model" question: Do I have the actual authoring key?

### ISSUE THREAD

**Issue by oldnathan47** [MicrosoftDocs/bot-docs#1728]
[Enter feedback here]

Hello!

I am trying to create the dispatch model, but my terminal is stuck. I'm thinking that I may have the wrong Authoring key, since the directions for where to find the key do not follow on the Luis portal. The instructions say, "From the 'Key and Endpoints' page, record the values Authoring Key as "your-luis-authoring-key" and Region as "your-region". However, there is no Key and Endpoints page on the Luis portal, and nothing in the settings section specifically identifies an authoring key. 

This is what I put into my terminal: 

dispatch init -n main.dispatch --luisAuthoringKey "my-luis-primary-key" --luisAuthoringRegion westus

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by JonathanFingold** [comment]
I'll take a look and update the article to match the latest iteration of the LUIS portal.

**Comment by JonathanFingold** [comment]
The updated topic should be live today or tomorrow. Please let me know if you need more help accessing LUIS from a bot.

**Comment by oldnathan47** [comment]
Do you think it will be up soon? I see it has not been updated yet.

**Comment by JonathanFingold** [comment]
I updated the [LUIS](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-v4-luis) article and failed to get the changes into the Dispatch article. Sorry about that. I'll update the Dispatch one this week.

**Comment by JonathanFingold** [comment]
The Dispatch article has been updated internally. The content should go live in a few days.

**Comment by JonathanFingold** [comment]
The changes should show up on the live today, once the server cache updates.
