### ISSUE TITLE
How to force webchat version when embedding ?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/bot-docs#1729]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/bot-docs.fr-fr/issues/5

@Gullfaxi171 commented 7 hours ago
Hi,

the provided embed link :
`<iframe src="https://webchat.botframework.com/embed/YOUR_BOT_ID?s=YOUR_SECRET_HERE"></iframe>`
forces the webchat version at 4.6.0, which misses some features. Is it possible to select within the url the used version of the webchat (for instantce 4.9.0 or 4.9.1 ?)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d54408c-bfbc-9d2c-a642-ec54f375475f
* Version Independent ID: 5b06e016-1aa8-a13b-179c-ec6700b8287c
* Content: [Connect a bot to the Web Chat channel - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-webchat.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-webchat.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Researching.

**Comment by mmiele** [comment]
@CeciAc The needed information can be found at this location: [What URL parameters are supported?](https://github.com/microsoft/BotFramework-WebChat/tree/master/packages/embed#what-url-parameters-are-supported).
