### ISSUE TITLE
option 1 in embed web chat control also reveals the secret key

### ISSUE THREAD

**Issue by asp1egui** [MicrosoftDocs/bot-docs#1730]
Hi ,
using the option 1 in this example also shows the secret key and to see that you just need to view the source code even though you could have prevented it using a web app(someone said that in gitter channel) even though the bot i build is a web app but with static html as the front side since i'm only doing it as a school project 😅. so now i ask if there is anyway to not show at all the secret key while using static html .

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d54408c-bfbc-9d2c-a642-ec54f375475f
* Version Independent ID: 5b06e016-1aa8-a13b-179c-ec6700b8287c
* Content: [Connect a bot to the Web Chat channel - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0#embed-the-web-chat-control-in-your-website)
* Content Source: [articles/bot-service-channel-connect-webchat.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-webchat.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@asp1egui. The steps described in option are not very clear. But they do advice to use a token instead of the secret key. That what you should be doing,. Take a look at this blog post it might be more useful for your project: [Connect a bot to Web Chat](https://blog.botframework.com/2020/06/28/connect-a-bot-to-web-chat/).
Let me know if it helps.

**Comment by asp1egui** [comment]
@mmiele yes, it did help. thanks for the answer

**Comment by mmiele** [comment]
Updated documentation.
