### ISSUE TITLE
What files do we need to zip up?

### ISSUE THREAD

**Issue by carlbm** [MicrosoftDocs/bot-docs#1731]
It's not at all obvious. Can you either link to a sample or let us know how to create/identify the files that need to be zipped?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
@carlbm Thanks for reporting the issue. As mentioned in the doc, you will need to manually zip the files in the [zip up the code directory manually step](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#52-zip-up-the-code-directory-manually). 

You need to select all the files and folders in your bot's project folder, and then, still in the bot's project folder, zip up all the selected files and folders.

For example: 
![image](https://user-images.githubusercontent.com/32497439/83956487-98d28580-a813-11ea-92d0-21c7c2f1ead4.png)

Then you will have a `.zip` file (the name may differ) such as this one: 

![image](https://user-images.githubusercontent.com/32497439/83956512-c15a7f80-a813-11ea-9c72-7441e32e0c7b.png)

After that, you can run the command to deploy your bot. 

Please let us know if it helps. Thank you.

**Comment by zxyanliu** [comment]
@carlbm Hey, did you get a chance to try as commented in the last thread? Please let us know if it helps. Thanks.

**Comment by zxyanliu** [comment]
Hey @carlbm any updates?

**Comment by viksing** [comment]
Hi, 
I did all the steps as mentioned here, or on main help page.
but I get this error.

Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
Configuring default logging for the app, if not already enabled
Zip deployment failed. {'id': 'efe5dafa95a840cba26352c3db41a507', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'ZipDeploy', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2021-11-19T16:48:41.9977292Z', 'start_time': '2021-11-19T16:48:42.1226719Z', 'end_time': '2021-11-19T16:48:52.3625298Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://xx-webapp.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://xx-webapp.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'xx-webapp', 'provisioningState': 'Failed'}. Please run the command az webapp log deployment show -n xx-webapp -g xx-rg


.deployment contains this
[config]
SCM_SCRIPT_GENERATOR_ARGS=--aspNetCore ".\xxxx.Bot.csproj"

command run is 

az webapp deployment source config-zip --resource-group "xxxx-rg" --name "xxxx-webapp" --src "xxx.zip"
