### ISSUE TITLE
Do we have a sample for WebChat client mode?

### ISSUE THREAD

**Issue by xieofxie** [MicrosoftDocs/bot-docs#1732]
Do we have a sample for `The following shows a normal and a fallback flow when using a WebChat client.`?

I have checked the code for VA(https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml) and it is very complex. Need a sample for how to do it in WebChat client mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 703a4f53-d548-76ed-8c8a-a1c8e6f17577
* Version Independent ID: 7311af4b-6943-fa86-ebb7-50f3bc9f39ba
* Content: [Single sign on Azure Bot Service - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-sso?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-sso.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-sso.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by xieofxie** [comment]
It seems this is quite close https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/07.advanced-web-chat-apps/e.sso-on-behalf-of-authentication

**Comment by mmiele** [comment]
@xieofxie Pleas look at this [sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/07.advanced-web-chat-apps/e.sso-on-behalf-of-authentication).

**Comment by xieofxie** [comment]
@mmiele yes, it worked. Maybe someone could update the link to the document. I will close this now.
