### ISSUE TITLE
documentation instructs to use deprecated azcli command

### ISSUE THREAD

**Issue by asdkant** [MicrosoftDocs/bot-docs#1734]
when running the `az group deployment create` command I get the following error:

> This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.

The deployments in the section "Deploy via ARM template (with existing Resource Group)" should use the `az deployment create` command instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=Python)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hey @asdkant Thanks for reporting this. This is a known issues and we are fixing in this PR: https://github.com/MicrosoftDocs/bot-docs-pr/pull/2172

**Comment by zxyanliu** [comment]
@asdkant The major changes are the following commands: 

`az deployment group create`
`az deployment sub create`

**Comment by zxyanliu** [comment]
The doc is updated and merged. The content will go live soon. Thanks!
