### ISSUE TITLE
Links to LG files in adaptive dialog docs are 404

### ISSUE THREAD

**Issue by FuzzAU** [MicrosoftDocs/bot-docs#1736]
In the "About the sample" section, there are links two two lg files, that are currently 404 as they refer to files in a specific branch that no longer exists.

"For C#, defined in RootDialog.lg"
Refers to: https://github.com/microsoft/BotBuilder-Samples/blob/vishwac/r9/js/experimental/adaptive-dialog/csharp_dotnetcore/01.multi-turn-prompt/Dialogs/RootDialog.lg

Likely better to be: https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/adaptive-dialog/01.multi-turn-prompt/Dialogs/RootDialog.lg

"For JavaScript, defined in userProfileDialog.lg (JavaScript)."
Refers to: https://github.com/microsoft/BotBuilder-Samples/blob/vishwac/r9/js/experimental/adaptive-dialog/javascript_nodejs/01.multi-turn-prompt/dialogs/userProfileDialog.lg

I was unable to find an appropriate equivilant in master for the javascript version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f287f901-82a5-ab1f-20cf-647aca8eeb06
* Version Independent ID: 35231719-4d9e-f789-dd98-94ce09c0f45f
* Content: [Create a bot using adaptive dialogs   - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialogs-adaptive?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialogs-adaptive.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialogs-adaptive.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing out the broken links @FuzzAU. You have the correct link for the C# file. Here is the link to the [JavaScript sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/adaptive-dialog/01.multi-turn-prompt).

I opened a PR with updates to the correct links to the files in PR [2240](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2240). The changes should go live soon.

**Comment by FuzzAU** [comment]
Thanks Emily, I was going to not be lazy and make a PR but couldn't find that second link.

Microsoft documentation is always great, so happy to help make it better!

**Comment by emgrol** [comment]
Thanks @FuzzAU, we appreciate the help!

Closing the issue now that the updated links are live.
