### ISSUE TITLE
Why do we have a location while creating bot channel registration app when bot services are global? What does the location do?

### ISSUE THREAD

**Issue by prashantsoni** [MicrosoftDocs/bot-docs#1737]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c93f5e57-c662-644a-776d-b1dd112a3832
* Version Independent ID: f7bfec78-1f6b-fcb5-09da-138e27dcad58
* Content: [Create a Bot Channels Registration with Bot Service - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-quickstart-registration.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart-registration.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi @prashantsoni Thanks for your feedback. When you create a **Web App Bot** or a **Bot Channels Registration**, the location you specified in Azure portal are both locations of the Resource Group you are creating. However, Azure Bot Services may store data such as routing data, registration data, and design data globally. 

![image](https://user-images.githubusercontent.com/32497439/84834885-43eaf800-afe7-11ea-9a6e-f30c0bdbbb44.png)

I have updated the property description of **Location** in [this article](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0).

Please let us know if it answers your question.

**Comment by Andrea-Orimoto** [comment]
Hi @prashantsoni, thanks for asking. All Azure resources require a Resource Group to be created, and the Resource Group requires a location. Location doesn't affect the Bot Service Registration.

Hope this helps!
Andrea
