### ISSUE TITLE
Missing Linked URL

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/bot-docs#1739]
Multi-lingual generation and language fallback policy section links to non-existent URL
https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/language-generation/csharp_dotnetcore/05.a.multi-turn-prompt-with-language-fallback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59573a90-7a7a-418c-f661-90f53a00e47d
* Version Independent ID: cec084c0-0823-0c68-887c-bc660ac109cc
* Content: [Language Generation - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-language-generation?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-concept-language-generation.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-language-generation.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing out the broken link @GauravES. Here are link to the samples:

- [C# sample](https://aka.ms/csharp-lg-multi-turn-prompt-language-fallback-sample)
- [JavaScript sample](https://aka.ms/js-lg-multi-turn-prompt-language-fallback-sample)

Updates are in [PR 2240](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2240/). The document has been updated and changes should go live soon.

**Comment by emgrol** [comment]
Closing now that the updated links are live.
