### ISSUE TITLE
Slack does not support suggested actions

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1742]
[This document](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference#action-support-by-channel) says Slack supports suggested actions. It does not. This is related to this longstanding issue: https://github.com/microsoft/botbuilder-dotnet/issues/2291

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60950444-cdcc-f0b9-aa21-c99894e26b50
* Version Independent ID: 0bd14221-e030-f9d8-41e6-1a52c9a76440
* Content: [Channels reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channels-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channels-reference.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out @v-kydela. The fix is in [PR 2258](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2258) and will hopefully go live soon.

**Comment by emgrol** [comment]
Closing now that the updates are live.
