### ISSUE TITLE
The user.id gets passed through but not the user.name this is important for the SSO situation 

### ISSUE THREAD

**Issue by xtianus79** [MicrosoftDocs/bot-docs#1743]
What is the point of the user.name. I am passing that through, it's in the token that obtains the conversation websocket.  However, when I use the websocket and and send an activity the from id is there of what I created and it is persisted even if I override that but the name is not there. now I can override that and add any object to the from field and that will post through to the message coming into the websocket but I would rather it act like the user.id. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd0bdf8-7cb8-1f26-65a1-3876ea84351f
* Version Independent ID: bda6ce3a-f006-baaf-db50-82bd79afa6ab
* Content: [Authentication - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-authentication.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Researching.

**Comment by anusharavindrar** [comment]
Investigating

**Comment by anusharavindrar** [comment]
@xtianus79, can you elaborate more on what you are trying to do? What type of SSO are you trying to implement?

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to reopen it if the issue persists.
