### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by sayak1711** [MicrosoftDocs/bot-docs#1744]
[Enter feedback here]
typo in "asynchronous"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a20df2-727c-1afd-2b87-836ea1ea4f7a
* Version Independent ID: 157fc262-fb1f-f12d-0890-e90119feb444
* Content: [Create a bot using Bot Framework SDK for Python - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/python/bot-builder-python-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/python/bot-builder-python-quickstart.md)
* Service: **bot-service**
* GitHub Login: @emgrol
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
@sayak1711 Thanks for reporting the issue. It's fixed in [PR2237](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2237). The content will be merged and go live soon.
