### ISSUE TITLE
Please disambiguate user auth from bot auth

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1745]
My understanding is that bot authentication is the Microsoft app ID and password, while the authentication done by OAuth prompts is better referred to as user authentication. This document is titled "Bot authentication" but it seems to be about user authentication. The first anchor is "User authentication in a conversation" and even the browser tab thinks the document is called "User authentication in the Azure Bot Service." Should the title on the actual Markdown page be changed from "Bot authentication" to "User authentication"? Perhaps a new "types of authentication" document could be added to disambiguate the terms. Client authentication could also be mentioned for the sake of completeness.

If we decide to consistently refer to user authentication as user authentication and not bot authentication, other documents like [this](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication) will also need to be updated. The language in the [samples](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/18.bot-authentication) should also change.

Example of a customer who could use this: https://stackoverflow.com/questions/62455129/what-is-the-botframework-security-model

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf2089c-a313-0abf-2ed3-8d7db5c4f677
* Version Independent ID: f0b3a9ce-b1e3-7b3d-15a9-0b9e032aa4bd
* Content: [User authentication in the Azure Bot Service - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-authentication?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-authentication.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
I'm not sure what the correct title should be, but yes, the current title is misleading. Perhaps:
- **Bot authorization** [to act on behalf of the user]
- **User authentication**, as the user proving their identity is part of this process
- or something else

**Comment by mmiele** [comment]
@v-kydela Maybe more that bot authentication we should say bot **authorization**. So the article **Bot authentication** will be named **Bot authorization**. 
The first paragraph could be modified as follows:
There are times when a bot must access secured online resources on behalf of the user; to do that the bot must be authorized. The authorization takes the form of a bearer token. **This token is obtained by authenticating the user's credentials using OAuth**. 
All this is accomplished by a set of components that are part of the Azure Bot Service architecture described below.

**Comment by v-kydela** [comment]
@mmiele - That would serve to disambiguate bot authorization from bot authentication, but it wouldn't serve to disambiguate user authentication from bot authentication. This raises a lot of questions for me. Are we considering bot authorization to be the same thing as user authentication? Is there a reason we don't want to user the term user authentication? I'm worried that the difference between authentication and authorization won't come across very well and will just add confusion. Personally I don't think bot authorization should be used to mean the same thing as user authentication, because even though the user is authorizing the bot to access resources with a user token, the Microsoft app ID and password are also authorizing the bot to access ABS with a bot token. My understanding is that authentication and authorization go hand in hand.

**Comment by mmiele** [comment]
@v-kydela You know Kyle, there are 2 sides to the story; authentication and authorization which are conflated, hence the confusion. Typically, when we say authentication we also imply authorization as in the case of our documentation as I found it when I started working on it. You are correct that the tile "bot authentication" is a bit misleading, because actually is the user that is authenticated and based on that a token is issued to authorize the bot to access the resources the user has access to. The documentation explains this in some form. Maybe we need to be more specific, perhaps using the previous wording. I would suggest to do this minimal adjustment. If you feel differently we may have to escalate this issue.

**Comment by mmiele** [comment]
Work in progress see PR https://github.com/MicrosoftDocs/bot-docs-pr/pull/2342.

**Comment by v-kydela** [comment]
I'm sorry, I'm still not seeing an explanation for why you don't want to use the term "user authentication." I think it's great that you're explaining the difference between authentication and authorization, but why not do that on top of explaining the three types of authentication?

**Comment by mmiele** [comment]
Disregard what I said in the previous comment. 
Working on the PR.

**Comment by mmiele** [comment]
Solved as per https://github.com/MicrosoftDocs/bot-docs-pr/pull/2343.
