### ISSUE TITLE
Incorrect link to V4 doc on page

### ISSUE THREAD

**Issue by jwiley84** [MicrosoftDocs/bot-docs#1750]
There is a banner at the top of the page that says "This topic applies to SDK v3 release. You can find the documentation for the latest version of the SDK v4 here." Clicking the link redirects to a generic Azure Bot Service page, instead of the v4 State documentation that it should. The  correct link should  go to :

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79468f82-f7aa-cafb-302c-a874c4521414
* Version Independent ID: d3e88f16-89de-a61b-213d-2fcfe6593b5b
* Content: [Manage state data (v3 C#) - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0&viewFallbackFrom=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-state.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by jwiley84** [comment]
Related to https://github.com/microsoft/BotBuilder-Samples/issues/2550

**Comment by JonathanFingold** [comment]
This is a known issue with our TOC. If the file contains both v3 and v4 content, then the switching between views works as expected; otherwise, switching views will dump you onto the landing page. As far as I know, we are not planning a fix for this behavior.

**Comment by JonathanFingold** [comment]
The fix for the samples issue is to link to the correct v4 topic.
