### ISSUE TITLE
The step 3 is incorrect

### ISSUE THREAD

**Issue by chschrae** [MicrosoftDocs/bot-docs#1751]
There is no longer an option to select the Language understanding bot as a template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f0f2ff1-f19c-c66d-53ac-b9569e0a4601
* Version Independent ID: 0ef27a09-09cf-e09a-ec40-9c86b1150bde
* Content: [Recognize intents and entities with LUIS (v3 C#) - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-luis-dialogs?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-luis-dialogs.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-luis-dialogs.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Please use the v4 SDK for any new bots.
