### ISSUE TITLE
add instead of sum in sum function samples

### ISSUE THREAD

**Issue by crismogram** [MicrosoftDocs/bot-docs#1754]
the sum function samples shows add instead of sum. typo

![image](https://user-images.githubusercontent.com/5903626/86013360-a5807d00-ba51-11ea-9fc9-98a4883dfb63.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5cc1453-1ec4-1ad7-2a9f-fa934224b79d
* Version Independent ID: 9645f547-d38a-4a22-c84b-ee98b7f24dfc
* Content: [Adaptive expressions prebuilt functions - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/adaptive-expressions/adaptive-expressions-prebuilt-functions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/adaptive-expressions/adaptive-expressions-prebuilt-functions.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out @crismogram. The function fix is in [PR 2258](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2258) and the changes should go live soon.

**Comment by crismogram** [comment]
Thank you @emgrol that's good to hear.

**Comment by emgrol** [comment]
Closing now that the typo fixes are live.
