### ISSUE TITLE
Seems to be missing the Azure Table Storage example?

### ISSUE THREAD

**Issue by safari137** [MicrosoftDocs/bot-docs#1755]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Write directly to storage - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@safari137 Can you please look in the section: [Memory storage](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp#memory-storage)? There you can find a link to the [Azure Table storage](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state-azure-table-storage?view=azure-bot-service-3.0&viewFallbackFrom=azure-bot-service-4.0). Let me know if this is the information you are looking for? 
Thanks

**Comment by safari137** [comment]
That's exactly what I was looking for. Thanks!

**Comment by mmiele** [comment]
@safari137  Perfect. Glad I could help.
