### ISSUE TITLE
Changes to the webex connection process

### ISSUE THREAD

**Issue by jwiley84** [MicrosoftDocs/bot-docs#1756]
According to this https://github.com/microsoft/botframework-sdk/issues/5864 there is an issue with the section detailing the webex portal. Per @garypretty:

>Yes, I agree it's a docs change. Looks like they slightly altered that portal / process, but should be a simple change.

Opening this here as it appears to be a docs issue. Will try to repro tonight to get the exact steps that need fixing and will update this ticket with them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e61be5-e537-8678-f907-10f27ea7bf90
* Version Independent ID: e2a9d88e-0819-9de5-d6f8-48bf7b270685
* Content: [Connect a bot to Webex Teams - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-adapter-connect-webex?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-adapter-connect-webex.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-adapter-connect-webex.md)
* Service: **bot-service**
* GitHub Login: @garypretty
* Microsoft Alias: **gapretty**

**Comment by mmiele** [comment]
@jwiley84 Jessica were you able to repro the issue and found the steps to document? Thanks

**Comment by mmiele** [comment]
Researching.

**Comment by jwiley84** [comment]
Hi @mmiele !

Sorry for the delay. Here are the steps that need changing. I included an updated images where they need to change as well.:

In "Complete configuration of your Webex app and bot", under 'Create and update a Webex webhook', from step 3 onward:

Steps 3 and 4 should read as:

3. Click the link for the 'POST' method `https://webexapis.com/v1/webhooks` (with the description "Create a webhook"). This will expand a form allowingyou to send a request to the endpoint.

![image](https://user-images.githubusercontent.com/17333688/88090018-ce240000-cb41-11ea-954c-9d9f46136776.png)


4. Populate the form with the following details:
 - Name (provide a name for your webhook, such as 'Messages Webhook')
- TargetUrl (the full URL to your bot's Webex endpoint, such as `https://yourbotapp.azurewebsites.net/api/webex`)
- Resource (messages)
- Event (created)
- filter (leave this blank)
- secret (here you should provide a secret of your choice to secure your webhook. This will later go in your bot's appsettings.json file)

![image](https://user-images.githubusercontent.com/17333688/88089913-aaf95080-cb41-11ea-9356-19446c9554cd.png)

**Comment by mmiele** [comment]
Issue solved. See related PR mm-fixing-webex-issue MicrosoftDocs/bot-docs-pr#2319.
