### ISSUE TITLE
it not run as well 

### ISSUE THREAD

**Issue by Suyleap** [MicrosoftDocs/bot-docs#1757]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a26d6f7-2453-f514-a812-f87916b6c724
* Version Independent ID: 806e3815-cee0-cfc7-9af5-e3a23270644c
* Content: [Connect a bot to WeChat - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-wechat?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-wechat.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-wechat.md)
* Service: **bot-service**
* GitHub Login: @seaen
* Microsoft Alias: **egorn**

**Comment by emgrol** [comment]
This seems to have been opened by accident. If there is an issue in this article, please reopen the issue and add a title and description of the issue.
