### ISSUE TITLE
Bot Emulator Question

### ISSUE THREAD

**Issue by RonnieQuan** [MicrosoftDocs/bot-docs#1760]
Is Bot framework emulator proxy aware? where do we configure the proxy setting for the Bot framework emulator?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f67913-4b16-2967-6044-4feb7be1f99b
* Version Independent ID: e3d2800a-d7b7-da55-4399-9586deaf4c9e
* Content: [Test and debug bots using the Bot Framework Emulator - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-service-debug-emulator.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-debug-emulator.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@tonyanziano - do you know?

**Comment by mmiele** [comment]
@RonnieQuan You may want to take a look at this StackOverflow question: [Is there a way to test the locally-hosted bot without Ngrok?](https://stackoverflow.com/questions/61480011/is-there-a-way-to-test-the-locally-hosted-bot-without-ngrok/61483034#61483034) The proxy topic is discussed there.

**Comment by tonyanziano** [comment]
Sorry for the late response, I didn't see this pop up in my email.

Yes, you can configure proxy settings in the Emulator by setting some environment variables on your machine before running the Emulator.

The configurable environment variables are:

`HTTP_PROXY` - specify a proxy url to route http requests through
`HTTPS_PROXY` - specify a proxy url to route https requests through
`NO_PROXY` - specify urls to bypass the above proxy settings for

More information [here](https://github.com/microsoft/BotFramework-Emulator/issues/1647).

Hope this helps

**Comment by mmiele** [comment]
Related PR: https://github.com/MicrosoftDocs/bot-docs-pr/pull/2320

**Comment by mmiele** [comment]
"Debug with the emulator" article updated with proxy information. It will be in the next available release.
