### ISSUE TITLE
Document adaptive dialogs tips and tricks

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#1767]
**Tips and tricks:** adding to existing docs or create a new article, this applies to Composer and the SDK – same issues, but the implementation details may be different.
- Need to keep an Uber list of all tips and tricks and brainstorm list to determine where they belong.
- Turn.recognized.score >= 0.8 applies to most intent triggers.
- 3 types of input values you can have in properties. Input, output and in/out.

**Comment by WashingtonKayaker** [comment]
**Tips and tricks:** adding to existing docs or create a new article, this applies to Composer and the SDK – same issues, but the implementation details may be different.
- Need to keep an Uber list of all tips and tricks and brainstorm list to determine where they belong.
- Turn.recognized.score >= 0.8 applies to most intent triggers.
- 3 types of input values you can have in properties. Input, output and in/out.

**Comment by JonathanFingold** [comment]
Unscheduling for now, until there is more clarity on the SDK side.
