### ISSUE TITLE
Not able to get access token

### ISSUE THREAD

**Issue by RonnieQuan** [MicrosoftDocs/bot-docs#1779]
I follow the steps to troubleshoot a sample BOT
But got following error in step 2 when I run curl

AADSTS500021: Access to 'Bot Framework' tenant i s denied.\r\nTrace ID: 75fda060-1b4c-489d-8336-183211be3d00\
--

I use the exact curl command from document, using my appId and secret.

Any guidance?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc8a0643-f219-a48f-666e-95bc9f0f351c
* Version Independent ID: 81578919-249c-b3e7-b367-183d70135890
* Content: [Troubleshooting Bot Framework Authentication - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-troubleshoot-authentication-problems.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-troubleshoot-authentication-problems.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by dmvtech** [comment]
HI @RonnieQuan Apologies for not getting to this sooner. Are you still having this issue?
