### ISSUE TITLE
The bot's Microsoft App ID or Microsoft App Password is incorrect

### ISSUE THREAD

**Issue by RonnieQuan** [MicrosoftDocs/bot-docs#1780]
I have followed the document, register AppId and create secret.
Download https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/18.bot-authentication
and start from local

But Bot framework emulator returns 500 with this error message "The bot's Microsoft App ID or Microsoft App Password is incorrect."

Can you please help me to understand how does bot framework emulator handle authentication for a bot running from local?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by amityksharma** [comment]
I have followed the document, register AppId and create secret.
Download https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/18.bot-authentication
and start from local


{
  "MicrosoftAppId": "Bot bulilder APID",
  "MicrosoftAppPassword": "BotSecret",
  "ConnectionName": "AzureADv2ConnectionString"
}

IT says [06:52:08]Cannot post activity. Unauthorized.
[06:52:08]POST401directline/conversations/<conversationId>/activities

**Comment by mmiele** [comment]
@RonnieQuan Did you provide your bot's app ID and password to the emulator? This information comes from the bot channels registration and is contained in the `appsettings.json` file. 
```json
{
  "MicrosoftAppId": "<your app id here>",
  "MicrosoftAppPassword": "<your password here>",
  "ConnectionName": ""
}
```
For more information, see [Test the bot using the emulator](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp#test-the-bot-using-the-emulator).

If you do not assign any values but empty strings, the bot should issue this error message: *The bot encountered an error or bug*.

I hope this helps solving your problem.
