### ISSUE TITLE
Does context have beginDialog method?

### ISSUE THREAD

**Issue by kostyaVyrodov** [MicrosoftDocs/bot-docs#1781]
This code snippet belongs to a class extending `ActivityHandler` type. 

`onMessage` accepts a function that has a parameter 'context' and the type of the parameter is `TurnContext` which doesn't have a method `beginDialog`, so the snippet doesn't work.

```
this.onMessage(async (context, next) => {

    const recognizerResult = {
        text: context.activity.text,
        intents: []
    };

    const greetingRegex = RegExp(/hello|hi|hey|greetings/i);

    if (greetingRegex.test(context.activity.text)) {
      // greeting intent identified
      recognizerResult.intents.push('Greeting');
    }

    if (recognizerResult.intents.includes('Greeting')) {
        // Run the 'Greeting' dialog
        // No context.beginDialog here! 
        await context.beginDialog(GREETING_DIALOG_ID);
    }

    await next();
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dc19058-d861-8d28-f14f-98517058c9a3
* Version Independent ID: b913f984-fe7d-b88f-2435-a8b097cb7b04
* Content: [JavaScript v3 to v4 migration quick reference - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/migration/javascript-migration-quickreference?view=azure-bot-service-4.0#to-register-activity-handlers)
* Content Source: [articles/v4sdk/migration/javascript-migration-quickreference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/migration/javascript-migration-quickreference.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
The code snippet is a little out of date, but the `context` from the current snippet refers to a DialogContext, and not to a TurnContext.

For a more up-to-date way to run the dialog, see the [run the dialog](https://docs.microsoft.com/azure/bot-service/bot-builder-dialog-manage-conversation-flow#run-the-dialog?view=azure-bot-service-4.0&tabs=javascript) section in the how to implement sequential conversation flow article.
