### ISSUE TITLE
QnA Maker default answer for a bot

### ISSUE THREAD

**Issue by diberry** [MicrosoftDocs/bot-docs#1785]
In the section titled "Calling QnA Maker from your bot" the C# sample code doesn't have the same hard-coded answer string the other code language samples have. Is that on purpose - how does C# get the default answer - it isn't clear from the code.

Additionally, and perhaps more importantly,why is the default answer code hard-coded instead of using the default answer value from QnA Maker? I'm looking for design guidance of the bot when compared to implementation guidance of the bot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@diberry The snippets are misaligned. However, if you look at the samples, they all appear to respond with "No QnA Maker answers were found" when now answers are found.

We can fix the snippet alignment issue, but if the samples themselves are using the wrong pattern, please open an issue in the samples repo.

**Comment by JonathanFingold** [comment]
And the snippets are misaligned again.

**Comment by JonathanFingold** [comment]
Fixed in master. Should go live in a few days.
