### ISSUE TITLE
Add to FAQ about how to deal with an outbound handoff activity

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#1786]
There is confusion around how to use the `handoff` activity.
- From the FAQ, we can explain that the event needs to be intercepted before it gets to the channel to function "properly", and link to the community samples.
- See botframework-sdk issue [5920](https://github.com/microsoft/botframework-sdk/issues/5920) for background on the issue.
- See the activity schema for more info about the [handoff activity](https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#handoff-activity).

In summary, the docs are conflicting in terms of support for handoff activity. Artur explained thusly.
 
> Handoff is supported by DirectLine for “bot as an agent” scenario. This is how LivePerson and PVA are using it. It works because there is an app at the other end of DirectLine that knows how to deal with the event. Other channels would not know what to do with the event.  For other channels, handoff is supported in the middleware that transforms the handoff event into API calls specific to the agent hub. We and customers have implemented connectors (middleware + adapter) for LivePerson proxy, ServiceNow, RingCentral and others.

**Comment by mmiele** [comment]
Completed. 
Related PR https://github.com/MicrosoftDocs/bot-docs-pr/pull/2277 has been merged.
