### ISSUE TITLE
Bot Service article - Image has typo

### ISSUE THREAD

**Issue by corinagum** [MicrosoftDocs/bot-docs#1787]
The first image in the article has a typo: the middle column says "Bot Adatper" instead of "Bot Adapter"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 665ea3ca-8796-7cc2-acda-c2a0a5f93912
* Version Independent ID: b110b105-da18-e4bd-5b6c-2bb8b130e079
* Content: [Direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Closing since the issue was addressed. Thanks for your feedback @corinagum
