### ISSUE TITLE
How to Article: migrate waterfall to adaptive dialog

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#1796]
Take a waterfall sample and convert to adaptive: "We should create a separate article that describes how to migrate waterfall steps to code actions. There are a couple of gotchas."

Sample apps:
- Non-adaptive dialog waterfall sample app is: [05.multi-turn-prompt](https://aka.ms/cs-multi-prompts-sample)
- Adaptive dialog waterfall sample app is: [01.multi-turn-prompt](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/adaptive-dialog/01.multi-turn-prompt)

Introduction to waterfall: 
- [Waterfall dialogs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0#waterfall-dialogs)

**Comment by erhopf** [comment]
Covered here:https://docs.microsoft.com/en-us/composer/how-to-migrate-a-bot-to-composer
