### ISSUE TITLE
[R10] Extend 'getProperty' builtin function to support accessing top memory.

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#1804]
Extend 'getProperty' builtin function to support accessing top memory.

Originally, `getProperty` accepts two parameters, the first parameter is an instance, and the second parameter is the property name which user wants to access the value from. In this mode, the user can not access the top-level memory from dynamic/special string property.

After this change, `getProperty` accepts only one parameter, that presents the root property from the memory.

Example:
Scope is :

```csharp
{
"a:b": "value"
}
```

`getProperty('a:b')` would get string "value",

C# pr:  
https://github.com/microsoft/botbuilder-dotnet/pull/4176

js pr:  
https://github.com/microsoft/botbuilder-js/pull/2437

**Comment by emgrol** [comment]
Closing now that the PR has been merged into the R10 branch.
