### ISSUE TITLE
 BUG - Bot responds "Value cannot be null. (Parameter 'key')"

### ISSUE THREAD

**Issue by rubit0** [MicrosoftDocs/bot-docs#1806]
Following this tutorial, will lead to the issue, where the Bot responds always with "Value cannot be null. (Parameter 'key')".
It took countless of hours finding out the issue across several github issue tickets: 

- https://github.com/microsoft/BotFramework-Composer/issues/2240

- https://github.com/microsoft/BotFramework-Composer/issues/3554

It turns out that in the activity request json body, you also have to add a *"locale"* field.
So in your example body it looks like this:

> {
    "type": "message",
    "from": {
        "id": "user1"
    },
    "text": "hello"
}

but it needs to be change to this:

> {
    "locale": "en-EN",
    "type": "message",
    "from": {
        "id": "user1"
    },
    "text": "hello"
}

Please update the documentation to include the *locale* field, so others don't run into the same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e4dd44-9bfc-14b1-cfd4-d37d500b1877
* Version Independent ID: 965c2c94-8cf1-fbf0-c321-547a90449382
* Content: [Send an activity the bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-send-activity?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-send-activity.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-send-activity.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
@rubit0 Thanks for reporting the issue and providing a solution to this issue.
We will update the doc and will let you know.

**Comment by zxyanliu** [comment]
@rubit0 Thanks again for your report. We already fixed the bug you pointed out. The content was merged and will be live soon. Closing this issue as it is addressed.
