### ISSUE TITLE
broken pypi requirements

### ISSUE THREAD

**Issue by burguyd** [MicrosoftDocs/bot-docs#1807]
[Enter feedback here]
Hello. There is problem with broken pypi reqiirements in the intruction:

`ERROR: cookiecutter 1.7.2 has requirement requests>=2.23.0, but you'll have requests 2.22.0 which is incompatible.`
But after upgrade requests package we take
`ERROR: botframework-connector 4.9.1 has requirement requests==2.22.0, but you'll have requests 2.23.0 which is incompatible`

So you should upgrate botframework-connector requirements or freeze cookiecutter==1.7.0
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a20df2-727c-1afd-2b87-836ea1ea4f7a
* Version Independent ID: 157fc262-fb1f-f12d-0890-e90119feb444
* Content: [Create a bot using Bot Framework SDK for Python - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/python/bot-builder-python-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/python/bot-builder-python-quickstart.md)
* Service: **bot-service**
* GitHub Login: @emgrol
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out @burguyd. The file has been updated with the correct package version in [PR 2258](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2258) and the changes should go live soon. 

Related issue: https://github.com/microsoft/botbuilder-python/issues/1070

**Comment by burguyd** [comment]
> been updated with th

Ok, thank you
