### ISSUE TITLE
Enable list concatenation for function "concat"

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#1808]
`concat`:
1. If all items are lists, concatenate them with list mode.
`concat([1, 2], [3, 4])` -> `[1, 2, 3, 4]`

2. If there exists any item that is not a list, use string concatenation mode:
`concat('a', 'b', 1, 2)` -> `'ab12'`
`concat('a', [1, 2])` -> `aSystem.Collections.Generic.List 1[System.Object]` // unreadable, best to avoid

3. If null exists, skip it
`concat([1, 2], null)` -> `[1, 2]`
`concat('a', 1, null)` -> `'a1'`

C# pr: https://github.com/microsoft/botbuilder-dotnet/pull/4066
js pr: https://github.com/microsoft/botbuilder-js/issues/2373

**Comment by emgrol** [comment]
Closing now that the PR has been merged into the R10 branch.
