### ISSUE TITLE
Add expandText LG function

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#1809]
Add `expandText` function for LG.(not expression)
Add expandText LG function to eval the plain text and get the data binding result.

C# pr: https://github.com/microsoft/botbuilder-dotnet/pull/4058
and a small fix: https://github.com/microsoft/botbuilder-dotnet/pull/4132

js:https://github.com/microsoft/botbuilder-js/pull/2387

**Comment by emgrol** [comment]
Closing now that the PR has been merged into the R10 branch.
