### ISSUE TITLE
Add lambda syntactic sugar

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#1810]
Support lambda style expression in `foreach`, `select` and `where` prebuilt functions.

For example, After the change, the expression could be:
`foreach(items, u => json(u))` instead of `foreach(items, u, json(u))`, it is more readable.

`foreach(items, u, json(u))` -> `foreach(items, u => json(u))`
`where(items, u, u > 1)` -> `where(items, u => u > 1)`
`select(items, u, json(u))` -> `select(items, u => json(u))`

pr link: 
C#: https://github.com/microsoft/botbuilder-dotnet/pull/3899
js: https://github.com/microsoft/botbuilder-js/pull/2328

**Comment by emgrol** [comment]
Closing now that the PR has been merged into the R10 branch.
