### ISSUE TITLE
expression doc missing inline object and array initialization

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#1812]
For creating array via [... , ...] syntax, the related PR is:
https://github.com/microsoft/botbuilder-dotnet/pull/3613
The syntax is, for the expression in LG below,
```
${['a', 'b', 'c']}
```
will return an array of `['a', 'b', 'c']`

For creating an object via {key: value, ...}, the related PR is:
https://github.com/microsoft/botbuilder-dotnet/pull/3694
The syntax is, for the expression in LG below
```
${{user: "Wilson"}, {user: {age: 27}}}
```
will return an object `{user: "Wilson"}, {user: {age: 27}}`

**Comment by emgrol** [comment]
Closing now that the changes have been merged into the R10 branch.
