### ISSUE TITLE
Start the waterfall dialog without sending any messages first.

### ISSUE THREAD

**Issue by grimz11** [MicrosoftDocs/bot-docs#1820]
With this implementation, Is there a way that we don't need need to input "Hi" first to start the waterfall dialog?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c5adf9-272a-e0f1-10f1-c8365e76035b
* Version Independent ID: 1982af41-5a06-4398-0e95-abcc50864e0d
* Content: [Implement sequential conversation flow - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Some channels send a `conversationUpdate` activity when a user joins a conversation, before they've sent a message to the bot, but other channels don't send this activity until after the user sends their first message. The Web Chat channel sends the `conversationUpdate` first, but I think it is in the minority. See how to [send a welcome message to users](https://docs.microsoft.com/azure/bot-service/bot-builder-send-welcome-message) and the [conversation update activity](https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#conversation-update-activity) in the activity schema for more information.

**Comment by grimz11** [comment]
@JonathanFingold, I manage to make it work. I added a Dialog.RunAsync() to the OnMembersAddedAsync() method.
