### ISSUE TITLE
changes in luis

### ISSUE THREAD

**Issue by safari137** [MicrosoftDocs/bot-docs#1822]
It looks like some things have changed in LUIS that aren't covered in the doc.

I get the following after importing the json model.

![image](https://user-images.githubusercontent.com/12038536/86811364-d3665280-c04b-11ea-82ac-88e3319a7d4a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Add natural language understanding to your bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for letting us know about this @safari137, I'll be updating the article soon.

**Comment by emgrol** [comment]
Closing now that the updates have been merged.
