### ISSUE TITLE
Typo - "LiverPerson" should be "LivePerson" - note the additional 'r'

### ISSUE THREAD

**Issue by VaderConsulting** [MicrosoftDocs/bot-docs#1823]
Typo - "LiverPerson" should be "LivePerson" - note the additional 'r'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 818b8a18-3321-4f50-f2e3-3d254806c958
* Version Independent ID: 0514154e-5d18-19fd-58e2-ec356509b19e
* Content: [Transition conversations from bot to human - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-handoff-human?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-design-pattern-handoff-human.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-pattern-handoff-human.md)
* Service: **bot-service**
* GitHub Login: @arturl
* Microsoft Alias: **arturl**

**Comment by arturl** [comment]
Thank you @VaderConsulting, we'll get it fixed.

**Comment by arturl** [comment]
Fixed.

**Comment by mmiele** [comment]
Fixed in the current documentation.
