### ISSUE TITLE
Training error issue: Help requested

### ISSUE THREAD

**Issue by akshaysureka** [MicrosoftDocs/bot-docs#1825]
I have been trying to follow the steps on this training
https://aischool.microsoft.com/en-us/conversational/learning-paths/building-an-intelligent-bot/quickly-creating-a-basic-bot/2wPHzCCswoImSqKGIoUgoa

My Bot does not build and has 28 errors. I am using the standard template. Very new to this stuff 

<img width="1052" alt="Screenshot 2020-07-12 at 16 01 42" src="https://user-images.githubusercontent.com/68193534/87249779-09934000-c459-11ea-9da1-60b455560228.png">

**Comment by JonathanFingold** [comment]
Which article is this in relation to?
