### ISSUE TITLE
Which visual studio version should I used to develop bot with Bot Framework v4 SDK 

### ISSUE THREAD

**Issue by fifteenjoy** [MicrosoftDocs/bot-docs#1826]
Which visual studio version should I used to develop bot with Bot Framework v4 SDK ?
Does VS2013 works ?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253d4e99-7fc5-cc8d-5b07-29bf2d78687a
* Version Independent ID: cdc0528d-cf1a-e015-1d8a-31ed062648f8
* Content: [Bot Framework Frequently Asked Questions Index - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-resources-bot-framework-faq.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-resources-bot-framework-faq.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
2019 is recommended.

**Comment by fifteenjoy** [comment]
Hi, Jonathan

How about 2013? I only have license for VS2013, not 2019

**Comment by JonathanFingold** [comment]
I don't think so, but I'll defer to our support team. However, you can use the community version of either Visual Studio 2019 or Visual Studio Code, both of which are free.
