### ISSUE TITLE
Webhook registration issue after fill your Telegram credentials

### ISSUE THREAD

**Issue by 4ININ** [MicrosoftDocs/bot-docs#1828]
Try to register webhook here https://dev.botframework.com/bots/channels?id=my-bot&channelId=telegram
But when click on "Save" button get "unable to save" message.
I do it many times successful earlier, but on this week something wrong. 

1. Go to https://dev.botframework.com/bots/channels?id=my-bot&channelId=telegram
2. Click on Save, after fill Access Token input field
3. See error "unable to save"

**Comment by dmvtech** [comment]
@4ININ Same here; Apologies. Is this issue still happening?

**Comment by 4ININ** [comment]
> @4ININ Same here; Apologies. Is this issue still happening?

Yes

**Comment by dmvtech** [comment]
@4ININ Please try deleting the channel and trying again. If it still doesn't work, then try pasting your API Token in a text editor (or developer tools console window) to make sure there are no hidden characters.
