### ISSUE TITLE
How to refresh `Conversation reference`?

### ISSUE THREAD

**Issue by johnny-linkedin** [MicrosoftDocs/bot-docs#1829]
In the Note section, it mentioned the `serverUrl` might change. If this thing happens, how can I get a new `serverUrl`? I can imaging if user contact me, I will update it with new value from the context of new message. However, does this mean I have no solution to send proactive message to users before users contact me again?

```
 Note

The service URL can change over time. If the service URL changes, previous conversation references will no longer be valid and calls to continue conversation will generate an error or exception. In this case, your bot will need to acquire a new conversation reference for the user before it can send proactive messages again.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521a9f9a-025c-c55b-c939-d9d4efc5c6d0
* Version Independent ID: 3bcafb54-f7eb-54f5-1d78-5f2087e2e2dc
* Content: [Send proactive notifications to users - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@johnny-linkedin - More information on the service Url can be found in the activity specification, [service URL](https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#service-url)

> Note A2304: **Channels SHOULD use stable values for the serviceUrl field as bots may persist them for long periods.**

Other than that, if the service URL changes and your catch an error, you just have to retire the conversation reference and wait for a new message from the user. I'll update the note to make this all a little more clear.

**Comment by johnny-linkedin** [comment]
Thanks a lot for clarifying it! I will follow your suggestion :)
