### ISSUE TITLE
Dialog doesn't working

### ISSUE THREAD

**Issue by 4ININ** [MicrosoftDocs/bot-docs#1830]
I try messaging with my Telegram bot.
When try messaging via Bot Emulator its ok (i send msg to bot and it reply to me).
When try messaging in telegram with webhook wich i registered here https://dev.botframework.com/bots?id=my-own-bot its ok 
But when i trying messaging with my custom webhook my bot dont reply.

```
    [Route("api/messages")]
    [ApiController]
    public class BotController : ControllerBase
    {
        private readonly IBotFrameworkHttpAdapter Adapter;
        private readonly IBot Bot;
        
        public BotController(IBotFrameworkHttpAdapter adapter, IBot bot)
        {
            Adapter = adapter;
            Bot = bot;
        }

        [HttpPost]
        public async Task PostAsync()
        {
            await Adapter.ProcessAsync(Request, Response, Bot);
            Response.StatusCode = 200;
        }
   }
```

**Comment by 4ININ** [comment]
Any info?

**Comment by dmvtech** [comment]
Hi @4ININ Sincerely apologize. Somehow this (and a few other) issues got passed by. Can you tell me; are you still having this issue?

**Comment by 4ININ** [comment]
> Hi @4ININ Sincerely apologize. Somehow this (and a few other) issues got passed by. Can you tell me; are you still having this issue?

Yes, its doesnt working

**Comment by dmvtech** [comment]
Is your bot published to azure or are you testing with a local bot and using ngrok?

**Comment by dmvtech** [comment]
Closing. If you are still having this issue, please let us know.
