### ISSUE TITLE
My bot takes a long time to reply. How do I troubleshoot the slowness? 

### ISSUE THREAD

**Issue by geo-msft** [MicrosoftDocs/bot-docs#1834]
[Enter feedback here]
How do I troubleshoot a slow performing bot? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ca2f105-818a-2e67-701d-b3de2533ec8b
* Version Independent ID: 8e216b2c-5a32-1153-7961-da8f6ba17fb8
* Content: [Bot Framework TroubleshootIndex - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-index?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-troubleshoot-index.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-troubleshoot-index.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
There is specific guidance on [My bot is slow to respond to the first message it receives. How can I make it faster?](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-general-problems?view=azure-bot-service-4.0#my-bot-is-slow-to-respond-to-the-first-message-it-receives-how-can-i-make-it-faster). Beyond that, we currently don't have much other guidance in the SDK documentation.

**Comment by geo-msft** [comment]
I am not referring to the slow first message. I mean: when I experience intermittent slowness (the bot takes longer to reply sometimes), how can I understand what requests take longer? One way to check application insights and see the dependencies or performance tab. But apart from that, what logs can I collect? How can I figure out if my code is not good? Thank you.

**Comment by EricDahlvang** [comment]
This is a great reference for troubleshooting timeout exceptions and long running operations: https://github.com/daveta/analytics/blob/master/troubleshooting_timeout.md

We are currently putting together some guidance for how to overcome these issues.
