### ISSUE TITLE
Azure Bot Menu Change

### ISSUE THREAD

**Issue by vibhav2799** [MicrosoftDocs/bot-docs#1837]
https://docs.microsoft.com/en-us/azure/bot-service/abs-quickstart?view=azure-bot-service-4.0#create-a-new-bot-service

Upon getting started, I couldn't seem to find **AI + Machine Learning -> Web App Bot** in Azure. I think the menu changed to **Bot Services -> Web App Bot**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33e8c5d2-bf2d-fc99-e813-bf9dd49eb9bb
* Version Independent ID: 830e4542-cdd8-3b64-f1df-2acae1ca3a88
* Content: [Create a bot with Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/abs-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/abs-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/abs-quickstart.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
The issue has been fixed in the current documentation. 
Thank you for reporting the problem.
