### ISSUE TITLE
Token service returns only access token, but not id_token

### ISSUE THREAD

**Issue by boz22** [MicrosoftDocs/bot-docs#1838]
When using the Token Botframework service to store and retrieve the tokens, is there a way to retrieve both access token and id token on a Connection created in the bot channel registration?

If I have the scope "openid, https://graph.microsoft.com/user.read" this will return access_token and id_token (in Postman) but I could only find references on how to retrieve access_token, not id_token (via Token Bot Service).

Also tried with sample: https://github.com/OfficeDev/microsoft-teams-sample-auth-node/issues

**Comment by mmiele** [comment]
@boz22 You would probably need your own authentication flow, and not use the bot framework token service that does not provide a way to get  the id token.
