### ISSUE TITLE
Change for race-sensitive language

### ISSUE THREAD

**Issue by GossiTheDog** [MicrosoftDocs/bot-docs#1840]
Hi - please change references to whitelist to allow list, in line with bias free comms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aa75583-93e6-cbcd-ab51-c6ec1bf85a58
* Version Independent ID: c33566c0-c48a-7d1a-d808-f7e3cee3d9dc
* Content: [Bot Framework Frequently Asked Questions Security and Privacy - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-faq-security?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-resources-faq-security.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-resources-faq-security.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Thanks @GossiTheDog - This fix is in PR and should be live within a week.
