### ISSUE TITLE
typos in bot creation cli

### ISSUE THREAD

**Issue by wilbug1git1** [MicrosoftDocs/bot-docs#1845]
Getting an error that SUB is not a required parameter here:
az deployment **sub** create --template-file "<path-to-template-with-new-rg.json" --location <region-location-name> --parameters appId="<app-id-from-previous-step>" appSecret="<password-from-previous-step>" botId="<id or bot-app-service-name>" botSku=F0 newAppServicePlanName="<new-service-plan-name>" newWebAppName="<bot-app-service-name>" groupName="<new-group-name>" groupLocation="<region-location-name>" newAppServicePlanLocation="<region-location-name>" --name "<bot-app-service-name>"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@wilbug1git1 Could you please provide more details about the problem you are experiencing? Thanks

**Comment by mmiele** [comment]
@wilbug1git1 I tested the command **az deployment sub create ...* and it is working as described. You may want to install the latest [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest). To check which version you have installed enter this command: **az --version**.
