### ISSUE TITLE
Incorrect return value documentation

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1846]
The [json](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions#json) return value has been erroneously copied from the [join](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions#join) return value

> The resulting string created from all the items in the specified array

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5cc1453-1ec4-1ad7-2a9f-fa934224b79d
* Version Independent ID: 9645f547-d38a-4a22-c84b-ee98b7f24dfc
* Content: [Adaptive expressions prebuilt functions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#json)
* Content Source: [articles/adaptive-expressions/adaptive-expressions-prebuilt-functions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/adaptive-expressions/adaptive-expressions-prebuilt-functions.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for catching this @v-kydela. I added a fix in https://github.com/MicrosoftDocs/bot-docs-pr/pull/2409.

**Comment by emgrol** [comment]
Closing now that the changes have been merged.
