### ISSUE TITLE
Building Missing Context

### ISSUE THREAD

**Issue by jawetzel** [MicrosoftDocs/bot-docs#1847]
In testing I had a case where the conversation contexts were lost, and I have been searching high and low for a way to rebuild conversation contexts once lost without a user needing to interact with the bot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521a9f9a-025c-c55b-c939-d9d4efc5c6d0
* Version Independent ID: 3bcafb54-f7eb-54f5-1d78-5f2087e2e2dc
* Content: [Send proactive notifications to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@jawetzel - I'm not aware of any way beyond normal data recovery methods. I'll flag this for support to look at.

**Comment by jawetzel** [comment]
After looking how to sign up new users to bot and send them proactive messages, I think both could use some more docs. 

GET /beta/users/${EMAIL} - provides user id

GET /beta/users/{UserId}/teamwork/installedApps?$expand=teamsApp&$filter=teamsApp/id eq '{BotHiddenId}' - provides install id, bot external id, and bot display name

GET /beta/users/{UserId}/teamwork/installedApps/{InstallId}/chat - provides chatId

`var address =
            {
                user: { id: {UserIdFromRequests} },
                bot:
                    {
                        id: {BotId From Requests},
                        name: {BotName From Requests}
                    },
                "conversation": {
                    "conversationType": "personal",
                    "tenantId": {TennantID},
                    "id": {ConversationId}
                },
                "channelId": "msteams",
                "locale": "en-US",
                "serviceUrl": "https://smba.trafficmanager.net/amer/"
            }
        await adapter.continueConversation(address, async turnContext => { . . . })`

**Comment by v-kydela** [comment]
@jawetzel - Are you still working on this?

**Comment by jawetzel** [comment]
@v-kydela 

Yes, I was able to recreate the context from graph. I posted the process so maybe it could get added to some docs. 

The problem I was having was my application was keeping the context in memory like all the examples used, but when you restart the app all references are lost.  The above comment is how i built the context from scratch.

**Comment by v-kydela** [comment]
@jawetzel - Your case sounds pretty unusual so I doubt this will be added to the docs, but we appreciate the work you've done and the info will remain here for people to find if they need it.

You do have a good point about the [samples](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/16.proactive-messages/Bots/ProactiveBot.cs#L19) storing the conversation references in local memory. Not only will the data be lost if the bot stops running but also the bot can't be scaled to run multiple instances. Anything that's meant to persist between turns should be stored in persistent state, but as far as I know we don't have an example of global bot state (meaning state that's not scoped to users or conversations). Would you like to raise that as a bug in the samples repo and link back to this issue?

**Comment by jawetzel** [comment]
My case isn't abnormal, its more of a fallback situation.

I do use a database as a persistent state for our use case. 

In early stages of implementation the database got cleaned out. It was immediately noticed that it was a pain to make every user initiate a conversation with the bot to get the context restored.

I think it's fairly common to ask if my data was destroyed what is our backup plan with the least user interuption.

**Comment by v-kydela** [comment]
@jawetzel - If you were using a database which got cleaned out, then why did you say you were using the bot's local memory which got reset when the bot restarted?

**Comment by jawetzel** [comment]
It is using memory, the database is a backup for the purpose of supporting restarts and scalability. 

Memory > Database > Graph Lookup.

Was trying to help.
