### ISSUE TITLE
Tiny 1-letter typo 

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/bot-docs#1848]
[Enter feedback here]

https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0#functions-injected-by-lg

**DeveRloper typo**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed604a1-7c6c-edfd-1c71-951322068283
* Version Independent ID: cbb78ea6-ad02-ba69-ede7-8eebc0ecf0a0
* Content: [.lg file format - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0&source=docs#functions-injected-by-lg)
* Content Source: [articles/file-format/bot-builder-lg-file-format.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/file-format/bot-builder-lg-file-format.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Fix merged into master. Changes should go live within a few days.
