### ISSUE TITLE
Delay Activity type is not referenced in the Bot Framework Activity spec

### ISSUE THREAD

**Issue by joe-tossell-mando** [MicrosoftDocs/bot-docs#1849]
The delay Activity type is not referenced in the Bot Framework Activity spec:
https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#typing-activity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055d8380-e33c-c31f-2ae0-7d4509472d1d
* Version Independent ID: ce913ebc-0575-180b-a6f5-850b69e86723
* Content: [Send and receive text message - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-send-messages?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-send-messages.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-send-messages.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@joe-tossell-mando - The `delay` activity is not part of the Bot Framework service. It is added by the SDK. The bot adapter intercepts the `delay` activity, pauses for a number of milliseconds, and then sends the remaining activities, if any.

The delay activity is never sent to a channel, and it's mainly for testing purposes.

**Comment by joe-tossell-mando** [comment]
Thanks for the clarification, I've been on leave, for anyone else wondering where that is:
https://github.com/microsoft/botbuilder-dotnet/blob/23f5c73a13e0651969473139ea1cca466d75ea04/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L529
For the C# adapter.

It would be useful to have this supported by the schema as it is useful for delaying a series of text responses based on reading times.

**Comment by JonathanFingold** [comment]
The Azure Bot Service times out a turn on most channels after 10 to 15 seconds, so this would not be a good way to handle your scenario. Here are a couple options that come to mind:
- You could use [suggested actions](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-add-suggested-actions#suggest-action-using-button) to give the user a "more" button. This would let the user start a new turn each time they click the button.
- You could push [proactive messages](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-proactive-message) to the conversation.

We have a new article coming out this week or next on how to manage "long-running" operations.

I'll review the **How to send messages** article and see if I can't make this all a little more clear.

**Comment by joe-tossell-mando** [comment]
The Azure Bot Service times out a turn on most channels after 10 to 15 seconds, so this would not be a good way to handle your scenario.
_I suppose that is why it would be could to include delay as an activity type so that the entire response can be provided within that time-frame, I guess though you are just moving the problem up the chain from the SDK into the ABS unless the channel itself supports delays_

Here are a couple options that come to mind:
    You could use suggested actions to give the user a "more" button. This would let the user start a new turn each time they click the button.
        _This is a good suggestion, I will raise it with our UX team_
    You could push proactive messages to the conversation.
        _Potentially, we have used proactive messages for scheduled notifications previously, however the delays we're talking about here are small and incidental. Average reading speed of 300wpm for messages of 5 - 10 words take between 1 and 2 seconds to read. Rather than have a single 15 - 20 word message breaking it up into smaller chunks and slightly pacing the delivery gives a more conversational experience._

_Our current solution:
We've implemented some middleware that introduces a small delay for sequential messages with the length of delay based on a reading speed of 300wpm and calculated from the previous message. I'll see if this can be added to https://github.com/BotBuilderCommunity/botbuilder-community-dotnet_

We have a new article coming out this week or next on how to manage "long-running" operations.
_Will keep an eye out for this_

**Comment by JonathanFingold** [comment]
I see where this could be useful for "short-running" operations where a minimal pause is desired. I'll look at adding a call-out for this method in the docs. I'm not yet sure where that would be discoverable.

For this, the BotFrameworkAdapter's Delay method should work just fine. This is a C#-specific implementation, though. If you need the equivalent method in another language, let me know.
