### ISSUE TITLE
Dispatch: Resolving incorrect top intent

### ISSUE THREAD

**Issue by safetyhorse** [MicrosoftDocs/bot-docs#1850]
I was trying to use the command provided to update the proper intent for dispatch, but it did not work and broke dispatch refresh for me. I was able to successfully remove the file and get dispatch CLI working again. When I tried again, I added the name parameter, -n <name> to the command and it went through and worked as described. The documentation might need an update in this section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs#resolving-incorrect-top-intent-from-dispatch)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **kamrani**

**Comment by diberry** [comment]
@tsuwandy Can you please review this issue?

**Comment by tsuwandy** [comment]
@safetyhorse, which command did you use?  Could you put the whole command here?  Thanks!

**Comment by safetyhorse** [comment]
To get the custom update file to work, I used this command:
`dispatch add -t file -n <name for service> -f <file path> --intentName <target intent name, ie l_General>`

**Comment by tsuwandy** [comment]
@safetyhorse, thanks!  Could you copy the content of the .dispatch file (with the file added) which broke refresh?    It'll be very helpful if you could email the .dispatch file and the files generated from dispatch create/refresh command (inside data folder) to tiens@microsoft.com.   Thank you!

**Comment by safetyhorse** [comment]
Unfortunately, .dispatch has been refreshed and overwritten enough times that I haven't been able to locate the iteration that broke.

**Comment by tsuwandy** [comment]
@safetyhorse, so you are not currently seeing the incorrect top prediction anymore, correct?  Should we close this issue and reopen when you see the issue again (or email me the dispatch files)?  Thanks!
