### ISSUE TITLE
Add Team's specific notes to proactive how-to

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#1852]
re: [47794-Case Review Item: Consider improving the documentation related to Proactive Messaging in Skype/Teams](https://fuselabs.visualstudio.com/BotFramework/_workitems/edit/47794)

- [x] Add note about needing a conversation reference.
- [x] Add note about being able to message individuals on a Teams group channel.
- [x] Add links to Teams docs and various Teams samples.
- [x] Get Eric's review on fixes (and possibly Andrew's)

**Comment by JonathanFingold** [comment]
@EricDahlvang Assigning back to you so you can resolve the issue that spawned this one.

**Comment by EricDahlvang** [comment]
Closing, since the work is completed.
