### ISSUE TITLE
{"v":"*****","k":true,"ib":false,"ob":false,"initialized":true} 

### ISSUE THREAD

**Issue by jtg5122** [MicrosoftDocs/bot-docs#1853]
Hi,

I've seen that other people have had this issue this year.  When confirm the direct line app extension and the bot are initialized, I get:

{"v":"*****","k":true,"ib":false,"ob":false,"initialized":true} 

What do I do to get true values for ib and ob?

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0

**Comment by Zerryth** [comment]
@jtg5122 A [Troubleshooting](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0#troubleshooting) section has been added to the DL ASE documentation. Are you able to resolve your issue following the steps listed there?
