### ISSUE TITLE
Deploy a python bot with additional dependencies is unclear

### ISSUE THREAD

**Issue by chris-askbrian** [MicrosoftDocs/bot-docs#1855]
Hi,  while it looks pretty straightforward to deploy a bot for other languages like nodejs with additional dependencies via vendoring (aka add the node_modules folder to the deployment zip file) this is not really a nice way to go in python... what would be the best way to handle this? Maybe the sentence "You do not need to prepare your project files before deploying a Python bot." is not so true at all ;D? Or do I simply lack the experience/ didnt look into the documentation close enough to see how to solve this problem in a nice way^^?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#deploy-via-arm-template-with-new-resource-group)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@chris-askbrian Could you please provide more details about the problem your are experiencing? Thanks

**Comment by emgrol** [comment]
@chris-askbrian Are you experiencing problems deploying a Python bot with additional dependencies? I reached out to the botbuilder-python team and they said the deployment steps look accurate, even for bots with additional dependencies.

**Comment by chris-askbrian** [comment]
I got confused by the following sentence: 

> Kudu assumes by default that deployments from zip files are ready to run and do not require additional build steps during deployment, such as npm install or dotnet restore/dotnet publish.

So I was expecting that the installation of the dependencies for python is happening before zipping the files like it does for the other languages... but after looking into the way the PYTHON image that is used in the deploymentTemplates it got more clear: It expects a requirements.txt to be present and because I use poetry to handle my dependencies the never got installed (solved it by converting the poetry dependencies list to a requirements.txt so maybe you should mention at this step for python that the installation of the dependencies happen on the server side not locally like it does for node/c# bots...

**Comment by emgrol** [comment]
Thanks for explaining the situation @chris-askbrian. I update the step in https://github.com/MicrosoftDocs/bot-docs-pr/pull/2373; the changes should go live shortly.

**Comment by emgrol** [comment]
Closing now that the updates are live.
