### ISSUE TITLE
Failed to process content in attachment

### ISSUE THREAD

**Issue by RafaNv** [MicrosoftDocs/bot-docs#1856]
I'm trying to send a message with Microsoft.graph.teams but return this error :Failed to process content in attachment.

	var file3 = ImageToBase64(model.URL);
	var chatMessage = new ChatMessage
    {
	Body = new ItemBody
	{
		ContentType = BodyType.Html,
		Content = model.Content
	},

        Attachments = new List<ChatMessageAttachment>()
            {
                new ChatMessageAttachment
                {
                    Id="123",
                    ContentType = " image/png",
                    Content = file3,
                    Name = "Spread_Anywhere.png"

                }
            }
    };
		await _client.Teams[model.GroupId].Channels[model.ChannelId].Messages
			.Request()
			.AddAsync(chatMessage);
			
	public string ImageToBase64(string fileName)
	{
		string base64String = null;
		//string path = "D:\SampleImage.jpg";
		var path = fileName;
		using (System.Drawing.Image image = System.Drawing.Image.FromFile(path))
		{
			using (MemoryStream m = new MemoryStream())
			{
				image.Save(m, image.RawFormat);
				byte[] imageBytes = m.ToArray();
				base64String = Convert.ToBase64String(imageBytes);
				return base64String;
			}
		}
	}

**Comment by JonathanFingold** [comment]
[How Microsoft Teams bots work](https://docs.microsoft.com/azure/bot-service/bot-builder-basics-teams) describes some of the additional activities you need to handle for a Teams bot. There is also additional information in the Microsoft Teams documentation on how to [create a bot for Microsoft Teams](https://docs.microsoft.com/microsoftteams/platform/bots/how-to/create-a-bot-for-teams).

If you're still having issues, please provide more detail, and someone on our support team can try to help out.

**Comment by RafaNv** [comment]
> [How Microsoft Teams bots work](https://docs.microsoft.com/azure/bot-service/bot-builder-basics-teams) describes some of the additional activities you need to handle for a Teams bot. There is also additional information in the Microsoft Teams documentation on how to [create a bot for Microsoft Teams](https://docs.microsoft.com/microsoftteams/platform/bots/how-to/create-a-bot-for-teams). In particular, see the Teams article on how to [send and receive files with a bot](https://docs.microsoft.com/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files)
> 
> If you're still having issues, please provide more detail, and someone on our support team can try to help out.

Hi @JonathanFingold , Thank you for answering the question, but, I need sends image like attachment by dll graph c# and return error: Failed to process content in attachment.
The attachment content is a image Base64 used according to documentation but it doesn't work.
The code show how I did.

**Comment by RafaNv** [comment]
> > [How Microsoft Teams bots work](https://docs.microsoft.com/azure/bot-service/bot-builder-basics-teams) describes some of the additional activities you need to handle for a Teams bot. There is also additional information in the Microsoft Teams documentation on how to [create a bot for Microsoft Teams](https://docs.microsoft.com/microsoftteams/platform/bots/how-to/create-a-bot-for-teams). In particular, see the Teams article on how to [send and receive files with a bot](https://docs.microsoft.com/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files)
> > If you're still having issues, please provide more detail, and someone on our support team can try to help out.
> 
> Hi @JonathanFingold , Thank you for answering the question, but, I need sends image like attachment by dll graph c# and return error: Failed to process content in attachment.
> The attachment content is a image Base64 used according to documentation but it doesn't work.
> The code show how I did.

'
