### ISSUE TITLE
The example for the adaptive card does not work on this page. What is the proper body payload of the REST POST to post that card?

### ISSUE THREAD

**Issue by BerndGewehr** [MicrosoftDocs/bot-docs#1858]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4df548-56f2-4601-31d8-58a3237fd867
* Version Independent ID: ec4ede13-b432-61bb-5de8-1ed88bf36e17
* Content: [Add rich card attachments to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-rich-cards?view=azure-bot-service-3.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-add-rich-cards.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-add-rich-cards.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by v-kydela** [comment]
@BerndGewehr - Sorry to leave you waiting.

Can you clarify what you mean when you say the example does not work? The example on the page is almost the same as the default example in the designer, and the example works if you paste it into the designer: https://adaptivecards.io/designer/

It looks just like it does in the image on the page:

![image](https://user-images.githubusercontent.com/41968495/92284011-009d7880-eeb6-11ea-9d5b-d0e93f109712.png)

**Comment by BerndGewehr** [comment]
The page is about REST API payloads - and the example card code is not yet a payload you can post to the API, it has to be included in a message attachment to be successfully posted against the API. That's why I think it should be listed as a portable payload on that page and not as a valid card JSON only.

**Comment by v-kydela** [comment]
If I modify the payload from the hero card section and paste the Adaptive Card JSON into it, it looks like this:

```json
{
  "type": "message",
  "from": {
    "id": "12345678",
    "name": "sender's name"
  },
  "conversation": {
    "id": "abcd1234",
    "name": "conversation's name"
  },
  "recipient": {
    "id": "1234abcd",
    "name": "recipient's name"
  },
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [
          {
            "type": "Container",
            "items": [
              {
                "type": "TextBlock",
                "text": "Publish Adaptive Card schema",
                "weight": "bolder",
                "size": "medium"
              },
              {
                "type": "ColumnSet",
                "columns": [
                  {
                    "type": "Column",
                    "width": "auto",
                    "items": [
                      {
                        "type": "Image",
                        "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
                        "size": "small",
                        "style": "person"
                      }
                    ]
                  },
                  {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                      {
                        "type": "TextBlock",
                        "text": "Matt Hidinger",
                        "weight": "bolder",
                        "wrap": true
                      },
                      {
                        "type": "TextBlock",
                        "spacing": "none",
                        "text": "Created {{DATE(2017-02-14T06:08:39Z, SHORT)}}",
                        "isSubtle": true,
                        "wrap": true
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "type": "Container",
            "items": [
              {
                "type": "TextBlock",
                "text": "Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation.",
                "wrap": true
              },
              {
                "type": "FactSet",
                "facts": [
                  {
                    "title": "Board:",
                    "value": "Adaptive Card"
                  },
                  {
                    "title": "List:",
                    "value": "Backlog"
                  },
                  {
                    "title": "Assigned to:",
                    "value": "Matt Hidinger"
                  },
                  {
                    "title": "Due date:",
                    "value": "Not set"
                  }
                ]
              }
            ]
          }
        ],
        "actions": [
          {
            "type": "Action.ShowCard",
            "title": "Comment",
            "card": {
              "type": "AdaptiveCard",
              "body": [
                {
                  "type": "Input.Text",
                  "id": "comment",
                  "isMultiline": true,
                  "placeholder": "Enter your comment"
                }
              ],
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "OK"
                }
              ]
            }
          },
          {
            "type": "Action.OpenUrl",
            "title": "View",
            "url": "https://adaptivecards.io"
          }
        ]
      }
    }
  ],
  "replyToId": "5d5cdc723"
}
```

Does this answer your question or are you saying you really want the doc to be modified?

@JonathanFingold - Do you think the doc should contain the full activity instead of just the card JSON?

**Comment by BerndGewehr** [comment]
My belief is that a page about REST API should point out valid API payloads on all examples, not only a few...

Thank you for caring!

**Comment by JonathanFingold** [comment]
My inclination is to make clear throughout this article that each example card JSON is meant to be added to an activity as an attachment. I think part of the problem is that this is only mentioned at the top of the article and easily missed.

I could situate each sample card JSON in a complete message activity payload, but then I'd need to repeat a bunch of placeholder content.

**Comment by BerndGewehr** [comment]
I agree. Maybe it would be helpful to start with demonstrating the pattern of attachment posting and later referring to it.

**Comment by JonathanFingold** [comment]
@BerndGewehr I made some changes to the article. These will go live the next time we push content to the live site.
