### ISSUE TITLE
When will this be available for nodejs?

### ISSUE THREAD

**Issue by shikshik** [MicrosoftDocs/bot-docs#1859]
[Enter feedback here]
This feature is exactly what we were looking for, but we have a nodejs based bot. Is there an ETA for nodejs version?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee5b7a1a-86c5-37a6-5a47-61dc29d9fa57
* Version Independent ID: a054ad1c-266f-9e28-bb7d-9fb4ee6c8988
* Content: [Introduction to adaptive dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-adaptive-dialog-introduction?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-adaptive-dialog-Introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-adaptive-dialog-Introduction.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@shikshik Adaptive dialogs are currently in preview in JavaScript. See [botbuilder-dialogs-adaptive](https://www.npmjs.com/package/botbuilder-dialogs-adaptive) on npm. In the upcoming release, adaptive dialogs should be a release candidate in JS.

**Comment by shikshik** [comment]
Great! I will definitely try it out.
Thanks @JonathanFingold !

**Comment by shikshik** [comment]
Hey, @JonathanFingold!
Is there any updates with the nodejs version? Or at least an example code / documentation?

**Comment by JonathanFingold** [comment]
@shikshik - The dev team still hasn't updated the readme for the npm package, but the JavaScript has preview support for adaptive dialogs. The JavaScript adaptive dialog samples are in the samples repo in the [experimental/adaptive-dialog/javascript_nodejs](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/adaptive-dialog/javascript_nodejs) folder. Many of the how-to docs for adaptive dialogs describe both the JavaScript and C# code, such as how to [Create a bot using adaptive dialogs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialogs-adaptive?view=azure-bot-service-4.0&tabs=javascript).

**Comment by shikshik** [comment]
Thank you @JonathanFingold .
I already managed to find the samples after reading every single document available :)
Also managed to test it in our bot.

Everything seems pretty good, but we are waiting for the end result with a finished version of the adaptive dialogs.
I see that you are planning to finish development until November 15, will it be released as a production version as well or it might take a bit longer for further processes after dev period is finished?

**Comment by cleemullins** [comment]
The JS Version of Adaptive Dialogs is in active development. This is an open-source project and there are nightly builds you could consume. We don't yet have a "GA" Release schedule for Adaptive Dialogs on the Node platform.
