### ISSUE TITLE
Proactive Message, Received error 401 “Authorization has been denied for this request”

### ISSUE THREAD

**Issue by vinisbranco** [MicrosoftDocs/bot-docs#1860]
I'm trying to send a proactive message using botframework in Nodejs (Teams channel), but a received 401 error.

I make some searches and I found that the error can be possible with the trust service URL, but I have already done that part.

My adpter config

```
const {
    BotFrameworkAdapter,
} = require('botbuilder');

const { MicrosoftAppCredentials } = require('botframework-connector');

const adapter = new BotFrameworkAdapter({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
})
```

Send proactive message code
```

adapter.continueConversation(address, async (t) => {
            MicrosoftAppCredentials.trustServiceUrl(process.env.MICROSOFT_BOT_SERVICE_URL);
            await t.sendActivity(model.render());
        }).then((r) => {
            console.log("continue")
            console.log(r)
            res.status(200).send({
                status: "OK"
            })
        }).catch((e) => {
            console.log(e);
            res.send("ERRO " + e)
        });
```

Request and response, with my AppId and conversation ID.

```
statusCode: 401,
>    request: WebResource {
>      streamResponseBody: false,
>      url: 'https://smba.trafficmanager.net/amer/v3/conversations/a%3A1MUpsVB7CH-6BTiSUHxOkMhv05saxu9O7qe0zRNPR04PCvXp-6QzsoYKpT-oykqyJpu8SgbawTkbUDauiBGF9bIeG9qg56Ts6lpEGgY6SSrMMj5YL_K-yxOJ5jjoqIrJQ/activities',
>      method: 'POST',
>      headers: HttpHeaders { _headersMap: [Object] },
>      body: '{"type":"message","serviceUrl":"https://smba.trafficmanager.net/amer/","channelId":"msteams","from":{"id":"c96afa27-addb-4bc8-80fb-c0317380bf1a","name":"Luna"},"conversation":{"id":"a:1MUpsVB7CH-6BTiSUHxOkMhv05saxu9O7qe0zRNPR04PCvXp-6QzsoYKpT-oykqyJpu8SgbawTkbUDauiBGF9bIeG9qg56Ts6lpEGgY6SSrMMj5YL_K-yxOJ5jjoqIrJQ"},"text":"Achei aqui! A OV de número 0001302956","inputHint":"acceptingInput"}',
>      query: undefined,
>      formData: undefined,
>      withCredentials: false,
>      abortSignal: undefined,
>      timeout: 0,
>      onUploadProgress: undefined,
>      onDownloadProgress: undefined,
>      operationSpec: {
>        httpMethod: 'POST',
>        path: 'v3/conversations/{conversationId}/activities',
>        urlParameters: [Array],
>        requestBody: [Object],
>        responses: [Object],
>        serializer: [Serializer]
>      }
>    },
>    response: {
>      body: '{"message":"Authorization has been denied for this request."}',
>      headers: HttpHeaders { _headersMap: [Object] },
>      status: 401
>    },
>    body: { message: 'Authorization has been denied for this request.' }
>  }

```

**Comment by vinisbranco** [comment]
@JonathanFingold can someone help me with this problem?

**Comment by JonathanFingold** [comment]
I'll try to get someone from support to reach out to you.

**Comment by mdrichardson** [comment]
Hi @vinisbranco 

It looks like you're not passing in a conversationReference to `continueConversation()`. Especially with Teams, there's quite a bit of required information for the conversationReference to contain. You can build the conversationReference manually (very hard), but it's really best to capture them when the user converses with the bot. See [this sample](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/57.teams-conversation-bot), particularly [where it calls `continueConversation`](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/57.teams-conversation-bot/bots/teamsConversationBot.js#L161)

**Comment by vinisbranco** [comment]
@mdrichardson I've tried to change my code, but continues the error

This is my continueConversation()
![Captura de tela de 2020-08-14 12-59-02](https://user-images.githubusercontent.com/28357433/90269195-9fdacd00-de2e-11ea-97a6-661f24e1187e.png)

Capturing the conversationReference when the user converses eith the bot
![Captura de tela de 2020-08-14 13-00-16](https://user-images.githubusercontent.com/28357433/90269345-dd3f5a80-de2e-11ea-960e-47973315e34b.png)

What is in the conversation Rerence when I call continueConversation()
![Captura de tela de 2020-08-14 12-58-16](https://user-images.githubusercontent.com/28357433/90269433-ffd17380-de2e-11ea-9e31-0a66bd9c33c6.png)

And the response
![Captura de tela de 2020-08-14 13-01-21](https://user-images.githubusercontent.com/28357433/90269489-18418e00-de2f-11ea-97c6-f070325ba7ef.png)

**Comment by mdrichardson** [comment]
I believe that the Bot Framework pieces of the code are correct.

1. I'm assuming that in the top picture `conversationReference` is defined by a call to your `db` and that it's returning the correct ConversationReference?
2. What does `model.render()` return? It _must_ return a valid activity. In your last picture, the "response" one, it shows `"activity": null`. I don't recall is the `HttpResponse.request` will contain the activity or not, but that seems like a possible issue.
3. Does [this sample](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/57.teams-conversation-bot?rgh-link-date=2020-08-13T23%3A21%3A16Z) work for you?

**Comment by vinisbranco** [comment]
@mdrichardson 

1. Yes, in my previous message in the third picture, is the response of db

2. 
![Uploading Captura de tela de 2020-08-14 16-50-37.png…]()

3. The sample works normal

4. Yes, this is the code https://github.com/vinisbranco/hyper-automation/tree/master/functions 
 and appId: df21894e-7d58-43e8-95bf-7492028c4e04

**Comment by mdrichardson** [comment]
@vinisbranco Thank you for including your code!!!!!!!!!! I don't think I would've figured this out, otherwise.

The issue is that in `sendMessage.f.js`, you're [instantiating a new `BotFrameworkAdapter`](https://github.com/vinisbranco/hyper-automation/blob/master/functions/message/sendMessage.f.js#L17), which differs from the one instantiated [in `gateway.f.js`](https://github.com/vinisbranco/hyper-automation/blob/master/functions/chatBot/gateway.f.js#L7), which you use to create the conversationReference.

They *look* the same because you're passing in the same appId/password, but [their `BotIdentityKey` differs](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/botAdapter.ts#L32) because the key is generated using `Symbol()`, which as you may know, [guarantees a unique key gets generated every time it's called, even with the same input.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Description)

If you want to keep them in separate files, I'd recommend exporting your adapter in `gateway.f.js` and importing it in `sendMessage.f.js`.

*Note: I confirmed this was the issue by running Sample 57, verifying it worked, then instantiating a new adapter in the proactive message section. I, too, got the 401 error.*

**Comment by mdrichardson** [comment]
@vinisbranco Did this end up fixing your issue?

**Comment by vinisbranco** [comment]
Yes @mdrichardson, I rewrite the code based on the sample and worked for me. Thank you a lot for the support!
