### ISSUE TITLE
The attachmen Error.

### ISSUE THREAD

**Issue by RafaNv** [MicrosoftDocs/bot-docs#1861]
I need sends image like attachment by dll graph c# and return error: "Failed to process content in attachment".
The attachment content is a image Base64 used according to documentation but it doesn't work.

Documentation 
https://docs.microsoft.com/es-es/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#attachment-object

The code show how I did.:

    var file3 = ImageToBase64(model.URL);
    var chatMessage = new ChatMessage
    {
        Body = new ItemBody
        {
	       ContentType = BodyType.Html,
	        Content = model.Content
        },

        Attachments = new List<ChatMessageAttachment>()
        {
            new ChatMessageAttachment
            {
                Id="123",
                ContentType = " image/png",
                Content = file3,
                Name = "Spread_Anywhere.png"

              }
          }
     };

	await _client.Teams[model.GroupId].Channels[model.ChannelId].Messages.Request().AddAsync(chatMessage);
		
      public string ImageToBase64(string path )
      {

	    using (System.Drawing.Image image = System.Drawing.Image.FromFile(path))
	    {
		 using (MemoryStream m = new MemoryStream())
		 {
			 image.Save(m, image.RawFormat);
			 byte[] imageBytes = m.ToArray();
			 base64String = Convert.ToBase64String(imageBytes);
			 return base64String;
		  }
	     }
      }

**Comment by stevkan** [comment]
@RafaNv, can you tell me the size of the image you are trying to send?

**Comment by stevkan** [comment]
Closed due to lack of activity. If the issue persists, please feel free to re-open.

**Comment by RafaNv** [comment]
@stevkan 
10 kb the size of the image.

**Comment by RafaNv** [comment]
@stevkan 
I would apologise to him for the delay. Can you help me? Can you show examples?
