### ISSUE TITLE
Slack bot app creation has changed such that screenshots and steps are no longer valid

### ISSUE THREAD

**Issue by FuzzAU** [MicrosoftDocs/bot-docs#1862]
Starting at the step "Create a Slack Bot User" the screenshots and steps are no longer valid.  

The following steps are now inconsistent with the Slack interface:

- Where "Bot Users" was an option on the left hand menu, there is now a "Where's Bot User" option. Clicking this explains that Bot User has moved to "App Home". 
- At this point the user is required to make a "Bot Token" and create Scopes (which is reference in #1831)
- The bot is then given a default display name and default name based on the name of the app.

The remainer of the documentation seemed to go as expected.

I suggest the note at the end of the document related to scopes be moved higher to draw users attention to it. I didn't read it as I thought it was related to the "Create an Add to Slack button" section.

Thank you for all your hard work keeping the MS docs awesome!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @arturl
* Microsoft Alias: **arturl**

**Comment by JonathanFingold** [comment]
I'm hoping to get to this article in the next week or two, to address this issue, as well as issue [1831](https://github.com/MicrosoftDocs/bot-docs/issues/1831).

**Comment by mmiele** [comment]
The fix will be available in the next documentation update.
