### ISSUE TITLE
Availability of DirectLine App Service Extension for Python SDK 

### ISSUE THREAD

**Issue by vijaysaimutyala** [MicrosoftDocs/bot-docs#1863]
It was mentioned in the issue https://github.com/microsoft/botbuilder-python/issues/829 that Direct Line App Service Extension 
is not available for Python SDK because of Linux App Service not supporting Streaming Extension. I was not able to find if WebSocket support for Linux App Service is available now. I want to understand that if its available, are there any plans of supporting Direct Line App Service Extension for the Python SDK?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 665ea3ca-8796-7cc2-acda-c2a0a5f93912
* Version Independent ID: b110b105-da18-e4bd-5b6c-2bb8b130e079
* Content: [Direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
I'll ask one of the devs.

**Comment by JonathanFingold** [comment]
@vijaysaimutyala The team has plans to implement this for Python, but they don't have a firm date for it yet. I hesitate to make a prediction as to when this will be available for Python.

**Comment by vijaysaimutyala** [comment]
Thanks @JonathanFingold
