### ISSUE TITLE
[Docs] Direct Line app service extension | endpoint for ASE given as "azurewebsite.net"

### ISSUE THREAD

**Issue by MeenakshiBalekar** [MicrosoftDocs/bot-docs#1866]
Document mentions the bot endpoint to be "azurewebsite.net" where in if the same is behind ASE it will be https://<Name>.appserviceenvironment.net/api/messages 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72c259-a864-9e1c-b585-562d6bca80ff
* Version Independent ID: 30a3fce8-d236-5c7b-88a0-003c971f2819
* Content: [.NET bot with direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by anusharavindrar** [comment]
@MeenakshiBalekar, thanks for the feedback. The current document is specific to enabling the direct line app service extension in the Azure App Service resource where the bot is hosted and not for the App Service Environment scenario. For more details about using the ASE, please refer to https://docs.microsoft.com/en-us/azure/app-service/environment/using-an-ase#app-access
