### ISSUE TITLE
[Docs] Direct Line app service extension | Node JS doc has appsetting.json mentioned instead of .env

### ISSUE THREAD

**Issue by MeenakshiBalekar** [MicrosoftDocs/bot-docs#1867]
[Enter feedback here]
This document mentions that at point number 6 about the appsetting.json where in it should be .env file as this is about node Js.

Point 6. Open the appsettings.json file and enter the following values:

"MicrosoftAppId": "<secret Id>"
"MicrosoftAppPassword": "<secret password>"

Could you please correct the same, this will help avoid confusions for many.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 206a361d-42ef-ed02-9c1d-5775395aa7a9
* Version Independent ID: d122568b-a72e-7087-03db-a0aa386094b9
* Content: [Node.js bot with direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-node-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-node-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-node-bot.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **dev**

**Comment by anusharavindrar** [comment]
@MeenakshiBalekar, thanks for the feedback. The changes have already been checked in along with the other corrections and will be live soon.
