### ISSUE TITLE
[Docs | Issue while accessing webchat] Directline app service extension | Webchat mentions azurewebsites.net

### ISSUE THREAD

**Issue by MeenakshiBalekar** [MicrosoftDocs/bot-docs#1868]
[Enter feedback here]
This article mentions in the webchat that the domain needs to be "https://<your_app_service>.azurewebsites.net/.bot/v3/directline"

Where in the endpoint which is created with ASE azure bot will be "https://<botname>.appserviceenvironment.net/api/messages

So should we use "azurewebsites.net" or " appserviceenvironment.net" while making a call to ASE azure web app bot with directline extension keys? If this needs to be " appserviceenvironment.net", kindly make the changes in the document :) 

Also, when we are using both, we get below error in browser :

![image](https://user-images.githubusercontent.com/58509122/90160180-10420980-ddaf-11ea-88e4-cc72dd43e0b5.png)

Please help with this request

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e3a6ed6-7d29-d82e-c86f-8f405ab12fe3
* Version Independent ID: 6a4ba6ea-51df-929f-e307-38c4a1f9b889
* Content: [Use Web Chat with the direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-webchat-client?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-webchat-client.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-webchat-client.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@MeenakshiBalekar The domain is where the bot is hosted.  For example, in Azure is  https://<bot_name>.azurewebsites.net/' as described in the example. The updated documentation will be in the next available release.

**Comment by mmiele** [comment]
The updated documentation will be in the upcoming release.
