### ISSUE TITLE
LINE Channel problem

### ISSUE THREAD

**Issue by rungsoso** [MicrosoftDocs/bot-docs#1869]
I connected the bot to LINE chanel according to this document https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-line?view=azure-bot-service-4.0 But all messages reply to users with push messages (paid messages), why not reply to messages (free messages)?

**Comment by anusharavindrar** [comment]
Issue resolved in this [comment](https://github.com/microsoft/BotFramework-Services/issues/246#issuecomment-682199722).
