### ISSUE TITLE
Actual telemetry from QnAMaker doesn't include question

### ISSUE THREAD

**Issue by savagemonitor** [MicrosoftDocs/bot-docs#1871]
I've instrumented my bot as per the [Add Telemetry To Your Bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0&tabs=csharp) page as well as the [QnA specific](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-qnamaker?view=azure-bot-service-4.0) page but when I tried to run a query based on the documentation in this article the "question" custom field is not present.

I'm currently on 4.9.1 of the bot framework and the only mention of a version that needs to be supported is 4.2.  Does the documentation need to be updated to reflect a specific version of the bot framework or have the "question" field removed?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdfeb662-d60b-d832-9290-c4d03233e84d
* Version Independent ID: e736a8ef-67cd-72b1-9d74-d542beeefed8
* Content: [Analyze the telemetry data from your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-analytics-queries?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-telemetry-analytics-queries.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-telemetry-analytics-queries.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@savagemonitor - The QnA Maker `question` data should show up as one of the `customDimensions` fields, if I understand correctly.

**Comment by savagemonitor** [comment]
@JonathanFingold I actually tracked this down and should have updated the issue.

In order to get the question out of the QnaMaker PII must be turned on through an additional parameter to the constructor:

    var qnaMaker = new QnAMaker(new QnAMakerEndpoint
            {
                KnowledgeBaseId = _configuration["QnAKnowledgebaseId"],
                EndpointKey = _configuration["QnAEndpointKey"],
                Host = _configuration["QnAEndpointHostName"]
            },
            null,
            httpClient,
            _telemetryClient,
            true); // <- this gets you the Question as well as who asked it.

This wasn't clear from even the docs about the [QnAMaker class](https://docs.microsoft.com/en-us/javascript/api/botbuilder-ai/qnamaker?view=botbuilder-ts-latest) though that's a different issue.

The way I found this out was by looking through the source code.

Ideally this would be documented in the table at the bottom of the page and on [Add telemetry to your QnA bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-qnamaker?view=azure-bot-service-4.0) page as well.

**Comment by dmvtech** [comment]
> This wasn't clear from even the docs about the QnAMaker class though that's a different issue.
> 
> The way I found this out was by looking through the source code.
> 
> Ideally this would be documented in the table at the bottom of the page and on Add telemetry to your QnA bot page as well.

@JonathanFingold Looks like this is more docs issue than support. If so, can you remove the label? If not, let me know.

**Comment by JonathanFingold** [comment]
Okay, thanks all for clarifying. I'll remove the support tag, and we'll update the docs.
