### ISSUE TITLE
Implementing Middleware with Bot Composer

### ISSUE THREAD

**Issue by Silu321** [MicrosoftDocs/bot-docs#1874]
Hello, Team
I am trying to implement Middleware with bot composer but there is no documentation or guidance can you please point out the correct documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c0c0448-d72d-3451-0b83-89b2fc93e0ab
* Version Independent ID: e3c31f64-02c7-046a-6a1f-a7408d68e5af
* Content: [Generators in adaptive dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-dialog-Generators?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-concept-adaptive-dialog-generators.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-adaptive-dialog-generators.md)
* Service: **bot-service**
* GitHub Login: @emgrol
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
We do have an article about middleware in SDK. 
In Composer, you can [eject the runtime](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#eject-bot-runtime) and then implement middleware follow the instruction in the [doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-middleware?view=azure-bot-service-4.0).

**Comment by zxyanliu** [comment]
We do not have a specific topic describing middleware implementation, but there will be a couple of new docs coming out for R11 (by November), including a doc describing Composer runtime (C# and JS). By then, users will have a clearer idea of what's inside the runtime, how to open a project in Visual Studio, etc.

You can also cut a ticket here: https://stackoverflow.com/questions/tagged/botframework

**Comment by zxyanliu** [comment]
I transferred this issue to here:
https://github.com/MicrosoftDocs/composer-docs/issues/9
Closing the issue for now since it seems to be a feature request for Composer docs instead of SDK docs. Thanks!
