### ISSUE TITLE
Missing javascript sample code in application insights docs

### ISSUE THREAD

**Issue by Christopher154** [MicrosoftDocs/bot-docs#1875]
Location: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0&tabs=javascript#enabling-telemetry-to-capture-usage-data-from-other-services-like-luis-and-qna-maker

Issue: In the fourth bullet point of this section it alludes to some sample code with the box used to display sample code being displayed below the bullet point, however it's empty

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db892de5-e60e-1d4f-505b-11b1cdb73323
* Version Independent ID: f7263014-b8fa-9a20-71aa-e4217b2821ee
* Content: [Add telemetry to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-telemetry.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-telemetry.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
Thank you for reporting this, the link to the sample's source code was off by one. Fixed, will go live the next time the master branch gets pushed live. This was due to the sample source being changed since the article was written.
