### ISSUE TITLE
Directline Ase return {"v":"123","k":true,"ib":fase,"ob":fase,"initialized":true} sometimes

### ISSUE THREAD

**Issue by fifteenjoy** [MicrosoftDocs/bot-docs#1876]
Hi,

I got a very strange status.

I have activated  Directline ASE successfullly. when I access
 _http://XXXXXX/.bot_, it return 
_{"v":"123","k":true,"ib":true,"ob":true,"initialized":true}_

But sometimes, "ib" and "ob" is get false automatically. like below
_{"v":"123","k":true,**"ib":false,"ob":false,**"initialized":true}_
In this case, I refresh http://XXXXXX/.bot mannuly in browser, then everything is correct again, "ib" and "ob" get "true"

My question is :

why "ib" and "ob" get false , what should I do to avoid this situation happen ?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72c259-a864-9e1c-b585-562d6bca80ff
* Version Independent ID: 30a3fce8-d236-5c7b-88a0-003c971f2819
* Content: [.NET bot with direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by anusharavindrar** [comment]
@fifteenjoy, there are typically only three reasons for the IB/OB values to be false:

- The bot is failing to start up correctly, which would mean it's not available through any channel

- The named pipe code added to the bot's startup/index was incorrect

- The App Service needs to be restarted to sync the bot and channel

Hope this helps.

**Comment by fifteenjoy** [comment]
Hi, 

Please do not close this issued, I think this bug is not fixed yet.

**My question is sometimes  IB/OB  get false **automatically sometimes**, most of time they are true.**

--The bot is failing to start up correctly, which would mean it's not available through any channel
My response:   Where I can start up bot in azure? 

--The named pipe code added to the bot's startup/index was incorrect
--  the named pipe code is copy form document    
"app.UseNamedPipes(System.Environment.GetEnvironmentVariable("APPSETTING_WEBSITE_SITE_NAME") + ".directline");"  .   

--The App Service needs to be restarted to sync the bot and channel
I didnot restart the App Service, IB/OB  get false suddenly(In that case I got 500 error )

**Comment by fifteenjoy** [comment]
Hi anusharavindrar,

Sorry, May be I did not make me clear.

Refresh the url is working for me.  But Because My chat bot is going to release, I dont want to refresh the url  manually,  I would like bot and DirectLine ASE communicate to each other smoothly all the time，

In a word,   I just want to aoid that "ib and ob values get false suddenly  with unknow reason" , this situation. 

Many thanks.
