### ISSUE TITLE
Documentation does not explain importResolver

### ISSUE THREAD

**Issue by JPalmerDev** [MicrosoftDocs/bot-docs#1880]
In the LG In Action section, it uses some sample code that uses an importResolver.
Nowhere in these docs does it define what this resolver is, or how it should be used.
You can make a function that fulfill's the signature for the delegate, but this doesn't communicate to a developer what they're supposed to write to make this code work or adequately parse the file correctly.

I'm currently going to console writeline what the parameters passed in are, otherwise I'm stuck and don't know how I should proceed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59573a90-7a7a-418c-f661-90f53a00e47d
* Version Independent ID: cec084c0-0823-0c68-887c-bc660ac109cc
* Content: [Language Generation - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-language-generation?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-concept-language-generation.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-language-generation.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for letting us know about the incorrect information @JPalmerDev. I updated the snippets in https://github.com/MicrosoftDocs/bot-docs-pr/pull/2440, the changes should go live.

**Comment by emgrol** [comment]
Closing now that the changes are live.
