### ISSUE TITLE
Blob transcript storage section is out of date as of 4.10

### ISSUE THREAD

**Issue by stevengum** [MicrosoftDocs/bot-docs#1882]
Section **Blob Transcript Storage** is out of date. ([Current](https://github.com/MicrosoftDocs/bot-docs/blob/f43ee82dc8ba7298b7d1d015a1902b1be948d218/articles/v4sdk/bot-builder-howto-v4-storage.md#blob-transcript-storage))

![image](https://user-images.githubusercontent.com/14935595/90911982-a6b59280-e38e-11ea-88a6-36045d3a26ef.png)

AzureBlobTranscriptStorage is deprecated in C#, and users should now use [BlobTranscriptStore](https://github.com/microsoft/botbuilder-dotnet/pull/4419), per @EricDahlvang.

AzureBlobTranscriptStore _is_ available in [JS](https://github.com/microsoft/botbuilder-js/blob/015ebb7c24a7dc50320fe34f13e84e6b5a4fcdbc/libraries/botbuilder-azure/src/azureBlobTranscriptStore.ts), but not in [Python](https://github.com/microsoft/botbuilder-python/tree/fcfd6a25c23c75fa524b373232b1a174cec41e98/libraries/botbuilder-azure/botbuilder/azure).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&amp%3Btabs=csharp&tabs=csharp#blob-transcript-storage)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Fix is in PR.
