### ISSUE TITLE
Consistently refer to user auth as user auth

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1885]
Followup issue to https://github.com/MicrosoftDocs/bot-docs/issues/1745

@mmiele clarified the difference between bot auth and user auth in this PR: https://github.com/MicrosoftDocs/bot-docs-pr/pull/2343

However, many places in the docs still refer to user authentication as bot authentication, like in this doc: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-security-guidelines

We will need to search the repo for "bot auth" and replace it with "user auth" when appropriate. This is especially important when it refers to the now-changed article title.

There will also need to be a PR in the sample repo, because the samples also refer to user auth as bot auth.

**Comment by mmiele** [comment]
@JonathanFingold Let's discuss how we want to handle this in the R11 timeframe.

**Comment by mmiele** [comment]
mm-bot-auth-cleanup MicrosoftDocs/bot-docs-pr#2387 in review

**Comment by mmiele** [comment]
The cleanup will be available in the next available doc update.
