### ISSUE TITLE
implement a #translator using #middleware with Bot composer

### ISSUE THREAD

**Issue by Silu321** [MicrosoftDocs/bot-docs#1887]
Hello, team
I am trying to implement a #translator using #middleware with Bot composer But there is no documentation or guidance Can you please point out the correct documentation?

**Comment by zxyanliu** [comment]
We do not have a specific topic describing middleware implementation, but there will be a couple of new docs coming out for R11 (by November), including a doc describing Composer runtime (C# and JS). By then, users will have a clearer idea of what's inside the runtime, how to open a project in Visual Studio, etc.

**Comment by zxyanliu** [comment]
https://github.com/MicrosoftDocs/bot-docs/issues/1874
