### ISSUE TITLE
Python Azure deployment issue

### ISSUE THREAD

**Issue by gavindavies** [MicrosoftDocs/bot-docs#1889]
ARM template had issues at first, so I manually created the resources as defined in the JSON, and then zipped up the Python Bot Sample and deployed it. Worked fine on my local machine, however steps to deploy on Azure are nebulous and invalid.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/30958981/91419021-d2cb8a80-e84a-11ea-8a4e-d8609d6c27a5.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/30958981/91419024-d4954e00-e84a-11ea-8e76-f689798c6341.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=python%2Cvs%2Ccsharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by jwiley84** [comment]
Thank you for your patience on this. The ARM templates have been updated. Please use an ARM template from a current sample and attempt to redeploy. I'm going to close this issue. If you continue to have the same problem with deploying, please comment and I will reopen.

**Comment by Mikhail2k15** [comment]
The same issue 
Please provide string value for 'botSku' (? for help): S1
Please provide string value for 'newAppServicePlanName' (? for help): mibonsentimentkvbotplan
Please provide string value for 'newAppServicePlanLocation' (? for help): westus
Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The resource 'Microsoft.Web/serverfarms/mibonsentimentkvbotplan' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.
Additional Information:
        Type: TemplateViolation
        Info: {
            "lineNumber": 0,
            "linePosition": 0,
            "path": ""
        }
