### ISSUE TITLE
Login with Microsoft Teams account

### ISSUE THREAD

**Issue by baole** [MicrosoftDocs/bot-docs#1891]
I'm not sure this is the right place to ask this question. I build a chat bot for Microsoft Teams. The bot has a companion web app to handle settings and other tasks. I would like to offer a "Login with Microsoft Teams" feature where users can login to the companion web app with their Microsoft Teams account. Is it possible to implement such feature? It's nice if you can point me to the right documents/tutorials/user guides.

**Comment by JonathanFingold** [comment]
There are a number of topics that touch on this.
- [How Microsoft Teams bots work](https://docs.microsoft.com/azure/bot-service/bot-builder-basics-teams?view=azure-bot-service-4.0)
- [Bot authentication](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-authentication?view=azure-bot-service-4.0)
- How to [Add authentication to a bot](https://docs.microsoft.com/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0)
