### ISSUE TITLE
Step 4 header is not a header.

### ISSUE THREAD

**Issue by mmartijnNL** [MicrosoftDocs/bot-docs#1892]
Just a small styling issue, but it can cause people to skip over step 4.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0b8671-359e-6026-fd3a-39331cea73f3
* Version Independent ID: 29bab4ad-243a-fb0a-99ed-d8336a92f648
* Content: [Develop DirectLine Speech Bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0)
* Content Source: [articles/directline-speech-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/directline-speech-bot.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Waiting for the fix to be published.

**Comment by mmiele** [comment]
Fix will be available in the next upcoming documentation update.
