### ISSUE TITLE
Case sensitive parameters when creating the webhook

### ISSUE THREAD

**Issue by johnkellyjr** [MicrosoftDocs/bot-docs#1894]
[Enter feedback here]
Both "Resource" and "Event" are case sensitive, and need to be all lower case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e61be5-e537-8678-f907-10f27ea7bf90
* Version Independent ID: e2a9d88e-0819-9de5-d6f8-48bf7b270685
* Content: [Connect a bot to Webex Teams - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-adapter-connect-webex?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-adapter-connect-webex.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-adapter-connect-webex.md)
* Service: **bot-service**
* GitHub Login: @garypretty
* Microsoft Alias: **gapretty**

**Comment by johnkellyjr** [comment]
Has anyone had success with this working? I can use the bot to test with Azure, and it will echo responses fine there. I am able to have WebEx recognize the bot, in that it allows me to add it to a Teams chat. Beyond that, I have never gotten it to echo a response in WebEx Teams. Am I missing something?

**Comment by mmiele** [comment]
Fix will be available in the next upcoming documentation update.
