### ISSUE TITLE
Slack configuration UI is changed

### ISSUE THREAD

**Issue by xieofxie** [MicrosoftDocs/bot-docs#1897]
It doesn't have a Bot User now, and it uses App Home instead:

![image](https://user-images.githubusercontent.com/2876650/92355144-45bfe580-f116-11ea-8ed4-bef6d12337d7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @arturl
* Microsoft Alias: **arturl**

**Comment by mmiele** [comment]
See issue https://github.com/MicrosoftDocs/bot-docs/issues/1897.

**Comment by mmiele** [comment]
The fix will be available in the next documentation update.
