### ISSUE TITLE
more documentation needed

### ISSUE THREAD

**Issue by mmartijnNL** [MicrosoftDocs/bot-docs#1898]
Hi,
Can you provide more documentation / example code?

With the original DirectLine (without ASE) we could set a watermark when calling createDirectLine() to get some chat history, see below. Is there a similar functionality for DirectLine ASE?
```
const directLine = createDirectLine( {
      token,
      webSockets: true,
      watermark: 10
    } );
```
I feel like there is no documentation for the createDirectLineAppServiceExtension() method.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e3a6ed6-7d29-d82e-c86f-8f405ab12fe3
* Version Independent ID: 6a4ba6ea-51df-929f-e307-38c4a1f9b889
* Content: [Use Web Chat with the direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-webchat-client?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-webchat-client.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-webchat-client.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@mmartijnNL Let me look into it. Thanks

**Comment by mmiele** [comment]
@mmartijnNL Please, look at this https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/bundle/src/createDirectLineAppServiceExtension.js. It might help.

**Comment by mmartijnNL** [comment]
@mmiele Thanks! I have decided to use the regular Direct Line without the extension and I got everything working. Nevertheless I do think that that article could help others.

**Comment by mmiele** [comment]
@mmartijnNL I ma glad you solved your problem. Thank you for your feedback, I will follow up on that.
