### ISSUE TITLE
Additional Azure Ad App needed if the external secured resource is Microsoft Graph?

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/bot-docs#1903]
[Enter feedback here]
>>Whenever you register a bot in Azure, it gets assigned an Azure AD application. However, this >>application secures channel-to-bot access. You need an additional Azure AD application for each >>external secured resource you want the bot to access on behalf of the user.

Can you clarify  if the Bot Azure AD App can be reused if the only external secured resource we want the bot to access the on behalf of the user is the Microsoft Graph which is a first party app? Do we absolutely need a additional Azure AD App for accessing the Microsoft Graph with delegated permissions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@GauravES Let me look into it and I will come back to you. Thanks

**Comment by mmiele** [comment]
@GauravES As of now, the Azure Bot Service and v4 SDK has authentication capabilities to make it easier to authenticate users to various identity providers such as GitHub, Azure AD, Google, etc. Whenever you register a bot in Azure, it gets assigned an Azure AD app. This app **secures channel-to-bot access**. As a general guideline and good practice, you need an additional AAD app for any application that you want the bot to be able to authenticate on behalf of the user.

**Comment by mmiele** [comment]
@GauravES 
The suggested best practices are: 

- Keep the AAD app (registration) restricted to it’s original purpose of being service to service application. 
- Create an additional AAD app for any user to service authentication, for more finite control over disabling authentication connections, rolling secrets, or reusing the AAD app with other applications.

Some of the problems that you can encounter if you use the AAD registration app for authentication are:

- If the certificate attached to the AAD app (registration) needs to be renewed it would impact users that have authenticated to other AAD services using it.
- In general it creates a single point of failure and control for all things authentication related to the bot.

**Comment by mmiele** [comment]
Added explanation to the documentation.
