### ISSUE TITLE
Command to deploy bot creates unwanted app service plan

### ISSUE THREAD

**Issue by DoofyFTW** [MicrosoftDocs/bot-docs#1904]
Hello,
in section _4. Deploy via ARM template / Deploy via ARM template with existing Resource Group / Option 1: Existing App Service Plan_ the command creates new App Service plan.
the command is same as the one in _Option 2: New App Service Plan_ 

I expect that the two commands should be different.

**Comment by emgrol** [comment]
Hi @DoofyFTW, the commands are slightly different. The existing app service plan uses the parameter `existingAppServicePlan` while the new app service plan command uses the parameter `newAppServicePlanName`.

**Comment by emgrol** [comment]
Closing now, the docs are up accurate.
