### ISSUE TITLE
Example for 'Oauth 2 Generic Provider' needs update

### ISSUE THREAD

**Issue by xieofxie** [MicrosoftDocs/bot-docs#1905]
Current fields are:
(Basically, provide Query String Template as ?)
![image](https://user-images.githubusercontent.com/2876650/93174813-3c132f00-f761-11ea-8c4e-68844bb79499.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb435f0d-6418-4868-9e50-e73348f5fabc
* Version Independent ID: ba585475-9607-26a7-f14f-56b71cdb5596
* Content: [Identity providers Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-identity-providers?view=azure-bot-service-4.0&tabs=adv1%2Cga2)
* Content Source: [articles/v4sdk/bot-builder-concept-identity-providers.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-identity-providers.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@xieofxie Could you please specify the missing field? Thanks

**Comment by xieofxie** [comment]
@mmiele My bad.. I clicked on the wrong panel..
