### ISSUE TITLE
Cant See Cortana option in Bot Channels. Does it have any Eligibility?

### ISSUE THREAD

**Issue by mandar003** [MicrosoftDocs/bot-docs#1908]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d57239-40c4-16b9-8f33-b4ccd910158f
* Version Independent ID: 7e275b0e-8352-9beb-aa35-80177d69b7c8
* Content: [Connect a bot to Cortana - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-cortana?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-cortana.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-cortana.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@mandar003 Could you please be more specific about the problem you are experiencing? 
We will be able to help you better.
