### ISSUE TITLE
URL in samples for Direct Line connection seems to be incorrect

### ISSUE THREAD

**Issue by haacked** [MicrosoftDocs/bot-docs#1909]
I'm following the docs here to try and connect to my bot hosted in Azure using DirectLine.

The code sample shows the following line:

```csharp
string endpoint = "https://<your_bot_name>.azurewebsites.net/.bot/";
string secret = "<your_bot_direct_line_secret_key>";

var tokenClient = new DirectLineClient(
    new Uri(endpoint),
    new DirectLineClientCredentials(secret));
var conversation = await tokenClient.Tokens.GenerateTokenForNewConversationAsync();
```

I replace `<your_bot_name>` and `<your_bot_direct_line_secret_key>` with my values. I was able to create a conversation token. But after that, any attempt I had to create new conversations or to post activities resulted in 404 responses.

When I changed the endpoint to `https://directline.botframework.com/` everything worked. So unless I'm misunderstanding the documentation, the code sample is incorrect or misleading and the endpoint URL should be `https://directline.botframework.com/`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c463a003-c709-b516-ce1b-6c45537de3b2
* Version Independent ID: 8ca42668-23ac-6dca-054d-d183b0fb5b0b
* Content: [Create .NET client for direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-client.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-client.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@haacked Did you intend to use the app service extension or just want to enable the Direct Line channel?
I tested the steps as specified in the article [Create .NET client for direct line app service extension](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0). The endpoint as specified is working. Please, let me know.

**Comment by haacked** [comment]
I think I got confused. What's the difference between the service extension and the Direct Line channel? When would I use one or the other?

I think in my case, I just wanted to use the Direct Line channel to post messages to my bot. I couldn't find docs for that scenario. The closest thing I found was the docs for the service extension.

**Comment by mmiele** [comment]
Code sample error.

**Comment by mmiele** [comment]
@haacked Our apologies for the confusion. I have raised the bar to improve the documentation. Were you able to solve your problem? Would you mind to let me know how? Thanks

**Comment by mmiele** [comment]
@haacked  The following is a simple console client that uses Direct Line (not he extension!). Hope it helps.

```csharp

using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Bot.Connector.DirectLine;

namespace Direct_Line_Client
{
    class Program
    {
        static void Main(string[] args)
        {
            Task.WaitAll(Run());
        }

        public static async Task Run()
        {
            // Direct Line endpoint for messages.
            var endpoint = "https://<your bot app service name>.azurewebsites.net/.bot/";
            // Direct Line secret key.
            var secret = "<yout direct line secret key";

            var userId = Guid.NewGuid().ToString();
            var userName = "Fred";

            Console.WriteLine("Connecting...");

            var tokenClient = new DirectLineClient(
            new Uri(endpoint),
            new DirectLineClientCredentials(secret));
            var tokenConversation = await tokenClient.Tokens.GenerateTokenForNewConversationAsync().ConfigureAwait(false);

            var client = new DirectLineClient(
                new Uri(endpoint),
                new DirectLineClientCredentials(tokenConversation.Token));

            await client.StreamingConversations.ConnectAsync(
                tokenConversation.ConversationId,
                ReceiveActivities).ConfigureAwait(false);

            var conversation = await client.StreamingConversations.StartConversationAsync().ConfigureAwait(false);

            Console.WriteLine($"Connected to conversation {conversation.ConversationId}");

            Console.Write("> ");
            var message = Console.ReadLine();

            while (message != "end")
            {
                try
                {
                    var response = await client.StreamingConversations.PostActivityAsync(conversation.ConversationId,
                        new Activity()
                        {
                            Type = "message",
                            Text = message,
                            From = new ChannelAccount()
                            {
                                Id = userId,
                                Name = userName
                            }
                        }).ConfigureAwait(false);
                }
                catch (OperationException ex)
                {
                    Console.WriteLine($"OperationException when calling PostActivityAsync: ({ex.StatusCode})");
                }
                Console.Write("> ");
                message = Console.ReadLine();
            }

            client.StreamingConversations.Disconnect();
        }

        public static void ReceiveActivities(ActivitySet activitySet)
        {
            if (activitySet != null)
            {
                foreach (var a in activitySet.Activities)
                {
                    if (a.Type == ActivityTypes.Message && a.From.Id.ToLowerInvariant().Contains("bot"))
                    {
                        Console.WriteLine($"<Bot>: {a.Text}");
                        if (a.Attachments.Any())
                        {
                            foreach (var attachment in a.Attachments)
                            {
                                var stream = attachment.Content as Stream;
                                Task.Run(async () => {
                                    int count;
                                    int total = 0;
                                    byte[] buffer = new byte[4096];
                                    do
                                    {
                                        count = await stream.ReadAsync(buffer, 0, 4096);
                                        total += count;
                                    } while (count > 0);
                                    Console.WriteLine($"  Read stream of length: {total}");
                                });
                            }
                        }
                    }
                }
            }
        }
    }
}

```

**Comment by haacked** [comment]
@mmiele Your code uses `https://<your bot app service name>.azurewebsites.net/.bot/` which doesn't work unless you have the DirectLine ASE installed on your site. A standard Bot Framework site won't respond to `/.bot/`.

I was able to get my scenario to work by changing the URL to `https://directline.botframework.com/`. In my use case, I didn't need to use the streaming APIs, just the HTTP APIs.
