### ISSUE TITLE
Suggested Actions: Majority of the Javascript sample is missing

### ISSUE THREAD

**Issue by q00u** [MicrosoftDocs/bot-docs#1919]
Here it is in its entirety on the page:

```javascript
*/
async sendSuggestedActions(turnContext) {
    const cardActions = [
        {
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53446ad1-6b8c-1ccb-6e78-2cb14358b1c3
* Version Independent ID: 8b0fcc34-e624-64a9-adc8-6c8fa3031f54
* Content: [Use button for input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-suggested-actions?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-add-suggested-actions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-suggested-actions.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
@q00u Thanks for pointing out the misaligned snippet. It's been fixed in https://github.com/MicrosoftDocs/bot-docs-pr/pull/2418 and should go live shortly.

**Comment by emgrol** [comment]
Closing now that the fix is live.
