### ISSUE TITLE
Issue with the _ctor of WebexAdapterWithErrorHandler sample code

### ISSUE THREAD

**Issue by SonOfJesseAsSnekithan** [MicrosoftDocs/bot-docs#1921]
[Enter feedback here]
It should be::
public WebexAdapterWithErrorHandler(IConfiguration configuration, ILogger<BotFrameworkHttpAdapter> logger)
    : base(configuration, null, logger)
instead of 
public WebexAdapterWithErrorHandler(IConfiguration configuration, ILogger<BotFrameworkHttpAdapter> logger)
    : base(configuration, logger)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e61be5-e537-8678-f907-10f27ea7bf90
* Version Independent ID: e2a9d88e-0819-9de5-d6f8-48bf7b270685
* Content: [Connect a bot to Webex Teams - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-adapter-connect-webex?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-adapter-connect-webex.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-adapter-connect-webex.md)
* Service: **bot-service**
* GitHub Login: @garypretty
* Microsoft Alias: **gapretty**

**Comment by jwiley84** [comment]
Hi @SonOfJesseAsSnekithan Are you having issues with [this](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/62.webex-adapter) sample? If so, can you open this issue in the samples repo so we can take a look?

**Comment by mmiele** [comment]
Code sample error.

**Comment by jwiley84** [comment]
The code in the docs needs to be fixed to add the missing 'null'

**Comment by jwiley84** [comment]
For clarification: In the snippet under the heading "Create a Webex Adapter Class", there's a line of code (line 4) that reads 
`: base(configuration, logger)` 
but needs to read 
`: base(configuration, null, logger)`
