### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by vidyesh-phases** [MicrosoftDocs/bot-docs#1922]
The demo link provided is not working.
Link: [Demo](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/c.es5-bundle/)

Other demo links in [Bot Framework Web Chat](https://github.com/microsoft/BotFramework-WebChat) also not working.

**Comment by jwiley84** [comment]
What doc is this from so we can get the link fixed?

**Comment by vidyesh-phases** [comment]
This is the one: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/e.host-with-react/

Also, samples here also not working:
https://github.com/microsoft/BotFramework-WebChat/tree/master/samples

**Comment by jwiley84** [comment]
I'm not sure if the webchat team took mockbot down for maintenance earlier, but it's functioning now:

![image](https://user-images.githubusercontent.com/17333688/94589716-7c32e100-023a-11eb-96ad-70ff784d9bfa.png)


I'm  going to close this issue, as the Docs Team cannot fix mockbot if it goes down. If mockbot doesn't work in the future, please open an issue in the [Webchat](https://github.com/microsoft/BotFramework-WebChat ) repo, so they can take a look and fix it.
