### ISSUE TITLE
Add (promote) sidecar debugging technique

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/bot-docs#1923]
Add content & links for sidecar debugging technique in Emulator, & dev concepts. It is particularly useful when developing for different channels.

**Comment by JonathanFingold** [comment]
@scheyal - Who can bring one of us up to speed so that we can write this article?

**Comment by JonathanFingold** [comment]
@scheyal -- We have an article about how to [Debug a bot with inspection middleware](https://docs.microsoft.com/azure/bot-service/bot-service-debug-inspection-middleware) that seems to be the content you're looking for, though we don't call it _sidecar debugging_. What is the particular doc need here? Is it to make this content more discoverable?
