### ISSUE TITLE
Typo in JavaScript code: "Headers" should be "headers"

### ISSUE THREAD

**Issue by Pingulea** [MicrosoftDocs/bot-docs#1928]
When we perform the
const res = await fetch(...),
the options object should not be "Headers", but instead "headers".

I just lost one hour trying to figure out why do I get a 403 Forbidden from the DL extension when calling to get a token.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e3a6ed6-7d29-d82e-c86f-8f405ab12fe3
* Version Independent ID: 6a4ba6ea-51df-929f-e307-38c4a1f9b889
* Content: [Use Web Chat with the direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-webchat-client?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-webchat-client.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-webchat-client.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Fix will be available in the next upcoming documentation update.
