### ISSUE TITLE
Are we missing a step enabling Web Sockets?

### ISSUE THREAD

**Issue by Pingulea** [MicrosoftDocs/bot-docs#1929]
Web Sockets is enabled in 2 steps, not just one:

1. We should enable the Web Sockets for the Azure App Service in the Portal's UI, and
2. I think we also need to enable it in the **_Web.config_** with a 

```
<configuration>
    <system.webServer>
        **<webSocket enabled="true" />**
        ...
    </system.webServer>
</configuration>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e3a6ed6-7d29-d82e-c86f-8f405ab12fe3
* Version Independent ID: 6a4ba6ea-51df-929f-e307-38c4a1f9b889
* Content: [Use Web Chat with the direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-webchat-client?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-webchat-client.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-webchat-client.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Fix will be available in the next upcoming documentation update.
