### ISSUE TITLE
A list of error codes and what they may mean

### ISSUE THREAD

**Issue by irwinwilliams** [MicrosoftDocs/bot-docs#1930]
Trying to use OAuth 2 Generic Provider for the first time (with Strava's API).
And though I'm following documentation to the letter, I'm getting this error:
```
{
  "message": "Login failed",
  "statusCode": 401,
  "responseBody": "{\"message\":\"Authorization Error\",\"errors\":[{\"resource\":\"Application\",\"field\":\"\",\"code\":\"invalid\"}]}"
}
```
Which seems to be saying that the value "returned" for the code field is invalid. It seems that this is an error on the azure side, with respect to the request being made. Perhaps in the docs you can provide examples of why requests might fail and what steps can be taken to recover from such failures.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb435f0d-6418-4868-9e50-e73348f5fabc
* Version Independent ID: ba585475-9607-26a7-f14f-56b71cdb5596
* Content: [Identity providers Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-identity-providers?view=azure-bot-service-4.0&tabs=adv1%2Cga2)
* Content Source: [articles/v4sdk/bot-builder-concept-identity-providers.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-identity-providers.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@irwinwilliams Could you tell us what identity provider are you using? Thanks

**Comment by mmiele** [comment]
@irwinwilliams Also take a look at this article [Azure AD Authentication and authorization error codes](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes) and the the [OAuth2.0 spec](https://tools.ietf.org/html/rfc6749#section-5.2).
