### ISSUE TITLE
Document convert types safely

### ISSUE THREAD

**Issue by emgrol** [MicrosoftDocs/bot-docs#1931]
Related issues:
- https://github.com/microsoft/botbuilder-dotnet/issues/4773 - tracking
- https://github.com/microsoft/botbuilder-dotnet/issues/4615#issuecomment-705960670 - closed

Possible new functions:
- tryParseToJson
- tryParseToFloat
- tryParseToBool
- tryParseToBase64
- tryParseToXml
- tryParseToBinary

Updates to existing functions:
- int
- string
- json
- float
- bool
- base64
- xml (C# only)
- binary

**Comment by JonathanFingold** [comment]
Closing due to age. If this is still an issue, please re-open this request with updated details.
