### ISSUE TITLE
 handle multiple TextPrompts

### ISSUE THREAD

**Issue by GaurangNaik** [MicrosoftDocs/bot-docs#1932]
How to handle multiple TextPrompts If I have to apply different validations on each?  AddDialog(new TextPrompt(nameof(TextPrompt), Validation1));  AddDialog(new TextPrompt(nameof(TextPrompt),Validation2));
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9577ff-cf56-e5de-84c3-bfe10aab5368
* Version Independent ID: b5d62753-f87b-4673-b09b-a5a3fd9360e8
* Content: [Manage dialog complexity - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-compositcontrol.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-compositcontrol.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Yes, you need a separate text prompt for each one that uses different validation.

**Comment by JonathanFingold** [comment]
The short answer is that validation is associated with a prompt in its constructor, and so you need a different instance for each unique type of validation.

You can achieve a certain amount of flexibility by saving and retrieving information in the dialog context, but this requires a fairly deep understanding of state management and the dialogs library.

**Comment by GaurangNaik** [comment]
> Yes, you need a separate text prompt for each one that uses different validation.

Thank you Jonathan.
