### ISSUE TITLE
No steps for CI/CD for bot deployment using Azure Devops? 

### ISSUE THREAD

**Issue by frackham** [MicrosoftDocs/bot-docs#1935]
[Enter feedback here]
I get you're going all in on GitHub, (which is great!) but would be helpful to either have some AzDo pipeline/release notes here (ideally an example) or a link to a relevant area if it exists (and not just the pipeline/release docs).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e9b10d5-ca65-d08c-2f11-ba62d66b8f80
* Version Independent ID: 396d52c0-d864-afac-4d1c-fd6880a973a9
* Content: [Configure continuous deployment for Bot Service - Bot Service](https://docs.microsoft.com/en-gb/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-build-continuous-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-build-continuous-deployment.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Unfortunately, we don't have a good way to provided examples for more than one or two scenarios. In the **Additional resources** section, there's a link to [continuous deployment to Azure App Service](https://docs.microsoft.com/azure/app-service/deploy-continuous-deployment). Is that the sort of information you are looking for?
