### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by troykirin** [MicrosoftDocs/bot-docs#1937]
There's a spelling error, for the word "botbuilder"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef4ea5a-1364-5432-dcbb-b39b7145028a
* Version Independent ID: f4b4a848-3ce4-7978-a72d-2c3952a3ab1b
* Content: [Handle user interruptions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-handle-user-interrupt?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-handle-user-interrupt.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-handle-user-interrupt.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
@troykirin Thanks for pointing out the typo. A fix should go live soon.

**Comment by emgrol** [comment]
Closing now that the fix has been merged.
