### ISSUE TITLE
Instructions appear incomplete

### ISSUE THREAD

**Issue by v-dathur** [MicrosoftDocs/bot-docs#1938]
I have followed the instructions as given, but my bot does not respond to messages.

I have created the Application and copied the credentials back to my bots Groupme channel configuration.

Do I need to also add Bot entries in the Groupme Developer dashboard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11eef4b-87da-48ad-71d3-558b1270f401
* Version Independent ID: 0f595090-fdee-a218-fa86-13c668d222af
* Content: [Connect a bot to GroupMe - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-groupme?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-groupme.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-groupme.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by anusharavindrar** [comment]
@v-dathur, I just followed the instructions in the attached documentation and configured the GroupMe channel for my bot. The bot is responding to the messages as expected. Can you elaborate more on what error you are getting in the channels Health tab or in the Dev Console for the GroupMe chat window?

**Comment by anusharavindrar** [comment]
@v-dathur, are you still having issues with configuring the GroupMe channel?
