### ISSUE TITLE
CosmosDB Container ID for Bot storage

### ISSUE THREAD

**Issue by hctrr** [MicrosoftDocs/bot-docs#1939]
Under the section [Add Cosmos DB configuration information ](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp#add-cosmos-db-configuration-information)

there's a note stating "you should not create the container yourself"

However the very next section requires that i add the container-id within the appsettings.json and then once again within the startup.cs

Upon following these steps - the bot does not auto create the container within CosmosDB (at least not by following the steps listed).

Is there a missing step?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by GiftA-MSFT** [comment]
@JonathanFingold and @emgrol can you please assist with the above inquiry? Same question was asked [here](https://docs.microsoft.com/en-us/answers/questions/133052/index.html). Thanks!

**Comment by JonathanFingold** [comment]
@mmiele, see sample 45; possibly, follow up with @EricDahlvang .

**Comment by emgrol** [comment]
Closed now that changes have been merged.
