### ISSUE TITLE
Starting a scenario automatically when user sent reply to Bot using Twilio integration

### ISSUE THREAD

**Issue by gopikrishnas** [MicrosoftDocs/bot-docs#1941]
I configured my Twilio number using the steps mentioned in this document. But when I send a message to the Twilio number e.g "_**Hi**_", it is replying as "**_Hi! How can I help!?_**". It is not starting a scenario until I am sending a message like "Begin &lt;ScenarioId&gt;".

But my expectation with the Twilio integration is it should start a particular scenario when a user replied to the Twilio number what I configured irrespective of the reply message the user sent. Is this possible with this Twilio integration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b76e08-962a-2a8e-2453-87fb917d68ec
* Version Independent ID: 937798fb-8f76-683c-e146-55dcd79622e1
* Content: [Connect a bot to Twilio - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-twilio?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-twilio.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-twilio.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by stevkan** [comment]
Hi @gopikrishnas,

- The _"Hi! How can I help!?"_ statement, is that generated as code from your bot or is that coming from Twilio as a feature?
- Which SDK are you using (C#, JS, Python) for your bot?
- If the statement is coming from your bot, are you able to post any of the relevant code, point me to a stored copy, or email it to me? In this way, I can better diagnose and attempt a repro of your issue.

**Comment by stevkan** [comment]
Closing due to a lack of activity.
