### ISSUE TITLE
Config Import Error

### ISSUE THREAD

**Issue by mmarzillo** [MicrosoftDocs/bot-docs#1943]
Complete novice here. I'm at the "Test your bot" section and when I try to start the dispatch_bot.py code I'm getting an Import error on the config file. I have a hunch this is something simple, but I tried adding a new environment variable to where that config.py file lives and that didn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=python)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **kamrani**

**Comment by jwiley84** [comment]
Can you post the full error and any changes you might have made to the bot?

**Comment by mmarzillo** [comment]
When I step through the code it I get the below error when I try to import DefaultConfig. Again I may be making a really easy mistake. No other changes have been made to the bot.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'DefaultConfig' from 'config' (C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\config\__init__.py)
>>> `

**Comment by jwiley84** [comment]
Where are you importing DefaultConfig? The example used in the doc doesn't show it, but in your import statements in your dispatch_bot.py (this step: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=python), you should have the following import statement: 

> from config import DefaultConfig 

if that line is not there, please put it in  and rerun the  bot.

**Comment by jwiley84** [comment]
Additionally, there is this sample here: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/14.nlp-with-dispatch

This is a full example of the bot in the doc. You can compare the code in it to your code, to see if you're missing any lines.

**Comment by jwiley84** [comment]
(sorry, had mouse issues)

**Comment by mmarzillo** [comment]
When I execute the app.py script from the command line the bot works fine. My error was happening when I was stepping through the code (because I was trying to understand it) but I suppose because the app.py runs just fine then we're all good?

**Comment by jwiley84** [comment]
It sounds like it's timing out because of the step debugging. I've never heard it giving an import error when timing out, but given your description of the issue, it seems like it's trying to initialize the project when you start it, but the step debugger is blocking a constructor somewhere from firing. I'm glad to hear that the bot works as expected when run without debugging. I'm going to close this issue here, as it isn't a bot-docs issue. Thank you for bringing it to our attention. I'll  run this problem past the python team, check if it's normal behavior. If it is not, I'll reopen this issue in the python repo.
