### ISSUE TITLE
Update Bot channels registration instructions to match current Azure UI

### ISSUE THREAD

**Issue by brianwhited** [MicrosoftDocs/bot-docs#1944]
1. Step 3 of Create a registration application reads "In the right panel selection box enter bot. From the drop-down list select Bot Channels Registration." It should read "In the top center search bar, enter `bot`. From the drop-down list select Bot Channels Registration which is located under the Marketplace title. " 

2. Step 5 has a table of fields and their descriptions. The first row is incorrect.
![BotRegistrationScreen](https://user-images.githubusercontent.com/3679573/97374683-40b62180-188f-11eb-92bd-cf32bf7661d0.png)

**Existing Row:**

Bot name | <Your bot display name> | Assign the display name for the bot that appears in channels and directories. You can change this name at anytime.

**New Row:**

Bot handle | <Your bot's unique identifier> | The Bot Handle is a unique identifier for your bot. You can choose a different Display Name for your bot in the Settings blade after bot creation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c93f5e57-c662-644a-776d-b1dd112a3832
* Version Independent ID: f7bfec78-1f6b-fcb5-09da-138e27dcad58
* Content: [Create a Bot Channels Registration with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-quickstart-registration.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart-registration.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
The fix will be in the upcoming documentation update.
