### ISSUE TITLE
How to automatically update .dispatch

### ISSUE THREAD

**Issue by UncountedBrute2** [MicrosoftDocs/bot-docs#1946]
This is a very good document for the bot framework, however, we have a front end that allows users to update the bot training at runtime. According to this doc, it looks like we would need to manually redeploy the .dispatch file every time a user updates the model.

Is there a way of automatically updating this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @diberry
* Microsoft Alias: **kamrani**

**Comment by diberry** [comment]
@cahann @tsuwandy

**Comment by tsuwandy** [comment]
@UncountedBrute2 , dispatch CLI has a *refresh* command ("dispatch refresh"), which could be scheduled (scheduled task or part of regularly scheduled CI/CD pipeline/release).  This command will pick up the changes in the sub LUIS apps/QnA Maker kbs participating in the dispatch and update the LUIS dispatch app.

**Comment by dmvtech** [comment]
Closing as answered.
