### ISSUE TITLE
Cannot 'Create a Slack Bot User'

### ISSUE THREAD

**Issue by Andrew47** [MicrosoftDocs/bot-docs#1947]
Following the documentation, I have deployed my chatbot on Azure and am trying to connect this chatbot with Slack using the Azure Bot Service Portal. There is a mismatch between what I can do when creating a Slack app and the steps specified by the documentation. The relevant part of the documentation is at: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs. 

## Details

* The documentation has a step 'Create a Slack Bot User'. Slack refers to the bot user feature being in a new place - App Home:

![WhereBotUser](https://user-images.githubusercontent.com/11377188/97432601-21ada300-1914-11eb-8bb2-180bbde8d55f.JPG)

* Upon clicking on the App Home tab, there is no bot user feature section. Instead, 
Slack states that I first need to assign a scope to my bot token:

![BotScopes](https://user-images.githubusercontent.com/11377188/97433026-c29c5e00-1914-11eb-842e-0f7526378058.JPG)

The current Microsoft documentation does not specify what scopes are required.

Thank you in advance for your help on this issue - it is much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs#feedback)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @arturl
* Microsoft Alias: **arturl**

**Comment by mmiele** [comment]
Duplication of issue https://github.com/MicrosoftDocs/bot-docs/issues/1897. The problem has been addressed.
The fix will be available in the next updated documentation

**Comment by mmiele** [comment]
The next documentation update to be made available soon.
