### ISSUE TITLE
Bot Analytics blade missing

### ISSUE THREAD

**Issue by daymayarn** [MicrosoftDocs/bot-docs#1948]
I'm unable to view the Bot Analytics blade on my Web App bot. 
Are there any conditions need to be satisfied to see Bot Analytics blade?

Screenshot:
![image](https://user-images.githubusercontent.com/73107962/97674721-ffeb2200-1ab3-11eb-90f4-b021f978c5fa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6120c4f2-ec78-8909-5fd8-46ec6fc8f434
* Version Independent ID: c5f17144-c914-e77c-628b-7be593f0570c
* Content: [Bot analytics - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-manage-analytics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-manage-analytics.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by nabeelp** [comment]
+1 same issue for me, event though I have App Insights configured in the Settings.

**Comment by HesselWellema** [comment]
Same here. I’m glad it was not discontinued without any notice 😀

**Comment by v-kydela** [comment]
Linking: https://stackoverflow.com/questions/64699491/azure-web-app-bot-analytics-blade-gone-discontinued

> Engineering is aware and currently working on it. There should be a release next week.

In the meantime, you can still access analytics by navigating to your bot resource and replacing the blade name in the URL with "analytics":

https://portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/{sub_id}/resourceGroups/{resource_group_id}/providers/Microsoft.BotService/botServices/{bot_id}/analytics
