### ISSUE TITLE
Working sample for website to BOT (SSO)

### ISSUE THREAD

**Issue by msekkappan** [MicrosoftDocs/bot-docs#1949]
Is there working sample for website to BOT (SSO)?  If so, could you point me to it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 703a4f53-d548-76ed-8c8a-a1c8e6f17577
* Version Independent ID: 7311af4b-6943-fa86-ebb7-50f3bc9f39ba
* Content: [Single sign on - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-sso?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-sso.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-sso.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
The two mostly likely articles to help you out are:
- [Add single sign on to Web Chat](https://docs.microsoft.com/azure/bot-service/bot-builder-webchat-sso)
- [Add single sign on to a bot](https://docs.microsoft.com/azure/bot-service/bot-builder-authentication-sso)

Let me know if that does the trick for you or not.

**Comment by mmiele** [comment]
@msekkappan There is a sample listed in this article: [Add single sign on to a bot](https://docs.microsoft.com/azure/bot-service/bot-builder-authentication-sso).
