### ISSUE TITLE
Middleware instructions are not early enough

### ISSUE THREAD

**Issue by paulio** [MicrosoftDocs/bot-docs#195]
The instructions are in two main parts, however the details about changing the state provider in the middleware is only in the second part but is a requirement for the first part. It needs to be moved up the document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95db9168-d434-3461-ab0d-c623c27800a6
* Version Independent ID: f3463efe-3ba7-385a-f2b4-9398fb5028de
* Content: [Ask the user questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-waterfall?view=azure-bot-service-4.0&tabs=cstab)
* Content Source: [articles/v4sdk/bot-builder-tutorial-waterfall.md](https://github.com/Microsoft/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-waterfall.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
@paulio - existing SDK v4 content is being updated based on changes to the SDK. We should have them out in a couple of days.
