### ISSUE TITLE
Bot User for Slack App can not be added anymore

### ISSUE THREAD

**Issue by juseljuk** [MicrosoftDocs/bot-docs#1951]
Your instructions to add Bot User to Slack App are incorrect. They have had some changes in Slack that are not yet reflected by your instructions.

// Jukka

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @arturl
* Microsoft Alias: **arturl**

**Comment by mmiele** [comment]
Duplication of issue [#1897](https://github.com/MicrosoftDocs/bot-docs/issues/1897). The problem has been addressed.
The fix will be available in the next documentation update.

**Comment by mmiele** [comment]
The next documentation update will be made available soon.
