### ISSUE TITLE
Question Regarding Direct Line Sites & Limits

### ISSUE THREAD

**Issue by DrDaveH** [MicrosoftDocs/bot-docs#1956]
Is there a limit to the number of Sites you can configure against a single Direct Line connection? If so, what is the restriction?

Apologies if this is documented somewhere but I've been unable to find any answer. Any help will be much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71081bf9-a44f-7f24-040a-fcc6bc6dca02
* Version Independent ID: d5f6d9e6-9522-5915-0bbe-28b9b7f4725f
* Content: [Connect a bot to Direct Line - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directline?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-directline.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directline.md)
* Service: **bot-service**
* GitHub Login: @mmiele
* Microsoft Alias: **v-mimiel**

**Comment by mmiele** [comment]
@DrDaveH Thank you for contacting us. Let me look into it.

**Comment by craigjensen** [comment]
We don't impose any limits on the number of sites that can be created.  How many are you expecting to create?

**Comment by stevkan** [comment]
Closing, per request.

**Comment by DrDaveH** [comment]
@craigjensen Many thanks for your response. To answer your question; we're not sure, we were thinking of potentially having a site per tenant but the number of tenants would depend on how many companies would use our product. Having looked further into how we can configure & identify the sites, it suggests that perhaps this is not the best route to take. Thanks again for your help.
