### ISSUE TITLE
add guide for bot channels registration

### ISSUE THREAD

**Issue by xieofxie** [MicrosoftDocs/bot-docs#1958]
It doesn't have Configuration item.
One could use the one in App Service instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72c259-a864-9e1c-b585-562d6bca80ff
* Version Independent ID: 30a3fce8-d236-5c7b-88a0-003c971f2819
* Content: [.NET bot with direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@xieofxie I am looking into it. Thanks

**Comment by xieofxie** [comment]
Maybe we should also make it clear that these configurations are for app service not your app. So setting them in appsettings.json does not work and you can't test it locally.

**Comment by mmiele** [comment]
The fix will be in the next documentation update release.
