### ISSUE TITLE
Cortana Channel Documentation - Update for retirement

### ISSUE THREAD

**Issue by Dewain27** [MicrosoftDocs/bot-docs#1959]
We might want to think about re-writing or removing this document as Cortana has removed the Skills capability and this content might need a refresh as this is being retired.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d57239-40c4-16b9-8f33-b4ccd910158f
* Version Independent ID: 7e275b0e-8352-9beb-aa35-80177d69b7c8
* Content: [Connect a bot to Cortana - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-cortana?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-cortana.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-cortana.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@Dewain27 I'll do a little research, and hopefully update this article in Jan.

**Comment by JonathanFingold** [comment]
@Dewain27 Cortana is labeled as fully retired now.
