### ISSUE TITLE
Mikko

### ISSUE THREAD

**Issue by mikkokivirantaoy** [MicrosoftDocs/bot-docs#196]
VAT details automatically to bookkeeper

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b809442-7e1a-0186-e59b-0e4d587104ac
* Version Independent ID: 694d8c3e-37f8-100e-cffa-1634b883b3dc
* Content: [Add suggested actions to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-suggested-actions?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-send-suggested-actions.md](https://github.com/Microsoft/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-send-suggested-actions.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@mikkokivirantaoy , I don't understand what the issue here is; can you clarify?
