### ISSUE TITLE
Latest documentation pages do not contain "Download PDF" button

### ISSUE THREAD

**Issue by gbelenky** [MicrosoftDocs/bot-docs#1961]
**No "Download PDF" button in the documentation pages**

**To Reproduce**
Check [https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0&tabs=vs](url)
**Expected behavior**
A "Download PDF" button like here (left lower corner) [https://docs.microsoft.com/en-us/azure/cognitive-services/luis/what-is-luis](url)

**Comment by JonathanFingold** [comment]
@gbelenky I'll open an issue with our internal support team to try and get the PDFs building again soon.

**Comment by JonathanFingold** [comment]
@gbelenky - This has finally been fixed. Thanks for your patience.
