### ISSUE TITLE
sharing access token between main-skill bot using generic oauth

### ISSUE THREAD

**Issue by jonathanhotono** [MicrosoftDocs/bot-docs#1963]
please provide NodeJS/TypeScript sample for token exchange(SSO) between root bot and skill bot.
Also is this method supports other authentication method like Generic Oauth 2?

And if it's not possible, is it ok/good practice to create a certain REST endpoint on mainbot to request for user's specific access token between skill/main bot then we skip the oauthcard dialog?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab060f59-0fc6-d90d-6b71-a0756f1a8aa0
* Version Independent ID: f7574aeb-0002-5e07-47ed-3d135a42f4ce
* Content: [Add Single sign on to a bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml)
* Content Source: [articles/v4sdk/bot-builder-authentication-sso.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication-sso.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by swagatmishra2007** [comment]
SSO is supported only for AAD V2 and not for other providers (including generic oauth). This is because not all providers support SSO or even have a common protocol for token exchange.
Sharing the access token between skill/main bot is ok, as long as the same bot developer owns the main bot and skill (that is, they share the same trust boundary). Otherwise, it maybe be a security issue. I'll defer to @Jeffders for more on this scenario

**Comment by jonathanhotono** [comment]
@swagatmishra2007 @Jeffders thank you. I currently have a scenario where the main bot provide oauthcard to user to authenticate to ServiceNow, then there is a separate skill bot that also connects to ServiceNow, but it would not be a great experience if user had to reauthenticate again using oauthcard when they are accessing the skill bot. 

Is it possible to send through a set of auth data using `postToSkill` method provided too? If we are using REST endpoint, what would be the most secured/best way for skillbot to request on behalf of current user context (any same context shared between main/skill bot?). 

I'm using NodeJS for both main/skill bot with MS Teams and webchat as main bot channel for user to interact.

Thanks

**Comment by mmiele** [comment]
The JavaScript sample will be available in the next samples release. Let me know if we answered your questions. Thanks

**Comment by jonathanhotono** [comment]
@mmiele thanks! does this sample also includes non-AAD V2 token sharing?

**Comment by mmiele** [comment]
@jonathanhotono I do not have that information; it will depend on the team's schedule. 
Thank you for your interest and patience.
