### ISSUE TITLE
cookiecutter link to a 4.7.0 echo sample

### ISSUE THREAD

**Issue by kidd** [MicrosoftDocs/bot-docs#1964]
Following the tutorial from an absolute beginner point of view, I've tried to deploy a simple bot using a new resource group, hitting this same issue reported here:
https://stackoverflow.com/questions/63332059/deployment-template-validation-failed-the-resource-microsoft-web-serverfarms
and here:
https://docs.microsoft.com/en-us/answers/questions/108956/unable-to-deploy-bot-via-arm-template.html

I'm trying to build a python bot, and ultimately I found that I was getting 4.7.0 from the line that is advised to use to clone the template:
`cookiecutter https://github.com/microsoft/botbuilder-python/releases/download/Templates/echo.zip`. However, the link just below that line, links to a different repo (BotBuilder-Samples).

^ This link appears in https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-create-basic-bot?view=azure-bot-service-4.0&tabs=python%2Cvs, and it works locally, but I found the error when trying to deploy.

I think there's some confusion there.

Should
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53c67a1a-6151-18a9-b5a4-bc84693592bc
* Version Independent ID: 61e09eab-c8f9-097e-d0d7-b75208d457d3
* Content: [Tutorial to deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-deploy-basic-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-deploy-basic-bot.md)
* Service: **bot-service**
* GitHub Login: @mmiele
* Microsoft Alias: **v-mimiel**

**Comment by JonathanFingold** [comment]
@kidd - Emily will look into this and get back to soon.

**Comment by emgrol** [comment]
@kidd Could you try the tutorials again? I successfully followed the Python instructions in the [Tutorial: Create a basic bot](https://docs.microsoft.com/azure/bot-service/bot-builder-tutorial-create-basic-bot) and [Tutorial: Deploy a basic bot](https://docs.microsoft.com/azure/bot-service/bot-builder-tutorial-deploy-basic-bot) articles so I don't think there's an issue with the docs nor the template.

**Comment by emgrol** [comment]
Hi @kidd, thanks for pointing this out. The correct link is https://github.com/microsoft/BotBuilder-Samples/releases/download/Templates/echo.zip.

**Comment by emgrol** [comment]
Closing now that the changes have been merged.
