### ISSUE TITLE
Document the generic ActivityHandler InstallationUpdate event

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/bot-docs#1967]
This event isn't documented: https://github.com/microsoft/botbuilder-dotnet/blob/5f064d5d89e5e2f5a51777fbd249b4b35fae7898/libraries/Microsoft.Bot.Builder/ActivityHandler.cs#L560

- [x] Add note about OnInstallationUpdateActivityAsync to [Event-driven conversations using an activity handler](https://docs.microsoft.com/azure/bot-service/bot-activity-handler-concept).
- [x] Review entire article for accuracy (and for any other changes that were made to the activity handler code).

Note: the Teams version of this handler is being tracked in issue #1857 .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a774de1e-766f-9057-b3f1-a3ed71b6c765
* Version Independent ID: 1e473cc2-5eaf-13d6-f335-787532ecf5e5
* Content: [Event-driven conversations and activity handlers - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-activity-handler-concept?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-activity-handler-concept.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-activity-handler-concept.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofin**

**Comment by JonathanFingold** [comment]
Resolving via https://github.com/MicrosoftDocs/bot-docs-pr/pull/2493. Updates will go live once we do the next live sync.
