### ISSUE TITLE
Direct Line Speech is now supported in Web Chat 4.7.0, table needs to be updated

### ISSUE THREAD

**Issue by fvarga01** [MicrosoftDocs/bot-docs#1968]
According to the documentation Direct Line Speech does not “work with Web Chat”: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline?view=azure-bot-service-4.0. The table reads "Works with Webchat = No" for Direct Line Speech.

However, it seems this support has been added as of Web Chat 4.7.0:  https://github.com/microsoft/BotFramework-WebChat, see section "Direct Line Speech support in Web Chat 4.7.0"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b30881c5-a087-aa49-9dbe-3c8772de5851
* Version Independent ID: a9fab212-bcaf-6eaa-af2e-2d960ff4cf0e
* Content: [About Direct Line channel - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline.md)
* Service: **bot-service**
* GitHub Login: @mmiele
* Microsoft Alias: **v-mimiel**

**Comment by mmiele** [comment]
The fix will be available in the next documentation update. Thanks
