### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by rmhorton** [MicrosoftDocs/bot-docs#1969]
"There is an incredibly wide range [of] uses ..."
"specific use cases that it is intended [to] support."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dfa6fd8-030a-8cd8-9f5a-e54aac4b8eaf
* Version Independent ID: 6474f365-6db2-4cb1-a1e7-15d5f44f9b56
* Content: [Design the user experience - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-user-experience?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-design-user-experience.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-user-experience.md)
* Service: **bot-service**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by emgrol** [comment]
Thanks for pointing these out @rmhorton. Fixes should go live soon.

**Comment by emgrol** [comment]
Closing now that the fixes are live.
