### ISSUE TITLE
Cast error in code

### ISSUE THREAD

**Issue by paulio** [MicrosoftDocs/bot-docs#197]
The dictionary value is of type object and the code cannot cast directly to a string; reservationName = args["Text"];

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95db9168-d434-3461-ab0d-c623c27800a6
* Version Independent ID: f3463efe-3ba7-385a-f2b4-9398fb5028de
* Content: [Ask the user questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-waterfall?view=azure-bot-service-4.0&tabs=cstab)
* Content Source: [articles/v4sdk/bot-builder-tutorial-waterfall.md](https://github.com/Microsoft/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-waterfall.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
@paulio , This tutorial is also getting replaced once the dialogs implementation is complete. Each prompt returns a dictionary to the next step of the dialog. The TextPrompt returns one where ["Text"] contains the user's response to the prompt, and it will be of type string.
