### ISSUE TITLE
Document support cache scope policy in Language Generation

### ISSUE THREAD

**Issue by Danieladu** [MicrosoftDocs/bot-docs#1970]
## Related issues:
https://github.com/microsoft/botbuilder-dotnet/issues/4965

## Related PR:
https://github.com/microsoft/botbuilder-dotnet/pull/4982

## Description

Support the following options in LG file to specify the cache scope
```
> !# @cacheScope= global/local/none   // by default is local
```

###  Support setting LG  cache scope in LG file
```
> !# @cacheScope= global // global cache
> !# @cacheScope= local // local cache
> !# @cacheScope= none // none cache
> !# @cacheScope= xxx // fallback to local cache
```

### Global cache is effective in the life cycle of an evaluation
For example:
```
var templates = Templates.ParseFile("xxx.lg");
var result1 = templates.Evaluate("template", null, new EvaluationOptions { CacheScope = LGCacheScope.Global});

// The second evaluation would drop all the results cached before.
var result2 = templates.Evaluate("template", null, new EvaluationOptions { CacheScope = LGCacheScope.Global});
```

### Option name case insensitive
```
> !# @cacheScope= global // ok
> !# @CACHESCOPE= global // ok
> !# @cachescope= global // ok
...
```

### Cache scope would follow the scope of the entrance LG
For example:
a.lg:
```
> !# @cacheScope= global
 [import](b.lg)

```

b.lg
```
> !# @cacheScope= none
# template1
- ${template2()} ${template2()}

# template2
- ${rand(1, 10000000)}
```
Code:
```
var templates = Templates.ParseFile("a.lg");
var result = templates.Evaluate("template1"); // the second "template2" would use the cache of the first evaluate result
```

## What should do
Add a cache scope option section here: https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0#options

**Comment by emgrol** [comment]
Closing now that changes have been merged.
