### ISSUE TITLE
Document installation events

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/bot-docs#1971]
We should add documentation for the onInstallationXXX events

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a774de1e-766f-9057-b3f1-a3ed71b6c765
* Version Independent ID: 1e473cc2-5eaf-13d6-f335-787532ecf5e5
* Content: [Event-driven conversations and activity handlers - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-activity-handler-concept?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-activity-handler-concept.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-activity-handler-concept.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofin**

**Comment by JonathanFingold** [comment]
This was addressed in https://github.com/MicrosoftDocs/bot-docs-pr/pull/2493. We just haven't pushed it live yet.

**Comment by JonathanFingold** [comment]
We're planning to do a live sync on Wednesday.
