### ISSUE TITLE
Resource Group snippets incorrectly say that `name` sets the bot's name, not the deployment's name

### ISSUE THREAD

**Issue by stevengum** [MicrosoftDocs/bot-docs#1972]
The deployment documentation indicates that the `name` used in the `az deployment [group] sub create` command sets the bot name, but the `--name` parameter is used to set the name of the deployment.

The table was incorrectly updated in PR #1564. Specific lines:

- New Resource Group - https://github.com/MicrosoftDocs/bot-docs/pull/1564/files#diff-d9172b43db52448ab8e2cbdd4fa7cf347e42e56c5baf55c4a979fb964305d7e5R14
- Existing Resource Group - https://github.com/MicrosoftDocs/bot-docs/pull/1564/files#diff-2e9de19e871789e47d2d0ffeafe546e8c5242552bab9f95de407a48763b46832R29

https://github.com/MicrosoftDocs/bot-docs/blob/41f11974ec255a4bfc6cbf34a1c4f154bf3c9d7e/articles/includes/deploy/snippet-ARM-existing-resource-group.md#L27-L29

https://github.com/MicrosoftDocs/bot-docs/blob/41f11974ec255a4bfc6cbf34a1c4f154bf3c9d7e/articles/includes/deploy/snippet-ARM-new-resource-group.md#L12-L14

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#deploy-via-arm-template-with-new-resource-group)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Solved. The fix will be available in the next documentation update.
