### ISSUE TITLE
Normalize and update labels

### ISSUE THREAD

**Issue by emgrol** [MicrosoftDocs/bot-docs#1974]
Update the labels used in the bot-docs, bot-docs-pr, and composer-docs-pr repos.

Notes:
- Labels should be based off of [Bot Framework Labeling Guidelines](https://github.com/microsoft/botframework-sdk/blob/main/docs/BF%20Labeling%20Guide.md) and deviate where necesssary.
- Labels for issues vs. PRs

**Comment by zxyanliu** [comment]
@zxyanliu will take care of labels for composer-docs repo and composer-docs-pr repo.

**Comment by emgrol** [comment]
Closing, will track elsewhere.
