### ISSUE TITLE
Delete old Azure resources

### ISSUE THREAD

**Issue by emgrol** [MicrosoftDocs/bot-docs#1978]
Check when old resources have been deleted:
- [x] @emgrol 
- [x] @JonathanFingold 
- [x] @mmiele 
- [x] @WashingtonKayaker
- [x] @zxyanliu

**Comment by mmiele** [comment]
I think we need to delete also the related App registrations.

**Comment by zxyanliu** [comment]
I have deleted all my unused Azure resources and related App registrations. Thanks!

**Comment by emgrol** [comment]
Closing now that everyone has deleted old resources.
