### ISSUE TITLE
Nonesense state code

### ISSUE THREAD

**Issue by paulio** [MicrosoftDocs/bot-docs#198]
options.Middleware.Add(new ConversationState&lt;MyBot.convoState&gt;(storage));
options.Middleware.Add(new UserState&lt;MyBot.userState&gt;(storage));
I created two new classes deriving from dictionary&lt;string,object&gt; but the above looks very strange

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900a193e-96cd-eb18-ca94-a4062517e5e9
* Version Independent ID: c1b6cf03-c236-cfbf-aa4b-96961b816bc3
* Content: [Persist user data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-persist-user-inputs?view=azure-bot-service-4.0&tabs=cstab)
* Content Source: [articles/v4sdk/bot-builder-tutorial-persist-user-inputs.md](https://github.com/Microsoft/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-persist-user-inputs.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
@paulio , Dialogs in the SDK as implemented require a Dictionary<string, object> state object. This tutorial is being replaced by an updated tutorial, but the update date is uncertain as the dialogs implementation is still in flux for v4.
