### ISSUE TITLE
Fix inconsistent verb tense in rest-api/bot-framework-rest-connector-api-reference.md

### ISSUE THREAD

**Issue by emgrol** [MicrosoftDocs/bot-docs#1987]
| HTTP status code | Meaning |
|----|----|
| 200 | The request succeeded. |
| 201 | The request succeeded. |
| 202 | The request has been accepted for processing. |
| 204 | The request succeeded but no content was returned. |
| 400 | The request was malformed or otherwise incorrect. |
| 401 | The bot is not authorized to make the request. |
| 403 | The bot is not allowed to perform the requested operation. |
| 404 | The requested resource was not found. |
| 405 | The channel does not support the requested operation. |
| 500 | An internal server error occurred. |
| 503 | The service is unavailable. |

**Comment by JonathanFingold** [comment]
My initial rubric was flawed. This is the one I ended up with:

| Condition | Tense used |
| :-- | :-- |
| Something happened or failed to happen | simple past |
| There's a persistent issue | simple present |
| There's a transitory issue, under your control | past perfect |
| There's a transitory issue, not under your control | simple present |
