### ISSUE TITLE
Incorrect handler names in "Methods to override in a derived class" section

### ISSUE THREAD

**Issue by Rajendrasinh-ECV** [MicrosoftDocs/bot-docs#1988]
While going through the documentation for this page I found a couple of incorrect method names in the methods for the derived class section. they are as follows and as per the documentation reference, it should be as per the third column in the table below.

**Note:** It is for the javascript section.

### Methods to override in a derived class
Method       | Handler | Should be
--------------- | ------------- | ----------
channelCreated | OnTeamsChannelCreated | It is correct.
channelDeleted | OnTeamsChannelDeletedEvent | OnTeamsChannelDeleted
channelRenamed | OnTeamsChannelRenamedEvent | OnTeamsChannelRenamed
teamRenamed | OnTeamsTeamRenamedEvent | OnTeamsTeamRenamed
MembersAdded | OnTeamsMembersAddedEvent | OnTeamsMembersAdded
MembersRemoved | OnTeamsMembersRemovedEvent | OnTeamsMembersRemoved

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a7a652-1a73-79a8-515e-5d1cc1de47fb
* Version Independent ID: b1668900-477b-c2f6-9a06-33171bd911ab
* Content: [How bots for Microsoft Teams work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics-teams?view=azure-bot-service-4.0&tabs=javascript#teams-bot-logic)
* Content Source: [articles/v4sdk/bot-builder-basics-teams.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics-teams.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Thanks @Rajendrasinh-ECV 

The table is indeed in error, and it looks like the casing, as well as the full names, are off. I'll fix this soon.

**Comment by JonathanFingold** [comment]
Sorry for the delay. The article is updated now, and the changes should be live by next week.
