### ISSUE TITLE
API name should be change

### ISSUE THREAD

**Issue by rvinothrajendran** [MicrosoftDocs/bot-docs#1989]
Teams conversation update activities in python  section , better change the on_teams_team_renamed_activity api name to on_teams_team_renamed(overload) 4.11.0 version api name has been changed
ref here : https://github.com/microsoft/botbuilder-python/pull/1418 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a7a652-1a73-79a8-515e-5d1cc1de47fb
* Version Independent ID: b1668900-477b-c2f6-9a06-33171bd911ab
* Content: [How bots for Microsoft Teams work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics-teams?view=azure-bot-service-4.0&tabs=python)
* Content Source: [articles/v4sdk/bot-builder-basics-teams.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics-teams.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
The documentation has been fixed.
