### ISSUE TITLE
Expected interruptions in prompts that have no text input

### ISSUE THREAD

**Issue by PhilThome** [MicrosoftDocs/bot-docs#199]
Hi, the example given in this document seems to be a bit easy. Extending the list of choices to handle user interruptions is easy and straightforward. I faced the challenge to interrupt or exit a numbers or date prompt. The prompt itself offers no option to cancel the dialog (at least not that I know of). So in the end I implemented a global interruptions check right at the beginning of the OnTurn method.  This does not feel like the best place to put it, because each dialog might have different interrupts, and using the same LUIS model to detect interruption and proper actions leads to a degradation of the model's performance.

Could you please elaborate on the best practice on doing this?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef4ea5a-1364-5432-dcbb-b39b7145028a
* Version Independent ID: f4b4a848-3ce4-7978-a72d-2c3952a3ab1b
* Content: [Handle user interrupt - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-handle-user-interrupt?view=azure-bot-service-4.0&tabs=csharptab)
* Content Source: [articles/v4sdk/bot-builder-howto-handle-user-interrupt.md](https://github.com/Microsoft/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-handle-user-interrupt.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
@PhilThome , Handling interrupts outside of your dialog, in the bot's turn handler, is the most straightforward way to do this.

You can create a dialog context object for a dialog and check its `ActiveDialog?.Id` to establish more context. If you have multiple dialog sets, you could do a similar thing for each, or you could maintain your own context flag in conversation state.

Let me know if this helps. If so, I can update the article with an example and a more complete explanation.

**Comment by JonathanFingold** [comment]
@PhilThome , With the very recent Dialogs library refactoring, there is now a way to handle mixed input to a prompt via the prompt's validator. Handling interrupts this way will make your dialog logic more complex. We'll be including documentation for this scenario when the team pushes updated NuGet packages to NuGet.org, in about a month.
