### ISSUE TITLE
Fix 'here' links

### ISSUE THREAD

**Issue by emgrol** [MicrosoftDocs/bot-docs#1992]
Fix links that use **here** for link string. 

From the Contributor's Guide page on [Links](https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master) (Listed in the TOC as **Add links to articles**):
- Use friendly words that in link text. Use normal English words or the title of the page that you're linking to. Escape special characters like \< with a backslash.
- Don't use click here as your link text. It's bad for SEO and doesn't adequately describe the target.

List of instances:
 - [ ] bot-service-channel-connect-wechat.md:35:, please follow the instruction [Here](https://kf.qq.com/product/weixinmp.html#hid=87).
 - [ ] bot-service-channels-reference.md:261:For more information about the numbers shown in the above table, refer to channel support code listed [here](https://aka.ms/channelactions).
 - [x] bot-service-resources-faq-ecosystem.md:73:You can find more information concerning Government Services [here](https://docs.microsoft.com/azure/azure-government/documentation-government-services-aiandcognitiveservices#azure-bot-service)
 - [x] what-is-new-archive.md:239:- You can see previous announcements [here](what-is-new-archive.md).
 - [x] what-is-new.md:51:- You can see previous announcements [here](what-is-new-archive.md).
 - [x] includes\snippet-deploy-without-bot.md:116:1. Download web.config from [here](https://github.com/projectkudu/kudu/wiki/Using-a-custom-web.config-for-Node-apps) and save it into your project folder.
 - [x] includes\snippet-getstarted-test-bot.md:5:Click [here](https://emulator.botframework.com/) to download the Emulator. After the download completes, launch the executable and complete the installation process.
 - [x] v4sdk\bot-builder-adaptive-dialog-Introduction.md:55: Adaptive dialogs supports a couple of other specialized triggers to wrap common events that your bot would handle. See [here][3] to learn more about supported triggers and their usage.-->
 - [x] v4sdk\bot-builder-concept-language-generation.md:18:
 - [x] v4sdk\bot-builder-concept-language-generation.md:197:    - Language generation preview is now available for JavaScript as well. Checkout packages [here][15]. Samples are [here][26]
 - [x] v4sdk\bot-builder-concept-language-generation.md:206:    - Structured Template support in .lg file format. See [here](../language-generation/language-generation-structured-response-template.md) to learn more about Structured Template definition.
 - [x] v4sdk\bot-builder-debug-transcript.md:27:  you can read more concerning that approach [here](./bot-builder-howto-v4-storage.md#blob-transcript-storage).
 - [x] any code that can be accessed using Microsoft's Bot Framework Emulator may be used to create a transcript file.
 - [x] v4sdk\bot-builder-telemetry-qnamaker.md:128:  … Endpoint Key and HostName values [here](/azure/cognitive-services/qnamaker/how-to/key-management).
 - [x] v4sdk\bot-builder-tutorial-dispatch.md:87:The first step to setting up a QnA Maker knowledge base is to set up a QnA Maker service in Azure. To do that, follow the step-by-step instructions found
 - [x] [here](/azure/cognitive-services/qnamaker/how-to/set-up-qnamaker-service-azure).
 - [x] v4sdk\bot-builder-tutorial-dispatch.md:532:This sample is based on a preconfigured LUIS model. Additional information to help you update this model, or create a new LUIS model, can be found [here](bot-builder-virtual-assistant-template.md#updating-your-cognitive-models).
 - [x] v4sdk\bot-builder-virtual-assistant-introduction.md:107: Examples of Adaptive Cards can be found [here](https://adaptivecards.io/samples/) with information on rendering
 - [x] options in the documentation [here](https://docs.microsoft.com/adaptive-cards/rendering-cards/getting-started).
 - [x] v4sdk\migration\csharp-user-state-using.md:20:The code sample can be found [here](https://github.com/microsoft/BotBuilder-Samples/tree/master/MigrationV3V4/CSharp/V4StateBotFromV3Providers).
 - [x] v4sdk\migration\csharp-user-state-using.md:127:- Install the Bot Framework Emulator version 4.3.0 or greater from [here][6]
 - [x] v4sdk\migration\javascript-user-state-using.md:21:The code sample can be found [here](https://github.com/microsoft/BotBuilder-Samples/tree/master/MigrationV3V4/Node/V4V3-user-state-adapter-sample-bot).
 - [x] v4sdk\migration\javascript-user-state-using.md:113:- Install the Bot Framework Emulator version 4.3.0 or greater from [here][6]

**Comment by mmiele** [comment]
Solved
