### ISSUE TITLE
Web chat API reference table is missing when viewing en-us locale docs

### ISSUE THREAD

**Issue by fvarga01** [MicrosoftDocs/bot-docs#1993]
I can only see the web-chat-api-reference table in the documentation for locales other than en-us.

Below is the spanish (es-es) locale page (which correctly shows the table):
https://docs.microsoft.com/es-es/azure/bot-service/bot-builder-webchat-overview?view=azure-bot-service-4.0#web-chat-api-reference

Please include the web-chat-api-reference table in the en-us locale page as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8fcc136-2176-535a-05f4-6423bfafbd67
* Version Independent ID: e0636491-0acf-5577-0313-80d3c9006131
* Content: [Web Chat overview - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-webchat-overview?view=azure-bot-service-4.0#web-chat-api-reference)
* Content Source: [articles/v4sdk/bot-builder-webchat-overview.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-webchat-overview.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
The table was removed from this article in favor of a link to the API reference in the Web Chat repo. The page in English and Spanish now both link to the Web Chat repo, and neither include the API table.
