### ISSUE TITLE
Fix INCLUDE usage in docs

### ISSUE THREAD

**Issue by WashingtonKayaker** [MicrosoftDocs/bot-docs#1995]
We need to investigate and evaluate all uses of INCLUDES in our docs and remove those that shouldn't be includes, and potentially add those that should in includes.

## List of all includes (not including `applies-to-v4-current.md`):
**Unique files**: 40

- [ ] bot-builder-deploy-az-cli.md	25	`[!INCLUDE [deploy prerequisite](~/includes/deploy/snippet-prerequisite.md)]`
- [ ] bot-builder-deploy-az-cli.md	29	`[!INCLUDE [deploy prepare intro](~/includes/deploy/snippet-prepare-deploy-intro.md)]`
- [ ] bot-builder-deploy-az-cli.md	33	`[!INCLUDE [deploy az login](~/includes/deploy/snippet-az-login.md)]`
- [ ] bot-builder-deploy-az-cli.md	37	`[!INCLUDE [deploy az subscription](~/includes/deploy/snippet-az-set-subscription.md)]`
- [ ] bot-builder-deploy-az-cli.md	41	`[!INCLUDE [deploy create app registration](~/includes/deploy/snippet-create-app-registration.md)]`
- [ ] bot-builder-deploy-az-cli.md	56	`[!INCLUDE [ARM with new resource group](~/includes/deploy/snippet-ARM-new-resource-group.md)]`
- [ ] bot-builder-deploy-az-cli.md	61	`[!INCLUDE [ARM with existing resource group](~/includes/deploy/snippet-ARM-existing-resource-group.md)]`
- [ ] bot-builder-deploy-az-cli.md	68	`[!INCLUDE [retrieve or create IIS/Kudu files](~/includes/deploy/snippet-IIS-Kudu-files.md)]`
- [ ] bot-builder-deploy-az-cli.md	72	`[!INCLUDE [zip up code](~/includes/deploy/snippet-zip-code.md)]`
- [ ] bot-builder-deploy-az-cli.md	76	`[!INCLUDE [deploy code to Azure](~/includes/deploy/snippet-deploy-code-to-az.md)]`
- [ ] bot-builder-deploy-az-cli.md	80	`[!INCLUDE [test in web chat](~/includes/deploy/snippet-test-in-web-chat.md)]`
- [ ] bot-builder-deploy-az-cli.md	93	`[!INCLUDE [deploy csharp bot to Azure](~/includes/deploy/snippet-deploy-simple-csharp-echo-bot.md)] -->	`
- [ ] bot-service-activities-entities.md	19	`	[!include[Entity boilerplate](includes/snippet-entity-boilerplate.md)]`
- [ ] bot-service-channel-connect-email.md	44	`[!INCLUDE [email channelData json](~/includes/snippet-channelData-email.md)]`
- [ ] bot-service-channel-connect-groupme.md	19	`[!INCLUDE [Channel Inspector intro](~/includes/snippet-channel-inspector.md)]`
- [ ] bot-service-channel-connect-telegram.md	19	`[!INCLUDE [Channel Inspector intro](~/includes/snippet-channel-inspector.md)]`
- [ ] bot-service-debug-bot.md	44	`[!INCLUDE [csharp vscode](~/includes/bot-service-debug-bot/csharp-vscode.md)]`
- [ ] bot-service-debug-bot.md	46	`[!INCLUDE [csharp visual studio](~/includes/bot-service-debug-bot/csharp-vs.md)]`
- [ ] bot-service-debug-bot.md	50	`[!INCLUDE [javascript vscode](~/includes/bot-service-debug-bot/js-vscode.md)]`
- [ ] bot-service-debug-bot.md	54	`[!INCLUDE [python vscode](~/includes/bot-service-debug-bot/python-vscode.md)]`
- [ ] bot-service-design-pattern-embed-web-site.md	61	`[!INCLUDE [Introduction to backchannel mechanism](~/includes/snippet-backchannel.md)]`
- [ ] bot-service-manage-channels.md	69	`[!INCLUDE [publishing](./includes/snippet-publish-to-channel.md)]`
- [ ] dotnet\bot-builder-dotnet-sdk-quickstart.md	20	`[!INCLUDE [Azure vs local development](../includes/snippet-quickstart-paths.md)]`
- [ ] dotnet\bot-builder-dotnet-sdk-quickstart.md	22	`	<!-- Delete this include file [!INCLUDE [dotnet quickstart](../includes/quickstart-dotnet.md)] -->	`
- [ ] dotnet\bot-builder-dotnet-sdk-quickstart.md	26	`[!INCLUDE [dotnet prerequisites](../includes/quickstart/dotnet/quickstart-dotnet-prerequisites.md)]`
- [ ] dotnet\bot-builder-dotnet-sdk-quickstart.md	30	`[!INCLUDE [dotnet quickstart create bot](../includes/quickstart/dotnet/quickstart-dotnet-create-bot.md)]`
- [ ] dotnet\bot-builder-dotnet-sdk-quickstart.md	34	`[!INCLUDE [dotnet quickstart start bot](../includes/quickstart/dotnet/quickstart-dotnet-start-bot.md)]`
- [ ] dotnet\bot-builder-dotnet-sdk-quickstart.md	38	`[!INCLUDE [dotnet quickstart start Emulator](../includes/quickstart/common/quickstart-start-emulator.md)]`
- [ ] includes\deploy\snippet-prepare-deploy-intro.md	13	`[!INCLUDE [about .NET Core versions in the templates](../vsix-templates-versions.md)]`
- [ ] includes\quickstart\dotnet\quickstart-dotnet-prerequisites.md	17	`[!INCLUDE [.NET VSIX templates info](../../../includes/vsix-templates-versions.md)]`
- [ ] includes\snippet-channeldata.md	35	`[!INCLUDE [email channelData json](~/includes/snippet-channelData-email.md)]`
- [ ] includes\snippet-deploy-considerations.md	10	`[!INCLUDE [Application configuration settings](~/includes/snippet-tip-bot-config-settings.md)]`
- [ ] javascript\bot-builder-javascript-quickstart.md	20	`[!INCLUDE [Azure vs local development](../includes/snippet-quickstart-paths.md)]`
- [ ] javascript\bot-builder-javascript-quickstart.md	22	`	<!-- Delete this include file [!INCLUDE [javascript quickstart](../includes/quickstart-javascript.md)] -->	`
- [ ] javascript\bot-builder-javascript-quickstart.md	26	`[!INCLUDE [dotnet prerequisites](~/includes/quickstart/javascript/quickstart-javascript-prerequisites.md)]`
- [ ] javascript\bot-builder-javascript-quickstart.md	30	`[!INCLUDE [dotnet quickstart create bot](~/includes/quickstart/javascript/quickstart-javascript-create-bot.md)]`
- [ ] javascript\bot-builder-javascript-quickstart.md	34	`[!INCLUDE [dotnet quickstart start bot](~/includes/quickstart/javascript/quickstart-javascript-start-bot.md)]`
- [ ] javascript\bot-builder-javascript-quickstart.md	38	`[!INCLUDE [dotnet quickstart start Emulator](~/includes/quickstart/common/quickstart-start-emulator.md)]`
- [ ] python\bot-builder-python-quickstart.md	21	`	<!-- Delete this include file [!INCLUDE [python quickstart](../includes/quickstart-python.md)] -->	`
- [ ] python\bot-builder-python-quickstart.md	25	`[!INCLUDE [dotnet prerequisites](~/includes/quickstart/python/quickstart-python-prerequisites.md)]`
- [ ] python\bot-builder-python-quickstart.md	29	`[!INCLUDE [dotnet quickstart create bot](~/includes/quickstart/python/quickstart-python-create-bot.md)]`
- [ ] python\bot-builder-python-quickstart.md	33	`[!INCLUDE [dotnet quickstart start bot](~/includes/quickstart/python/quickstart-python-start-bot.md)]`
- [ ] python\bot-builder-python-quickstart.md	37	`[!INCLUDE [dotnet quickstart start Emulator](~/includes/quickstart/common/quickstart-start-emulator.md)]`
- [ ] rest-api\bot-framework-rest-connector-add-media-attachments.md	16	`[!INCLUDE [Channel Inspector intro](~/includes/snippet-channel-inspector.md)]`
- [ ] rest-api\bot-framework-rest-connector-add-rich-cards.md	36	`[!INCLUDE [Channel Inspector intro](~/includes/snippet-channel-inspector.md)]`
- [ ] rest-api\bot-framework-rest-connector-add-rich-cards.md	58	`[!INCLUDE [Table of card action types](../includes/snippet-card-action-types.md)]`
- [ ] rest-api\bot-framework-rest-connector-add-suggested-actions.md	14	`[!INCLUDE [Introduction to suggested actions](../includes/snippet-suggested-actions-intro.md)]`
- [ ] rest-api\bot-framework-rest-connector-channeldata.md	34	`[!INCLUDE [Email channelData table](~/includes/snippet-channelData-email.md)]`
- [ ] rest-api\bot-framework-rest-connector-create-messages.md	20	`[!INCLUDE [Channel Inspector intro](~/includes/snippet-channel-inspector.md)]`
- [ ] v4sdk\abs-quickstart.md	25	`[!INCLUDE [Azure vs local development](~/includes/snippet-quickstart-paths.md)]`
- [ ] v4sdk\abs-quickstart.md	91	`[!INCLUDE [download keys snippet](../includes/snippet-abs-key-download.md)]`
- [ ] v4sdk\bot-builder-basics.md	170	`[!INCLUDE [alert-await-send-activity](../includes/alert-await-send-activity.md)]`
- [ ] v4sdk\bot-builder-channeldata.md	18	`[!INCLUDE [Channel Data Content](../includes/snippet-channeldata.md)]`
- [ ] v4sdk\bot-builder-concept-adaptive-dialog-declarative.md	433	`[!INCLUDE [Install the Bot Framework CLI](../includes/install-bf-cli.md)]`
- [ ] v4sdk\bot-builder-concept-identity-providers.md	55	`[!INCLUDE [azure-ad-v1-settings](~/includes/authentication/auth-aad-v1-settings.md)]`
- [ ] v4sdk\bot-builder-concept-identity-providers.md	66	`[!INCLUDE [azure-ad-v2-settings](~/includes/authentication/auth-aad-v2-settings.md)]`
- [ ] v4sdk\bot-builder-concept-identity-providers.md	105	`[!INCLUDE [generic-oauth2-settings](~/includes/authentication/auth-generic-oauth2-settings.md)]`
- [ ] v4sdk\bot-builder-concept-identity-providers.md	114	`[!INCLUDE [generic-provider-oauth2-settings](~/includes/authentication/auth-generic-provider-oauth2-settings.md)]`
- [ ] v4sdk\bot-builder-create-a-bot-project.md	48	`[!INCLUDE [VSIX templates](../includes/vsix-templates-versions.md)]`
- [ ] v4sdk\bot-builder-howto-add-media-attachments.md	177	`[!INCLUDE [Table of card action types](../includes/snippet-card-action-types.md)]`
- [ ] v4sdk\bot-builder-howto-bf-cli-alterations-qna.md	43	`[!INCLUDE [applies-to-v4](../includes/install-bf-cli.md)]`
- [ ] v4sdk\bot-builder-howto-bf-cli-deploy-luis.md	81	`[!INCLUDE [applies-to-v4](../includes/install-bf-cli.md)]`
- [ ] v4sdk\bot-builder-howto-bf-cli-deploy-luis.md	164	`[!INCLUDE [applies-to-v4](../includes/generate-source-code-luis-cli.md)]`
- [ ] v4sdk\bot-builder-howto-bf-cli-deploy-qna.md	75	`[!INCLUDE [applies-to-v4](../includes/install-bf-cli.md)]`
- [ ] v4sdk\bot-builder-howto-bf-cli-update-luis.md	47	`[!INCLUDE [applies-to-v4](../includes/install-bf-cli.md)]`
- [ ] v4sdk\bot-builder-howto-bf-cli-update-luis.md	163	`[!INCLUDE [applies-to-v4](../includes/generate-source-code-luis-cli.md)]`
- [ ] v4sdk\bot-builder-howto-cross-train.md	100	`[!INCLUDE [applies-to-v4](../includes/install-bf-cli.md)]`
- [ ] v4sdk\bot-builder-howto-v4-storage.md	26	`[!INCLUDE [VSIX templates](~/includes/vsix-templates-versions.md)]`
- [ ] v4sdk\bot-builder-telemetry.md	82	`[!INCLUDE [dotnet telemetry section](../includes/telemetry-dotnet-main.md)]`
- [ ] v4sdk\bot-builder-telemetry.md	86	`[!INCLUDE [javascript telemetry section](../includes/telemetry-javascript-main.md)]`
- [ ] v4sdk\bot-builder-telemetry.md	90	`[!INCLUDE [python telemetry section](../includes/telemetry-python.md)]`
- [ ] v4sdk\bot-builder-telemetry.md	99	`[!INCLUDE [dotnet telemetry-Enabling disabling activity section](../includes/telemetry-dotnet-enabling-disabling-activity-event-personal-information-logging.md)]`
- [ ] v4sdk\bot-builder-telemetry.md	103	`[!INCLUDE [javascript telemetry section](../includes/telemetry-javascript-enabling-disabling-activity-event-personal-information-logging.md)]`
- [ ] v4sdk\bot-builder-telemetry.md	108	`[!INCLUDE [python telemetry section](../includes/telemetry-python-enabling-disabling-activity-event-personal-information-logging.md)]`
- [ ] v4sdk\bot-builder-telemetry.md	117	`[!INCLUDE [dotnet telemetry-luis section](../includes/telemetry-dotnet-luis.md)]`
- [ ] v4sdk\bot-builder-telemetry.md	121	`[!INCLUDE [javascript telemetry-luis section](../includes/telemetry-javascript-luis.md)]`
- [ ] v4sdk\bot-builder-telemetry.md	126	`[!INCLUDE [python telemetry-luis section](../includes/telemetry-python-luis.md)]`
- [ ] v4sdk\bot-builder-tutorial-add-qna.md	391	`[!INCLUDE [zip up code](~/includes/deploy/snippet-zip-code.md)]`
- [ ] v4sdk\bot-builder-tutorial-add-qna.md	405	`[!INCLUDE [deploy code to Azure](~/includes/deploy/snippet-deploy-code-to-az.md)]`
- [ ] v4sdk\bot-builder-tutorial-add-qna.md	414	`[!INCLUDE [publish snippet](~/includes/deploy/snippet-publish-js.md)]`
- [ ] v4sdk\bot-builder-tutorial-create-basic-bot.md	29	`[!INCLUDE [dotnet prerequisites](~/includes/quickstart/dotnet/quickstart-dotnet-prerequisites.md)]`
- [ ] v4sdk\bot-builder-tutorial-create-basic-bot.md	33	`[!INCLUDE [javascript prerequisites](~/includes/quickstart/javascript/quickstart-javascript-prerequisites.md)]`
- [ ] v4sdk\bot-builder-tutorial-create-basic-bot.md	37	`[!INCLUDE [python prerequisites](~/includes/quickstart/python/quickstart-python-prerequisites.md)]`
- [ ] v4sdk\bot-builder-tutorial-create-basic-bot.md	45	`[!INCLUDE [dotnet quickstart create bot](~/includes/quickstart/dotnet/quickstart-dotnet-create-bot.md)]`
- [ ] v4sdk\bot-builder-tutorial-create-basic-bot.md	49	`[!INCLUDE [javascript quickstart create bot](~/includes/quickstart/javascript/quickstart-javascript-create-bot.md)]`
- [ ] v4sdk\bot-builder-tutorial-create-basic-bot.md	53	`[!INCLUDE [python quickstart create bot](~/includes/quickstart/python/quickstart-python-create-bot.md)]`
- [ ] v4sdk\bot-builder-tutorial-create-basic-bot.md	61	`[!INCLUDE [dotnet quickstart start bot](~/includes/quickstart/dotnet/quickstart-dotnet-start-bot.md)]`
- [ ] v4sdk\bot-builder-tutorial-create-basic-bot.md	65	`[!INCLUDE [javascript quickstart start bot](~/includes/quickstart/javascript/quickstart-javascript-start-bot.md)]`
- [ ] v4sdk\bot-builder-tutorial-create-basic-bot.md	69	`[!INCLUDE [python quickstart start bot](~/includes/quickstart/python/quickstart-python-start-bot.md)]`
- [ ] v4sdk\bot-builder-tutorial-create-basic-bot.md	75	`[!INCLUDE [dotnet quickstart start Emulator](~/includes/quickstart/common/quickstart-start-emulator.md)]`
- [ ] v4sdk\bot-builder-tutorial-deploy-basic-bot.md	34	`[!INCLUDE [deploy prerequisites](../includes/deploy/snippet-prerequisite.md)]`
- [ ] v4sdk\bot-builder-tutorial-deploy-basic-bot.md	40	`[!INCLUDE [deploy prepare intro](../includes/deploy/snippet-prepare-deploy-intro.md)]`
- [ ] v4sdk\bot-builder-tutorial-deploy-basic-bot.md	44	`[!INCLUDE [deploy az login](../includes/deploy/snippet-az-login.md)]`
- [ ] v4sdk\bot-builder-tutorial-deploy-basic-bot.md	48	`[!INCLUDE [deploy az subscription](../includes/deploy/snippet-az-set-subscription.md)]`
- [ ] v4sdk\bot-builder-tutorial-deploy-basic-bot.md	52	`[!INCLUDE [deploy create app registration](../includes/deploy/snippet-create-app-registration.md)]`
- [ ] v4sdk\bot-builder-tutorial-deploy-basic-bot.md	66	`[!INCLUDE [ARM with new resource group](../includes/deploy/snippet-ARM-new-resource-group.md)]`
- [ ] v4sdk\bot-builder-tutorial-deploy-basic-bot.md	70	`[!INCLUDE [ARM with existing resource group](../includes/deploy/snippet-ARM-existing-resource-group.md)]`
- [ ] v4sdk\bot-builder-tutorial-deploy-basic-bot.md	76	`[!INCLUDE [retrieve or create IIS/Kudu files](../includes/deploy/snippet-IIS-Kudu-files.md)]`
- [ ] v4sdk\bot-builder-tutorial-deploy-basic-bot.md	80	`[!INCLUDE [zip up code](../includes/deploy/snippet-zip-code.md)]`
- [ ] v4sdk\bot-builder-tutorial-deploy-basic-bot.md	84	`[!INCLUDE [deploy code to Azure](../includes/deploy/snippet-deploy-code-to-az.md)]`
- [ ] v4sdk\bot-builder-tutorial-deploy-basic-bot.md	88	`[!INCLUDE [test in web chat](../includes/deploy/snippet-test-in-web-chat.md)]`
- [ ] v4sdk\bot-builder-tutorial-deploy-basic-bot.md	92	`[!INCLUDE [additional resources snippet](../includes/deploy/snippet-additional-resources.md)]`
- [ ] v4sdk\migration\conversion-core.md	42	`[!INCLUDE [VSIX templates](~/includes/vsix-templates-versions.md)]`
- [ ] v4sdk\migration\migration-overview.md	155	`[!INCLUDE [VSIX templates](~/includes/vsix-templates-versions.md)]`

### Included Markdown files

Where markdown files need to be repeated in multiple articles, you can use an include file. The includes feature instructs Docs to replace the reference with the contents of the include file at build time. You can use includes in the following ways:

- Inline: Reuse a common text snippet inline with within a sentence.
- Block: Reuse an entire Markdown file as a block, nested within a section of an article.

An inline or block include file is a Markdown (.md) file. It can contain any valid Markdown. Include files are typically located in a common includes subdirectory, in the root of the repository. When the article is published, the included file is seamlessly integrated into it.

#### Includes syntax

Block include is on its own line:

> [!INCLUDE [<title>](<filepath>)]

Inline include is within a line:

> Text before [!INCLUDE [<title>](<filepath>)] and after.

Where `<title>` is the name of the file and `<filepath>` is the relative path to the file. `INCLUDE` must be capitalized and there must be a space before the `<title>` .

Here are requirements and considerations for include files:

- Use block includes for significant amounts of content--a paragraph or two, a shared procedure, or a shared section. Do not use them for anything smaller than a sentence.
- Includes won't be rendered in the GitHub rendered view of your article, because they rely on Docs extensions. They'll be rendered only after publication.
- Ensure that all the text in an include file is written in complete sentences or phrases that do not depend on preceding text or following text in the article that references the include. Ignoring this guidance creates an untranslatable string in the article.
- Don't embed include files within other include files.
- Place media files in a media folder that's specific to the include subdirectory--for instance, the <repo> /includes/media folder. The media directory should not contain any images in its root. If the include does not have images, a corresponding media directory is not required.
- As with regular articles, don't share media between include files. Use a separate file with a unique name for each include and article. Store the media file in the media folder that's associated with the include.
- Don't use an include as the only content of an article. Includes are meant to be supplemental to the content in the rest of the article.

Also see the section **Include reusable content in articles** in the contributor guide.

**Comment by emgrol** [comment]
When working on this issue, check off the files you've edited.

**Comment by JonathanFingold** [comment]
Move this to DevOps, then close.
