### ISSUE TITLE
Is the WeChat Channel still valid?

### ISSUE THREAD

**Issue by dawwa** [MicrosoftDocs/bot-docs#1996]
I could not find the WeChat channel in Azure Portal anymore, is it deprecated which makes this doc a legacy page now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a26d6f7-2453-f514-a812-f87916b6c724
* Version Independent ID: 806e3815-cee0-cfc7-9af5-e3a23270644c
* Content: [Connect a bot to WeChat - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-wechat?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-wechat.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-wechat.md)
* Service: **bot-service**
* GitHub Login: @seaen
* Microsoft Alias: **egorn**

**Comment by mmiele** [comment]
@dawwa WeChat is still supported. You need to use the adapter as explained in the documentation: 

WeChat adapter for Microsoft Bot Framework is an open source adapter on GitHub. [Download WeChat Adapter for Bot Framework](https://github.com/microsoft/BotFramework-WeChat/). 

Let us know if this helps.
