### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by dhananshan** [MicrosoftDocs/bot-docs#200]
Microsoft.Bot.Samples.Dialog.Prompts &lt;https://github.com/Microsoft/botbuilder-dotnet/tree/master/samples/MIcrosoft.Bot.Samples.Dialog.Prompts&gt; doesn't exists anymore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c5adf9-272a-e0f1-10f1-c8365e76035b
* Version Independent ID: 1982af41-5a06-4398-0e95-abcc50864e0d
* Content: [Manage a conversation flow with dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md](https://github.com/Microsoft/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
@dhananshan , Samples have been renamed and moved to the [samples-final](https://github.com/Microsoft/botbuilder-dotnet/tree/master/samples-final) directory.

**Comment by JonathanFingold** [comment]
@janstrijk I'm not able to repro. Have you tried refreshing the page in your browser? The updated text in the article should look like this:

In this article, we use _dialog sets_ to create a conversation flow that contains both prompts and waterfalls. We will draw on code from the **multi-turn prompt** [[C#](https://aka.ms/cs-multi-prompts-sample)|[JS](https://aka.ms/js-multi-prompts-sample)] sample.
