### ISSUE TITLE
@zxyanliu doc clean up

### ISSUE THREAD

**Issue by emgrol** [MicrosoftDocs/bot-docs#2000]
Guidance: https://github.com/MicrosoftDocs/bot-docs-pr/blob/jf/contrib-0104/contributor-guide/formatting-text.md

ToDo:

- [ ] [Grammar and spelling check](https://github.com/MicrosoftDocs/bot-docs/issues/2006)

Docs:
- [ ] rest-api/bot-framework-rest-connector-channeldata.md [grammar, spelling, table formatting]
  - [ ] links to double check: 
      - https://api.slack.com/docs/messages
      - https://api.slack.com/docs/message-attachments
      - https://api.slack.com/docs/message-buttons
      - https://developers.facebook.com/docs/messenger-platform/send-api-reference#guidelines
      - https://core.telegram.org/bots/api#available-methods
      - https://dev.kik.com/#/docs/messaging#message-formats      
- [ ] bot-service-debug-inspection-middleware.md
- [ ] security-baseline.md
     - Important: This content is machine generated; do not modify this topic directly. Contact mbaldwin for more information.
- [ ] language-generation/functions-injected-from-language-generation.md
- [ ] adaptive-expressions/adaptive-expressions-API-reference.md
- [ ] v4sdk/bf-cli-overview.md
- [ ] v4sdk/bot-builder-concept-adaptive-dialog-Triggers.md
- [ ] v4sdk/migration/conversion-javascript.md
- [ ] bot-service-channel-connect-facebook.md
- [ ] v4sdk/skills-write-manifest-2-1.md
- [ ] bot-service-channel-directline.md
- [ ] bot-service-channel-connect-directline.md
- [ ] bot-service-manage-analytics.md
- [ ] v4sdk/bot-builder-howto-v4-state.md
- [ ] v4sdk/skill-actions-in-dialogs.md
- [ ] v4sdk/bot-builder-howto-bf-cli-deploy-qna.md
- [ ] v4sdk/bot-builder-concept-authentication-types.md
- [ ] bot-service-channel-connect-slack.md
- [ ] bot-service-channel-connect-line.md
- [ ] bot-service-resources-user-agent.md
- [ ] v4sdk/bot-builder-concept-adaptive-dialog-interruptions.md
- [ ] bot-service-channel-additional-channels.md
- [ ] v4sdk/bot-builder-concept-adaptive-dialog-Actions.md
- [ ] bot-service-resources-faq-ecosystem.md
- [ ] bot-service-channel-connect-directlinespeech.md
- [ ] bot-service-channel-connect-kik.md
- [ ] v4sdk/bot-builder-howto-bf-cli-deploy-luis.md
- [ ] v4sdk/bot-builder-skills-overview.md
- [ ] bot-service-overview-introduction.md
- [ ] v4sdk/bot-builder-compositcontrol.md
- [ ] v4sdk/bot-builder-custom-storage.md
- [ ] v4sdk/bot-builder-authentication-basics.md
- [ ] bot-service-design-pattern-knowledge-base.md
- [ ] rest-api/bot-framework-rest-direct-line-1-1-start-conversation.md
- [ ] v4sdk/bot-builder-tutorial-dispatch.md
- [ ] bot-service-channel-connect-cortana.md
- [ ] v4sdk/bot-activity-handler-concept.md
- [ ] v4sdk/bot-builder-debug-transcript.md
- [ ] v4sdk/bot-builder-primitive-prompts.md
- [ ] bot-service-troubleshoot-general-problems.md
- [ ] bot-service-debug-emulator.md
- [ ] bot-service-channel-connect-alexa.md
- [ ] bot-service-troubleshoot-authentication-problems.md

**Comment by zxyanliu** [comment]
Suggested way to proceed on this:

* Chunk the work into PRs such that you can wrap up a PR in 3-4 days (making review less difficult)
* Limit the number of articles in the PR or limit the scope of the changes you're making o each article
* Link back to the associated issue
* Include a description

**Comment by emgrol** [comment]
Closing, will track doc clean up elsewhere.
