### ISSUE TITLE
Deploy source code???

### ISSUE THREAD

**Issue by truezanuda** [MicrosoftDocs/bot-docs#2002]
As for "Zip up the code directory manually part":
I can't believe that I should zip the source files from my bot's project folder. And it is even more confusing that I should put built artifacts (bin/obj folder inside my project folder) in same zip-file!
I'm sitting in front of a monitor and I'm completelly confused... Why does documentation say that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by dmvtech** [comment]
Hi @truezanuda My _assumption_ is that this is done for simplicity sake. Rather than have a convoluted script or process to include what is needed and exclude what is not, it's easier and simpler to just zip up everything. 

@JonathanFingold Do you have any insight on this? We can discuss internally if needed.

**Comment by JonathanFingold** [comment]
For some languages, the source code is compiled on the server side as part of deployment, and for some the source code is not compiled. So, it's just easier to always compress the entire folder.

**Comment by truezanuda** [comment]
Guys, it can have a good reason but it's confusing. A documentation should help people, not confuse them :)
I just point the bad place in your docs. You can improve it or not, it's your decision. Thank you for replying me here at least :)

**Comment by JonathanFingold** [comment]
@truezanuda I'm following up with engineering for appropriate links into the Azure Web Service docs.

**Comment by JonathanFingold** [comment]
Adding a link to the Azure documentation, [Deploy a ZIP package](https://docs.microsoft.com/azure/app-service/deploy-zip#deploy-a-zip-package).
