### ISSUE TITLE
Broken link on 'Actions in Adaptive Dialogs page' 

### ISSUE THREAD

**Issue by scurvydoggo** [MicrosoftDocs/bot-docs#2003]
The markdown looks to be misformatted for this link, so appears as raw markdown: [Managing state]

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-dialog-actions?view=azure-bot-service-4.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd4b952-8725-f66b-f60f-3146c11480d5
* Version Independent ID: 4017cd75-a1ad-c33b-fcd9-d309cd5e9158
* Content: [Actions - Bot Framework SDK - adaptive dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-dialog-actions?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-adaptive-dialog-Actions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-adaptive-dialog-Actions.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
Thank you for reporting this. The link has been fixed and the update to this article will go live the next time updates are pushed to docs.microsoft.com.

**Comment by JonathanFingold** [comment]
Fix is live.
