### ISSUE TITLE
AAD Integrated Authentication For QnA Maker

### ISSUE THREAD

**Issue by RonnieQuan** [MicrosoftDocs/bot-docs#2009]
Can you please confirm if AAD integrated authentication is available for BOT to access QnA Maker knowledge base?

So far in this document or example, seems only via qna-maker-resource-key.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@RonnieQuan Can you please clarify your question. Are you asking if bot authentication via AAD allow you to access the QnA service as well? Thanks

**Comment by mmiele** [comment]
Added FAQ entry. It will be available in the next documentation update.
