### ISSUE TITLE
main.py doesnt work with the above code, throws 404 error with local host

### ISSUE THREAD

**Issue by utsavagarwal444** [MicrosoftDocs/bot-docs#201]
I used this url for main.py code https://github.com/Microsoft/botbuilder-python/blob/master/samples/Echo-Connector-Bot/main.py

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a20df2-727c-1afd-2b87-836ea1ea4f7a
* Version Independent ID: 157fc262-fb1f-f12d-0890-e90119feb444
* Content: [Create a bot using Bot Builder SDK for Python - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/python/bot-builder-python-quickstart.md](https://github.com/Microsoft/bot-docs/blob/live/articles/python/bot-builder-python-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by Kaiqb** [comment]
Added issue to the Python repo. Microsoft/botbuilder-python#104
