### ISSUE TITLE
IAM Authentication from Teams to Azure Bot Service

### ISSUE THREAD

**Issue by RonnieQuan** [MicrosoftDocs/bot-docs#2010]
Does Azure Bot Framework Service handle the authentication of the request from teams channel?
Anyone from any teams can send message to the Bot if they know the bot id/manifest?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e31fe2a-ac8e-815c-f33e-2f08fd554915
* Version Independent ID: e4b7dd0b-e9c9-00d8-41ea-f2ecbbb68752
* Content: [Connect a bot to Microsoft Teams - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0)
* Content Source: [articles/channel-connect-teams.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/channel-connect-teams.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by clearab** [comment]
The Azure Bot Service handles the service-to-service authentication - essentially validating that the request did indeed come from Teams. The bot is responsible for handling lower levels of authentication. For example, you can apply a filter so your bot only accepts requests from a particular tenant ID, or you can require your users to authenticate with some oAuth service.

**Comment by RonnieQuan** [comment]
So my bot run on tenant A, and some user logon to Teams belongs to tenant B.
It's possible to upload my bot to tenant B and user in that tenant can get authenticated to use my bot?

What about if I only want user from my own tenant to be able to use my Bot?

**Comment by mmiele** [comment]
@RonnieQuan This StackOverflow post could help in answering to your latest questions: [MS Teams app manifest file Tenant restriction](https://stackoverflow.com/questions/61382080/ms-teams-app-manifest-file-tenant-restriction/61383764#61383764)

**Comment by clearab** [comment]
Yes, you have a couple of different options for restricting incoming messages that your bot processes, with middleware being a good option for doing so.

You can add the TeamsTenantFilteringMiddleware class to your bot, and wire it up in your startup method. You can see an example of this here (the project referenced from the StackOverflow answer given above): https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Teams/Roster

It is important to note - you cannot prevent Teams from sending you messages from various tenants, nor can you prevent someone from installing your bot if they have your app manifest. All you can do is prevent your bot from processing the messages.

If you are dealing with secure data, it is definitely recommended to use oAuth to authenticate your users.

**Comment by mmiele** [comment]
Added FAQ entry. It will be available in the next documentation update.
