### ISSUE TITLE
Authenticate requests from the Bot Connector service to your bot

### ISSUE THREAD

**Issue by RonnieQuan** [MicrosoftDocs/bot-docs#2011]
How this token is created by the bot framework connector? does the token identify the bot service itself, or it's user token or identify a channel user?
e.g, I logon to my teams, then submit request to the bot via bot service connector.

Does the token presented  by Bot connector to my BOT identify the channel user and allow my BOT to authorize only user from trusted channels? e.g. only allow user from my AAD tenant to talk to my bot. 

https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0#connector-to-bot

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58bf70a-3263-93a1-5bc2-085431a7aa6b
* Version Independent ID: c5e3de2f-58ad-1c6a-e0f3-93489d013114
* Content: [Authenticate requests - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0#connector-to-bot)
* Content Source: [articles/rest-api/bot-framework-rest-connector-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-authentication.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by v-kydela** [comment]
Thank you for the question, @RonnieQuan 

The bearer token included in requests from Teams to your bot gets decoded into something like this:

```json
{
  "alg": "RS256",
  "kid": "<base64>",
  "typ": "JWT",
  "x5t": "<base64>"
}.{
  "serviceurl": "https://smba.trafficmanager.net/amer/",
  "nbf": 1600000000,
  "exp": 1600010000,
  "iss": "https://api.botframework.com",
  "aud": "<guid>"
}.[Signature]
```

The bot can use this to determine that the request came from a legitimate source (Teams), but it's not meant to identify the user, etc. The information you're looking for can be found in the body of the request, i.e. the activity. You can check the activity's `conversation` and `from` properties manually, or you can use the middleware that's already built into the SDK: https://stackoverflow.com/a/61383764/2122672

**Comment by mmiele** [comment]
Added FAQ entry. It will be available in the next documentation update.
