### ISSUE TITLE
Bug in NumberInput example

### ISSUE THREAD

**Issue by rvinothrajendran** [MicrosoftDocs/bot-docs#2015]
NumberInput example code section

1 ) Validations must accept the List **BoolExpression** () object but sample code ref the List **String()**

## Current code
Validations =  **new List String ()** {
                        "int(this.value) >= 1",
                        "int(this.value) <= 10"
                    },
## Excepted code.
Validations = **new List BoolExpression()** {
                        "int(this.value) >= 1",
                        "int(this.value) <= 10"
                    },

**2) $ is missing**
## Current code 
new SendActivity("Your favorite number is {user.favoriteNumber}")
## Excepted code.
 new SendActivity("Your favorite number is ${user.favoriteNumber}")
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2faabd1e-9990-fa4e-3b3b-f96f3e20920b
* Version Independent ID: ef07f78f-42e9-4642-e5d4-cd6c9e4b882b
* Content: [Inputs in adaptive dialogs - reference guide - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-dialog/adaptive-dialog-prebuilt-inputs?view=azure-bot-service-4.0#numberinput)
* Content Source: [articles/adaptive-dialog/adaptive-dialog-prebuilt-inputs.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/adaptive-dialog/adaptive-dialog-prebuilt-inputs.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
Thank you for pointing this out Vinoth. You are correct, and I have updated the example. This will get pushed live the next time we push the main branch to live.

**Comment by rvinothrajendran** [comment]
@WashingtonKayaker  :  just improve the code sane standard
 section : AttachmentInput example.
 If possible remove the "$userAttachmentCarImage" ,   **$** ( and SendActivity also ) in the variable

**Comment by WashingtonKayaker** [comment]
Vinoth, please create a new issue to track this and I will take a look asap. Thanks!

**Comment by rvinothrajendran** [comment]
@WashingtonKayaker its correct code only.

**Comment by JonathanFingold** [comment]
We have taken the adaptive dialog information out of the SDK docs. For more information, please check the Composer docs, such as in the [Ask for user input](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input?tabs=v2x) how to.
