### ISSUE TITLE
bot-builder-howto-add-media-attachments needs updated to reflect changes in the Using cards sample bot.

### ISSUE THREAD

**Issue by WashingtonKayaker** [MicrosoftDocs/bot-docs#2016]
See section: **Code sample for processing Adaptive Card input**

Note: There is no `ChoiceValidator` method.

**Comment by mmiele** [comment]
I checked the 

> See section: **Code sample for processing Adaptive Card input**
> 
> Note: There is no `ChoiceValidator` method.

I checked the documentation and at line 465 it reads as follows:
_This `ChoiceValidator` method is placed into the **Using cards** sample just after the closed brace public for declaration of MainDialog:_
This is followed by a C# inline sample where the `ChoiceValidator` is defined. 
So I do not understand the comment? What is the problem?

**Comment by mmiele** [comment]
Closing, obsolete.
