### ISSUE TITLE
Update Additional channels article

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#2019]
1. Better to clarify which channel adapters are found in which repositories.
2. Clean up links: we should start with [the table in the SDK README.](https://github.com/microsoft/botframework-sdk#channels-and-adapters), then include a very small number of links into to the Botkit and Community repos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dab6cb1-d601-d9c3-a7a2-7f29f0c21fe4
* Version Independent ID: c2a81b49-88e6-8718-5cd1-64c0eb8f07e6
* Content: [Additional channels - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-additional-channels?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-additional-channels.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-additional-channels.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Partially solved.
