### ISSUE TITLE
ConfigureAwait

### ISSUE THREAD

**Issue by paulio** [MicrosoftDocs/bot-docs#202]
Why is configureAwait used in this tutorial a nowhere else? Seems odd given this is asp.net core. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72538432-fde5-22ab-7997-8a34b11aa24e
* Version Independent ID: c469fa5b-2590-ee16-1491-51b90c069204
* Content: [Prompt users for input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-prompts.md](https://github.com/Microsoft/bot-docs/blob/live/articles/v4sdk/bot-builder-prompts.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
@paulio , The `ConfigureAwait` should not have been used in the sample code in this article, and it's been removed. Thanks.
