### ISSUE TITLE
Do not abbreviate customer-managed keys to CMK

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#2020]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab6b752f-84b0-9ab2-15dd-fa590c9228c3
* Version Independent ID: b35b8505-2cf5-dbc7-4a22-db4cc110f537
* Content: [Azure Bot Service encryption for data at rest - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-encryption?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-encryption.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-encryption.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jameslew**

**Comment by mmiele** [comment]
Solved
