### ISSUE TITLE
Please update docs

### ISSUE THREAD

**Issue by faceoffers28** [MicrosoftDocs/bot-docs#2023]
[Enter feedback here]

The .deployment file should look like this.

```
[config]
SCM_SCRIPT_GENERATOR_ARGS=--aspNetCore "MyBot.csproj"
```

When you run the following command, it adds unnecessary information to the file.

`az bot prepare-deploy --lang Csharp --code-dir "./Source/Repos/MyBot/MyBot" --proj-file-path "C:\Users\<username>\Source\Repos\MyBot\MyBot\MyBot.csproj"`

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#option-1-existing-app-service-plan)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
The documentation reflects what is describe in the CLI reference: 
https://docs.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest#az_bot_prepare_deploy-examples. Would you mind to clarify what is wrong, so we can address your concerns?

**Comment by faceoffers28** [comment]
Sure, if you follow the directions explicitly, that command creates an entry like this (see below). It also creates it in another folder. Furthermore, it never really explains what the command does, when it does it and how it impacts the Project. 

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#51-retrieve-or-create-necessary-files

In Section 5.1, you don't even provide an example of what the file is supposed to look like after issuing such a crucial command.

```
[config]
SCM_SCRIPT_GENERATOR_ARGS=--aspNetCore "C:\Users\<username>\Source\Repos\MyBot\MyBot\MyBot.csproj"

```
Kudu can't handle that .deployment file so, you get this error message in Deployment Center (Preview) for the App Service. You also get a Zip Deployment Failed message in the Command Prompt window.

Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "D:\local\Temp\zipdeploy\extracted" -o "D:\home\site\deployments\tools" --aspNetCore "C:\Users<username>\Source\Repos\MyBot\MyBot\MyBot.csproj"'. D:\Program Files (x86)\SiteExtensions\Kudu\91.21119.4922\bin\node_modules\kuduscript\lib\generator.js:90 throw new Error("The project file path should be a sub-directory of the repository root"); } ; ^

Error: The project file path should be a sub-directory of the repository root
