### ISSUE TITLE
Direct Line link is broken

### ISSUE THREAD

**Issue by rbnswartz** [MicrosoftDocs/bot-docs#2028]
The links point to direct line https://docs.botframework.com/restapi/directline3/#navtitle don't actually go to the intended page but instead just redirect to the main documentation page for bot framework https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0#navtitle

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8d46849-521e-3d23-ff95-f0c71966dcb4
* Version Independent ID: 35b66480-1cde-b05b-fd00-29f0e64511c9
* Content: [Embed a bot in a website - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-embed-web-site?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-design-pattern-embed-web-site.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-pattern-embed-web-site.md)
* Service: **bot-service**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by mmiele** [comment]
The fix will be in the next documentation build update.
