### ISSUE TITLE
None-Intent needs a better example

### ISSUE THREAD

**Issue by paulio** [MicrosoftDocs/bot-docs#203]
The None-Intent is very useful but not for the reason given here. If you entered, "schedule an appointment on Friday", then yes it would provide either On/Off but crucially the score would be low and the client should reject it. The real benefit of a None-Intent is to train away false positives. I.e. "Milk has gone off" might result in Lights-Off 60% confidence score. By training "Milk has gone off" to "None" you can protect the quality of the matches. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b9de9f8-0d16-eaa5-7287-0a713278fc01
* Version Independent ID: 5a19dadd-5b1c-13d1-2a3c-1e389d2b4725
* Content: [Language Understanding for bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-luis?view=azure-bot-service-4.0#best-practices-for-language-understanding)
* Content Source: [articles/v4sdk/bot-builder-concept-luis.md](https://github.com/Microsoft/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-luis.md)
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by JonathanFingold** [comment]
@paulio , I've clarified and added an example. Please reopen this if there is still an issue in the article.
