### ISSUE TITLE
Does Bot Channel Registration Have Integration With KeyVault

### ISSUE THREAD

**Issue by RonnieQuan** [MicrosoftDocs/bot-docs#2030]
When I create bot channel registration, have to input appId and secret, where Azure store these credentials?
Can Bot Channel Registration reference secret from my Keyvault instead?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c93f5e57-c662-644a-776d-b1dd112a3832
* Version Independent ID: f7bfec78-1f6b-fcb5-09da-138e27dcad58
* Content: [Create a Bot Channels Registration with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-quickstart-registration.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart-registration.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@RonnieQuan Please look at this article: [Azure Bot Service encryption for data at rest](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-encryption?view=azure-bot-service-4.0). Let me know if it answers your questions.
