### ISSUE TITLE
"Events and triggers in adaptive dialog" is missing three trigger types

### ISSUE THREAD

**Issue by mewa1024** [MicrosoftDocs/bot-docs#2031]
Three trigger types have been added to the SDK schema that are not documented here:

- OnAssignEntity
- OnChooseEntity
- OnChooseProperty

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d05995b-ebcd-898f-a3e0-ed79d90a8312
* Version Independent ID: 67b58640-980c-d0cf-72d9-aae18aac734c
* Content: [Events and triggers in adaptive dialogs - reference guide - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-dialog/adaptive-dialog-prebuilt-triggers?view=azure-bot-service-4.0#recognizer-event-triggers)
* Content Source: [articles/adaptive-dialog/adaptive-dialog-prebuilt-triggers.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/adaptive-dialog/adaptive-dialog-prebuilt-triggers.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
@mewa1024 I've been waiting for final word on the future of the where what aspects of adaptive dialog topics will be covered in the SDK Vs Composer docs moving forward. At some point the adaptive dialog topics in the SDK docs will be refactored and moved into the Composer docs, and these actions will be added to the docs then.

Is there a source of truth for the schema, one we can check periodically for both the actions and their descriptions?

**Comment by mewa1024** [comment]
@WashingtonKayaker I don't know where the source of truth for the schema is. I was just looking at the "$schema" field in the .dialog files:

`"$schema": "https://raw.githubusercontent.com/microsoft/BotFramework-Composer/stable/Composer/packages/server/schemas/sdk.schema"`

**Comment by JonathanFingold** [comment]
This is no longer being documented in the SDK doc set, just in Composer.
