### ISSUE TITLE
scope values

### ISSUE THREAD

**Issue by msekkappan** [MicrosoftDocs/bot-docs#2032]
Are we supposed to enter the scope values in the token exchange URL property?  or in the scopes?  It seems like it should be the scopes and token exchange URI with the URL.  I think there is an error in the docs.  This is about the identity for root bot, skill bot is correct I think

![image](https://user-images.githubusercontent.com/22689003/107264260-c4e07f00-6a10-11eb-986f-bf80c684ac02.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab060f59-0fc6-d90d-6b71-a0756f1a8aa0
* Version Independent ID: f7574aeb-0002-5e07-47ed-3d135a42f4ce
* Content: [Add Single sign on to a bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml)
* Content Source: [articles/v4sdk/bot-builder-authentication-sso.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication-sso.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by swagatmishra2007** [comment]
For the root bot, the scopes should be added in the scopes field and the token exchange URI should be left empty. 
What i mean by "scopes" here is the Url that the user initially signs in into the root bot.
For example, assume that the appid of the root bot is X and a skill is Y -
root bot's scope will be something like api://X/customScope , which will be used to login a user. this root bot token will be exchanged for api://Y/customscope during SSO and finally the skill may exchange it further for graph scopes or others.
Hopefully, that clarifies it?

**Comment by mmiele** [comment]
The fix will be available in the next documentation update.
