### ISSUE TITLE
Security FAQ  "Which specific URLs do I need to allow-list in my corporate firewall to access Bot Framework services"

### ISSUE THREAD

**Issue by adalfa** [MicrosoftDocs/bot-docs#2033]
In the security FAQ are showed some URL:

westus.api.cognitive.microsoft.com (for Luis.ai NLP integration)
cortanabfchanneleastus.azurewebsites.net (Cortana channel)
cortanabfchannelwestus.azurewebsites.net (Cortana Channel)

In the case of a bot located in Europe it seems ok to use westeurope.api.cognitive.microsoft.com instead of westus.api.cognitive.microsoft.com .
But for Cortana is not clear:
1) the information is still relevant
2) there are a any regional endpoints?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253d4e99-7fc5-cc8d-5b07-29bf2d78687a
* Version Independent ID: cdc0528d-cf1a-e015-1d8a-31ed062648f8
* Content: [Bot Framework Frequently Asked Questions Index - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-resources-bot-framework-faq.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-resources-bot-framework-faq.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@adalfa Grazie Amdrea per il tuo fedback. Fammi ricercare un po' e ti faro' sapere possibillmente al piu' presto.

**Comment by mmiele** [comment]
@adalfa Bot Framework does not support Cortana anymore. The correct documentation will be available in the upcoming update. Apologies for the inconvenience.
