### ISSUE TITLE
Broken link under section Show GitHub repository as an attachment on Web Chat customization page

### ISSUE THREAD

**Issue by Power-Maverick** [MicrosoftDocs/bot-docs#2036]
Under section _[Show GitHub repository as an attachment](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-webchat-customization?view=azure-bot-service-4.0&preserve-view=true#show-github-repository-as-an-attachment)_ the statement with a provided link shown below is broken.

![image](https://user-images.githubusercontent.com/36135520/107855893-30509500-6df3-11eb-9c99-1f245fe85f0a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d32e774-cb21-7ebc-f5c4-71edf8cf05e9
* Version Independent ID: 1403c378-79e7-a966-4d5b-a9f3f18e0790
* Content: [Web Chat customization - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-webchat-customization?view=azure-bot-service-4.0&preserve-view=true)
* Content Source: [articles/v4sdk/bot-builder-webchat-customization.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-webchat-customization.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
This has been fixed.
