### ISSUE TITLE
Need Web API to create Bot Channel Registration

### ISSUE THREAD

**Issue by RiadKatby** [MicrosoftDocs/bot-docs#2039]
Could you please add the api to create bot channel registrations programmatically 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c93f5e57-c662-644a-776d-b1dd112a3832
* Version Independent ID: f7bfec78-1f6b-fcb5-09da-138e27dcad58
* Content: [Create a Bot Channels Registration with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-quickstart-registration.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart-registration.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Is this the information you are looking for? [Create an App registration](https://docs.microsoft.com/azure/bot-service/bot-builder-tutorial-deploy-basic-bot#3-create-an-app-registration) If so, I can add a link to the **Bot channels registration** article.

**Comment by JonathanFingold** [comment]
The instruction will be changing in a few weeks. When we make those changes, we'll try to make the information easier to find in general.
