### ISSUE TITLE
Typo in Javascript quickstart docs

### ISSUE THREAD

**Issue by bradrlaw** [MicrosoftDocs/bot-docs#204]
In the prerequisite section it says "asynchronous programming in Java" and it should most likely say "asynchronous programming in JavaScript"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaad3f2-75c5-e958-4734-8925d03d95c6
* Version Independent ID: 8d98b390-5368-1fa4-8cce-3b0cff252eaa
* Content: [Create a bot using Bot Builder SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/Microsoft/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by JonathanFingold** [comment]
Fixed, thanks.
