### ISSUE TITLE
Cross training diagrams are unreadable with dark theme

### ISSUE THREAD

**Issue by peterbozso** [MicrosoftDocs/bot-docs#2042]
Hi!

Parts of the travel bot's diagrams [in this section](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-cross-train?view=azure-bot-service-4.0#travel-bot) are unreadable with dark theme.

![image](https://user-images.githubusercontent.com/3806723/110285547-af488000-7fe3-11eb-8899-d87b2398b675.png)

![image](https://user-images.githubusercontent.com/3806723/110285767-08181880-7fe4-11eb-9f7b-b40273bbdc4b.png)

Thanks,
Péter Bozsó

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 713dff27-c833-7ea9-8a76-7d5708464d80
* Version Independent ID: c687f79b-e199-c2fa-e659-90625343a26c
* Content: [Cross training your LUIS and QnA Maker models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-cross-train?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/bot-builder-concept-cross-train.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-cross-train.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
Thank you peterbozso, these have been updated and are awaiting review and checkin.

**Comment by JonathanFingold** [comment]
Fixes are live now.
