### ISSUE TITLE
Not supported by Alexa policy

### ISSUE THREAD

**Issue by germanviscuso** [MicrosoftDocs/bot-docs#2043]
The propose way to add Alexa as channel to a LUIS backend is not supported by Alexa policy (single intent skills that bypass the NLU to another system are not allowed). So this solution works while tested in development but will be rejected for publication as a live skill.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c24dc268-76db-f9d6-472f-4859a005792c
* Version Independent ID: 8279092d-0e86-c15b-89cb-8759eb25450d
* Content: [Connect a bot to Alexa - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-alexa?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-alexa.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-alexa.md)
* Service: **bot-service**
* GitHub Login: @NickEricson
* Microsoft Alias: **kamrani**

**Comment by NickEricson** [comment]
We have had customers get approved using this method. However, Alexa may change their policy at any time.

This sets the default slot to "phrase". Alexa performs TTS and gives the full text to the bot. The text can then be used directly by the bot or passed to LUIS for entity/intent extraction.

This Service Channel is based on the Adapter Channel here: https://www.nuget.org/packages/Bot.Builder.Community.Adapters.Alexa/

**Comment by JonathanFingold** [comment]
@germanviscuso - hopefully, @NickEricson 's feedback helped. Please reopen this with further details if you have more questions. For other forms of support, see [Bot Framework additional resources](https://docs.microsoft.com/azure/bot-service/bot-service-resources-links-help?view=azure-bot-service-4.0).
