### ISSUE TITLE
REST API links broken

### ISSUE THREAD

**Issue by jmnsf** [MicrosoftDocs/bot-docs#2044]
Previously-working links are now broken and redirect to https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0

For example:
* https://docs.botframework.com/en-us/restapi/connector/#!/Conversations/Conversations_GetActivityMembers

What's worse the new page has absolutely no pointers to the REST API, so I had to go around digging for them again. For anyone reading this with the same issue, they're here: https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-overview?view=azure-bot-service-4.0

One would expect there to be a redirect in place. Even if the anchors stop working, at least you're not stuck looking at a mostly unrelated page.

**Comment by JonathanFingold** [comment]
@jmnsf - I'll look into this. For now, use this link to the [Bot Framework Connect REST API](https://docs.microsoft.com/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference).

**Comment by JonathanFingold** [comment]
Sorry to take so long to get back to you. For issues with the Bot Framework Services portal, please log issues in the [microsoft/BotFramework-Services](https://github.com/microsoft/BotFramework-Services) repo. I'll copy this issue to their repo, then close this one.

**Comment by jmnsf** [comment]
@JonathanFingold no problem, thanks.

**Comment by Andrea-Orimoto** [comment]
@jmnsf thanks for reporting this. Could you please let us know where you found those broken links?

**Comment by jmnsf** [comment]
@Andrea-Orimoto had them mostly in internal documentation as reference. They're used in [this library](https://github.com/zabirauf/ex_microsoftbot/blob/master/lib/conversations_client.ex#L13) as well.
