### ISSUE TITLE
Microsoft Bot Framework mixing conversation and dialogs between users who send request to bot at same time

### ISSUE THREAD

**Issue by mansetaashok** [MicrosoftDocs/bot-docs#2047]
I have implemented a bot using Microsoft Bot Framework SDK 4. The Bot is working fine, however I have experienced its not working when two users sends the request to the bot at same time.

I have printed the turnContext values for the users on each turn and its printing correct user and conversation data, however when the beginDialog calls, then sometimes its encountered with Error or sometimes it's mixing dialog response to users ( Bot send response to other user).

I have implemented multiple dialogs steps using Waterfall Dialog: Find below code snippet : Where Message 'Hi there :) Welcome User : Name of the user ' is working fine with multiple users , but beginDialog is not working and mixing response to users at same time.

Bot.ts
````
adapter.onMessage = async turnContext => {
     const results = await adapter.continueDialog()
     const recognitionResult = await Luis.recognize(turnContext)
     const { topScoringIntent } = recognitionResult
     
     
     if (topScoringIntent === 'welcome') {
         await turnContext.sendActivity(`Hi there :) Welcome User ${turnContext.activity.form.name}` )
         await adapter.beginDialog(DialogsTimebot.GreetingDialog, {
                recognitionResult
          })

     }
}
````
Adapter.ts

````
async beginDialog(dialog: Dialog, options: object | undefined) {
      if (!dialogMap.has(dialog)) {
        const id = `dialog-${randomId()}`
        const dialogClass = new (class extends ComponentDialog {
          constructor() {
            super(id)
            this.addDialog(
              new WaterfallDialog(
                `waterfall-${id}`,
                dialog.steps.map(step => modStep(step, dialogMap))
              )
            )
          }
        })()
        dialogMap.set(dialog, { id, dialogClass })
        _dialogSet.add(dialogClass)
      }
      const dialogId = dialogMap.get(dialog)!.id
      await _dialogContext.beginDialog(dialogId, options)
    },

````

I have got stuck for quite long time. Kindly please suggest any work around. Thank you.

**Comment by anusharavindrar** [comment]
@mansetaashok, are you referring to any of the [botbuilder samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples) for implementing your bot? What channel are you testing your bot on?

**Comment by mansetaashok** [comment]
> @mansetaashok, are you referring to any of the [botbuilder samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples) for implementing your bot? What channel are you testing your bot on?

@anusharavindrar, I have created own bot adapter to make dynamic dialogs and waterfall dialogs. I am using Ms Teams channel. 
Now, I have tested some dialogs with botbuilder samples and it's working fine. However It is not working with the adapter I have created.

**Comment by anusharavindrar** [comment]
@mansetaashok, sincerely apologize for the delay in response. Are you still looking for assistance on this?
