### ISSUE TITLE
Disable Security in Python

### ISSUE THREAD

**Issue by AlexanderTodorovic** [MicrosoftDocs/bot-docs#2048]
The documentation describes how to [Disable Security](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0#disable-security-localhost) for .NET and Node.js.

How can the security for the Python version be disabled? Would be
```
APP_ID = None
APP_PASSWORD = None
```
in the config.py file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc8a0643-f219-a48f-666e-95bc9f0f351c
* Version Independent ID: 81578919-249c-b3e7-b367-183d70135890
* Content: [Troubleshooting Bot Framework Authentication - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-troubleshoot-authentication-problems.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-troubleshoot-authentication-problems.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
@AlexanderTodorovic You are correct, add the following to config.py: 

> APP_ID = None
> APP_PASSWORD = None

I will update the [Troubleshooting Bot Framework authentication](https://docs.microsoft.com/azure/bot-service/bot-service-troubleshoot-authentication-problems#disable-security-localhost) article.

**Comment by AlexanderTodorovic** [comment]
@WashingtonKayaker Thank you!
