### ISSUE TITLE
Standard vs Premium Channels SLA

### ISSUE THREAD

**Issue by jzarzuela** [MicrosoftDocs/bot-docs#2049]
It seems that using Teams, Skype and so, wouldn't be considered as premium. 

So, reading the SLA it is unclear whether there would be a 99.9 SLA or not for them.

Azure SLA page text: _"We guarantee that 99.9% of the time the Azure Bot Service **Premium Channels** will successfully receive and respond to REST API calls to the Premium Channels API Endpoint."_

**Comment by v-kydela** [comment]
Hello, @jzarzuela - It sounds like you'd like more information added to the docs. Is that correct? Can you please link to the Azure SLA page you're quoting?

@WashingtonKayaker - How would you like the support team to help with this?

**Comment by WashingtonKayaker** [comment]
@v-kydela - This is not something that we document in bot-docs.

**Comment by v-kydela** [comment]
@jzarzuela - Do you still need help?

**Comment by WashingtonKayaker** [comment]
@jzarzuela, this information is outside of our purview. I will close this issue since there has not been a response in over a week, if you do still need information on this, [Azure Bot Services pricing](https://azure.microsoft.com/pricing/details/bot-services) may be able to help.
