### ISSUE TITLE
Links to the different cards are broken

### ISSUE THREAD

**Issue by anamariakantar** [MicrosoftDocs/bot-docs#205]
Hi there, the urls for several types of cards don't work. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c205b864-640c-a101-8468-6227d8f2e7cb
* Version Independent ID: a8c5bdba-01f3-46ec-1c73-a8fabd4ccf0f
* Content: [Add rich card attachments to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-rich-card-attachments?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-add-rich-card-attachments.md](https://github.com/Microsoft/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-add-rich-card-attachments.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@anamariakantar - I've asked the web team to fix the issue. Thanks
