### ISSUE TITLE
Grammar error and edit this doc link is broken

### ISSUE THREAD

**Issue by haacked** [MicrosoftDocs/bot-docs#2051]
A couple things. I wanted to fix a minor grammar error ("to authenticated"):

```diff
- * The user’s identity from the identity provider that the bot uses to authenticated the user.
+ * The user’s identity from the identity provider that the bot uses to authenticate the user.
```

But when I clicked the Edit link above, it linked to https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-security-enhanced.md which gave me a 404 so I couldn't submit a PR to fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ab96859-2093-073e-6ccb-b736f00d8d0a
* Version Independent ID: 77dd3d41-c221-e831-7f66-f13f075920c9
* Content: [Bot Framework channels security - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-security-enhanced?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-security-enhanced.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-security-enhanced.md)
* Service: **bot-service**
* GitHub Login: @mmiele
* Microsoft Alias: **v-mimiel**

**Comment by JonathanFingold** [comment]
Thanks for reporting. A fix is in in pot-docs-pr [PR 2651](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2615).

**Comment by JonathanFingold** [comment]
Fix should be live now.
