### ISSUE TITLE
Conversation Reference API

### ISSUE THREAD

**Issue by jonathanhotono** [MicrosoftDocs/bot-docs#2052]
Can we **please** have an api endpoint that could grab the conversation reference/id from a particular user so the bot doesn't need to be interacted by the users beforehand and simply send a proactive message when needed. I have a scenario where a notification using teams chat needs to be sent to certain user based on certain condition/rule (e.g compliance). 

It is not ideal having user to chat the bot first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521a9f9a-025c-c55b-c939-d9d4efc5c6d0
* Version Independent ID: 3bcafb54-f7eb-54f5-1d78-5f2087e2e2dc
* Content: [Send proactive notifications to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp#send-proactive-message)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Issues in this repo are for changes to the docs. Please post this as a feature request in the [microsoft/botframework-sdk](https://github.com/microsoft/botframework-sdk/issues) repo.
