### ISSUE TITLE
Small clarification/fix on Greater than behavior

### ISSUE THREAD

**Issue by dmvtech** [MicrosoftDocs/bot-docs#2053]
This:
```
The expression (dialog.orderTotal + dialog.orderTax) > 50 adds the values of the properties dialog.orderTotal and dialog.orderTax, and evaluates to True if the sum is greater than 50 or False if the sum is less than 50.
```

Should be this:
```
The expression (dialog.orderTotal + dialog.orderTax) > 50 adds the values of the properties dialog.orderTotal and dialog.orderTax, and evaluates to True if the sum is greater than 50 or False if the sum is 50 or less.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98fbb9f4-706c-e90d-bad8-bf14a80f838c
* Version Independent ID: 06f4923f-e7aa-abf1-0b08-32b8513e69eb
* Content: [Adaptive expressions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-expressions?view=azure-bot-service-4.0&tabs=other)
* Content Source: [articles/v4sdk/bot-builder-concept-adaptive-expressions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-adaptive-expressions.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out @dmvtech, the fix should go live soon.

**Comment by JonathanFingold** [comment]
Fix should be live now.
