### ISSUE TITLE
[Bot Service Compliance] Add Chapter 508 and EN 301 549, update WCAG 2.0 to 2.1

### ISSUE THREAD

**Issue by compulim** [MicrosoftDocs/bot-docs#2055]
From time to time, customers asks if we support U.S. Chapter 508 and EN 301 549, despite we listed WCAG 2.0.

Chapter 508 and EN 301 549 are compliance for accessibility and listed in [Microsoft compliance offerings](https://docs.microsoft.com/en-us/compliance/regulatory/offering-home) page and we have conformance report in the [Microsoft Accessibility Conformance Reports](https://cloudblogs.microsoft.com/industry-blog/government/2018/09/11/accessibility-conformance-reports/) website.

Should we add them to the page too?

[Our conformance report is stored here](https://cloudblogs.microsoft.com/industry-blog/government/2018/09/11/accessibility-conformance-reports/), which listed Chapter 508, EN 301 549, and WCAG 2.1.

And [this article](https://docs.microsoft.com/en-us/compliance/regulatory/offering-Section-508-VPATS) details about Chapter 508 certification in Azure and Azure Government.

In addition, we could add links to Microsoft compliance pages to let our customers better understand the details of the compliance, for example, [the FedRAMP page](https://docs.microsoft.com/en-us/compliance/regulatory/offering-fedramp).

My proposal:

1. Update WCAG 2.0 to 2.1 (our conformance report show 2.1)
2. Add Chapter 508 to "US Government" column
3. Add EN 301 549 to "Region or country specific" column
4. Add links to compliance pages, for example,
   - [FedRAMP](https://docs.microsoft.com/en-us/compliance/regulatory/offering-fedramp)
   - [WCAG](https://cloudblogs.microsoft.com/industry-blog/government/2018/09/11/accessibility-conformance-reports/)

| Globally applicable    | US Government                                                                                    | Industry specific                                                                                                   | Region or country specific                                                                  |
| :--------------------- | :----------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------ |
| CSA STAR Certification | [Chapter 508](https://docs.microsoft.com/en-us/compliance/regulatory/offering-Section-508-VPATS) | HIPAA BAA                                                                                                           | Australia IRAP                                                                              |
| CSA STAR Attestation   | DoD SRG Level 2                                                                                  | HITRUST                                                                                                             | [EN 301 549](https://docs.microsoft.com/en-us/compliance/regulatory/offering-en-301-549-eu) |
| ISO 20000-1:2011       | FedRAMP Moderate                                                                                 | PCI DSS Level 1                                                                                                     | Germany C5                                                                                  |
| ISO 22301:2012         | GxP (FDA 21 CFR Part 11)                                                                         | [WCAG 2.1](https://cloudblogs.microsoft.com/industry-blog/government/2018/09/11/accessibility-conformance-reports/) | UK G-Cloud                                                                                  |
| ISO 27001:2013         |                                                                                                  |                                                                                                                     |                                                                                             |
| ISO 27017:2015         |                                                                                                  |                                                                                                                     |                                                                                             |
| ISO 27018:2014         |                                                                                                  |                                                                                                                     |                                                                                             |
| ISO 9001:2015          |                                                                                                  |                                                                                                                     |                                                                                             |
| SOC 1, 2, 3            |                                                                                                  |                                                                                                                     |                                                                                             |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25831c8b-9819-9488-6dc1-7d6d9e911ace
* Version Independent ID: bb8ba49b-858b-9ba7-efe3-cba569283971
* Content: [Compliance in Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-compliance?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-compliance.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-compliance.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **jameslew**

**Comment by mmiele** [comment]
Fixed as requested.
