### ISSUE TITLE
Update to use our Azure Queue library

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/bot-docs#2056]
We've added a library for working with Azure Queues, this doc and sample code should be updated to use that library.

**Comment by JonathanFingold** [comment]
@clearab - which topic are your referring to? Also, is there a sample in the Samples repo that we can pull code from?

**Comment by clearab** [comment]
Not sure, looks like the library was added a while ago (not sure who wrote it). Probably need to run through this entire article, test it, and figure out what the "current" way to do this is.

**Comment by JonathanFingold** [comment]
@clearab - Assuming the article in question is [write directly to storage](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-v4-storage), my suggestion is to retire this and replace it with are reference topic that doesn't include much in the way of code snippets, but does include useful links for each type of storage and any tips and tricks for using the storage type within the SDK.
