### ISSUE TITLE
Confusing index on file formats

### ISSUE THREAD

**Issue by Dewain27** [MicrosoftDocs/bot-docs#2057]
File formats in main index and then the LG file formats are in the LG section.  It is very confusing the navigation to this document.  Should we not have a different top level index beyond File Formats or move the LG one to that section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed604a1-7c6c-edfd-1c71-951322068283
* Version Independent ID: cbb78ea6-ad02-ba69-ede7-8eebc0ecf0a0
* Content: [.lg file format - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0)
* Content Source: [articles/file-format/bot-builder-lg-file-format.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/file-format/bot-builder-lg-file-format.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@Dewain27 - Agreed, though we may not have time to fix it till after this next release.

**Comment by emgrol** [comment]
Closing now that the change is merged.
