### ISSUE TITLE
Web Chat Customization doc links result in 404s

### ISSUE THREAD

**Issue by GraniteStateHacker** [MicrosoftDocs/bot-docs#2059]
Links to defaultStyleOptions.js file and createStyleSet.js file are 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d32e774-cb21-7ebc-f5c4-71edf8cf05e9
* Version Independent ID: 1403c378-79e7-a966-4d5b-a9f3f18e0790
* Content: [Web Chat customization - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-webchat-customization?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-webchat-customization.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-webchat-customization.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Solved
