### ISSUE TITLE
The live branch is out of sync with the docs

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#2060]
**Describe the bug**

The edit buttons on the pages at https://docs.microsoft.com/azure/bot-service link to Markdown documents in the live branch of this repo, yet the two sites do not match. https://docs.microsoft.com/azure/bot-service/what-is-new says March 2021, yet the page it links to says December 2019. This makes it difficult to make edits, since the page we'd be editing is irrelevant to the current document.

**To Reproduce**
1. Go to a page in the bot docs
2. Click on the edit button
3. Observe that the Markdown file on GitHub doesn't match the page

**Expected behavior**
The edit button should link to a document that reflects the current docs site, so that actual edits to that current document can be made

**Screenshots**
![image](https://user-images.githubusercontent.com/41968495/114072016-a05d2380-9856-11eb-9b4c-02e71ef27f26.png)

**Comment by JonathanFingold** [comment]
@v-kydela This is a known operations feature at the moment. Folks should not be making edits in the bot-docs repo, but in _bot-docs-pr_. If there is an issue on the live page, feel free to open an issue for it in bot-docs.

**Comment by v-kydela** [comment]
@JonathanFingold - Can anything be done about the edit button?

**Comment by JonathanFingold** [comment]
@v-kydela - In theory, yes. In practice, I need to research how to do so, and it probably requires some coordination with the publishing team.

**Comment by JonathanFingold** [comment]
We will look into this and related issues after build, probably in June.
