### ISSUE TITLE
Bot service authentication contains incorrect information for emulator

### ISSUE THREAD

**Issue by ItalyPaleAle** [MicrosoftDocs/bot-docs#2062]
Developing using the Bot Framework Emulator (v4.11) I noticed that the documentation for authenticating requests from the bot ([Authenticate requests from the Bot Framework Emulator to your bot](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0#emulator-to-bot))) contains at least 2 incorrect information in Step 4:

1. The `issuer` claim in the JWT is `https://login.microsoftonline.com/d6d49420-f39b-4df7-a1dc-d59a935871db/v2.0` and not one of the two shown in the page (also applies to the information in the "Security protocol changes" section)
2. There is no claim `appid` in the JWT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58bf70a-3263-93a1-5bc2-085431a7aa6b
* Version Independent ID: c5e3de2f-58ad-1c6a-e0f3-93489d013114
* Content: [Authenticate requests - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0#connector-to-bot)
* Content Source: [articles/rest-api/bot-framework-rest-connector-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-authentication.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@ItalyPaleAle, ho corretto la documentazione secondo i tuoi suggerimenti. Ti faro' sapere quando sara' pronta. Grazie

**Comment by mmiele** [comment]
The update will be available in the next upcoming documentation release.
