### ISSUE TITLE
Typo in az deployment group create example

### ISSUE THREAD

**Issue by rogfut** [MicrosoftDocs/bot-docs#2063]
[Enter feedback here]
Under the section 'Option 2: New App Service Plan' there is the following az cli command

`az deployment group create --resource-group "<name-of-resource-group>" --template-file "<path-to-template-with-preexisting-rg.json>" --parameters appId="<app-id-from-previous-step>" appSecret="<password-from-previous-step>" botId="<id or bot-app-service-name>" newWebAppName="<bot-app-service-name>" newAppServicePlanName="<name-of-app-service-plan>" newAppServicePlanLocation="<region-location-name>" --name "<bot-app-service-name>"`

However, az cli throws an error because `newAppServicePlanLocation` is not a valid parameter

`unrecognized template parameter 'newAppServicePlanLocation'. Allowed parameters: appId, appSecret, appServicePlanLocation, botId, botSku, existingAppServicePlan, newAppServicePlanName, newAppServicePlanSku, newWebAppName`

here's my az version
```
az --version
azure-cli                         2.22.0

core                              2.22.0
telemetry                          1.0.6
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
There's an error in the docs, the `newAppServicePlanLocation` parameter should instead be `appServicePlanLocation`. We'll update the docs.

**Comment by emgrol** [comment]
Closing now that the typo fix has been merged.
