### ISSUE TITLE
Unable to validate JWT tokens. OpenID provider spec is not correctly implemented.

### ISSUE THREAD

**Issue by nvioli** [MicrosoftDocs/bot-docs#2064]
According to the [OpenID provider spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig),
> OpenID Providers supporting Discovery MUST make a JSON document available at the path formed by concatenating the string /.well-known/openid-configuration to the Issuer.

and in section 4.3,

> The issuer value returned MUST be identical to the Issuer URL that was directly used to retrieve the configuration information. This MUST also be identical to the iss Claim value in ID Tokens issued from this Issuer. 

The `iss` field of the JWT token provided by the Bot Connector is `https://api.botframework.com`, but the metadata / configuration document is located at `https://login.botframework.com/v1/.well-known/openidconfiguration` (and alternatively, `https://api.botframework.com/v1/.well-known/openidconfiguration`). Note the extra `v1/` in the path.

Microsoft is not correctly implementing the OpenID provider spec, which makes JWT validation impossible using some popular services and libraries which expect strict adherence. In my case I wish to validate the JWT token with AWS API Gateway, but I am unable to do so.

Editing to add the error received to help others searching for this issue: `invalid_token: the issuer in the OIDC discovery endpoint metadata does not match the configured issuer`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58bf70a-3263-93a1-5bc2-085431a7aa6b
* Version Independent ID: c5e3de2f-58ad-1c6a-e0f3-93489d013114
* Content: [Authenticate requests - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-authentication.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@nvioli - checking in with a dev. Hoping to have an answer for you soon.

**Comment by mmiele** [comment]
Assigned to service, see https://github.com/microsoft/BotFramework-Services/issues/302.
