### ISSUE TITLE
Edit/Addendum Suggestions for 'Deploy your bot to Azure' (C#) Instructions

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/bot-docs#2066]
### While working through the instructions for [Azure deployment of a bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp), I found several missing steps.
1. [Step 3.1](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#31-create-the-azure-application-registration) of the deployment document walks users through creating a new Azure application registration for their bot.  And [Step 5](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#5-prepare-your-code-for-deployment) instructs users in how to deploy their code to Azure.  However, users will need to update relevant solution files (appsettings.json and manifest.json), with the relevant app id and app secret that was created in step 3.1, before proceeding to Step 5.  
2. Users should also be instructed to clean/re-build their solution after changes to files, before proceeding to Step 5.  
3. For users building Teams application bots, these instructions need to include [adding the MS Teams channel](https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0) in the bot channel registration.    
4. The deployment instructions [require an ARM deployment templates directory](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#4-create-the-bot-application-service).  However, most of the [dotnetcore samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore) do not contain such a directory.   Please provide guidance on how to generate an ARM template when working from the samples.  
_(I copied/pasted the `template-with-new-rg.json` file from a different sample that had it.)_
5. Please add guidance for best practices on toggling between local development and staging/production environments for Teams application bots.  To avoid the overhead of updating my appsettings.json and manifest.json files each time, I am instead updating the messaging endpoint of a single Azure bot channel registration to reflect either my local ngrok URL or the Azure web application URL.  This is not ideal for several reasons, but [testing options for Teams-specific bot functionality is limited](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/debug/locally-with-an-ide#test-your-bot-without-uploading-to-teams).   
![image](https://user-images.githubusercontent.com/38665906/115096311-5f5db280-9ed9-11eb-81f3-cde7c9d66b4b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Fixes will be available in the next documentation update.
