### ISSUE TITLE
Please document that deleting the Teams channel will invalidate all cached IDs

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/bot-docs#2067]
Deleting the Teams channel registration will cause a new pairwise key to be generated when it is re-enabled. This has the effect of invalidating all 29:xxx and a:xxx IDs that the bot may have stored for proactive messaging.

I recommend updating this page to warn developers against deleting the channel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e31fe2a-ac8e-815c-f33e-2f08fd554915
* Version Independent ID: e4b7dd0b-e9c9-00d8-41ea-f2ecbbb68752
* Content: [Connect a bot to Microsoft Teams - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0)
* Content Source: [articles/channel-connect-teams.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/channel-connect-teams.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Article updated.
