### ISSUE TITLE
CLI Docs Should indicate the "tools" CLI is legacy

### ISSUE THREAD

**Issue by cleemullins** [MicrosoftDocs/bot-docs#2069]
The page has links to both the BF CLI and the older "-tools" CLI repo. 

The "-tools" repo is legacy, and that message should be clearly communicated here. Consider even deleting the link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 342edda6-ca59-cafd-ef8f-68586acd7703
* Version Independent ID: ad1d9e0d-9252-4abd-d23c-c06d2ce6e826
* Content: [Azure Bot Framework Command-Line Interface (CLI) tool - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bf-cli-overview?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bf-cli-overview.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bf-cli-overview.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Verified with @cleemullins - need to update the link text (no longer "new", etc.). The link target is good.

**Comment by JonathanFingold** [comment]
@cleemullins - I'm finally getting around to fixing the copy in the SDK docs. Someone should update the copy in the repo's README file.
