### ISSUE TITLE
JS parity?

### ISSUE THREAD

**Issue by jwiley84** [MicrosoftDocs/bot-docs#2071]
Would it be possible to get this page in JS as well? People who are JS fluent, but not C# fluent might have issues "translating" from the sample code, which is only in C#.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fc218c5-0049-2279-c85e-8d0285b386f6
* Version Independent ID: d61e8b62-9ff0-32b2-8510-2ccf35a20d31
* Content: [Add telemetry to your QnA bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-qnamaker?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-telemetry-qnamaker.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-telemetry-qnamaker.md)
* Service: **bot-service**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@jwiley84 - I can't find a sample that has this code in it, for C# or JS. Ask the dev team for a sample (we tried), and perhaps they will provide one from which we can pull code snippets.
