### ISSUE TITLE
Clicking on the "Edit" button for the bot creation and tutorial pages lead to a 404

### ISSUE THREAD

**Issue by kimadeline** [MicrosoftDocs/bot-docs#2074]
**Describe the bug**

Hello!

Clicking on the "Edit" button in the top-right corner of these pages leads to a 404 page:
- [Tutorial: Create a basic bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-create-basic-bot?view=azure-bot-service-4.0&tabs=csharp%2Cvs) ➡️ leads to non-existent https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-create-basic-bot.md
- [Tutorial: Deploy a basic bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=csharp) ➡️ leads to non-existent https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-deploy-basic-bot.md

**To Reproduce**
1. Go to [Tutorial: Create a basic bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-create-basic-bot?view=azure-bot-service-4.0&tabs=csharp%2Cvs) or [Tutorial: Deploy a basic bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=csharp)
2. Click on the "Edit" button
4. See 404

**Expected behavior**

To be redirected to the docs page on GitHub.

**Screenshots**

Not attaching them since it's a default GitHub 404 page, let me know if I need to include them anyway.

**Additional context**

Note that the edit button for the last tutorial works correctly: [Tutorial: Use QnA Maker in your bot to answer questions](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp)
 redirects to https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md.

**Comment by JonathanFingold** [comment]
We've disabled the edit button for now, until we update the full process on our side. In the meantime, please file issues if you find problems in an article, or suggest edits in the private bot-docs-pr repo.
