### ISSUE TITLE
Cannot follow instructions to create an "Add to Slack" button: No bots listed on dev.botframework.com/bots

### ISSUE THREAD

**Issue by kimadeline** [MicrosoftDocs/bot-docs#2075]
**Describe the bug**

Hello!

Please let me know if this issue should live in another repo that would be more appropriate for it 🙂 

While following the instructions under the [Create an Add to Slack button](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs#create-an-add-to-slack-button) section of the doc for integrating with Slack, the first bullet point is:

> 1. On https://dev.botframework.com/bots, click your bot.

However when I go to this URL I see the "You don't have any bots or skills yet" message, despite having followed the tutorials for [creating](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-create-basic-bot?view=azure-bot-service-4.0&tabs=python%2Cvs) and [deploying](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=python) a basic bot, and managing to connect my bot to Slack following the rest of the Slack tutorial.

If I click on the "Create" button on that page and try to create a bot using the "Web App Bot" or "Bot Channels Registration" bot services, neither end up listed under "My Bots" either.

Are there any extra steps that need to be performed so the bot appears on this page?

**To Reproduce**

1. Create a Python echo bot following the [bot creation tutorial](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-create-basic-bot?view=azure-bot-service-4.0&tabs=python%2Cvs)
2. Deploy the bot following the [bot deployment tutorial](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=python)
2. Verify that the bot was deployed correctly and test it in Web Chat
3. Go to https://dev.botframework.com/bots and click on "My bots"
4. See that no bots are listed under "My bots", the only available option is to create one

**Expected behavior**

I expected my bot to be listed on the "My bots" page, or instructions (or a link pointing to instructions) on how to register the bot.

**Screenshots**

<img width="841" alt="image" src="https://user-images.githubusercontent.com/51720070/117511886-652c3e00-af43-11eb-91b0-0c90d9bc9d27.png">

**Additional context**

N/A

**Comment by mmiele** [comment]
@kimadeline Apologies for the delay. You are correct, there are problems with the documentation. I am fixing it and I will let you know when the corrected documentation is ready, In the meantime, use the Azure portal to obtain the URL for the button. These are the steps:

1. Go to the Azure portal.
1. Select your Azure bot resource.
1. In the left pane, select **Channels**.
1. In the right pane, right-click on the Slack channel name.
1. In the drop-down menu, select **Copy link**.  
1. Use this link in your Slack button.

**Comment by mmiele** [comment]
The fixed documentation will be available in the upcoming docs update.
