### ISSUE TITLE
GitHub resource no longer valid for: Example on how to generate token - Direct Line Token

### ISSUE THREAD

**Issue by dalesayers** [MicrosoftDocs/bot-docs#2078]
Bottom of page: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0

Link to "Direct Line Token" points to: https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/DirectLineTokenSite

DirectLineTokenSite information no longer listed in experimental section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d54408c-bfbc-9d2c-a642-ec54f375475f
* Version Independent ID: 5b06e016-1aa8-a13b-179c-ec6700b8287c
* Content: [Connect a bot to the Web Chat channel - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-webchat.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-webchat.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
The samples in the repo appear to have been reorganized. I'll fix the link. In the mean time, I think this is the correct target: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/k.direct-line-token

**Comment by JonathanFingold** [comment]
Fix should go live today or tomorrow.
