### ISSUE TITLE
Telegram not showing Welcome Scenario. MS Azure Health Bot

### ISSUE THREAD

**Issue by chaundhyan** [MicrosoftDocs/bot-docs#2079]
Hi,
I have successfully created a Telegram Bot and my bot is also working fine on Azure.
I've configured my bot to start the automatic scenario when someone opens the chat window.

But, I'm unable to achieve this in the Telegram bot, it always starts the chat with `/start`.
I want, whenever anyone first opens the chat it should get the result from my welcome scenario.

Please help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 260c283c-f5e9-e00d-19ec-ee9df18335e5
* Version Independent ID: d1525408-36d3-6575-2331-a16379744a59
* Content: [Create a bot for Telegram - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-telegram?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-telegram.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-telegram.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by v-kydela** [comment]
Thank you for the report, @chaundhyan 

When I click on a bot in Telegram, I see a start button:

![image](https://user-images.githubusercontent.com/41968495/119405051-87d58b00-bc95-11eb-85f8-afc6632efa9b.png)

After clicking the start button, Telegram automatically sends a "/start" message to the bot on my behalf.

I see a few possibilities for what you might be asking. Do you want to skip the start button entirely, or do you want to click the start button and have it not send the "/start" message, or do you want that "/start" message to automatically trigger your bot's welcome message the way a conversation update does?

**Comment by chaundhyan** [comment]
Hi @v-kydela 

Thanks for your response!

I was looking to get my welcome message displayed when the user clicks START.
The last suggestion of yours looks good to me, that if the "/start" message automatically triggers my bot's welcome message.

Thanks & Regards,
Mukul Kumar Chaundhyan

**Comment by v-kydela** [comment]
@chaundhyan - It looks like Telegram doesn't send a conversation update when the conversation starts, so you'll just have to have your bot respond to the "/start" message as a normal message. It seems like you have two options.

1. If you're okay with allowing the user to ask for the welcome message as many times as they like by sending the "/start" command, just have your bot check for that string in incoming message activities and send your welcome message in response to that.
2. If you want to have your bot only send the welcome message once and disallow the user from getting it again, you'll need to create a property in your bot state that keeps track of whether the welcome message has been sent already in each conversation.

Does this resolve your issue?

**Comment by v-kydela** [comment]
@chaundhyan - Are you still working on this?

**Comment by chaundhyan** [comment]
@v-kydela : Sorry I forgot to update, but I've mapped the /start into triggering into initiating my welcome scenario. 
That resolved the issue.
Thanks for your time and suggestions.
Though I’m seeing some UI issues in iOS. I think this is not the right place to raise such concerns?

**Comment by v-kydela** [comment]
@chaundhyan - Yes, I think you'd better talk to Telegram support about their iOS app. I'm glad we could resolve your issue.
