### ISSUE TITLE
500: Internal Server Error for echo bot quick start 

### ISSUE THREAD

**Issue by babakbiglari-py** [MicrosoftDocs/bot-docs#2081]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-create-basic-bot?view=azure-bot-service-4.0&tabs=python%2Cvs)
* Content Source: [articles/v4sdk/bot-builder-tutorial-create-basic-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-create-basic-bot.md)
* Service: **bot-service**
* GitHub Login: @mmiele
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Double check that your prerequisites match what's in the article and that you have the latest version of the listed pip packages.
- Only versions 3.6, 3.7, and 3.8 of Python are supported at this time.

**Comment by jwiley84** [comment]
Hi @babakbiglari-py 
You didn't give us a lot of go on here. Is it safe to assume you followed the doc bit for bit? Can you, ask Jonathan asked, double check your python installation?

**Comment by babakbiglari-py** [comment]
Thank you @jwiley84 and @JonathanFingold . Python Version was the problem. 
It is resolved.
