### ISSUE TITLE
Wrong link to templates

### ISSUE THREAD

**Issue by nudbeach** [MicrosoftDocs/bot-docs#2082]
[Enter feedback here]

In the 'Prepare for deployment' step, in Java tap, it's linked to JavaScript template. There must be a maven project linked to this

![image](https://user-images.githubusercontent.com/20915976/119432926-2c1c0800-bd50-11eb-90d8-c6699966caca.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=java#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@nudbeach Thank you for your feedback. The fix will be in the next doc update.
