### ISSUE TITLE
Issue while running the echo bot directly 

### ISSUE THREAD

**Issue by gkgaurav31** [MicrosoftDocs/bot-docs#2085]
I am trying to following the documentation here:  
https://docs.microsoft.com/en-us/azure/bot-service/java/bot-builder-java-quickstart?view=azure-bot-service-4.0

The bot works if I start the Java Echo Bot using the command: **java -jar target\echo-1.0.0.jar**

However, when I start the same application using the the following command directly, it does not work:
**cd target**
**java -jar echo-1.0.0.jar**

**Excepted output:**
HTTP 200 for http://localhost:3978/

**Actual output:**
HTTP 404 response for http://localhost:3978/

The Bot emulator also fails to get the messages when using the 2nd method.

**Comment by v-kydela** [comment]
Thank you for the report, @gkgaurav31. I would like to help and I have a few questions.

1. Why do you want to run the command from a different folder?
2. What requests are you sending to http://localhost:3978/?
3. Does http://localhost:3978/api/messages also return 404?

**Comment by gkgaurav31** [comment]
@v-kydela : 
1. I will be deploying the JAR file on a VM, so it should work by directly using the JAR. 
2. During my test, I was just trying to get the default blue page via http://localhost:3978/ from browser - HTTP GET.
3. Yes.

**Comment by v-kydela** [comment]
@gkgaurav31 - I tried following the instructions in the document you linked to, and I could not get the bot to start at all using those steps. It doesn't look like the the generator generates a `target` folder, and I've reported that problem here: https://github.com/MicrosoftDocs/bot-docs/issues/2093

Are you sure you just followed the steps in that document, or did you perhaps include any additional steps to build the project, etc.?

**Comment by gkgaurav31** [comment]
You will need to run **mvn package** to build the jar

**Comment by mmiele** [comment]
There is a missing step in the documentation to create the JAR file. The fix is in the listed [PR 2727.](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2727)

**Comment by mmiele** [comment]
@gkgaurav31  > You will need to run **mvn package** to build the jar. You are correct.
We are fixing the documentation. Thanks

**Comment by mmiele** [comment]
The fix will be available in the next documentation update.
