### ISSUE TITLE
[LOC]Fixed inappropriate japanese "端末"→"ターミナル" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/bot-docs#2089]
ja-jp:"https://docs.microsoft.com/ja-jp/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0"
![bot-builder-python-quickstart_j](https://user-images.githubusercontent.com/40815708/121460294-b074b900-c9e7-11eb-990d-550f602ce24b.png)

en-us:"https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0"
![bot-builder-python-quickstart_e](https://user-images.githubusercontent.com/40815708/121460311-b4a0d680-c9e7-11eb-8ea8-ed65e773aecf.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a20df2-727c-1afd-2b87-836ea1ea4f7a
* Version Independent ID: 157fc262-fb1f-f12d-0890-e90119feb444
* Content: [Create a bot using Bot Framework SDK for Python - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/python/bot-builder-python-quickstart.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/python/bot-builder-python-quickstart.md)
* Service: **bot-service**
* GitHub Login: @emgrol
* Microsoft Alias: **kamrani**

**Comment by erhopf** [comment]
@hyoshioka0128 - Thank you for notifying us of this issue. We've reached out to our localization team and they will patch/update this article (and update this definition) in the July release. 

As this is now tracked as a work item internally, I'm closing this issue.
