### ISSUE TITLE
Will you also provide CreateConversation smaple?

### ISSUE THREAD

**Issue by antonvidishchev** [MicrosoftDocs/bot-docs#209]
Pro-active messaging that is based on existing conversations is clear, however, how should I use the CreateConversation method? It is confusing how to specify the Channel Account of the user to be messaged.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc28a40-716e-22bc-8944-15f0a8b0d5c2
* Version Independent ID: 86252b0d-94e2-2ea6-ed17-fc32ae38e6fc
* Content: [How to use proactive messaging - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/Microsoft/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by JonathanFingold** [comment]
@antonvidishchev , I am rewriting this topic and will include more information about **ContinueConversation**. I will try to get a separate article out that convers **CreateConversation**.

The **Microsoft.Bot.Builder.Adapters.BotFrameworkAdapter** defines an overload of CreateConversation that has a _conversationParameters_ property that you can use to specify the members to add to the conversation. Most channels do not support the creation of group conversations this way.

**Comment by metasonic** [comment]
@antonvidishchev did you manage to find a way to send proactive messages in conversations based only on the conversation id?
In the old version it looked like this, making it really easy to send messages based on a api call
https://github.com/MicrosoftDX/botFramework-proactiveMessages/blob/master/node/simpleSendMessage/index.js

**Comment by JonathanFingold** [comment]
@metasonic , Here's a link to an issue thread in the Botbuilder-dotnet repo. It contains a sample proactive bot that targets the daily build (as of the time of the posting, so there have been a few breaking changes since then). The article will be updated in about a month, and the technique outlined will be only slightly different. Let me know if this helps.

**Comment by Kaiqb** [comment]
I've added this request to the issues list in the botbuilder repo. You can track it using this link: https://github.com/Microsoft/BotBuilder/issues/5010
