### ISSUE TITLE
Cortana is no longer available on channels 

### ISSUE THREAD

**Issue by venkatx5** [MicrosoftDocs/bot-docs#2091]
Cortana is no longer available on channels to register. Please update the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be897af4-2b67-3bc3-7857-9de57017d6d3
* Version Independent ID: 6d8b34e6-4639-544a-b4d2-f6c981afb56d
* Content: [Add speech to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-text-to-speech?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-text-to-speech.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/rest-api/bot-framework-rest-connector-text-to-speech.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
We will remove Cortana from this article and check for references in other articles.

**Comment by mmiele** [comment]
Docs updated
