### ISSUE TITLE
Enabling authentication on Alexa

### ISSUE THREAD

**Issue by aishwaryaumachandran** [MicrosoftDocs/bot-docs#2092]
Is there documentation for enabling authentication for Alexa on Bot Framework? i.e if I want to use Email/Calendar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c24dc268-76db-f9d6-472f-4859a005792c
* Version Independent ID: 8279092d-0e86-c15b-89cb-8759eb25450d
* Content: [Connect a bot to Alexa - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-alexa?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-alexa.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-connect-alexa.md)
* Service: **bot-service**
* GitHub Login: @NickEricson
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@aishwaryaumachandran There is more in the [README](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.Alexa) for the community adapter.

**Comment by mmiele** [comment]
The fix will be available in the upcoming documentation update.
