### ISSUE TITLE
The steps given in the Java quickstart are insufficient to start the bot

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#2093]
Following the instructions in the Java quickstart, I cannot start the bot. The instructions go straight from running the Yeoman generator to running the jar file, with no steps in between to create the jar file, etc. I'm noticing that the generator does not produce a `target` folder:

![image](https://user-images.githubusercontent.com/41968495/121972078-16867680-cd2f-11eb-9dde-e7834197fa61.png)

Are there any missing steps in this document? Does the project need to be built after it's generated, perhaps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 748e48cd-09ac-2aaa-8dab-9e0615c70652
* Version Independent ID: 4b25c9d1-dcab-ea00-3835-0fe4b72943dd
* Content: [Create a bot using Bot Framework SDK for Java - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/java/bot-builder-java-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/java/bot-builder-java-quickstart.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/java/bot-builder-java-quickstart.md)
* Service: **bot-service**
* GitHub Login: @mmiele
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
There is a missing step in the documentation to create the JAR file. The fix is in the listed [PR 2727.](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2727)

**Comment by mmiele** [comment]
The fix will be available in the next documentation update.
