### ISSUE TITLE
Small sentence correction

### ISSUE THREAD

**Issue by jameshoff-msft** [MicrosoftDocs/bot-docs#2094]
says "However, you can choose to use a differ application layer for your app."
would be better : "However, you can choose to use a different application layer for your app."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ccf81d0-a7a0-1e2a-5b35-8cfd723c1225
* Version Independent ID: e3ebe0a1-a22f-1535-c649-3f79158b4ece
* Content: [How bots work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by emgrol** [comment]
Thanks for pointing this out, a fix should go live shortly.

**Comment by emgrol** [comment]
Closing now that the issue fix has been merged.
