### ISSUE TITLE
Explain how to emit custom event with custom properties

### ISSUE THREAD

**Issue by MACEL94** [MicrosoftDocs/bot-docs#2097]
Hi

Is there a way for emitting custom events using the same telemetryClient or add custom properties to enrich the events that are already being correctly exported?

I didn't find any simple example.
I'd like to save not a metric but a custom event("location") that clients send me(latitude, longitude) so then i will be able to plot them in a PBI dashboard.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bd316bd-4f82-195f-6530-38474ce69cef
* Version Independent ID: 78f7afc4-8d6d-b98f-cd6e-cee82b9425e2
* Content: [Events generated by the Bot Framework Service telemetry - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-reference?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-telemetry-reference.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-telemetry-reference.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by garypretty** [comment]
@MACEL94 If you're using pure SDK then all dialogs have a TelemetryClient and you can call TelemetryClient.TrackEvent from anywhere, which allows you to send a custom event and also add whatever custom properties you wish.  If you're using Composer then you have an action available to track a custom telemetry event also.

**Comment by garypretty** [comment]
Additionally, if you want to add properties to all events logged, then you can implement your own class using TelemetryLoggerMiddleware as a base class.  This will allow you to override methods such as FillSendEventProperties - here you can call the base method and then add your own properties and they will be appended to every outgoing event, something like...

```cs
override Task<Dictionary<string, string>> FillSendEventPropertiesAsync(Activity activity, Dictionary<string, string> additionalProperties = null)
        {
        var props = base.FillSendEventPropertiesAsync(activity, additionalProperties);
        
        props.Add("myCustomPropertyKey", "myCustomPropertyValue");
        
        return props;
}
```

Then you just need to update the service registration in startup.cs to ensure your implementation gets used.

```cs
services.AddSingleton<TelemetryLoggerMiddleware, MyTelemetryMiddlewareClass>();
```

**Comment by MACEL94** [comment]
Thank you, got it working!

**Comment by JonathanFingold** [comment]
Excellent. I'll work on updating the telemetry docs over the next few weeks.
