### ISSUE TITLE
Scope value is not working properly

### ISSUE THREAD

**Issue by nitin-kumolus** [MicrosoftDocs/bot-docs#2098]
In curl request(getting bot token) ->
 for scope value -> "https://graph.microsoft.com/.default"  and 
     scope_value -> https%3A%2F%2Fapi.botframework.com%2F.default

Getting right token value  for both scope values.But for first scope value( "https://graph.microsoft.com/.default" ) if i use this token to send message to user then i am getting {"message":"Authorization has been denied for this request."}.

This is confusing and in Ruby i guess "https%3A%2F%2Fapi.botframework.com%2F.default" scope value is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03c49826-bbc8-1589-7b80-ad46c6cbcac6
* Version Independent ID: 327925a7-ec0d-0d00-f3c6-16f62cdf05b9
* Content: [Create a bot with the Bot Connector service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-quickstart.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/rest-api/bot-framework-rest-connector-quickstart.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by stevkan** [comment]
@nitin-kumolus, I don't believe Graph tokens can be used in place of tokens created using the Bot Framework REST API. However, I am double checking that and will respond once I have an update.

**Comment by stevkan** [comment]
@nitin-kumolus, when calling the BotFramework REST API the scopes that are passed in are specific to that API as validation is performed to verify that only the correct scopes are accepted. So, passing in the Graph scopes will not work. You will need to use the `https://api.botframework.com/.default` scope.

Closing this as resolved.
