### ISSUE TITLE
getsessionid endpoint missing?

### ISSUE THREAD

**Issue by tomezpl** [MicrosoftDocs/bot-docs#2099]
We're using the DirectLine REST API to connect our frontend web app to our web app bot. Recently, we've added user authentication using Bot Framework's OAuth2 support. However, the validation/"magic" code prompt kept showing up no matter what - I've followed the documentation exactly through each step and couldn't find anything we missed (enabled enhanced authentication, added trusted origins, etc.) 

After trying WebChat with our bot instead, I've realised that DirectLineJS doesn't suffer from this issue because it makes a call to the endpoint `session/getsessionid` which doesn't appear to be documented anywhere in the REST API docs. It's referenced in the DirectLineJS source here: [https://github.com/microsoft/BotFramework-DirectLineJS/blob/ef94e994c8a52c5665ab8cfa52228191bd7a7595/src/directLine.ts#L725](https://github.com/microsoft/BotFramework-DirectLineJS/blob/ef94e994c8a52c5665ab8cfa52228191bd7a7595/src/directLine.ts#L725). I've implemented this in our frontend code and it does work, but I'm curious as to whether this is purposely not included in the docs or is it just an oversight?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd81692-76ae-f89f-19d8-d92845cc7dc9
* Version Independent ID: c26a44b5-6995-11e0-daa0-001a2716b9f1
* Content: [API reference - Direct Line API 3.0 - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-api-reference.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-api-reference.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
With a quick review of the Bot Framework protocol [Swagger files ](https://github.com/microsoft/botframework-sdk/tree/main/specs/botframework-protocol), it looks like `session/getsessionid` is described there, at least for Direct Line 3.0.

The REST API documentation is under review, and we are looking to improve the documentation soon, but we don't have a timeframe yet. Sorry I don't have a more satisfying answer at the moment. Hopefully, having a link to the current Swagger file is useful.

If you have other questions, let me know.

**Comment by tomezpl** [comment]
Thanks - admittedly, I haven't checked the Swagger files, I only looked at the docs article, so this helps a lot :)
