### ISSUE TITLE
"Navigate to your bot's Bot Channels Registration blade on the Azure Portal." What???

### ISSUE THREAD

**Issue by AskYous** [MicrosoftDocs/bot-docs#210]
What's the "Bot's Bot Channel Registration blade?" I don't see it. Is this out of date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d80e0b-f1b7-175b-128d-0fb12f17ae36
* Version Independent ID: 1ed9006a-bf0b-9aaa-d180-9d2cb0c09524
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0#create-your-bot-and-an-authentication-application)
* Content Source: [articles/bot-builder-tutorial-authentication.md](https://github.com/Microsoft/bot-docs/blob/live/articles/bot-builder-tutorial-authentication.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **JonathanFingold**

**Comment by JonathanFingold** [comment]
@AskYous , Before you can register your Azure AD application, you first need to [create you bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0#create-your-bot-on-azure). Once you've done that, you can get to its properties and settings by searching your resources for the Bot Channels Registration you just created.

I'll update the topic to remove the jargon, "blade", which I'm probably misusing here anyway.

**Comment by AskYous** [comment]
Hey @JonathanFingold! Thanks for the reply! Here's a screenshot of my Azure portal. I don't know what or where the "Registration blade" is.

![image](https://user-images.githubusercontent.com/791996/43967979-af8303aa-9c7a-11e8-845b-b310aa4141bf.png)

**Comment by AskYous** [comment]
Hey @JonathanFingold. Let me explain more of what I'm trying to do. I would like to create a web chat bot where users can sign in using Microsoft Open Graph. Then the bot can help with their calendar events or emails. So I would need users to authenticate themselves using the bot.

**Comment by iMicknl** [comment]
@AskYous You are on the right page. Just click on 'Settings' under the section 'Bot Management', which is visible on your screenshot. From there on you could just follow the guidance on the Microsoft Docs page.

>Navigate to your bot's Bot Channels Registration blade on the Azure Portal.
>Click Settings.

**Comment by JonathanFingold** [comment]
No problem @AskYous . It looks like you've created the wrong type of resource.

First, create a Bot Channels Registration:

![createbotchannelsregistration](https://user-images.githubusercontent.com/35047199/43968368-bfa3528e-9c7b-11e8-80aa-6d14caea2f08.PNG)

Then, this is what you should see when you navigate to the page for that resource:

![botchannelsregistrationpage](https://user-images.githubusercontent.com/35047199/43968191-3bc42498-9c7b-11e8-8120-fe1724953325.PNG)

You'll still be able to publish your web app bot to this resource, but it may be a slightly different process than you've used in the past. [Deploy your bot to Azure](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-3.0) describes how to do so from Visual Studio.

**Comment by AskYous** [comment]
Thanks guys!
