### ISSUE TITLE
Publish bot code directly to Azure with publishing profile not mentioned as a deployment method.

### ISSUE THREAD

**Issue by frankodoom** [MicrosoftDocs/bot-docs#2100]
Why doesn't this document talk about publishing your bot directly to azure from visual studio using the publishing profile? I think this is one of the fastest ways to go about it, especially for beginners and people with minimal CLI and KUDU knowledge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
I've brought this up with the team. We're discussing which options to support without making the article too complex. We'll update this issue when we have a concrete plan.

**Comment by JonathanFingold** [comment]
We've decided no to document this scenario, and just focus on one or two scenarios to support in the docs.
