### ISSUE TITLE
Is there a way i can test for choices?

### ISSUE THREAD

**Issue by MACEL94** [MicrosoftDocs/bot-docs#2102]
Hi

Sorry to bother you, but I don't know if I'm doing something wrong.
If I wanted to test my logic and verify the fact that given an input, i can expect one or more choices from a dialog, could i do that?

I am able to test the text portion of replies in unit tests but i don't understand if i can test that the length of outputted choices, for a specific channel, are exactly 3.

```c#
using AzureMapsToolkit;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Builder.Testing;
using Microsoft.Bot.Builder.Testing.XUnit;
using Microsoft.Bot.Schema;
using Moq;
using System.Threading;
using System.Threading.Tasks;
using Xunit;
using Xunit.Abstractions;
```

...

```c#
public class TelegramStartDialogTests
{
private MockRepository mockRepository;

private Mock<IAzureMapsServices> mockAzureMapsServices;
private Mock<IBotTelemetryClient> mockBotTelemetryClient;
private readonly IMiddleware[] _middlewares;

public TelegramStartDialogTests(ITestOutputHelper output)
{
this.mockRepository = new MockRepository(MockBehavior.Loose);

this.mockAzureMapsServices = this.mockRepository.Create<IAzureMapsServices>();
this.mockBotTelemetryClient = this.mockRepository.Create<IBotTelemetryClient>();
_middlewares = new[] { new XUnitDialogTestLogger(output) };
}

private TelegramStartDialog CreateTelegramStartDialog()
{
return new TelegramStartDialog(
this.mockAzureMapsServices.Object,
this.mockBotTelemetryClient.Object);
}

[Fact]
public async Task ChooseTroubleAsync_ReceveingValidMessage_ShouldSuggest3Options()
{
// Arrange
var telegramStartDialog = this.CreateTelegramStartDialog();
var testClient = new DialogTestClient(Microsoft.Bot.Connector.Channels.Telegram, telegramStartDialog, _middlewares);

var reply = await testClient.SendActivityAsync<Activity>("anymessage");
Assert.Contains("# Welcome", reply.Text); //Ok

//How do i test that choices are 3 here?
}
```

This is the part I'd like to test for choices:

```c#
        public async Task<DialogTurnResult> MethodNameAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
            var data = stepContext.Context.Activity.ChannelData as dynamic;

            string msg = @$"# Welcome {data?.message?.from?.first_name}

How can i help you?";
            var retryText = $"Please choose one option.\n\n{msg}";
            var retryPromptText = MessageFactory.Text(retryText, retryText, InputHints.ExpectingInput);

            return await stepContext.PromptAsync("ChoiceTextDialog", new PromptOptions()
            {
                Prompt = MessageFactory.Text(msg),
                Choices = ChoiceFactory.ToChoices(new List<string> { "option a", "option b", "option c" }),
                RetryPrompt = retryPromptText
            }, cancellationToken);
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afcaa01f-5e9c-8b11-9dbe-9f9740a45397
* Version Independent ID: b24363df-987f-75c3-a8b8-eab8509aa13c
* Content: [Unit test bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/unit-test-bots?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/unit-test-bots.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/unit-test-bots.md)
* Service: **bot-service**
* GitHub Login: @gabog
* Microsoft Alias: **ggilaber**

**Comment by JonathanFingold** [comment]
For most channels, a choice prompt sends a `message` activity that contains suggested actions. The Activity protocol describes the "shape" of activities. See [Suggested action](https://github.com/Microsoft/botframework-sdk/blob/main/specs/botframework-activity/botframework-activity.md#suggested-actions) for specifics.

We haven't discussed in the docs how the prompts are implemented, but let me know if you'd like pointers into the SDK code.

**Comment by JonathanFingold** [comment]
[Debug a bot with inspection middleware](https://docs.microsoft.com/azure/bot-service/bot-service-debug-inspection-middleware) might be useful for discovering how individual activities are formed. You could then use that to inform how you construct your tests.

**Comment by MACEL94** [comment]
Hi Jonathan

thank you for your answers, i sorted it out.
Basically something breaks but doesn't really throw any Exception when instantiating choices with strings that are too long.

When this happens, no actions get suggested, and during the context.PromptAsync(...) i get back a generic error.

Now that i used shorter strings for choices, everything is correctly working(both in tests and in the live BOT).

Thank you again

**Comment by JonathanFingold** [comment]
Made a suggestion/feature request in the dev repo.

**Comment by skommireddi** [comment]
> Hi Jonathan
> 
> thank you for your answers, i sorted it out.
> Basically something breaks but doesn't really throw any Exception when instantiating choices with strings that are too long.
> 
> When this happens, no actions get suggested, and during the context.PromptAsync(...) i get back a generic error.
> 
> Now that i used shorter strings for choices, everything is correctly working(both in tests and in the live BOT).
> 
> Thank you again

Hi @MACEL94 Can you help me with the repro steps for this issue and the generic error you get when choices are too long. I am looking into this to see if we can show a clear exception when choice prompts are too long.

**Comment by skommireddi** [comment]
@MACEL94 Hi Francesco, Can you help me with the repro steps for this issue and the generic error you get when choices are too long. I am looking into this to see if we can show a clear exception when choice prompts are too long.

**Comment by MACEL94** [comment]
Hi @skommireddi 

i changed the code a lot since the first of july when i wrote this issue, and i also updated every package to their latest version.
I tried but i'm not able to reproduce it anymore, so it was either my error or it was fixed.

Thank you for your time and help, and sorry if i wasn't clear enough on the code used.

**Comment by skommireddi** [comment]
Thanks @MACEL94 for getting back. Since this cannot be reproduced, I will close the issue [5759- Throw clear exception when choice prompt strings are too long.](https://github.com/microsoft/botbuilder-dotnet/issues/5759) linked to this for now.
