### ISSUE TITLE
Which channels are Premium and which are Standard

### ISSUE THREAD

**Issue by geo-msft** [MicrosoftDocs/bot-docs#2104]
[Enter feedback here]
Could you clearly document in this page or other bot docs page which are the Premium channels and which are the Standard channels? 

Thank you. // I am sorry I did not find the doc clearly stating which are premium and which are standard. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3882e9d-ce18-408f-194c-7d973000b3a7
* Version Independent ID: 1017b42b-84de-1827-bb7e-0ca7270c1a0f
* Content: [Configure a bot to run on one or more channels - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-channels?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-manage-channels.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-manage-channels.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mainguy70** [comment]
Hi, can you tell me where you are seeing "premium vs standard"?

**Comment by geo-msft** [comment]
Hi, in this pricing doc: https://azure.microsoft.com/en-us/pricing/details/bot-services/ 

![image](https://user-images.githubusercontent.com/57954688/124712381-ee420000-df07-11eb-9d2f-fd0eac3e78f1.png)

And it is not clear which channels are Premium and which are Standard.

**Comment by JonathanFingold** [comment]
@geo-msft I _think_ that just Web Chat and Direct Line are premium. @mainguy70 can confirm.

**Comment by JonathanFingold** [comment]
I have confirmation, finally, that Direct Line is the only premium channel at this time. We'll figure out how we can update the relevant docs to make this clearer.
