### ISSUE TITLE
Wrong parameter name

### ISSUE THREAD

**Issue by yuharucan** [MicrosoftDocs/bot-docs#2105]
[Enter feedback here]
Option 2: New App Service Plan
az deployment group create --resource-group "<name-of-resource-group>" --template-file "<path-to-template-with-preexisting-rg.json>" --parameters appId="<app-id-from-previous-step>" appSecret="<password-from-previous-step>" botId="<id or bot-app-service-name>" newWebAppName="<bot-app-service-name>" newAppServicePlanName="<name-of-app-service-plan>" newAppServicePlanLocation="<region-location-name>" --name "<bot-app-service-name>"

"newAppServicePlanLocation" does not exist. "appServicePlanLocation" need to be used.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53c67a1a-6151-18a9-b5a4-bc84693592bc
* Version Independent ID: 61e09eab-c8f9-097e-d0d7-b75208d457d3
* Content: [Tutorial to deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=csharp#option-1-existing-app-service-plan)
* Content Source: [articles/v4sdk/bot-builder-tutorial-deploy-basic-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-tutorial-deploy-basic-bot.md)
* Service: **bot-service**
* GitHub Login: @mmiele
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Closing now that the fix is merged.
