### ISSUE TITLE
Fpr more information => For more information

### ISSUE THREAD

**Issue by nirmalkrishnav** [MicrosoftDocs/bot-docs#2106]
Typo in **Get Azure bot resource password from the Azure key vault** section

**Fpr** more information, see Use Key Vault 

I think it should be **For** more information, see Use Key Vault 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe8cc9a-f4d9-bf84-e92b-628b612b0883
* Version Independent ID: b075774f-a422-f39f-e82f-36220884f30a
* Content: [Manage a bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-overview?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-manage-overview.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-manage-overview.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by nirmalkrishnav** [comment]
Url: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-overview?view=azure-bot-service-4.0

**Comment by emgrol** [comment]
Thanks for pointing this out, the typo has been fixed.
