### ISSUE TITLE
Update the TLS section

### ISSUE THREAD

**Issue by x509cert** [MicrosoftDocs/bot-docs#2107]
Hey guys, we need to make some edits to the SSL/TLS section, to make it tighter and more accurate. Here's my proposed wording.

>>start

Securing Network Traffic (was Protocols and Encryption) 
Protocols exist that provide cryptographic controls to address data tampering and disclosure during transmission. In this regard, bots should communicate only over secured channels.

To exchange data on the wire the system must use the HTTPS protocol, which transfers data using HTTP over Transport Layer Security (TLS). See also RFC 2818 - HTTP Over TLS.

<<end

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45b3f75-ffd6-c50a-5d2b-3b1bf3223879
* Version Independent ID: d4ce336f-7888-90ef-d329-1bde4fd53635
* Content: [Bot Framework security guidelines - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-security-guidelines?view=azure-bot-service-4.0&source=docs#feedback)
* Content Source: [articles/v4sdk/bot-builder-security-guidelines.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-security-guidelines.md)
* Service: **bot-service**
* GitHub Login: @mmiele
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@x509cert I updated  the article based on your suggestion, Let me know if you can access the PR [2777 ](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2777)

**Comment by x509cert** [comment]
@mmiele i can't see the PR... but so long as it's close to the above then we're good :)

**Comment by mmiele** [comment]
@x509cert The section now reads:

Securing Network Traffic
Protocols exist that provide cryptographic controls to address data tampering and disclosure during transmission. In this regard, bots should communicate only over secured channels.

To exchange data on the wire any secure system must use the HTTPS protocol, which transfers data over HTTP in encrypted connections protected by Transport Layer Security (TLS) or Secure Sockets Layer (SSL). See also RFC 2818 - HTTP Over TLS.

**Comment by mmiele** [comment]
Fix in the upcoming doc update.
