### ISSUE TITLE
Incorrect parameter name on deployment using template-with-preexisting-rg template

### ISSUE THREAD

**Issue by ldardick** [MicrosoftDocs/bot-docs#2108]
Under the [Option 2: New App Service Plan](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=java#option-2-new-app-service-plan) section, the documentation is prompting to use the `newAppServicePlanLocation`, but the ARM templates on the [BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples) repository uses `appServicePlanLocation` instead, causing the Azure CLI command to fail.

For example: 

**Java sample:**
https://github.com/microsoft/BotBuilder-Samples/blob/e1b6d70b2be013bb5656f3652350c3c3bfc8b6bb/samples/java_springboot/02.echo-bot/deploymentTemplates/template-with-preexisting-rg.json#L50-L56

**C# Dotnet Core Sample:**
https://github.com/microsoft/BotBuilder-Samples/blob/e1b6d70b2be013bb5656f3652350c3c3bfc8b6bb/samples/csharp_dotnetcore/02.echo-bot/DeploymentTemplates/template-with-preexisting-rg.json#L50-L55

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=java#option-2-new-app-service-plan)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
If I follow correctly, the correct parameter name is `appServicePlanLocation`. I see one place in the doc that still uses the incorrect parameter name `newAppServicePlanLocation`. I'll work on that.

**Comment by ldardick** [comment]
> If I follow correctly, the correct parameter name is `appServicePlanLocation`. I see one place in the doc that still uses the incorrect parameter name `newAppServicePlanLocation`. I'll work on that.

That's right, the correct one (according to the ARM template) is `appServicePlanLocation`.

**Comment by JonathanFingold** [comment]
Fixed in master. Change will go live the next time we push content live.
