### ISSUE TITLE
[LOC]Unnecessary asterisks are displayed

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/bot-docs#2112]
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp
![bot-builder-howto-v4-storage_e](https://user-images.githubusercontent.com/40815708/126760035-5e599c95-fa33-459a-8313-ae5e7efb2840.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Fixed in PR. Change will go live with the next live sync.
