### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by FastmoreCrak** [MicrosoftDocs/bot-docs#2113]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 260c283c-f5e9-e00d-19ec-ee9df18335e5
* Version Independent ID: d1525408-36d3-6575-2331-a16379744a59
* Content: [Create a bot for Telegram - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-telegram?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-telegram.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-connect-telegram.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
This looks like a mis-click. Please provide more information if you found a documentation issue in this topic.
