### ISSUE TITLE
Typo and update to code snippets

### ISSUE THREAD

**Issue by compulim** [MicrosoftDocs/bot-docs#2114]
## Typo

- `AZP.NET` -> `ASP.NET`
- `App Service extension Keys` -> `App Service Extension Keys`

## Update the link for OOP

Update the link of "See Out-of-process hosting model in the AZP.NET Core documentation for more information.".

Please point to this link instead, https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1&preserve-view=true#attributes-of-the-aspnetcore-element.

The previous link is asking the dev to modify `.csproj`, which is not true. We should modify the `web.config/configuration/system.webServer/aspNetCore/hostingModel` to use OOP instead.

```diff
  <?xml version="1.0" encoding="utf-8"?>
  <configuration>
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
-     <aspNetCore processPath="dotnet" arguments=".\EchoBot.dll" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles\stdout" hostingModel="inprocess" />
+     <aspNetCore processPath="dotnet" arguments=".\EchoBot.dll" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles\stdout" hostingModel="outofprocess" />
    </system.webServer>
  </configuration>
```

## Update code snippets

The Echo Bot template has been updated. The new code snippet should look like this.

```diff
  public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
  {
      if (env.IsDevelopment())
      {
          app.UseDeveloperExceptionPage();
      }

      app.UseDefaultFiles()
          .UseStaticFiles()
          .UseWebSockets()
+         // Allow the bot to use named pipes.
+         .UseNamedPipes(System.Environment.GetEnvironmentVariable("APPSETTING_WEBSITE_SITE_NAME") + ".directline")
          .UseRouting()
          .UseAuthorization()
          .UseEndpoints(endpoints =>
          {
              endpoints.MapControllers();
          });

      // app.UseHttpsRedirection();
  }
```

## Add section for updating the Bot SDK

Bot SDK 4.11.0 does not work with DL ASE due to a bug, https://github.com/microsoft/botbuilder-dotnet/issues/5110.

Please add a bullet point to ask the dev to update it to latest version (4.14.1 looks good). Currently, the Echo Bot provisioned by Azure is 4.11.0.

To update to use latter version of Bot SDK, modify `EchoBot.csproj` as follow:

```diff
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.1" />
-   <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.11.0" />
+   <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.14.1" />
  </ItemGroup>
```

## Surface "HTTP Error 500.34 - ANCM Mixed Hosting" issue

Echo Bot template is by default using in-process, instead of OOP.

That means, it will always fail.

I think the step to enable OOP (a.k.a. "ANCM Mixed Hosting" issue) always present. That means, instead of outlining it in FAQs, we should put this one in the step, because it is a "must do" to enable the bot, not optional step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72c259-a864-9e1c-b585-562d6bca80ff
* Version Independent ID: 30a3fce8-d236-5c7b-88a0-003c971f2819
* Content: [.NET bot with Direct Line App Service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
The fixed docs will be in the upcoming documentation update.
