### ISSUE TITLE
`xPath` examples should use the correct casing.

### ISSUE THREAD

**Issue by tonyanziano** [MicrosoftDocs/bot-docs#2115]
In some of the examples for the prebuilt function `xPath`, the expression invokes the function `xpath` which is the wrong casing, and will result in an exception being thrown.

![image](https://user-images.githubusercontent.com/3452012/127394967-199e6967-75d1-430c-8b95-633cd34d56fd.png)

These should be corrected to show `xPath` with a capital "P".

Reference: **https://github.com/microsoft/botframework-sdk/issues/6353**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5cc1453-1ec4-1ad7-2a9f-fa934224b79d
* Version Independent ID: 9645f547-d38a-4a22-c84b-ee98b7f24dfc
* Content: [Adaptive expressions prebuilt functions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#xPath)
* Content Source: [articles/adaptive-expressions/adaptive-expressions-prebuilt-functions.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/adaptive-expressions/adaptive-expressions-prebuilt-functions.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Fixed in [PR 2774](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2774).
