### ISSUE TITLE
AADv2 needs docs on where to find the token exchange url

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/bot-docs#2116]
there's nothing about where to find this, should at least link to other docs if not explain the discovery in steps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb435f0d-6418-4868-9e50-e73348f5fabc
* Version Independent ID: ba585475-9607-26a7-f14f-56b71cdb5596
* Content: [Identity providers Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-identity-providers?view=azure-bot-service-4.0&tabs=adv1%2Cga2)
* Content Source: [articles/v4sdk/bot-builder-concept-identity-providers.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-concept-identity-providers.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@drdamour Could you please refer to the Note that is in the section [Create an OAuth connection settings](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml#create-an-oauth-connection-settings)? Let us know if it helps.

**Comment by drdamour** [comment]
> @drdamour Could you please refer to the Note that is in the section [Create an OAuth connection settings](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml#create-an-oauth-connection-settings)? Let us know if it helps.

All it says is leave it blank, this does not help me

**Comment by swagatmishra2007** [comment]
The token exchange url is left blank only for the root bot. The value is populated for the skill bot . Please look at the documentation at https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml#create-an-oauth-connection-settings-1 to see how to get the value for it.

The exchange url is used to figure out what scope would be needed to call the skill bot from the root bot. 
For example, let's say the root bot had an appid1 and skill had appid2. for appid1, you have a scope created as scope1 and for appid2, you have a custom scope created as scope2. The token exchange url for skillbot would be api://appid2/scope2 . This value is used inside the bot builder sdk to call the botframework token service to get a token targetting the appid2/scope2 scope. 
Please refer the first flow diagram here - https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-sso?view=azure-bot-service-4.0#sso-components-interaction (virtual assistant bot is the root bot in this case)

**Comment by mmiele** [comment]
The fixed documentation will be available in the upcoming docs update.

**Comment by drdamour** [comment]
perfect, thx for the note and the cross link, doc makes more sense now
