### ISSUE TITLE
Update documentation to indicate that a channel may send a single Conversation Update

### ISSUE THREAD

**Issue by p-nagpal** [MicrosoftDocs/bot-docs#2118]
Some channels like DirectLine may also send a single Conversation Update activity indicating that both the bot and the user have joined the conversation. This happens in cases when the user information is available at the conversation start. The DirectLine channel includes both ChannelAccounts (bot, user) in a single Conversation Update activity. 

Could we request the following documentation page be updated with this note: 
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0

Parent issue: https://github.com/microsoft/botframework-sdk/issues/6359 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ccf81d0-a7a0-1e2a-5b35-8cfd723c1225
* Version Independent ID: e3ebe0a1-a22f-1535-c649-3f79158b4ece
* Content: [How bots work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
Fixed in PR. Change should be live within a week or so.
