### ISSUE TITLE
This page will be replaced by a new one?

### ISSUE THREAD

**Issue by fedsp** [MicrosoftDocs/bot-docs#2119]
Since Microsoft announced the deprecation of dispatch, how the orchestrator will handle the same business needs as the dispatcher?

Given this example:
4 QnaMaker knowledge bases: "employees utilities", "employees code of conduct", "guests utilities" and "guests code of conduct".
2 Luis apps: employeesBot and guestsBot.
"employeesBot" is attached to the first 2 Kbs, and "guestsBot" is attached to the last 2 Kbs.

Both the KBs "employees utilities" and "guests utilities" has this qna pair:
"What is the building Wifi Password?.
However, the answer for this question is different in each KB.

The business need (currently fulfilled by dispatcher) is pretty simple:
The user who have access to the "employeesBot" sees only the answer provided by the "employees utilities" KB and the user who have access to the "guestsBot" sees only the answer provided by the "guests utilities" KB.

1 bot registration, 2 different luis apps, updated constantly by the 'dispatch refresh' command.

Is this goal still reachable by the orchestrator?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use Dispatch for multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
@scheyal/@daveta: Do you know if this is possible?

**Comment by jiruss** [comment]
@scheyal @daveta Can we get a comment on this? There is a support issue on this internally for the same and we need an answer.

**Comment by tsuwandy** [comment]
@fedsp, this page is the Orchestrator version
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-orchestrator?view=azure-bot-service-4.0&tabs=cs

**Comment by scheyal** [comment]
See the following for dispatch alternatives:
* https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-orchestrator?view=azure-bot-service-4.0&tabs=cs
* https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/14.nlp-with-orchestrator
* https://github.com/microsoft/botframework-sdk/tree/main/Orchestrator

**Comment by hcyang** [comment]
Hi @fedsp, yes Orchestrator is a shoo-in replacement of LUIS Dispatch. Please follow the pages posted by @scheyal for details.

**Comment by fedsp** [comment]
Got it. The "shoo-in replacement" makes me confident, I will proceed implementing the things and I will come back if somehow I got blocked.

**Comment by hcyang** [comment]
Hi @fedsp, let us know your experiences of using Orchestrator. The "shoo-in replacement" was in terms of functionality, not API compatibility. I.e., Orchestrator is no longer a LUIS app, but you can create a BotFramework Recognizer just like you can create a Recognizer using a Dispatch LUIS app.
