### ISSUE TITLE
Installing packages don't work

### ISSUE THREAD

**Issue by Rykimaruh** [MicrosoftDocs/bot-docs#212]
I tried installing, but I get error mesages when using nuget console. I tried looking on nuget browser and nothing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ab01d4-92a2-3213-7cf4-ae6046ce17de
* Version Independent ID: e7999c0c-77ac-3018-ff2c-11bcd7f51fa6
* Content: [Translate user input to make your bot multilingual - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-translation?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-translation.md](https://github.com/Microsoft/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-translation.md)
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
@Rykimaruh Which link are you using?

**Comment by Rykimaruh** [comment]
@Kaiqb these ones:

[https://www.nuget.org/packages/Microsoft.Bot.Builder.Ai.LUIS/4.0.1-preview](https://www.nuget.org/packages/Microsoft.Bot.Builder.Ai.LUIS/4.0.1-preview)

[https://www.nuget.org/packages/Microsoft.Bot.Builder.Ai.Translation](https://www.nuget.org/packages/Microsoft.Bot.Builder.Ai.Translation)

[https://www.nuget.org/packages/Microsoft.Bot.Builder.Integration.AspNet.Core/](https://www.nuget.org/packages/Microsoft.Bot.Builder.Integration.AspNet.Core/)

the article doesn't specify which ones exclusively so I just searched for the nuget

**Comment by Kaiqb** [comment]
@Rykimaruh - the translation middleware is no longer in the v4 SDK. Instead, you can use the approach shown in the Multilingual Bot sample: https://github.com/Microsoft/BotBuilder-Samples/tree/v4/csharp_dotnetcore.
