### ISSUE TITLE
Continuos deployment for new Azure Bot resource

### ISSUE THREAD

**Issue by hinojosachapel** [MicrosoftDocs/bot-docs#2120]
Microsoft is deprecating Web App Bot in favor of new Azure Bot. When you create a Web App Bot, an App Service is automatically created where you can host the source code of your bot, along with two other needed resources. When you create an Azure Bot resource, only this resource is created. Fine, no problem, as long as you know what other resources you need for your bot. But the documentation seems to be incompleted or outdated. This article explain how to set up continuos deployment from an App Service, but we cannot create an App Service. We need to create a Web App. So, in summary, when you create an Azure Bot, what are the next steps in order to keep things working as previously with Web App Bot.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e9b10d5-ca65-d08c-2f11-ba62d66b8f80
* Version Independent ID: 396d52c0-d864-afac-4d1c-fd6880a973a9
* Content: [Configure continuous deployment for Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-build-continuous-deployment.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-build-continuous-deployment.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@hinojosachapel - Deploy your bot manually, at least once, before setting up continuous deployment. After initial deployment, all the necessary resources should be in place for your bot, such as the app service.

Let me know if you have a more specific question.

**Comment by hinojosachapel** [comment]
THNX @JonathanFingold! I'll give it a try.
