### ISSUE TITLE
Missing step in how to welcome users

### ISSUE THREAD

**Issue by lijithomas2020** [MicrosoftDocs/bot-docs#2121]
The article could refer to the step on creating the WelcomeUserState as well.

public class WelcomeUserState
    {
        // Gets or sets whether the user has been welcomed in the conversation.
        public bool DidBotWelcomeUser { get; set; } = false;
    }

without the above, the following lines alone will not be executable-

var welcomeUserStateAccessor = UserState.CreateProperty<WelcomeUserState>(nameof(WelcomeUserState));
var didBotWelcomeUser = await welcomeUserStateAccessor.GetAsync(turnContext, () => new WelcomeUserState(), cancellationToken);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 534e4b75-75fe-bdf9-5978-e75852a66390
* Version Independent ID: 92b81bb4-b10c-ca88-ed2f-a1537f460075
* Content: [Send welcome message to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Service: **bot-service**
* GitHub Login: @DanDev33
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
The fixed documentation will be available in the next docs update.
