### ISSUE TITLE
Typo "bot Emulator"→"Bot Emulator"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/bot-docs#2122]
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-orchestrator?view=azure-bot-service-4.0&tabs=cs
![bot-builder-tutorial-orchestrator_e](https://user-images.githubusercontent.com/40815708/129876123-8af299cb-e650-4cef-adea-03717f249f2f.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b917a5b0-2fe8-6070-ce27-02543205d078
* Version Independent ID: 8a129a06-7836-40db-c4f3-b62eea7d7b52
* Content: [Use multiple LUIS and QnA models with Orchestrator - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-orchestrator?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-tutorial-orchestrator.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-tutorial-orchestrator.md)
* Service: **bot-service**
* GitHub Login: @tsuwandy
* Microsoft Alias: **tiens**

**Comment by emgrol** [comment]
Thanks for pointing this out. Closing now that the issue fix has been merged.
