### ISSUE TITLE
References to preview NuGet packages for DL-ASE can be updated.

### ISSUE THREAD

**Issue by DDEfromOR** [MicrosoftDocs/bot-docs#2123]
Hello, I hope this is the right process to file this!

On the 'Create .NET client with extension' page under Direct Line App Service Extension we have a sub-section and later references to an experimental NuGet package for the Bot Connector. These NuGets have been deprecated and the code within them moved to open source! The repo where the code can now be found is https://github.com/microsoft/BotFramework-DirectLine-DotNet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c463a003-c709-b516-ce1b-6c45537de3b2
* Version Independent ID: 8ca42668-23ac-6dca-054d-d183b0fb5b0b
* Content: [Create .NET client for direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-client.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-directline-extension-net-client.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
Fix in the next documentation update.
