### ISSUE TITLE
Documentation mentions deprecated npm package

### ISSUE THREAD

**Issue by EdwinOtten** [MicrosoftDocs/bot-docs#2125]
The documentation in paragraph [Installing Blob storage packages](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript#installing-blob-storage-packages) is out of date.
For javascript projects, the documentations recommends installing the `botbuilder-azure` package. That package is deprecated (mentioned [here](https://github.com/microsoft/botbuilder-js/issues/3669#issuecomment-838744692) by MSFT developer @joshgummersall). He recommends installing the `botbuilder-azure-blobs` package instead, which doesn't have the same critical vulnerabilities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
resolved
