### ISSUE TITLE
Unable to send a Card as an attachment Via Bot Framework Rest API

### ISSUE THREAD

**Issue by sunnydodhiya** [MicrosoftDocs/bot-docs#2126]
The BOT which is being used in this example is "AZURE BOT" and It's uploaded to the MsTeams.

While trying to send an Adaptive Card as an attachment from the BOT to the MsTeams Client via Bot Framework Rest Api Its throwing 403.

**Request**:
method=POST, url=https://smba.trafficmanager.net/in//v3/conversations/a:1FrXZEq8MUMyERAJ6JZ8h_QpM-ItPUSgIr1kBnzk47ezvdX1rZnfYkmLxAB3ZVOflXlAwE9GruuKbHYGX1REvjOMqe9gOPDGuiIwy-2HSRLLlXryZSsiD5V9U1KtvWavq/activities, tags={}

**Json for the Adaptive card (Body)**:

{"type": "message","attachments": [{"contentType":"application/vnd.microsoft.card.adaptive","content":{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","type":"AdaptiveCard","version":"1.0","body":[{"type":"ColumnSet","columns":[{"type":"Column","width":2,"items":[{"type":"TextBlock","text":"xyz","weight":"bolder","size":"medium"},{"type":"TextBlock","text":"xyz"},{"type":"Input.Text","id":"phoneNumber","placeholder":"+1 999 999 9999","style":"tel"}]}]}],"actions":[{"type":"Action.Submit","title":"Submit"}]}}]}

**The Token used for sending the request is generated via**:
https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token
By passing valid "client_secret" and "client_id" and "scope" and "grant_type".

**The Permissions attached to the AAD Applications are**:
* User.ReadWrite.All
* Directory.ReadWrite.All
* Group.ReadWrite.All
* TeamsAppInstallation.ReadWriteForTeam.All
All of them are Application Permissions

**Response for the above request is**:
Response{protocol=h2, code=403, message=, url=https://smba.trafficmanager.net/in//v3/conversations/a:1FrXZEq8MUMyERAJ6JZ8h_QpM-ItPUSgIr1kBnzk47ezvdX1rZnfYkmLxAB3ZVOflXlAwE9GruuKbHYGX1REvjOMqe9gOPDGuiIwy-2HSRLLlXryZSsiD5V9U1KtvWavq/activities

Can you please help me on this.
Thanks In advance!

**Comment by anusharr** [comment]
@sunnydodhiya, are you making use of any specific [botbuilder sample](https://github.com/microsoft/BotBuilder-Samples)?

**Comment by dmvtech** [comment]
Closing due to lack of response.
