### ISSUE TITLE
Test in Web Chat section is incorrect

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/bot-docs#2129]
In this document: [https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#test-in-web-chat](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#test-in-web-chat)

In the Test in Web Chat section it says:

5. Click the link of your Bot Channels Registration.
6. In the Bot Channels Registration panel, click Test in Web Chat. Alternatively, in the right panel, click the Test box.

No Bot Channels Registration link is visible. It should say:

5. Click on the Azure Bot resource name.
6. In the left navigation pane under Settings, click Test in Web Chat.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#option-2-new-app-service-plan)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Simplified these instructions to:
1. In your browser, navigate to the [Azure portal](https://ms.portal.azure.com).
1. Go to your bot resource.
1. Open the **Test in Web Chat** pane.
1. Interact with your deployed bot.

Fix is in https://github.com/MicrosoftDocs/bot-docs-pr/pull/2835
