### ISSUE TITLE
Step by Step guide

### ISSUE THREAD

**Issue by nelsonkthomas** [MicrosoftDocs/bot-docs#213]
Step by Step easy to follow guide is available at: http://blog.cloudadmin.me/2018/08/11/create-a-chat-bot-and-integrate-with-skype-for-business-using-azure-cognitive-services-qnamaker-luis-bot-framework/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9e2e6-b901-9e27-d070-701922396a4c
* Version Independent ID: c29a68b2-886d-2cec-0ce7-c49c586d7ea8
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/Microsoft/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
The link gives "account suspended" error.
