### ISSUE TITLE
"Create a bot" for Python in Windows gets cryptography error

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/bot-docs#2131]
## Repro:
On a clean Windows 10 machine without Python installed:

Install Python using python-3.8.3-webinstall.exe (That's the 32-bit version.)

Following the ["Create a Bot" document for Python](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=python%2Cvs) in Windows, execute:

python -m venv venv
venv\Scripts\activate.bat
pip install botbuilder-core

Then the error occurs:
"  ----------------------------------------
  ERROR: Failed cleaning build dir for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly"

## The Fix:
I suspect the real problem may lie in the botbuilder-core dependencies. Whatever the cause, to compensate for it...

In the document before the "pip install botbuilder-core" command, add the command "pip install cryptography==2.8", as in:

pip install cryptography==2.8
pip install botbuilder-core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c86f2-9c0d-015b-d44f-58914fed2deb
* Version Independent ID: 85fe7f0c-002a-e449-55cb-712d92874b19
* Content: [Create a bot with the Bot Framework SDK in C#, Java, JavaScript, or Python - Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=python%2Cvs)
* Content Source: [articles/bot-service-quickstart-create-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-quickstart-create-bot.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment]
Thanks for pointing this out @BruceHaley. I'll update the doc with your suggestion and let the Python devs know.

**Comment by emgrol** [comment]
@BruceHaley I spoke with the devs and they said 32 bit isn't standard; I added a note re: cryptography for those users.

**Comment by emgrol** [comment]
Closing now that the changes have been merged.
