### ISSUE TITLE
Typo in "Start your bot" section

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/bot-docs#2132]
Instruction 4 says:

4. Copy the last for [sic] digits in the address on the last line, usually 3978; you'll need these when you use the Emulator to interact with your bot.

You don't just need the four digits. You need the whole URL. Better to say:

4. Copy the http address in the last line. You will need it when you use the Emulator to interact with your bot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c86f2-9c0d-015b-d44f-58914fed2deb
* Version Independent ID: 85fe7f0c-002a-e449-55cb-712d92874b19
* Content: [Create a bot with the Bot Framework SDK in C#, Java, JavaScript, or Python - Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=python%2Cvs)
* Content Source: [articles/bot-service-quickstart-create-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-quickstart-create-bot.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Fix is in https://github.com/MicrosoftDocs/bot-docs-pr/pull/2835.
