### ISSUE TITLE
No information for storing app password in key vault. 

### ISSUE THREAD

**Issue by azumicro** [MicrosoftDocs/bot-docs#2134]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab6b752f-84b0-9ab2-15dd-fa590c9228c3
* Version Independent ID: b35b8505-2cf5-dbc7-4a22-db4cc110f537
* Content: [Azure Bot Service encryption for data at rest - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-encryption?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-encryption.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-encryption.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jameslew**

**Comment by JonathanFingold** [comment]
Does the [Configure the web app to connect to Key Vault](https://docs.microsoft.com/en-us/azure/key-vault/general/tutorial-net-create-vault-azure-web-app#configure-the-web-app-to-connect-to-key-vault) portion of the **Tutorial: Use a managed identity to connect Key Vault to an Azure web app in .NET** have the information you need? We can add a link to that information in our docs.
