### ISSUE TITLE
Sample code ContentType is set to image/png while the content URL is .jpg

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/bot-docs#2137]
[Enter feedback here]
It would be better if there was not an extension incompatibility in this example. png vs jpg.
ContentType is set to image/png while the content URL is .jpg

```
 "attachments": [
        {
            "contentType": "image/png",
            "contentUrl": "https://www.publicdomainpictures.net/pictures/30000/t2/duck-on-a-rock.jpg",
            "name": "duck-on-a-rock.jpg"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b3009c-7efa-e1bb-fa2d-516d134b3a96
* Version Independent ID: e91d90a7-8478-a1d3-2d0b-89cbdaff275c
* Content: [Add media attachments to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-media-attachments?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-add-media-attachments.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/rest-api/bot-framework-rest-connector-add-media-attachments.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
The correct article will be available in the next docs update,
