### ISSUE TITLE
Please delete and redirect this page

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/bot-docs#2138]
It shouldn't exist, Java samples have been merged into the main samples repository.

https://docs.microsoft.com/en-us/azure/bot-service/java/bot-builder-java-samples?view=azure-bot-service-4.0 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1565f1f6-f9d9-c27b-55f7-19cc8290cf29
* Version Independent ID: 20c6301e-07ff-568e-e87b-b18b9a328025
* Content: [Sample bots for Bot Framework SDK for Java - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/java/bot-builder-java-samples?view=azure-bot-service-4.0)
* Content Source: [articles/java/bot-builder-java-samples.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/java/bot-builder-java-samples.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@clearab -- look like the article was only partially retired. I'll retire it the rest of the way.

**Comment by JonathanFingold** [comment]
Should be good, once I have a chance to do a live sync today or tomorrow.
