### ISSUE TITLE
Add to document that Yeoman arguments are case-sensitive

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/bot-docs#2139]
Yeoman generator command line options fail if the wrong case is used. See Issue #3498: https://github.com/microsoft/BotBuilder-Samples/issues/3498

#### The fix:
Add another sentence to the statement: "The generator supports a number of command line options that can be used to change the generator's default options or to pre-seed a prompt."

Have it read: "The generator supports a number of command line options that can be used to change the generator's default options or to pre-seed a prompt. Options are case-sensitive."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c86f2-9c0d-015b-d44f-58914fed2deb
* Version Independent ID: 85fe7f0c-002a-e449-55cb-712d92874b19
* Content: [Create a bot with the Bot Framework SDK in C#, Java, JavaScript, or Python - Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=java%2Cvs)
* Content Source: [articles/bot-service-quickstart-create-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-quickstart-create-bot.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Fix is in https://github.com/MicrosoftDocs/bot-docs-pr/pull/2835
