### ISSUE TITLE
Fix broken links to examples

### ISSUE THREAD

**Issue by yochay** [MicrosoftDocs/bot-docs#214]
I found 2 articles referencing the older sample folder. 

- bot-builder-dialog-manage-conversation-flow.md, has a link that points to  (https://github.com/Microsoft/botbuilder-dotnet/tree/master/samples/MIcrosoft.Bot.Samples.Dialog.Prompts), not clear what sample should be instead

- v4sdk\bot-builder-howto-classic.md,  which has a link to https://github.com/Microsoft/botbuilder-dotnet/tree/master/samples/Microsoft.Bot.Samples.EchoBot-Classic.  

Need to update links and points to the right samples.

**Comment by Kaiqb** [comment]
@yochay - fixed.
