### ISSUE TITLE
Found Analytics deprecated on September 1, 2021. 

### ISSUE THREAD

**Issue by CharingJC** [MicrosoftDocs/bot-docs#2145]
[Enter feedback here]
From the portal there is an annoncement. 
''' This Analytics blade will be deprecated on September 1, 2021.'''
 Need Clarification on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6120c4f2-ec78-8909-5fd8-46ec6fc8f434
* Version Independent ID: c5f17144-c914-e77c-628b-7be593f0570c
* Content: [Bot analytics - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-manage-analytics.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-manage-analytics.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@CharingJC - following up with the devs; will let you know what I discover.

**Comment by JonathanFingold** [comment]
@CharingJC -- "Regarding analytics, the new Azure Bot does not have the old analytics blade...." Older resources are showing the analytics blade with a deprecation warning at the top.

The solution is to remove the old analytics resource and to follow the instructions to [Add telemetry to your bot](https://docs.microsoft.com/azure/bot-service/bot-builder-telemetry) and [Analyze your bot's telemetry data](https://docs.microsoft.com/azure/bot-service/bot-builder-telemetry-analytics-queries).

Hope this helps. Let me know if you have follow up questions.
