### ISSUE TITLE
Get Conversations API returns 405 (Method not allowed)

### ISSUE THREAD

**Issue by dgancho** [MicrosoftDocs/bot-docs#2146]
[Get Conversations API ](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#get-conversations) returns 405 (Method Not Allowed)
All other APIs with the same auth token seems to works as advertised.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36ddb50-9e44-96e3-2df3-174166efa75d
* Version Independent ID: 68ac4b64-6616-2216-3519-e0b33d3a53e4
* Content: [Bot Framework Connector service REST API reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* GitHub Login: @erhopf
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
See comments in issue #1759 and the alert at the end of the [Conversation operations](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#conversation-operations) table.
