### ISSUE TITLE
`messageUpdate`/`messageDelete` is not supported in Teams

### ISSUE THREAD

**Issue by shilcare** [MicrosoftDocs/bot-docs#2148]
[Enter feedback here]

`messageUpdate`/`messageDelete` events are not supported in Teams yet. The doc need to be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60950444-cdcc-f0b9-aa21-c99894e26b50
* Version Independent ID: 0bd14221-e030-f9d8-41e6-1a52c9a76440
* Content: [Channels reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#message-update)
* Content Source: [articles/bot-service-channels-reference.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channels-reference.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@shilcare -- Your bot can _send_ the `messageUpdate` and `messageDelete` _activities_ to Microsoft Teams, which should respect them. Your bot should not expect to receive these activities from Teams. The Teams docs ([Update and delete messages sent from your bot
](https://docs.microsoft.com/microsoftteams/platform/bots/how-to/update-and-delete-bot-messages)) describe the use of these activities on the Teams channel.

I hope that helps clarify.
