### ISSUE TITLE
Add necessary user permissions for Azure Bot creation

### ISSUE THREAD

**Issue by matt852** [MicrosoftDocs/bot-docs#2149]
Please add necessary permissions required for creating an Azure Bot, Resource Group, or other steps if they differ.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cf57ecf-7774-8f8b-1e47-cf628c3bfa25
* Version Independent ID: ba30559c-36df-69c6-2703-cd67aa1380c2
* Content: [Create an Azure Bot resource in the Azure portal - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/abs-quickstart?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/abs-quickstart.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/abs-quickstart.md)
* Service: **bot-service**
* GitHub Login: @mmiele
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@matt852 -- I'm in the process of updating this topic. I'll ask the product team and let you know what I find out.

**Comment by JonathanFingold** [comment]
@matt852 -- as long as you're signed in to the Azure tenant, you should be able to create all these resources without any additional permissions needed.
