### ISSUE TITLE
.NET version?

### ISSUE THREAD

**Issue by Rykimaruh** [MicrosoftDocs/bot-docs#215]
Is there a .NET version of the codes mentioned in this document? Not really familiar with node.js

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e9b932b-8f31-e07b-7ac3-9298047bccb1
* Version Independent ID: fbc204fc-4ab0-f370-043a-6bae9b4b7fd2
* Content: [Support localization - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-localization?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-localization.md](https://github.com/Microsoft/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-localization.md)
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
There isn't.

**Comment by t1agob** [comment]
Is it in the roadmap to create one?

**Comment by mauguzun** [comment]
maby same as  asp.net ?
