### ISSUE TITLE
[Doc bug] messageUpdate/messageDelete events are not received by bot

### ISSUE THREAD

**Issue by v-chetsh** [MicrosoftDocs/bot-docs#2151]
As per documentation, it says that messageUpdate/messageDelete events are supported for bot but events are not received by bot.
But in actual Teams doesn't support those events.

Reference doc section link:
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#message-update

Could you please help here to update the doc accordingly.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60950444-cdcc-f0b9-aa21-c99894e26b50
* Version Independent ID: 0bd14221-e030-f9d8-41e6-1a52c9a76440
* Content: [Channels reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#message-update)
* Content Source: [articles/bot-service-channels-reference.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channels-reference.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@v-chetsh -- Your bot can _send_ the `messageUpdate` and `messageDelete` _activities_ to Microsoft Teams, which should respect them. Your bot should not expect to receive these activities from Teams. The Teams [Update and delete messages sent from your bot](https://docs.microsoft.com/microsoftteams/platform/bots/how-to/update-and-delete-bot-messages) article describes the use of these activities on the Teams channel.

I hope that helps clarify.
