### ISSUE TITLE
The page seems outdated

### ISSUE THREAD

**Issue by zikalino** [MicrosoftDocs/bot-docs#2155]
Screenshots look very different from actual layout, so it wasn't very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e9b10d5-ca65-d08c-2f11-ba62d66b8f80
* Version Independent ID: 396d52c0-d864-afac-4d1c-fd6880a973a9
* Content: [Configure continuous deployment for Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-build-continuous-deployment.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-build-continuous-deployment.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@zikalino - Thanks for catching this. The Azure portal UI changes periodically, and we don't always notice in a timely fashion. We'll  let you know when we've updated this article.

**Comment by JonathanFingold** [comment]
@zikalino I fixed this a month or two ago and forgot to notify you. Sorry for the delay.
