### ISSUE TITLE
Missing step in Bot Framework / Direct Line App Service Extension / Configure Node.js bot for extension

### ISSUE THREAD

**Issue by thomasgauvin** [MicrosoftDocs/bot-docs#2156]
Application settings configuration (steps 7-11) should be done within the App Service resource, rather than Bot Service resource (which is what the preceding steps 1-6 seem to imply). This should be more clear.

![image](https://user-images.githubusercontent.com/35609369/143626974-1aa48dcb-fe1f-49be-b531-fb7c0f321100.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72c259-a864-9e1c-b585-562d6bca80ff
* Version Independent ID: 30a3fce8-d236-5c7b-88a0-003c971f2819
* Content: [Configure .NET bots for the Direct Line App Service extension in the Bot Framework SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by thomasgauvin** [comment]
Links to pages: 
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-node-bot?view=azure-bot-service-4.0
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-node-bot?view=azure-bot-service-4.0

**Comment by JonathanFingold** [comment]
@thomasgauvin - Thanks for catching this. I'm working on a fix now.

**Comment by JonathanFingold** [comment]
@thomasgauvin - The fix is live. Thanks much.
