### ISSUE TITLE
Possible typo in the last sentence of the second paragraph.

### ISSUE THREAD

**Issue by BulldogCTISolutions** [MicrosoftDocs/bot-docs#2157]
Search for 'langue'.  The sentence structure reads like 'language' should be used.  Although pretty hard core if 'langue' was actually meant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c96c66c-0821-89c7-7e3f-4becc0e14940
* Version Independent ID: 6d0c2ff4-66e0-419a-0e87-e947b9822426
* Content: [.lu file format - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lu-file-format?view=azure-bot-service-4.0)
* Content Source: [articles/file-format/bot-builder-lu-file-format.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/file-format/bot-builder-lu-file-format.md)
* Service: **bot-service**
* GitHub Login: @emgrol
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Thanks for catching this. I'll fix this today.

**Comment by JonathanFingold** [comment]
Found additional typos and issue in the article that are now fixed.

**Comment by JonathanFingold** [comment]
Changes should be visible in about 4 hours or so.
