### ISSUE TITLE
Issue with Authentication and Bot Channels Registration

### ISSUE THREAD

**Issue by jcbartle** [MicrosoftDocs/bot-docs#2158]
Just wanted to state (in case someone else is running into this) that I was not able to get authentication working in Teams using an existing bot created using the old Bot Channels Registration Azure resource.

The behavior I was seeing was that the OAuthPrompt card would trigger and the sign in button would appear, but clicking on the sign in button did nothing. No matter what I did, I was not able to get the sign in / consent page to pop.

I created a new Multi Tenant bot using the new Azure Bot resource type. Everything works perfectly now. So I guess I'm saying that, if you need authentication within your bot, take the time to switch from the Bot Channels Registration to the Azure Bot resource type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to a bot in Bot Framework SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@jcbartle - thanks for reporting. I'm trying to track down an answer. Will let you know when I have more information.

**Comment by jcbartle** [comment]
Morning, @JonathanFingold. I won't be able to test this going forward, as I'm converting all of my bots to the new Azure Bot resource. This was more for anyone else who is running into this issue. If Microsoft can confirm / deny and update documentation as needed, that would be greatly appreciated.

**Comment by stevkan** [comment]
@jcbartle, thank you for bringing this to our attention. I'll look closer at the docs and sample and see what can needs to be updated.

**Comment by anishprasad01** [comment]
Aspects of Azure that bots rely on, such as the Bot resource, app services, app registrations, and auth support keep getting updated, and there is no guarantee that new configurations of these features will work with deprecated resources. The note in the documentation specify that "existing resources" will continue to work, but we'll see about rephrasing this to clarify that we mean resources that have already been configured and deployed prior to deprecation.

**Comment by JonathanFingold** [comment]
Fix should be live by tomorrow.
