### ISSUE TITLE
Handling attachments sample not working

### ISSUE THREAD

**Issue by vhmoura** [MicrosoftDocs/bot-docs#2159]
[Enter feedback here]
Hi, the handling attachments link doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 607856cb-baae-c401-5b34-876b5018771d
* Version Independent ID: 77df1de7-7b2e-a546-1280-a66121039a94
* Content: [Send media attachments with the Bot Framework SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-add-media-attachments.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-howto-add-media-attachments.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
There's an extra "-js" at the end of the link URL. Remove that and it resolves correctly. Fixing presently.

**Comment by JonathanFingold** [comment]
Fix should be live tomorrow. Thanks for reporting this.
