### ISSUE TITLE
Improper capitalization of GitHub

### ISSUE THREAD

**Issue by antn** [MicrosoftDocs/bot-docs#2160]
👋 Hi there! I noticed that GitHub is written as `Github` on this page, and the screenshot also shows that incorrect capitalization:

<img width="613" alt="Screen Shot 2021-12-07 at 11 35 09 PM" src="https://user-images.githubusercontent.com/858504/145167619-436ff882-fa68-4262-8150-182d328841c6.png">

GitHub should always be written with a capital H, never lowercase. It appears that the actual button in Azure has since been updated, but the docs are outdated:

<img width="303" alt="Screen Shot 2021-12-07 at 11 31 52 PM" src="https://user-images.githubusercontent.com/858504/145167706-c8ca164c-e377-43a2-a49a-8869ba5bb819.png">

I was going to submit a pull request to fix this, but it looks like all of the content was removed from this repo in https://github.com/MicrosoftDocs/bot-docs/pull/2150. Are these docs no longer open source? 💭 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c93f5e57-c662-644a-776d-b1dd112a3832
* Version Independent ID: f7bfec78-1f6b-fcb5-09da-138e27dcad58
* Content: [Register a Bot Framework SDK bot with Azure - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=userassigned)
* Content Source: [articles/bot-service-quickstart-registration.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-quickstart-registration.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@antn Thanks for catching this, we'll update the article soon.

As to your other question, we're no longer accepting PRs in the public repo. The [docs.microsoft.com - Terms of use](https://docs.microsoft.com/legal/termsofuse) still apply.

**Comment by JonathanFingold** [comment]
@antn The fix is in and should be visible in the live docs later today.
