### ISSUE TITLE
What is the _actual_ limit to Card Actions in Teams?

### ISSUE THREAD

**Issue by q00u** [MicrosoftDocs/bot-docs#2161]
In the "Action support by channel" section, Teams is listed as not having support for Suggested Actions, and limiting Card Actions to three.

But I just made a card with 5 actions, and it appeared in teams and functions with no problems.

So what is the *actual* limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60950444-cdcc-f0b9-aa21-c99894e26b50
* Version Independent ID: 0bd14221-e030-f9d8-41e6-1a52c9a76440
* Content: [Channels reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channels-reference.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channels-reference.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
I found the information:
> Effectively now there's no limit to the number of Card Actions supported. Each card in both Channels and Chats can support up to 6 primary actions. With the addition of Overflow menus, the 7th and subsequent primary actions will be hidden away in the overflow menu as well as any secondary actions.

I'll update the channel reference. (I've also asked the Teams group to update their docs.)

**Comment by JonathanFingold** [comment]
I updated the **Action support by channel** table in the article for Teams. The fix should be live by tomorrow.
