### ISSUE TITLE
Clarifying Slack adapter Oauth token functionality

### ISSUE THREAD

**Issue by Bolleman** [MicrosoftDocs/bot-docs#2162]
In working with the Slack connector I've noticed a couple things that others could likely benefit from knowing as follows:

1) Bot service connector vs. Bot builder adapter.   A key difference is that since the Slack adapter is tied to a specific OAuth token, OOB it can only be used with a Slack workspace that the developer has access to, so publishing an app to the Slack app directory would require using the bot service connector.   Also might be worth clarifying that the SlackBotToken in the [Slack adapter settings](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0#add-slack-app-settings-to-your-bots-configuration-file) is the Slack Bot User OAuth Access Token and not the Slack App Client Secret.

2) The bot service connector only supports the [legacy Slack message button format](https://api.slack.com/legacy/message-buttons), not the current [Block Kit button elements](https://api.slack.com/reference/block-kit/block-elements#button).  More details are this are in an issue I raised on the BotFramework-Services repo [here](https://github.com/microsoft/BotFramework-Services/issues/326).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack with the Bot Framework SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
The Connect to Slack article has been updated to point users to the Community repo if they want instructions on how to use the Slack adapter.
