### ISSUE TITLE
Broken Link to TeamsTenantFilteringMiddleware Class Code

### ISSUE THREAD

**Issue by jcbartle** [MicrosoftDocs/bot-docs#2163]
Hello.

On this page, the link to the C# TeamsTenantFilteringMiddleware class (https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Teams/Roster) is broken. Searching GitHub, it appears that Microsoft may have purged this code? Is this no longer the recommended solution to limiting the tenant IDs which can access your bot?

Thanks,
J.C.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aa75583-93e6-cbcd-ab51-c6ec1bf85a58
* Version Independent ID: c33566c0-c48a-7d1a-d808-f7e3cee3d9dc
* Content: [Bot Framework Security and Privacy Frequently Asked Questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-faq-security?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-resources-faq-security.yml](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-resources-faq-security.yml)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@jcbartle - yes the test was moved from the SDK repo to the Samples repo, and then later removed entirely. :\ I'll review the FAQ and update that entry.

Here's the [last version of the middleware](https://github.com/microsoft/BotBuilder-Samples/blob/c20ee2158ada698c53025ed83038134c5e7a9d84/experimental/teams/csharp-dotnetcore/Microsoft.Bot.Builder.Teams/Middlewares/TeamsTenantFilteringMiddleware.cs) I could find.

**Comment by JonathanFingold** [comment]
PS. The Teams docs describe the channel data that Teams includes in activities it sends to bots: [Messages in bot conversation](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet)

**Comment by jcbartle** [comment]
@JonathanFingold - thank you for the quick response! I'll be able to implement my own logic to handle this based on that middleware example. Would be great if the Azure Bot Channels section had a way of limiting tenant IDs from the Azure infrastructure. The code-level control works, but being able to block the traffic further upstream would help some folks sleep at night : )

**Comment by JonathanFingold** [comment]
Glad I could help. I'll forward your suggestion to the Azure folks.
