### ISSUE TITLE
Expire conversation in Composer Bot Framework

### ISSUE THREAD

**Issue by jcmorara** [MicrosoftDocs/bot-docs#2164]
Is there a way to do something similar but Composer Bot Framework?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3157dd4-9d49-ef32-52d2-bc4e4e48943a
* Version Independent ID: 4ebe828a-8bfe-e5a7-f82d-1d01e02a7945
* Content: [Expire a conversation - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-expire-conversation?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-expire-conversation.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-howto-expire-conversation.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
For Composer, it looks like you would need to either customize the "bot runtime" behind the scenes, as a one-off for each bot, or create a template package that has your custom runtime as a base. Unfortunately, the package creation docs are pretty thin right now. :(
