### ISSUE TITLE
Issue with Token Exchange URL in Teams

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/bot-docs#2165]
If we keep value in "Token Exchange URL", OAuth prompt is not showing in teams bot. Bot is not showing any error and OAuth card is not posting. If the note is added in documentation to leave "Token Exchange URL" blank, it would help for developers.

Same issue reported here: https://github.com/microsoft/botbuilder-dotnet/issues/4927#issuecomment-726404570 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb435f0d-6418-4868-9e50-e73348f5fabc
* Version Independent ID: ba585475-9607-26a7-f14f-56b71cdb5596
* Content: [Identity providers in Bot Framework SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-identity-providers?view=azure-bot-service-4.0&tabs=adv1%2Cga2)
* Content Source: [articles/v4sdk/bot-builder-concept-identity-providers.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-concept-identity-providers.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
There is a note in the article to that effect, but it is confusingly worded. I'll update the table and note to make the step clearer.

**Comment by JonathanFingold** [comment]
The article updates are finally checked in and will be live later today.
