### ISSUE TITLE
Corrections Needed.

### ISSUE THREAD

**Issue by abhi23arora** [MicrosoftDocs/bot-docs#2166]
Hi

There are a few corrections needed on the code meant to be updated in azure function.

1. Instead of
public static async Task Run(string **queueItem**, ILogger log) -> Function apps now take the parameter as myQueueItem

This was causing compile time issue.

2. CompareOptions ->  Have to be replaced by StringComparison at lines
    if(originalActivity.Value.ToString().Equals("option 1", CompareOptions.OrdinalIgnoreCase))
    {
        originalActivity.Value = " (Result for long operation one!)";
    }
    else if(originalActivity.Value.ToString().Equals("option 2", CompareOptions.OrdinalIgnoreCase))
    {

This was also causing compile time issue.

Thanks
Abhimanyu Arora

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afce7fb8-6f98-48ae-ac02-0d13f32a5d43
* Version Independent ID: b2cccd25-c541-4286-3feb-1f2653e8cdea
* Content: [Manage a long-running operation using the Bot Framework SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-howto-long-operations-guidance.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-howto-long-operations-guidance.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@abhi23arora PR 2968 should fix your second issue, and changes should be live by tomorrow. If the parameter name generates an error, please reopen this issue and include the error text.
