### ISSUE TITLE
Missing Python tutorial + incomplete sample.

### ISSUE THREAD

**Issue by ivopisarovic** [MicrosoftDocs/bot-docs#2167]
A python version of this document would be awesome! I have spent a few days figuring out how to configure everything. Something is in the example (https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/python/21.corebot-app-insights/app.py) but for the initialization of the TelemetryMiddleware is completely missing in the example!

```
INSTRUMENTATION_KEY = CONFIG.APPINSIGHTS_INSTRUMENTATION_KEY
TELEMETRY_CLIENT = ApplicationInsightsTelemetryClient(
    INSTRUMENTATION_KEY, telemetry_processor=AiohttpTelemetryProcessor(), client_queue_size=1
) if INSTRUMENTATION_KEY else None
TELEMETRY_LOGGER_MIDDLEWARE = TelemetryLoggerMiddleware(TELEMETRY_CLIENT, True) # this is the key missing part to log sent and received messages!
ADAPTER.use(TELEMETRY_LOGGER_MIDDLEWARE) # this is the key missing part to log sent and received messages!
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bd316bd-4f82-195f-6530-38474ce69cef
* Version Independent ID: 78f7afc4-8d6d-b98f-cd6e-cee82b9425e2
* Content: [Add telemetry to your bot in Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-telemetry.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-telemetry.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@ivopisarovic -- Looking into it. As long as the Python sample and implementation is similar enough to the C# and JavaScript ones, I should be able to add the Python bits. Otherwise, we may need to open a samples or Python SDK issue about lack of parity.

**Comment by ivopisarovic** [comment]
Thanks! If you need any help, let me know. I have already a working setup and can provide sample code.

**Comment by JonathanFingold** [comment]
@ivopisarovic Sorry to have dropped this. There is not sufficient parity. Would you be willing to open an [issue in the Samples repo](https://github.com/microsoft/BotBuilder-Samples/issues) with the information you have?

**Comment by ivopisarovic** [comment]
@JonathanFingold sure, done :) https://github.com/microsoft/BotBuilder-Samples/issues/3706

**Comment by JonathanFingold** [comment]
Thanks @ivopisarovic . Once the sample's updated, I'll work on updating the article.
