### ISSUE TITLE
Production embedding option

### ISSUE THREAD

**Issue by PiriyaD** [MicrosoftDocs/bot-docs#2169]
I like this document especially for the Dev part. However, could you please have more detail on the Production embedded option? I would like to know how to do it step by step if possible.
Thank you so much in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d54408c-bfbc-9d2c-a642-ec54f375475f
* Version Independent ID: 5b06e016-1aa8-a13b-179c-ec6700b8287c
* Content: [Connect a bot to Web Chat in the Bot Framework SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0#development-embedding-options)
* Content Source: [articles/bot-service-channel-connect-webchat.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-connect-webchat.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
The samples in the Web Chat repo might help. There's a [Direct Line token](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/01.getting-started/k.direct-line-token) sample.
