### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by chamikasandamal** [MicrosoftDocs/bot-docs#2172]
If you are using the **Bot Framework SDK** for .NET or the Bot Framework SDK for Node.js, you do not need to implement the security procedures described in this article, because the SDK automatically does it for you

above section is pointing to invalid url. 
https://docs.microsoft.com/en-us/previous-versions/azure/bot-service/dotnet/bot-builder-dotnet-overview?view=azure-bot-service-3.0&viewFallbackFrom=azure-bot-service-4.0

it should be navigate to https://docs.microsoft.com/en-us/azure/bot-service/index-bf-sdk?view=azure-bot-service-4.0
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58bf70a-3263-93a1-5bc2-085431a7aa6b
* Version Independent ID: c5e3de2f-58ad-1c6a-e0f3-93489d013114
* Content: [Authenticate requests with the Bot Connector API - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-authentication.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/rest-api/bot-framework-rest-connector-authentication.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Sorry for the delay. Investigating.

**Comment by JonathanFingold** [comment]
Fix should be live by tomorrow. Thanks for pointing it out.

**Comment by chamikasandamal** [comment]
Changes reflected :)
