### ISSUE TITLE
If typing indicator is support by facebook channel?

### ISSUE THREAD

**Issue by CharingJC** [MicrosoftDocs/bot-docs#2175]
[Enter feedback here]
Statements are different from Uncategorized table and Summary table all activities to all channels table.
Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60950444-cdcc-f0b9-aa21-c99894e26b50
* Version Independent ID: 0bd14221-e030-f9d8-41e6-1a52c9a76440
* Content: [Channels reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channels-reference.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channels-reference.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by CharingJC** [comment]
Dear team, is there any update?

**Comment by JonathanFingold** [comment]
@CharingJC -sorry for the delay. I'll ask the folks that should know and get back to you.

**Comment by CharingJC** [comment]
Thank you for the feedback @JonathanFingold

**Comment by JonathanFingold** [comment]
Facebook does support the typing indicator, and I'll update the article to be clear on that.

A couple things to keep in mind:
- Most channels require a response within 15 seconds.
- If your bot needs more time, you can use a _proactive message_ to send a response when the bot is finally ready. See how to [Send proactive notifications to users](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-proactive-message) and how to [Manage a long-running operation](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-long-operations-guidance).

**Comment by JonathanFingold** [comment]
Fix to the table should be live by tomorrow.
