### ISSUE TITLE
BOT TELEGRAM

### ISSUE THREAD

**Issue by raju2123** [MicrosoftDocs/bot-docs#2176]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 260c283c-f5e9-e00d-19ec-ee9df18335e5
* Version Independent ID: d1525408-36d3-6575-2331-a16379744a59
* Content: [Connect a Bot Framework bot to Telegram - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-telegram?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-telegram.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-connect-telegram.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@raju2123 - What is the issue you found in this article?
