### ISSUE TITLE
Variable Name Error

### ISSUE THREAD

**Issue by alangak** [MicrosoftDocs/bot-docs#2177]
Hello Team,

Possibly there is a variable name mismatch. As I could see declared name is "ExpireAfterSeconds" and assigned with value to "TimeoutSeconds"

![image](https://user-images.githubusercontent.com/33109030/151132530-3593c45f-9723-4e46-b5bd-7c1cf4824ff1.png)

Thanks,
Alanga

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3157dd4-9d49-ef32-52d2-bc4e4e48943a
* Version Independent ID: 4ebe828a-8bfe-e5a7-f82d-1d01e02a7945
* Content: [Expire a conversation - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-expire-conversation?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-expire-conversation.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-howto-expire-conversation.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Thanks. Fix should be live tomorrow.
