### ISSUE TITLE
couldn't send

### ISSUE THREAD

**Issue by ElyoenaiMR** [MicrosoftDocs/bot-docs#218]
When i try to test the bot in the Web chat and type "Hi" i only get "couldn't send" and a link "retry", but nothing happens

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your bot to Azure - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/Microsoft/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ElyoenaiMR** [comment]
I was missing to add /api/messages in the URL , that was the problem

**Comment by nikhilligade123** [comment]
Tried to test my bot in "Test in web chat" but it's giving a reply with "My Bot code is having an issue". However the code is working fine on local environment.
