### ISSUE TITLE
botId description is incorrect

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/bot-docs#2180]
The document incorrectly lists: <html>
<body>

botId | The name of the Azure Bot resource your created earlier.
-- | --

</body>
</html>

The document should instead say:<html>
<body>

botId | The name of the new Azure Bot resource to create.
-- | --

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp%2Cuserassigned)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Will fix this as part of work on #2179 .
