### ISSUE TITLE
(Minor Issue) - Spell mistake in 'What is a bot?' section

### ISSUE THREAD

**Issue by asaflevi72** [MicrosoftDocs/bot-docs#2182]
[Enter feedback here]
'through' misspelled - A user connects to a bot 'though' a

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6838575c-d2fc-65e3-98c2-0b35992c10b2
* Version Independent ID: 2b5dc3fc-49c0-7cd2-e6e1-4ced8da6c5f9
* Content: [What is the Bot Framework SDK? - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview?view=azure-bot-service-4.0#what-is-a-bot)
* Content Source: [articles/bot-service-overview.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-overview.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Fix should be live later today.
