### ISSUE TITLE
Update Debugging via Ngrok page for tenancy

### ISSUE THREAD

**Issue by anishprasad01** [MicrosoftDocs/bot-docs#2183]
Testing a bot locally via Ngrok is only supported for multi-tenant bots, and I'm seeing people come in with issues trying to test single-tenant and user-assigned managed identity bots with Ngrok since they don't know it's unsupported. A note or bullet point of some kind explaining this would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb2e2b4-8b91-ac29-b786-bf8418dd358b
* Version Independent ID: 13abc144-e6eb-eea7-3645-68331bf4537e
* Content: [Debug a channel using ngrok - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-debug-channel-ngrok.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-debug-channel-ngrok.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Fix should be live later today.
