### ISSUE TITLE
doc update: `dotnet new corebot -n TestBot` command expects to create project at TestBot/CoreBot

### ISSUE THREAD

**Issue by ramfattah** [MicrosoftDocs/bot-docs#2184]
Hello, 

I'm opening this issue regarding this documentation https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=csharp%2Ccli

When creating a new bot in [this step](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=csharp%2Ccli#:~:text=Create%20a%20new%20echo%20bot%20project%20using%20the%20following%20command.%20Replace%20%3Cyour%2Dbot%2Dname%3E%20with%20the%20name%20to%20use%20for%20your%20bot%20project.), it could use a little more clarification on running `dotnet new corebot -n TestBot` that only the parent directory receives the bot name. i.e. at directory `TestBot/CoreBot`

### Possible solution: 

Perhaps [step 3](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=csharp%2Ccli#:~:text=Create%20a%20new%20echo%20bot%20project%20using%20the%20following%20command.%20Replace%20%3Cyour%2Dbot%2Dname%3E%20with%20the%20name%20to%20use%20for%20your%20bot%20project.) could be updated to this:

3. Create a new echo bot project using the following command. Replace <your-bot-name> with the name to use for your bot project. (For a core bot project, only the parent folder receives the bot name.)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c86f2-9c0d-015b-d44f-58914fed2deb
* Version Independent ID: 85fe7f0c-002a-e449-55cb-712d92874b19
* Content: [Create a bot with the Bot Framework SDK in C#, Java, JavaScript, or Python - Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=csharp%2Ccli)
* Content Source: [articles/bot-service-quickstart-create-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-quickstart-create-bot.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Fix should be live later today.
