### ISSUE TITLE
Please add user-assigned managed identity for Python SDK 🙏🏻

### ISSUE THREAD

**Issue by denissa4** [MicrosoftDocs/bot-docs#2185]
Do you have any plans to add a user-assigned managed identity for Python SDK?

I believe Python becomes the most used SDK and this is a good idea to add user-assigned managed identity for Python SDK as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp%2Cuserassigned)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
The Python SDK does not currently support user-assigned managed identity bots.

Please create this as a feature request issue in the https://github.com/microsoft/botframework-sdk/issues repo.
