### ISSUE TITLE
Page should mention deployment of LUIS app to production slot

### ISSUE THREAD

**Issue by thomasgauvin** [MicrosoftDocs/bot-docs#2186]
This page should mention that the LUIS app should be published, specifically in the production slot: https://stackoverflow.com/questions/63117893/luis-and-botframework-not-working-response-status-code-does-not-indicate-succes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Add natural language understanding to your bot in Bot Framework SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Thanks for the feedback. The update should be live later today.
