### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by axelekenberg** [MicrosoftDocs/bot-docs#2187]
Im trying to connect my bot composer to slack and im trying to use the sample slack adapter but when you open the link for the git repo it turns out to be "Page not found". pls look it up:)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack with the Bot Framework SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@axelekenberg
- We have an update for this process in the works which should be out soon. However, this article is for an SDK-first bot, as opposed to a Composer bot.
- For Composer bots, you should use the Bot.Builder.Communinty.Adapters.Slack package and follow [their documentation](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/master/libraries/Bot.Builder.Community.Adapters.Slack#readme).
