### ISSUE TITLE
Fix links and move Adaptive Tools to Composer docs

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/bot-docs#2188]
This page points at resources that (as far as I can tell) do not exist.
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-adaptive-tools?view=azure-bot-service-4.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8117ef4-d878-652f-8fc0-b60000fea3f1
* Version Independent ID: 396ae831-70df-a000-6a29-f560e096dcdb
* Content: [Debug bots using Bot Framework Adaptive Tools - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-adaptive-tools?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-debug-adaptive-tools.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-debug-adaptive-tools.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@clearab - Given that the extension is available still for VS Code, I'm inclined to fix the one broken link, have the applicable content migrate to the Composer docs, and then retire this article with a redirect to the Composer docs.

**Comment by JonathanFingold** [comment]
- [x] Fix links. (PR 2971)
- [ ] Port content to Composer.
- [ ] Retire SDK doc.

**Comment by JonathanFingold** [comment]
Plans change. Will close this issue as resolved and address refactoring of articles later.
