### ISSUE TITLE
Azure Bot FAQ - new section for backup considerations and procedures

### ISSUE THREAD

**Issue by bgfast** [MicrosoftDocs/bot-docs#2189]
[Enter feedback here]
Hello-

It would be helpful to see the topic of backup covered in the FAQ. These are some areas to consider when looking at the bot:
	Project teams should review the Bot architecture and determine the backup approach for each component. 
	What is the importance and process for the following systems:
		○ Source code
		○ Application Logging
		○ Usage metrics
		○ Log analytics
		○ Bot click tracking
		○ Storage repositories
		○ Cognitive services - for example: Knowledgebase - Download - REST API (Azure Cognitive Services - QnA Maker) | Microsoft Docs
		○ Deployment process
		○ CI/CD pipelines

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253d4e99-7fc5-cc8d-5b07-29bf2d78687a
* Version Independent ID: cdc0528d-cf1a-e015-1d8a-31ed062648f8
* Content: [Bot Framework Frequently Asked Questions Index - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-resources-bot-framework-faq.yml](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-resources-bot-framework-faq.yml)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by clearab** [comment]
Thanks for the feedback! However, as your bot is, at the end of the day, just a web application we feel it would be outside the scope of this documentation to talk about things like source control processes and devops pipelines - we don't have an opinion on what technologies you use to perform those actions so it is difficult to provide any guidance beyond vague generalities.

Each potential combination of technologies involved is going to be specific to each implementation - for example if you're deploying your web app to Azure, this article would be very useful https://docs.microsoft.com/en-us/azure/app-service/manage-backup, however not at all useful if you're deploying to some other configuration.
