### ISSUE TITLE
Azure Health Bot Omission

### ISSUE THREAD

**Issue by gjlisiak** [MicrosoftDocs/bot-docs#2191]
Just wondering if there is any reason why the Azure Health Bot is not referenced in the section "Choose the right chatbot solution for your use case"?
 
https://docs.microsoft.com/en-us/azure/bot-service/bot-overview?view=azure-bot-service-4.0
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49545c0d-aa2e-4336-731c-8f8dc9aeee12
* Version Independent ID: a3de46d4-9ab3-4403-94c3-3c5704f73a2c
* Content: [Choose the right chatbot solution for your use case - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-overview?view=azure-bot-service-4.0)
* Content Source: [articles/bot-overview.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-overview.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Thanks for the question. For health care scenarios, use Health Bot. I'll work on updating the article.
