### ISSUE TITLE
Steps for injecting Application Insights into Language - Custom Question and Answering wanted to be summarized.

### ISSUE THREAD

**Issue by yutaro113** [MicrosoftDocs/bot-docs#2193]
Hi team, 
Steps for injecting AI into Bot with Language - Custom Question and Answering (which is successor of QnA Maker) is same as this page?
When I try this step on the Bot with Language, code didn't work at below step.
I guess generated code between bot with QnA Maker and Language is different.

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-qnamaker?view=azure-bot-service-4.0#enable-default-qna-logging

![image](https://user-images.githubusercontent.com/36602021/163698532-18734af7-f5b6-4107-9521-297aa274461d.png)

Error shows
CS0246 : https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0246
CS0103 : https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0103

Before this step, I did no customization from its original code generated in Azure Bot Service.

If so, right steps for Language also wanted to be summarized as QnA Maker will be deprecated and Language is now recommended to use. Or if code is same but doc missing some step, wanted this page to be corrected and also the fact this page's step can also be applied to Bot with Language.

Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fc218c5-0049-2279-c85e-8d0285b386f6
* Version Independent ID: d61e8b62-9ff0-32b2-8510-2ccf35a20d31
* Content: [Add telemetry features to your Bot Framework QnA bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-qnamaker?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-telemetry-qnamaker.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-telemetry-qnamaker.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@yutaro113 - unfortunately, the Bot Framework does not have built in support for the new Azure Cognitive Service for Language. You can design your bot to access the service using HTTP requests to the new service and interpreting the responses. You would need to generate your own telemetry.

**Comment by yutaro113** [comment]
@JonathanFingold , thank you very much for the confirmation!
