### ISSUE TITLE
CI/CD Deployment Center instructions do not match what I see - can't complete

### ISSUE THREAD

**Issue by mattgillam** [MicrosoftDocs/bot-docs#2194]
Hello

re https://docs.microsoft.com/en-gb/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=userassigned%2Cnewgroup%2Ccsharp

Having authorised Azure to GitHub I am attempting to Step 2. "After authorizing the AzureAppService, go back to Deployment Center in the Azure portal.
Select Continue."

The screen I see is the following, it does not match the screenshot showing steps 1 to 4.

I fill in the screen I see as I believe is correct (items are valid) but the "Settings" header shows an * (presumably something is missing?) and the 'Save' link does not respond. I'm unable to continue with the CI/CD set up so can't develop my bot.

I also don't see a match for these instructions ->

"On the Build provider page, select the build provider you want to use and select Continue.
On the Configure page, enter the required information and select Continue. The information required will depend on which source control service and build provider you chose.
On the Summary page, review the settings and then select Finish.
"

Please advise, thank you.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/379568/164273622-def4a93f-b44d-4274-9bd0-75291ec06d4d.png">

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/379568/164274409-4c404820-1d3b-4aa9-aece-c0562adbabe9.png">

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e9b10d5-ca65-d08c-2f11-ba62d66b8f80
* Version Independent ID: 396d52c0-d864-afac-4d1c-fd6880a973a9
* Content: [Configure continuous deployment for Bot Service - Bot Service](https://docs.microsoft.com/en-gb/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-build-continuous-deployment.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-build-continuous-deployment.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by mattgillam** [comment]
also worth mentioning: the instructions don't tell the user to create a GutHub repo for the bot prior to CI/CD setup attempt.

**Comment by mattgillam** [comment]
Update: I found some instructions here that are a better match: https://docs.microsoft.com/en-gb/azure/app-service/deploy-continuous-deployment?tabs=github

I did this change: 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/379568/164285086-90ac7582-0230-4509-84ea-19f00a9723a1.png">

Not fully tested but it seemed to work.

**Comment by JonathanFingold** [comment]
Thanks for bringing this up. Investigating.

**Comment by JonathanFingold** [comment]
I've updated and tested the instructions. Changes should be live by end of day.

**Comment by mattgillam** [comment]
Thanks.
