### ISSUE TITLE
What is a Bot Id? How is it used? 

### ISSUE THREAD

**Issue by BillStrait** [MicrosoftDocs/bot-docs#2198]
During the process of creating an ARM template for the bot, we are told to populate the "Bot Id" property with the "The ID of the Azure Bot resource to create. The bot ID is immutable."

To me, this sounds like you're asking for a GUID. Taking some educated guesses about what I'm creating, I think this is the name of the resource ("MyBotsUniqueName"). Some clarification in the documentation would be helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Publish your bot to Azure - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=userassigned%2Cexistinggroup%2Ccsharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
The `botId` parameter is used as the _bot handle_ for the Azure Bot resource in Azure.
- The name of the associated Web App, unless otherwise specified, is also set to the botId.
- The bot handle is immutable, but you can change the Web App later.

I'll see if I can make the description a bit clearer.

**Comment by JonathanFingold** [comment]
@BillStrait The process has since been divided into two separate steps, one for the app service and one for the Azure Bot resource. Let me know if the description of the newer `azureBotId` parameter needs more clarification.

**Comment by BillStrait** [comment]
Thanks for the update. I checked the page linked in the original issue and ctrl+f'd for BotId, 
![image](https://user-images.githubusercontent.com/1637449/183707019-8d021354-b034-422e-9978-6b36467d727d.png)

The content source page 404's also. So... I guess it's been made so clear that I can't see it anymore. 😆 I'm not anticipating creating a new Bot Framework bot in the foreseeable future. I'll differ to your judgment on closing this.

**Comment by BillStrait** [comment]
![image](https://user-images.githubusercontent.com/1637449/183708866-3000680b-31d1-4da6-912d-c963e38a4cd8.png)

I suggest changing 
"Required. The globally unique and immutable bot ID." 
to something like
"Required. The globally unique and immutable handle for the bot, such as 'Cortana'"

**Comment by JonathanFingold** [comment]
Fix merged. Should be visible later today.
