### ISSUE TITLE
Why are there no Node.Js examples?

### ISSUE THREAD

**Issue by jjgriff93** [MicrosoftDocs/bot-docs#220]
The documentation for authentication is very disparate at the moment and there are no node.js examples for the above - please add some. Users can get very confused with the different routes they can take here (BotAuth etc.) so please have this documented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d80e0b-f1b7-175b-128d-0fb12f17ae36
* Version Independent ID: 1ed9006a-bf0b-9aaa-d180-9d2cb0c09524
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0)
* Content Source: [articles/bot-builder-tutorial-authentication.md](https://github.com/Microsoft/bot-docs/blob/live/articles/bot-builder-tutorial-authentication.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **JonathanFingold**

**Comment by jonathanhotono** [comment]
@Kaiqb we definitely need something better than this.. sample to authenticate to Azure AD, and how to handle the token expiration etc to minimize the amount of time user have to click the login button.

**Comment by Kaiqb** [comment]
@jonathanhotono - with the release of SDK v4, I'm not sure if we will have additional samples in V3. Adding @Jeffders to comment.

**Comment by Kaiqb** [comment]
@jonathanhotono - yes, SDK v4 was released last month. We recommend using it for bot development.
