### ISSUE TITLE
The account linking as a part of the conversation does not send an account linking card

### ISSUE THREAD

**Issue by aishwaryaumachandran** [MicrosoftDocs/bot-docs#2200]
I'm using the 4.14 version and the OAuth does not send an account linking card. Does it need a specific version that is missing? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c24dc268-76db-f9d6-472f-4859a005792c
* Version Independent ID: 8279092d-0e86-c15b-89cb-8759eb25450d
* Content: [Connect a bot to Alexa - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-alexa?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-alexa.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-connect-alexa.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by anishprasad01** [comment]
Hi @aishwaryaumachandran,

As per the [linked documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-alexa?view=azure-bot-service-4.0#user-authentication-in-alexa), the Alexa link card can be generated and sent in different ways depending on how you as the developer want to do it.

In order for us to investigate further, we need you to provide us with code samples and reproduction steps describing how you have implemented this.

**Comment by aishwaryaumachandran** [comment]
The steps to reproduce are: 

1. Set up the alexa channel as per the documentation with the account linking on Azure AD. 
2.  [I used the following sample to test as our project is also configured on Bot Builder 4.14.1 ](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/82.skills-sso-cloudadapter)
3.  Replace the RootBot.cs with the following code below 
4. Ideally the attachment is supposed to convert the signin card to the LinkAccount Card, but it does not respond.

Let me know if you have any other questions?

`// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Schema;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.BotBuilderSamples.RootBot.Bots
{
    public class RootBot<T> : ActivityHandler
        where T : Dialog
    {
        private readonly ConversationState _conversationState;
        private readonly Dialog _mainDialog;

        public RootBot(ConversationState conversationState, T dialog)
        {
            _conversationState = conversationState ?? throw new ArgumentNullException(nameof(conversationState));
            _mainDialog = dialog ?? throw new ArgumentNullException(nameof(dialog));
        }

        public override async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default)
        {
            if (turnContext.Activity.Type != ActivityTypes.ConversationUpdate)
            {
                // Run the Dialog with the Activity.
                await _mainDialog.RunAsync(turnContext, _conversationState.CreateProperty<DialogState>("DialogState"), cancellationToken);
            }
            else
            {
                var dataToken = JObject.Parse(JsonConvert.SerializeObject(turnContext.Activity.ChannelData));

                dataToken.TryGetValue("session", out var sessionObject);

                var parsedSessionObject = JObject.Parse(JsonConvert.SerializeObject(sessionObject));

                dataToken.TryGetValue("request", out var requestObject);

                var parsedRequestObject = JObject.Parse(JsonConvert.SerializeObject(requestObject));

                parsedRequestObject.TryGetValue("type", out var typeObject);

                parsedSessionObject.TryGetValue("user", out var userObject);

                var parsedUserObject = JObject.Parse(JsonConvert.SerializeObject(userObject));

                parsedUserObject.TryGetValue("accessToken", out var accessToken);

                string token = accessToken?.ToString();

                if (typeObject.ToString().Contains("LaunchRequest") && string.IsNullOrEmpty(token))
                {
                    var value = new Attachment
                    {
                        Name = "Your account is not linked to Alexa yet. Please link your account in the settings tab.",
                        ContentType = "application/vnd.microsoft.card.signin"
                    };

                    var reply = MessageFactory.Attachment(value);

                    await turnContext.SendActivityAsync(reply, cancellationToken);

                    return;
                }

                if (typeObject.ToString().Contains("LaunchRequest") && !string.IsNullOrEmpty(token))
                {
                    await turnContext.SendActivityAsync("Welcome to AA!! What would you like to do?", cancellationToken: cancellationToken);

                    return;
                }

                // Let the base class handle the activity.
                await base.OnTurnAsync(turnContext, cancellationToken);
            }

            // Save any state changes that might have occurred during the turn.
            await _conversationState.SaveChangesAsync(turnContext, false, cancellationToken);
        }

        protected override async Task OnMembersAddedAsync(IList<ChannelAccount> membersAdded, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            foreach (var member in membersAdded)
            {
                // Greet anyone that was not the target (recipient) of this message.
                if (member.Id != turnContext.Activity.Recipient.Id)
                {
                    await turnContext.SendActivityAsync(MessageFactory.Text("Hello and welcome!"), cancellationToken);
                    await _mainDialog.RunAsync(turnContext, _conversationState.CreateProperty<DialogState>("DialogState"), cancellationToken);
                }
            }
        }
    }
}`

**Comment by aishwaryaumachandran** [comment]
Also, this is the json output on the developer console. 

````
{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "PlainText",
				"text": "Your account is not linked to Alexa"
			},
			"card": {
				"type": "LinkAccount"
			},
			"shouldEndSession": false,
			"type": "_DEFAULT_RESPONSE"
		}
	}
}
```

**Comment by anishprasad01** [comment]
Thanks for the information. I will investigate and attempt to repro.

**Comment by aishwaryaumachandran** [comment]
Here's an update. The above code resolves the issue. 

So the login card appears on the Home screen and not the chat screen. We can close this issue. That was something I missed seeing earlier. Thank you!

**Comment by anishprasad01** [comment]
Thank you for sharing your resolution.
