### ISSUE TITLE
 I'm getting this error while sending adaptive cards to outlook from my azure bot. I am trying to build an Outlook connector bot as explained herein MS Docs (link https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-actionable-email?view=azure-bot-service-4.0 here). I have also created an Azure Bot and have registered it with the channel on the registration page. However, I am not getting a response in the bot when the button is clicked. Wonder if there is a more step-by-step. I need help to know how I can connect (and verify) the action with my Bot.

### ISSUE THREAD

**Issue by Surabhims** [MicrosoftDocs/bot-docs#2201]
**Describe the bug**
The remote endpoint returned an error (HTTP 404)
"actions": [
                        {
                            "type": "Action.Http",
                            "title": "Submit",
                            "method": "POST",
                            "url": "https://5fd9-49-207-202-185.ngrok.io/api/email",
                            "body": "{Option: {{Options.value}}, SuggestionText: {{Suggestions.value}}}",
                            "isPrimary": true,
                            "style": "positive",
                            "headers": [
                                {
                                    "name": "Content-Type",
                                    "value": "application/json"
                                },
                                {
                                    "name": "Authorization",
                                    "value": ""
                                }
                            ]

**Comment by anishprasad01** [comment]
@Surabhims,

Issues on documentation repositories should only be opened in reference to specific errors with the associated document. General bug reports should be opened in the repository corresponding to the framework or SDK that you are using. For example, a bug report or feature request for the Bot Builder C# SDK would be opened in [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet). 

Furthermore, this report is not reproducible in its current state. Please update your report and open it in the appropriate repository. This issue will be closed.
