### ISSUE TITLE
bot doesnt work in web chat following the steps here

### ISSUE THREAD

**Issue by jolienai** [MicrosoftDocs/bot-docs#2204]
[Enter feedback here]
After following all those steps the bot doesn't work when trying to test it on web chat.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Publish your bot to Azure - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=userassigned%2Cnewgroup%2Ccsharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by jolienai** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/47538362/171006451-17aba958-fdc8-49ad-8ca5-f0d9f9a4f484.png">

**Comment by anishprasad01** [comment]
Hi @jolienai,

Could you please provide information as to what you actually did, what didn't work, and which specific steps you followed? As it stands, I have no clue what you've done.

**Comment by anishprasad01** [comment]
This issue will be closed due to inactivity.
