### ISSUE TITLE
Python Bot Service Single-Tenant

### ISSUE THREAD

**Issue by arotena** [MicrosoftDocs/bot-docs#2205]
[Enter feedback here]
Hello,

When would be available the single tenant App registration option for python SDK?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cf57ecf-7774-8f8b-1e47-cf628c3bfa25
* Version Independent ID: ba30559c-36df-69c6-2703-cd67aa1380c2
* Content: [Create an Azure Bot resource in the Azure portal - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/abs-quickstart?view=azure-bot-service-4.0&tabs=userassigned)
* Content Source: [articles/v4sdk/abs-quickstart.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/abs-quickstart.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Thanks for your message! Unfortunately, I can't comment on future plans for the SDK or the Bot Service.

See [Bot Framework additional resources](https://docs.microsoft.com/azure/bot-service/bot-service-resources-links-help) for the best places to submit product requests or ask troubleshooting questions.
