### ISSUE TITLE
Please verify azure search service is up, restart the WebApp and try again

### ISSUE THREAD

**Issue by Dubawi** [MicrosoftDocs/bot-docs#2208]
We are trying to deploy a KB on production and QA (Jenkins) and we are getting this error:

"error": {
"code": "BadArgument",
"message": "Please verify azure search service is up, restart the WebApp and try again"

On Dev environment works fine. We restarted the service, but it fails again.

**Comment by dmvtech** [comment]
hi @Dubawi 

Can you please link to the documentation you were following when you received this error?

**Comment by dmvtech** [comment]
Also; does the KB work in the QnA portal?

**Comment by Dubawi** [comment]
Hi @dmvtech, I don't have documentation about this error, we can deploy using pipelines only. In dev environment, the KB works fine. 

When the pipeline executes this line:
![image](https://user-images.githubusercontent.com/79773748/173492029-7c45ef2b-7bb0-4468-a21f-a8c31a0cbb23.png)

we get this:
![image](https://user-images.githubusercontent.com/79773748/173491368-d736f17a-ef0e-47e3-ba24-6bc72b11b20c.png)

The service is on (started) and we restated it before running the script, but we got the error,
