### ISSUE TITLE
Typo "Bot emulator"→"Bot Framework emulator"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/bot-docs#2209]
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs

![image](https://user-images.githubusercontent.com/40815708/173197762-1f5078f3-427b-4055-a252-e0b31d06dc43.png)

#PingMSFDocs
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use Dispatch for multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@hyoshioka0128 -- Issue is fixed. Thanks for reporting.
