### ISSUE TITLE
Edit link up top leads to a 404

### ISSUE THREAD

**Issue by irwinwilliams** [MicrosoftDocs/bot-docs#221]
Hey, 
The edit link above (https://github.com/Microsoft/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md) leads to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Using LUIS for Language Understanding - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/Microsoft/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
@irwinwilliams - reported this bug to the team to fix. You can access the page by adding "docs" in the URL. See below.
(https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)

**Comment by irwinwilliams** [comment]
Issue's not fixed, @Kaiqb. If you go back to the document this comment is based on (in the Document Details section) and click "edit" you'll get a 404. 
Your team has to change the url on that link.
