### ISSUE TITLE
Incomplete Source Code for Python 

### ISSUE THREAD

**Issue by mayank-cse** [MicrosoftDocs/bot-docs#2213]
Sir/Ma'am,
Under "Suggested Action Using Button" the source code given for python isn't complete when compared to other languages.
Kindly check the code below.

Thank You!
```
reply.suggested_actions = SuggestedActions(
            actions=[
                CardAction(
                    title="Red",
                    type=ActionTypes.im_back,
                    value="Red",
                    image="https://via.placeholder.com/20/FF0000?text=R",
                    image_alt_text="R",
                ),
                CardAction(
                    title="Yellow",
                    type=ActionTypes.im_back,
                    value="Yellow",
                    image="https://via.placeholder.com/20/FFFF00?text=Y",
                    image_alt_text="Y",
                ),
                CardAction(
                    title="Blue",
                    type=ActionTypes.im_back,
                    value="Blue",
                    image="https://via.placeholder.com/20/0000FF?text=B",
                    image_alt_text="B",
                ),
            ]
        )
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53446ad1-6b8c-1ccb-6e78-2cb14358b1c3
* Version Independent ID: 8b0fcc34-e624-64a9-adc8-6c8fa3031f54
* Content: [Use button for input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-suggested-actions?view=azure-bot-service-4.0&tabs=python)
* Content Source: [articles/v4sdk/bot-builder-howto-add-suggested-actions.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-howto-add-suggested-actions.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Update should be live within a few hours.
