### ISSUE TITLE
Microsoft.Bot.Builder.Integration.AspNet.Core version should be 4.16  or above for single tenant and direct line extension

### ISSUE THREAD

**Issue by contactrmehra** [MicrosoftDocs/bot-docs#2215]
Microsoft.Bot.Builder.Integration.AspNet.Core version should be 4.16  or above for single tenant and direct line extension.
Here is the scenario:
Bot Service with private endpoints for Bot and Token.
C# app deployed on appservice
AppService DirectLine Extension configured in the appservice

For the client app to be able to communicate to extension the Microsoft.Bot.Builder.Integration.AspNet.Core version should be 4.16  or above.

The ib and ob flag will change to false if the version lower than 4.16 is used for the Bot

<img width="1650" alt="Screen Shot 2022-06-27 at 9 27 53 AM" src="https://user-images.githubusercontent.com/32003715/176899628-3e35198b-fc4e-4b3c-a8ba-5d18b106c6ee.png">
<img width="1634" alt="Screen Shot 2022-07-01 at 6 00 14 AM" src="https://user-images.githubusercontent.com/32003715/176899803-d6ee452b-849d-4d26-bfcc-2e58edded047.png">
<img width="1561" alt="Screen Shot 2022-06-30 at 10 12 15 PM" src="https://user-images.githubusercontent.com/32003715/176899884-9ecde722-5151-4940-9f8a-8383d596bb19.png">
<img width="1037" alt="Screen Shot 2022-06-27 at 10 49 37 AM" src="https://user-images.githubusercontent.com/32003715/176899975-f07d042d-b4df-4c84-b5af-20c94a610b3d.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID:

 665ea3ca-8796-7cc2-acda-c2a0a5f93912
* Version Independent ID: b110b105-da18-e4bd-5b6c-2bb8b130e079
* Content: [Direct Line App Service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-directline-extension.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-directline-extension.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@contactrmehra - per engineering, 4.16 is required if you're bot uses private endpoints (for network isolation). I have a draft update to the [Configure network isolation](https://docs.microsoft.com/azure/bot-service/dl-network-isolation-how-to) article.

**Comment by JonathanFingold** [comment]
Thanks for the feedback. Changes should be live later today. Closing as resolved.
