### ISSUE TITLE
The  CLI --password  argument is not recognized when trying to create an app.

### ISSUE THREAD

**Issue by Gariantroll** [MicrosoftDocs/bot-docs#2218]
The 

az ad app create --display-name "appName" --password "password" --available-to-other-tenants

Response messaging
unrecognized arguments: -password "password" --available-to-other-tenants

**Comment by ramfattah** [comment]
Hi @Gariantroll,

Can you confirm if you are using az cli 2.36.0?

**Comment by ramfattah** [comment]
Hi @Gariantroll ,

nvrmind above answer.
[Provision and publish a bot](https://docs.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=userassigned%2Ccsharp) documentation got updated last week.

For [az cli 2.39.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.39.0), the password parameter is no longer needed, [Reference here](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-create:~:text=Update%20an%20application.-,az%20ad%20app%20create,az%20ad%20app%20create%20%2D%2Ddisplay%2Dname%20mytestapp,-Create%20an%20application).

Example:
`az ad app create --display-name "<name>" --sign-in-audience "AzureADandPersonalMicrosoftAccount"`


Let me know if you have any questions. Thanks.

**Comment by Gariantroll** [comment]
Thanks,

I ended up using composer bot to make the bot and made the credentials and resources.

Thank you,
Alexis
________________________________

**Comment by ramfattah** [comment]
Awesome!

Closing this issue for now. Please feel free to re-open if needed. Thanks.
