### ISSUE TITLE
[Doc Bash][Image not matching the description]

### ISSUE THREAD

**Issue by smol-elak** [MicrosoftDocs/bot-docs#2221]
![image](https://user-images.githubusercontent.com/79516068/179985585-1c1f5be1-55d6-43cc-aecf-a73b465053a4.png)

The image is not in line with the description provided. ABS is a term mentioned in the image which I do not understand and is not mentioned anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ccf81d0-a7a0-1e2a-5b35-8cfd723c1225
* Version Independent ID: e3ebe0a1-a22f-1535-c649-3f79158b4ece
* Content: [Basics of the Bot Framework Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
ABS should read as Azure Bot Service. I'll update the image in the next few days.

**Comment by JonathanFingold** [comment]
Updated artwork should be live later today. Thanks.
