### ISSUE TITLE
When will bot be updated to .NET6?

### ISSUE THREAD

**Issue by alexsab1** [MicrosoftDocs/bot-docs#2224]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c86f2-9c0d-015b-d44f-58914fed2deb
* Version Independent ID: 85fe7f0c-002a-e449-55cb-712d92874b19
* Content: [Create a bot with the Bot Framework SDK in C#, Java, JavaScript, or Python - Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=csharp%2Cvs)
* Content Source: [articles/bot-service-quickstart-create-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-quickstart-create-bot.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
This is planned for an upcoming release, though we don't have a hard date yet.

**Comment by JonathanFingold** [comment]
1. The Bot Framework SDK versions for each language are now distinct from each other. see https://github.com/microsoft/botbuilder-dotnet/releases/ for the latest version of the SDK for C#, currently 4.16.1 (May 2022).
2. I can't announce the release before the fact, but the C# SDK is planned soon, well before December. You can experiment with the daily builds. See the [MyGet feed](https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily) for available packages. See any of the package pages for the details on how to use the MyGet packages.

**Comment by JonathanFingold** [comment]
Hmm, I had a simple 4.16 echo bot hanging around. I updated the project settings to target .NET 6, and it worked fine.

You may be able to sync to the latest current packages and target .NET 6 and have your bot work, before 4.17 is released.

**Comment by JonathanFingold** [comment]
https://www.nuget.org/packages/Microsoft.Bot.Builder 4.17.1 was pushed up today and is ready for consumption.
