### ISSUE TITLE
Send Box Customization

### ISSUE THREAD

**Issue by JoseKPG** [MicrosoftDocs/bot-docs#2225]
Would like ability to adjust border radius of text box to appear like the following
![TextBoxRadius](https://user-images.githubusercontent.com/110568157/183120138-beb0ea3c-3db5-4ae7-b13d-4716b8389307.png)
.

**Comment by JonathanFingold** [comment]
Hi @JoseKPG 

If you want to customize the Web Chat control, the most recent information will be in the microsoft/BotFramework-WebChat repo, see the [Customizing the Web Chat UI](https://github.com/microsoft/BotFramework-WebChat#customizing-the-web-chat-ui) in their README.

You can also open issues in their repo for feature requests. Hope this helps.
