### ISSUE TITLE
Unable to create resources with latest ARM templates using AZ CLI 2.36.0

### ISSUE THREAD

**Issue by ramfattah** [MicrosoftDocs/bot-docs#2228]
**Describe the bug**

Following this doc to deploy javascript bot:
https://docs.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot

After copying this [deploymentTemplates ](https://github.com/microsoft/botbuilder-js/tree/main/generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates) folder into my sample bot. 

I ran into an error while using `az cli 2.36.0` when attempting to [create an app service ](https://docs.microsoft.com/en-us/azure/bot-service/provision-app-service?view=azure-bot-service-4.0&tabs=userassigned%2Cexistingplan)using the latest ARM template and parameter files after running this command:
`az deployment group create –-resource-group <resource-group> --template-file <template-file-path> --parameters <parameters-file-path>` 
![image](https://user-images.githubusercontent.com/38049078/185275002-d7572e1d-946c-442f-9326-44cf09016c05.png)

```js
{'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'The template resource of type 'Microsoft.Web/serverfarms' at line '129' an
d column '5' is not valid. The name property cannot be null or empty. Please see https://aka.ms/arm-template/#resources for usage details.'.", 'additional Inf
o': [{'type': 'TemplateViolation', 'info': {'lineNumber': 129, 'linePosition': 5, 'path': 'properties. template.resources [0]'}}]}
```

#

Ultimately, using `az cli 2.39.0` and starting over from scratch (w/a few modifications) from the docs, I was able to create the app service using latest ARM Templates and published successfully.

Sharing the steps I took to publish:
1. Installed [az cli 2.39.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.39.0) (latest)
2. For section [Create an identity resource](https://docs.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=multitenant%2Cjavascript#:~:text=Azure%20CLI.-,Create%20an%20identity%20resource,-User%2Dassigned%20managed), 
     * Instead of `az ad app create --display-name "<name>" --password "<password>" --available-to-other-tenants`
     * I used : `az ad app create --display-name "<name>" --sign-in-audience "AzureADandPersonalMicrosoftAccount"`
3. After the above 2 changes, I no longer face issues with the deployment process in the [docs](https://docs.microsoft.com/en-us/azure/bot-service/provision-app-service?view=azure-bot-service-4.0&tabs=userassigned%2Cexistingplan).

>Note: for step #2.2, signInAudience values can be found here https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0#signinaudience-values

#

**To Reproduce**
1. Use az cli 2.36.0
5. Follow [this doc ](https://docs.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot)to deploy a bot
6. Progress through step 1 in section [Create resources with ARM templates ](https://docs.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=multitenant%2Cjavascript#:~:text=Create%20resources%20with%20ARM%20templates) 
7. See error after running command `az deployment group create –-resource-group <resource-group> --template-file <template-file-path> --parameters @<parameters-file-path>` 

#### Summary
* Cant create App Service using [latest ARM templates](https://docs.microsoft.com/en-us/azure/bot-service/provision-app-service?view=azure-bot-service-4.0&tabs=userassigned%2Cexistingplan#:~:text=If%20you%20do%20not%20have%20the%20current%20templates%2C%20create%20a%20copy%20in%20your%20bot%20project%20of%20the%20deploymentTemplates%20folder%3A%20C%23%2C%20JavaScript%2C%20Python%2C%20or%20Java.) with az cli 2.36.0, thus couldn't progress through the docs. 

* Upgrading az cli to 2.39.0 and creating an identity resource with the below command solved the issue.
    ```
    az ad app create --display-name "<name>" --sign-in-audience "AzureADandPersonalMicrosoftAccount"
    ``` 

* `--sign-in-audience` parameter doc found [here ](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-create:~:text=Update%20an%20application.-,az%20ad%20app%20create,documentation%2C%20see%20https%3A//docs.microsoft.com/graph/api/resources/application.,-Azure%20CLI).

**Comment by JonathanFingold** [comment]
Updated instructions for C# and JavaScript are merged and should be live after noon. Waiting on more info to fix the Python and Java instructions.

**Comment by JonathanFingold** [comment]
@ramfattah  - Closing, as I despair of any update to the Java ARM templates. Reopen if hope yet exists.
