### ISSUE TITLE
Typo of console command

### ISSUE THREAD

**Issue by MSTJingjingHe** [MicrosoftDocs/bot-docs#2229]
[Enter feedback here]

Instead of `ngrok http 3978 -host-header="localhost:3978"`, `ngrok http 3978 --host-header="localhost:3978"` works for me
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb2e2b4-8b91-ac29-b786-bf8418dd358b
* Version Independent ID: 13abc144-e6eb-eea7-3645-68331bf4537e
* Content: [Debug a channel using ngrok - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-debug-channel-ngrok.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-debug-channel-ngrok.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
With the latest version of ngrok, I verified that `ngrok http 3978 --host-header rewrite` works. Will update the article.

**Comment by JonathanFingold** [comment]
Update should be live later today.
