### ISSUE TITLE
Java Documentation sample code incomplete.

### ISSUE THREAD

**Issue by BlueWings98** [MicrosoftDocs/bot-docs#2231]
The Java code examples are incomplete as they are not opened and close correctly, rendering the copy button a bad idea to use because it will need changes after pasting in ones one code.
It also gives the feeling that parts of the sample code is missing.
Here we can see examples of both problems as taken from https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=java :

 * @return A future task.
 */
@Override
protected CompletableFuture<Void> onMessageActivity(TurnContext turnContext) {
    // Get state data from ConversationState.
    StatePropertyAccessor<ConversationData> dataAccessor =
        conversationState.createProperty("data");
    CompletableFuture<ConversationData> dataFuture =
        dataAccessor.get(turnContext, ConversationData::new);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e18bc52f-7eaf-a473-1cba-9b7c83bd0025
* Version Independent ID: c1b6cf03-c236-cfbf-aa4b-96961b816bc3
* Content: [Save user and conversation data in the Bot Framework SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=java)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
In general, the complete sample code is in the samples repo:
- The complete sample is linked to from the prerequisites section.
- The snippets in the article are meant to be illustrative.

I'll take a look at the article structure to see if I can make this clearer.

**Comment by JonathanFingold** [comment]
Looks like the code snippet got misaligned. Fixing.

**Comment by JonathanFingold** [comment]
Submitted a fix, which should be live by tomorrow. Hopefully, this addresses your issue.

**Comment by BlueWings98** [comment]
Looks much better now. Only missing the closing curly braces on ConversationData.Java:

public class ConversationData {
    // The time-stamp of the most recent incoming message.
    private String timestamp;
    // The ID of the user's channel.
    private String channelId;
    // Track whether we have already asked the user's name.
    private boolean promptedUserForName = false;

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String withTimestamp) {
        timestamp = withTimestamp;
    }

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String withChannelId) {
        channelId = withChannelId;
    }

    public boolean getPromptedUserForName() {
        return promptedUserForName;
    }

    public void setPromptedUserForName(boolean withPromptedUserForName) {
    // We need to close this one.
