### ISSUE TITLE
token returns 403 "The bot isn't authorized to perform the requested operation." when sending message to 1:1 chat in Teams

### ISSUE THREAD

**Issue by kkukkadri** [MicrosoftDocs/bot-docs#2232]
I have registered my bot in Azure only (not in dev.botframework.com, as it is no longer possible to create a bot in there) and successfully obtained an access token using the below POST request

POST https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded
grant_type=client_credentials&client_id=MICROSOFT-APP-ID&client_secret=MICROSOFT-APP-PASSWORD&scope=https%3A%2F%2Fapi.botframework.com%2F.default

I have also added Teams channel to my bot in Azure, uploaded my bot in Teams, and published the bot to my organization.

The token that I added to header and received using the above method returns 403  "The bot isn't authorized to perform the requested operation."

My Bot Connector client is created as follows:

 val connectorClient = RestConnectorClient(activity.serviceUrl, MicrosoftAppCredentials(config.azureBotId, config.azureBotSecret))
 connectorClient.restClient.headers().addHeader("Authorization", "Bearer ${token}")

In the forums, I have seen suggestions to add MicrosoftAppCredentials.trustServiceUrl("the URl"), but this method also does not seem to be available any longer in the library.

How to overcome the authorization issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58bf70a-3263-93a1-5bc2-085431a7aa6b
* Version Independent ID: c5e3de2f-58ad-1c6a-e0f3-93489d013114
* Content: [Authenticate requests with the Bot Connector API - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-authentication.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/rest-api/bot-framework-rest-connector-authentication.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by dmvtech** [comment]
Hi @kkukkadri 

- Is there a need to go about implementing it in this fashion (using the connector client instead of just using the SDK)?
- Have you tried using the Teams Auth sample to confirm that works for you?

Please give more information on what your end goal is so that we can assist in ensuring the best approach.

**Comment by dmvtech** [comment]
Closing due to lack of response.
