### ISSUE TITLE
Bad link to Bot Framework Telephony project

### ISSUE THREAD

**Issue by mladewig** [MicrosoftDocs/bot-docs#2233]
The link to the Bot Framework Telephony project returns a 404 from github.  [Bot Framework Telephony project](https://github.com/microsoft/botframework-telephony#readme). 

The project repo itself seems to have gone missing, or is not available to the public.

Please fix the repo / link. 

If this is under a controlled preview, please provide details how to signup for preview. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 176c6ffa-093d-88bc-cc6c-1d17c6c6ee42
* Version Independent ID: bac9d6af-5a47-6eb4-0114-2a20e031b03a
* Content: [Connect a bot to Telephony in Bot Framework SDK (Preview) - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-telephony?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-telephony.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-connect-telephony.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@mladewig -- that is odd. Following up internally. Will let you know when I find something out.

**Comment by JonathanFingold** [comment]
@mladewig -- this channel never made it out of preview. I'll update the docs.

**Comment by JonathanFingold** [comment]
PS. The channel is not accepting new bot development at this time.

**Comment by JonathanFingold** [comment]
Documentation updated. Changes should be live in a few hours.
