### ISSUE TITLE
Is it possible to play some audio message when user opens web chat using direct line channel in webpage?

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/bot-docs#2234]
-> When user click on the bot icon, I want to play some audio file regarding introduction of bot to the user. Is it possible??
I'm using bot framework SDKv4, through direct line channel

**Comment by anishprasad01** [comment]
Hi @samthrusha123,

WebChat runs on a website, so sure, you can write code to implement whatever features you would like to.

Furthermore, we request that issues opened on the docs repositories deal with specific issues with the documentation itself. Issues with SDK code or How-To questions should be asked in the appropriate location. 

This issue will be closed.
