### ISSUE TITLE
Web Chat with Direct Line Extension not working - 502 error

### ISSUE THREAD

**Issue by nickfrancis** [MicrosoftDocs/bot-docs#2236]
Hi
I've built a bot in Framework Composer and published it to Azure. Web Chat is working fine but I'd like to implement Direct Line as I believe it offers enhanced security, and might get round the Magic Code I'm seeing when users are signing in via OAuth.

I've worked through the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-webchat-client?view=azure-bot-service-4.0) but can't seem to get the bot to work on my local machine.

The token is generating ok but in Chrome console I'm getting the error:

Failed to connect Error: Connection response code 502
 (anonymous) @ webchat.js:2

Not sure if this is to do with the Body of my POST request but not sure what else to replace those parameters with. Below is a copy of my code - with various bits removed obviously :)

```
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script
      crossorigin="anonymous"
      src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js">
    </script>
    <style>
      html,
      body {
        background-color: #f7f7f7;
        height: 100%;
      }

      body {
        margin: 0;
      }

      #webchat {
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.05);
        height: 100%;
        margin: auto;
        max-width: 480px;
        min-width: 360px;
      }
    </style>
  </head>
  <body>
    <div id="webchat" role="main"></div>
    <script>
      (async function() {
        const res = await fetch('https://mks1cpm-chatbot.azurewebsites.net/.bot/v3/directline/tokens/generate', 
          {
            "method": "POST",
            "headers": {
              "Authorization": "Bearer " + "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            },
            "body": "{'user': {'id': 'my_test_id', 'name': 'my_test_name'}}"
          }
        );
        const { token } = await res.json();

        window.WebChat.renderWebChat(
          {
            directLine: await window.WebChat.createDirectLineAppServiceExtension({
              domain: 'https://mks1cpm-chatbot.azurewebsites.net/.bot/v3/directline',
              token
            })
          },
          document.getElementById('webchat')
        );

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>
  </body>
</html>

```
If anyone has any input or guidance I'd really appreciate it. Or - if I'm just pure barking up the wrong tree let me know!

**Comment by nickfrancis** [comment]
Believe the issue may be caused by using Bot Framework Composer and not being able to use NamedPipes in startup.cs:

"Allow your app to use named pipes:

Open the Startup.cs file.
In the Configure method, add a call to the UseNamedPipes method."

**Comment by JonathanFingold** [comment]
Unfortunately, there are many ways to break a Composer bot if you edit the underlying bot project. If you're just starting out with bot development, consider starting with [Power Virtual Agents](https://docs.microsoft.com/power-virtual-agents/fundamentals-what-is-power-virtual-agents) or an "SDK-first" bot ([Create a basic bot](https://docs.microsoft.com/azure/bot-service/bot-service-quickstart-create-bot)).

This repo is for doc-related issues. For the best places to submit product requests or ask troubleshooting questions, See [Bot Framework additional resources](https://docs.microsoft.com/azure/bot-service/bot-service-resources-links-help).
