### ISSUE TITLE
Incorrect Hyphen in App Service Provisioning Steps

### ISSUE THREAD

**Issue by anishprasad01** [MicrosoftDocs/bot-docs#2237]
In the steps for [Creating an App Service](https://docs.microsoft.com/en-us/azure/bot-service/provision-app-service?view=azure-bot-service-4.0&tabs=userassigned%2Cexistingplan#create-the-app-service) for deploying a bot, the box that allows you to copy the command template to paste in your terminal has an incorrectly formatted hyphen for the `--resource-group` parameter.

![image](https://user-images.githubusercontent.com/33945547/189703877-a1d979ec-725c-4c4b-bec5-daee95142b3b.png)

Depending on the terminal used, copying and pasting this command into the terminal will display two hyphens that look correct at first, but will trigger the error message `Parameter --resource-group is required` upon running the command. This may cause confusion for users who do not notice the error in the box.

Fixing the hyphen resolves the issue and the command is otherwise correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb04e71-7ca2-a900-9683-1d25297c9b50
* Version Independent ID: beb04e71-7ca2-a900-9683-1d25297c9b50
* Content: [Use Azure CLI to create an App Service resource - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/provision-app-service?view=azure-bot-service-4.0&tabs=userassigned%2Cexistingplan)
* Content Source: [articles/provision-app-service.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/provision-app-service.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Fix merged. Content should be live tomorrow.
