### ISSUE TITLE
Composer Issue

### ISSUE THREAD

**Issue by CLNELATU** [MicrosoftDocs/bot-docs#2238]
As the QnA Maker is getting deprecated. How does composer support in creating new QnA KB's !!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8e4395-71b3-8794-411b-750b696ddb99
* Version Independent ID: aa60dd8b-8cbf-8399-d1dc-87b628908560
* Content: [What's new in the Bot Service SDKs for C#, Java, JavaScript, and Python - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/what-is-new?view=azure-bot-service-4.0)
* Content Source: [articles/what-is-new.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/what-is-new.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@CLNELATU -- looking into this. I'll let you know as soon as I have an answer.

**Comment by CLNELATU** [comment]
> @CLNELATU -- looking into this. I'll let you know as soon as I have an answer.
@JonathanFingold Thanks for the reply.
I came to know that even LUIS is getting deprecated and should migrate Luis Applications to CLU.
So, Can you please help me with this too !

**Comment by JonathanFingold** [comment]
Information has been posted here: https://github.com/microsoft/BotFramework-Composer/issues/9400

**Comment by CLNELATU** [comment]
> Information has been posted here: [microsoft/BotFramework-Composer#9400](https://github.com/microsoft/BotFramework-Composer/issues/9400)

Thank you @JonathanFingold
