### ISSUE TITLE
Enabling Direct Line ASE for Composer - requires one additional step

### ISSUE THREAD

**Issue by nickfrancis** [MicrosoftDocs/bot-docs#2239]
Have been working on getting Direct Line Extension working on my bot in Composer & finally got it to work. Thought it might be worth documenting on this page for other users. Steps were as follows:

- Add the "use named pipes" to startup.cs as already documented.
- Add "using Microsoft.Bot.Builder.Integration.AspNet.Core;" to the top of startup.cs

Publishing Bot now works successfully with Named Pipes enabled.

Thanks
Nick

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c72c259-a864-9e1c-b585-562d6bca80ff
* Version Independent ID: 30a3fce8-d236-5c7b-88a0-003c971f2819
* Content: [Configure .NET bots for the Direct Line App Service extension in the Bot Framework SDK - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-net-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-directline-extension-net-bot.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Sorry for the delay @nickfrancis -- there's a thread going here: https://github.com/microsoft/BotFramework-Composer/issues/9400.

**Comment by JonathanFingold** [comment]
Fix is live.
