### ISSUE TITLE
Typo in "Select a skill" section

### ISSUE THREAD

**Issue by guy-microsoft** [MicrosoftDocs/bot-docs#2241]
"SkllPrompt" should be "SkillPrompt".
https://learn.microsoft.com/en-us/azure/bot-service/skill-use-skilldialog?view=azure-bot-service-4.0&tabs=cs#select-a-skill

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf0b5ce-8d48-2045-a163-9154efa07de4
* Version Independent ID: 40996693-4ce0-85ce-09cc-1996bf9ddcd6
* Content: [Use a dialog to consume a skill - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/skill-use-skilldialog?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/skill-use-skilldialog.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/skill-use-skilldialog.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Fix should be live later today. Thanks.
