### ISSUE TITLE
Usage of  Primary Key in LUIS app

### ISSUE THREAD

**Issue by karthik-jeevith** [MicrosoftDocs/bot-docs#2244]
In  [official documentation image](https://learn.microsoft.com/en-us/azure/bot-service/v4sdk/media/how-to-luis/manage-luis-app-azure-resources.png?view=azure-bot-service-4.0) the primary key of **authoring resource** is being used as **LuisAPIKey** in the appsettings.json ,  my suggestion is , the primary key of **prediction resource** too can be used as the **LuisAPIKey** . both are working fine. please correct if wrong. Thanks in Advance. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Add natural language understanding to your bot - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@karthik-jeevith - Can you update the description? The issue is incomplete.

**Comment by JonathanFingold** [comment]
Thanks for the clarification @karthik-jeevith -- I'll check with the engineers to make sure this works consistently. However, starting in April, you won't be able to create new LUIS apps.

**Comment by JonathanFingold** [comment]
@karthik-jeevith -- I'll update the docs in the next few days.

**Comment by JonathanFingold** [comment]
Updated article will be live tomorrow.
