### ISSUE TITLE
There is no guidance on how to add to Teams as part of a Teams app

### ISSUE THREAD

**Issue by DimitrisK5** [MicrosoftDocs/bot-docs#2246]
There is a warning against adding a bot by GUID, however there are no instructions on how to link a Teams app with an Azure Bot. FWIW, the Teams documentation pages offer no guidance either.

This is especially problematic because the Teams documentation pages offer examples only for new apps created using the Teams plugin for VS Code, which assumes a fresh application deployment. I couldn't find any instructions on how to include an existing Azure Bot to a Teams app.

I understand that not everything should be included in this page. Majority of instructions should live in the Teams documentation pages, but some guidance in this page is very much needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e31fe2a-ac8e-815c-f33e-2f08fd554915
* Version Independent ID: e4b7dd0b-e9c9-00d8-41ea-f2ecbbb68752
* Content: [Connect a Bot Framework bot to Microsoft Teams - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0)
* Content Source: [articles/channel-connect-teams.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/channel-connect-teams.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
@DimitrisK5 - I haven't had a chance to do this myself, but I think the instructions you're looking for are in this section of the Teams docs, [distribute your app](https://learn.microsoft.com/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview). If this is helpful, and can add this link to the note.

**Comment by DimitrisK5** [comment]
Hi and thank you for answering!

The page you link to does not really offer any guidance either. Here are some of the things I had to figure out and I would expect some guidance on:

***
### How to create a manifest and an app package
The [official page](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-package) is useless if you already have an Azure Bot because there is no starting place. I would point to the [Teams Developer Portal](https://dev.teams.microsoft.com) and have a few simple steps like:
1. Create an app
2. Fill-in the `Application (client) ID` by using the `Microsoft App ID` of the Azure Bot
3. On App Features add Bot feature. On `Enter a bot ID` enter the `Microsoft App ID` of the Azure Bot
4. Click `Preview in Teams` to side-load the app locally or `Publish` to publish the app or download the app package
5. (Optional) Create a `TeamsAppManifest` folder in your solution and add there the contents of the package (for an example see the [Teams Conversation Bot sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/57.teams-conversation-bot)

### Bot identity caveats
When you install an app with an Azure Bot on a Teams Team, you might encounter an error:

> Custom apps must come from the same organization that they are being installed in, and the webApplicationInfo.id must be registered in the same organization.

Make sure the `Messaging endpoint` of the Azure Bot points to an Azure deployed bot that uses a Managed Identity (Note: not sure about this one, I have only tested with _User-assigned Managed Identity_). If the `Messaging endpoint` points to your local bot (e.g. using Ngrok), the app cannot be authenticated. You can only test with the local bot on one-on-one conversations.

If you are using a valid `Messaging endpoint` you might still encounter the above error or an error like the following when installing on a Teams Team:

> Custom apps must come from the same organization that they are being installed in, and the webApplicationInfo.id must be registered in the same organization.

or 

> Please check the values of webApplicationInfo.id, webApplicationInfo.applicationPermissions and authorization.permissions.resourceSpecific.

In that case, edit your `manifest.json` file manually, delete the `webApplicationInfo` object and recreate the app package. (Note: this is just one solution I found, which would be problematic if I needed to use e.g. SSO on a Tab. Not sure what the proper solution to this is.)
***
Anyway, that's the sort of guidance I would expect. If you feel that this is not needed or that a there are sufficient info on some other link where you can point to (and maybe add some additional info there), feel free to close this issue. As it stands, I feel it's very difficult to figure out how to integrate an existing Azure Bot to Teams, but that's just my personal experience.

Thank you again for your time!

**Comment by DimitrisK5** [comment]
Just a side-note. The `webApplicationInfo.id` related problems I had might have been related to some Resource-specific consent (RSC) permissions I had in the manifest. They are not yet supported it seems and the error messages are not very helpful.

Not related to this issue, but I thought I might give a heads-up to anyone that might find this from a search engine.

**Comment by JonathanFingold** [comment]
@DimitrisK5 -- I've asked a writer on the Teams documentation team to look into updating their content. Once that's in place, I'll have a better idea of how to update this article.

**Comment by JonathanFingold** [comment]
@DimitrisK5 -- It looks there were updates to these Teams docs over the last week:
- [Create Teams app package](https://learn.microsoft.com/microsoftteams/platform/concepts/build-and-test/apps-package)
- [App manifest schema for Teams](https://learn.microsoft.com/microsoftteams/platform/resources/schema/manifest-schema)
- [Upload your app in Teams](https://learn.microsoft.com/microsoftteams/platform/concepts/deploy-and-publish/apps-upload)

Let me know if this would have made your initial publishing attempt smooth enough not to have required additional research and trial and error.

I'll review the Bot Framework doc to see if I can add a few more breadcrumbs, too.
