### ISSUE TITLE
A customer is inquiring if 2 Azure Bots can share 1 App Service?

### ISSUE THREAD

**Issue by iamramengirl** [MicrosoftDocs/bot-docs#2247]
Is it possible for 2 Azure Bots to share 1 App Service? If so, how to manage the config of App Service?
If not, may you please update the documentation? Thank you in advance!

https://learn.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=userassigned%2Ccsharp

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Provision and publish a bot in Azure - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=userassigned%2Ccsharp)
* Content Source: [articles/provision-and-publish-a-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/provision-and-publish-a-bot.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by jameslew** [comment]
It's possible though we don't have official documentation for such.  There is a slightly older reference here that should be conceptually accurate.  Basically you're going to replace the logic that retrieves authentication credentials to first look up which bot your code is acting as at the time, and then return the appropriate signing credentials from that lookup.

https://stackoverflow.com/questions/42414912/serving-multiple-bots-from-one-bot-instance
https://devblogs.microsoft.com/cse/2017/01/10/creating-a-single-bot-service-to-support-multiple-bot-applications/

**Comment by iamramengirl** [comment]
Thank you for your reply, @jameslew!
