### ISSUE TITLE
CQA KB Download HTTP request

### ISSUE THREAD

**Issue by CLNELATU** [MicrosoftDocs/bot-docs#2249]
Hi,
We currently use CQA Services, but we cannot find the HTTP request to download KB from Language Studio. any solution for this

For reference (QNA HTTP request):
(GET {Endpoint}/qnamaker/v4.0/knowledgebases/{kbId}/{environment}/qna)

**Comment by JonathanFingold** [comment]
@CLNELATU - there are a couple new custom question answering samples. I'm working on a draft companion article.

https://github.com/microsoft/BotBuilder-Samples#custom-question-answering-samples

**Comment by CLNELATU** [comment]
Got the HTTP Request URL hence closing
