### ISSUE TITLE
How to add CQA to LUIS Dispatcher

### ISSUE THREAD

**Issue by CLNELATU** [MicrosoftDocs/bot-docs#2250]
Hi, I know how to create and add QnA maker to Luis Dispatcher.

But we cannot find Adding CQA to Luis Dispatcher  Can anyone help us with it !

**Comment by JonathanFingold** [comment]
The recommended approach would be to use Cognitive Service for Language's _orchestrator workflow_ to generate the combined language model. We don't yet have a sample for how to do that from the Bot Framework.

**Comment by CLNELATU** [comment]
@JonathanFingold  Thank you so much

**Comment by CLNELATU** [comment]
@JonathanFingold 
**Can we use the downloaded CQA KB (json/tsv) adding to the dispatcher as a file.** Since we are aware of that command.
"dispatch add -t file -n TestModule3 -f c:\src\testmodule3.json"

**Comment by JonathanFingold** [comment]
I've pinged the engineering team. Hopefully, they'll be able to comment soon.

**Comment by CLNELATU** [comment]
@JonathanFingold 
As per our requirement, we have added .tsv file from CQA to Luis Dispatcher and it's working fine.
Thank you :)
