### ISSUE TITLE
Not working with latest node version (18.12.1)

### ISSUE THREAD

**Issue by abhisheke1mishra** [MicrosoftDocs/bot-docs#2253]
These steps are not working with latest node.js version 18.12.1 and npm 9.2.0 version.
During npm start getting error for restify - "TypeError: Cannot set property closed of #<Readable> which has only a getter"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f55c86f2-9c0d-015b-d44f-58914fed2deb
* Version Independent ID: 85fe7f0c-002a-e449-55cb-712d92874b19
* Content: [Create a basic bot - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=javascript%2Cvs#start-your-bot)
* Content Source: [articles/bot-service-quickstart-create-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-quickstart-create-bot.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Opened a bug in the SDK repo. Closing here.

**Comment by anishprasad01** [comment]
https://github.com/microsoft/botbuilder-js/issues/4401
