### ISSUE TITLE
Remove Bot Python and Java tutorial

### ISSUE THREAD

**Issue by rvinothrajendran** [MicrosoftDocs/bot-docs#2254]
[Enter feedback here]

I think Bot Python and Java tutorial has to remove from Microsoft Learn.  Because Java and python moved to as maintains project 
New Bot development developers choose Bot SDK (C# or JS) or PVA only.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f55c86f2-9c0d-015b-d44f-58914fed2deb
* Version Independent ID: 85fe7f0c-002a-e449-55cb-712d92874b19
* Content: [Create a basic bot - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=csharp%2Cvs)
* Content Source: [articles/bot-service-quickstart-create-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-quickstart-create-bot.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by peterswimm** [comment]
I think the position of the PM group is that the content is functionally complete, so we should probably keep them for now, and mark whatever status we have them down as.
