### ISSUE TITLE
Feedback on Send a (non-reply) message section

### ISSUE THREAD

**Issue by abhishekpdubey** [MicrosoftDocs/bot-docs#2256]
This feedback is for "Send a (non-reply) message " section.
Is it possible to send a non-reply message to a channel? what are the steps to do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3bb730d0-5973-2b5a-3594-18338cf58812
* Version Independent ID: 1785b946-10bd-6cd1-ac6b-f70cf6c9bd12
* Content: [Send and receive messages - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-send-and-receive-messages?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-send-and-receive-messages.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/rest-api/bot-framework-rest-connector-send-and-receive-messages.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Yes. You need an existing conversation on the channel. Otherwise, the steps are very similar to how you send a reply message.
