### ISSUE TITLE
Typo in the deployment command on the "Use Azure CLI to create an App Service" page

### ISSUE THREAD

**Issue by anishprasad01** [MicrosoftDocs/bot-docs#2257]
The command to [create an app service](https://learn.microsoft.com/en-us/azure/bot-service/provision-app-service?view=azure-bot-service-4.0&tabs=multitenant%2Cexistingplan#create-the-app-service) has an extraneous `@` symbol in the parameters argument of the command which causes this command to fail when run.

```bash
az deployment group create --resource-group <resource-group> --template-file <template-file-path> --parameters @<parameters-file-path>
```

The correct command is:

```bash
az deployment group create --resource-group <resource-group> --template-file <template-file-path> --parameters <parameters-file-path>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: beb04e71-7ca2-a900-9683-1d25297c9b50
* Version Independent ID: beb04e71-7ca2-a900-9683-1d25297c9b50
* Content: [Use Azure CLI to create an App Service resource - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/provision-app-service?view=azure-bot-service-4.0&tabs=multitenant%2Cexistingplan)
* Content Source: [articles/provision-app-service.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/provision-app-service.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Fixed
