### ISSUE TITLE
Should mention the regional endpoint of Directline in Europe

### ISSUE THREAD

**Issue by guy-microsoft** [MicrosoftDocs/bot-docs#2259]
Doc doesn't specify the https://europe.directline.botframework.com endpoint. I think it should to avoid confusion when using regional bot service.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd81692-76ae-f89f-19d8-d92845cc7dc9
* Version Independent ID: c26a44b5-6995-11e0-daa0-001a2716b9f1
* Content: [API reference - Direct Line API 3.0 - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-api-reference.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-api-reference.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by guy-microsoft** [comment]
Thanks!

**Comment by JonathanFingold** [comment]
Turns out, the https://europe.directline.botframework.com/ endpoint is correct. I'll update the article. Thanks for pointing this out.

**Comment by JonathanFingold** [comment]
The update should be live later today. Thanks.
