### ISSUE TITLE
Blob State Storage Instructions are incorrect for Node bots

### ISSUE THREAD

**Issue by anishprasad01** [MicrosoftDocs/bot-docs#2261]
*Issues with this document initially reported in* https://github.com/microsoft/botbuilder-js/issues/4411.

The instructions for installing and configuring blob storage for Node.js bots is out of date. The current instructions mostly reference the `botbuilder-azure` package. However, the blob storage class in this package has been deprecated and the functionality moved to a new class in the `botbuilder-azure-blobs` package.

In the section [Installing Blob Storage Packages](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript#installing-blob-storage-packages):
* While the example command instructs users to (correctly) install `botbuilder-azure-blobs`, the rest of the text in this section references the `botbuilder-azure` package. These references should be changed to specify `botbuilder-azure-blobs`.

In the section [Blob Storage Implementation](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript#blob-storage-implementation):
* There are more references to `botbuilder-azure` that need to be changed to `botbuilder-azure-blobs`.
* The code to reference the blobs class in the code is currently written as:
```js
const { BlobStorage } = require("botbuilder-azure");
```
In order to reference the new blobs class, it should be changed to:
```js
const { BlobsStorage } = require("botbuilder-azure-blobs");
```
*Note*: The old class name BlobStorage has been changed to BlobsStorage, where the word "Blob" has been pluralized. This is easy to miss and will cause errors claiming an inability to create the object. All references to the old class name must be updated to the new class name.
* The code to create a new blob storage object is currently written as:
```js
const myStorage = new BlobStorage({
    containerName: process.env.BlobContainerName,
    storageAccountOrConnectionString: process.env.BlobConnectionString
});
```
In order to correctly create the new object, it should be written as follows:

```js
const myStorage = new BlobsStorage(
    process.env.BlobConnectionString, 
    process.env.BlobContainerName
);
```
*Notes*:
1. The `{}` brackets are now gone. The constructor in the old class took an object containing the connection string and container name as a parameter. The new class only accepts each as a distinct string parameter.
2. The order of the parameters matters now, and has been changed accordingly. The connection string must be first, and the container name second.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Write directly to storage - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Fix merged.
