### ISSUE TITLE
QnA maker KB import Issue

### ISSUE THREAD

**Issue by CLNELATU** [MicrosoftDocs/bot-docs#2262]
Hi, we are unable to import excel into the QnAmaker KB. can anyone help with this?
<img width="385" alt="ss" src="https://user-images.githubusercontent.com/92921723/214845077-6641581f-335a-46c4-91b1-c5229e0a37fc.png">

**Comment by JonathanFingold** [comment]
Please see https://learn.microsoft.com/azure/cognitive-services/language-service/question-answering/how-to/export-import-refresh. If that doesn't help, please use the feedback button at the bottom of the page to open an issue in their doc set.
