### ISSUE TITLE
Steps missing and correction in the configuration section of the docs

### ISSUE THREAD

**Issue by cswesh** [MicrosoftDocs/bot-docs#2264]
### Steps missing and correction in the configuration section of the docs 
In the **Update bot code** section => before the following line of code added for the ***CloudAdaptor (Recommended)*** 
>
>***(To be added - start)***
>Add this const { AuthenticationConstants } = require('botframework-connector')
>**Please note: add the npm package 'botframework-connector' if not available in the package.json > dependencies** 
>***(To be added - end)***
>

And there is an extra space to be removed before ***APPSETTING_WEBSITE_SITE_NAME***
```javascript
adapter.connectNamedPipe(
    process.env. APPSETTING_WEBSITE_SITE_NAME + '.directline',
    async (context) => {
        await myBot.run(context);
    },
    process.env.MicrosoftAppId,
    AuthenticationConstants.ToChannelFromBotOAuthScope);
```
```javascript
adapter.connectNamedPipe(
    process.env.APPSETTING_WEBSITE_SITE_NAME + '.directline',
    async (context) => {
        await myBot.run(context);
    },
    process.env.MicrosoftAppId,
    AuthenticationConstants.ToChannelFromBotOAuthScope);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 206a361d-42ef-ed02-9c1d-5775395aa7a9
* Version Independent ID: d122568b-a72e-7087-03db-a0aa386094b9
* Content: [Configure Node.js bots for Direct Line App Service extension in the Bot Framework SDK - Bot Service](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-node-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-directline-extension-node-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-channel-directline-extension-node-bot.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by JonathanFingold** [comment]
Fix should be visible by tomorrow. Thanks.
