### ISSUE TITLE
FormFlow not available in SDK 4.x

### ISSUE THREAD

**Issue by Souvik04** [MicrosoftDocs/bot-docs#227]
I am using Bot builder SDK 4.x and trying to implement FormFlow. I have referenced the required nuget packages but I can't see any reference for `IForm` in the `Microsoft.Bot.Builder.FormFlow` namespace. Is there something I am missing?
Also referring to the documentation page, it only shows documentation for SDK 3.x.

![image](https://user-images.githubusercontent.com/17876015/44329302-bf2e0200-a481-11e8-9cc3-7ee45183ab78.png)

![image](https://user-images.githubusercontent.com/17876015/44329370-ea185600-a481-11e8-83fe-ccbc2dd79fe1.png)
Is it possible to implement FormFlow using SDK 4.x or it not supported yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46424ef9-9af9-55a1-207a-4202ef8f1af3
* Version Independent ID: cad8ef24-51c5-e32b-6af8-cb3a3fe7b551
* Content: [Basic features of FormFlow - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-formflow?view=azure-bot-service-3.0&viewFallbackFrom=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-formflow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-formflow.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
In v4, the v3 features are in the **Classic** library. To access form flow, use the `Microsoft.Bot.Builder.Classic` NuGet package and reference the `Microsoft.Bot.Builder.Classic.FormFlow` namespace.

Please reopen if this does not address the issue.

**Comment by Souvik04** [comment]
I tried your solution. Here's what my Form is like-
```
[Serializable]
public class HelpForm
{
	public string FullName { get; set; }
	public string EmailID { get; set; }
	public string Question { get; set; }
	public DateTime BestTimeToContact { get; set; }
	public List<Priority> Priority { get; set; }
	public static IForm<HelpForm> BuildForm()
	{
		return new FormBuilder<HelpForm>()
			.Message("Please fill out the details as prompted.")
			.Build();
	}
}

public enum Priority
{
	Low,
	Medium,
	High
}
```
In my `OnTurn` event of my bot, I am doing something like this-
`await Microsoft.Bot.Builder.Classic.Dialogs.Conversation.SendAsync(context, () => FormDialog.FromForm(HelpForm.BuildForm));`
This doesn't seem to work and I get a response in the emulator as 

> Sorry, my bot code is having an issue.

**Comment by EricDahlvang** [comment]
@Souvik04

The Bot Builder Community has released a FormFlow implementation for V4: https://www.nuget.org/packages/Bot.Builder.Community.Dialogs.FormFlow/  with source here: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/master/libraries/Bot.Builder.Community.Dialogs.FormFlow/README.md

**Comment by EricDahlvang** [comment]
Have you created a Bot Channels Registration?  https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-3.0#create-a-bot-channels-registration and point the Messaging Endpoint at your Azure web app.

Place the Microsoft App Id and Microsoft App Password in the bot file, or application settings of the web app (depending on how your bot is setup). Here is how you can get the password after creating a bot registration: https://blog.botframework.com/2018/07/03/find-your-azure-bots-appid-and-appsecret/

**Comment by ArunaSinghRathore** [comment]
While debugging production endpoint in local bot emulator i found following error in log:
request to https://xxxxxx.azurewebsites.net/api/messages failed, reason: getaddrinfo ENOTFOUND xxxxxxx.azurewebsites.net xxxxxxx.azurewebsites.net:443

**Comment by EricDahlvang** [comment]
Does your bot file have a production endpoint?  Can you share your startup file, how is it loading the bot file?

**Comment by ArunaSinghRathore** [comment]
This is my bot file                       
{
  "name": "FormFlowV4SDK",
  "description": "",
  "services": [
    {
      "appId": "copied app id here",
      "appPassword": "copied password here"
    },   
    {
      "type": "endpoint",
      "appId": "copied the app id here",
      "appPassword": "I have copied the password here",
      "endpoint": "https://xxxxxx.azurewebsites.net/api/messages",
      "name": "production",
      "id": "97"
    }
  ],
  "padlock": "",
  "version": "2.0",
  "path": "C:\\Projects\\Chatbots\\botbuilder-community-dotnet-master\\botbuilder-community-dotnet-master\\samples\\Form Flow Sample\\FormFlowV4SDK.bot",
  "overrides": null,
  "secretKey": ""
}

below is excerpt from startup file(i have made no change here)
 services.AddBot<TestBot>(options =>
            {
                IStorage dataStore = new MemoryStorage();
                options.State.Add(new ConversationState(dataStore));
                options.Middleware.Add(new AutoSaveStateMiddleware(options.State.ToArray()));
                //options.Middleware.Add(new ShowTypingMiddleware());

                var secretKey = Configuration.GetSection("botFileSecret")?.Value;
                var botFilePath = Configuration.GetSection("botFilePath")?.Value;

                // Loads .bot configuration file and adds a singleton that your Bot can access through dependency injection.
                var botConfig = BotConfiguration.Load(botFilePath ?? @".\BotConfiguration.bot", secretKey);
                services.AddSingleton(sp => botConfig ?? throw new InvalidOperationException($"The .bot config file could not be loaded. ({botConfig})"));

                // Retrieve current endpoint.
                var environment = _isProduction ? "production" : "development";
                var service = botConfig.Services.Where(s => s.Type == "endpoint" && s.Name == environment).FirstOrDefault();
                if (!(service is EndpointService endpointService))
                {
                    throw new InvalidOperationException($"The .bot file does not contain an endpoint with name '{environment}'.");
                }

                options.CredentialProvider = new SimpleCredentialProvider(endpointService.AppId, endpointService.AppPassword);
            });

**Comment by EricDahlvang** [comment]
Is the _isProduction flag being set correctly?

**Comment by ArunaSinghRathore** [comment]
I have set it to true while publishing, but after publishing on accessing the bot url , it gives following error : HTTP Error 502.5 - Process Failure
