### ISSUE TITLE
Download PDF option on the left side does not work

### ISSUE THREAD

**Issue by ignaciofls** [MicrosoftDocs/bot-docs#230]
Empty doc (0 bytes) is generated. Works fine for other services within Azure portfolio, kindly fix it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33a7931f-82f5-dde3-3d8d-63e6d88dfd4a
* Version Independent ID: 38bc1524-942b-5a49-d680-81368f3f8ef7
* Content: [Secure your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-security?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-security.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-security.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@mikekinsman - could you take a look at this issue.

**Comment by Kaiqb** [comment]
@ignaciofls - this issue has been resolved. Thanks for reporting.
