### ISSUE TITLE
Coulldn't send

### ISSUE THREAD

**Issue by Sreejith-Git** [MicrosoftDocs/bot-docs#231]
When i try to test the bot in the Web chat and type "Hi" i only get "couldn't send" and a link "retry", but nothing happens

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your bot to Azure - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-3.0)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Sreejith-Git** [comment]
Hi Jonathan,

Yes , I did test on Emulator and it was working perfectly.

Please find the error message recorded based on your steps,

There was an error sending this message to your bot: HTTP status code
NotFound

**Comment by Kaiqb** [comment]
@Sreejith-Git - you can use stackoverflow to get help. Here is the link: https://stackoverflow.com/questions/tagged/botframework
