### ISSUE TITLE
This no longer reflects the Twilio site UI. 

### ISSUE THREAD

**Issue by JerryNixon** [MicrosoftDocs/bot-docs#232]
This no longer reflects the Twilio site UI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b0da760-d520-f235-70af-f7bfffb2187c
* Version Independent ID: 8ef43209-3288-3307-ca47-d27bd90f5fb8
* Content: [Connect a bot to Twilio - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-twilio?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-channel-connect-twilio.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-twilio.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by mehtanilay10** [comment]
Looks like the link is older. I found below link which has similar UI.
https://www.twilio.com/user/account/voice/dev-tools/twiml-apps

**Comment by v-kydela** [comment]
@mehtanilay10 I found that too but it's only good for one step. The rest of the guide is still largely inapplicable. For example, when we create a new number we can't click it to "add it to the TwiML application." There are too many SID's scattered throughout the site, too many places to enter a request URL, and nowhere to enter the name of an existing TwiML app. I can't use the guide in its current state.

**Comment by v-kydela** [comment]
Okay, I got it working. It looks like the account SID and auth token you want are the ones just found at the root: https://www.twilio.com/console

I don't know if any other configurations are needed. I fiddled with various options throughout the Programmable SMS site. While you can create a TwiML app, that is probably unnecessary.

**Comment by CathyQian** [comment]
@JerryNixon @v-kydela  The problem will be addressed and represented in the new document soon. Please check back in a week or so.

**Comment by JonathanFingold** [comment]
Please reopen if issues remain in this article.
