### ISSUE TITLE
Channels requiring the Magic Code

### ISSUE THREAD

**Issue by mchuck** [MicrosoftDocs/bot-docs#236]
"The reason for this is that some clients (like WebChat) do not need the Magic Code verification code and can directly send the Token in the TokenResponseEvent. Other clients still require the magic code (like Facebook or Slack)." - Which channels exactly don't need the Magic Code? Is it possible to use directline channel with WebChat control built from source and be free from the code? TBH it is a UX nightmare :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d80e0b-f1b7-175b-128d-0fb12f17ae36
* Version Independent ID: 1ed9006a-bf0b-9aaa-d180-9d2cb0c09524
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0)
* Content Source: [articles/bot-builder-tutorial-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tutorial-authentication.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **JonathanFingold**

**Comment by desflan** [comment]
MS Teams has been confirmed as needing a Magic Number on [stackoverflow](https://stackoverflow.com/questions/52043234/oauthcard-magic-number-in-ms-teams/52045361?noredirect=1#comment91066278_52045361)

**Comment by Kaiqb** [comment]
Please ask our support engineers this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework).
