### ISSUE TITLE
Chatdown examples

### ISSUE THREAD

**Issue by miikaeru** [MicrosoftDocs/bot-docs#238]
The hyperlink for chatdown example files is dead. Does there still exists examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa3a3039-9b21-fcb9-3fd7-4ae8c69bce93
* Version Independent ID: 36ceb86e-828a-03d7-3245-44ab6ea4c09a
* Content: [Test and debug bots using the Bot Framework Emulator - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-3.0#author-transcripts-with-chatdown)
* Content Source: [articles/bot-service-debug-emulator.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-debug-emulator.md)
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by JonathanFingold** [comment]
It is now [here](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Chatdown). We'll update the link.
