### ISSUE TITLE
Missing line

### ISSUE THREAD

**Issue by jwiley84** [MicrosoftDocs/bot-docs#239]
The code sample above for the global.asax.cs file is missing a line. Above 'var uri = ...' there should be the following line:

`GlobalConfiguration.Configure(WebApiConfig.Register);`

created PR.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 817455ad-3059-608d-17ad-ce68300756d9
* Version Independent ID: a6ed0691-e64c-61c2-fc9a-8b5c45c85418
* Content: [Manage custom state data with Azure Cosmos DB - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state-azure-cosmosdb?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-state-azure-cosmosdb.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-state-azure-cosmosdb.md)
* Product: **bot-framework**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kaiqb**

**Comment by Kaiqb** [comment]
@jwiley84 - fixed. thanks for reporting
