### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by mas-dse-juremigi** [MicrosoftDocs/bot-docs#245]
All requests return a 501 using the above code
```
127.0.0.1 - - [30/Aug/2018 17:14:54] code 501, message Unsupported method ('GET')
127.0.0.1 - - [30/Aug/2018 17:14:54] "GET /api/messages HTTP/1.1" 501 -
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a20df2-727c-1afd-2b87-836ea1ea4f7a
* Version Independent ID: 157fc262-fb1f-f12d-0890-e90119feb444
* Content: [Create a bot using Bot Builder SDK for Python - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/python/bot-builder-python-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/python/bot-builder-python-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by Kaiqb** [comment]
@mas-dse-juremigi 

Fixed this line: 
            loop.run_until_complete(JwtTokenValidation.assert_valid_activity(
                activity, self.headers.get("Authorization"), credential_provider))

to
loop.run_until_complete(JwtTokenValidation.authenticate_request(
                activity, self.headers.get("Authorization"), credential_provider))
