### ISSUE TITLE
There is no module like FormFlow for Nodejs?

### ISSUE THREAD

**Issue by blueelvis** [MicrosoftDocs/bot-docs#246]
Hi,

Is there no module like FormFlow for Nodejs as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46424ef9-9af9-55a1-207a-4202ef8f1af3
* Version Independent ID: cad8ef24-51c5-e32b-6af8-cb3a3fe7b551
* Content: [Basic features of FormFlow - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-formflow?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-formflow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-formflow.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@blueelvis - there isn't one.
