### ISSUE TITLE
To not publish DB keys on public repos...

### ISSUE THREAD

**Issue by sjciasullo** [MicrosoftDocs/bot-docs#247]
Regarding "Modify Your Bot Code"#2. It's my understanding that it would be bad practice to hardcode your database keys directly into your code. I'd love to see a note or comment next to the database option fields (host and masterKey) here acknowledging that these values should be kept hidden (i.e. using some environmental variables like process.env).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 432edb74-c60c-6416-c568-69fcbe0a768e
* Version Independent ID: 06e3a7a0-263c-9654-d328-8d573c0552ea
* Content: [Manage custom state data with Azure Cosmos DB - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state-azure-cosmosdb?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-state-azure-cosmosdb.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-state-azure-cosmosdb.md)
* Product: **bot-framework**
* GitHub Login: @ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
@sjciasullo - fyi you can use msbot tool to manage this type of information. See https://github.com/Microsoft/botbuilder-tools/tree/master/packages/MSBot.
