### ISSUE TITLE
Edge

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#249]
When I'm using the Azure portal in the Edge browser, Slack validation doesn't work. When I click save after modifying the landing page URL field, it's supposed to open a new browser tab where I can authorize access to my account. In Edge, it opens a new tab but it's blank. It seems whatever web action it tries to take doesn't work in Edge. I have tried clearing my browsing data but that doesn't affect it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e38b3d9f-a7c8-18d6-3fca-db1be46dff14
* Version Independent ID: 328f6bde-8645-5fbd-fb10-55aeef61e0c5
* Content: [Connect a bot to Slack - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@v-kydela - does it work in other browsers?

**Comment by v-kydela** [comment]
@Kaiqb - Yes it does

**Comment by v-kydela** [comment]
@Kaiqb - May I ask why you closed this issue?
