### ISSUE TITLE
Redirect URL

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#250]
This guide says to set the redirect URL to https://slack.botframework.com which itself redirects to https://bots.botframework.com/. Is there a different URL we should be telling people to use, since this one seems to be deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e38b3d9f-a7c8-18d6-3fca-db1be46dff14
* Version Independent ID: 328f6bde-8645-5fbd-fb10-55aeef61e0c5
* Content: [Connect a bot to Slack - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
Sent this issue to the team for investigation.

**Comment by sandtemp01** [comment]
After following all steps and post authentication by other slack user, user is redirected to https://bots.botframework.com/ where it is mentioned "The Bot Directory is no longer accepting new submissions. Add your bot to the Bing channel so users will not only be able to find it, but chat with it too" . Issue on stackoverflow: [https://stackoverflow.com/questions/53006327/add-to-slack-ms-bot-framework-he-bot-directory-is-no-longer-accepting-new-su](https://stackoverflow.com/questions/53006327/add-to-slack-ms-bot-framework-he-bot-directory-is-no-longer-accepting-new-su)
