### ISSUE TITLE
Landing Page URL

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#251]
Does anyone know what the purpose of the Landing Page URL is? Where and how would a user get linked to that URL? I think we'd expect it to be when an "Add to Slack" button is used, but that uses the redirect URL from the Slack portal and ignores the Landing Page URL from the Azure portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e38b3d9f-a7c8-18d6-3fca-db1be46dff14
* Version Independent ID: 328f6bde-8645-5fbd-fb10-55aeef61e0c5
* Content: [Connect a bot to Slack - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by vlytvynchuk** [comment]
+1
I tried to use Landing Page URL parameter, but it looks like Slack still uses redirect url specified on Slack portal.

**Comment by v-kydela** [comment]
@Kaiqb 
May I ask why this was closed?
