### ISSUE TITLE
Link to Dispatcher tool is wrong

### ISSUE THREAD

**Issue by rahulunlimited** [MicrosoftDocs/bot-docs#252]
Link to the Dispatcher tool is incorrect and returns error 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Integrate multiple LUIS and QnA services with the Dispatch tool - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csaddref%2Ccsbotconfig)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by JonathanFingold** [comment]
They reorganized their repo recently. I'll update the link. Expect the fix to be live early next week.
