### ISSUE TITLE
ConversationState returns null for state

### ISSUE THREAD

**Issue by rahulunlimited** [MicrosoftDocs/bot-docs#253]
The statement below does not return a state.
var state = ConversationState&lt;Dictionary&lt;string, object&gt;&gt;.Get(context);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Using LUIS for Language Understanding - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-demak**

**Comment by rahulunlimited** [comment]
Issue resolved. Had to add the following line in the ConfigureServices
options.Middleware.Add(new ConversationState<ConversationInfo>(storage));

**Comment by arashaga** [comment]
How can we test this app using the emulator? I get and error that the message could not be sent. Also, what should the end point be? the local host or the Microsoft?
