### ISSUE TITLE
timeout nodejs example

### ISSUE THREAD

**Issue by vivekjainAco** [MicrosoftDocs/bot-docs#255]
I am so unhappy with the documentations sometime, I would like to see the same heading under nodejs too. but they are not equal. It was written somewhere that bot development supports both nodejs and C# equally. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da604d3a-5623-8092-9d4e-774177748d73
* Version Independent ID: ee9da6a5-2b55-d309-4a3a-b619583eeb3a
* Content: [Send proactive messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-proactive-messages?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-proactive-messages.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-proactive-messages.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
The are differences between C# and Nodjs in the SDK v3 version. In SDK v4, we've attempted to address that.
