### ISSUE TITLE
LUDown link is not functioning.

### ISSUE THREAD

**Issue by sharatsc** [MicrosoftDocs/bot-docs#256]
https://github.com/Microsoft/botbuilder-tools/tree/master/ludown shows a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eac19e28-e37b-1496-4758-1b1638c311db
* Version Independent ID: 10df3cfc-fcec-411b-5d6d-796883bfb773
* Content: [Create bots with Azure CLi - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tools-az-cli?view=azure-bot-service-3.0)
* Content Source: [articles/bot-builder-tools-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tools-az-cli.md)
* Product: **bot-framework**
* GitHub Login: @matthewshim-ms
* Microsoft Alias: **v-shimma**

**Comment by JonathanFingold** [comment]
It was moved in their repo: https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Chatdown

We'll be updating our links early next week.
