### ISSUE TITLE
Code sample missing for creation of Cosmos DB storage provider (Javacript)

### ISSUE THREAD

**Issue by MarekLani** [MicrosoftDocs/bot-docs#260]
Please add code snippet showing how to create CosmosDB storage provider 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b752c3-6cc6-58f7-29cf-d9a122bd854e
* Version Independent ID: 2484117e-596e-21d2-aabe-3506b2602ac0
* Content: [Create middleware using Cosmos DB - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-cosmos-middleware?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/v4sdk/bot-builder-howto-cosmos-middleware.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-cosmos-middleware.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by IntVoid** [comment]
Code samples have been added and the article has been updated.
