### ISSUE TITLE
doesn't work if app id and password are not blank

### ISSUE THREAD

**Issue by cwying817** [MicrosoftDocs/bot-docs#264]
when i replace APP_ID and APP_PASSWORD with my own pair, error msg is shown. It works fine if app ID and password remain blank. 
[20:49:43]-&gt;message hi
[20:49:44]POST 401 directline.postActivity 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a20df2-727c-1afd-2b87-836ea1ea4f7a
* Version Independent ID: 157fc262-fb1f-f12d-0890-e90119feb444
* Content: [Create a bot using Bot Builder SDK for Python - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/python/bot-builder-python-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/python/bot-builder-python-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by Kaiqb** [comment]
@cwying817 - Python SDK is still in development. If you run into issues, please post your question on Stackoverflow (https://stackoverflow.com/questions/tagged/botframework)
