### ISSUE TITLE
Exception: There was an error deserializing the object of type Microsoft.MT.MDistributor.V2.TranslateArrayRequest.

### ISSUE THREAD

**Issue by bfayez** [MicrosoftDocs/bot-docs#270]
I am getting the following error when I run the tutorial:

An unhandled exception occurred while processing the request.

            
Exception: There was an error deserializing the object of type Microsoft.MT.MDistributor.V2.TranslateArrayRequest. End element 'From' from namespace '' expected. Found element 'html' from namespace ''. Line 1, position 52.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ab01d4-92a2-3213-7cf4-ae6046ce17de
* Version Independent ID: e7999c0c-77ac-3018-ff2c-11bcd7f51fa6
* Content: [Translate user input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-translation?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-translation.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-translation.md)
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
@bfayez - the translation middleware hasn't been updated in a while. You can look at the translation sample for V4 here: https://github.com/Microsoft/BotBuilder-Samples/tree/v4/csharp_dotnetcore/18.Multi-Lingual-Bot
