### ISSUE TITLE
Workaround for VS2017 does not work

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/bot-docs#273]
I tried to 'Debug a Consumption plan C# Functions bot' with Visual Studio 2017 with no success. I think the documentation is missing a point or the tool chain has changed.

Steps I did

 - download my Azure Function Bot and unzip it.
 - download messages.csproj and put into the messages folder

When I run `dotnet restore` I get:

```
C:\Program Files\dotnet\sdk\2.1.402\NuGet.targets(114,5): warning : Kein wiederherzustellendes Projekt gefunden! [C:\Use
rs\sschoof\Source\Repos\dgHelperFunction\Bot.sln]
```

(the german means: "no project to restore found")

Opening the project in VS 2017 and add the project to the sln does also not help.

If I run the `debughost.cmd` I get compile errors for missing the Micrsoft.Bot Namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3691ca29-1a48-7842-8536-5f86d5ef0908
* Version Independent ID: 08ea18f3-3fe9-14a8-d08a-6bbc2b33b42d
* Content: [Debug a bot built using Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-bot?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-debug-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-debug-bot.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Tempest1000** [comment]
For the C# Functions bot, on Visual Studio 2017 15.8 I tried your workaround and received this error while trying to run debughost.cmd and received this error:

````
'func' is not recognized as an internal or external command,
operable program or batch file.
----------------------------------------------------------------------
To fetch your bot service settings run the following command:
    func azure functionapp fetch-app-settings [YOUR_BOT_SERVICE_NAME]
----------------------------------------------------------------------
````

**Comment by Tempest1000** [comment]
Ok, that worked, this can be closed.

**Comment by StefanSchoof** [comment]
My project still is still not working. Can you explain how you restore the nuget packages?

**Comment by Kaiqb** [comment]
@StefanSchoof - you can the link below to report this issue to the support team. https://stackoverflow.com/questions/tagged/botframework

**Comment by StefanSchoof** [comment]
I created a question: https://stackoverflow.com/questions/52474528
