### ISSUE TITLE
Error Bot Framework

### ISSUE THREAD

**Issue by Skyscalesystems** [MicrosoftDocs/bot-docs#275]
I’m using Azure subscription and created a chat bot using same. But currently, I’m having trouble chatting using it. The bot is created using Visual studio using Bot framework and published to Azure. https://yourbotname.azurewebsites.net/ is my messaging end-point URL. I made bot channel registration for the same application and used the bot api endpoint with api/messages as end-point for it. Updated web config file with generated app ID and password and published. But when I try testing with web chat in Azure it is error: Sorry, my bot code is having an issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your bot to Azure - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-3.0)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
@Skyscalesystems - please report the issue to our support team. See https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-links-help?view=azure-bot-service-3.0, details.
