### ISSUE TITLE
Access denied for KB

### ISSUE THREAD

**Issue by praveenrengarajan** [MicrosoftDocs/bot-docs#278]
After I published KB and got KB id, and using KB subscription key from Azure. I'm trying to create dispatch to Luis (which is in another account). Am getting  "Access denied Error (The remote server returned an error: (401) Access Denied. )" for Request URL: https://westus.api.cognitive.microsoft.com/qnamaker/v4.0/knowledgebases/xxxx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Integrate multiple LUIS and QnA services with the Dispatch tool - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csaddref%2Ccsbotconfig#additional-resources)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
@praveenrengarajan - please report it to the QnA support team https://stackoverflow.com/questions/tagged/QnAMaker
