### ISSUE TITLE
Typo in the Webhooks section

### ISSUE THREAD

**Issue by blueelvis** [MicrosoftDocs/bot-docs#280]
One of the Subscription Fields should be "messaging_optins" and not "messaging_options".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acb1736e-f822-2374-fc91-60a13567966e
* Version Independent ID: 03a952ae-0752-9aeb-a214-981bbfaf3b91
* Content: [Connect a bot to Facebook Messenger - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-channel-connect-facebook.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-facebook.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **RobStand**

**Comment by Kaiqb** [comment]
@blueelvis - fixed.
