### ISSUE TITLE
Bot Microsoft.Bot.Sample.AadV1Bot not working - Sorry, my bot code is having an issue

### ISSUE THREAD

**Issue by itechVivek** [MicrosoftDocs/bot-docs#281]
I have downloaded the BotBuilder-master Sample from this l[ink](https://github.com/Microsoft/BotBuilder) and follow the below steps to prepare solution using this [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0)
- Created  Web App Bot App in Micosoft Azure
- Register an application in Azure AD (with help of this [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0#register-an-application-in-azure-ad))
- Register your Azure AD application with your bot (using this [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0#to-register-an-azure-ad-v1-application))
- Prepare the bot sample code (using this [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0#prepare-the-bot-sample-code))
- Set the  ConnectionName, MicrosoftAppId, and MicosoftAppPassword from Bot Settings
- Deploy the Bot to Bot Site

Bot is working as expected in Bot Emulator but It is not Working in both Azure Test in Web Chat and Skype as shown in below image -  **Sorry, my bot code is having an issue**
![image](https://user-images.githubusercontent.com/18301577/45694520-0ab8f600-bb7d-11e8-8339-7e222a729bef.png)

Please help me to find which step is missing to run bot on Azure Web chat and Skype

Thanks

**Comment by Kaiqb** [comment]
@itechedit - Please report this to our support team. https://stackoverflow.com/questions/tagged/botframework.
