### ISSUE TITLE
Typographical error

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/bot-docs#282]
I'm guessing the phrase "do the following for the specific type of type you have" should be "do the following for the specific type of **bot** you have"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1c84393-ea23-98d1-0392-b8679d02982b
* Version Independent ID: 32af546a-4848-4755-9a69-2887e23b7658
* Content: [Build a bot with the Azure online code editor - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-online-code-editor?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-build-online-code-editor.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-build-online-code-editor.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
@EddieLotter - this has been fixed. thanks for reporting.
