### ISSUE TITLE
Typographical error

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/bot-docs#283]
I suspect the section title
&gt; Connect to LUIS an QnA maker services from the CLI
should be
&gt; Connect to LUIS **and** QnA maker services from the CLI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e258c266-773e-1e1f-7edf-cec09957ee8b
* Version Independent ID: 594cf0da-f103-7a89-afaa-38055e1f6921
* Content: [Create bots with Botbuilder Templates - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-create-templates?view=azure-bot-service-3.0#connect-to-luis-an-qna-maker-services-from-the-cli)
* Content Source: [articles/bot-builder-create-templates.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-create-templates.md)
* Product: **bot-framework**
* GitHub Login: @matthewshim-ms
* Microsoft Alias: **v-shimma**

**Comment by Kaiqb** [comment]
@EddieLotter - updated content will be released next week.
