### ISSUE TITLE
Where can I find channel specific data information, when it comes to Skype channel

### ISSUE THREAD

**Issue by timkernighan** [MicrosoftDocs/bot-docs#287]
I left the detailed information here https://stackoverflow.com/questions/52405081/no-channeldata-except-message-text-while-receiving-incoming-message-from-skype-i/52411209#52411209

When I receive the channel data from Skype there is only message text and nothing more. I need at least a user guid to know who to answer. Where can I find this information?

**Comment by JonathanFingold** [comment]
@timkernighan Which article is missing this information, and which language are you developing in? Does the activity's [**from** field](https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-activity/botframework-activity.md#from) have the information you are looking for?

**Comment by timkernighan** [comment]
@JonathanFingold Yes, it is. Sorry.
