### ISSUE TITLE
There is no samples-final folder in the git repository as it states above

### ISSUE THREAD

**Issue by jjgriff93** [MicrosoftDocs/bot-docs#288]
Can't find any v4 examples and `cd botbuilder-dotnet\samples-final` leads nowhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d94889fb-62e2-1f01-d129-866a423986e3
* Version Independent ID: 57102de8-4f11-75c0-8f58-5377374b6b47
* Content: [Sample bots for Bot Builder SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-samples?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-samples.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-samples.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by IntVoid** [comment]
The link is now pointing to the correct repo.
