### ISSUE TITLE
QNA Maker sample link is broken

### ISSUE THREAD

**Issue by jjgriff93** [MicrosoftDocs/bot-docs#290]
https://aka.ms/qna-cs-bot-sample leads nowhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
The offending aka link was removed, and the link in the doc has been fixed.
