### ISSUE TITLE
BotHandle Validation

### ISSUE THREAD

**Issue by cristiag** [MicrosoftDocs/bot-docs#292]
[ I have found that if at the step of Subscribe to Bot Events from the "Connect a bot to Slack" the user does not match exactly the name of the bothandle "Crneguleslack" versus "CrneguleSlack" the test still results in a Succesfful Verification. Evern if that happens the bot will not work on the slack side.  Once you go back and change "/Events/Crneguleslack" to "/Events/CrneguleSlack" the bot starts to work. 
 The easy workaround would be to add to the documentation extra information for the users.
 In section Subscribe to Bot Events Step 3. Subscribe to Bot Events
 In Request URL, enter this URL, but replace {YourBotHandle} with your bot handle. https://slack.botframework.com/api/Events/{YourBotHandle}
 
 to 
 In Request URL, enter this URL, but replace {YourBotHandle} with your bot handle. https://slack.botframework.com/api/Events/{YourBotHandle}. Pay attention the {YourBotHandle} needs to be an exact match with the one you took from your bot. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e38b3d9f-a7c8-18d6-3fca-db1be46dff14
* Version Independent ID: 328f6bde-8645-5fbd-fb10-55aeef61e0c5
* Content: [Connect a bot to Slack - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0#subscribe-to-bot-events)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
This article was recently updated. There is now this tip in the section that you mentioned:
>Your bot handle is the name of your bot. To find a bot's handle, visit https://dev.botframework.com/bots, choose a bot, and record the name of the bot.

If this is not sufficient, please reopen this issue.
