### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by IuriiD** [MicrosoftDocs/bot-docs#293]
Hi! Sorry but the link to github repo in the paragraph "Sample code" (https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-proactiveMessages) seems to be not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a43a9bfa-a69a-ffb2-31a6-d06d78517671
* Version Independent ID: 6bcbbcbf-79f2-9b81-7d03-b9bd8d6286a1
* Content: [Send proactive messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-proactive-messages?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-proactive-messages.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-proactive-messages.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
@IuriiD - v3 samples are here: https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/Node/core-proactiveMessages. We'll be updating the docs to point to the correct location.
