### ISSUE TITLE
Add code to send the message actually as well

### ISSUE THREAD

**Issue by blueelvis** [MicrosoftDocs/bot-docs#295]
In the "Send An Adaptive Card" section, the code is there to create an adaptive card. But, please add the last line to actually send the msg as well with something like - "session.send(msg);" like you have in previous above examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed5a1c8d-c61b-4130-1ecb-e25d7b8cc4ad
* Version Independent ID: ba796614-7173-b45f-f9eb-6a3c3fe55b09
* Content: [Add rich card attachments to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-rich-cards?view=azure-bot-service-3.0#send-an-adaptive-card)
* Content Source: [articles/nodejs/bot-builder-nodejs-send-rich-cards.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-send-rich-cards.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by ivorb** [comment]
Hi @blueelvis are you unable to send the message in the same way as the other examples? The message should be able to send regardless of the content type, but if that's failing we will need to find out why.

Additionally, our v4sdk provides a richer experience and has updated docs if you'd like to try that out!

**Comment by blueelvis** [comment]
Hey @ivorb !

I am able to send the message but this issue is to enhance the clarity of the documentation. I have created a PR as well over here for this change -- https://github.com/MicrosoftDocs/bot-docs/pull/358

Let me know what you think on this.

Also, is there any good comparison doc for v3 vs v4? We are actually developing a bot for production use but since v4 is in preview, what would you suggest on this?
