### ISSUE TITLE
How does Bot-To-Human handoff work here ? Is it part of Virtual Assistant template ?

### ISSUE THREAD

**Issue by technoprax** [MicrosoftDocs/bot-docs#297]
How does Bot-To-Human handoff work here ? Is it part of Virtual Assistant template ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7338c62d-fdb3-5177-cf36-d37398c1d687
* Version Independent ID: c5cac0e9-fb71-6e2c-11df-5e940fd80fc8
* Content: [Virtual Assistant Overview - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-virtual-assistant-introduction?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-virtual-assistant-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-virtual-assistant-introduction.md)
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by Kaiqb** [comment]
Adding @darrenj to address the question.

**Comment by darrenj** [comment]
Hi,

This isn't something we've put into the template at this time. It's on the list as a common scenario and we offer some guidance in the docs: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-handoff-human?view=azure-bot-service-4.0

The enterprise template provides a simple dialog hook for an escalation where you could then connect up to your human hand-off capability but nothing beyond that. If your after something specific that we could invest in to help you and broad scenarios please go ahead and raise an issue on https://github.com/microsoft/ai and we'll take a look and get on our backlog!

**Comment by Kaiqb** [comment]
Closing for now, feel free to open it if needed.
