### ISSUE TITLE
Enterprise Bot Template deployment fails

### ISSUE THREAD

**Issue by cloudguy-pro** [MicrosoftDocs/bot-docs#298]
Hi, If I try to run the command below I get an error:

`msbot clone services --name "SB_EnterpriseBot" --luisAuthoringKey "YOUR_AUTHORING_KEY" --folder "DeploymentScripts\msbotClone" --location "westus"`

This is the error message I get. 
**ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again.**

I already had this in the past when I wanted to create a bot using the **az bot create** command is this still not fixed?

**Comment by Kaiqb** [comment]
@darrenj - can you help?

**Comment by darrenj** [comment]
Yes. Happy to. Can you run it again with the --verbose command and let us know? Also feel free to raise an issue on https://github.com/Microsoft/AI/

**Comment by cloudguy-pro** [comment]
Here you go:

msbot clone services --name "SB_EnterpriseBot" --luisAuthoringKey "eea97ba4823748f683cff09a40a8664d" --folder "DeploymentScripts\msbotClone" --location "westeurope" --verbose
[msbot] The following services will be created by this operation:
 Service                                 Location            SKU                 Resource Group
 Azure App Site Plan                     westeurope          S1                  SB_EnterpriseBot
 Azure AppInsights Service               West Europe         F0                  SB_EnterpriseBot
 Azure Blob Storage Service              westeurope          Standard_LRS        SB_EnterpriseBot
 Azure Bot Service Registration          Global                                  SB_EnterpriseBot
 Azure CosmosDB Service                  westeurope          1 write region      SB_EnterpriseBot
 Azure LUIS Cognitive Service            westeurope          S0                  SB_EnterpriseBot
 Azure LUIS Cognitive Service            westeurope          S0                  SB_EnterpriseBot
 (Dispatch)
 Azure QnA Maker Service                 westus              S0                  SB_EnterpriseBot
 Azure Search Service                    westeurope          Standard            SB_EnterpriseBot
 Azure WebApp Service (Bot)              westeurope                              SB_EnterpriseBot
 Azure WebApp Service (QnA)              westeurope                              SB_EnterpriseBot
Would you like to perform this operation? [y/n]y
[msbot] Checking az botservice version
[msbot] az -v
[msbot] Fetching subscription account
[msbot] az account show
[msbot] Creating resources in subscription: SBI-MVP-AzureSubscription c84063d6-342e-432b-9d82-62fdff45ae45
[msbot] Creating Azure group [SB_EnterpriseBot]
[msbot] az group create -g SB_EnterpriseBot -l westeurope
[msbot] Creating Azure Bot Service [SB_EnterpriseBot]
[msbot] az bot create -g SB_EnterpriseBot --name SB_EnterpriseBot --kind webapp --location westeurope --insights-location "West Europe"  --version v4
[msbot] [az bot] To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code C2Y6LR2HT to authenticate.

[msbot] az bot create -g SB_EnterpriseBot --name SB_EnterpriseBot --kind webapp --location westeurope --insights-location "West Europe"  --version v4 exit code: 1
WARNING: The behavior of this command has been altered by the following extension: botservice
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code C2Y6LR2HT to authenticate.
ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again.

[msbot] Usage: msbot clone services [options]

allows you to clone all of the services a bot into a new azure resource group

Options:

  -n, --name <name>                            name of new bot
  -f, --folder <folder>                        path to folder containing exported resources
  -l, --location <location>                    location to create the bot service in (westus, ...)
  --luisAuthoringKey <luisAuthoringKey>        authoring key from the appropriate luisAuthoringRegion for luis resources
  --luisAuthoringRegion <luisAuthoringRegion>  (OPTIONAL) [westus|westeurope|australiaeast] authoring region to put LUIS models into (default is based on location)
  --luisPublishRegion <luisRegion>             (OPTIONAL) region to publish LUIS models to (default fallback is based location || luisAuthoringRegion)
  --subscriptionId <subscriptionId>            (OPTIONAL) Azure subscriptionId to clone bot to, if not passed then current az account will be used
  --insightsRegion <insightsRegion>            (OPTIONAL) region to create appInsights account in (default is based on location)
  --groupName <groupName>                      (OPTIONAL) groupName for cloned bot, if not passed then new bot name will be used for the new group
  --sdkLanguage <sdkLanguage>                  (OPTIONAL) language for bot [Csharp|Node] (Default:CSharp)
  --sdkVersion <sdkVersion>                    (OPTIONAL) SDK version for bot [v3|v4] (Default:v4)
  -q, --quiet                                  minimize output
  --verbose                                    show commands
  -f, --force                                  do not prompt for confirmation
  -h, --help                                   output usage information

[msbot] NOTE: You did not complete clone process.
[msbot] To delete the group and resources run:
[msbot] az group delete -g SB_EnterpriseBot --no-wait

**Comment by darrenj** [comment]
Thanks. Tracking in this bug https://github.com/Microsoft/botbuilder-tools/issues/596

**Comment by Kaiqb** [comment]
@darrenj @cloudguy-pro - closing this issue as this is being tracked in the tools repo.

**Comment by NicuAhmadi** [comment]
I've been struggling with the same issue ... and not resolved yet:

- Originally I got "ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again." 
- As suggested several places, I then added arguments for appId and appSecret.. No luck here as I got a generic error 
- I then created a brand new application manually and retrieved appId and appSecret and made the call using msbot clone services ; I got the following error 
"az bot create ...( remaining of this message ) exit code: 1
WARNING: The behavior of this command has been altered by the following extension: botservice
ERROR: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
- I then tried "az group deployment operation list --name Name -g Name --query "[*].properties.statusMessage" and got the below message 👍 
 [
  {
    "error": {
      "code": "InvalidBotData",
      "message": "Bot is not valid. Errors: Id: Id is already in use.. "
    }
  },
... Any ideas on what to do next? 
One more, to make sure I'm using the right appId, I opened the manifest and grabbed the same ID as it appears in the file..

**Comment by darrenj** [comment]
Perhaps the Bot name you are using already exists somewhere? Try adding something more unique to the name, based on what you’ve shown below I suspect that’s the issue (which we’ll add better tests for)
