### ISSUE TITLE
Please let developers integrate other NLU services like DialogFlow, Wit.ai, Watson etc 

### ISSUE THREAD

**Issue by InsaneNaman** [MicrosoftDocs/bot-docs#300]
It would be great if we can get some official easy way to integrate other services just like you are doing for LUIS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b9de9f8-0d16-eaa5-7287-0a713278fc01
* Version Independent ID: 5a19dadd-5b1c-13d1-2a3c-1e389d2b4725
* Content: [Language Understanding - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-luis?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-luis.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
Feedback noted.
