### ISSUE TITLE
Can't download above shared Sample i.e. throw  404 error

### ISSUE THREAD

**Issue by manoj1201** [MicrosoftDocs/bot-docs#302]
Above shared solution i.e. C# Auth Graph redirect to 404, Please correct this path to download the solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d80e0b-f1b7-175b-128d-0fb12f17ae36
* Version Independent ID: 1ed9006a-bf0b-9aaa-d180-9d2cb0c09524
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-tutorial-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tutorial-authentication.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **JonathanFingold**

**Comment by Kaiqb** [comment]
@manoj1201 - with the v4 sdk release, the samples have moved to a new location. You can find them here: https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples. We are updating the links in the docs.

**Comment by manoj1201** [comment]
It seems like above shared 3 solution i.e. "C# Auth" "C# Auth Graph" "Node Auth" has moved to new location i.e. https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples
