### ISSUE TITLE
Issues with Bot Publishing

### ISSUE THREAD

**Issue by andrewchungxam** [MicrosoftDocs/bot-docs#304]
There seems to be issues with Bot Publishing. ie.: the steps described in this document to publish from Visual Studio: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0

Does not work with the "hello world" .NET Bot Builder Echo Bot described in this document:
https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0 (which in turn uses this template:
https://botbuilder.myget.org/feed/aitemplates/package/vsix/BotBuilderV4.fbe0fc50-a6f1-4500-82a2-189314b7bea2)

**Comment by Kaiqb** [comment]
@andrewchungxam - can you describe what kind of errors you are getting?

**Comment by Kaiqb** [comment]
@andrewchungxam - there is a bug in the VSIX template that is being fixed. That should address the issue you were having.

**Comment by andrewchungxam** [comment]
Thank you Kaiqb!

**Comment by andrewchungxam** [comment]
Do you know the nature of the bug? or a link to it? i'd love to investigate - see what it is in case I run into something similar in the future.
