### ISSUE TITLE
Word reuse

### ISSUE THREAD

**Issue by BillStrait** [MicrosoftDocs/bot-docs#305]
"These ConversationUpdate Activities are easily distinguished these because the sender id and the recipient id will be the same for the bot joining." The second 'these' in this sentence is a mistake. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf8a24b-7029-247b-3c5c-3902befe0ccf
* Version Independent ID: bcd01444-d332-29e6-2b81-5558bb2d576b
* Content: [Bot Activity in the Bot Builder SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by Kaiqb** [comment]
@BillStrait - fixed
