### ISSUE TITLE
Sample links broken

### ISSUE THREAD

**Issue by Vavro** [MicrosoftDocs/bot-docs#307]
the links http://aka.ms/v4csharpauth  http://aka.ms/v4csharpauthgraph http://aka.ms/v4cnodeauth are all broken
i assume the last one should point to https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/24.bot-authentication-msgraph

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d80e0b-f1b7-175b-128d-0fb12f17ae36
* Version Independent ID: 1ed9006a-bf0b-9aaa-d180-9d2cb0c09524
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-tutorial-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tutorial-authentication.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **JonathanFingold**

**Comment by JonathanFingold** [comment]
@Vavro , We are in the process of fixing the links. Samples 18 and 24 cover authentication. These links should be fixed soon. Sorry for the inconvenience.
