### ISSUE TITLE
Link to .NET SDK3 reference goes to API browser home page

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/bot-docs#308]
Currently points to https://docs.microsoft.com/en-us/dotnet/api/?view=botbuilder-3.12.2.4

The views currently available are https://docs.microsoft.com/en-us/dotnet/api/?view=botbuilder-dotnet-stable
https://docs.microsoft.com/en-us/dotnet/api/?view=botbuilder-dotnet-preview, both of which appear to be for the V4 SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35d1244-e389-9ee3-8eb8-18610bc81d56
* Version Independent ID: d41d1c45-fed6-80f0-189a-2c5c051dbb25
* Content: [Manage bot using Bot Builder tools - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tools?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-tools.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tools.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
@fowl2 , this page relates to the v4 SDK. The CLI tools do support the v3 SDK.

Where on the page is this particular link? What is the link text?

**Comment by JonathanFingold** [comment]
@fowl2 , Yes, the navigation/TOC link to the .NET SDK v3 is broken, and we're looking into it.

**Comment by Kaiqb** [comment]
@JonathanFingold - is this issue fixed?

**Comment by JonathanFingold** [comment]
@Kaiqb Partially, The link now takes you to the [.NET API Browser](https://docs.microsoft.com/en-us/dotnet/api/?term=botbuilder), but that leaves one having to hunt for the correct namesapace and version.

**Comment by Kaiqb** [comment]
Fixed.
