### ISSUE TITLE
"Start your bot" not descriptive enough

### ISSUE THREAD

**Issue by martinkearn** [MicrosoftDocs/bot-docs#309]
For someone who is new to Node or TypeScript saying "Change directories to the one created for your bot, and start it" is nowhere near descriptive enough. I would expect at least high level steps for starting both Node and Typescript templates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaad3f2-75c5-e958-4734-8925d03d95c6
* Version Independent ID: 8d98b390-5368-1fa4-8cce-3b0cff252eaa
* Content: [Create a bot using Bot Builder SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by josefaidt** [comment]
Until the documentation gets updated, you'll want to use the terminal in the projects directory, and type `npm start`

**Comment by JMyner** [comment]
https://github.com/MicrosoftDocs/bot-docs/pull/326

**Comment by v-kydela** [comment]
My thoughts exactly. "Start what? How?" In V3 there was an app.js and you run it with `node app` which is different from `npm start`

**Comment by IntVoid** [comment]
This has been resolved in the next publish.
