### ISSUE TITLE
Roller Skill sample

### ISSUE THREAD

**Issue by Toemsel** [MicrosoftDocs/bot-docs#310]
Dead link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab32bd66-4026-877f-aaac-15d8f050ad4b
* Version Independent ID: 4f0e5bc2-2e95-9765-5d55-d546c01548f5
* Content: [Add speech to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-text-to-speech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-text-to-speech.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@Toemsel - with the release of SDK v4, old samples are here: https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp

**Comment by Kaiqb** [comment]
Fixed.
