### ISSUE TITLE
Wrong application options for LuisRecognizer [Javascript]

### ISSUE THREAD

**Issue by MarekLani** [MicrosoftDocs/bot-docs#312]
There is bug in sample, to create LuisRecognizer, there should be used applicationEndpoint property instead of azureRegion as stated in sample above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Integrate multiple LUIS and QnA services with the Dispatch tool - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by MarekLani** [comment]
Sorry just endpoint not applicationEndpoint

**Comment by DivyaNarayana** [comment]
Hi, I had a doubt on how will i fetch entities from LuisServices which is fetched into result.
result.Entities gives all the data i just want the entities. So can we use Entities.Value or item?

**Comment by JonathanFingold** [comment]
Unfortunately, the [Node.js sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/14.nlp-with-dispatch) has bugs in it. I've removed references it from this article for now. I will add them back in once the sample is updated.
