### ISSUE TITLE
How storage keys are generated.

### ISSUE THREAD

**Issue by martinlarosa** [MicrosoftDocs/bot-docs#316]
I believe the description of how storage keys are generated is inverted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0846e672-f3f3-844d-ec78-6e401f5120dc
* Version Independent ID: 1ab740e5-8248-af3e-6bf9-063d1bb418e9
* Content: [Dialog State - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-state?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-dialog-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-state.md)
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by Kaiqb** [comment]
Fixed
