### ISSUE TITLE
GitHub URL Reference invalid

### ISSUE THREAD

**Issue by rcc-peters** [MicrosoftDocs/bot-docs#322]
URL to Basic Multi Dialog sample returns a 404 error:

https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-BasicMultiDialog

**Comment by JonathanFingold** [comment]
@rcc-peters Links to the v4 samples should be good now. If you notice any, please use the feedback feature so we know which article has the issue.
