### ISSUE TITLE
Confusing diction for Note on LUIS for Basic Bot

### ISSUE THREAD

**Issue by josefaidt** [MicrosoftDocs/bot-docs#323]
"For a Basic bot, you'll need to a LUIS language model."
Connect? Integrate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaad3f2-75c5-e958-4734-8925d03d95c6
* Version Independent ID: 8d98b390-5368-1fa4-8cce-3b0cff252eaa
* Content: [Create a bot using Bot Builder SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by josefaidt** [comment]
![image](https://user-images.githubusercontent.com/5033303/46211791-079ad400-c2fa-11e8-9e78-bf3647585151.png)

**Comment by Kaiqb** [comment]
Fixed.
