### ISSUE TITLE
Version 3 Template for Visual Studio No Longer Available

### ISSUE THREAD

**Issue by jwood803** [MicrosoftDocs/bot-docs#325]
Going to [the link](https://marketplace.visualstudio.com/items?itemName=BotBuilder.BotBuilderV3) gives an error page saying that the item can't be found.

With v4 now being generally available, is this intended? Or should this page still exist?

**Comment by Kaiqb** [comment]
@jwood803 - The removal of VSIX for SDK v3 was intentional. We want customers to use SDK v4 for building bots.
