### ISSUE TITLE
add luis to bot doesn't work

### ISSUE THREAD

**Issue by amthomas46** [MicrosoftDocs/bot-docs#327]
Following all instructions, these lines error

```csharp
// Call LUIS recognizer
                var result = this.Recognizer.RecognizeAsync(context, System.Threading.CancellationToken.None);
                
                var topIntent = result?.GetTopScoringIntent();
```
the second "result" errors. if you make it
```csharp
var result = await Recognizer.RecognizeAsync(stepContext.Context, cancellationToken);
```
it runs, but it gets and exception `Operation returned an invalid status code 'NotFound'`.

Please assist and also update the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Using LUIS for Language Understanding - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by amthomas46** [comment]
I got it to work by adding the await and updating the endpoint to end at "....Microsoft.com/" . Previously, you had to go all the way, including luis/v2/apps/, so you might want to note exactly where the endpoint ends for future.

**Comment by ADefWebserver** [comment]
I can confirm that the fix by @amthomas46 to no longer add "/luis/v2/apps/" works.

**Comment by CathyQian** [comment]
This document will be updated soon.

**Comment by JonathanFingold** [comment]
This topic has been updated. If you find other issues, please open a new issue.
