### ISSUE TITLE
Missing dependency: git

### ISSUE THREAD

**Issue by kathywl** [MicrosoftDocs/bot-docs#328]
As a new employee running on a fresh laptop, I noticed there is a missing dependency: git. 
If you don't have git installed, you will get an error when running this:
npm install -g generator-botbuilder

**Comment by JonathanFingold** [comment]
@kathywl , Please link to the article you noticed this in, and we'll update it.

**Comment by kathywl** [comment]
https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0

**Comment by JonathanFingold** [comment]
Thanks, I've added **git** to the list of prerequisites. The fix should go live in a few days.
