### ISSUE TITLE
Start your bot -> not descriptive enough

### ISSUE THREAD

**Issue by kathywl** [MicrosoftDocs/bot-docs#329]
"Start your bot
Change directories to the one created for your bot, and start it. At this point, your bot is running locally."

These instructions are lacking.
Something like this would be better:

In Powershell/Bash, change directories to the one created for your bot.
Run:
npm start

[now start the Bot Emulator, etc.]

**Comment by IntVoid** [comment]
I have this resolved and added to the appropriate article. It'll be in the next publish.
