### ISSUE TITLE
Missing await on EchoBot

### ISSUE THREAD

**Issue by ladeak** [MicrosoftDocs/bot-docs#330]
```csharp
var result = this.Recognizer.RecognizeAsync(context, ystem.Threading.CancellationToken.None);
var topIntent = result?.GetTopScoringIntent();
```

Missing an await on 'result'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Using LUIS for Language Understanding - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
Being taken care of, thanks for reporting!

**Comment by JonathanFingold** [comment]
This topic has been updated. If you find other issues, please open a new issue.
