### ISSUE TITLE
Component dialogs link

### ISSUE THREAD

**Issue by ladeak** [MicrosoftDocs/bot-docs#331]
Component dialogs link seems to point a page still documenting the 'preview' version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6606cce-8a4e-587b-ded2-bd775a4cd7c7
* Version Independent ID: 6f637bca-8cc0-a526-4cbd-9c5f9f94ca2b
* Content: [Manage a complex conversation flow with dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by IntVoid** [comment]
This has been fixed in our next publish.
