### ISSUE TITLE
Getting error while running msbot clone services

### ISSUE THREAD

**Issue by virajpangam** [MicrosoftDocs/bot-docs#332]
I am getting the following error while running 
msbot clone services --name "MyBotName" --luisAuthoringKey "myauthoringkey" --folder "DeploymentScripts\msbotClone" --location "westus"

ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by darrenj** [comment]
Hi. Could you share the error please?

**Comment by virajpangam** [comment]
> Hi. Could you share the error please?

ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again.

**Comment by virajpangam** [comment]
> Thanks. Looks like the same issue as: [Microsoft/botbuilder-tools#596](https://github.com/Microsoft/botbuilder-tools/issues/596) Will get back to you early next week. Sent from my 📱
> […](#)
> ________________________________ From: virajpangam <notifications@github.com> Sent: Saturday, September 29, 2018 12:09 pm To: MicrosoftDocs/bot-docs Cc: Darren Jefford; Mention Subject: Re: [MicrosoftDocs/bot-docs] Getting error while running msbot clone services (#332) Hi. Could you share the error please? ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fbot-docs%2Fissues%2F332%23issuecomment-425636910&data=02%7C01%7C%7Caadd6c95313c4e25c86908d625fbfe66%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636738161557981385&sdata=JHIn8bfegemAVlUkvlKnvVES3WbmmR7vnUkknBynC8g%3D&reserved=0>, or mute the thread<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAf93oJM7FTpgNapKBSlKeRng2UCUyBm5ks5uf1TagaJpZM4XAdDZ&data=02%7C01%7C%7Caadd6c95313c4e25c86908d625fbfe66%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636738161557981385&sdata=ZWUKLmPOHeZzr%2BhvPz3SynlrbvirlRiE%2FEXrgTsbutY%3D&reserved=0>.

Thanks Darren.

**Comment by mefree98** [comment]
I am getting this error when trying to run msbot clone services.  It successfully opens the webpage, I authenticate, it accepts, then this error;

az bot create -g Trinity --name Trinity --kind webapp --location westus --insights-location "West US 2"  --version v4 exit code: 1
WARNING: The behavior of this command has been altered by the following extension: botservice
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code (Author has removed code) to authenticate.
ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again.

**Comment by darrenj** [comment]
Hi,

The endpoint that provisions the Application Ids is in preview and has problems in some situations which we are trying to understand further. In the meantime we have provided a workaround (not ideal I know).

- Go to https://apps.dev.microsoft.com/ and create a new Application making note of the ApplicationId and Password/Secret.
- Run `msbot clone services` against but pass the ApplicationId via the `--appId` argument and Secret versus the `--appSecret` argument.

This should move you forward, let me know either way please! I'll get the docs updated now.

**Comment by mefree98** [comment]
Thank you very much for the reply.  I did as you asked and it got much further along in the process but unfortunately did eventually error out again;

Command failed: az cosmosdb create -n trinity -g TrinityERROR: Operation failed with status: 'BadRequest'. Details: DataActivityId: 50425acc-d87b-11e8-9508-5cf370692fd7, Microsoft.Azure.Documents.Common/2.1.0.0

I am getting a bad request error on the CosmosDB create section.

**Comment by darrenj** [comment]
Thanks - I'll get that looked into, one thing to double check it's not a naming collision (we need to add some checks). Could you try again and use trinityNUMBER replacing number with something of your choice just to check it's not a naming issue (haven't seen this particular issue before so thought I'd ask)

**Comment by mefree98** [comment]
Yes I can do that, but to be clear about a couple of items.  First, should I delete out everything that it created in the previous steps it got through to prevent duplication?  Second, do I need to start the project over with a new name, or can I simply change the --name attribute on msbot clone services?

**Comment by darrenj** [comment]
if you change the --name all should be good ;-)

**Comment by mefree98** [comment]
This time it failed even sooner oddly;
Creating Azure Bot Service [TrinityBP]
az bot create -g TrinityBP --name TrinityBP --kind webapp --location westus --insights-location "West US 2"  --version v4 --appid d5dce05d-3532-482d-a782-434d8052315b -p "zyyunSCRV19~-qhFHH138*}" exit code: 1
WARNING: The behavior of this command has been altered by the following extension: botservice
ERROR: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.

**Comment by mefree98** [comment]
So I ran it again without adding the "BP" to the name and it proceeded all the way to the CosmosDB error again.

**Comment by darrenj** [comment]
I perhaps misled you on re-use. Bear with me :) Create a new AppId, try again with a very unique name e.g. Trinity6789 and add --verbose to the end of your msbot clone

**Comment by mefree98** [comment]
Sorry got caught up in meetings the rest of the day, and about to get sucked into more.  So, that said I deleted everything, cleaned everything up and used a new/longer name, and now we have success!

TrinityBP2018.bot created.
Done cloning.

Thank you very much!

**Comment by darrenj** [comment]
Thanks for letting us know, I suspect it's a naming thing causing issues. But this data helps!

**Comment by mefree98** [comment]
No problem at all, thank you for all the help.  One last question and this may be the wrong thread, but, I've fully published this to Azure now but when testing I get an error after the initial "hi" message.  It responds correctly, asks for my name, then crashes after that
![boterror](https://user-images.githubusercontent.com/19614917/47578990-0dd79c80-d908-11e8-812d-99679a78c45e.png)
.  Is this another known issue?

**Comment by mefree98** [comment]
Actually when I click the endpoint URL I see this;

{"query":null,"intents":[],"entities":[]}

**Comment by mefree98** [comment]
Also, the entire chat experience is now different.  I don't get the welcome to bot framework hero card anymore, etc.  Instead I just get this.  I haven't changed anything since last week, other than login to LUIS.AI and find the endpoint URL and click on it.  Any idea what/why this is happening?

![webchat](https://user-images.githubusercontent.com/19614917/47657579-f4785f80-db56-11e8-8693-2dc30427c923.png)

**Comment by darrenj** [comment]
If the endpoint URL response is like you show above the key is working fine. You can put hello on the q parameter to check it resolves to an intent.

As for the second experience, looks like your pointing at the production endpoint in the emulator not the development one. Assume you haven't published your Bot to the Azure resource yet, we don't do this automatically (you can right click in VS and choose the app service we create for you)

**Comment by Kaiqb** [comment]
It seems that issue has been addressed.
