### ISSUE TITLE
Missing NuGet

### ISSUE THREAD

**Issue by mikewiegand** [MicrosoftDocs/bot-docs#333]
Hi
great blog. I used this code and it worked great. I had to also add: Microsoft.Rest.ClientRuntime NuGet package as it was throwing a runtime exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc04415a-5587-3c0c-9447-aee46e5e1928
* Version Independent ID: 1067e35b-07e1-2f47-6bda-d92b024c09d0
* Content: [Create a Direct Line bot and client - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-direct-line?view=azure-bot-service-4.0&tabs=cscreatebot%2Ccsclientapp%2Ccsrunclient)
* Content Source: [articles/v4sdk/bot-builder-howto-direct-line.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-direct-line.md)
* Product: **bot-framework**
* GitHub Login: @v-royhar
* Microsoft Alias: **v-royhar**

**Comment by IntVoid** [comment]
Will be resolved in the next publish.

**Comment by mikewiegand** [comment]
Not resolved. If you follow these instructions they do not work. Plus, after opening a ticket to resolve to ambiguous dependencies, other isssues arise.  Microsoft.Bot.Builder.IBot . Can someone PLEASE fix this blog?
