### ISSUE TITLE
Please share sample link for V3

### ISSUE THREAD

**Issue by manoj1201** [MicrosoftDocs/bot-docs#334]
Dear Team,

Above mentioned AadV1Bot	v3 & AadV2Bot V3 link are broken and not found. Please help to share the exact link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d80e0b-f1b7-175b-128d-0fb12f17ae36
* Version Independent ID: 1ed9006a-bf0b-9aaa-d180-9d2cb0c09524
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0&tabs=csharp&viewFallbackFrom=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-tutorial-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tutorial-authentication.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **JonathanFingold**

**Comment by manoj1201** [comment]
Got sample path :- https://github.com/Microsoft/BotBuilder-V3/tree/master/CSharp/Samples

Please mark as closed.

**Comment by IntVoid** [comment]
This will be resolved in the next publish.
