### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mrameshk** [MicrosoftDocs/bot-docs#336]
Proactive Messages sample (GitHub) seems to be a broken link, anyone knows which is the correct link ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da604d3a-5623-8092-9d4e-774177748d73
* Version Independent ID: ee9da6a5-2b55-d309-4a3a-b619583eeb3a
* Content: [Send proactive messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-proactive-messages?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-proactive-messages.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-proactive-messages.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by iMicknl** [comment]
Are you using V3 or V4? You can find the sample for V3 [here](https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp/core-proactiveMessages). It moved to another branch (v3-sdk-samples), but it looks like the docs aren't updated yet.

**Comment by mrameshk** [comment]
Thank you, i am currently on v3 now.

**Comment by IntVoid** [comment]
This is currently being resolved.

**Comment by IntVoid** [comment]
This will be resolved in the next publish.
