### ISSUE TITLE
Start your bot instructions are lacking.

### ISSUE THREAD

**Issue by kathywl** [MicrosoftDocs/bot-docs#339]
"Start your bot
Change directories to the one created for your bot, and start it. At this point, your bot is running locally."
These instructions are lacking.
Something like this would be better:
In Powershell/Bash, change directories to the one created for your bot.
Run:
npm start
[now start the Bot Emulator, etc.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaad3f2-75c5-e958-4734-8925d03d95c6
* Version Independent ID: 8d98b390-5368-1fa4-8cce-3b0cff252eaa
* Content: [Create a bot using Bot Builder SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by IntVoid** [comment]
This will be resolved in the next publish.
