### ISSUE TITLE
"Endless" questions

### ISSUE THREAD

**Issue by VioletTape** [MicrosoftDocs/bot-docs#342]
What is the recommended way to handle an endless\undfined sequence of questions? 
For instance, I have some sort of decision map an want to guide a user through the map. Every next question depends on an answer from the previous one and the number of questions unknown. So I can't define a list of questions upfront as methods in the code. Rather I'd like to load new question from storage and form new step (dialog?) in the conversation based on gathered information from a user. Of course, there will be resuming of "upper" branches, but it was described quite well in the documentation. Additionally, you can think that every answer has a specific weight that leads to a certain answer, and the whole process can be finished when weight reach critical value (i.e. sequence and a number of questions can't be foreseen). 
Also, questions do not offer a free-form answer (at least for now and for the sake of simplicity)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6606cce-8a4e-587b-ded2-bd775a4cd7c7
* Version Independent ID: 6f637bca-8cc0-a526-4cbd-9c5f9f94ca2b
* Content: [Manage a complex conversation flow with dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
@VioletTape You may need to extend the Dialogs library (still under development) or roll your own version that is closer to a finite state machine. The LUIS recognizer allows you to do some natural language processing on the user's input. The SDK should be more stable after GA, in about a month.

You can also get help from our support team. https://stackoverflow.com/questions/tagged/botframework.

**Comment by JonathanFingold** [comment]
@VioletTape PS, you may be able to use the information in the [Manage complex conversation flows with dialogs](https://docs.microsoft.com/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow?view=azure-bot-service-4.0&tabs=csharp) topic to add looping and branching to your dialogs.
