### ISSUE TITLE
The V3 docs still link to the master branch of the BotBuilder-Samples repo

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#343]
While the master branch of the [BotBuilder-Samples repo](https://github.com/Microsoft/BotBuilder-Samples) used to contain the V3 samples, those samples now have to be accessed on a [different branch](https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples). However, the [V3 docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-3.0) still link to the master branch in the navigation pane under Samples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ffe447d-f0a8-f4b6-d572-ba2c3bba4aab
* Version Independent ID: 6c1d9a6a-4cb3-f404-ce1f-940b443f0e34
* Content: [Azure Bot Service Introduction - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-overview-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-overview-introduction.md)
* Product: **bot-framework**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@v-kydela We're finishing up the process of fixing all the links broken by the repo change. Should be good by the end of the week.

**Comment by v-kydela** [comment]
@Kaiqb - You closed this but I can see it still hasn't been resolved

**Comment by JonathanFingold** [comment]
@v-kydela , Is the broken link the one in the nav bar (TOC) for **samples / samples repo**?

**Comment by v-kydela** [comment]
On this page: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-3.0

There is a Samples > Samples repo button that leads here: https://github.com/Microsoft/BotBuilder-Samples/blob/master/readme.md
