### ISSUE TITLE
SendActivity should be SendActivityAsync

### ISSUE THREAD

**Issue by talon2king** [MicrosoftDocs/bot-docs#347]
I found that when I was using this demo, I had to use SendActivityAsync, not SendActivity to get this working for each case statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Using LUIS for Language Understanding - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
@talon2king There's a code fix in that should be merged later this week.

**Comment by JonathanFingold** [comment]
This topic has been updated. If you find other issues, please open a new issue.
