### ISSUE TITLE
New Project Image Incorrect

### ISSUE THREAD

**Issue by mphacker** [MicrosoftDocs/bot-docs#348]
I installed the latest project templates and when I look at the Bot Framework folder I see two options "Microsoft Bot Builder V4 SDK" and "Bot Builder Echo Bot"   If I choose the first option I get a solution with 2 V4 bot projects.  If I choose the 2nd one I end up with a V3 SDK bot.   This is very confusing at first.    I also have a sub-folder under Bot Framework called Multi-project.  If I go into that I see templates for separate Basic and Echo V4 bots.     Please update the documentation to reflect what a person might actually see if they have been using the bot framework in the past or have installed the new templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Builder SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by mphacker** [comment]
I am also noticed that the Echo Bot template is now creates an EchoBotWithCounter.   This change breaks other pages in the documentation.  The section showing how to Use QnA Maker (https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs) references EchoBot.cs which does not exist in any of the V4 templates.

**Comment by Kaiqb** [comment]
@mphacker - the article you reference above uses the QnA sample. Therefore, it will have different class names etc. 

@vishwacsena - please fix the template issue mentioned above. Thx

**Comment by ivorb** [comment]
Screenshot of it is updated in our docs - if the template changes it will need a new picture, but as of now it's correct.

As for the places that reference EchoBot.cs, we do need updates to match the new template
