### ISSUE TITLE
DialogContainer

### ISSUE THREAD

**Issue by mplogas** [MicrosoftDocs/bot-docs#349]
Text says " To modularize this task, we create a CheckIn class that extends ComponentDialog. " but code says "public class CheckIn : DialogContainer". Type DialogContainer is unknown. What is the DialogContainer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9577ff-cf56-e5de-84c3-bfe10aab5368
* Version Independent ID: b5d62753-f87b-4673-b09b-a5a3fd9360e8
* Content: [Create an integrated set of dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-compositcontrol.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-compositcontrol.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
@mplogas We temporarily removed this topic from the TOC, as there have been some breaking changes since it was last updated. We're hoping to update this topic in the next week or two. The `DialogContainer` class was renamed to `ComponentDialog`.

**Comment by Kaiqb** [comment]
Topic was updated.
