### ISSUE TITLE
V3 docs instruct user to install wrong version of botbuilder

### ISSUE THREAD

**Issue by nyxsys** [MicrosoftDocs/bot-docs#350]
As mentioned in an [issue](https://github.com/Microsoft/botbuilder-js/issues/506) received in the botbuilder-js repo there are instructions in the documentation that are not v3-specific. 

As seen in this [documentation](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-quickstart?view=azure-bot-service-3.0&viewFallbackFrom=azure-bot-service-4.0) `npm install --save botbuilder` should actually be `npm install --save botbuilder@3.13.1` so that the user does not install v4 instead.

**Comment by Kaiqb** [comment]
@nyxsys - the SDK V3 Quickstarts have now been removed. Users should use V4 templates.
