### ISSUE TITLE
REST API new topic creation

### ISSUE THREAD

**Issue by Orimay** [MicrosoftDocs/bot-docs#352]
I am trying to create a new topic with a title using REST API, but have no success. Keep getting error "BadSyntax: Invalid user identity in provided tenant". 

Here is the data I send:

```
{
    "topicName": "Topic Creation Test",
    "members": [
        {
            "id": "a:1slblBK0IwmxqS0DkoXkYEyBLEP_Gk..."
        }
    ],
    "bot": {
        "id": "9e4e1ab2-48fa-4a..."
    },
    "channelData": {
        "tenant": {
            "id": "3547a1dc-9847-49..."
        }
    },
    "isGroup": false,
    "activity": {
        "text": "Hello, world!",
        "type": "message"
    }
}
```

The tenant id I added was recieved from message activity. "Invalid user identity in provided tenant" confuses me, since there are no samples of how to add anything like this to start a new topic. No information regarding channelData to start a new conversation at all.

My goal is to create a new named topic with user, so that I could add more users to it later. Also, the documentation says to use Conversation object to create a new conversation, while it should be (per API response) ConversationParameters.

BTW, id prefixes confuse a lot. I found no place where it has an explaination what are all those "a:", "28:", "29:" etc. It's not clear which ids to use at all. And what aadObjectId is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e47c9b6-a06c-caa8-9b8f-b50fdfa70109
* Version Independent ID: d24d686f-8d14-eb25-9fe9-112df8993ae4
* Content: [API reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@Orimay - please post your question on Stackoverflow so that support team can help: https://stackoverflow.com/questions/tagged/botframework.

**Comment by mark-szabo** [comment]
for everybody else who is searching here for an answer:
- an issue for sure is that the user id you are using is an encrypted id. Have you copied that out from storage explorer? So use an un-encrypted id. It should be a GUID, so something like this: `fd223658-dfd2-5k3s-3bdg-ccdbee6b91cf` If you open a transcript file in Bot Emulator, it will decrypt it for you. 
- aadObjectId is the id of the user in the Azure Active Directory (AAD) tenant. It is a universal id of that user in all systems that use Active Directory authentication.
