### ISSUE TITLE
DatetimePrompt don't resolve natural language in spanish

### ISSUE THREAD

**Issue by VaroJulio** [MicrosoftDocs/bot-docs#353]
I have been testing DateTime Prompts with inputs like "Mañana a las 8pm" or "Mañana" or "Hoy" or "Próximo viernes" and the DateTimePrompts can't get the rigth Date, but when I write inputs in English like "Tomorrow at 8pm", it works. 

Atually, I´m using the BotBuilder V4 preview SDK(4.0.0-preview1.2) (botbluilder, botbuilder-ai, botbuilder-azure, botbuilder-choices, botbuilder-core, botbuilder-dialogs, botbuilder-propmts).

Could you help me, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72538432-fde5-22ab-7997-8a34b11aa24e
* Version Independent ID: c469fa5b-2590-ee16-1491-51b90c069204
* Content: [Prompt users for input using the Dialogs library - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-prompts.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
This sounds like and issue with the SDK itself, or one of the other libraries it relies on. Please log this as an issue in the [botbuilder-js](https://github.com/Microsoft/botbuilder-js/) repo. Help is also available from our support team: https://stackoverflow.com/questions/tagged/botframework.
