### ISSUE TITLE
A FormCanceledException<T> is not sufficiently handled by the Do() method

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#355]
When following the example in [this section](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-formflow?view=azure-bot-service-3.0#handling-quit-and-exceptions), a quit command will throw an exception that is successfully be caught and handled by the catch block, but an unhandled FormCanceledException<T> is also thrown. It seems the more effective way of responding to a quit command is with Chain.Catch().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46424ef9-9af9-55a1-207a-4202ef8f1af3
* Version Independent ID: cad8ef24-51c5-e32b-6af8-cb3a3fe7b551
* Content: [Basic features of FormFlow - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-formflow?view=azure-bot-service-3.0#handling-quit-and-exceptions)
* Content Source: [articles/dotnet/bot-builder-dotnet-formflow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-formflow.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
With the release of SDK v4, the older docs (v3) are only updated for high-pri issues.

**Comment by Kaiqb** [comment]
With the release of SDK v4, the older docs (v3) are only updated for high-pri issues.
