### ISSUE TITLE
Unable to run msbot clone in Azure DevOps

### ISSUE THREAD

**Issue by cykreng** [MicrosoftDocs/bot-docs#356]
I'm using a Azure Powershell task (with a service principal authenticated against the subscription) in Azure DevOps to run the following command.
 msbot clone services --name $(BotName) --luisAuthoringKey $(LUISAuthoringKey) --folder "$(System.ArtifactsDirectory)/Enterprise Template Test/drop/DeploymentScipts/msbotClone" --location "westus" --force
However, I'm still getting the error 
##[error]Command failed: az account showERROR: Please run 'az login' to setup account. Would I need to authenticate again, and if so, what is the preferred method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by JonathanFingold** [comment]
@cykreng , You can get help with specific issue from our support team at https://stackoverflow.com/questions/tagged/botframework.
