### ISSUE TITLE
Need to elaborate on botFilePath and botFileSecret

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#362]
Since we presumably aren't actually meant to use the strings "yourbasicBot.bot" and "ukxxxxxxxxxxxs=" some instructions should be provided about where to find those values and how to format them (e.g. if the name of the bot file is fine or if some additional path information should be given)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47c9768c-751e-1e0d-3eed-5d44b27d447d
* Version Independent ID: e9bfdfd4-2c21-7e66-ad92-eb1a5ecdc660
* Content: [Download and redeploy bot source code - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-download-source-code?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-build-download-source-code.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-build-download-source-code.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by IntVoid** [comment]
This has been addressed and will be available in the next publish.
