### ISSUE TITLE
Javascript code sample issues

### ISSUE THREAD

**Issue by inigoX** [MicrosoftDocs/bot-docs#363]
1. under "Add the prompts to the set" section, variable dialogs appears out of nowhere. Better to give its declaration.
2. "step.promt" 's signature has two paramters in the latest SDK (4.0.6). The prompt and choices are packed into an object.
3. For the "Create the reserve table dialog" section, the last line of 'await' lacks a return.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6606cce-8a4e-587b-ded2-bd775a4cd7c7
* Version Independent ID: 6f637bca-8cc0-a526-4cbd-9c5f9f94ca2b
* Content: [Manage a complex conversation flow with dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
@inigoX Thanks for pointing this out. There are a few outdated code sections and some missing content. I'll update this and hopefully get a fix live in a few days.

- In **bot.js**, `this.dialogs` should be `this.dialogSet`.
- In the JavaScript library, there is an overload of the dialog context's prompt method that allows the parameters to work as shown:

https://github.com/Microsoft/botbuilder-js/blob/480dbab810c1b28ac677f68c34476fec2c566c32/libraries/botbuilder-dialogs/src/dialogContext.ts#L140:L172

**Comment by a1development** [comment]
As this is a tutorial style document, the whole Javascript tutorial seems incomplete. If you compare the C# with the Javascript Code, there are many things missing, e.g. in the section "Create a dialog set" or in the section "Define some of the supporting information". I was not able to follow the tutorial. 
After coming back from V2(or 3) this. Documentation makes it hard to dive in, using javascript. Are there any good tutorials / resources?

**Comment by a1development** [comment]
@JonathanFingold ok thank you for the feedback. Is there any way to get notified, or do you habe a rough time estimate? I am planing to build a bot for our business.

**Comment by JonathanFingold** [comment]
The complex conversation topic has been updated, and the code in the articles should be current now.

We'll be triaging issues and adding and updating content on an ongoing basis.

Unfortunately, the site does not support following a topic for changes. If your browser supports it, you could watch an article that way.
