### ISSUE TITLE
Please added a toggle option for manually turn off auto translate middleware

### ISSUE THREAD

**Issue by EugeneFoo** [MicrosoftDocs/bot-docs#366]
Hi, a small suggestion that it should include a toggle for manually turn on/off the automatic language translation, this is to prevent when it required an input from user like shipping information in Chinese recipient name and address, but the middleware auto translate these as well.

Atm I only can manually modify the botbuilder-ai code to make it works correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c406c6-b851-189e-4996-4e9ec7b6079b
* Version Independent ID: 4d5e7967-bddf-818d-1a6b-1a1ca4628bf4
* Content: [Translate user input to make your bot multilingual - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-how-to-translation?view=azure-bot-service-4.0&tabs=csrefs%2Ccssetuptranslate%2Ccshelp%2Ccstranslateback%2Cjschangelanguage%2Ccslanguageluis%2Cjsbypass%2Ccstranslation)
* Content Source: [articles/v4sdk/bot-builder-how-to-translation.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-how-to-translation.md)
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by ivorb** [comment]
The article referenced here uses translation middleware is no longer there for v4, but we do have a sample that uses translation that you can use! Take a look here: 
https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/17.multilingual-bot

There is also a JS version of the same sample in that repo, if you need JS.
