### ISSUE TITLE
Error CS0246: The type or namespace name 'BasicLuisDialog' could not be found

### ISSUE THREAD

**Issue by ceteongvanness** [MicrosoftDocs/bot-docs#367]
I follow the step by still get the error message that i did not touch it the source code in MessagesController.cs . And it show me the the following error code:
Controllers\MessagesController.cs(27,66): error CS0246: The type or namespace name 'BasicLuisDialog' could not be found (are you missing a using directive or an assembly reference?) [D:\home\site\wwwroot\Microsoft.Bot.Sample.LuisBot.csproj]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f0f2ff1-f19c-c66d-53ac-b9569e0a4601
* Version Independent ID: 0ef27a09-09cf-e09a-ec40-9c86b1150bde
* Content: [Recognize intents and entities with LUIS - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-luis-dialogs?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-luis-dialogs.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-luis-dialogs.md)
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
It could be that updates to the older version of the SDK (v3) has broken this. Please report it on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework).
