### ISSUE TITLE
missing comma after authoringKey entry

### ISSUE THREAD

**Issue by turnm** [MicrosoftDocs/bot-docs#369]
"authoringKey": "&lt;your authoring key&gt;" -&gt; "authoringKey": "&lt;your authoring key&gt;",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fb99c59-443b-e949-63f7-10dc3621046d
* Version Independent ID: c58faee3-d99b-d101-ca0f-9a0ee36a0ac4
* Content: [Create a bot using Bot Builder SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-service-file?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-service-file.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-service-file.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by ivorb** [comment]
Thanks! Fixed, should be published shortly
