### ISSUE TITLE
Link to C# template is broken

### ISSUE THREAD

**Issue by pschaeflein** [MicrosoftDocs/bot-docs#370]
In the prerequisites section, the link to the Bot template for C# is broken.

https://marketplace.visualstudio.com/items?itemName=BotBuilder.BotBuilderV3

That link returns a 404 today.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5668ed00-c579-8520-c30f-6008ff4bf9d1
* Version Independent ID: a1d437ab-faa9-fbfa-d380-d1e4b36fdd8e
* Content: [Create a bot with the Bot Builder SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-quickstart?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@pschaeflein - with the release of SDK v4, the old VSIX template was removed from the gallery.
