### ISSUE TITLE
Option 1 does not appear secure

### ISSUE THREAD

**Issue by cbarkerms** [MicrosoftDocs/bot-docs#373]
Option 1 does not appear secure as you are suggesting to include the secret in client-side JavaScript. I think you would need to have this portion of the code running on the server and just return the token to the client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a95d02-732d-3324-37ce-d2c1a41131e0
* Version Independent ID: bc0366f3-8714-e758-ff02-07837a7751d0
* Content: [Connect a bot to the Web Chat channel - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-webchat.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-webchat.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by mingweiw** [comment]
You and the doc are saying same thing. The doc says "Use this option if you can execute a **server-to-server** request to exchange your web chat secret for a temporary token," For even more security, see [this](https://blog.botframework.com/2018/09/25/enhanced-direct-line-authentication-features/).
