### ISSUE TITLE
Steps to add LUIS to EchoBot don't match the SDK template project

### ISSUE THREAD

**Issue by markleavesley** [MicrosoftDocs/bot-docs#375]
I'v got the latest "Bot Builder V4 SDK Template for Visual Studio", created an echo bot and started following the above steps. The sample does not contain a class called "EchoBot" nor does the class code above match anywhere in the sample. 

Susbtituting "EchoBot" for "EchoWithCounterBot" looks like it might be the answer but if you paste the code in you get several errors, such as can't find "EchoState" (which doesn't exist in any sample set I've downloaded from MSDN/GitHub). Can you please correct the above instructions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Using LUIS for Language Understanding - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
@markleavesley This topic is being rewritten. Changes will go live in the next few days.

**Comment by JonathanFingold** [comment]
This topic has been updated. If you find other issues, please open a new issue.
