### ISSUE TITLE
Botframework 4 is more hectic to work.

### ISSUE THREAD

**Issue by vairaselvam** [MicrosoftDocs/bot-docs#376]
Comparing to Botframework 3 Version 4 is more tedious even to create a simple bot. the framework is not simple as version 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1217f5b5-6736-e72c-c420-773fc968aff3
* Version Independent ID: 3a139655-6959-d8fd-a982-fe527db4d04a
* Content: [Additional support resources for the Bot Framework - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-links-help?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-resources-links-help.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-resources-links-help.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
For feedback on the SDK design itself, please log an issue in the appropriate repository for the language you are using. See [BotBuilder](https://github.com/Microsoft/BotBuilder) for a list of the repos.
