### ISSUE TITLE
Bot sample

### ISSUE THREAD

**Issue by Rykimaruh** [MicrosoftDocs/bot-docs#377]
are there any actual bot sample for the new qna? This seems too complex just to make a simple qnamaker dialog call or are we to do this from now on with the new qnamaker? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
@Rykimaruh - the sample used in the article is referenced at the beginning in the prerequisites section. You can download it from GitHub using the link provided.

**Comment by SungminAI** [comment]
There is not link in the prerequisites section. "Qna Maker" is only showing in bold. please fix it.
