### ISSUE TITLE
Creating a bot with Rest?

### ISSUE THREAD

**Issue by jsweiler** [MicrosoftDocs/bot-docs#381]
The title say "Create a bot with REST" but I don't see any information on actually doing that. It shows how to get an accesstoken but then jumps to exchanging a message with a user.

I am interested in knowing how to create a bot with Rest if possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03c49826-bbc8-1589-7b80-ad46c6cbcac6
* Version Independent ID: 327925a7-ec0d-0d00-f3c6-16f62cdf05b9
* Content: [Create a bot with the Bot Connector service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-quickstart?view=azure-bot-service-3.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by jsweiler** [comment]
What I really want to do is create a bot channel registration with rest only as opposed to doing so in the Azure portal.

**Comment by Kaiqb** [comment]
@jsweiler - the preferred way is to do it using the Azure Portal. Could you describe the scenario you are trying to address?

**Comment by jsweiler** [comment]
We are creating Bots to use the [Graph Calling API ](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/calls-api-overview)for Microsoft Teams which is in beta now.

Each bot will be a "call queue" for our customers. The customers will be creating these Queues (Bots) and we want them to be able to push a button and automatically create the Bot Channel Registration. We don't want them to have to run any powershell script or cli command.

I also had posted a [question here](https://stackoverflow.com/questions/52779519/create-bot-with-rest-api-or-sdk) where the Nuget package I'm using there seems like what I want but I was getting an error and wasn't sure why.

**Comment by jsweiler** [comment]
Here is something else I was trying: doing a PUT request to https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/myresourcegroup/providers/Microsoft.BotService/botServices/MyNewBot1000?api-version=2018-07-12
with a body of 
``` json
{
  "properties": {
    "displayName": "MyNewBot1000",
    "description": "Description of New Bot",
    "endpoint": "https://url.com",
    "msaAppId": "myid",
    "password": "mypassword",
    "location": "global",
    "sku": {
      "name": "F0"
    },
    "kind": "sdk",
    "version": "4"
  },
  "location": "global"
  
}
```
I am using an access token retrieved by doing POST: https://login.microsoftonline.com/{{tenant}}/oauth2/token
with body of
```
scope:https://management.core.windows.net
client_id:myId
client_secret:mypassword
grant_type:client_credentials
resource:https://management.core.windows.net
```
However I get the following response:
``` json
{
    "error": {
        "code": "InvalidBotData",
        "message": "Bot is not valid. Errors: BotServiceRuntimeVersion: RuntimeVersion is required. "
    }
}
```

**Comment by jsweiler** [comment]
@Kaiqb Just checking, is this going to be something that is possible to do sometime?

**Comment by EricDahlvang** [comment]
Programmatic bot creation can be done with 'az bot' within the Azure CLI: https://docs.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest
