### ISSUE TITLE
What i did wrong?

### ISSUE THREAD

**Issue by Kipetcoff** [MicrosoftDocs/bot-docs#382]
Hello, I did everything according to this manual, but in the result test my bot gets "There was an error sending this message to your bot: HTTP status code Forbidden". What I did wrong? My application accessible. Localy eveything works fine, but remotelly not. I think some keys should be putten somewhere. The question is WHERE?

**Comment by Kipetcoff** [comment]
Here are some screens withparameters
![2018-10-11_15-08-10](https://user-images.githubusercontent.com/28597113/46803007-bb26ae00-cd67-11e8-988e-bb226010ea4e.png)
![2018-10-11_15-07-23](https://user-images.githubusercontent.com/28597113/46803008-bb26ae00-cd67-11e8-84e4-bf3f0bfd19f4.png)
![2018-10-11_15-07-05](https://user-images.githubusercontent.com/28597113/46803009-bbbf4480-cd67-11e8-80f4-197648a6410f.png)
![2018-10-11_15-06-58](https://user-images.githubusercontent.com/28597113/46803010-bbbf4480-cd67-11e8-9008-427866ca1d3a.png)
![2018-10-11_15-06-47](https://user-images.githubusercontent.com/28597113/46803012-bbbf4480-cd67-11e8-9b60-3e5c87447a18.png)

**Comment by iMicknl** [comment]
Can you please add a link to the specific guide you followed? I think you didn't deploy your .bot file which includes the Microsoft App Id & Password, however it is hard to say without knowing which tutorial you followed.

**Comment by Kipetcoff** [comment]
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0

**Comment by Kipetcoff** [comment]
You are right. Problem was in BotConfiguration.bot file. I had there configuration for local use, but not for azure deployment with app keys. Thank you!
