### ISSUE TITLE
Update .net core too

### ISSUE THREAD

**Issue by paulio** [MicrosoftDocs/bot-docs#384]
The instructions do say to upgrade the NuGet packages but you also need to change the project to .net Core 2.1 otherwise the packages will not update correctly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Builder SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by IntVoid** [comment]
This has been addressed and will be in the next publish. Thanks.
