### ISSUE TITLE
Overly complicated or not complicated enough?

### ISSUE THREAD

**Issue by paulio** [MicrosoftDocs/bot-docs#385]
I find this page a little bit confused. For those brand new to the Bot framework just getting to grips with the basic asynchronous nature and the state of the Bot is probably enough. I do agree Middleware plays a very important part but either add that as the next step and don't mention it here OR explicitly use a new bit of Middleware here. Having a sample but only talking about the Middleware seems confusing to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf8a24b-7029-247b-3c5c-3902befe0ccf
* Version Independent ID: bcd01444-d332-29e6-2b81-5558bb2d576b
* Content: [Bot Activity in the Bot Builder SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by ivorb** [comment]
New iteration covering these ideas is in the works

**Comment by Kaiqb** [comment]
Fixed and published updates.
