### ISSUE TITLE
Incorrect naming

### ISSUE THREAD

**Issue by paulio** [MicrosoftDocs/bot-docs#387]
The source doesn't match this example. The source code uses 'DidBotWelcomeUser' NOT 'DidBotWelcomedUser'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a16806-95d6-7c66-3b85-b2ace211f367
* Version Independent ID: c8565ece-392a-fb56-e911-8a5dd5555dee
* Content: [Develop Welcome the user - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=csharp%2Ccsharpmulti%2Ccsharpwelcomeback)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Product: **bot-framework**
* GitHub Login: @Dashel
* Microsoft Alias: **dashel**

**Comment by IntVoid** [comment]
This has been addressed and will be fixed in the next publish. Thanks!
