### ISSUE TITLE
Content Moderation: Missing steps and bug in the generated middleware

### ISSUE THREAD

**Issue by PatLac04** [MicrosoftDocs/bot-docs#395]
In order for the Content Moderation to work, you nee to connect your bot to the service using "msbot connect" like this:
msbot connect generic -n ContentModerator --url https://westus.api.cognitive.microsoft.com/contentmoderator --keys "{\"subscriptionKey\":\" YOUR_API_KEY \",\"region\":\"westus\"}" --secret YOUR_SECRET

The Url is not used but a required parameter.

Also, in the ContentModeratorMiddleware.cs file, the client Endpoint is missing the "https://" part. It should be like this:
   client.Endpoint = $"https://{this.region}.api.cognitive.microsoft.com";

Even better, it should use the URL provided when connecting the service using msbot connect.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-ca/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by Kaiqb** [comment]
@darrenj - issues with content moderator that should be addressed.

**Comment by Kaiqb** [comment]
Thank you for taking the time to share your product and documentation feedback with us. Your input is valued because it helps us create the right documentation for our customers. 
Due to the volume of issues in our queue, our policy is to close issues that have been inactive for the last 90 days. We hope to continue hearing from you. 
Thank you.
