### ISSUE TITLE
Real proactivity

### ISSUE THREAD

**Issue by myselfhimself** [MicrosoftDocs/bot-docs#401]
Hello, this example obviously shows "proactivity" in terms of running fake background jobs and replying asynchronously almost "right away".
This unfortunately does not show how to trigger the bot remotely and have it say something to the user.
Example use cases : 
- notify users who have requested for it that breakfast is ready ;
- ask users what they would fancy doing today. 
What should the right implementation strategies be for that:
1) use the createConversation API ? (if a real conversation has to be started, because the client will be asked to interact eg. "hey, what about jogging today, or do you have a better idea to let me propose you every morning ?")?
2) POST to the /api/messages ? (if the client just has to be notified of something eg. "breakfast is ready!")?
The trigger would come from, say, a remote REST client with a business logic payload (ie. recipe of the breakfast that is ready, to have it shown to the client), but the Bot code has to know to whom (which client) to redirect the messages.
Thanks for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc28a40-716e-22bc-8944-15f0a8b0d5c2
* Version Independent ID: 86252b0d-94e2-2ea6-ed17-fc32ae38e6fc
* Content: [How to use proactive messaging - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by JonathanFingold** [comment]
This scenario requires an additional app or service. The serverice generates the event activity, which it sends to the bot's api/messages endpoint, and the bot then sends the notice (proactive message) to the user. The event activity that the service generatates needs to contain the following information:
* An event name, unique to your app
* A conversation reference for the user, such as the one in which the user subscribed to the notices.
* Enough information for the bot to construct an appropriate notice.

The first item is the event activity's **name** property.
Include the remaining information in the event activity's **value** property.

The code to have the bot generate a proactive message when it receives a message activity is only for demonstration and testing purposes.

Let me know if that helps or if you're still blocked.

**Comment by JonathanFingold** [comment]
One other note about this. The bot will send the proactive message right after it receives the event activity from the service, so the service should send the event at an appropriate time.

**Comment by JonathanFingold** [comment]
@myselfhimself , I'll close this for now. If you have more questions, feel free to reopen this or open a new issue.

**Comment by ladeak** [comment]
Is there a way to create a bot adapter from code and use that to send the message?
When you have a conversation reference, how can you send a message without having a turncontext/botadapter?

**Comment by timkernighan** [comment]
That's how I worked it out:

-  The outer side (that triggers the proactive dialog) should know your bot's id and client secret to begin conversation with your bot. As written in the [Authentication part of wiki](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0), you need to generate the token by sending the POST request to  https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token with difference that the scope parameter should be {your_bot_app_id}/.default

- Then you need to send the POST request to api/messages route of your bot, with Authorization: Bearer {your_token} header. The JSON structure of the message you can look within Bot Framework Emulator or in documentation.

- The rest you can know out by placing the breakpoint in OnTurnAsync method and looking inside context.Activity object of your bot while sending him messages first from the messenger (Skype/Telegram/Facebook), then from your own application. The key parameters are replyToId and serviceUrl. They should be the same as in the message where user started the dialog.

**Comment by jorn1** [comment]
Does anyone have any example code for 'real proactivity'? thanks

**Comment by liamkernighan** [comment]
@jorn1 

### 1. User had started the dialog, you gathered all the required information. Collect it, send it to the external service.
```

private BotMetadata CreateBotMetadataFromDialogContext(WaterfallStepContext context)
{
    var activity = context.Context.Activity;
        var botData = new BotMetadata
        {
            Channel = EnumHelpers.GetChannelById(activity.ChannelId),
            ChannelId = activity.ChannelId,
            ConversationId = activity.Conversation.Id,
            IsGroup = activity.Conversation.IsGroup == true,
            FromId = activity.From.Id,
            FromName = activity.From.Name,
            RecipientId = activity.Recipient.Id,
            RecipientName = activity.Recipient.Name,
            ServiceUrl = activity.ServiceUrl,
            DialogId = context.ActiveDialog.Id,
        };

    return botData;
}
```



You decide to trigger the dialog from external service.
### 2. You need to gather the token for your bot to recognize you. (On external side)

Form the urlencoded string: `grant_type=client_credentials&client_id={your_client_id}&client_secret={your_client_secret}&scope={your_client_id}/.default`

Send it within your body of https POST request to [login.microsoftonline.com/oauth2/v2.0/token](url)
Get the value from access_token field from JSON-response. You can use that token for about an hour or so (the `expires_in` field)

### 3.  Form the POST request for your bot and send it.

Headers:
```
Content-Type: application/json
Authorization: Bearer {token_from_step2}
```

Body:

```
{
    "channelId": "{BotMetadata.ChannelId from step 1.}",
    "conversation": { "id": "{BotMetadata.ConversationId}" },
    "from": {
        "id": "{BotMetadata.FromId}",
        "name": "{BotMetadata.FromName} ?? {String.Empty}",
        "role": "MyExternalClientOrWhatever"
    },
    "id": "{BotMetadata.DialogId}",
    "replyToId": "{BotMetadata.FromId}",
    "inputHint": "acceptingInput",
    "recipient": {
        "id": "{BotMetadata.RecipientId}",
        "name": "{BotMetadata.RecipientName}"
    },
    "serviceUrl": "{BotMetadata.ServiceUrl}",
    "text": "{Your message to the bot or whatever}",
    "timestamp": "{Current timestamp in XML rfc3339 2002-10-02T10:00:00-05:00}",
    "type": "message",
}
```
Send it to `{your_bot_address}/api/messages`

### 4. Profit

```
public async Task OnTurnAsync(ITurnContext turnContext, CancellationToken token = default(CancellationToken))
{
    var dialogCtx = await this.dialogSet.CreateContextAsync(turnContext, token);

    if (turnContext.Activity.Type == ActivityTypes.Message)
    {

        if (turnContext.Activity.From.Role == "MyExternalClientOrWhatever")
        {
            await HandleMessageFromExternalClientOrWhatever(dialogCtx, token);
        }
        else
        {
            await HandleMessageFromMessenger(dialogCtx, token);
        }
    }
}
```

**Comment by liamkernighan** [comment]
@DmitryBLR **{your_client_id}**/.default where **your_client_id** is your client id. I don't now how to explain it any other way.
