### ISSUE TITLE
Links are dead

### ISSUE THREAD

**Issue by jawine1** [MicrosoftDocs/bot-docs#402]
Links to 'Real Estate Bot sample' and 'Job Listing Bot sample' do not work. 404 Error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9cdb2f8-2862-a662-f01c-d8a3f26024c2
* Version Independent ID: 77444357-8674-41ae-6b81-c993190791f3
* Content: [Create data-driven experiences with Azure Search - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-search-azure?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-search-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-search-azure.md)
* Product: **bot-framework**
* GitHub Login: @matthewshim-ms
* Microsoft Alias: **v-shimma**

**Comment by Kaiqb** [comment]
@jawine1 - the correct link is:https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/Node/demo-Search
