### ISSUE TITLE
Poor grammar: Dialogs and DialogContext class work together

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#403]
Fourth paragraph: "At runtime, Dialogs and DialogContext class work together to choose the appropriate Dialog to handle the activity."

Perhaps you meant "the DialogContext class," or maybe "the Dialog and DialogContext classes"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d405d76-b17a-dbe9-c2f2-734fa34b0e8b
* Version Independent ID: 3acc3fa8-b98d-a5f1-8bea-e823c3efec14
* Content: [Dialogs within the Bot Builder SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-dialog.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-dialog.md)
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by IntVoid** [comment]
Fixed, will be in the next publish. Thank you!
