### ISSUE TITLE
Poor grammar: "which is not time-bound and maybe over several days"

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#404]
Second paragraph: "Between each turn of the conversation (which is not time-bound and maybe over several days), the stack is persisted."

I think you meant "may be" instead of "maybe." It might even be worthwhile to say "may span several days" instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d405d76-b17a-dbe9-c2f2-734fa34b0e8b
* Version Independent ID: 3acc3fa8-b98d-a5f1-8bea-e823c3efec14
* Content: [Dialogs within the Bot Builder SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-dialog.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-dialog.md)
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by IntVoid** [comment]
Fixed, will be in the next publish. Thank you!
