### ISSUE TITLE
Unclear.

### ISSUE THREAD

**Issue by GreybackCoder** [MicrosoftDocs/bot-docs#406]
It is not clear where the "services.AddSingleton(sp =&gt;" ... block goes.
It seems implied that it follows services.AddBot, but then options is out of context.
If it is added inside services.addbot var userState is defined twice if the preceding block was copied in before.
Instead of just showing snippets out of context, complete code would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c94a4c9-e988-3b42-a7db-3634d15e9c47
* Version Independent ID: 68765289-1d77-6e4a-c6fb-1abbc067fcbd
* Content: [Manage conversation and user state - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
@GreybackCoder - please take a look at the startup.cs file where the EchoBotWithCounter sample adds these service. Basically, you are adding UserState right after ConversationState that is in the source code.
