### ISSUE TITLE
Sample code doesn't correspond to this document

### ISSUE THREAD

**Issue by msimecek** [MicrosoftDocs/bot-docs#408]
There's no `BotAccessors` class in the linked sample. It's probably `MultiTurnPromptsBotAccessors`. `BotAccessors` was defined in the previous article, but that doesn't seem to have connection to this one (contains different properties).

There are also other differences which make navigating the sample slightly confusing. It would be nice to have a comprehensive piece of code directly on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72538432-fde5-22ab-7997-8a34b11aa24e
* Version Independent ID: c469fa5b-2590-ee16-1491-51b90c069204
* Content: [Prompt users for input using the Dialogs library - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-prompts.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by ivorb** [comment]
The code in the article is intended to show how to use prompts in the Dialogs library, following the same model even if it's not exactly the same. The sample is then provided to give a complete running bot that uses the methods and principles.  When the article doesn't explicitly say it's walking through a certain sample, there will be naming differences or different elements within a class.

**Comment by msimecek** [comment]
Understood. Thanks
