### ISSUE TITLE
EndConversation not found in Microsoft.Bot.Connector.DirectLine 

### ISSUE THREAD

**Issue by Wenfengcheng** [MicrosoftDocs/bot-docs#411]
I try to send EndConversation request by using DirectLineClient, but I can not find any method, or the bot-side will automatically end this conversation with timeout? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174f2cb3-cad3-7d6b-3682-6fae14b1f632
* Version Independent ID: 2f9132db-9d77-0a7a-d6d1-ba140354b388
* Content: [End a conversation - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-end-conversation?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-end-conversation.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-end-conversation.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by CathyQian** [comment]
@Wenfengcheng Is this implemented in your bot file?

**Comment by Wenfengcheng** [comment]
@CathyQian 
No, the only thing I can do is to implement the api request of end conversation by myself.
But I doubt whether the Bot side will automatically end conversation after the application side lose websocket connecton.

**Comment by Kaiqb** [comment]
EndOfConversation is intended to mean that the channel has ended the conversation. Very few channels send it. Possibly only Cortana. Cortana is the only channel that accepts this activity. All other channels, including Direct Line, drop it or forward it without understanding it.
