### ISSUE TITLE
DirectLine + Advanced Authentication - How to provide user id for reconnection?

### ISSUE THREAD

**Issue by tbuquet** [MicrosoftDocs/bot-docs#412]
Hello,

Using channel directline + advanced authentication. I want to be able to handle connection / reconnection in my backend and return the token for a specific user.

If I want to create a new conversation with a specific user, I can use this endpoint:
POST https://directline.botframework.com/v3/directline/conversations
Along with the post data:
`{
    "User": {
        "Id": "dl_userId",
        "name": "User Name"
    }
}`

It works fine and I get a token containing the user context!

Now, there is no documentation as to how I can reconnect to a conversation and specify the user id.
GET https://directline.botframework.com/v3/directline/conversations/{conversationId}?watermark={watermark_value}
Error returned:
`{
    "error": {
        "code": "MissingProperty",
        "message": "Missing user ID"
    }
}`
Surely there must be a way to generate a new token with the user context that I need?
EDIT: If I send a valid token instead of the secret, it works. But that kind of defeat the purpose of what i'm trying to do... I need to be able to join an existing conversation, even if the token expired.

Thanks for your help!

**Comment by calvin-evans** [comment]
+1 to this, when performing a GET against /conversations/{conversationId} using a secret as your token you get a 400 with the body:
```
  {
  "error": {
    "code": "MissingProperty",
    "message": "Missing user ID"
  }
```

Second what @tbuquet says, whilst a token works, it leaves no way to access a conversation once a token expires if you fail to renew it, essentially expiring the conversation also.

**Comment by Kaiqb** [comment]
Please post this on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework). We have support engineers who answer questions.

**Comment by adaddeo** [comment]
I ran into this same issue. I didn't find anything on Stackoverflow. Did anyone ever figure out a solution to this?

**Comment by jmurphyacc** [comment]
+1 This is a pretty big issue for us as well. We are unable to reconnect our conversation.

**Comment by DavidCGarcia89** [comment]
I have this issue as well

**Comment by calvin-evans** [comment]
@DavidCGarcia89 @adaddeo @jmurphyacc have you tried [disabling enhanced authentication](https://github.com/MicrosoftDocs/bot-docs/issues/679#issuecomment-460229816) and seeing if that fixes it?

**Comment by DavidCGarcia89** [comment]
Yeah it fixes, but the problem is that I'm connecting to an oAuth server and is forcing me to copy a magic code which I think is a bad user experience. That is the reason I was trying to enable enhanced authentication.

**Comment by Zack-Strife** [comment]
I have got the exact same problem. I don't want to use the magic code, did you ever find a workaround or a fix ? @DavidCGarcia89 @calvin-evans
