### ISSUE TITLE
Details on how to use the userState and dialogState accessors configured in the template

### ISSUE THREAD

**Issue by jjgriff93** [MicrosoftDocs/bot-docs#414]
Would be useful to have some info on how to use the built in state accessors in the template. Cosmos DB is configured to store this but there isn't much info on how you can use i in your own dialogs and customise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a178d6a6-8037-940c-e8fb-aad548203b92
* Version Independent ID: 181758cf-3495-6848-5808-9dc8234140ab
* Content: [Enterprise Bot Customization - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-customize?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-customize.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-customize.md)
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by darrenj** [comment]
We've provided some examples in the Onboarding Dialog, admittedly simplistic. Let us know if that helps - if not let me have an idea of what you'd like guidance on doing and I'll get it added to the docs

**Comment by AzureDataGeek** [comment]
How would I add an additional knowledgebase to the Bot?

**Comment by Kaiqb** [comment]
Additional QnA KB was addressed in another issue.
