### ISSUE TITLE
Number of bots in C# solution

### ISSUE THREAD

**Issue by stofte** [MicrosoftDocs/bot-docs#416]
Hello. From the samples, IBot seems to be a foundational interface. Should there be only one IBot per project, or is an IBot similar to an IController, and so there can be multiples in an application? If I wish to coordinate my QnABot with MultiLingualBot, should I pick one to be the "main" bot, or should I merge the two, or leave them as is, and add integration code elsewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ffe447d-f0a8-f4b6-d572-ba2c3bba4aab
* Version Independent ID: 6c1d9a6a-4cb3-f404-ce1f-940b443f0e34
* Content: [Azure Bot Service Introduction - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-overview-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-overview-introduction.md)
* Product: **bot-framework**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
In SDK v4, you can do that. See [MVC sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/30.asp-mvc-bot).
