### ISSUE TITLE
Unable to start bot 

### ISSUE THREAD

**Issue by tkosin** [MicrosoftDocs/bot-docs#417]
For the first time to start the bot, OK it works. 
For the second, I get following error:

C:\Users\Facgure\Develop\myJsBots\facgureChatBot&gt;npm start

&gt; FacgureChatBot@1.0.0 start C:\Users\Facgure\Develop\myJsBots\facgureChatBot
&gt; node ./index.js

C:\Users\Facgure\Develop\myJsBots\facgureChatBot\index.js:58
    appId: endpointConfig.appId || process.env.microsoftAppID,
                          ^

TypeError: Cannot read property 'appId' of null
    at Object.&lt;anonymous&gt; (C:\Users\Facgure\Develop\myJsBots\facgureChatBot\index.js:58:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! FacgureChatBot@1.0.0 start: `node ./index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the FacgureChatBot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Facgure\AppData\Roaming\npm-cache\_logs\2018-10-23T09_43_02_269Z-debug.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaad3f2-75c5-e958-4734-8925d03d95c6
* Version Independent ID: 8d98b390-5368-1fa4-8cce-3b0cff252eaa
* Content: [Create a bot using Bot Builder SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by JonathanFingold** [comment]
@tkosin , I tried running through the steps in the article and was not able to reproduce the error.

Did you stop the bot first, before trying to restart it? From a command prompt, you'd press ctrl-C, and then enter `y` to confirm:

```text
…
restify listening to http://[::]:3978

Get Bot Framework Emulator: https://aka.ms/botframework-emulator

To talk to your bot, open myChatBot.bot file in the Emulator
Terminate batch job (Y/N)? y
```

You can also get help from our support team. https://stackoverflow.com/questions/tagged/botframework.

**Comment by tkosin** [comment]
Hi @JonathanFingold,

Thank you for your help. I have stopped the bot before restart it again. But it does not work. I will follow your support on StackOverflow.
