### ISSUE TITLE
 Global Message Handlers sample code doesnot exist

### ISSUE THREAD

**Issue by vivekjainAco** [MicrosoftDocs/bot-docs#418]
Global Message Handlers sample code link is not working. Its giving 404 code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b69f4105-9442-84c9-5fb3-2064f5856973
* Version Independent ID: 5c63b35f-f9cd-3ad4-af89-47062d5e7ec3
* Content: [Implement global message handlers - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-global-handlers?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-global-handlers.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-global-handlers.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@vivekjainAco -  Just so you know, the content that you are looking for is for V3. if you are looking for v4 content, then use this URL: https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0.
