### ISSUE TITLE
sample code missing

### ISSUE THREAD

**Issue by vivekjainAco** [MicrosoftDocs/bot-docs#419]
Sample code links returning 404 code. page not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8de1be0-19df-c8e9-9a80-e8f6df9dc362
* Version Independent ID: 92ae3a1e-10a1-1911-70b2-b8fd6142ba4f
* Content: [Intercept messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-middleware?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-middleware.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-middleware.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
The SDK v3 sample is here: https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp/core-Middleware.
