### ISSUE TITLE
Quickstart mismatch

### ISSUE THREAD

**Issue by vivekjainAco** [MicrosoftDocs/bot-docs#420]
I want to follow the steps here to understand the dialogs and conversation flow. 
But when I followed the Quickstart with SDK4, the created project doesn't have the MessagesController.cs file. So can you please tell me how to follow this page? Would be very helpful. 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95893c20-a332-ad0c-43f4-9c5a62292d3f
* Version Independent ID: e2ccf63b-3b87-a4e4-560b-c7cc8fe68b9a
* Content: [Dialogs overview - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-dialogs?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-dialogs.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-dialogs.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@vivekjainAco - the page you are looking at is for SDK v3. This is the page you should look at: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs. It explains how v4 bots work. The TOC has additional topics in the "Concepts" node that cover the new dialog system.

**Comment by sidbenavente** [comment]
This is sort of a circular dead-end and I can see why @vivekjainAco was having issues. This tutorial references MessagesController.cs, which is said to be created in the Quickstart. However, the v3 Quickstart no longer exists, and users are pointed to the v4 quickstart, which doesn't create the project in a way that follows in step with this tutorial, i.e., there is no MessagesController.cs. The page that @Kaiqb has pointed @vivekjainAco to is the current page, I get that, however, bottom line, the v4 has no step-by-step tutorial and the v3 step-by-step is no longer functional as written.
