### ISSUE TITLE
WelcomeUserStateAccessors code is not consistent with github sample

### ISSUE THREAD

**Issue by rlamba89** [MicrosoftDocs/bot-docs#421]
WelcomeUserStateAccessors code mentioned in the documentation is not consistent with github sample.

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=csharp%2Ccsharpmulti%2Ccsharpwelcomeback

https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/03.welcome-user/WelcomeUserStateAccessors.cs

**Comment by JonathanFingold** [comment]
@rlamba89 , The samples repo is updated independently of the documentation, so these will occaisonally be out of sync.
