### ISSUE TITLE
"Open online code editor" screenshot is outdated

### ISSUE THREAD

**Issue by LanderVe** [MicrosoftDocs/bot-docs#424]
FYI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1c84393-ea23-98d1-0392-b8679d02982b
* Version Independent ID: 32af546a-4848-4755-9a69-2887e23b7658
* Content: [Build a bot with the Azure online code editor - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-online-code-editor?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-build-online-code-editor.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-build-online-code-editor.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by CathyQian** [comment]
Updating it now.

**Comment by dekey** [comment]
Actually this screens are misleading developers. Previously  in your doc you have described how to create basic bot, and here is a screens from echo bot.

**Comment by IntVoid** [comment]
@dekey thank you for pointing that out, I'll go ahead and fix the issue!

**Comment by IntVoid** [comment]
@dekey can you provide me the link to the article you were following prior to https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-online-code-editor?view=azure-bot-service-4.0 ?
