### ISSUE TITLE
Not receiving user message

### ISSUE THREAD

**Issue by PapaLamine** [MicrosoftDocs/bot-docs#425]
I have issues with to intercept all messages. I can log only messages sent by the bot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2409c28b-855f-a7c4-9bb1-d49c70bfa5cf
* Version Independent ID: a1e427a6-301a-52c7-7999-71994954cf8a
* Content: [Intercept messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-intercept-messages?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-intercept-messages.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-intercept-messages.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@PapaLamine - take a look at the support options listed on this page to get help with the issue you are having: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-links-help?view=azure-bot-service-4.0.
