### ISSUE TITLE
No details on how to Extract entities 

### ISSUE THREAD

**Issue by ferares4** [MicrosoftDocs/bot-docs#428]
Hi, the Extract entities section does not specify how to extract them in Visual Studio after created in LUIS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Using LUIS for Language Understanding - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by CathyQian** [comment]
@ferares4 We briefly mentioned this in the text right above the 'Extract entities' section -- 'Any entities recognized will be returned as a map of entity names to values and accessed using recognizerResults.entities." We will update the article to include entities in the code snippets. You will expect to see the updated article soon.

**Comment by Kaiqb** [comment]
Updated content has the steps that show how to extract entities.
