### ISSUE TITLE
Teams specific examples would be good

### ISSUE THREAD

**Issue by drub0y** [MicrosoftDocs/bot-docs#429]
Would be a good idea to add (or link to) some Teams specific examples here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1170b28d-13ae-2e47-e14b-7cd9af0c61d3
* Version Independent ID: 506a2fe7-420f-9b76-53db-c89f4a977849
* Content: [Implement channel-specific functionality - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-channeldata?view=azure-bot-service-4.0#create-a-facebook-notification)
* Content Source: [articles/v4sdk/bot-builder-channeldata.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-channeldata.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@drub0y Can you provide a sample message (or other activity) from MS Teams that contains a sample entity?

**Comment by mmiele** [comment]
Work in progress.
See PR: https://github.com/MicrosoftDocs/bot-docs-pr/pull/1697

**Comment by mmiele** [comment]
Added the following Teams section: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-channeldata?view=azure-bot-service-4.0#adding-a-bot-to-teams.
