### ISSUE TITLE
sample code - Facebook-events URL is broken

### ISSUE THREAD

**Issue by alundiak** [MicrosoftDocs/bot-docs#433]
In section:

"
For further reference the Facebook-events sample bot can be used to explore the bot communication with Facebook Messenger.
"
The url https://aka.ms/facebook-events is 404
In fact full url is broken:
https://github.com/Microsoft/BotBuilder-Samples/tree/v4/samples/csharp_dotnetcore/23.facebook-events

And I belive it's somewhere from here:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/23.facebook-events

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acb1736e-f822-2374-fc91-60a13567966e
* Version Independent ID: 03a952ae-0752-9aeb-a214-981bbfaf3b91
* Content: [Connect a bot to Facebook Messenger - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-facebook.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-facebook.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **RobStand**

**Comment by Kaiqb** [comment]
@alundiak - fixed. thanks for reporting.
