### ISSUE TITLE
Your hello echo bot is giving 136 errors.

### ISSUE THREAD

**Issue by tehmeerali786** [MicrosoftDocs/bot-docs#445]
I just have followed as it is given in tutorial. there are errors like this..
Severity	Code	Description	Project	File	Line	Suppression State
Error		Package Microsoft.AspNetCore.Hosting.Server.Abstractions 2.0.2 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Hosting.Server.Abstractions 2.0.2 supports: netstandard2.0 (.NETStandard,Version=v2.0)			0	
Severity	Code	Description	Project	File	Line	Suppression State
Error		Package Microsoft.AspNetCore.Authentication.OpenIdConnect 2.0.3 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Authentication.OpenIdConnect 2.0.3 supports: netstandard2.0 (.NETStandard,Version=v2.0)			0	
Please let me know what is the problem. It suppose to work with only few steps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Builder SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by Kixantrix** [comment]
Seems that updating the version of Visual Studios fixes this problem https://stackoverflow.com/questions/45802909/updating-to-asp-net-core-2-0-packages-are-not-compatible-with-netcoreapp2-0. I'll be trying with my setup.

**Comment by IntVoid** [comment]
I've verified the issue and as @Kixantrix has already pointed out, doing the following will resolve your issue.

"Solved it by updating Visual Studio to it's latest version.
Also, make sure SDK is updated to version 2.0 and NuGet to its latest version."

**Comment by tehmeerali786** [comment]
Yes Sir: It is resolved. Thank You for your help. As soon I updated the Visual Studio, I tried again and it worked.

**Comment by adisdhiv** [comment]
I am getting similar error when I run the hello bot. I am using visual studio 2017, Bot builder SDK 4.0

Package Microsoft.AspNetCore.All 2.2.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.AspNetCore.All 2.2.0 supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2)
Package Microsoft.Bot.Configuration 4.2.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.Bot.Configuration 4.2.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.Bot.Schema 4.2.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.Bot.Schema 4.2.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.Bot.Builder 4.2.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.Bot.Builder 4.2.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.Bot.Builder.Integration.AspNet.Core 4.2.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.Bot.Builder.Integration.AspNet.Core 4.2.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.Bot.Connector 4.2.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.Bot.Connector 4.2.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
One or more packages are incompatible with .NETCoreApp,Version=v2.1.
