### ISSUE TITLE
Documentation is incorrect to generate a client library

### ISSUE THREAD

**Issue by james-lawrence** [MicrosoftDocs/bot-docs#447]
swagger file is a dead link. its now unclear how to generate a client for other languages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09901557-99b5-3776-56bb-9cc148f7c93f
* Version Independent ID: 1e0c11e1-7d7c-99ab-afc2-5da53824361e
* Content: [Key concepts in the Bot Connector service and Bot State service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-concepts?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-concepts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-concepts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by CathyQian** [comment]
Checking it now. Will get back to you soon.
