### ISSUE TITLE
Table of contents and page title don't match

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#450]
In the table of contents, this page is called "Create your own prompts to gather user input", the title of the article here is "Prompt users for input using your own prompts". These should match to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79129724-5f90-ac8d-6918-d5801a4e2001
* Version Independent ID: 08e19b7b-2ec6-95da-2f5a-d534e761f5da
* Content: [Manage a conversation flow with primitive prompts - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-primitive-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-primitive-prompts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
@cmayomsft - fix published to the live site.
