### ISSUE TITLE
Title of article in ToC doesn't match title of doc.

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#451]
In the ToC, this doc is called "Use LUIS and QnA services with the Dispatch tool". The doc is titled "Integrate multiple LUIS and QnA services with the Dispatch tool" above. These titles should match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Integrate multiple LUIS and QnA services with the Dispatch tool - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
@cmayomsft - fix published to the live site.
