### ISSUE TITLE
Awkward sentence...

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#455]
This sentence "We provide tools for various stages of bot development that you can use to build your bot to get you started." is really awkward. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ffe447d-f0a8-f4b6-d572-ba2c3bba4aab
* Version Independent ID: 6c1d9a6a-4cb3-f404-ce1f-940b443f0e34
* Content: [Azure Bot Service Introduction - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-overview-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-overview-introduction.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Simplifying to:
> We provide tools for various stages of bot development to help you design and build bots.

This update should go live in a few days.
