### ISSUE TITLE
Image is confusion, looks like req/res, not two posts.

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#456]
In the image/example under the title "Understanding how bots work", having the user post "hi" and the bot respond with "hi" makes it look like request/response, rather than two posts/activities. Changing the bot to respond with "hello" would make it clear that these are two different messages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf8a24b-7029-247b-3c5c-3902befe0ccf
* Version Independent ID: bcd01444-d332-29e6-2b81-5558bb2d576b
* Content: [Bot Activity in the Bot Builder SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by cmayomsft** [comment]
Or have it echo back "You said 'hi'" like the EchoBot example.

**Comment by ryanvolum** [comment]
Instead of an image, this would be much better solved with a gif, which would configure the emulator and send 'hi' to the bot.

**Comment by JonathanFingold** [comment]
@cmayomsft @ryanbor , Agreed. I'll try to fix the artwork to better reflect the fact that the "response" activity from the bot happens separately but within the timeframe of the "request" activity from the channel.

**Comment by Kaiqb** [comment]
@cmayomsft @ryanvolum @JonathanFingold - when we were writing this topic, we did discuss whether it should be hi or hello. The reason we settled on hi is because it is an echo bot. So, I agree that it should be You said: hi.

**Comment by JonathanFingold** [comment]
@cmayomsft @ryanvolum @Kaiqb - Is this a better picture for the article? (I don't have the original artwork file.)

![activityoverview](https://user-images.githubusercontent.com/35047199/47926510-f48d9d80-de7d-11e8-982d-dbee357e2dcf.png)

**Comment by Kaiqb** [comment]
@JonathanFingold - I can get you the original.

**Comment by Kaiqb** [comment]
The image is fixed and checked into the master branch.
