### ISSUE TITLE
No mention of .bot deployment approaches

### ISSUE THREAD

**Issue by ryanvolum** [MicrosoftDocs/bot-docs#457]
Most authoring approaches now seem to point towards using .bot files to deploy bots. This document completely neglects to mention that deployment approach and in turn tells a confusing deployment story. If a developer authors their bot by using a template, yeoman generator, or by pulling the github samples, and then uses this document to deploy their bot, they will be stuck with a confused hybrid deployment story. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your bot to Azure - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by mandardhikari** [comment]
In order for you to deploy the bot using bot file you need to do following
1) Add Production endpoint to your bot file with appId and appPassword
2) Encrypt your bot
3) Deploy the bot the the Azure App service and add botFilePath and botSecret with values .\example.bot and <your bot secret respectively> add these values in the app settings of the service plan
That should take care of the deployment

**Comment by JonathanFingold** [comment]
@ryanbor Agreed. Adding to our backlog.

**Comment by djpirra** [comment]
The App Password should be one of your choice when you are configuring the bot file?
If not, where to get it from?

Thank you

Also, on the channels the example code talks about secret and not app password.. should be the same? If not, where to get it from?

**Comment by Kaiqb** [comment]
@ryanvolum - The .bot file part is something the developer needs to do before deploying the bot, which now mentioned in the topic referenced in this issue. Take a look at the updated topic, and if you run into tools related bug, please file them in the [botbuilder-tools](https://github.com/Microsoft/Botbuilder-tools/issues) repo.

The readme files are also being updated for the samples in botbuilder-samples repo.

**Comment by JonathanFingold** [comment]
@ryanvolum These topics have been added or updated recently. Please reopen if we haven't addressed your concern.
- [Manage resources with a .bot file](https://docs.microsoft.com/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0)
- [Deploy bots from botbuilder-samples repo](https://docs.microsoft.com/azure/bot-service/bot-builder-deploy-samples?view=azure-bot-service-4.0)
- [Deploy your bot using Azure CLI](https://docs.microsoft.com/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0)
