### ISSUE TITLE
Defining a turn

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#459]
I think there's a more base concept here that would make the concept of a turn more concrete. Define a turn based conversation (a conversation where each side takes a turn talking), and then what a turn is in that conversation ("What is your name?" and the response "Bill"). From that context, the concept of a turn in your bot code and what a turn context is would make more sense. https://en.wikipedia.org/wiki/Turn-taking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf8a24b-7029-247b-3c5c-3902befe0ccf
* Version Independent ID: bcd01444-d332-29e6-2b81-5558bb2d576b
* Content: [Bot Activity in the Bot Builder SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
@cmayomsft Is the following rewrite better?
> In a conversation, people often speak one-at-a-time, taking turns speaking. With a bot, it generally reacts to user input. Within the Bot Builder SDK, a _turn_ consists of the user's incoming activity to the bot and any activity the bot sends back to the user as an immediate response. You can think of a turn as the processing associated with the arrival of a given activity.

**Comment by Kaiqb** [comment]
@cmayomsft @JonathanFingold - fyi the updated content is live now.

**Comment by JonathanFingold** [comment]
@cmayomsft Closing for now. Reopen if you think the introduction requires more work.
