### ISSUE TITLE
Be sure to await any activity calls

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#462]
This is really great guidance, but doesn't belong under "Concepts". How would I apply this knowledge there? This guidance should be very close to the code/sample that this applies to, so it doesn't get lost. Like having it after the code that sends the first message to a user in Develop/"Send welcome message to users" and/or Develop/"Send text and spoken messages".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf8a24b-7029-247b-3c5c-3902befe0ccf
* Version Independent ID: bcd01444-d332-29e6-2b81-5558bb2d576b
* Content: [Bot Activity in the Bot Builder SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs#response-event-handlers)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
Duplicated this alert later in this topic, in the **Bot structure** section, and in the first how to topic, **Send welcome message to users**.
This update should go live in a few days.
