### ISSUE TITLE
"Bot structure" JavaScript narrative is lacking Node.js overview

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#463]
The C# docs has a good overview of how a bot is an ASP.Net Core app. This is missing in the JavaScript page, The JavaScript page just launches into .env file, etc. Is something missing from the JS documentation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf8a24b-7029-247b-3c5c-3902befe0ccf
* Version Independent ID: bcd01444-d332-29e6-2b81-5558bb2d576b
* Content: [Bot Activity in the Bot Builder SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=js#response-event-handlers)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
Duplicated the alert later in this same article, in the **Bot structure** section, and also in the first how to topic, **Send welcome message to users**. This update should go live in a few days.

**Comment by JonathanFingold** [comment]
Updated the JS intro paragraph in the **Bot structure** section. Update should go live in a day or two.

The Yeoman generator creates a type of [restify](http://restify.com/) web application. If you look at the restify quickstart in their docs, you'll see an app similar to the generated **index.js** file. This section mainly describes the **package.json**, **.env** , **index.js**, **bot.js**, and **echobot-with-counter.bot** files. Code in some files won't be copied here, but you will see it when you run the bot, and you can refer to the [Node.js echobot-with-counter](https://aka.ms/js-echobot-with-counter) sample.
