### ISSUE TITLE
Awkward sentence

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#464]
"The central concept in the SDK to manage conversations is the idea of a Dialog." is awkward and doesn't read well. "Managing conversations through the concept of a Dialog is central to the SDK."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d405d76-b17a-dbe9-c2f2-734fa34b0e8b
* Version Independent ID: 3acc3fa8-b98d-a5f1-8bea-e823c3efec14
* Content: [Dialogs within the Bot Builder SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-dialog.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-dialog.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by Kaiqb** [comment]
@cmayomsft - Fix is pushed to the live site. Changes should appear in the next 15-20 minutes.
