### ISSUE TITLE
Bot State vs. Dialog State

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#465]
This feels like two docs, one how how BotState/Accessors work and then another doc (that builds on the first) that talks about how DialogState works. Having it as a single document is confusing, covers too many concepts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0846e672-f3f3-844d-ec78-6e401f5120dc
* Version Independent ID: 1ab740e5-8248-af3e-6bf9-063d1bb418e9
* Content: [Dialog State - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-state?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-dialog-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
Updates to the conceptual topics are in review. Changes should go live soon.

**Comment by JonathanFingold** [comment]
@cmayomsft These topics have been refactored. Please reopen if your issue has not been addressed.
- [Managing state](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0)
- [Dialogs library](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0)
