### ISSUE TITLE
Step by Step instructions mislead non .NET devs

### ISSUE THREAD

**Issue by ryanvolum** [MicrosoftDocs/bot-docs#466]
As developers step through each instruction step-by-step, they create their bot using:

![image](https://user-images.githubusercontent.com/3891951/47753458-d2650700-dc54-11e8-81b3-9611694d7c29.png)

They they continue to scroll down to find that if they were Node developers they had to pass a specific flag, meaning they have to go to azure and deprovision everything they just accidentally spun up:

![image](https://user-images.githubusercontent.com/3891951/47754762-3a1d5100-dc59-11e8-8842-ecd30a6aad9c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eac19e28-e37b-1496-4758-1b1638c311db
* Version Independent ID: 10df3cfc-fcec-411b-5d6d-796883bfb773
* Content: [Create bots with Azure CLi - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tools-az-cli?view=azure-bot-service-3.0)
* Content Source: [articles/bot-builder-tools-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tools-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @matthewshim-ms
* Microsoft Alias: **v-shimma**

**Comment by Kaiqb** [comment]
@ryanvolum - moved the note to include --lang argument at the beginning so that users don't run into the issue you listed above.

**Comment by Kaiqb** [comment]
Pushed update to the live site.
