### ISSUE TITLE
ConversationDialogState and UserState are never specified

### ISSUE THREAD

**Issue by robinmanuelthiel** [MicrosoftDocs/bot-docs#468]
The code samples use a `ConversationDialogState` and `UserState` class that are never defined, linked or specified somewhere else. So for users who are simply following this documentation, it is not possible to get a working sample afterward!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c5adf9-272a-e0f1-10f1-c8365e76035b
* Version Independent ID: 1982af41-5a06-4398-0e95-abcc50864e0d
* Content: [Manage a simple conversation flow with dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
This topic has been reworked extensively and is now more comprehensive. Changes are in a currently pending PR.
