### ISSUE TITLE
Code sample can't be run...

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#469]
The code above isn't complete, so you can't copy/paste to run it, nor does the article link to a complete sample that you could run. Linking to code you could run/start from would be really helpful to make the doc something you could do rather than just read.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a16806-95d6-7c66-3b85-b2ace211f367
* Version Independent ID: c8565ece-392a-fb56-e911-8a5dd5555dee
* Content: [Develop Welcome the user - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=js%2Ccsharpmulti%2Ccsharpwelcomeback)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Dashel
* Microsoft Alias: **dashel**

**Comment by JonathanFingold** [comment]
There is a section in the doc that refers to the code sample. Closing for now, but I'll discuss with the team if there is a better way to call out the complete samples.

## Same welcome for different channels
The following example watches for new conversation update activity, sends only one welcome message based on your user joining the conversation, and sets a Prompt status flag to ignore the user’s initial conversation input. The example code below uses the welcome user samples in the Github repo for [C#](https://aka.ms/bot-welcome-sample-cs) and [JS](https://aka.ms/bot-welcome-sample-js) code.
