### ISSUE TITLE
Sample is slightly different from doc...

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#470]
...Looking at the sample here, the sample is slightly different from the doc above. It would be great to read the doc, then link to the sample and just be able to run/step through the code I just read about. https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/03.welcome-users/bot.js

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a16806-95d6-7c66-3b85-b2ace211f367
* Version Independent ID: c8565ece-392a-fb56-e911-8a5dd5555dee
* Content: [Develop Welcome the user - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=js%2Ccsharpmulti%2Ccsharpwelcomeback)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Dashel
* Microsoft Alias: **dashel**

**Comment by JonathanFingold** [comment]
Unfortunately, the samples in the samples repo are a moving target, for now. We're currently sync'ing on an opportunistic basis. The goal is to eventually bring the docs in line with the final versions of the samples.
