### ISSUE TITLE
"Track prompt states" sample doesn't run as written

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#473]
I created a new bot using the Yeoman template, and then added the code above and it doesn't compile. I fixed those errors and the sample always prompts for name and never moves to the next prompt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79129724-5f90-ac8d-6918-d5801a4e2001
* Version Independent ID: 08e19b7b-2ec6-95da-2f5a-d534e761f5da
* Content: [Manage a conversation flow with primitive prompts - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-primitive-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-primitive-prompts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
The `Echo` template changed out from under this article. I'll work on a fix.

**Comment by Kaiqb** [comment]
@JonathanFingold - this is for JS. I tested C# code and fixed minor issues.

**Comment by JonathanFingold** [comment]
@cmayomsft I've rewritten the topic and updated the code. Fixes should be live tomorrow or the next day.
