### ISSUE TITLE
Integrate Simple-Prompt sample

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#474]
It would be great to integrate this sample here, so you have something you can just run. https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/04.simple-prompt/bot.js

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79129724-5f90-ac8d-6918-d5801a4e2001
* Version Independent ID: 08e19b7b-2ec6-95da-2f5a-d534e761f5da
* Content: [Manage a conversation flow with primitive prompts - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-primitive-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-primitive-prompts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
These are fundamentally different. This topic is specifically does not use the dialogs library. The 04 sample uses prompts (a feature of the dialogs library) outside of a dialog.

We have a few separate topics showing how to use prompts within a dialog, and some of those match up with existing samples.
