### ISSUE TITLE
"Validate user input" sample won't run

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#475]
You can't run the code in the section above, would be great to use this sample and integration validation/multi prompt into it. Like prompting for name and age (validating it's a number). https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/04.simple-prompt/bot.js

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79129724-5f90-ac8d-6918-d5801a4e2001
* Version Independent ID: 08e19b7b-2ec6-95da-2f5a-d534e761f5da
* Content: [Manage a conversation flow with primitive prompts - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-primitive-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-primitive-prompts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
See #473 and #474.
