### ISSUE TITLE
Table of Contents title doesn't match doc title

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#476]
Doc is "Use dialog library to gather user input" and the title in the doc is "Prompt users for input using the Dialogs library". These titles should match to make it easy to see I'm on the correct doc for the link I clicked...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72538432-fde5-22ab-7997-8a34b11aa24e
* Version Independent ID: c469fa5b-2590-ee16-1491-51b90c069204
* Content: [Prompt users for input using the Dialogs library - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-prompts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
@cmayomsft - Fix published to the live site.
