### ISSUE TITLE
DatetimePrompt calls a LUIS model?

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#477]
The following text is confusing. Does the DatetimePrompt call a LUIS and uses it's prebuilt entity to recognize date/time or does it use the same recognizer as LUIS? See below.

https://github.com/Microsoft/Recognizers-Text/tree/master/JavaScript/packages/recognizers-text-suite

"Prompt the user for a date-time. Users can respond using natural language such as "Tomorrow at 8pm" or "Friday at 10am". The Bot Framework SDK uses the LUIS builtin.datetimeV2 prebuilt entity. For more information, see builtin.datetimev2."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72538432-fde5-22ab-7997-8a34b11aa24e
* Version Independent ID: c469fa5b-2590-ee16-1491-51b90c069204
* Content: [Prompt users for input using the Dialogs library - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-prompts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
DateTime uses the same recognizer as LUIS. It does not call LUIS - it works locally.

**Comment by cmayomsft** [comment]
Yes, exactly. As written, it makes me wonder if it's making LUIS calls... who owns the model...

**Comment by JonathanFingold** [comment]
This topic has been updated recently. That text is no longer present.
