### ISSUE TITLE
The code in this document is v3 code for C#

### ISSUE THREAD

**Issue by drub0y** [MicrosoftDocs/bot-docs#479]
It appears that the C# code in this document is for v3 and should be upgraded for v4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3691ca29-1a48-7842-8536-5f86d5ef0908
* Version Independent ID: 08ea18f3-3fe9-14a8-d08a-6bbc2b33b42d
* Content: [Debug a bot built using Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-bot?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-debug-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-debug-bot.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by IntVoid** [comment]
Updated, this will be available in the next publish.
