### ISSUE TITLE
Middleware and Logging sample link

### ISSUE THREAD

**Issue by zipibz** [MicrosoftDocs/bot-docs#482]
Link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2409c28b-855f-a7c4-9bb1-d49c70bfa5cf
* Version Independent ID: a1e427a6-301a-52c7-7999-71994954cf8a
* Content: [Intercept messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-intercept-messages?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-intercept-messages.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-intercept-messages.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Here's an updated link: https://aka.ms/v3-js-capability-middlewareLogging

I'm updating the article, which should go live in a day or two.
