### ISSUE TITLE
Links to Multi-Dialog Bot sample and the Contoso Flowers Bot sample get 404

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/bot-docs#483]
The links behind Multi-Dialog Bot sample and the Contoso Flowers Bot go to https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-MultiDialogs and https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/demo-ContosoFlowers and these result into a 404 Not Found page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57eaab52-c854-288c-7e5a-d23adca41e36
* Version Independent ID: 6a664f69-7195-3990-0e1d-59d7b118837d
* Content: [Localize form content - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-formflow-localize?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-formflow-localize.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-formflow-localize.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
The v3 repo was renamed. You can find the C# samples [here](https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp).
Updating links, fixes should go live in a day or two.
