### ISSUE TITLE
NuGet or npm

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#485]
For JavaScript developers, they will install through npm. The text below only mentions NuGet.

"To parse this information, we use the Microsoft's Text Recognizer library. This package is available through NuGet, or downloading it from the repository. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79129724-5f90-ac8d-6918-d5801a4e2001
* Version Independent ID: 08e19b7b-2ec6-95da-2f5a-d534e761f5da
* Content: [Create your own prompts to gather user input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-primitive-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-primitive-prompts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
Fixed.
