### ISSUE TITLE
To less information

### ISSUE THREAD

**Issue by janstrijk** [MicrosoftDocs/bot-docs#491]
To get this actually working there is to less information supplied. Writer should realize that this is very complex for people starting to use the Azure Bot Service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c5adf9-272a-e0f1-10f1-c8365e76035b
* Version Independent ID: 1982af41-5a06-4398-0e95-abcc50864e0d
* Content: [Manage a simple conversation flow with dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
@janstrijk I updated this article recently. We will be updating the companion conceptual article ([Dialogs library](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-dialog)) soon.

For a complete sample that you can run, see the **multi-turn prompt** [[C#](https://aka.ms/cs-multi-prompts-sample)|[JS](https://aka.ms/js-multi-prompts-sample)] sample.

Let me know which sections are causing you problems, and I'll try to update the article accordingly.

**Comment by janstrijk** [comment]
Thanks, I will use the multi-turn promt sample to study this stuff.

**Comment by JonathanFingold** [comment]
I'm updating the article to include:
* the require statement for the **bot.js** file
* the custom validation code of the `AGE_PROMPT`

**Comment by JonathanFingold** [comment]
Fix should be live today or tomorrow. Thanks.
