### ISSUE TITLE
Unable to display REST call ( post call) response in the Microsoft NodeJS V4 bot

### ISSUE THREAD

**Issue by srikanth4kakumanu** [MicrosoftDocs/bot-docs#492]
Hi Guys,
We are developing a bot with Microsoft NodeJS. In this our requirement is, once the Utterance is entered, an API call need to be made to one of our server's & need to display the data in the Bot that was received from the server.
I am getting the data & able to display the result in the console. But I am not able to print that response in the Bot using the statement "  **await turnContext.sendActivity(${result} );** ".
A piece of my bot.js Code is below:

`// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// bot.js is your bot's main entry point to handle incoming activities.

const { ActivityTypes } = require('botbuilder');
var requestify = require('requestify');

// Turn counter property
const TURN_COUNTER_PROPERTY = 'turnCounterProperty';

class EchoBot { 
    
    /**
     *
     * @param {ConversationState} conversation state object
     */
    constructor(conversationState) {
        // Creates a new state accessor property.
        // See https://aka.ms/about-bot-state-accessors to learn more about the bot state and state accessors
        this.countProperty = conversationState.createProperty(TURN_COUNTER_PROPERTY);
        this.conversationState = conversationState;
    }
    /**
     *
     * Use onTurn to handle an incoming activity, received from a user, process it, and reply as needed
     *
     * @param {TurnContext} on turn context object.
     */
    async onTurn(turnContext) {
        // Handle message activity type. User's responses via text or speech or card interactions flow back to the bot as Message activity.
        // Message activities may contain text, speech, interactive cards, and binary or unknown attachments.
        // see https://aka.ms/about-bot-activity-message to learn more about the message and other activity types
        if (turnContext.activity.type === ActivityTypes.Message) {
            // read from state.
            let count = await this.countProperty.get(turnContext);
            count = count === undefined ? 1 : ++count;
            var dataObject = someObject;    
            const callingSynapse = async function() {
                requestify.post('IPAddress', dataObject).then(async function(response) {
                    // console.log(JSON.parse(response.body).result.result.botMessage);
                    let result = JSON.parse(response.body).result.result.botMessage;
                    console.log(result);    /* Iam able to display the required result in this console.*/
                    await turnContext.sendActivity(`${result } `);                    
                });               
            }
            callingSynapse();           
            // await turnContext.sendActivity(`${turnContext.activity.text } `);   
            // increment and set turn counter.
            await this.countProperty.set(turnContext, count);
        } else { 
            // Generic handler for all other activity types.
            await turnContext.sendActivity(`[${ turnContext.activity.type } event detected]`);
        }
        // Save state changes
        await this.conversationState.saveChanges(turnContext);
    }
}
exports.EchoBot = EchoBot;`

The line, await turnContext.sendActivity(${result} ); is unable to display the result to the Bot.
Even If I write the line **await turnContext.sendActivity(You said: ${turnContext.activity.text } );** in the **requestify** block, It is unable to get displayed.

Can anybody help me to get this solved.

Thanks in advance.

**Comment by JonathanFingold** [comment]
@srikanth4kakumanu Your best bet might be to ask  [our support team on StackOverflow](https://stackoverflow.com/questions/tagged/botframework).

At a complete guess, as I'm not familiar with the requestify library:
* define `callingSynapse` to return the result.
* call and await the result from `callingSynapse`.
* then call `sendActivity` to display the result to the user.

**Comment by JonathanFingold** [comment]
Closing. Please reopen if you still have questions.
