### ISSUE TITLE
No response in MS Teams

### ISSUE THREAD

**Issue by NobinJoseRad** [MicrosoftDocs/bot-docs#493]
Hey, I've created a bot using Enterprise template. I deployed to Azure and able to get a reply using web channel. 
However after enabling the Teams channel I've copied the AppID to Ms teams but unable to get any reply. Normal echo bot (v4) is able to get reply in Teams. I wish to know if there is any knows compatibility issues.

God Bless

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by NobinJoseRad** [comment]
anyone can help? is there any known issue with teams integration of enterprise bot?

**Comment by NobinJoseRad** [comment]
thank you...

**Comment by Kaiqb** [comment]
Closing as duplicate.
