### ISSUE TITLE
After publishing from Visual Studio, link is giving error. 

### ISSUE THREAD

**Issue by tehmeerali786** [MicrosoftDocs/bot-docs#494]
my Visual Studio says, successfully published. 

However, the link that opens says 

"
HTTP Error 502.5 - Process Failure

Common causes of this issue:
The application process failed to start
The application process started but then stopped
The application process started but failed to listen on the configured port

Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect

For more information visit: https://go.microsoft.com/fwlink/?LinkID=808681"

I don't know what is the problem. At this time, I am simply trying to publish Echo Bot that is in Microsoft Bot Framework Quick Start (from C#). Please help.

**Comment by Kaiqb** [comment]
@tehmeerali786 - I've seen this error when your Visual Studio project has spaces in its name. Does your project name has spaces?

**Comment by tehmeerali786** [comment]
Thanks. I have made new project with no  spaces on . Now it is giving me another error. 
"An error occurred while starting the application.
.NET Core 4.6.26614.01 X86 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 2.1.1-rtm-30846    |    Microsoft Windows 10.0.14393    |   Need help?"

**Comment by Kaiqb** [comment]
@tehmeerali786 - the team is investigating similar issues. How did you create your project?

**Comment by tehmeerali786** [comment]
I created from bot builder template v4. Simple echo bot. 
But, the tutorials I have watched and textbooks all of them show some bot template coming on project dialog. But now it appears on column. And, it does not create the same bot files that were created in textbooks printed few months ago. Why Microsoft is doing drastic changes in Syntax and
