### ISSUE TITLE
Transcript Storage for Javascript 

### ISSUE THREAD

**Issue by singzzz** [MicrosoftDocs/bot-docs#495]
Is this available / can samples be provided?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8f39f5-1a91-6fdb-3cc0-124b282e9806
* Version Independent ID: 701f9b3c-a893-dee1-d012-760e6f870ec4
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-gb/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by JonathanFingold** [comment]
@singzzz , This functionality is under development. You can watch https://github.com/Microsoft/botbuilder-js/issues/383 to know when a fix is merged, or periodically check sample **22.conversation-history** in the [samples list](https://github.com/Microsoft/BotBuilder-Samples#samples-list) to see whether the JS sample is available.

**Comment by madenwala** [comment]
Some of these samples on this page don't have JavaScript examples. please add!
