### ISSUE TITLE
Please explain how to test it?

### ISSUE THREAD

**Issue by arashaga** [MicrosoftDocs/bot-docs#497]
How can we test this app using the emulator? I get and error that the message could not be sent. Also, what should the end point be? the local host or the Microsoft?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Using LUIS for Language Understanding - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=js#configure-your-bot-to-use-your-luis-app)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by CathyQian** [comment]
@arashaga checking it now.

**Comment by arashaga** [comment]
Any updates on this?

**Comment by Kaiqb** [comment]
@arashaga - take a look at the updated topic which should address your issue. Basically, you are testing the sample code using the Emulator. The Emulator will use the .bot file to get access to the services the bot needs. The .bot file in the sample needs to be updated, which is also shown in the updated topic. 

The URL you list above is not how you'd test the bot. The bot must be tested using the the sample referenced in the topic.

**Comment by xtianus79** [comment]
This isn't working and or the instructions are lacking.  How do you get this working on the bot Framework Emulator
