### ISSUE TITLE
Backchannel sample

### ISSUE THREAD

**Issue by payboxcma** [MicrosoftDocs/bot-docs#498]
The link for Backchannel sample no longer works. Can you provide a working link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40659e74-4b85-b408-a29a-ffe827c2ed7f
* Version Independent ID: c85d39c9-0b71-c892-613a-e7b2e622a0a9
* Content: [Exchange information using the web control - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-backchannel?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-backchannel.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-backchannel.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@payboxcma , I'm guessing they moved or renamed the folder in the Web-Chat repo: https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/redux-activity-middleware. I'll update the link in the article.
