### ISSUE TITLE
Error in Documentation in line : const LUIS_CONFIGURATION = '<YOUR_LUIS_APP_NAME>';

### ISSUE THREAD

**Issue by pinakipatrapro** [MicrosoftDocs/bot-docs#499]
As mentioned in documentation,
the line const LUIS_CONFIGURATION = '<YOUR_LUIS_APP_NAME>'; is not in index.js but in bot.js (Line 25) as per the autogenerated yo bot builder. 

Line in documentation : "In the index.js file, we read in the configuration information to generate the LUIS service and initialize the bot. Update the value of LUIS_CONFIGURATION to the name of your LUIS app, as it appears in your configuration file."  https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=js

**Comment by pinakipatrapro** [comment]
It for Basic Bot, JS code snippet

**Comment by IntVoid** [comment]
This has been fixed and will be available in the next publish.
