### ISSUE TITLE
This is missing key information

### ISSUE THREAD

**Issue by joeyjoejo1234** [MicrosoftDocs/bot-docs#500]
This makes no mention about the fact that businesses cannot use the Cortana channel. It was extremely frustrating for me to find out that my company cannot use Cortana because you need a personal license, you cannot use it when you have a Microsoft E5 license!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155fd9a4-a390-eb9e-5f1a-fae7a2ede084
* Version Independent ID: 21c420dc-db37-f5d5-ac38-c843055e195a
* Content: [Connect a bot to Cortana - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-cortana?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-cortana.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-cortana.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@jameslew - can we get confirmation about this issue the customer is reporting?

**Comment by jameslew** [comment]
Hello @joeyjoejo1234; the Cortana Channel is currently limited to Microsoft Account authentication; it is mostly about the origins of Cortana originally being targeted at a consumer audience.  Recently, the Cortana team has announced a private preview of Cortana Skills Kit for Enterprise based on the Bot Service.  They're collecting interested parties on this page: https://docs.microsoft.com/en-us/cortana/enterprise/overview.
