### ISSUE TITLE
Conflicting/confusing information

### ISSUE THREAD

**Issue by joeyjoejo1234** [MicrosoftDocs/bot-docs#501]
Although this specifically states "The Skype for Business Bot Framework channel is currently supported for Skype for Business Online." when i speak to Microsoft support they say that skype for business is still in preview and is not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e517934d-f0c3-05f8-71e1-c721eb6d0608
* Version Independent ID: ccb249e9-e9b6-1b8b-8506-c7de560f99cd
* Content: [Connect a bot to Skype for Business - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-skypeforbusiness?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-skypeforbusiness.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-skypeforbusiness.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@joeyjoejo1234 - In the Azure portal, you can add Skype for Business as a channel.
