### ISSUE TITLE
Conflict between Microsoft.Bot.Builder and Microsoft.Bot.Builder.Core packages in Direct Line bot

### ISSUE THREAD

**Issue by FitzekD** [MicrosoftDocs/bot-docs#503]
According to the tutorial on how to create a Direct Line bot and client (https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-direct-line) you should use bot the Microsoft.Bot.Builder and the Microsoft.Bot.Builder.Core.Extensions NuGet packages. 
This leads to the following conflict between Microsoft.Bot.Builder and Microsoft.Bot.Builder.Core which is a dependency of Microsoft.Bot.Builder.Core.Extensions when using the ITurnContext interface.
- The type 'ITurnContext' exists in both Microsoft.Bot.Builder.Core, ...' and 'Microsoft.Bot.Builder, ...'

It seems that both packages implement the ITurnContext in the same namespace Microsoft.Bot.Builder.
Because of this, visual studio is unable to determine which implementation of the interface should be used and the example is not compiling.

If this is intended I would need some help to clarify how the example should be implemented to make it work.

Some information:
Microsoft.Bot.Builder 4.1.5
Microsoft.Bot.Builder.Core.Extensions 4.0.1-preview
Microsoft.NETCore.App v2.2.0-preview3-27014-02

**Comment by Kaiqb** [comment]
@FitzekD - this content is removed from the TOC because it is not up to date and not working currently.

**Comment by Mwalima** [comment]
I have the same issue. Why is this closed. I dont see a solution.

**Comment by RenanCarso** [comment]
I'm facing the same issue.
