### ISSUE TITLE
Misleading text

### ISSUE THREAD

**Issue by dekey** [MicrosoftDocs/bot-docs#507]
&gt; You can find the MicrosoftAppID and MicrosoftAppPassword for your bot in the Application Settings blade.

Actually not. After setup this setting will not appear in `Application settings` section for basic bot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe8cc9a-f4d9-bf84-e92b-628b612b0883
* Version Independent ID: b075774f-a422-f39f-e82f-36220884f30a
* Content: [Manage a bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-overview?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-manage-overview.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-manage-overview.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **rstand**

**Comment by Kaiqb** [comment]
The `MicrosoftAppID` is under `Settings`. The `MicrosoftAppPassword` is only shown when you first create it.

**Comment by IntVoid** [comment]
This has been fixed and will be in the next publish.
