### ISSUE TITLE
ContentModeratorClient does not contain a definition of  'BaseUrl'

### ISSUE THREAD

**Issue by AzureDataGeek** [MicrosoftDocs/bot-docs#514]
Compiling a seemingly properly configured Enterprise Bot gives the following error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ContentModeratorClient' does not contain a definition for 'BaseUrl' and no accessible extension method 'BaseUrl' accepting a first argument of type 'ContentModeratorClient' could be found (are you missing a using directive or an assembly reference?)	sh-bot	C:\source\Bot\sh-bot\Middleware\ContentModeratorMiddleware.cs	68	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by Kaiqb** [comment]
@darrenj - could you take a look at it?

**Comment by AzureDataGeek** [comment]
@darrenj - after setting all the bot packages to 4.06 it compiled.  The error was from me upgrading the libraries.

**Comment by darrenj** [comment]
We'll update the packages in the template to avoid this in the future. thank you!

**Comment by ryanlengel** [comment]
Hi @AzureDataGeek, last week we updated the bot packages to `2.1.5` in the Enterprise Template. See Microsoft/AI#236 for details, I'd recommend you update to the same

**Comment by AzureDataGeek** [comment]
Thanks @ryanlengel .  Will do.  Noticed all the BotBuilder dependencies are now at 4.1.5 as well.  Hopefully this solves some issues I'm experiencing.

**Comment by Kaiqb** [comment]
Feel free to reopen it if the issue isn't resolved.
