### ISSUE TITLE
.bot file not being generated

### ISSUE THREAD

**Issue by ivan13mx** [MicrosoftDocs/bot-docs#515]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 748e48cd-09ac-2aaa-8dab-9e0615c70652
* Version Independent ID: 4b25c9d1-dcab-ea00-3835-0fe4b72943dd
* Content: [Create a bot using Bot Builder SDK for Java - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/java/bot-builder-java-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/java/bot-builder-java-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/java/bot-builder-java-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by ivan13mx** [comment]
Following instructions here: https://docs.microsoft.com/en-us/azure/bot-service/java/bot-builder-java-quickstart?view=azure-bot-service-4.0 is unclear how to generate .bot file from eclipse

**Comment by Kaiqb** [comment]
@ivan13mx - the Java SDK is not on the same schedule as C# or JS, so that is why it is not working. The topic you are using has been removed from the TOC, but not from the content set. I'll remove it.
