### ISSUE TITLE
Adding a second QnA Knowledgebase

### ISSUE THREAD

**Issue by AzureDataGeek** [MicrosoftDocs/bot-docs#516]
I've added a second QnAMaker Knowledgebase service using msbot.  All looks fine in the config files, but the bot is giving me an error indicating that the LUIS dispatcher model needs to be published.  I've refreshed and published the dispatch model, but  it's still giving that error.  

Does the Enterprise Bot support more than one knowledgebase?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a178d6a6-8037-940c-e8fb-aad548203b92
* Version Independent ID: 181758cf-3495-6848-5808-9dc8234140ab
* Content: [Enterprise Bot Customization - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-customize?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-customize.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-customize.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by AzureDataGeek** [comment]
Exception raised on line 131 of TelemetryLuisRecognizer.cs.

            var recognizerResult = await base.RecognizeAsync(context, ct);

**Comment by AzureDataGeek** [comment]
I get the same error when simply adding a new question to the FAQ and refreshing the dispatcher.  To reproduce:  

1. Deploy a new project locally via the Deploy template instructions.  
2. Test the bot with "hello".  Everything works fine with response "Hi There."
3. Add a new question & answer pair via QnA Maker, Save, Train, and Publish.  
4. dispatch refresh --bot "YOURBOT.bot" --secret YOURSECRET

Bot no longer works and fails same place as above.

It's clear I'm doing something wrong, but don't know what.

**Comment by AzureDataGeek** [comment]
Continuing to report on this.  

It's not the only error in dispatch, but one of the errors after running a dispatch refresh, it leaves the LUIS dispatch application marked as "private".  

Switching it to public does not fix the error.

Also, it's definitely related to dispatch and / or msbot.   If I leave all the settings as they are in the bot file and simply add a QA pair to the FAQ in QNA, and also add the same Question to the Dispatch LUIS model, retrain and publish both, everything still works.  

So something in msbot or dispatch is breaking the application.

**Comment by Kaiqb** [comment]
@darrenj - could you look into this?

**Comment by Kaiqb** [comment]
Fixed.
