### ISSUE TITLE
Confusing with App Password, Secrets and so on...

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/bot-docs#521]
Where to get the App ID and App Password?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your C# bot to Azure - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
@djpirra Following the steps in the [Create your bot channels registration](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0#create-your-bot-channels-registration) section, you should have recorded your app ID and password in steps 16 and 18.

**Comment by Kaiqb** [comment]
Correct. You can find the MicrosoftAppID in the Azure portal, but you can't get the MicrosoftPassword after generating it.

**Comment by brandonh-msft** [comment]
When users arrive at this page, a password has already been created. The presence of this pwd should be addressed.
