### ISSUE TITLE
Template generates .NET Framework project

### ISSUE THREAD

**Issue by iks111** [MicrosoftDocs/bot-docs#523]
I downloaded the .vsix file with the template, however in my Visual Studio it's named "Bot Builder Echo Bot", not "Bot Builder Echo Bot V4". As soon as I create a solution using it, nothing compiles with lots of references errors.
I've checked and the project targets .NET Framework 4.6 and it's impossible to change it to .NET Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Builder SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
You might want to post this question on StackOverflow: https://stackoverflow.com/questions/tagged/botframework. We have support engineers who monitor issue.
