### ISSUE TITLE
suggestedAction issue with telegram bot

### ISSUE THREAD

**Issue by psitnikov** [MicrosoftDocs/bot-docs#524]
Hello!
I'm trying to add suggestedAction to communicate with telegram bot in this way:

`
"suggestedActions": {
        "actions": [
            {
                "type": "imBack",
                "title": "Blue",
                "value": "color:blue"
            },
            {
                "type": "imBack",
                "title": "Red",
                "value": "color:red"
            },
            {
                "type": "imBack",
                "title": "Green",
                "value": "color:green"
            }
        ]
}
`

 and when user taps on button (green button, for example ) bot returns not a `value` (color:green) as expected but a `title` (Green)

With the skype bot the same code works well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac4d38d8-00f8-10f8-6641-9de10ff0c9eb
* Version Independent ID: 2af2a93a-b938-74d2-6709-f1b245af63be
* Content: [Add suggested actions to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-suggested-actions?view=azure-bot-service-3.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-add-suggested-actions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-add-suggested-actions.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
It could be an issue with Telegram. Please post a question on StackOverflow: https://stackoverflow.com/questions/tagged/botframework.
