### ISSUE TITLE
Should also show how to create a bot using Azure CLI

### ISSUE THREAD

**Issue by drub0y** [MicrosoftDocs/bot-docs#525]
So I would keep this entry as a root topic, maybe with some of the generalities of creating a bot service, but I would recommend splitting into two subtopics from there. One being this article as it exists today, but name it "Deploying a bot via the Azure Portal" and then another, new one called "Deploying a bot via Azure CLI" which covers all the steps from a command line perspective.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9e2e6-b901-9e27-d070-701922396a4c
* Version Independent ID: c29a68b2-886d-2cec-0ce7-c49c586d7ea8
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
This issue is being tracked in the Bot Builder Samples Repo [875](https://github.com/Microsoft/BotBuilder-Samples/issues/875). 
The plan is to have a topic that shows how to create/deploy bots using az cli, but this work is pending fixes needed in the az cli.
