### ISSUE TITLE
Display multiple adaptive cards in Cortana window

### ISSUE THREAD

**Issue by GTrabucco** [MicrosoftDocs/bot-docs#529]
I have a Cortana Skill set up using .NET that retrieves event information and displays them on adaptive cards. When I require that multiple events be displayed in Cortana, each card is briefly shown in the Cortana window and then it briefly shows the next until it reaches the last event and it stays there. Is there a way to display multiple cards in the Cortana window?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c205b864-640c-a101-8468-6227d8f2e7cb
* Version Independent ID: a8c5bdba-01f3-46ec-1c73-a8fabd4ccf0f
* Content: [Add rich card attachments to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-rich-card-attachments?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-add-rich-card-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-add-rich-card-attachments.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
Take a look at this doc: https://docs.microsoft.com/en-us/cortana/skills/cards, and if you still have questions, feel free to post it on [Stackoverflow](https://docs.microsoft.com/en-us/cortana/skills/cards) - we have support engineers there who can help.
