### ISSUE TITLE
Unable to clone services

### ISSUE THREAD

**Issue by reguita** [MicrosoftDocs/bot-docs#530]
I followed the ReadMe instructions as carefully as I know how.  when I run following command i get this error: "operable program or batch file.ot recognized as an internal or external command,"

msbot clone services --name "chat-bot" --luisAuthoringKey "MyLuisAuthoringKey1234" --folder "DeploymentScripts/MsbotClone" --location "southcentralus" --groupName "MyResourceGroupName"

What could I be doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use LUIS and QnA services with the Dispatch tool - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csharp#notes-about-the-code)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by reguita** [comment]
I just want to make sure I am understanding the strategy here... it seems really redundant and opens lots of room for error.  Almost like I'd need to create an app to manage and write my luis intents and qna maker faqs so that they stay in sync.

So if I understand we use 2 LUIS services 1 for Home Automation and the other for Weather.  These each have intents and entities.

We have 1 QNA Maker service which has multiple FAQs

We then have a 3rd LUIS service (referred to as Dispatcher) which holds all of the questions in QNA Maker, All of the utterences in the other 2 Luis services and we use this to determine what the bot should do with request?

So any time I add/edit/remove a FAQ I also need to update my Dispatcher Luis?  

This seems like a governing nightmare, am I getting this correct?

**Comment by CathyQian** [comment]
@reguita I'm looking into this now and will get back to you soon.

**Comment by Kaiqb** [comment]
@reguita - the error you are getting could be a bug in the tool. You might want to ask this on StackOverflow (https://stackoverflow.com/questions/tagged/botframework).

**Comment by reguita** [comment]
Where you able to replicate the issue all you have to do is clone a recent
copy of the GitHub and walk through the steps on the readme file I get it
every time on multiple computers.

**Comment by r2roesk** [comment]
I agree with @reguita, are we missing something? We really have to update our LUIS/QnA AND Dispatcher whenever something changes? Will a future update fix this entanglement?
