### ISSUE TITLE
Emulator installation instructions

### ISSUE THREAD

**Issue by ovishesh** [MicrosoftDocs/bot-docs#531]
It will be a great developer experience to update the link in the prerequisites section for Emulator to an existing doc, "Debug with the emulator", (as opposed to releases page on GitHub) that explains what the emulator is and how it works with proper screenshots.

Do you want me to create a similar issue for the Node.js doc as well?

Debug with the emulator - https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-4.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Builder SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@ovishesh How does the Emulator's [Getting started](https://github.com/Microsoft/BotFramework-Emulator/wiki/Getting-Started) page look like a good link for this?

**Comment by JonathanFingold** [comment]
I'll update the links in the quickstarts, and scan and update our other articles, too.

The Emulator repo is outside my control, but I can forward these suggestions. I'll ask about getting this from their wiki into docs.microsoft.com.

**Comment by JonathanFingold** [comment]
The link update is in and should be live within a couple days.

**Comment by ovishesh** [comment]
@JonathanFingold - don't forget to update with this new doc with a link to the newly published .bot doc - https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0
