### ISSUE TITLE
Confusion between port 3978 and 3979

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#532]
You say the command `ngrok.exe http 3979 -host-header="localhost:3979"` configures ngrok for a bot running on 3978

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab11009-d70c-0f09-6640-5848d9f2ef22
* Version Independent ID: c9864bd5-030b-fd3e-e87c-afd762c70328
* Content: [Test a Cortana skill - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-cortana-skill?view=azure-bot-service-3.0&viewFallbackFrom=azure-bot-service-4.0#test-your-cortana-skill)
* Content Source: [articles/bot-service-debug-cortana-skill.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-debug-cortana-skill.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kaiqb**

**Comment by CathyQian** [comment]
We will update the text to remove the confusion. Thanks!

**Comment by Kaiqb** [comment]
@v-kydela - feel free to submit PR with a fix for minor issues like these.
