### ISSUE TITLE
Minor Edits.

### ISSUE THREAD

**Issue by Joll59** [MicrosoftDocs/bot-docs#533]
1. There are 3 random Ellipses in the first JS code snippet. 
2. require`botbuilder` should be changed to require`botbuilder-core`
3. First code snippet needs to address `userState` not set as a property on the class in the constructor but it is referencing `this.userState` a few lines down, when saving state changes. (Right below 3 random Ellipses actually)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a16806-95d6-7c66-3b85-b2ace211f367
* Version Independent ID: c8565ece-392a-fb56-e911-8a5dd5555dee
* Content: [Send welcome message to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=js%2Cjsmulti%2Cjswelcomeback)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Dashel
* Microsoft Alias: **dashel**

**Comment by Kaiqb** [comment]
This content is based on the Welcome Sample. Before we can update the content, the sample needs to be updated. Go ahead a submit a PR again the Welcome Sample in the [BotBuilder-Samples repo](https://github.com/Microsoft/BotBuilder-Samples).

**Comment by Joll59** [comment]
Hey @Kaiqb, [the sample](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/03.welcome-users/bot.js), has some of the changes already implemented but are not reflected in the docs.

**Comment by ryanvolum** [comment]
@Kaiqb can you reopen this bug? it appears to still be an issue that developers are running into. Though it should be a minor fix, the issue continues to exist, so the bug should remain open. 

To @Joll59 's point, it also appears that the sample this borrow from _is_ working (there are no ellipses, userState is declared as a private property), so the fix here should just involve aligning the two.
