### ISSUE TITLE
How long does a conversation last?

### ISSUE THREAD

**Issue by CraigGraw** [MicrosoftDocs/bot-docs#534]
When a conversation is created in Directline and you are given a conversationId how long does this conversation last?
Does it ever expire or can the client expect that conversation to exist indefinitely?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d7238a1-4d34-349b-e5cc-f7238c981892
* Version Independent ID: d5945944-58de-1221-d202-d14266bf7dc9
* Content: [Key concepts in the Bot Framework Direct Line API 3.0 - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-concepts?view=azure-bot-service-4.0#developer-resources)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-concepts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-concepts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by CathyQian** [comment]
The conversation run as long as the bot and client participate and have valid credentials. Does this answer your question?

**Comment by Kaiqb** [comment]
Yes, there isn't anything in the bot framework that ends the conversation.

**Comment by CraigGraw** [comment]
Has this behaviour recently changed? The issue below would suggest it has.

https://github.com/Microsoft/BotBuilder/issues/5291

If so is it documented in the Microsoft Directline Documentation?
