### ISSUE TITLE
Link to code sample please.

### ISSUE THREAD

**Issue by utkarsh24** [MicrosoftDocs/bot-docs#537]
Link to code sample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6606cce-8a4e-587b-ded2-bd775a4cd7c7
* Version Independent ID: 6f637bca-8cc0-a526-4cbd-9c5f9f94ca2b
* Content: [Create advance conversation flow using branches and loops - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
This one uses the Echo bot created in the quickstart. See "Create the dialogs for the hotel bot" section for links to the quickstart.

**Comment by zorosafi2003** [comment]
@kaiqb can you please add the link for   Create the dialogs for the hotel bot because i can't find it
