### ISSUE TITLE
Broken link to  CafeBot LUIS sample

### ISSUE THREAD

**Issue by MarekLani** [MicrosoftDocs/bot-docs#542]
Github link to  CafeBot LUIS sample shows 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3449824e-105d-ffe2-000c-0a20e42a45f4
* Version Independent ID: 3fa03eda-b09c-e6d9-c4f3-a186184232ee
* Content: [Extract typed LUIS results - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luisgen?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luisgen.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luisgen.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by MarekLani** [comment]
C#

**Comment by Kaiqb** [comment]
The topic you are looking at was removed from the TOC because of several issues. See LUISGen readme (https://github.com/Microsoft/botbuilder-tools/blob/master/packages/LUISGen/readme.md) on GitHub for information.
