### ISSUE TITLE
Dialogset constructor gives error

### ISSUE THREAD

**Issue by vivekjainAco** [MicrosoftDocs/bot-docs#543]
dialogs = new DialogSet(); gives error that it takes the IstatePropertyAccessor as  a parameter. 
How shall I continue?

Thanks,
Vivek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95db9168-d434-3461-ab0d-c623c27800a6
* Version Independent ID: f3463efe-3ba7-385a-f2b4-9398fb5028de
* Content: [Ask the user questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-waterfall?view=azure-bot-service-4.0&tabs=cstab)
* Content Source: [articles/v4sdk/bot-builder-tutorial-waterfall.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-waterfall.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
The content that you are looking at is not in the TOC and is outdated. The correct link is: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=csharp. 

I've removed the old content and the site will be updated soon.
