### ISSUE TITLE
Missing description of PrivateConversationState

### ISSUE THREAD

**Issue by peterbozso** [MicrosoftDocs/bot-docs#547]
This documentation only mentions UserState end ConversationState, while the SDK-s have a PrivateConversationState class as well:
https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/PrivateConversationState.cs
https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/privateConversationState.ts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0846e672-f3f3-844d-ec78-6e401f5120dc
* Version Independent ID: 1ab740e5-8248-af3e-6bf9-063d1bb418e9
* Content: [Dialog State - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-state?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/bot-builder-dialog-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
PrivateConversationState was added recently. We'll work on getting it into the docs soon.

**Comment by JonathanFingold** [comment]
We just updated [Managing state topic](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-state). Discussion of the different state types was moved here.

We will publish an updated version of [Save user and conversation data](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-v4-state) early next week.

**Comment by peterbozso** [comment]
Perfect, thank you Jonathan!
