### ISSUE TITLE
C# sample

### ISSUE THREAD

**Issue by dchumpitaz** [MicrosoftDocs/bot-docs#548]
When is avalaible a C# version from this sample? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1ea3ca-002b-5114-df1d-fb50b0e103e2
* Version Independent ID: b393f465-9b91-7f96-aaf8-e6f023eab8e4
* Content: [Transition conversations from bot to human - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-handoff-human?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-design-pattern-handoff-human.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-pattern-handoff-human.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by Kaiqb** [comment]
We don't have an ETA at this point. The best place to monitor what's available is the sample repo on [GitHub](https://github.com/Microsoft/BotBuilder-Samples/blob/master/README.md).

**Comment by Basavarajsk1992** [comment]
Is there any sample code for sdkv4 in node js.
