### ISSUE TITLE
Source code link is broken

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#549]
The last link on the page, "download the source code," seems to be trying to access the preview branch instead of the master branch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a95d02-732d-3324-37ce-d2c1a41131e0
* Version Independent ID: bc0366f3-8714-e758-ff02-07837a7751d0
* Content: [Connect a bot to the Web Chat channel - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-webchat.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-webchat.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Thanks for catching that. It is fixed now.
