### ISSUE TITLE
How to create new azure Oauth connection using REST API?

### ISSUE THREAD

**Issue by utkarsh24** [MicrosoftDocs/bot-docs#550]
I want to create dynamically new Oauth connection using Rest API.
currently i am using 
https://management.azure.com/subscriptions/subscriptionId/resourceGroups/resourceGroupName/providers/Microsoft.BotService/botservices/botName/Connections?api-version=2017-12-01

I get following error 

{
    "error": {
        "code": "InvalidRequestMethodForResourceCollectionRequest",
        "message": "The request method 'POST' is invalid for the resource collection request https://management.azure.com/subscriptions/subscriptionId/resourceGroups/resourceGroupName/providers/Microsoft.BotService/botservices/botName/Connections?api-version=2017-12-01'. Only GET requests are supported for resource collection requests."
    }
}

What is the api-version to create Oauth connection using REST?
Could you please provide sample code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eac19e28-e37b-1496-4758-1b1638c311db
* Version Independent ID: 10df3cfc-fcec-411b-5d6d-796883bfb773
* Content: [Create bots with Azure CLi - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tools-az-cli?view=azure-bot-service-3.0)
* Content Source: [articles/bot-builder-tools-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tools-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @matthewshim-ms
* Microsoft Alias: **v-shimma**

**Comment by Kaiqb** [comment]
Take a look at this [topic](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0).
