### ISSUE TITLE
What does a bot file look like? // Update

### ISSUE THREAD

**Issue by johnwildes** [MicrosoftDocs/bot-docs#552]
I'm trying to build a bot from scratch using the BASIC BOT Template.  It's challenging to say the least.  I'm now looking at my bot file configuration wondering what I need to include, what is optional to include, and what each of the json pair keys values mean.  Some are explanatory, some like ID are not.  I expected to find a walkthrough on what goes in a bot file here.  I have not found that.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8cc826-fa2f-5521-ead7-b771ad527269
* Version Independent ID: 91bc6ab6-e909-e8da-74aa-4a178559c290
* Content: [Manage bot resources with a bot file - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-file-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-file-basics.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
This topic is an overview of what a .bot file is. If you are trying to add services to the .bot file, use the MSBot tool to do that. More information about the commands and options are listed in the [MSBot](https://github.com/Microsoft/botbuilder-tools/blob/master/packages/MSBot/README.md) readme under the **MSBot functionality** section.
