### ISSUE TITLE
Missing Subscription Key from the doc

### ISSUE THREAD

**Issue by ovishesh** [MicrosoftDocs/bot-docs#559]
Missing `subscriptionKey` for QnA maker in the `.bot` snippet above. Also, missing information on where to grab the `subscriptionKey`, i.e. from the Azure portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
Are you getting errors when running the sample? The [readme](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/11.qnamaker/README.md) of the sample used in this article does not mention the subscription key.

**Comment by ovishesh** [comment]
1. Used the sample as a ref along with the doc.
1. Followed [this `.bot` file](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/11.qnamaker/qnamaker.bot) 
1. Removed my Subscription Key and seems to work fine, I guess we don't need the subscription key - so maybe needs to be omitted out of the Sample to be inline with the doc?

**Comment by ivorb** [comment]
@ovishesh could you follow the link to the issue I referenced above, and provide any extra information there? Thanks!
