### ISSUE TITLE
Looks more complicated than it should be

### ISSUE THREAD

**Issue by LanderVe** [MicrosoftDocs/bot-docs#561]
Maybe there is a good reason, but all this code seems very complex just to get an accessor. The code is scattered all over the place. For example: the accessor properties (e.g. TopicState on EchoBotAccessors) are defined in the accessor, then set in startup based on the consersation/user state. But to set it you need a name from EchoBotAccessor again, so you need a public static property for that. Why not just something like this(based on EchoBot template):

//accessor
public class EchoBotAccessors
{
  public EchoBotAccessors(ConversationState conversationState)
  {
    ConversationState = conversationState ?? throw new ArgumentNullException(nameof(conversationState));
    CounterState = conversationState.CreateProperty&lt;CounterState&gt;($"{nameof(EchoBotAccessors)}.CounterState");
  }
  public ConversationState ConversationState { get; }
  public IStatePropertyAccessor&lt;CounterState&gt; CounterState { get; }
}

//startup - in configureservices method
var accessors = new EchoBotAccessors(conversationState);

I've omitted the user state here, but you get the idea: initializing the StatePropertyAccessor in the constructor of the accessor.
Am I missing something here? Do you need to know that public static string outside of the accessor class?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c94a4c9-e988-3b42-a7db-3634d15e9c47
* Version Independent ID: 68765289-1d77-6e4a-c6fb-1abbc067fcbd
* Content: [Save user and conversation data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
Content updated to simplify the discussion around state management. Take a look at the updated content that was published yesterday.

**Comment by LanderVe** [comment]
Looks a lot better. But I still don't understand why the IStatePropertyAccessor properties are initialized in startup, and not just in the Accessor's constructor
