### ISSUE TITLE
Meeting the Skype criteria

### ISSUE THREAD

**Issue by jwiley84** [MicrosoftDocs/bot-docs#562]
The Bug:

Skype has their own internal list of criteria that must be met to have a bot officially published. While a bot can be connected to Skype and interacted with by the dev (and 99 more people), in order to publish it on the store, you must meet: https://github.com/Microsoft/skype-dev-bots/blob/master/certification/CHECKLIST.md 

This should be mentioned in the doc, at least towards the end. At the very least, there should be a link to that Checklist, for customers who want to fully publish their bot in the Skype Store to see and follow. Simply going to Azure and filling out the 'publish' information for the bot without following Skype's checklist leads to the following error:

![Skype Error](https://user-images.githubusercontent.com/17333688/48859143-2190ea00-ed72-11e8-8db5-500646c2a3bb.png)

**Comment by ivorb** [comment]
@jwiley84 What file where you following when you hit this?

**Comment by ivorb** [comment]
Found it here: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-skype?view=azure-bot-service-4.0

Added to that article, will be published soon

**Comment by ivorb** [comment]
Live
