### ISSUE TITLE
How to log bot reply to user message?

### ISSUE THREAD

**Issue by EugeneFoo** [MicrosoftDocs/bot-docs#563]
Hi, I tried the above sample however it's only show user message to bot information in the context below:

{ type: 'message',
  text: 'Robot begins.',
  from: { id: 'd75e5365-43e9-4a3b-ac31-7ed81890a3b1', name: 'User' },
  locale: '',
  textFormat: 'plain',
  timestamp: '2018-11-21T18:36:18.772Z',
  channelData: { clientActivityId: '1542825376552.5753502099783043.0' },
  entities: 
   [ { type: 'ClientCapabilities',
       requiresBotState: true,
       supportsTts: true,
       supportsListening: true } ],
  channelId: 'emulator',
  conversation: { id: '54b3bc60-edbc-11e8-ac4c-eb4fd75fe5ff|livechat' },
  id: '5606c940-edbc-11e8-9437-ff0e7af78dc6',
  localTimestamp: '2018-11-22T02:36:18+08:00',
  recipient: 
   { id: '8b995130-c487-11e8-ac6c-83c26c0aab90',
     name: 'Bot',
     role: 'bot' },
  serviceUrl: 'http://localhost:57244' }

How can I get the bot reply as well for logging?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8f39f5-1a91-6fdb-3cc0-124b282e9806
* Version Independent ID: 701f9b3c-a893-dee1-d012-760e6f870ec4
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by EugeneFoo** [comment]
do you have the nodejs version for this?

**Comment by JonathanFingold** [comment]
[Here](https://github.com/Microsoft/botbuilder-js/blob/291730346cc5b8242f2e4502baf733de042d6f36/libraries/botbuilder-core/src/transcriptLogger.ts#L47-L54) is the corresponding JS code.

**Comment by EugeneFoo** [comment]
Thank you.
