### ISSUE TITLE
Warning about in-memory storage is unclear

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#564]
Consider this warning:

&gt; [!NOTE] 
&gt; Use bot state manager to store preferences, user name, or the last thing they ordered, but do not use it to store critical business data. For critical data, create your own storage components or write directly to [storage](bot-builder-howto-v4-storage.md).
&gt; In-memory data storage is intended for testing only. This storage is volatile and temporary. The data is cleared each time the bot is restarted.

Looking at the markdown in the source, it seems like these are meant to be two different warnings, and it's a little confusing when they're combined into one in the viewed page. It looks like the part about in-memory storage is a continuation of the thought about the bot state manager, which tends to give the impression that all bot state manager storage is in-memory storage, which would be to say they're the same thing. If these were split into two separate notes then it would be more clear that in-memory storage is just one type of storage that the bot state manager manages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c94a4c9-e988-3b42-a7db-3634d15e9c47
* Version Independent ID: 68765289-1d77-6e4a-c6fb-1abbc067fcbd
* Content: [Save user and conversation data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
The content was updated and one of the warnings is moved to the additional information section.
