### ISSUE TITLE
Why are there two versions of this document?

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#574]
In the Document Details below, it looks like the [Content link](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp) takes me to a document that starts with "A bot is inherently stateless" and the [Content Source link](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md) takes me to a document that starts with "A key to good bot design is to track the context of a conversation." This second document was what I was seeing before as the content on docs.microsoft.com and not just the content source on GitHub. I'm wondering why there's been this change, as there now seem to be two totally different documents. Is the document I'm seeing now on docs.microsoft.com a newer rewritten version, or has it reverted back to some older version, or what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c94a4c9-e988-3b42-a7db-3634d15e9c47
* Version Independent ID: 68765289-1d77-6e4a-c6fb-1abbc067fcbd
* Content: [Save user and conversation data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
There are two documents on state management. One is a conceptual and the other is a how-to. There is also dialog state content that is specific to dialogs. A lot the content has changed in the last couple of days.
