### ISSUE TITLE
Record the outgoing activity

### ISSUE THREAD

**Issue by andyisgentleman** [MicrosoftDocs/bot-docs#577]
How to get the message that the bot reply to the user in the middleware?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c8000f6-59aa-472e-d99b-96356084ff4e
* Version Independent ID: 7219b726-fce3-958f-5084-fcefeef659d5
* Content: [Create your own middleware - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-create-middleware?view=azure-bot-service-4.0&tabs=csaddmiddleware%2Ccsetagoverwrite%2Ccsmiddlewareshortcircuit%2Ccsfallback)
* Content Source: [articles/v4sdk/bot-builder-create-middleware.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-create-middleware.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
Your middleware could register an OnSendActivities handler on the turn context. We don't currently have a how-to on this, but the transcript logger middleware implements this functionality ([C#](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs) / [JS](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/transcriptLogger.ts)).

Please reopen if you need more information.
