### ISSUE TITLE
Proactive bot - botemulator POST 500 directline.postActivity

### ISSUE THREAD

**Issue by SurielRuano** [MicrosoftDocs/bot-docs#579]
I want to test the example of "ProactiveBot" when compiling the project does not show error, but when I send a message from the emulator it tells me "could not send try" LOG "POST 500 directline.postActivity"

Additional

in the file proactive-messages.bot I already enter my appId and my appPassword, and additionally in my service of BotChannelRegistration I already enable a DirectLine channel, and configure my emulator with ngrok and register it in my BotChannelRegistration  settings

**Comment by Kaiqb** [comment]
Is [this](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/16.proactive-messages) the sample you are referring to?

**Comment by SurielRuano** [comment]
Yes

**Comment by JonathanFingold** [comment]
@SurielRuano Our [support team on StackOverflow](https://stackoverflow.com/questions/tagged/botframework) may be a better resource for this issue, as this is outside the scope of the current documentation.

**Comment by SurielRuano** [comment]
@JonathanFingold, thanks, I'll create the question on stackoverflow
