### ISSUE TITLE
Does Bot Framework support Azure AAD OnBehalfOf flow? 

### ISSUE THREAD

**Issue by thomshib** [MicrosoftDocs/bot-docs#580]
Is it possible to implement  On-Behalf-Of flow with Chat bot as mentioned in this url?

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58bf70a-3263-93a1-5bc2-085431a7aa6b
* Version Independent ID: c5e3de2f-58ad-1c6a-e0f3-93489d013114
* Content: [Authenticate requests - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-authentication.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
OAuth2 is supported, see this [topic](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp) that talks about adding authentication to your bot. Although, it does not specifically call out OnBehalfOf flow.
