### ISSUE TITLE
Error in the library

### ISSUE THREAD

**Issue by Yudner** [MicrosoftDocs/bot-docs#582]
Does not recognize StaticCredentialProvider.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43340ba9-4fc5-1202-e2c1-f901f33dc7c7
* Version Independent ID: 236be49b-6c2e-5353-de90-720fd7690a1c
* Content: [Authenticating activities using .NET Core - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-core-authentication?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-core-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-core-authentication.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Yudner** [comment]
In the startup class

**Comment by Kaiqb** [comment]
The one you are referencing is out of date. We'll remove it.  Take a look at this topic: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0 on authentication.
