### ISSUE TITLE
Cannot connect to Azure account

### ISSUE THREAD

**Issue by webtop** [MicrosoftDocs/bot-docs#585]
When trying to log in using the sign-in link in the welcome page, I see this message:

Request Id: 3ee0bac8-6b9d-48ce-8c83-28e1b75c0e00
Correlation Id: f8c7f287-b7aa-43d9-9dfc-e678816427c1
Timestamp: 2018-12-02T08:23:38Z
Message: AADSTS50020: User account 'pallsopp@gmail.com' from identity provider 'live.com' does not exist in tenant 'Microsoft' and cannot access the application '4f28e5eb-6b7f-49e6-ac0e-f992b622da57' in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa3a3039-9b21-fcb9-3fd7-4ae8c69bce93
* Version Independent ID: 36ceb86e-828a-03d7-3245-44ab6ea4c09a
* Content: [Test and debug bots using the Bot Framework Emulator - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-debug-emulator.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-debug-emulator.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
Try asking your question on [Azure Community Support](https://azure.microsoft.com/en-us/support/community/).
