### ISSUE TITLE
Documentation loop

### ISSUE THREAD

**Issue by webtop** [MicrosoftDocs/bot-docs#586]
After reading this article, I click on the Next Steps, which takes me to creating an Azure bot. Clicking on the next steps of that articles brings me back here.
These articles should guide a reader through understanding bots. If there is no clear "next step" the reader should be presented with relevant articles.

Thanks...great articles by the way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf8a24b-7029-247b-3c5c-3902befe0ccf
* Version Independent ID: bcd01444-d332-29e6-2b81-5558bb2d576b
* Content: [How bots work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
@webtop We're removing the **next step** from the **Bot basics** topic, and expanding its **Additional resources** section.
