### ISSUE TITLE
This template depends on flat-map-stream, which is a security concern right now!

### ISSUE THREAD

**Issue by kraghavk** [MicrosoftDocs/bot-docs#596]
The project generated by botbuilder mentioned here has a dependency on flat-map-stream package and this package cannot be trusted anymore. See npm audit output below:

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Critical        Malicious Package

  Package         flatmap-stream

  Patched in      No patch available

  Dependency of   nodemon [dev]

  Path            nodemon &gt; pstree.remy &gt; ps-tree &gt; event-stream &gt;
                  flatmap-stream

  More info       https://nodesecurity.io/advisories/737

found 1 critical severity vulnerability in 2920 scanned packages
  1 vulnerability requires manual review. See the full report for details.

Hope MS will fix this dependency soon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaad3f2-75c5-e958-4734-8925d03d95c6
* Version Independent ID: 8d98b390-5368-1fa4-8cce-3b0cff252eaa
* Content: [Create a bot using Bot Builder SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
@kraghavk Closing here and opening in the **BotBuilder-Samples** repo, which is where the generators are maintained (issue [1044](https://github.com/Microsoft/BotBuilder-Samples/issues/1044))

**Comment by kraghavk** [comment]
@JonathanFingold, thanks for moving it to the appropriate repo.
