### ISSUE TITLE
Is it Azure Bot Service or Bot Framework Service?

### ISSUE THREAD

**Issue by brandonh-msft** [MicrosoftDocs/bot-docs#600]
We have the docs under 'Azure Bot Service' but _in_ the docs we refer to the 'Bot Framework Service'. Is this something different? The same thing? We call it the Bot Framework Emulator... if it's the Azure Bot Service we should call it the Azure Bot Service Emulator (a la Azure Storage, Compute, etc). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf8a24b-7029-247b-3c5c-3902befe0ccf
* Version Independent ID: bcd01444-d332-29e6-2b81-5558bb2d576b
* Content: [How bots work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by Kaiqb** [comment]
These are the same things. The branding is a bit confusing at this time. These will be updated once that final decisions are made.
