### ISSUE TITLE
What else can be done with the .bot file?

### ISSUE THREAD

**Issue by brandonh-msft** [MicrosoftDocs/bot-docs#601]
There should be a link directly in this section for the _full schema_ of the .bot file including available options and their purpose. For reference see what [Azure Functions has done with host.json](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf8a24b-7029-247b-3c5c-3902befe0ccf
* Version Independent ID: bcd01444-d332-29e6-2b81-5558bb2d576b
* Content: [How bots work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs#the-bot-file)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
Work on issue Microsoft/botbuilder-tools#795 is scheduled for the 4.3 release (February). We will add a link to the schema, once it exists.

**Comment by ivorb** [comment]
There is also a link on that page for [managing resources in your .bot file](https://docs.microsoft.com/en-gb/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0). Are you looking for more information than that? Each feature that needs entries in the .bot file has that explained in it's own article, although we may benefit from putting it all in one place.

**Comment by brandonh-msft** [comment]
I think that doc is good, and i see it's linked from the one I wrote this bug against. This coupled with an actual schema + UI in the bot emulator to support would go a long way. 👍
