### ISSUE TITLE
Can I use VS Code to do this?

### ISSUE THREAD

**Issue by SarahSexton** [MicrosoftDocs/bot-docs#604]
The instructions in the documentation only describe how to do this in .NET in Visual Studio 2017. How can I do this in .NET in VS Code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Builder SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by ajforu74** [comment]
Yes, you can use Visual Studio 2015 or 2017. But you should have the .net SDK 4.x with emulator handy!

**Comment by Kaiqb** [comment]
We will also be adding support for VS Code soon.
