### ISSUE TITLE
I need a non-VSIX based path to starting a bot. 

### ISSUE THREAD

**Issue by SarahSexton** [MicrosoftDocs/bot-docs#606]
I need a non-VSIX based path to starting a bot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Builder SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@SarahSexton We don't describe how to do this from scratch in the docs, but one option is to copy one of the sample projects in the [BotBuilder-Samples](https://github.com/Microsoft/BotBuilder-Samples) repo. If you need an alternative way to generate a C# bot project, you can file an issue in that same repo. Let me know if that helps.

**Comment by Kaiqb** [comment]
Yes, that is one way of doing it.
