### ISSUE TITLE
Process events within rich cards

### ISSUE THREAD

**Issue by SarahSexton** [MicrosoftDocs/bot-docs#612]
Confusion around the difference between "imBack" and "postback." Providing feedback that the difference should be better explained. ImBack sends messages as Instant Messages and posts responses in the chat. PostBack may not post a visible response in the chat.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 607856cb-baae-c401-5b34-876b5018771d
* Version Independent ID: 77df1de7-7b2e-a546-1280-a66121039a94
* Content: [Add media to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-add-media-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-media-attachments.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
Updated table for clarity. Fix is in [bot-docs-pr PR 1217](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1217).
