### ISSUE TITLE
Documentation is unclear

### ISSUE THREAD

**Issue by diberry** [MicrosoftDocs/bot-docs#613]
The section titled "Azure subscription account" suggests an azure cli command "msbot clone services ..." is the deployment. However, further in the article, there is a section called "To update your bot code in Azure" that uses "az bot publish". Is the msbot clone services creating a new bot on azure services, or is it pulling down the existing code from an existing bot? Separately, it seems like using the Azure Portal's Deployment center for my existing bot, is also a good scenario and seems more clear/easier than figuring out why I have to clone then published. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot using Azure CLI - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by diberry** [comment]
@ivorb Actually, I've added comments to each line for the doc below:

Go to the Application Registration Portal. Click on Add an app to register your application, create Application Id, and Generate New Password. [dina] what if I already have an existing bot that already has an app id and password? 

Save both application id and the new password you just generated, so you that can use them with msbot clone services command.[dina] the clone command is pulling the existing bot code from Azure down to my local box. - I'm not sure that is clear here. 

To deploy, use the command that applies to your bot. [dina] why is the word deployed used? I think this really means pull the Azure cloud bot code down to the local machine. Correct? Then the app publish further in the article is how the code is deployed.

**Comment by Kaiqb** [comment]
@diberry - submit a PR with changes you'd like to see. Thanks

**Comment by diberry** [comment]
@Kaiqb 

When I edit the page in the browser, the resulting page 404s - https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md. 

Perhaps the content has already been updated or moved around but not published yet?

**Comment by Kaiqb** [comment]
It's live. Not sure why you are getting the error...

**Comment by diberry** [comment]
@Kaiqb It isn't displaying correctly - the text under the C#/js gets pulled into the code block - but I've tried just changing the date only and it still doesn't display correctly. Is there a post-build step after I sign-off that fixes this? 

https://github.com/MicrosoftDocs/bot-docs-pr/pull/1195

**Comment by Kaiqb** [comment]
This topic has been updated significantly. It no longer has the issue raised here.
