### ISSUE TITLE
Basic Multi-Dialog sample (GitHub) ends up in 404 page

### ISSUE THREAD

**Issue by rolandskrumbergsedu** [MicrosoftDocs/bot-docs#615]
If you try to open up Multi-Dialog sample link under Additional resources, it will navigate to GitHub 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0640c5f-df95-00a1-7aaa-0598ab59822f
* Version Independent ID: 2e290ec7-5ddd-6f90-ba64-2c2f88239ab2
* Content: [Manage conversation flow with dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-manage-conversation-flow?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-manage-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-manage-conversation-flow.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
This sample seems to have moved [here](https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp/core-BasicMultiDialog). I'll update the link, and the fix should go live in a few days.

**Comment by joymon** [comment]
The link is not yet updated. Its waste of time when we have to test the link inside and read all the comments to get the working link. Please do the needful

**Comment by JonathanFingold** [comment]
Couldn't find previous PR in which this was addressed. Added fix to bot-docs-pr PR [1260](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1260).
