### ISSUE TITLE
Cortana DOES support adaptive cards

### ISSUE THREAD

**Issue by jwiley84** [MicrosoftDocs/bot-docs#617]
From user @v-daturc on our Botbuilder repo:

> On the Channel Inspector page, the note says that "Cortana does not render Adaptive Cards." Cortana has supported them since February 2018, so you should remove the note.

https://github.com/Microsoft/BotBuilder/issues/5216

**Comment by Kaiqb** [comment]
I am not sure which page the user is looking at, but Channel Inspector is out of date. Currently there is no plan in place for updating it.
