### ISSUE TITLE
Inconsistant dash usage

### ISSUE THREAD

**Issue by managedcoder** [MicrosoftDocs/bot-docs#618]
I noticed in a number of examples that sometimes "-" is used and other times "--" is used even in cases where the doc only calls of a single "-".  In https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-customize?view=azure-bot-service-4.0#updating-an-existing-luis-model  link shows an example of this inconsistency where luisgen only documents single dashes yet "--" is used on the --cs argument:

luis export version --appId [LUIS_APP_ID] --versionId [LUIS_APP_VERSION] --authoringKey [YOUR_LUIS_AUTHORING_KEY] | luisgen --cs [CS_FILE_NAME] -o "\Dialogs\Shared\Resources"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a178d6a6-8037-940c-e8fb-aad548203b92
* Version Independent ID: 181758cf-3495-6848-5808-9dc8234140ab
* Content: [Enterprise Bot Customization - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-customize?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-customize.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-customize.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by ivorb** [comment]
I guess I need more information to address your question - in your pasted example, are you confused why "appId" has "--", but "o" only has one "-"? I did see that there are some inconsistencies in the doc you linked to for the dispatch CLI, but from what I saw luisgen was as expected.

**Comment by managedcoder** [comment]
Yeah, my mistake.  I was not understanding things correctly.  Now that I better understand things I do think there is an issue with what I opened in #730 where single dash was used with full argument name which caused the command to complain.  So it was -secret instead of --secret
