### ISSUE TITLE
Does these Directline samples are updated for botframeworok SDK 4.0?

### ISSUE THREAD

**Issue by vivekjainAco** [MicrosoftDocs/bot-docs#621]
I want to write an test automation for my bot and want to use directline to get the answer and then compare them against the right answer. I have SDK 4.0 in C# for my bot, does this  Direct Line Bot Sample works for it  or i need to change it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d7238a1-4d34-349b-e5cc-f7238c981892
* Version Independent ID: d5945944-58de-1221-d202-d14266bf7dc9
* Content: [Key concepts in the Bot Framework Direct Line API 3.0 - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-concepts?view=azure-bot-service-3.0#)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-concepts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-concepts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
These are SDK v3 samples. If you need assistance, post your question on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework), where support engineers can help.

**Comment by raghukrishnamoorthy** [comment]
Just to be clear then, there are no samples for SDK v4 officially?

**Comment by vivekjainAco** [comment]
seems so that Microsoft has not documented any test automation process for SDK 4.0.
