### ISSUE TITLE
JavaScript code snippets use undefined variable

### ISSUE THREAD

**Issue by navzam** [MicrosoftDocs/bot-docs#624]
In the "Send attachments" and "Send a hero card" sections, the JavaScript code snippets use a variable called `reply` that is never defined.

Based on the referenced sample, I think the missing line is

```
const reply = { type: ActivityTypes.Message };
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 607856cb-baae-c401-5b34-876b5018771d
* Version Independent ID: 77df1de7-7b2e-a546-1280-a66121039a94
* Content: [Add media to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-add-media-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-media-attachments.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
You are correct. I'll updated the snippet code. Fixes should go live in a few days.

**Comment by navzam** [comment]
@JonathanFingold @EricDahlvang I don't think the referenced commit fixes this issue

**Comment by JonathanFingold** [comment]
@navzam Eric's commit is part of a different process. You can follow [bot-docs-pr/#1217](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1215) PR to see when the fix is merged.
