### ISSUE TITLE
Validators

### ISSUE THREAD

**Issue by jamsoft** [MicrosoftDocs/bot-docs#628]
You've detailed that validators are avaiable, what they do and how to write one but completely neglect to document how they are wired into the flow ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72538432-fde5-22ab-7997-8a34b11aa24e
* Version Independent ID: c469fa5b-2590-ee16-1491-51b90c069204
* Content: [Gather user input using a dialog prompt - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-prompts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
@jamsoft Looking back at this, the information is hidden near the top of the article. I'll add a note and highlight corresponding code in the validation section itself.

Here's the relevant C# code from the sample:
```csharp
            // Create the dialog set and add the prompts, including custom validation.
            _dialogSet = new DialogSet(_accessors.DialogStateAccessor);
            _dialogSet.Add(new NumberPrompt<int>(PartySizePrompt, PartySizeValidatorAsync));
            _dialogSet.Add(new ChoicePrompt(LocationPrompt));
            _dialogSet.Add(new DateTimePrompt(ReservationDatePrompt, DateValidatorAsync));
```

**Comment by JonathanFingold** [comment]
Added in the missing context to the **Implement validation code** section. The update should go live in a couple days.
