### ISSUE TITLE
Topic ends without explaining how to download the source code that was just created

### ISSUE THREAD

**Issue by drub0y** [MicrosoftDocs/bot-docs#629]
One of the benefits of the "Bot Service First" approach (vs locally first) is understood to be that some source code was created up in the cloud based on the template the person chose. This article ends with the following sentence:

> Now, learn how to manage your bot and start working with its source code.

However, the button that follows ("How bots work") takes you to a concepts article that doesn't mention anything about downloading the source code. Perhaps a new section is needed before "Next Steps" that explains how to download the source code??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9e2e6-b901-9e27-d070-701922396a4c
* Version Independent ID: c29a68b2-886d-2cec-0ce7-c49c586d7ea8
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by scoupeau** [comment]
If you use compilation option  in Azure you can download the bot code. Unfortunately the .bot file does not run well (if you try to use services like qna, nlp or dispatch) and I had problems with node restify module. I was not able to run locally the bot.

**Comment by yochay** [comment]
@scoupeau, the .bot file is encrypted and you can find the password in your App Service setting tab.

**Comment by yochay** [comment]
@drub0y do you find the path of creating a bot via ABS and then downloading the code useful?

**Comment by Kaiqb** [comment]
Added steps to download the code and how to update botFilePath and botFileSecrets in appsettings.json or .env file.

**Comment by kprpg** [comment]
OK. So after one downloads the code, I was thinking you can load it up in an editor like Visual Studio OR code. But the article does not talk about how to use which editor to work with the code.
