### ISSUE TITLE
ngrok did not get installed following this tutorial

### ISSUE THREAD

**Issue by jeffmartinxyz** [MicrosoftDocs/bot-docs#630]
After reboot I had to manually install ngrok. If you have chocolatey installed you can run:  choco install ngrok      

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Builder SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
ngrok is not installed when you install the Emulator. I'll add a link to the quickstarts: [tunneling (ngrok)](https://github.com/Microsoft/BotFramework-Emulator/wiki/Tunneling-(ngrok)). Fix will be in [Microsoft/bot-docs-pr PR 1217](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1217).
