### ISSUE TITLE
Skype calling feature

### ISSUE THREAD

**Issue by jasomr** [MicrosoftDocs/bot-docs#631]
I can not find any info about the Skype calling feature and code examples for the SDK - v4.x. There is something for the SDK - v3.x.
Does it mean that calling is not supported in the SDK - v4.x?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 486e6e6d-a7aa-2876-dfec-edc9d8a0d1ef
* Version Independent ID: aa6e5bfa-bbda-39ad-559e-62c92cbf5f86
* Content: [Connect a bot to Skype - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-skype?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-skype.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-skype.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **RobStand**

**Comment by JonathanFingold** [comment]
@jasomr The Skype Calling feature has the same documentation for both the [v3](https://docs.microsoft.com/azure/bot-service/bot-service-channel-connect-skype?view=azure-bot-service-3.0#calling) and [v4](https://docs.microsoft.com/azure/bot-service/bot-service-channel-connect-skype?view=azure-bot-service-4.0#calling) SDK.

We do not yet have sample code for an SDK v4 Skype bot. You can request one by opening an issue in the [Microsoft/BotBuilder-Samples](https://github.com/Microsoft/BotBuilder-Samples) repo.
