### ISSUE TITLE
Style for choicePrompts

### ISSUE THREAD

**Issue by NejibK** [MicrosoftDocs/bot-docs#632]
Hi !
Can you provide an example for defining the style of a choicePrompt ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72538432-fde5-22ab-7997-8a34b11aa24e
* Version Independent ID: c469fa5b-2590-ee16-1491-51b90c069204
* Content: [Gather user input using a dialog prompt - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-prompts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
@NejibK Once you create your ChoicePrompt object, you can explicitly set its "list style" by setting its_style_ property. The values are defined in the `ListStyle` enumeration ([C#](https://github.com/Microsoft/botbuilder-dotnet/blob/79339fe77935dc37bcd48df93a43f77596ea4048/libraries/Microsoft.Bot.Builder.Dialogs/Choices/ListStyle.cs#L10-L36) / [JS](https://github.com/Microsoft/botbuilder-js/blob/3292b7c46c0e8fb6c26389c4c9c7efd8abf9dcd1/libraries/botbuilder-dialogs/src/prompts/prompt.ts#L17-L42)).

If that is enough to unblock you, please close this issue.
