### ISSUE TITLE
Please identify the nuget package necessary for this sample code

### ISSUE THREAD

**Issue by SarahSexton** [MicrosoftDocs/bot-docs#633]
The code on this page does not work until / unless the developer imports a nuget package mentioned NOWHERE on this page. It is assumed to be in the sample. "Prerequisites: The code in this article is based on the DialogPromptBot sample. You'll need a copy of the sample in either C# or JS." In real-world scenarios, developers are trying to make their own code work, not download an unrelated sample. Please identify the nuget package necessary for this sample code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72538432-fde5-22ab-7997-8a34b11aa24e
* Version Independent ID: c469fa5b-2590-ee16-1491-51b90c069204
* Content: [Gather user input using a dialog prompt - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-prompts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by Kaiqb** [comment]
We are taking a different approach to content based on the feedback from several hackathons we've conducted with customers. The feedback was to base content on samples. The samples have all the dependencies in them. Any code that you see is from the sample. That is why the sample is listed as a pre-req.
