### ISSUE TITLE
Migration from Bing Speech to unified speech

### ISSUE THREAD

**Issue by prwani-microsoft** [MicrosoftDocs/bot-docs#636]
Hi, The instructions in this article refer to integrating "bing speech" api in "WebChat" control. Please update this article to leverage new speech api - https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-js-browser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4689475d-3454-3eb7-9211-453867a3a1ae
* Version Independent ID: 321658a5-145b-a72c-1fe4-60b5a707e5d4
* Content: [Enable speech in Web Chat - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat-speech?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-channel-connect-webchat-speech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-webchat-speech.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by ivorb** [comment]
There is work to integrate this coming up, but Bing Speech no longer works and has been removed
