### ISSUE TITLE
npm install -g yo generator-botbuilder fails

### ISSUE THREAD

**Issue by newthings4learning** [MicrosoftDocs/bot-docs#637]
this step is failing with the below error -
C:\SelfLearning\msBot&gt;npm install -g yo generator-botbuilder
npm ERR! Unexpected end of JSON input while parsing near '...,"inquirer":"~0.3.1",'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vipulba\AppData\Roaming\npm-cache\_logs\2018-12-14T11_27_12_300Z-debug.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaad3f2-75c5-e958-4734-8925d03d95c6
* Version Independent ID: 8d98b390-5368-1fa4-8cce-3b0cff252eaa
* Content: [Create a bot using Bot Builder SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
@newthings4learning I tried uninstalling and reinstalling Yeoman (yo) and the generator-botbuilder pacakges and was not able to reproduce your error. I'm including a minimally edited log below as reference.

Note that Node version 8.5 or higher is required

You may be able to get help with this issue from our support team on StackOverflow: https://stackoverflow.com/questions/tagged/botframework.

```shell
npm un -g yo generator-botbuilder
```
```text
removed 939 packages in 10.134s
```
```shell
npm i -g yo generator-botbuilder
```
```text
npm WARN deprecated ms-rest-js@1.0.455: Package has been renamed to @azure/ms-rest-js
npm WARN deprecated ms-rest-azure-js@1.0.176: Package has been renamed to @azure/ms-rest-azure-js
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
...\AppData\Roaming\npm\yo -> ...\AppData\Roaming\npm\node_modules\yo\lib\cli.js
...\AppData\Roaming\npm\yo-complete -> ...\AppData\Roaming\npm\node_modules\yo\lib\completion\index.js

> spawn-sync@1.0.15 postinstall ...\AppData\Roaming\npm\node_modules\yo\node_modules\spawn-sync
> node postinstall

> yo@2.0.5 postinstall ...\AppData\Roaming\npm\node_modules\yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version
√ yo version

Everything looks all right!
+ yo@2.0.5
+ generator-botbuilder@4.2.1
added 914 packages from 414 contributors in 30.782s
```
