### ISSUE TITLE
Proactively messaging a new user who has not initiated chat with the bot before

### ISSUE THREAD

**Issue by newthings4learning** [MicrosoftDocs/bot-docs#638]
i have a use case where the user keeps changing almost daily or it can also change more than once in a single day. my bot needs to inform the user that is currently assigned to a specific task. i will have the email id or skype id of this person.
is there anyway my bot can message this user who has never messaged the bot before ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc28a40-716e-22bc-8944-15f0a8b0d5c2
* Version Independent ID: 86252b0d-94e2-2ea6-ed17-fc32ae38e6fc
* Content: [Get notification from bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by newthings4learning** [comment]
Hi @ivorb, thanks for your reply. Let me further explain my use case. We have list of all the users and their details (Name, Skype Email Id etc.) in a repository. In a given day we can create N number of new tasks.
Now what we are trying to do is that when we create a new task and assign it to a user, we want to message him on Skype via our bot. Similarly if a task was earlier assigned to user1, but the moved to a new user2, we want to message user2 via our bot.

Doesicrosoft bot framework support such use cases ? Or is there any good alternate solution to it?

Would appreciate any help or suggestions on this.

**Comment by Kaiqb** [comment]
@newthings4learning - You might want to post your question on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework) where support engineers might be able to help.
