### ISSUE TITLE
Where do you get the configuration details for the dispatch section of the bot file?

### ISSUE THREAD

**Issue by andybeak** [MicrosoftDocs/bot-docs#645]
In general the Microsoft documentation is quite weak on bot configuration.  There isn't an easily accessible page that outlines exactly how it works.  In this specific page there is no treatment given to explaining which app id to use in the dispatch section of the bot file.

If it is the LUIS application id then why do we not use the qna application?

```
{
            "type": "dispatch",
            "serviceIds": [
                "50",
                "201",
                "7"
            ],
            "name": "nlp-with-dispatchDispatch",
            "appId": "",
            "authoringKey": "",
            "subscriptionKey": "",
            "version": "Dispatch",
            "region": "",
            "id": "161"
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by JonathanFingold** [comment]
@andybeak We recently updated the how to deploy using the Azure CLI article. There's a section on how to use the Emulator to [update your .bot file](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#update-the-bot-file). We're waiting on the dev team to publish the .bot file schema, and we'll link to it once it's available.

With respect to deploying samples, they assume that you will not be touching the associated .bot file. It's not ideal, but that how the dev team has decided to manage the samples. Please reopen if this doesn't address your issue.
