### ISSUE TITLE
No discussion of creating the dispatch model

### ISSUE THREAD

**Issue by andybeak** [MicrosoftDocs/bot-docs#646]
This tutorial completely omits training dispatch.  You will encounter the following error if you try to use this page.
```
[botInitializationError]: Error: No dispatch model found in .bot file. Please ensure you have dispatch model created and available in the .bot file. See readme.md for additional information
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by DanDev33** [comment]
Hi Andy, thanks for your feedback. In the article" Use multiple LUIS and QnA models" under #manually-create-LUIS-apps, we walk through the LUIS training process for home-automation.  The last sentence in that section states:  
“Once completed, repeat these same steps for both your locally downloaded 'weather.json' and 'nlp-with-dispatchDispatch.json' files.”  
nlp-with-dispatchDispatch.json builds and Trains the dispatch model, BUT this is not very clear! We'll rework this section to provide more clarity. Thanks for helping us to continue improving our docs!

**Comment by hansmbakker** [comment]
For this sample you provided us with a ready-made dispatch model, but what is the best way to create this ourselves?

Is it a manual action to create the dispatch data from the other models or is there a way to automatically compile the dispatch model from the other models?

**Comment by andybeak** [comment]
Thanks, I really struggled to create the model using the documentation.  This link helps.

**Comment by DanDev33** [comment]
Thank you Hans & Andy for your feedback. I am going to place a description and link within the Additional Resources section of this article so the people who are looking to update the sample LUIS model, or create a new one, have easy access to this information. 
Thanks for helping us to continue improving our docs!

**Comment by Kaiqb** [comment]
Updated the additional infomration section.

**Comment by hansmbakker** [comment]
Thanks to both of you!
