### ISSUE TITLE
Samples no longer available

### ISSUE THREAD

**Issue by jboeshart** [MicrosoftDocs/bot-docs#647]
All of the links to sample applications appear to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3bc8631-6157-a3aa-431a-fc65abc6c752
* Version Independent ID: d8d2de9c-082d-090f-f6d0-93e74555089e
* Content: [Create data-driven experiences with Azure Search - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-search-azure?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-search-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-search-azure.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @matthewshim-ms
* Microsoft Alias: **v-shimma**

**Comment by ivorb** [comment]
Looks like old links in our v3 content.

We'll have to update that in the docs when we can, but for now you can find our samples here, in your preferred language folder: https://github.com/Microsoft/BotBuilder-Samples.

For you @jboeshart go here to find the samples: https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore. Do note, samples have changed and moved around

**Comment by Kaiqb** [comment]
Fixed.
