### ISSUE TITLE
Build Issue in App Service Editor

### ISSUE THREAD

**Issue by link2rn** [MicrosoftDocs/bot-docs#648]
When I tried to build my code in app service editor it shows error like:
Installing Kudu Sync
An error has occurred during web site deployment.
'npm' is not recognized as an internal or external command,
operable program or batch file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f0f2ff1-f19c-c66d-53ac-b9569e0a4601
* Version Independent ID: 0ef27a09-09cf-e09a-ec40-9c86b1150bde
* Content: [Recognize intents and entities with LUIS - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-luis-dialogs?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-luis-dialogs.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-luis-dialogs.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by ivorb** [comment]
This appears to be a problem with your npm install. Do you have npm added to your path?

**Comment by Kaiqb** [comment]
You should download the code and build it locally and then deploy the code. Closing the issue for now.
