### ISSUE TITLE
Second user doesn't see any jobs started by first user

### ISSUE THREAD

**Issue by erinha** [MicrosoftDocs/bot-docs#650]
By "first user", I mean the first window of the Bot Emulator and "second user" is the second window of the Bot Framework. These are two separate windows, not tabs. 

The bot appears to be working, but I'm not able to see any jobs returned when the second user types "show", after the first user has typed "run" a few times. When the second user types "done &lt;job#&gt;" with a job# started by the first user, my bot says "Sorry no job with &lt;job#&gt;".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc28a40-716e-22bc-8944-15f0a8b0d5c2
* Version Independent ID: 86252b0d-94e2-2ea6-ed17-fc32ae38e6fc
* Content: [Get notification from bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by JonathanFingold** [comment]
@erinha I sync'd and ran the Node.js sample today. Both conversations were able to view all of the created jobs, and able to complete jobs and receive notification of job completion.

If the sample is not working in your environment, tou can get help from our support team. https://stackoverflow.com/questions/tagged/botframework.

![image](https://user-images.githubusercontent.com/35047199/50120175-93d9da80-0209-11e9-89d0-ebaa35d28e20.png)

**Comment by erinha** [comment]
I had converted a previous sample to match the code used in this sample and the difference was in index.js, I was passing ConversationState to ProactiveBot constructor (as per other samples) instead of a BotState object that takes a StorageKeyFactory callback. Once I changed my code to use a BotState object, the code worked.
