### ISSUE TITLE
The .values property that hangs off of stepContext in JS is not properly documented.

### ISSUE THREAD

**Issue by lucashuet93** [MicrosoftDocs/bot-docs#652]
The values property on stepContext in a waterfall dialog is not documented at all. It is extremely useful and simplifies state management, and should be properly documented as a result.

**Comment by JonathanFingold** [comment]
@lucashuet93 There is a small amount of documentation on the values property of the waterfall set context:

- There's a mention of the _values_ property in the [Waterfall step context properties](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-dialog#waterfall-step-context-properties) section of the [Dialogs library](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-dialog) conceptual topic.
- The sample code for [Create advanced conversation flow using branches and loops](https://docs.microsoft.com/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow) demonstrates how to access the _values_ property.

**Comment by JonathanFingold** [comment]
Fixing in MicrosoftDocs/bot-docs-pr. This update should go live in a few days.
