### ISSUE TITLE
This page is linked under which navigation links/navigation section on the right ?

### ISSUE THREAD

**Issue by pkaushik23** [MicrosoftDocs/bot-docs#655]
The url is also not descriptive. it is under How-To/Concepts/Samples or  Tutorials. Having a a navigation connection helps while learning through the official documentation.  I here from https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-conversation-flow?view=azure-bot-service-4.0 but not sure how to go back. (except the back button ofcourse) Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b58151c-02ca-4504-215a-491454df91fb
* Version Independent ID: 355c58d3-06ab-e25c-c750-03fc6abac2c2
* Content: [Conversations within the Bot Builder SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-conversations?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-conversations.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-conversations.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by JonathanFingold** [comment]
@pkaushik23 The conversation flow topic is out of date and was removed from our TOC. I will replace the link to it with more relevant links:
- [Create your own prompts to gather user input](https://docs.microsoft.com/azure/bot-service/bot-builder-primitive-prompts)
- Use dialogs to [implement sequential conversation flow](https://docs.microsoft.com/azure/bot-service/bot-builder-dialog-manage-conversation-flow)

**Comment by JonathanFingold** [comment]
Fix is in [Microsoft/bot-docs-pr#1217](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1217). The fix may not go live for a couple weeks due to the holidays.

**Comment by v-kydela** [comment]
@JonathanFingold - I can still see this document

**Comment by JonathanFingold** [comment]
@v-kydela I removed links to this page from the offending article, but I forgot to "retire" the article so the page redirects to somewhere useful. I'll do that tomorrow.
