### ISSUE TITLE
Text in diagram isn't visible in dark theme

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/bot-docs#656]
Please make sure of the diagram visibility in dark theme also

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6b66ee3-d953-6283-b983-7ed7fdd92aac
* Version Independent ID: e4107511-07ab-e83c-2921-0b32e63bccc1
* Content: [Information bot scenario - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-scenario-informational?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-scenario-informational.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-scenario-informational.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @brianrandell
* Microsoft Alias: **v-brra**

**Comment by JonathanFingold** [comment]
@mganeshphani I've removed transparency from the image, so it will have a white background in any theme. Fix should go live within a couple days.
