### ISSUE TITLE
Documentation and samples are outdates. 

### ISSUE THREAD

**Issue by cloudedturtle** [MicrosoftDocs/bot-docs#657]
Git samples and code snippets in docs are not updated. Trying to build code from the docs does not result in a working bot. This combined with the fact that the links to the sample are not accurate made for a task of finding the right information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a16806-95d6-7c66-3b85-b2ace211f367
* Version Independent ID: c8565ece-392a-fb56-e911-8a5dd5555dee
* Content: [Send welcome message to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=csharp%2Ccsharpmulti%2Ccsharpwelcomeback)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Dashel
* Microsoft Alias: **dashel**

**Comment by DanDev33** [comment]
Thank you for this feedback Matt. The pointers in this article should be pointing to sample 03.welcome-user 
This will be fixed and published shortly.

**Comment by DanDev33** [comment]
Link fixed - closed
