### ISSUE TITLE
Is there's update for CosmosDB?

### ISSUE THREAD

**Issue by EugeneFoo** [MicrosoftDocs/bot-docs#659]
Hi, I just opening up another 30 days trial cosmos db and test it out, the interface now need to force to key-in partition key by default.

And since this structure change, when i link it to the bot storage, it failed to load.

The error message I received:

Cross partition query is required but disabled. Please set x-ms-documentdb-query-enablecrosspartition to true, specify x-ms-documentdb-partitionkey, or revise your query to avoid this exception.

I had checked my CosmosDB setting the Enable cross-partition query was enabled.
Is that the library for botbuilder-Azure need to update? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8f39f5-1a91-6fdb-3cc0-124b282e9806
* Version Independent ID: 701f9b3c-a893-dee1-d012-760e6f870ec4
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript#using-cosmos-db)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
@DanDev33 - this article needs to be updated. There are changes in the Azure portal that impact the creation of CosmosDB.

**Comment by DanDev33** [comment]
Hi Eugene,
Thanks for your feedback! What you have encountered is an acknowledged bug arising from changes in CosmosDb. A solution for this is targeted to be available in the next release. In the meantime, there is a simple case workaround. If you are trying to access a smaller set of documents, create a new database using only the partition key /id and your query should succeed. I will be updating our existing documentation to include this.

**Comment by EugeneFoo** [comment]
Hi Dan,

Great to hear that!

Wait for the new documentation then, thanks!

**Comment by DanDev33** [comment]
Partition key info is live now, so closing this Issue.
