### ISSUE TITLE
Import "Home Automation" json error

### ISSUE THREAD

**Issue by DONGZHUPENG** [MicrosoftDocs/bot-docs#660]
It raised error in the first step when importing "Home-Automation" json file download from github:
BadArgument: Failed to parse application json. Parameter name: applicationJsonString 

Did anyone ever tried it successfully?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by DanDev33** [comment]
Thanks for your feedback. It may not be immediately evident from the link in the article you referenced, but the 4 .JSON files are hosted at the following GitHub location: https://github.com/Microsoft/BotFramework-Samples 
This is a different location from the main GitHub C# or JS sample at https://github.com/Microsoft/BotBuilder-Samples  
Cloning or downloading the BotFramework-Samples repository will allow you to access and use the .JSON files and manually build the LUIS and QnA Maker apps for your sample. Based on your feedback, I'll modify the article to make this separate location clear for anyone wanting to download these files.

**Comment by DanDev33** [comment]
closed - article updated.
