### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by baole** [MicrosoftDocs/bot-docs#662]
I would like to create messages with attachments and come across this document. However, examples are done with either .Net or Node.js. Is there a JSON Schema or JSON example of message with attachments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c205b864-640c-a101-8468-6227d8f2e7cb
* Version Independent ID: a8c5bdba-01f3-46ec-1c73-a8fabd4ccf0f
* Content: [Add rich card attachments to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-rich-card-attachments?view=azure-bot-service-3.0#adaptive-card)
* Content Source: [articles/dotnet/bot-builder-dotnet-add-rich-card-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-add-rich-card-attachments.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by ivorb** [comment]
Looks like you're using the v3 version of the Bot Framework - both v3 and v4 are definitely focused on .NET and JS currently, but there are REST options available. 

See if this is what you're looking for?
https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-media-attachments?view=azure-bot-service-4.0

**Comment by baole** [comment]
it works. Thanks
