### ISSUE TITLE
Page reference from learning broken

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/bot-docs#664]
This page is being referenced from AISchool.. looks broken.. please fix asap
https://aischool.microsoft.com/en-us/conversational/learning-paths/getting-started-with-azure-bot-framework/hosting-your-bot-with-azure-bot-service?selectedItemId=7N1yv36UtqMQMAGsUQQi6Y

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0416d5e0-52de-a6c6-d9e7-0e719bd56ec8
* Version Independent ID: e2d8ddfe-d33f-0682-84b8-d0b48edb6c89
* Content: [redirect_url: /bot-framework/bot-service-build-online-code-editor - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/azure-bot-service-build-options?view=azure-bot-service-4.0)
* Content Source: [articles/azure-bot-service-build-options.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/azure-bot-service-build-options.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kaiqb**

**Comment by ivorb** [comment]
fixed the redirect
