### ISSUE TITLE
Seemingly no mention of card styling 

### ISSUE THREAD

**Issue by ryanvolum** [MicrosoftDocs/bot-docs#665]
**Describe the bug**
I'm using Hero Cards and having trouble understand how I can style them. Through some brute force, I discovered that I'm able to use some markdown syntax to achieve my desired effect. 

**To Reproduce**
1. Attempt to make Hero Card text bold, or italics, or try to create a new line on a card
2. Search for syntax to demonstrates this. 

**Screenshots**
Ultimately, I was able to create a new line using `\r`, and was able to create bold text using markdown syntax: `**bold**`:
![image](https://user-images.githubusercontent.com/3891951/50470709-87baef00-0966-11e9-9062-aa9e21ac5304.png)

It's clear that these cards support some styling, but nothing seems to indicate or demonstrate this.

**Comment by JonathanFingold** [comment]
@ryanvolum Would a link into the [ativity spec](https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-activity/botframework-activity.md#message-activity) or just mentioning that markdown is generally supported, but support may vary by channel?

**Comment by JonathanFingold** [comment]
Added note about markdown in the topic, and added the reference to the schema in the additional resources section. Affected topics: **Send an receive text message** and **Add media to messages**. See PR for specifics. Changes should go live within a week.
