### ISSUE TITLE
Step 3: "BotAuthenticator failed to authenticate incoming request!"

### ISSUE THREAD

**Issue by JouretC** [MicrosoftDocs/bot-docs#667]
Resolved by updating Nuget package System.IdentityModel.Tokens.Jwt
https://social.msdn.microsoft.com/Forums/en-US/74c2534c-3bd7-443f-a636-d387c9947dbb/botauthenticator-failed-to-authenticate-incoming-request?forum=MachineLearning

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 995ea08b-4ae3-a724-143c-f90a08eedbb7
* Version Independent ID: 1c00c3c2-6133-9f24-1176-52ec31b9abf3
* Content: [Troubleshooting Bot Framework Authentication - Bot Service](https://docs.microsoft.com/nl-be/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0#PW)
* Content Source: [articles/bot-service-troubleshoot-authentication-problems.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-troubleshoot-authentication-problems.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by ivorb** [comment]
will be fixed with next release. thanks for the heads up!

**Comment by Kaiqb** [comment]
@ivorb - was the fix published?
