### ISSUE TITLE
How can I define "mention" entities for TextBlock's Adaptive cards

### ISSUE THREAD

**Issue by baole** [MicrosoftDocs/bot-docs#668]
I would like to make an adaptive card which includes several TextBlocks which are in turn may include mention. Here is an example of my payload:

```
{
  "type": "message",
  "entities": [
    {
      "mentioned": {
        "id": "user id go here",
        "name": "Duy Le"
      },
      "text": "<at>Duy Le</at>",
      "type": "mention"
    }
  ],
  "attachments": [
    {
      "content": {
        "body": [
          {
            "text": "<at>Duy Le</at>  mentioned",
            "wrap": true,
            "type": "TextBlock"
          }
        ],
        "type": "AdaptiveCard",
        "version": "1.0",
        "${'$'}schema": "http://adaptivecards.io/schemas/adaptive-card.json"
      },
      "contentType": "application/vnd.microsoft.card.adaptive"
    }
  ]
}
```

It works perfectly if I changed attachments/TextBlock to "text". Any help?

Mentions: https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-create-messages?view=azure-bot-service-3.0#entities
TextBlock: https://adaptivecards.io/explorer/TextBlock.html

**Comment by Kaiqb** [comment]
We don't have any additional information on the behavior of the adaptive cards. You might want to ask this question in AdaptiveCards repo or forum.
