### ISSUE TITLE
Not able to build the SDK.

### ISSUE THREAD

**Issue by mata-ashutosh** [MicrosoftDocs/bot-docs#670]
Dear Team,

I followed the steps explained above but I am not able to build the SDK. Please check.

Thanks
Ashutosh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 748e48cd-09ac-2aaa-8dab-9e0615c70652
* Version Independent ID: 4b25c9d1-dcab-ea00-3835-0fe4b72943dd
* Content: [Create a bot using Bot Builder SDK for Java - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/java/bot-builder-java-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/java/bot-builder-java-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/java/bot-builder-java-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by Kaiqb** [comment]
The Java and Python SDKs are still in early development. The topic that you looked at was outdated and has been updated with a link to the wiki page on GitHub. You can track the progess of the SDK there.
