### ISSUE TITLE
GitHub BotFramework-Samples Files are missing

### ISSUE THREAD

**Issue by jlwilliamson8** [MicrosoftDocs/bot-docs#672]
The GitHub BotFramework-Samples are supposed to include the following files required to build a sample "bot". (files listed below)

However, those files do not exist in this Git location. 
Am I missing something ? 
Please help. 
Thx !!!

home-automation.json, 
weather.json, 
nlp-with-dispatchDispatch.json, 
QnAMaker.tsv

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by DanDev33** [comment]
Thanks for your feedback! The pointer in our article was pointing to the BotFramework-Samples repository, but not to the subdirectory holding these 4 files. We are updating the article to correct this. In the meantime you can find these 4 sample files here: 
https://github.com/Microsoft/BotFramework-Samples/tree/master/SDKV4-Samples/dotnet_core/nlp-with-dispatch

**Comment by jlwilliamson8** [comment]
Thanks Dan.


James

**Comment by Kaiqb** [comment]
The links point to the correct samples in C# and JS.
