### ISSUE TITLE
initialDialogId property lacks explanation

### ISSUE THREAD

**Issue by ryanvolum** [MicrosoftDocs/bot-docs#673]
In the code in this document each ComponentDialog has this line of code: 
```js
        // ID of the child dialog that should be started anytime the component is started.
        this.initialDialogId = dialogId;
```

I was surprised to find that whenever we don't set this property, the dialog just doesn't run. I don't really understand what this is doing, but would expect that if it's a vital part of using Component Dialogs, that it would be explained in the documentation.

**To Reproduce**
1. Copy code from Reuse Dialogs doc
2. Remove `this.initialDialogId = dialogId;`
3. Observe that the dialog just hangs quietly 

**Update**: Upon digging into the source code, I discovered that it's not necessary to set this property, but that if you don't, the first dialog added will be set as the initialDialog. In my case, the first dialog I added was a `ChoicePrompt`, since I had no idea that order mattered. 

Beyond being undocumented, this behavior feels odd. Developers will likely see code that doesn't set it and be confused when the correct dialog doesn't run. If the order that dialogs are added determines their ability to run, this needs to be declared up front. Furthermore, having multiple ways that developers can set initialDialogId will likely confuse them - I'd suggest either doubling down on the _order matters_ approach, _or_ adding an additional property in the `ComponentDialog` constructor, _or_ relying on a well documented setter method.

**Comment by ryanvolum** [comment]
For reference, I explain the current `initialDialogId` behavior in [this wiki](https://github.com/ryanvolum/menu-bot/wiki#creating-component-dialogs)

**Comment by JonathanFingold** [comment]
@ryanvolum I can add some clarification to the article.

For the code change to the SDK, can you open an issue in either the https://github.com/Microsoft/botbuilder-dotnet or https://github.com/Microsoft/botbuilder-js/ repo?

**Comment by JonathanFingold** [comment]
Fixing article in MicrosoftDocs/bot-docs-pr.

Adding a short section about component dialogs in the component dialog how-to...

## About component dialogs

With a component dialogs, you can create independent dialogs to handle specific scenarios, breaking a large dialog set into more manageable pieces. Each of these pieces has its own dialog set, and avoids any name collisions with the dialog set that contains it.

Use the _add dialog_ method to add dialogs and prompts to the component dialog. The first item you add with this method is set as the initial dialog, but you can change this by explicitly setting the _initial dialog_ property in the component dialog's constructor. When you start a component dialog, it will start its _initial dialog_.
