### ISSUE TITLE
luis bot

### ISSUE THREAD

**Issue by Diro92** [MicrosoftDocs/bot-docs#675]
Hello.  There is an error that keeps showing up. It says:

System.ArgumentException: '"&lt;luis appid&gt;" is not a valid LUIS application id.'

When trying to test that with the emulator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf8a24b-7029-247b-3c5c-3902befe0ccf
* Version Independent ID: bcd01444-d332-29e6-2b81-5558bb2d576b
* Content: [How bots work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by Kaiqb** [comment]
Feel free to reopen the issue if you are still running into issues. Or, you can use [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework) where support engineers monitor issues reported by customers.
