### ISSUE TITLE
Please provide more info about the BotState object

### ISSUE THREAD

**Issue by erinha** [MicrosoftDocs/bot-docs#676]
It seems as though the BotState object in index.js is crucial to the conversation state being shared between two users (if you pass a ConversationState to the ProactiveBot instead, the sample doesn't work) and I think it's the StorageKeyFactory callback that is the key to this (no pun intended). 

In the sample, the callback is simply a hard-coded string. Is it just that the BotState needs to return the same string for each conversation in order to know about each other or is it more complicated than that?

Can you please provide some more information about how that callback works? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc28a40-716e-22bc-8944-15f0a8b0d5c2
* Version Independent ID: 86252b0d-94e2-2ea6-ed17-fc32ae38e6fc
* Content: [Get notification from bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=javascript#tabpanel-issues-open)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by JonathanFingold** [comment]
@erinha Adding this to the how-to article, in the **Define job data and state** section. Let me know if this helps clarify, or if I need to add more explanation.

We'll extend _bot state_ to define our own, bot-wide state management object. The bot framework uses the _storage key_ and the turn context to persist and retrieve state. See [managing state](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-state) for more information.
