### ISSUE TITLE
I can't image the chance to POST to "https://smba.trafficmanager.net"

### ISSUE THREAD

**Issue by FengXiaohe** [MicrosoftDocs/bot-docs#678]
Take the direct line as example, we post to "https://directline.botframework.com", when should we post to "https://smba.trafficmanager.net" ?

And I have tried via the tool of PostMan to post to "https://directline.botframework.com", the response is "Unauthenticated".  The following is the request content and response.

[Request]
POST /apis/v3/conversations HTTP/1.1
Host: smba.trafficmanager.net
Content-Type: application/json
Authorization: Bearer [The token I got before]

{
    "type": "message",
    。。。。。。。
}

[Response]
{
    "error": {
        "code": "BadArgument",
        "message": "Unauthenticated"
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03c49826-bbc8-1589-7b80-ad46c6cbcac6
* Version Independent ID: 327925a7-ec0d-0d00-f3c6-16f62cdf05b9
* Content: [Create a bot with the Bot Connector service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-quickstart?view=azure-bot-service-3.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
@jameslew - do you know?

**Comment by Kaiqb** [comment]
Doesn't seem possible - closing
