### ISSUE TITLE
Reconnecting to conversations

### ISSUE THREAD

**Issue by calvin-evans** [MicrosoftDocs/bot-docs#679]
The docs seem to imply that you can use tokens and secrets interchangeably, however, when you GET /conversations/{conversationId} using a secret you get a 400 "MissingProperty" error saying no user ID specified. It looks like it's trying to decode the secret as a JWT. 

This puts one in a tricky situation as you have no way to retrieve a conversation once a token has expired forcing you to either:
a) start a new conversation every session or
b) repeatedly renew all tokens constantly (which doesn't seem viable at scale)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c428e7-100f-2c36-9e0e-08edb41ce127
* Version Independent ID: 03ae66b5-1ba5-d1f3-f2bb-ebb8e8bb8d94
* Content: [Reconnect to a conversation - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by calvin-evans** [comment]
Update: this only happens when *Enhanced Authentication Options* is enabled in the DirectLine settings:

![image](https://user-images.githubusercontent.com/1681236/52208021-234d5280-2877-11e9-878a-cd234f527997.png)

Hopefully, that will help anyone else who runs into this issue. 

In light of this, it doesn't seem to be a bug, more a case of obscure docs. I'll leave this open in case you want to rectify.

**Comment by Kaiqb** [comment]
Fixed.

**Comment by aschemel** [comment]
@kaiqb, as I see your fix is:

"If you have "Enhanced authentication option" enabled in the Direct Line settings, you might get a 400 "MissingProperty" error saying no user ID specified." 

I'm not sure if that's actually right, this should (as far as I understand) work even when the Enhanced Authentication is enabled. 

It seems like a bug.

**Comment by Zack-Strife** [comment]
So there's no fix ? We're stuck we a 400 and a false error a long as the enhanced authentication is activated ?
More than obscure doc, it still looks like a bug and is problematic
