### ISSUE TITLE
"Bad format of conversation ID" error happened when start a conversation

### ISSUE THREAD

**Issue by FengXiaohe** [MicrosoftDocs/bot-docs#681]
hi,

I want to start a conversation via REST API, and as the following the "Bad format of conversation ID" error happened. Could you find where is wrong ?

[Request 1]
First, I post the following request to get the Access Token.
POST : https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token
Content-Type : application/x-www-form-urlencoded
Body :
grant_type=client_credentials&client_id=<My Bot's App Id>&client_secret=<my Bot's secret>&scope=https%3A%2F%2Fapi.botframework.com%2F.default

[Request 2]
POST : https://smba.trafficmanager.net/apis/v3/conversations
Content-Type : application/json
Authorization : Bearer <the Access Token got via Request 1>
Body:
{
    "bot": {
        "id": "<My Bot's Id>",
        "name": "<My Bot's Name>"
    },
    "isGroup": false,
    "members": [
        {
            "id": "abcd",
            "name": "recipient name"
        }
    ],
    "topicName": "News Alert"
}

[ Response of Request 2 ]
{
    "error": {
        "code": "BadSyntax",
        "message": "Bad format of conversation ID"
    }
}
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bb730d0-5973-2b5a-3594-18338cf58812
* Version Independent ID: 1785b946-10bd-6cd1-ac6b-f70cf6c9bd12
* Content: [Send and receive messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-send-and-receive-messages?view=azure-bot-service-3.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-send-and-receive-messages.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-send-and-receive-messages.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
Based on [this](https://gitter.im/Microsoft/BotBuilder/archives/2017/08/21) issue, it could be related to bot id or url used. If you still need help, reach out to support engineering team on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework).

**Comment by LeoCN7** [comment]
Hi, I have the same problem. Could you solve it?

**Comment by NPrice99** [comment]
Hi

This is a documentation issue.  Step 10 Get the groupID and ChannelID you do not need to decode the channelID.

Regards

Nigel
