### ISSUE TITLE
Correct QnA samples for ludown

### ISSUE THREAD

**Issue by luiscantero** [MicrosoftDocs/bot-docs#682]
The 3 .lu snippets for QnA are wrong. When appended together, they generate the wrong output.

The right format would be as follows:
![qna_lu](https://user-images.githubusercontent.com/1353540/50729439-c7898f80-1139-11e9-8183-a00896271958.PNG)

* The answer block begins with 3 backticks.
* Apparently the keyword `markdown` right after them is not necessary, it makes no difference if it's there or not.
* The answer block ends with 3 backticks that start at the beginning of the line.

See [this example](https://github.com/Microsoft/botbuilder-tools/blob/master/packages/Ludown/ChitChat/Friendly/AboutBot.lu).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35d1244-e389-9ee3-8eb8-18610bc81d56
* Version Independent ID: d41d1c45-fed6-80f0-189a-2c5c051dbb25
* Content: [Manage bots using CLI tools - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tools?view=azure-bot-service-4.0#create-and-manage-luis-applications-using-luis-cli)
* Content Source: [articles/bot-builder-tools.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tools.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
@luiscantero Thanks for catching this. Fixing in MicrosoftDocs/bot-docs PR.
