### ISSUE TITLE
Remove instruction to use botservice extension

### ISSUE THREAD

**Issue by Kagigz** [MicrosoftDocs/bot-docs#684]
By @stevengum : 
"The new version of msbot does not use the botservice extension, so you are not required to call az extension add -n botservice."

This documentation still mentions the botservice az extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot using Azure CLI - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
Fix submitted in Microsoft/bot-docs-pr#1235.
