### ISSUE TITLE
Edit doc: no proj-file for JS

### ISSUE THREAD

**Issue by Kagigz** [MicrosoftDocs/bot-docs#685]
The documentation says  proj-file is the name of the startup project file name, while this argument is not required for JS according to the Azure CLI doc (and an "unrecognized argument" error shows if the proj-file is specified).
PS: Link to edit doc is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d36b63c1-a0d4-cba9-b5b5-8618ec848e11
* Version Independent ID: a6bc9f4e-8da1-650e-9ea5-9802b64880f3
* Content: [Deploy bots from botbuilder-samples repo - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-samples?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-samples.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-samples.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
Fix is in Microsoft/bot-docs-pr PR 1235.
