### ISSUE TITLE
Update disclaimer about deprecation

### ISSUE THREAD

**Issue by Urmade** [MicrosoftDocs/bot-docs#686]
The Bot State Service API is deprecated now and when uploading the Bot (without specifing an additional storage) to Azure the developer gets the error message "The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.". The other way round if you use the table storage pre-configured in the template code of the Bot Service (Node.js v3 SDK Basic Bot) the bot won't work locally. It would be great if you could emphasize this in the first disclaimer as it might confuses devs to think that the State Service although not recommended would still work in production.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04cf96e3-3840-3418-6957-ad0bb97aefba
* Version Independent ID: 34be9a7f-9aa8-af2f-eb5e-3a4b9765d574
* Content: [Manage state data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-state?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/rest-api/bot-framework-rest-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
Thanks for your suggestion. Given that SDK v4 is out, the older version SDK docs are only updated for high-pri security issues.
