### ISSUE TITLE
code is obsolete

### ISSUE THREAD

**Issue by pancongying** [MicrosoftDocs/bot-docs#687]
When i try to use scorable dialog, it gives the warning below:
'builder.Update(Conversation.Container)' is obsolete: 'Containers should generally be considered immutable. Register all of your dependencies before building/resolving. If you need to change the contents of a container, you technically should rebuild the container. This method may be removed in a future majar release.'

So is there any updates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1242ecb9-f6cd-59fb-94f3-d8ec0496c759
* Version Independent ID: fb7c80c8-08f4-c866-bf9e-aa6cf0948ee4
* Content: [Global message handlers using scorables - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-scorable-dialogs?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-scorable-dialogs.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-scorable-dialogs.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @matthewshim-ms
* Microsoft Alias: **v-shimma**

**Comment by Kaiqb** [comment]
That seems to be ASP.NET/MVC issue. You might want to ask our [support engineers](https://stackoverflow.com/questions/tagged/botframework).
