### ISSUE TITLE
v4 of the SDK Doesn't Use appsettings.config

### ISSUE THREAD

**Issue by torynfarr** [MicrosoftDocs/bot-docs#689]
This article seems a bit specific to v3 of the Bot Framework. There is no appsettings.config file if you're using v4 of the Bot Framework. Your Microsoft App ID and app password are stored in the .bot file under the endpoint service with the value for the app password encrypted using your bot's secret.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 995ea08b-4ae3-a724-143c-f90a08eedbb7
* Version Independent ID: 1c00c3c2-6133-9f24-1176-52ec31b9abf3
* Content: [Troubleshooting Bot Framework Authentication - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-troubleshoot-authentication-problems.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-troubleshoot-authentication-problems.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by JonathanFingold** [comment]
The v4 C# bot templates still make use of the **appsettings.json** file.

**Comment by torynfarr** [comment]
Sure, but that's JSON not XML. And it contains the bot file path and bot secret not the Microsoft App ID and password. It's a very different thing then what is mentioned in this article.

**Comment by JonathanFingold** [comment]
Sorry, yes. I've been jumping between too many articles. You are correct.

**Comment by ivorb** [comment]
updated, will be pushed live shortly
