### ISSUE TITLE
Just to say it is a great article!

### ISSUE THREAD

**Issue by DmitryBLR** [MicrosoftDocs/bot-docs#690]
It is a great article!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81843db8-8ae5-be19-45e4-43ba0ac604de
* Version Independent ID: 319f4345-5023-8b1a-e369-4ef9355e61d5
* Content: [Principles of bot design - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-principles?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-design-principles.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-principles.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by ivorb** [comment]
Glad to hear it, thanks!
