### ISSUE TITLE
Authentication part is unclear

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/bot-docs#691]
1. It is unclear how authentication settings should be added to the bot configuration (it looks like https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/csharp/EnterpriseBotSample/BotServices.cs#L128-L138 expects the configuration in the .bot file).
2. It looks like the authentication settings expect an Azure Active Directory v2 configuration? Can it be used with Azure Active Directory v1?
3. How will this work locally in the emulator?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by hansmbakker** [comment]
I found the needed command for `1.` in https://github.com/Microsoft/botbuilder-tools/issues/713 but that was really not the place where I expected to find it.

**Comment by hansmbakker** [comment]
It is unclear how the token response should be handled in the Enterprise Bot Template.

When follow the steps in https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0#authentication:
- I add `AddDialog(new AuthenticationDialog(_services.AuthConnectionName));` to the constructor of `MainDialog`
- I add `var authResult = await dc.BeginDialogAsync(nameof(AuthenticationDialog));` as the last statement in the `OnStartAsync` method of `MainDialog`

then I get the question to log in, but the `FinishLoginDialog` of `AuthenticationDialog` is never called. Instead the token response ends up in `OnEventAsync` of `MainDialog`.

How is this `AuthenticationDialog` supposed to be used?

**Comment by miojoffey** [comment]
@hansmbakker: have you figured out how to properly use AuthenticationDialog? i have the same problem here. can't find any solid solution to this one for days already. thanks

**Comment by hansmbakker** [comment]
I don't know if it is the correct way, so I would really appreciate somebody from the bot builder team having a look at this.

@cleemullins @johnataylor since you work on the Bot Framework, could you help out here or could you suggest who can give us confirmation that this is the way to go?

I did the following:
- In `MainDialog`, update `OnEventAsync(…)` to :
```csharp
protected override async Task OnEventAsync(DialogContext dc, CancellationToken cancellationToken = default(CancellationToken))
{
    if (dc.Context.Activity.Name == "tokens/response")
    {
        var result = await dc.ContinueDialogAsync();
        return;
    }
    // Check if there was an action submitted from intro card
    else if (dc.Context.Activity.Value != null)
    {
        dynamic value = dc.Context.Activity.Value;
        if (value.action == "startOnboarding")
        {
            await dc.BeginDialogAsync(nameof(OnboardingDialog));
            return;
        }
        //else if(value)
    }
}
```

- In the dialog where you want to use authentication, do the following:
  - add this to the constructor: `AddDialog(new AuthenticationDialog(_botServices.AuthConnectionName));`
  - add the following code as the first `WaterfallStep`:
```csharp
public async Task<DialogTurnResult> CheckLogin(WaterfallStepContext sc, CancellationToken cancellationToken)
{
    var adapter = sc.Context.Adapter as BotFrameworkAdapter;
    var tokenResponse = await adapter.GetUserTokenAsync(sc.Context, _botServices.AuthConnectionName, null, cancellationToken);
    if (tokenResponse is null)
    {
        await _responder.ReplyWith(sc.Context, CreateProjectResponses.ResponseIds.ShouldLoginMessage);
        // If Bot Service does not have a token, send an OAuth card to sign in
        var authResult = await sc.BeginDialogAsync(nameof(AuthenticationDialog));
        return authResult;
    }
    else
    {
        return await sc.NextAsync(tokenResponse);
    }
}
```
  - use the `tokenResponse` in the next `WaterfallStep`:
```csharp
TokenResponse tokenResponse = null;
if(sc.Result is TokenResponse)
{
    tokenResponse = sc.Result as TokenResponse;
}

var user = await GetProfile(sc.Context, tokenResponse);
```

**Comment by miojoffey** [comment]
I think your solution here at least gives light to how its supposed to be used. @hansmbakker thank you

**Comment by narihane** [comment]
any updates? @hansmbakker @miojoffey

**Comment by Kaiqb** [comment]
We've added this [topic ](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-authentication?view=azure-bot-service-4.0)on auth that link to additional content for v4.
