### ISSUE TITLE
Error sending this message to your bot: HTTP status code Forbidden

### ISSUE THREAD

**Issue by Jhanbury** [MicrosoftDocs/bot-docs#692]
Hi, 

I have followed the docs and I am now receiving the following error when I try to test with the web chat:
There was an error sending this message to your bot: HTTP status code Forbidden

I updated my Application settings to include the following:

MicrosoftAppId
MicrosoftAppPassword
Bot File Location

The only difference from the post is that I am using my own bot which required me to add the bot file location
Are there any additional steps or requirements that have been added following the creation of this post?
Any help you can give would be appreciated 

Thanks again

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your C# bot using Visual Studio - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
To get help on this issue, use [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework), where support engineers monitor customer reported issues.
