### ISSUE TITLE
Bot AppID and AppSecret issue while creating

### ISSUE THREAD

**Issue by ikivanc** [MicrosoftDocs/bot-docs#693]
Hi Team,

I tried below command after I got the error when I leave AppID and AppSecret empty in my command. I created AppID and AppSecret manually on dev.microsoft.com. Here's the command I use.

> msbot clone services --name "EnterpriseBot" --luisAuthoringKey "MY_LUIS_KEY" --folder "DeploymentScripts\EN" --location "westus" --appId "MY_APP_ID_CREATED_AT_DEV_MICROSOFT_COM" --appSecret "MY_SECRET_KEY_CREATED_AT_DEV_MICROSOFT_COM"

Output on Azure is like below
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidBotData\",\r\n    \"message\": \"Bot is not valid. Errors: Id: Id is already in use.. \"\r\n  }\r\n}"
    }
  ]
}

Edit: For couple of hours I tried many combinations including changing msbot-clone-services.js files in

> C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\msbot\bin 

But it still got same errors.

After changing region to westeurope fixed the problem.

> msbot clone services --name "EnterpriseBot" --luisAuthoringKey "MY_LUIS_KEY" --folder "DeploymentScripts\EN" --location "westeurope" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by ivorb** [comment]
I'm confused - you created your ID and password on the web, then when trying to use them in the westus region it claimed they were already in use... but switching that region to westeurope fixed it? Did that last command that worked also provision a new appID and password?

**Comment by darrenj** [comment]
I suspect this issue might be because you need to have a more unique name for your bot, EnterpriseBot is definitely already used. Can you try something  like EnterpriseBotivanc?

**Comment by Kaiqb** [comment]
This content has been removed from the library. Closing the issue.
