### ISSUE TITLE
msbot clone - sintax error  

### ISSUE THREAD

**Issue by fraangel** [MicrosoftDocs/bot-docs#694]
Hi all,
I'm facing problem trying to start this sample: 
([https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/14.nlp-with-dispatch/README.md](link)
I followed all the instruction and when I arrived to the point to run the command 
`msbot clone services --name "<your_bot_name>" --luisAuthoringKey <LUIS-authoring-key> --code-dir "." --location westus --sdkLanguage "Node" --folder deploymentScripts/msbotClone --verbose `
I get the error: 

> WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code C6MPFEF2J to authenticate.
> ERROR: Unable to provision Microsoft Application automatically. To manually provision a Microsoft Application, go to the Application Registration Portal at https://apps.dev.microsoft.com/. Once you manually create you application, pass the application Id and password as parameters for bot creation.

 
Reading all the documents related, I tryed to solve the problem adding **"appId"** and **"appSecret"** like below:
`msbot clone  services --name "My_nlp-with-dispatch" --luisAuthoringKey <luis auth key> --code-dir "." --location westeurope --sdkLanguage "Node" --folder deploymentScripts/msbotClone --appId <my app id> --appSecret "<my app secret>"`

And I got the following error: **INCORRECT COMMAND SINTAX**, anyone can help? 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by Kaiqb** [comment]
Please log an issue in the Sample repo: https://github.com/Microsoft/BotBuilder-Samples/. You can also post your question on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework), and someone from the support team should be able to help.
