### ISSUE TITLE
Auto login

### ISSUE THREAD

**Issue by msekkappan** [MicrosoftDocs/bot-docs#695]
Is there a way to login with the existing token in the browser?  I am trying to avoid prompting if the user is already logged in.  How do I do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d80e0b-f1b7-175b-128d-0fb12f17ae36
* Version Independent ID: 1ed9006a-bf0b-9aaa-d180-9d2cb0c09524
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0#notes-on-the-token-retrieval-flow)
* Content Source: [articles/bot-builder-tutorial-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tutorial-authentication.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **JonathanFingold**

**Comment by CoHealer** [comment]
Re-applying support label for aggregation inclusion

**Comment by mdrichardson** [comment]
@msekkappan 	I apologize for not replying to this issue sooner. You can only do this if you're using [WebChat](https://github.com/Microsoft/BotFramework-WebChat). See the [SSO Sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/19.a.single-sign-on-for-enterprise-apps) for how to do so. Basically, you pass the existing token through `channelData` to your bot.

**Comment by mdrichardson** [comment]
Closing as this is likely answered and there has been no response
