### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by raghukrishnamoorthy** [MicrosoftDocs/bot-docs#696]
The sample was 11.qnamaker from the samples repository.
qnamaker created and then followed the deployment script to the T. Did not change a single thing anywhere.
 
The deployment provisions resources but fails at this point.

Error as follows:
Creating QnA Maker KB [qnamaker-QNA]
qnamaker create kb --subscriptionKey 1ca6f1921ed14010bf7ffd6fe4faf515 --name "qnamaker-QNA" --in deploymentScripts\msbotClone\34.qna --wait --msbot -q
Command failed: qnamaker create kb --subscriptionKey 1ca6f1921ed14010bf7ffd6fe4faf515 --name "qnamaker-QNA" -Failed. Error: { "operationState": "Failed", "createdTimestamp": "2019-01-08T05:52:44Z",
"lastActionTimestamp": "2019-01-08T05:52:45Z", "userId": "0fa58a46aae7429c91b4d4fbc890c893", "operationId": "5b1e31f6-7578-4c88-a972-ff232b1b7193"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by raghukrishnamoorthy** [comment]
I downloaded a zip yesterday and did it so that I was working with the latest version of the samples.

**Comment by raghukrishnamoorthy** [comment]
Would you like any more information?

**Comment by raghukrishnamoorthy** [comment]
I'm getting a different error now.

Creating QnA Maker KB [qnamaker-QNA]
qnamaker create kb --subscriptionKey [Redacted] --name "qnamaker-QNA" --in deploymentScripts\msbotClone\34.qna --wait --msbot -q
Command failed: qnamaker create kb --subscriptionKey [Redacted] --name "qnamaker-QNA" --in deploymentScripts\msbotClone\34.qna --wait --msbot -qError: {    "code": "Unspecified",    "message": "Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key."}
Usage: msbot clone services [options]

Steps to repro.

Follow the docs here https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs
1. Create a qna service
2. Download the samples and open the 11.qnamaker from csharp_dotnetcore
3. Add the KBID, hostname, subscriptionkey, endpoint key to the .bot file for qna service like so

{
        "type": "qna",
        "name": "QnABot",
        "kbId": "[Redacted]",
        "subscriptionKey": "[Redacted]",
        "endpointKey": "[Redacted]",
        "hostname": "https://raghuqna.azurewebsites.net/qnamaker",
        "id": "117"
      }

4. Run the bot locally with bot emulator. works like a charm

Now to the deployment part. Following the docs at https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-samples?view=azure-bot-service-4.0&tabs=csharp

1. az login to login to the account
2. az account set --subscription "<azure-subscription>" to set current subscription
3. msbot clone services --folder deploymentScripts/msbotClone --location "<geographic-location>" --verbose --proj-file "<your-project-file>" --name "<bot-name>" with westus for location, project filename for proj-file and botname that is unique. 
4. Run the command and azure provisions all the neccessary resources and when it reaches the qnamaker createkb it breaks.

A few things:

1. Running the command separately like 
qnamaker create kb --subscriptionKey 2d179ea766014534a43fc420399931e4 --name "qnamaker-QNA" --in deploymentScripts\msbotClone\34.qna --wait --msbot -q
works. It outputs

Succeeded..................              done
{
  "type": "qna",
  "name": "qnamaker-QNA",
  "id": "[Redacted]",
  "kbId": "[Redacted]",
  "subscriptionKey": "[Redacted]",
  "endpointKey": "[Redacted]",
  "hostname": "https://[redacted]-qnahost.azurewebsites.net"
}

Note that the subscriptionId here is the same id for which we get the message "Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key" when the command runs as a part of the msbot clone flow.

2. I have not changed a single line of code in the sample except the .bot file. This is the latest code downloaded an hour back

3. I'm also unsure what 34.qna does and what is going on here in this snipped from the .recipe file

{
      "type": "qna",
      "id": "34",
      "name": "qnamaker-QNA"
 },

4. The msbot, qnamaker and az cli are all the latest versions.


Any help would be hugely appreciated guys. I am willing to provide any more information that you need to help fix this issue.

**Comment by JonathanFingold** [comment]
The **Deploy bots from botbuilder-samples repo** article you are following is for deploying unmodified samples in the samples repo.

Use the instructions in the How-To / Deploy / [Deploy your bot using Azure CLI](https://docs.microsoft.com/azure/bot-service/bot-builder-deploy-az-cli) topic., which uses the `az bot publish` command, instead of `msbot clone services`.

Sorry about the confusion. The bot publication pipeline is still in flux, but the steps in the how-to article should work for you.

**Comment by Kaiqb** [comment]
Feel free to reopen if you still run into issues.

**Comment by raghukrishnamoorthy** [comment]
Hi Jonathan,

The link you provided describes creating a Echo bot on Azure first, then downloading the bot, then making config changes and then republishing.

This seems like a very roundabout way. I already have a bot with me.

I will again describe what i want.

1. I downloaded a sample bot
2. I made a few changes, added a few cognitive services and tested it locally. It works.
3. I want to publish this to Azure.

We've already covered that the deploying samples tutorial does not work for modified samples just like you said.

The link you provided however creates a new bot on Azure first and then downloads, makes a few changes and then deploys it. That is not what I want. I do not want to create a basic bot on azure then download it and make changes.

I have a bot, I need to publish it to Azure. I do not want to create a template bot on Azure which is what the link you provided does.

Would you like any more information?

**Comment by JonathanFingold** [comment]
@raghukrishnamoorthy This is more a problem with our description than with the process.
- We have you create a web app bot so that Azure provisions resources.
- We have you download the bot to a temporary file so that you can copy resource information from the wep app bot's .bot file.
- When you publish your bot, you are uploading your local bot's code, replacing the underlying code of the web app bot, but continuing to use the provisioned resources.

Let me know if this addresses your concern or not.

We are working on the deployment topics, and I'll try to clean up the description as part of that effort.

**Comment by raghukrishnamoorthy** [comment]
Yes this does address my concern. I was looking for a way similar to how the "msbot clone" way of deployment provisions services on Azure with the actual local bot without having to go through the cycle you mentioned above.

This should do for now though. Thank you for your time Jonathan.
