### ISSUE TITLE
reference to luis.cs should be luisbot.cs

### ISSUE THREAD

**Issue by jhealy** [MicrosoftDocs/bot-docs#697]
&gt;&gt; Next, in the Luis.cs file, the bot gets this LUIS instance.
Should be LuisBot.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Add natural language understanding to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
@jhealy Thanks for catching this. Fixing in MicrosoftDocs/bot-docs PR [1260](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1260).
