### ISSUE TITLE
Instruction and Code do not compliant with V4

### ISSUE THREAD

**Issue by SigmaSolutions** [MicrosoftDocs/bot-docs#700]
The instructions as is will result ambiguous dependencies! Please update the article to compliant with V4.
 
I have used Bot Builder V4 SDK template "EmptyBot" to create the project. Modify the bot class with above code (using Async). It works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc04415a-5587-3c0c-9447-aee46e5e1928
* Version Independent ID: 1067e35b-07e1-2f47-6bda-d92b024c09d0
* Content: [Create a Direct Line bot and client - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-direct-line?view=azure-bot-service-4.0&tabs=cscreatebot%2Ccsclientapp%2Ccsrunclient)
* Content Source: [articles/v4sdk/bot-builder-howto-direct-line.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-direct-line.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-royhar
* Microsoft Alias: **v-royhar**

**Comment by Kaiqb** [comment]
This content is not up to date. Once it is updated, it will be published as part of the docs.
