### ISSUE TITLE
No Dictionary created in first sample

### ISSUE THREAD

**Issue by quickbasic22** [MicrosoftDocs/bot-docs#701]
error here I copy from further down and still doesn't work.

// show user new list of saved messages.
         await context.SendActivityAsync($"The list is now: {string.Join(", ", logItems.UtteranceList)}");
         
         // Create Dictionary object to hold new list of messages.
         {
             changes.Add("UtteranceLog", logItems);
          };

further down I copied this into first sample but doesn't work

// create a note for the first time, with a non-null, non-* ETag.
var note = new Note { Name = "Shopping List", Contents = "eggs", ETag = "x" };

var changes = Dictionary&lt;string, object&gt;();
{
    changes.Add("Note", note);
};
await NoteStore.WriteAsync(changes, cancellationToken);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8f39f5-1a91-6fdb-3cc0-124b282e9806
* Version Independent ID: 701f9b3c-a893-dee1-d012-760e6f870ec4
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by DanDev33** [comment]
Hi David,
Thanks for your feedback. similar to the class definition of UtteranceLog in the example, I added a class defintion for "Note" to the sample code as follows:
 public class Note : IStoreItem
{
      public string Name { get; set; } = "";
       public string Contents { get; set; } = "";
       public string ETag { get; set; } = "x";
}

Now your code, as shown below, both creates and stores a Dictionary entry into _myStorage:

// create a note for the first time, with a non-null, non-* ETag.
var note = new Note { Name = "Shopping List", Contents = "eggs", ETag = "x" };
var changes = new Dictionary<string, object>();
{
        changes.Add("Note", note);
};
// Save new list to your Storage.
await _myStorage.WriteAsync(changes, CancellationToken);

retrieving your note back required the following code changes from the reading of the utteranceList:

// retrieve stored notes
Note noteItems = null;
string[] noteList = { "Note" };
noteItems = _myStorage.ReadAsync<Note>(noteList).Result?.FirstOrDefault().Value;

I hope this class definition helps you out with your bot project.

**Comment by DanDev33** [comment]
Closed - hopefully this resolved David's issue.
