### ISSUE TITLE
Link to Github repo?

### ISSUE THREAD

**Issue by kevinclarkneudesic** [MicrosoftDocs/bot-docs#702]
Can this not just be a link to Github?  Why do I have to use Visual Studio 2017 when I just want to use VS Code.  I understand most .NET developers are probably not familiar with Git, but just seems far simpler to clone a repo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Builder SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
You could, but this is a simpler experience for people who want to ramp-up in a step-by-step manner.

**Comment by kevinclarkneudesic** [comment]
Well then why not offer both. -_- And it is not very simple at all, I about threw the computer out the window trying to follow the "quick start".  It is WAY easier just calling the LUIS endpoint directly rather than using this whole Bot Builder SDK, and assuming I have to write code to handle LUIS intent anyways, then it makes more sense too.
