### ISSUE TITLE
Deployment Docs for V3

### ISSUE THREAD

**Issue by mdrichardson** [MicrosoftDocs/bot-docs#704]
I occasionally/frequently see support requests pop up for deploying V3 bots, which the current doc instructions don't cover. Clicking the link here:

![image](https://user-images.githubusercontent.com/40401643/51064200-57ed2780-15b3-11e9-8b78-373d6abb3283.png)

...is currently broken and I can't find V3-specific deployment docs.

There aren't many differences but I do have a couple of suggestions for V3:

1. Duplicate the doc for V3 and remove the following sections since the V3 samples and the V3 bots generated when creating the Azure Web App Bot Resource don't (always) contain .bot files:
    * Download the bot from Azure
    * Decrypt the downloaded .bot file
    * Use the downloaded .bot file in your project
2. Replace the above sections with (or just add something like *Note: If you are deploying a V3 bot...* to the V4 page):

### Create a .bot file for your project (if it's missing)

In the root folder of your project, run:

```cmd
msbot init
```

### Add your new production endpoint to your local bot

After running the `az bot create` command, your console should have generated an output message with an `endpoint`. If not, you can retrieve your endpoint by opening your Web App Bot Resource in Azure, stay in the Overview tab, and copy the "Messaging endpoint". Then run:

```cmd
msbot connect endpoint --endpoint "https://<your-endpoint>.azurewebsites.net/api/messages" --name production --appId "<application-id>" --appPassword "<application-password>" --secret "<bot-file-secret>"
```

### Prepare for Publication

Depending on how you created your V3 bot, it may need some additional deployment preparation with the following command:

```cmd
az bot prepare-publish --name <bot-resource-name> --resource-group <resource-group-name> --proj-name <project-file-name> --sln-name <solutions-file-name>
```

| Option | Description |
|:---|:---|
| --name | The resource name of the bot in Azure. |
| --resource-group | Name of resource group. |
| --proj-name | For C#, use the startup project file name (without the .csproj) that needs to be published. It must still be called in Node.js, but leave it blank, using `--proj-name ""` |
| --sln-name | For C#, use the start up solutions project file name that needs to be published. It must still be called in Node.js, but leave it blank, using `--sln-name ""` |

---

*Note: I know the `.bot` file isn't needed for V3 bots, but it may make adding the proper endpoints easier. I don't have enough experience with V3 to really say definitively.*

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot using Azure CLI - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
We are revisiting the deployment path to make it easier for users to deploy bots. Once that is done we'll update the docs.
