### ISSUE TITLE
Documentation of ActionTypes

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/bot-docs#707]
The `ActionTypes` are currently not too well documented (there is no intellisense documentation or API documentation for it, the documentation is scattered over multiple pages); the sample on this page just uses `ActionTypes.ImBack` without explaining why and with no link as to where to find more explanation, even though it looks relevant for this page.

The types are briefly explained at https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-rich-cards?view=azure-bot-service-4.0. However there are not many details added, for example for the `signin` type and a discussion about whether to use an `OAuthPrompt` or this action?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53446ad1-6b8c-1ccb-6e78-2cb14358b1c3
* Version Independent ID: 8b0fcc34-e624-64a9-adc8-6c8fa3031f54
* Content: [Use button for input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-suggested-actions?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-add-suggested-actions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-suggested-actions.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by hansmbakker** [comment]
There is more documentation at https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-actions#adaptive-card-actions

**Comment by Kaiqb** [comment]
There is a topic on adding [authentication](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp) to your bot that covers these.

**Comment by shikelong** [comment]
+1.
No documentation about ActionTypes.

**Comment by v-kydela** [comment]
@Kaiqb - This issue shouldn't have been closed. That authentication document doesn't cover the [card action types](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/ActionTypes.cs), and even if it did it would be off topic for that document.
