### ISSUE TITLE
Bug in JavaScript code for setAlarmDialog

### ISSUE THREAD

**Issue by erinha** [MicrosoftDocs/bot-docs#709]
The code to define the prompts used in the conversation flow for the SetAlarmDialog result in the error:
Property 'dialogs' is private and only accessible within class 'ComponentDialog&lt;O&gt;'.

Current code: 
this.dialogs.add(new DateTimePrompt('datePrompt'));

The code should use this.addDialog(...) instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9577ff-cf56-e5de-84c3-bfe10aab5368
* Version Independent ID: b5d62753-f87b-4673-b09b-a5a3fd9360e8
* Content: [Reuse dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-compositcontrol.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-compositcontrol.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
@erinha If I understand correctly, you're looking at code in the constructor for the SetAlarmDialog class:
```javascript
class SetAlarmDialog extends ComponentDialog {
    constructor(dialogId) {
        super(dialogId);

        // ID of the child dialog that should be started anytime the component is started.
        this.initialDialogId = dialogId;

        // Define the prompts used in this conversation flow.
        this.dialogs.add(new DateTimePrompt('datePrompt'));
        ...
```
Since the initialDialogId is already set, this is functionally the same here as `this.addDialog(new DateTimePrompt('datePrompt'))`.

I've tried the code both ways, and they appear to work identically, without generating errors. Are you using TypeScript instead of JavaScript here?

**Comment by JonathanFingold** [comment]
I've since updated this code snippet to use `this.addDialog`.
