### ISSUE TITLE
Article mentions WaitForToken but this method is not used in the code that is listed in the article and also not in the linked code samples

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/bot-docs#710]
The title explains it all:
In the section [Wait for a TokenResponse Event](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp#wait-for-a-tokenresponseevent), the `WaitForToken` method is mentioned, but it is not shown in the code that is listed in the article.

Also, the article refers to 2 code samples, but the `WaitForToken` method is also not used in [24. MS Graph Authentication](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/24.bot-authentication-msgraph/GraphAuthenticationBot.cs) nor in [18. Authentication](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/18.bot-authentication/AuthenticationBot.cs)

This is very confusing since it makes you wonder whether you're looking in the wrong place or whether you're reading documentation for the wrong version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp#notes-on-the-token-retrieval-flow)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
@hansmbakker I think the sample has been updated over time, and the description is now in error. I'll check with the sample author as to what this should be now.

**Comment by JonathanFingold** [comment]
Still waiting to hear back from the dev. Sorry for the delay.

**Comment by JonathanFingold** [comment]
The article has since been updated, and `WaitForToken` is no longer mentioned.
