### ISSUE TITLE
Declare the class - twice info

### ISSUE THREAD

**Issue by rvinothrajendran** [MicrosoftDocs/bot-docs#714]
Please check the declare the class section , same paragraph has displayed twice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc28a40-716e-22bc-8944-15f0a8b0d5c2
* Version Independent ID: 86252b0d-94e2-2ea6-ed17-fc32ae38e6fc
* Content: [Get notification from bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by JonathanFingold** [comment]
@rvinothrajendran Thanks for catching this. Fixing in MicrosoftDocs/bot-docs PR [1260](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1260).
