### ISSUE TITLE
How to automate tests for a complete bot

### ISSUE THREAD

**Issue by vivekjainAco** [MicrosoftDocs/bot-docs#715]
I wrote a test program which is testing individual servies, for example QnA and LUIS.  and I can save the results in a file to compare with the expected results. Is there any documentation to test the complete Bot instead of mocking individual features because it is consuming a lot of time and analysis. Sometimes the Json responses from the Bot framework and from the service APIs are different and have to synch the test program. 

It would be nice if you can point me out to test automation for the complete Bot.

Thanks in advance.
vivek 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b24220ea-6a9f-2c17-e213-73fa577eb1fa
* Version Independent ID: dae9c683-5c77-c2c1-8dee-27a009487af5
* Content: [Testing and debugging guidelines - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-testing-debugging?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-testing-debugging.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-testing-debugging.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
@vivekjainAco - there isn't additional documentation on testing at this time. You can ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework) that is monitored by Bot Framework support engineers.
