### ISSUE TITLE
Is SMS a channel

### ISSUE THREAD

**Issue by alathrop** [MicrosoftDocs/bot-docs#716]
SMS seems to be mentioned as channel at the beginning of this article ("For example, if the bot sends a message that contains a card with action buttons to the SMS channel...."). But SMS is not listed under the channels section on the left for documentation. Is SMS a regular channel and if so, where is the documentation?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca402ef4-c22b-dbe6-eea8-a3e564e10495
* Version Independent ID: 659f8981-078c-79a8-06e4-0b403aa2d53b
* Content: [Configure a bot to run on one or more channels - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-channels?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-manage-channels.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-manage-channels.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
SMS standalone isn't a channel, but is available through other channels. I'll update the article to remove that reference as it is misleading

**Comment by ivorb** [comment]
fixed
