### ISSUE TITLE
The Direct Line service may forcibly close the WebSocket connection

### ISSUE THREAD

**Issue by alexzaitsev** [MicrosoftDocs/bot-docs#717]
Could you clarify this `The Direct Line service may forcibly close the WebSocket connection under certain conditions. `? What exact conditions are? What is sent to the client if the WebSocket is about to be closed by the Direct Line service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 825c44db-4144-1b78-c034-e9f3acc688ae
* Version Independent ID: d1916e07-ff35-5891-534e-e20266af73ee
* Content: [Receive activities from the bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-receive-activities?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-receive-activities.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-receive-activities.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by hansmbakker** [comment]
I'm interested in this, too

**Comment by mmiele** [comment]
Hi Alex, thank you for contacting us.
Direct Line sockets may be closed due to load, server reboots, or after an accumulation of network-related send failures. The conditions for these closures are not predictable and you should expect that unforeseen issues will cause socket closures.

**Comment by mmiele** [comment]
Also, we suggest to visit https://stackoverflow.com/questions/tagged/botframework for related questions.
