### ISSUE TITLE
SDK V4 Example

### ISSUE THREAD

**Issue by vinayjayaram** [MicrosoftDocs/bot-docs#718]
Is there any example with SDK V4 integration using NodeJS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2698526b-6251-3832-85e6-e6ba41b74909
* Version Independent ID: f2109d38-c3cd-06b3-7c51-fefcf1367fb9
* Content: [Conduct audio calls - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-conduct-audio-calls?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-conduct-audio-calls.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-conduct-audio-calls.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by ivorb** [comment]
Are you looking for audio/speech specifically, or NodeJS integration for V4 in general?

For V4 in general, take a look at the [samples for NodeJS](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs) and our [V4 content](https://docs.microsoft.com/en-gb/azure/bot-service/bot-builder-howto-send-messages?view=azure-bot-service-4.0&tabs=javascript)

Unified speech for v4 is in the backlog, and we'll add documentation when it comes available

**Comment by vinayjayaram** [comment]
We ae looking for a skype channel bot with call integration. I do see
examples for Skype call feature in SDK V3  hut unfortunately not for SDK V4

**Comment by ivorb** [comment]
Did you take a look [at this page](https://docs.microsoft.com/azure/bot-service/bot-service-channel-connect-skype?view=azure-bot-service-4.0), it introduces skype channel.

We don't have a v4 sample for skype call feature yet in our repo, but v3 and the [skype bots](https://dev.skype.com/bots) dev page can be used for a starting point.

**Comment by Kaiqb** [comment]
Closing.
