### ISSUE TITLE
Error on az bot create

### ISSUE THREAD

**Issue by JackStrap** [MicrosoftDocs/bot-docs#719]
I always get a error on az bot create if the password of the appId contain a parentheses in it.

Ok, here's a screenshot of the error i received and yes i put the password in double quote.

Thanks, hope it help!
Jack

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
Hi Jack, can you paste in a sample command? did you put the password in double quotations? (")

**Comment by JackStrap** [comment]
Hi, sorry it seem i close the issue by error. I will try to reopen it.
Jack

**Comment by ivorb** [comment]
Hi Jack, thanks for the screenshot. Could you also include the error as you see it?

Additionally, this looks like it runs a little differently for you in PS, could you run `az --version` for me and tell me what version you're running? I'm surprised to see it repeated in your window with the az alias replaced, but our configurations may just be different.

**Comment by JackStrap** [comment]
Hi, sorry I'm not sure to understand very well what you mean by include the error as i see it, would you  like to have it in text format?

Here's the return of az --version

PS D:\devSAQ\bolse000> az --version
azure-cli (2.0.55)

acr (2.1.12)
acs (2.3.14)
advisor (2.0.0)
ams (0.3.2)
appservice (0.2.11)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.6)
billing (0.2.0)
botservice (0.1.4)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.20)
consumption (0.4.2)
container (0.3.11)
core (2.0.55)
cosmosdb (0.2.7)
dla (0.2.3)
dls (0.1.7)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.2)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.2.0)
interactive (0.4.1)
iot (0.3.4)
iotcentral (0.1.5)
keyvault (2.2.9)
lab (0.1.5)
maps (0.3.3)
monitor (0.2.8)
network (2.3.0)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.8)
role (2.3.0)
search (0.1.1)
security (0.1.0)
servicebus (0.3.2)
servicefabric (0.1.11)
signalr (1.0.0)
sql (2.1.7)
storage (2.3.0)
telemetry (1.0.0)
vm (2.2.12)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'D:\Tmp\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Thanks, 
Jack

**Comment by ivorb** [comment]
Okay, so you're up to date, and I misunderstood your error (hence the confusion, but I think I get it now!) I was looking for the output I normally see for az CLI, and just overlooked your error output.

Oddly though, it looks like it isn't an error in az... when I put an unrecognized command into az I get "az: error: unrecognized arguments: {wpasd377*". It looks to be a parsing issue within your command line window, where the closed parenthesis terminates it. 

I can repo your error text when doing something like `--name IB)377`, without `"`, and get an error just like yours. But, I can avoid it by just doing `--name "IB)377"`... and when trying that with a fake appid and your password, it works for me.

Do you have any extra escape char settings for your command line or powershell scripts?

**Comment by array0** [comment]
Hey Jack your password is showing!  You might want to remove the pics because even though you blocked out part of the password the error returned says:  {password that was hidden} was not expected at this time.

**Comment by JackStrap** [comment]
Ok, thanks guys for your support. 
I don't think i've extra escape setting, that i know, but, there is so many GPO and other script running on my computer from my company.
I'll ask our security IT guy here, if there is anything running for powershell.
I'll close the issue, since it's probably something only happening on my side.
Again, thanks for your support it's really appreciated.

Jack
