### ISSUE TITLE
Dynamic Waterfalls

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/bot-docs#720]
Is it possible to have dynamic waterfalls that can be created in runtime?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7473adf8-26d3-13aa-ea29-eb07d00344b0
* Version Independent ID: 834aece5-d907-c61b-ca4a-7f91382c4f07
* Content: [Define conversation steps with waterfalls - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-dialog-waterfall?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-dialog-waterfall.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-dialog-waterfall.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
In theory, yes, but you would have to save enough state to be able to recreate the same waterfall on subsequent turns. Unless the dynamic waterfall is guaranteed to be the top one on the stack, I wouldn't try this. Much better to create a custom dialog by deriving directly from `Dialog` and implementing the _begin_, _continue_, and _resume dialog_ methods.

**Comment by Unders0n** [comment]
@JonathanFingold if i sure that it will be on the top of the stack what is the recommended way to go with waterfalldialog? c#, botbuilder 4

**Comment by JonathanFingold** [comment]
Thinking about this further, I think the recommended way is to go with a custom dialog, that is, derive your dynamic dialog from `Dialog`. The custom dialog could manage a "dynamic" waterfall dialog at that point, or implement its own dialog steps.

**Comment by BeigeBadger** [comment]
@JonathanFingold is your comment above still the recommended advice? My understanding is that the [custom dialog sample](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/19.custom-dialogs/Dialogs/RootDialog.cs#L29) is where people are usually [pointed to](https://github.com/microsoft/botbuilder-dotnet/issues/1006#issuecomment-427936443). My problem with this is that although the dialog steps are "custom" they are still known at compile time.

What is your guidance on how to handle creating a waterfall at runtime - is this even supported by the bot framework (will calling `AddDialog` add them to the correct dialog stack with the compile time dialogs?) My scenario is that I am using an API response to create the dialogs and their controls, unfortunately the API is an external one so I can't modify the response.

**Comment by JonathanFingold** [comment]
@BeigeBadger While the steps themselves need to be defined at compile time, you could define a custom dialog that would decide what the next step should be at run time, based on the current dialog state. (You can think of the dialog stack as a hierarchical finite state machine, if that helps.)

Alternatively, [adaptive dialogs](https://github.com/Microsoft/BotBuilder-Samples/tree/master/experimental/adaptive-dialog) are in preview and might work for your needs. If they do not, and you're up to digging through the underlying code, you could see how they are adding rule-based turn selection and maybe adapt it to your needs.

**Comment by BeigeBadger** [comment]
Thanks for the response @JonathanFingold. So if I understand you correctly the `WaterfallStep` collection needs to be defined a compile time along with a function to handle the step (HandleStep). Then this collection is passed into the `AddDialog` method.

Inside my custom dialog I could have a stack of cards that I build from my API response, then inside HandleStep I could have logic to determine which card to show from the stack. Does this sound workable to you? The API I am using returns JSON that includes a dynamic [UISchema](https://mozilla-services.github.io/react-jsonschema-form/) based on the element requested, I will translate this response into the appropriate cards/controls and add to my stack of cards to select from inside HandleStep.
