### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by raghukrishnamoorthy** [MicrosoftDocs/bot-docs#722]
This is brilliant. This is clearer than the previously existing doc. Thank you Jonathan and Kamran.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
Excellent, and I appreciate the feedback.
