### ISSUE TITLE
getAnswers is not a function

### ISSUE THREAD

**Issue by ckcar1** [MicrosoftDocs/bot-docs#723]
I'm not sure what I'm doing wrong here. I'm trying to integrate QnA Maker with a LUIS bot, and I've copied the code from this tutorial into my existing bot. It recognises the intent just fine, but when I use the code to pull answers from my KB, it throws this error - 

    [onTurnError]: TypeError: this.qnaServices[i].getAnswers is not a function

I've also tried it with the generateAnswers function, but that just brings back an empty array.
The KB is not the issue, because I've tried it with another QnA-specific bot and it works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by ckcar1** [comment]
I think I've found the root of the problem - my QnA isn't being read properly. The code I'm using to connect to it is:

    const QNA_CONFIGURATION = 'myKbNameHonestGuv';
    const qnaConfig = botConfig.findServiceByNameOrId(QNA_CONFIGURATION);
    const qnaServices = [];
    const endpoint = {
      knowledgeBaseId: qnaConfig.KbId,
      endpointKey: qnaConfig.endpointKey,
      host: qnaConfig.hostname
    };
    const options = {};
    qnaServices.push(new QnAMaker(endpoint, options));
    console.log("\n" + qnaServices);

However, this is what the console says:

![image](https://user-images.githubusercontent.com/46711659/51482957-afe41500-1d8f-11e9-8943-19e9c633268e.png)

It's reading the encrypted keys from the .bot file correctly, but it seems to be getting stuck at the

    new QnAMaker()

bit. I've required it correctly as far as I know:

    const { QnAMaker } = require('botbuilder-ai');

**Comment by xieyonggang** [comment]
i think you might need to upgrade the botBuilder-ai version to 4.2.0 if you did not

"botbuilder": "^4.2.0",
        "botbuilder-ai": "^4.2.0",
        "botframework-config": "^4.2.0",
        "dotenv": "^6.1.0",
        "restify": "^7.2.3"

**Comment by Kaiqb** [comment]
Please ask our support engineers on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework).
