### ISSUE TITLE
SDK v3 links in ToC are broken

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/bot-docs#727]
Both the v3 SDK links in the Reference section of the ToC are broken. I believe this is the correct link for the .NET API (https://docs.microsoft.com/en-us/dotnet/api/?view=botbuilder-dotnet-3.0), not sure on the Node.js one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ffe447d-f0a8-f4b6-d572-ba2c3bba4aab
* Version Independent ID: 6c1d9a6a-4cb3-f404-ce1f-940b443f0e34
* Content: [Azure Bot Service Introduction - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-overview-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-overview-introduction.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
Fixed.
