### ISSUE TITLE
I've done exactly how this tutorial says but I'm getting  '[onTurnError]: TypeError: this.storage.read is not a function' during runtime

### ISSUE THREAD

**Issue by dracosachin** [MicrosoftDocs/bot-docs#728]
Can you help me out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c94a4c9-e988-3b42-a7db-3634d15e9c47
* Version Independent ID: 68765289-1d77-6e4a-c6fb-1abbc067fcbd
* Content: [Save user and conversation data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Hi Sachin,
Thanks for your feedback. Did you encounter this error while running the C# or the JS sample code?
-Dan

**Comment by DanDev33** [comment]
Hi Sachin,
I've built and run both samples successfully, so I suspect there is some difference between our build environments. I'll be looking for your response to see if I can figure out what the problem you are encountering might be. Here are a few possible causes:
If using C#, please ensure that the Microsoft.Bot libraries are updated to the latest version v4.2.0
If using JS, please open a console window into your code directory and run "npm i npm -g". This will ensure you are building using the latest version of npm.

**Comment by dracosachin** [comment]
JS code

**Comment by dracosachin** [comment]
Thanks

**Comment by DanDev33** [comment]
closing

**Comment by RamitHansda** [comment]
@dracosachin how did you fix the issue?
