### ISSUE TITLE
The --secret command line argument is missing from msbot connect luis command

### ISSUE THREAD

**Issue by managedcoder** [MicrosoftDocs/bot-docs#729]
In the Adding a new LUIS model section, the msbot connect luis is missing its required --secret command line arg and so when you run what is specified above you get:

Error: You are attempting to perform an operation which needs access to the secret and --secret is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a178d6a6-8037-940c-e8fb-aad548203b92
* Version Independent ID: 181758cf-3495-6848-5808-9dc8234140ab
* Content: [Enterprise Bot Customization - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-customize?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-customize.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-customize.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by managedcoder** [comment]
Actually, I couldn't get -s, -secret, or --secret to work!  I had to remove it from the command line and let it ask me for it.  Also, I think I needed to also add --version Dispatch to the command line

**Comment by DanDev33** [comment]
Enterprise Template

**Comment by Kaiqb** [comment]
Closing as the content referenced here has been replaced with VA templates.
