### ISSUE TITLE
Adding new LUIS Model section has bad command argument... needs to be --secret, not -secret

### ISSUE THREAD

**Issue by managedcoder** [MicrosoftDocs/bot-docs#730]
Running the last command in that section: 
dispatch refresh -bot "YOUR_BOT.bot" -secret YOUR_SECRET
results in the following error:
ERROR
You are attempting to perform an operation which needs access to the secret and --secret is incorrect.
------
-secret needs to be changed to --secret (i.e. 2 dashes)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a178d6a6-8037-940c-e8fb-aad548203b92
* Version Independent ID: 181758cf-3495-6848-5808-9dc8234140ab
* Content: [Enterprise Bot Customization - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-customize?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-customize.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-customize.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by Kaiqb** [comment]
fixed
