### ISSUE TITLE
How to get state info within a Dialog?

### ISSUE THREAD

**Issue by DanteNahuel** [MicrosoftDocs/bot-docs#732]
Hi
I'm using the UserState accessors to save user input or even retry attempts. I'm able to redirect dialog flow according to this information. However I'm wondering how could I get these state properties saved in the UserInfo from within a Dialog.
I tried casting them inside a Task:
`var ticketNumber = ((UserInfo)stepContext.Options).TicketNumber.ticketNumber;`
but this crashes the program with the following error:
`.TicketNumber threw an exception of type "System.InvalidCastException"`

This is the State i'm trying to access

```
public class TicketNumber
    {
        public string ticketNumber { get; set; }
        public string ticketLetter { get; set; }
    
    }
```

Thanks in advance.

**Comment by ivorb** [comment]
Take a look at [this article section](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=csharp#define-the-check-in-component-dialog), particularly at the RoomStepAsync definition - we save the users name in the way I'm thinking you are trying to. I think it's just an issue casting the right thing

**Comment by DanteNahuel** [comment]
Thank you. I believe the issue i'm having is more complex than that but I didn't understand it. I'll create a more complete post summarizing everything.
Thank you
