### ISSUE TITLE
Is there a way to send multiple Option objects?

### ISSUE THREAD

**Issue by DanteNahuel** [MicrosoftDocs/bot-docs#733]
Hi
When using stepContext.BeginDialogAsync(DialogId, options, cancellationToken), is there a way to send more objects?
I understand that options can be received on the other end using stepContext.Options, but I want to send, for example:
DialogId. [options, customobject1, customobject2], cancellationToken

Is there a way to achieve this?

**Comment by ivorb** [comment]
If you need more objects passed via the options object, try creating a class inside your bot that holds all the different objects you need. Then, you can reference them as `(options as <customClass>).<subclass name>.

Take a look at how the options is used in [this article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=csharp#define-the-reserve-table-and-wake-up-component-dialogs), specifically down where we look for the Room value on the GuestInfo class.

**Comment by DanteNahuel** [comment]
Thank you. I believe the issue i'm having is more complex than that but I didn't understand it. I'll create a more complete post summarizing everything.
Thank you
