### ISSUE TITLE
No .bot file in downloaded bot

### ISSUE THREAD

**Issue by ryanvolum** [MicrosoftDocs/bot-docs#735]
I just tried following these directions verbatim. After creating my bot using the az cli tool, I downloaded it into a tmp directory. I'm then told to decrypt the downloaded.bot file, but the downloaded bot has no .bot file. 

Frankly I'm not sure why I even have to create a bot in Azure and download it if all I'm trying to do is push my local bot up. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot using Azure CLI - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
Are you using JS or CSharp?

We mention it in the article, but I'm going to make it more obvious - this isn't strictly necessary (the creating a web app, then downloading it, then using that bot file to upload your bot) it's the easiest way to have Azure provision all the necessary parts for a bot (the web app, the service plan, any other selected services etc). Doing it all manually to upload your bot works too, but it's much more tedious.

**Comment by ivorb** [comment]
I've created a v4 bot in both Node and Csharp this morning, and got the bot file for both. Are you using a work or MSA account?

**Comment by DanDev33** [comment]
Ivor successfully downloaded a .bot file using an Azure work account. I am going to try the same exercise using an MSA account to see if perhaps that is an issue.

**Comment by AskYous** [comment]
This is probably linked to #721 .

**Comment by DanDev33** [comment]
I built & deployed both a C# & JS bot using my MSA account and "az bot create"
used appid & password for each from Application Registration Portal
Successfully ran Test in Web Chat for each app, then executed:
 C:\>az bot download --name az-test-bot-cs --resource-group qna-deploy-test-group --save-path "c://development/bot file tests/downloads/cs"
{
  "downloadPath": "c://development/bot file tests/downloads/cs\\az-test-bot-cs"
}

C:\>az bot download --name az-test-bot-js --resource-group qna-deploy-test-group --save-path "c://development/bot file tests/downloads/js"
{
  "downloadPath": "c://development/bot file tests/downloads/js\\az-test-bot-js"
}

both apps downloaded into their correct folders (unzipped) and included the .bot files for each.
So MSA account is not the issue.

**Comment by Kaiqb** [comment]
Ryan was able to resolve this issue. I was also able to create and download a bot with the .bot file. You need to use the latest az cli tool (v 2.0.55). With the latest version of the az cli tool, you should uninstall the botservice extension.
