### ISSUE TITLE
az bot create errors out

### ISSUE THREAD

**Issue by ryanvolum** [MicrosoftDocs/bot-docs#736]
After running for about 10 minutes (seemingly in a loop), the az bot create command throws: 
```
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
telemetry.save : Save telemetry record of length 2521 in cache
telemetry.check : Negative: The C:\Users\ryvolum\.azure\telemetry.txt was modified at 2019-01-23 16:25:24.065109, which in less than 600.000000 s
```
It seems as if everything has been properly configured in Azure, but it's hard to tell. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot using Azure CLI - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
What kind of bot are you trying to create? Is it provisioning certain resources for you, past what's needed for a basic bot?

**Comment by ivorb** [comment]
Can you provide the command you were using?

**Comment by Kaiqb** [comment]
I had chatted with Ryan and this issue was resolved.
