### ISSUE TITLE
Loads .bot configuration file

### ISSUE THREAD

**Issue by Wendy-YongAiJing** [MicrosoftDocs/bot-docs#737]
error occured in the line below saying an exception of type 'System.ArgumentException' occurred in System.Private.CoreLib.dll but was not handled in user code
EncryptedText is not properly formatted

var botConfig = BotConfiguration.Load(botFilePath ?? @".\jfEchoBot.bot", secretKey);

how someone help me with this error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by Wendy-YongAiJing** [comment]
Problem is solved by setting the padlock of the .bot file to the empty string.

**Comment by DanDev33** [comment]
Glad you found the problem Wendy.
