### ISSUE TITLE
Error when using az bot create

### ISSUE THREAD

**Issue by mokoro1** [MicrosoftDocs/bot-docs#738]
I received the following error when I executed the command az bot create.

Deployment failed. Correlation ID: 06b2721c-e8aa-4297-80f5-04cab0f84b71. {
  "error": {
    "code": "InvalidBotData",
    "message": "Version: Bot Version has an invalid value. "
  }
}

Is this in any way related to me setting the version to "v4"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
very possible, that would be my first guess. Can you share the command you executed?

**Comment by mokoro1** [comment]
The command executed was:

az bot create --kind webapp --name EchoBot1 --location westus -v v4 --lang Csharp --verbose --resource-group DIT-Bot-Resource-Group --appid [My Application ID] --password [My Password ID] --verbose

**Comment by ivorb** [comment]
Just to appease me, could you try it with `--version v4`?

**Comment by Kaiqb** [comment]
@mokoro1 - what is the version of the az cli you are using?

**Comment by mokoro1** [comment]
Pardon the delayed reply.

The Azure CLI version I'm currently using is 2.0.55, I think this is the latest version.

________________________________

**Comment by Kaiqb** [comment]
We tested this scenario and we are able to run the az bot create command without any issues.  Make sure you aren't running into permission issues on the Azure side.

**Comment by gpsarkar** [comment]
We saw this issue today. Out bot name was testbot2. Tried from different accounts but on same subscription. After spending nearly few hours, when we changed the bot name to something else keeping all other parameters same, it worked. Definitely some weird bug.
