### ISSUE TITLE
Can you call Dialogs with multiple Options?

### ISSUE THREAD

**Issue by DanteNahuel** [MicrosoftDocs/bot-docs#739]
Is it possible to send multiple Option objects when calling a Dialog using the usual suspects:
`context.BeginAsync(opt1,opt2,opt3,opt4, cancellationToken)` ?
If so, what would be the correct syntax?
If not, could this feature be added?
It would be very helpful.

**Comment by JonathanFingold** [comment]
This is not currently supported. When I need something like this, I generally define dialog specific classes for input options and for return values.

Feature requests can be opened in one of the SDK repos: [Microsoft/BotBuilder-dotnet](https://github.com/Microsoft/botbuilder-dotnet) or [Microsoft/BotBuilder-jf](https://github.com/Microsoft/botbuilder-js/).
