### ISSUE TITLE
Invalid KbId Exception

### ISSUE THREAD

**Issue by xieyonggang** [MicrosoftDocs/bot-docs#740]
I am getting this exception, even though i check properly that the kbID is correct via curl or postman

QnAMakerService+&lt;GenerateAnswer&gt;d__12\nVoid MoveNext()","HResult":-2147024809,"Source":"QnAMakerRuntime","WatsonBuckets":null,"ParamName":"kbId"},"code":"Invalid KbId Exception\r\nParameter name: kbId"}}}

Curl  that works :
curl -X POST https://tkassyqnamaker.azurewebsites.net/qnamaker/knowledgebases/3fff1d25-2ac9-4f8f-a3d8-eb8e72dd7530/generateAnswer -H "Authorization: EndpointKey 4235120e-d0e6-4152-b4dc-70f013a0b3f9" -H "Content-type: application/json" -d "{'question':'hey'}"

below is my chatbot service code 
{
      "type": "TKassyKB",
      "name": "TKassyKB",
      "KbId": "3fff1d25-2ac9-4f8f-a3d8-eb8e72dd7530",
      "subscriptionKey": "xxxxxxxxxx",
      "endpointKey": "4235120e-d0e6-4152-b4dc-70f013a0b3f9",
      "hostname": "https://tkassyqnamaker.azurewebsites.net/qnamaker",
      "id": "204"
    }

the subscritopn key is obtained by following this 
https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/key-management

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by mydiemho** [comment]
In your service code, you're using `KbId`, with a capital K.  When you're constructing the qna endpoint, you're probably using `kbId`.

Take a look at where you're constructing the endpoint.

```
const endpoint = {
            knowledgeBaseId: s.kbId,
            endpointKey: s.endpointKey,
            host: s.hostname
        };
```

**Comment by JonathanFingold** [comment]
@xieyonggang , please reopen if this has not answered your issue.
