### ISSUE TITLE
App Password Bug

### ISSUE THREAD

**Issue by ryanvolum** [MicrosoftDocs/bot-docs#741]
When the generated app password has a '|' in it, it causes failures in the msbot command: 

```bash
PS C:\git\OpenHackTest\openhack-deployment-test&gt; msbot clone services --folder deploymentScripts/msbotClone --location "westus" --code-dir . --name "deployment-bot" --appId "12345" --appSecret "zjpqRX7614|^(jrsQBGQF9#" --verbose
'(jrsQBGQF9#' is not recognized as an internal or external command,
operable program or batch file.
```

To resolve this I had to generate a new password and make sure it had no '|'. If this is an unsolvable problem, it should at least be documented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d36b63c1-a0d4-cba9-b5b5-8618ec848e11
* Version Independent ID: a6bc9f4e-8da1-650e-9ea5-9802b64880f3
* Content: [Deploy bots from botbuilder-samples repo - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-samples?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/bot-builder-deploy-samples.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-samples.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
I believe I had encountered this before and did document it. Will look to find out where that was done and note it in the deploy article as well. Thanks Ryan.

**Comment by DanDev33** [comment]
Updated article will contain this info when published. Thanks!
