### ISSUE TITLE
No .bot file created if you do not define --lang

### ISSUE THREAD

**Issue by ross-p-smith** [MicrosoftDocs/bot-docs#742]
When you create a bot using az cli using 2.0.55 and do not define the --lang flag, no bot file is created

az bot create --kind webapp --name rosmith --location westeurope --version v4 --verbose --resource-group repro

This should create a bot file like it does if you use

az bot create --kind webapp --name rosmith1 --lang Csharp --location westeurope --version v4 --verbose --resource-group repro1

I have reproduced this with just this one argument being different

**Comment by DanDev33** [comment]
Thank for your feedback on this Ross. We appreciate this info.
