### ISSUE TITLE
Looping into a nested Dialog?

### ISSUE THREAD

**Issue by DanteNahuel** [MicrosoftDocs/bot-docs#744]
Hi,
I'm having trouble understanding how to use ReplaceDialogAsync to loop back when inside a nested Dialog.

Once you branch out of the main Dialog, (and correct me if i'm wrong, which it's very very likely) the nested Dialog should inherit the main dialog Id with this:
```
        public NestedDialog1(string Id) : base(Id)
        {
            InitialDialogId = Id;
            }
```

So, I assumed that when using ReplaceDialogAsync, I could use this Id to restart the Nested Dialog again:

`context.ReplaceDialogAsync(InitialDialogId, null, cancellationToken)`

However this doesn't work, and I'm assuming it's because i'm not using (and understanding) the Ids of the nested/child Dialogs.

How should I approach this?

And also, a feature request:
The framework should allow to loop into specific waterfall steps, instead of having to mix NextAsync with a lot of switches and properties in order to skip already passed steps.

Thank you a lot.

**Comment by JonathanFingold** [comment]
PS. Feature requests can be opened in one of the SDK repos: Microsoft/BotBuilder-dotnet or Microsoft/BotBuilder-js.

**Comment by DanteNahuel** [comment]
Thank you for your reply.

So the correct implementation would be like this:
```

private const string ComponentDialogId = "componentDialogID";
 public NestedDialog1(string Id) : base(Id)
        {
            InitialDialogId = componentDialogID;
            }

WaterfallStep[] waterfallSteps = new WaterfallStep[]
            {
Step1,
Step2,
Step3,
            };
            AddDialog(new WaterfallDialog(ComponentDialogId, waterfallSteps));


```

Correct?

if that the case, thank you for the explanation.
I'll send a feature request for the looping into specific steps.

**Comment by DanteNahuel** [comment]
This indeed helped me understand what was going on. Yes. Docs should be updated with this example using diferent Dialog Id for the Parent Dialog Referencing ID and the Component ID.
Thank you for your help. Closing it.
