### ISSUE TITLE
I can not get the Introduction Card to work.

### ISSUE THREAD

**Issue by Gariantroll** [MicrosoftDocs/bot-docs#746]
The introduction Card does not seem to work.   Is there a way I have to activate it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by joroSharp** [comment]
Hello Gariantroll,
I was suffering the same issue, but after making a rebuild of the solutions it works. 
This sounds pretty silly, but have you tried it?

**Comment by Gariantroll** [comment]
I don't think so.  My namespace starts with an underscore and some numbers.  It seems that is legal.  I am still hammering away at this issue.

**Comment by Gariantroll** [comment]
Hey, I realized that none of the basic responses is working from the LUIS s even though LUIS is being recognized.  It will then give a default answer from my qnaKB if there is a similar match.  Is there a known solution for this or should I attempt to just rebuild a new Dispatch and see what happens?

**Comment by Gariantroll** [comment]
Also, is there some documentation on building Dispatch without the template?  I realized we don't need to all of the default Intents from the template.

**Comment by Gariantroll** [comment]
Hey, I just started over and made a new bot and everything is fine.  Thanks for your help.  

Alexis
