### ISSUE TITLE
Please mention that an app must be created ADDITIONAL to the app created in the beginning for your bot.

### ISSUE THREAD

**Issue by AskYous** [MicrosoftDocs/bot-docs#747]
This part really confused me and I spent about a week trying to diagnose my issue. When I read the section titled ["Register an application in Azure AD"](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp#register-an-application-in-azure-ad), I decided to skip this step because I thought that I already did this step in [the introduction](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=javascript#msa-email-account). Please clarify that this is needed even if the developer created an app before. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp#register-an-application-in-azure-ad)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
Updating the first line of the **Overview** to read:
> This tutorial creates a sample bot that connects to the Microsoft Graph using an Azure AD v1 or v2 token, and the associated Azure AD app.

The lead in above the **Register an application Azure AD** section already mentions:
> You need to create a registration bot to which you'll publish your bot code, and you need to create an Azure AD (either v1 or v2) application to allow your bot to access Office 365.
