### ISSUE TITLE
Can you please describe what means: "Create your bot on Azure Create a Bot Channels Registration using the Azure Portal."

### ISSUE THREAD

**Issue by SiTox** [MicrosoftDocs/bot-docs#750]
It's not clear if it's Channel registration or Web App Bot and which values to put in AppID and endpoint.

Also not clear why and how to update ConnectionName if you run locally. I haven't managed to run this locally yet. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by Kaiqb** [comment]
It is asking you to create a channels registration bot in the Azure portal. To do that, you click on "Create a resource" and then search for "Bot Channels Registration".

**Comment by SiTox** [comment]
This guide is quite confusing, it took me 2 days to make it work. For example, 
1) Now I don't have channel registration, only web app bot and it works. Why do I need channel registration if you can manage channels from your web bot app? 
2) You don't describe deployment to from Visual Studio and connection using ngrok. 
3) How you can even test this example locally, having the fact that you need to have oAuth connection ? That is confusing.

**Comment by AskYous** [comment]
This also cost me a couple days because this channel registration step was confusing.
