### ISSUE TITLE
ECCONREFUSED error when connecting with Bot Framework Emulator

### ISSUE THREAD

**Issue by santos2312** [MicrosoftDocs/bot-docs#751]
Hello,

I have been having the same error over and over, as seen in the image. I have followed all the steps as per the documentation. And when it comes to connecting to test in real time and not locally the error always shows. 
I have gone through all the post in here related with this issue, some had the same issue but the solutions found were not applicable to my situation. 
I have created the bot template from both Azure portal and locally through the Bot SDK and when i get to the point of connecting to Azure the issue appears. 

I additional information is required I will be glad to share.  

![ngrokissue](https://user-images.githubusercontent.com/40268633/51831120-a9a2eb00-22f1-11e9-946b-a3ef9f611616.png)

**Comment by DanDev33** [comment]
Hi! A possible problem that causes this error occurs when the emulator is closed, but your local version of ISS Express is still holding the http://localhost:3978 connection open. If that is your issue it can be resolved by either stopping /restarting that service, or by stopping/restarting windows. Please try that and let us know if this still remains an issue.

**Comment by Kaiqb** [comment]
It seems Dan's response has helped the user. Closing.
