### ISSUE TITLE
I this sample available in its entirety for download?

### ISSUE THREAD

**Issue by JSWilsonX** [MicrosoftDocs/bot-docs#754]
Where can I download this project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c94a4c9-e988-3b42-a7db-3634d15e9c47
* Version Independent ID: 68765289-1d77-6e4a-c6fb-1abbc067fcbd
* Content: [Save user and conversation data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
The pre-req has a link to the sample in C# and JS. Just click on the language you are using. This is the line in the topic:
- The code in this article is based on the StateBot sample. You'll need a copy of the sample in either C# or JS.

**Comment by JSWilsonX** [comment]
@Kaiqb Thanks for pointing me to the source. Unfortunately, it does not build. I get a number of  errors including: 
Error CS0234: The type or namespace name 'Builder' does not exist in the namespace 'Microsoft.Bot' (are you missing an assembly reference?) (CS0234) (StateBot)

NU1202: Package Microsoft.AspNetCore.All 2.2.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.All 2.2.1 supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2)
