### ISSUE TITLE
Bold "Echo Bot" on "In Visual Studio, create a new bot project using the Bot Framework Echo Bot V4 template."

### ISSUE THREAD

**Issue by mahomedalid** [MicrosoftDocs/bot-docs#756]
Bold "Echo Bot" on "In Visual Studio, create a new bot project using the Bot Framework Echo Bot V4 template." It is easy to miss the word "Echo Bot" and create a project from the generic Microsoft Bot V4 template with two projects (Echo and Empty Bot). Happened too to some of my friends. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Framework SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by DanDev33** [comment]
Thanks for your feedback. This selection will appear bolded in the next article update.
