### ISSUE TITLE
Run `npm install` after the bot is generated

### ISSUE THREAD

**Issue by kichinsky** [MicrosoftDocs/bot-docs#757]
According to the docs on the generator (https://github.com/Microsoft/BotBuilder-Samples/tree/master/generators/generator-botbuilder) you need to run `npm install` before runing `npm start`. It is a missing step for this docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaad3f2-75c5-e958-4734-8925d03d95c6
* Version Independent ID: 8d98b390-5368-1fa4-8cce-3b0cff252eaa
* Content: [Create a bot using Bot Framework SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by DanDev33** [comment]
Hi Kichinsky,
Your source references bot-builder-javascript-quickstart.md
In this article, Step #3 contains:

Ensure your version of npm is up to date.
> npm install -g npm

This command installs the latest version of npm into your directory.

I do note that this same step is in fact missing from the Readme within the code Sample.
I am going to close this issue against the docs and open it instead as a code sample issue. Thanks

**Comment by DanDev33** [comment]
npm install is referenced in the sample readme just prior to npm start.
