### ISSUE TITLE
Minor Typo issue on the source code 

### ISSUE THREAD

**Issue by angie4u** [MicrosoftDocs/bot-docs#759]
"this.welcomedUserPropery" -&gt; It will be better change to "this.welcomedUserProperty"

Added more typos..!
 // If any new membmers added to the conversation -> If any new members added to the conversation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaad3f2-75c5-e958-4734-8925d03d95c6
* Version Independent ID: 8d98b390-5368-1fa4-8cce-3b0cff252eaa
* Content: [Create a bot using Bot Framework SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by DanDev33** [comment]
closed.
