### ISSUE TITLE
Step 2 - creation of myJsBots folder - is this step necessary

### ISSUE THREAD

**Issue by smich73** [MicrosoftDocs/bot-docs#761]
In step 2, the instructions mention to create folder if one does not already exist. Running the Yo Generator actually creates a folder (named after your bot) so is this step 2 necessary. Could cause confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaad3f2-75c5-e958-4734-8925d03d95c6
* Version Independent ID: 8d98b390-5368-1fa4-8cce-3b0cff252eaa
* Content: [Create a bot using Bot Framework SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by Kaiqb** [comment]
Step 2 already has the following clarification:
"We're creating a directory for your JavaScript bots in general, even though we're only creating one bot in this tutorial."

**Comment by DanDev33** [comment]
Hi Simon,
Thanks for your feedback. While this article does only have the user create a single bot within the folder, it's a good practice to separate coding samples, by type, into discreet folders. The general feeling is that any potential confusion was outweighed by helping newer users lay out their samples in a way where they can later be easily accessed. We appreciate you taking the time to review our docs and provide feedback.
