### ISSUE TITLE
Send welcome message to user page - First example (JavaScript) missing reference to userState object + Typo

### ISSUE THREAD

**Issue by hattan** [MicrosoftDocs/bot-docs#762]
This error pertains to the page "Send Welcome Message to User."
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=js%2Ccsharpmulti%2Ccsharpwelcomeback

In the first JavaScript code sample there is a bug in that userState is not saved into a member variable of the class. 

The constructor looks like this
```
constructor (userState) {
        // Creates a new user property accessor.
        // See https://aka.ms/about-bot-state-accessors to learn more about the bot state and state accessors.
        this.welcomedUserPropery = userState.createProperty(WELCOMED_USER);
    }
```

Notice that although a property is created, the reference to userState is not saved.  Further down in the code this line utilizes userState

```
await this.userState.saveChanges(turnContext);
```

However, since userState is not saved, this.userState returns undefined and results in an error.

### Expected Behavior:
Sample should work and save the reference to userState in the constructor.
```    
constructor (userState) {
        this.welcomedUserPropery = userState.createProperty(WELCOMED_USER);   
        this.userState = userState; 
    }
```
In addition, the property this.welcomedUserPropery contains a spelling error (missing t from property.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a16806-95d6-7c66-3b85-b2ace211f367
* Version Independent ID: c8565ece-392a-fb56-e911-8a5dd5555dee
* Content: [Send welcome message to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=js%2Ccsharpmulti%2Ccsharpwelcomeback)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DanDev33
* Microsoft Alias: **v-dashel**

**Comment by JonathanFingold** [comment]
Thanks for catching this. I have a fix in a local branch, and this update should go live in a few days.
