### ISSUE TITLE
500 error in Emulator following creating state object/accessor classes

### ISSUE THREAD

**Issue by jackiebecker** [MicrosoftDocs/bot-docs#763]
Following the step: 'We need to create a state object for a given user in a conversation and it's accessor.'

Created state object/accessor in new class files. When bot was ran in emulator, got 500 ("POST 500 directline.postActivity") and 'couldn't send, retry.' Error message was not helpful so set flag in VS to break on any error, broke on: 

`'System.InvalidOperationException: 'Unable to resolve service for type 'OpenHackBot_hacker1.WelcomeUserStateAccessors' while attempting to activate 'OpenHackBot_hacker1.OpenHackBot_hacker1Bot'.'`

At which point was able to realize it was because I had not added 'WelcomeUserStateAccessors' as a service/singleton in Startup not added UserState to application state i.e. 

`services.AddBot<Bot>(options =>
{
 ... 
var userState = new UserState(dataStore);
options.State.Add(userState);
}); `

Might want to clarify/remind people to add these classes as service in Startup thus, or better specify where they should add that block of code. Also 500 error was unhelpful alone in diagnosing this. 

Code used to add as singleton: 

           
            services.AddSingleton<WelcomeUserStateAccessors>(sp =>
            {
                var options = sp.GetRequiredService<IOptions<BotFrameworkOptions>>().Value;
                if (options == null)
                {
                    throw new InvalidOperationException("BotFrameworkOptions must be configured prior to setting up the state accessors");
                }

                var userState = options.State.OfType<UserState>().FirstOrDefault();
                if (userState == null)
                {
                    throw new InvalidOperationException("UserState must be defined and added before adding conversation-scoped state accessors.");
                }

                // Create the custom state accessor.
                // State accessors enable other components to read and write individual properties of state.
                var accessors = new WelcomeUserStateAccessors(userState)
                {
                    WelcomeUserState = userState.CreateProperty<WelcomeUserState>(WelcomeUserStateAccessors.WelcomeStateName),
                };

                return accessors;
            });

Also unrelated & small note, but in sentence 'We need to create a state object for a given user in a conversation and it's accessor,' should be 'its' since being used to denote ownership, not contraction. 

Edits: for clarity & formatting. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a16806-95d6-7c66-3b85-b2ace211f367
* Version Independent ID: c8565ece-392a-fb56-e911-8a5dd5555dee
* Content: [Send welcome message to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=csharp%2Ccsharpmulti%2Ccsharpwelcomeback#feedback)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DanDev33
* Microsoft Alias: **v-dashel**

**Comment by DanDev33** [comment]
Thanks Jackie! I'll look to see how I can better clarify this.

**Comment by DanDev33** [comment]
You will see clarification of WelcomeUserStateAccessors and UserState in the next publication of this article. Thanks for helping us make our docs better.

**Comment by jackiebecker** [comment]
Awesome, thanks @DanDev33. Adding @brandonh-msft for issue tracking.
