### ISSUE TITLE
Suggested Action documentation should show choice processing after action is chosen.

### ISSUE THREAD

**Issue by JamesEarle** [MicrosoftDocs/bot-docs#764]
The documentation [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-suggested-actions?view=azure-bot-service-4.0&tabs=javascript) shows you how to create suggested actions from `MessageFactory` but does not show you how to handle processing the selection after a choice is made. This looks like it already exists in the source code [here.](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/08.suggested-actions/bot.js)

This should be added to the documentation.

**Comment by Kaiqb** [comment]
We are planning to update the samples and will modify docs as needed. Thanks!
