### ISSUE TITLE
Missing link to Skype web control

### ISSUE THREAD

**Issue by msimecek** [MicrosoftDocs/bot-docs#765]
There's no link to the Skype web control. How about this one? https://dev.skype.com/webcontrol

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2c6d823-f87f-84b3-f1de-c48851979480
* Version Independent ID: e3b11c52-641d-0372-2aad-7cdb77fda99f
* Content: [Embed a bot in a website - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-embed-web-site?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-design-pattern-embed-web-site.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-pattern-embed-web-site.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by DanDev33** [comment]
Thanks Martin! I'll create an aka.ms link for this and add it to the article.

**Comment by DanDev33** [comment]
You'll see this active link the next time this article is published.
