### ISSUE TITLE
Why is ngrok in Prerequisites?

### ISSUE THREAD

**Issue by msimecek** [MicrosoftDocs/bot-docs#766]
There's no need to have ngrok installed to deploy to Azure, yet it's in the Prerequisites section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your C# bot using Visual Studio - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Thanks for your feedback Martin. The requirement for ngrok is a holdover from when it was required. We'll remove it. You'll see the change online the next time this article Is published.

**Comment by DanDev33** [comment]
removed from requirements.
