### ISSUE TITLE
Add media to messages - link to sample code of suggested actions (JS) goes to Microsoft homepage

### ISSUE THREAD

**Issue by hattan** [MicrosoftDocs/bot-docs#767]
On the page "Add media to messages" , there are links at the bottom to view sample code. One of the links is for suggested actions and provides options for C# and JS. The link to C# works, however the link to JS points to https://aka.ms/SuggestedActionsJS which redirects to microsoft.com.

## Expected Behavior
Link should point to github repo with JS code for suggested actions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 607856cb-baae-c401-5b34-876b5018771d
* Version Independent ID: 77df1de7-7b2e-a546-1280-a66121039a94
* Content: [Add media to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-add-media-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-media-attachments.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
Fixed.
