### ISSUE TITLE
`Back Channel Sample` link is returning 404

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/bot-docs#768]
the sample is gone on github

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40659e74-4b85-b408-a29a-ffe827c2ed7f
* Version Independent ID: c85d39c9-0b71-c892-613a-e7b2e622a0a9
* Content: [Exchange information using the web control - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-backchannel?view=azure-bot-service-3.0&viewFallbackFrom=azure-bot-service-4.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-backchannel.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-backchannel.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by mydiemho** [comment]
I would assume so.  

The broken link is set to `https://aka.ms/v3-js-backchannel-sample` which reroute to 
`https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/redux-activity-middleware` (which doesn't exist)

**Comment by Kaiqb** [comment]
Updated aka.ms link to point to https://github.com/Microsoft/BotFramework-WebChat/tree/v3/samples/backchannel.
