### ISSUE TITLE
Article should give guidance on encrypting the .bot file using the msbot tool

### ISSUE THREAD

**Issue by AndyCW** [MicrosoftDocs/bot-docs#769]
The article explains how to update settings for a QnA Maker service in your .bot file. It needs to guide the developer to use the msbot tool to update the .bot file when it is encrypted. A developer new to bot development will be blocked unless this is explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
We are re-evaluating the role of .bot file and how to manage bot services all up. So, expect to see changes coming in this area of the tools.
