### ISSUE TITLE
Application Settings are ignored

### ISSUE THREAD

**Issue by pkirch** [MicrosoftDocs/bot-docs#772]
Section "Update your bot’s Application Settings" explains to set the App ID and App password via Application Settings. Unfortunately, those are ignored by the EchoBot Template installed with the "Bot Framework SDK v4 template for C#" as stated in https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0. The Startup.cs file from the EchoBot template only reads the settings from the bot file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your C# bot using Visual Studio - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
There is no automatic way for the tooling to update local bot with settings that you create/update in Azure. To add IDs/Pwd to a bot file, you'll need to make sure that the .bot file is not encrypted. 

Overall, we've had feedback on the .bot file approach and the friction it creates, and we are actively working on simplifying the experience.
