### ISSUE TITLE
In Activity object add info for "type"

### ISSUE THREAD

**Issue by jannavarro** [MicrosoftDocs/bot-docs#773]
In Activity object, in the **type** property, you should add "event" as one of the values. Reference: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-activities-entities?view=azure-bot-service-4.0&tabs=cs#event

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e47c9b6-a06c-caa8-9b8f-b50fdfa70109
* Version Independent ID: d24d686f-8d14-eb25-9fe9-112df8993ae4
* Content: [API reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#activity-object)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
Updated.
