### ISSUE TITLE
Missing Reference: Microsoft.Bot.Builder.AI.Luis

### ISSUE THREAD

**Issue by ActiveNick** [MicrosoftDocs/bot-docs#775]
When creating the BotServices class, the LuisApplication and LuisRecognizer classes do not resolve because the article omits to tell the reader to add a Nuget reference to Microsoft.Bot.Builder.AI.Luis. The following using statements also need to be added:

using Microsoft.Bot.Builder.AI.Luis;
using Microsoft.Bot.Configuration;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Add natural language understanding to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Hi Nick,
Thank you for your feedback! The changes you requested will appear live the next time this article is published.

**Comment by DanDev33** [comment]
Update ready
