### ISSUE TITLE
Use FindServiceByNameOrId rather than foreach/switch

### ISSUE THREAD

**Issue by sbaidachni** [MicrosoftDocs/bot-docs#776]
There is no sense to use foreach/switch..case to reiterate through all services from .bot file - just use (QnAMakerService)botConfig.FindServiceByNameOrId(..) to make it not so complicated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
This is an issue with the code in the BotBuilder-Samples repo. There are plans to rework the samples, but I'm not sure what the schedule is.

**Comment by Kaiqb** [comment]
Please open the issue in the [samples repo](https://github.com/Microsoft/botbuilder-samples/issues).

**Comment by ovishesh** [comment]
Hi @Kaiqb, would you be able to move this issue to the Samples repo using the [new GitHub feature](https://help.github.com/articles/transferring-an-issue-to-another-repository/) and re-open it?
