### ISSUE TITLE
Generating a consistent story to BotServices between LUIS and QnAMaker samples and docs

### ISSUE THREAD

**Issue by mahomedalid** [MicrosoftDocs/bot-docs#777]
LUIS uses BotServices with:

- A constructor that takes BotConfiguration and initializes a Dictionary

QnAMaker uses BotServices:

- With a static method that initializes the QnAMaker instances on a Dictionary
- Then the result is being passed to BotServices just as a container

It's a little confusing if you are working on a project with both LUIS and QnAMaker to reconcile both approaches on the same base code. Additionally, the BotServices abstraction seems like a recommended approach, which I don't know if it's the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
We are working on streamlining samples and the code to address the issue you and others have raised. Thanks
