### ISSUE TITLE
No documentation on how to use Email Channel

### ISSUE THREAD

**Issue by DanteNahuel** [MicrosoftDocs/bot-docs#778]
Hi again!
I'm having a lot of trouble trying to use the Email Channel functionality.
There's no documentation on how to access/use the ChannelData to read, check and specially reply to emails sent to the bot.
ChannelData seems to be impossible to cast to a string variable (which I need to Deserialize the JSON string). 
`var variable = stepContext.Context.Activity.ChannelData as string;`
The bot just SKIPS the line entirely as if it didn't exist (and try catch is also skipped) and goes right into the return await line

And i can't find any example on how to correctly reply to an email using framework classes.

Is there any working examples on this?

Thanks in advance.

**Comment by Kaiqb** [comment]
Are you using Office 365?

**Comment by DanteNahuel** [comment]
Yes, I am!

**Comment by DanteNahuel** [comment]
Yes, I am!

**Comment by JonathanFingold** [comment]
We have a small amount of info in [implement channel-specific functionality](https://docs.microsoft.com/azure/bot-service/bot-builder-channeldata).

**Comment by DanteNahuel** [comment]
@JonathanFingold Yes, however the info is scare. For example, it should be added that the bot is capable of replying any email just by using context.contex.sendactivityasync("reply"). I was struggling to understand how to reply emails because my intuition made me believe I needed to use a specific class. However this was not the case (and I was relieved to know it was this easy)
This can be changed to suggestion

**Comment by Kaiqb** [comment]
This [sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/24.bot-authentication-msgraph) show how to do email among other things.
