### ISSUE TITLE
Azure Devops integration

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/bot-docs#780]
Can you add a documentation section to integrate this with Azure Devops?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by Kaiqb** [comment]
For continous deployment, take a look at: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0.

**Comment by darrenj** [comment]
We are planning additional docs for the Enterprise Template showing how you can manage dependencies like LUIS, unit tests, etc. for a Bot project leveraging the Enterprise Template. We have addressed a number of these issues for our internal Virtual Assistant project so will be sharing this once baked further

**Comment by mganeshphani** [comment]
@Kaiqb I am expecting a documentation on how to create release pipeline.. The reason we need a way to have release pipeline is to make sure we have appropriate approval process in place when the code moves between different environments.. along with this we want to integrate our infrastructure definition in pipeline itself.

**Comment by mganeshphani** [comment]
@darrenj  may I get notified once you are done with this?

**Comment by darrenj** [comment]
https://github.com/Microsoft/AI/issues/655<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FAI%2Fissues%2F655&data=02%7C01%7Cdarrenj%40microsoft.com%7C7736a992d06b4cc30c2708d686cabba8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636844602656339155&sdata=cvX6cE72ui5ggb6CIimTIT%2FxnzmelAejRWrQhYPbWbo%3D&reserved=0> :-)
