### ISSUE TITLE
Sample links easy to overlook

### ISSUE THREAD

**Issue by pkirch** [MicrosoftDocs/bot-docs#782]
I spent some time on this page learning where to paste the provided sample code. After search a long time I found that in the prerequisites "C#" and "JS" are links. Maybe you can make it more clear that those are links to GitHub; so the next reader finds it faster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
made the links a little larger pieces of text, so they should be more visible

**Comment by brandonh-msft** [comment]
@ivorb the text doesn't look bigger in the doc today but regardless bigger text isn't necessarily the issue here. We should have more descriptive (and accessibility-friendly) link text like "C# Sample on GitHub" vs just "C#", etc. This is true throughout our docs.

**Comment by GeekTrainer** [comment]
To add to what @brandonh-msft said, having a link which simply reads C# is equivalent to having link text which is simply "here". It doesn't tell the reader, and more importantly a screen reader, what is on the other side of the link. We need to have more descriptive text, rather than simply larger text.

**Comment by ivorb** [comment]
The text now says "C# sample", which is more noticeable and descriptive. Closing this, as this sample isn't the only one that has the super short (C#) link. We'll be fixing the rest of them in bulk to be a bit longer/more descriptive
