### ISSUE TITLE
No steps direct the user to create a production endpoint in the .bot file before publishing 

### ISSUE THREAD

**Issue by ayako** [MicrosoftDocs/bot-docs#785]
In order for the published bot to use the production endpoint reference in Startup code by samples and templates, the user must add a 'production' endpoint to their .bot file. This step is not outlined in any documentation on deployment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your C# bot using Visual Studio - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0#next-steps)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
There is other work that I think needs to happen with this article, past adding the production endpoint information. That work will be done together.

**Comment by ivorb** [comment]
Added notes to backlog, will update this article with this and other information.
