### ISSUE TITLE
Initial dialog property

### ISSUE THREAD

**Issue by msimecek** [MicrosoftDocs/bot-docs#786]
"you can change this by explicitly setting the *initial dialog* property" -&gt; there's no such property, it's actually called `InitialDialogId` (or `initialDialogId` in JavaScript). I believe that changing it to the proper name with a code highlight will help uderstanding the code - currently is very easy to miss.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9577ff-cf56-e5de-84c3-bfe10aab5368
* Version Independent ID: b5d62753-f87b-4673-b09b-a5a3fd9360e8
* Content: [Reuse dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?tabs=javascript&view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-compositcontrol.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-compositcontrol.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
Fixed.
