### ISSUE TITLE
`.bot` json mismatched with sample code causing error

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/bot-docs#788]
In the [`.bot` sample](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=js#update-the-bot-file), the service entry for qna is using `KbId` whereas the js code is using `kbId `.  Then when user execute the code, they would get a 400, because the `knowledgeBaseId` would be null since `qnaConfig` does not contain a `kbId` entry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=js#update-the-bot-file)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
This is fixed and will be pushed live soon... the actual sample appears to be correct, but there was a typo in the doc for kbId. Thanks for pointing it out!
