### ISSUE TITLE
Error when trying to add Cortana channel

### ISSUE THREAD

**Issue by alathrop** [MicrosoftDocs/bot-docs#791]
I'm getting this error when I try to add the Cortana channel to my bot. This error appears when I click on the Cortana icon in the 'channels' blade for my bot settings in the Azure portal:
Sorry, something went wrong :-(

Trace Id : a08b1165-4b5d-465f-8fd2-d4691cfda350 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155fd9a4-a390-eb9e-5f1a-fae7a2ede084
* Version Independent ID: 21c420dc-db37-f5d5-ac38-c843055e195a
* Content: [Connect a bot to Cortana - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-cortana?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-cortana.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-cortana.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
I'm not able to repro this. If you still need help, reach out to support engineering team on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework).
