### ISSUE TITLE
Unclear documentation on key/id/registration value retrieval 

### ISSUE THREAD

**Issue by jackiebecker** [MicrosoftDocs/bot-docs#795]
When connecting together a Bot Channel Registration with App Services or Web App Bots, it isn't immediately clear enough how/where to get these pieces and where to put them. 

EDIT: for clarity. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your C# bot using Visual Studio - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0#next-steps)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
@jackiebecker - The article talks about deploying the local bot and then creating a registration bot. can clarify what is not clear?

**Comment by jackiebecker** [comment]
Compared to v3 (where page would immediately open & values could be copied), there are too many moving parts here. Default is to auto-generate, at which point you can not retrieve secret unless you delete & regenerate outside of portal. This needs to be simplified as the only way to figure out how to get ID & Secret is by following this doc in the first place--should be more intuitive than four additional steps at creation, or if you already created w/o grabbing these values at init, needing to know you should click on Resource -> Settings -> App ID/Manage -> go to separate web page -> regenerate with no guidance telling you to do so.

**Comment by jackiebecker** [comment]
Edited original description for clarity on this, as issue is more related to flow within Portal & the fact that documentation is even necessary. Still, images within documentation showing these steps of grabbing values would at least be more helpful.

**Comment by Kaiqb** [comment]
We've made updates to the templates in the Azure portal for v4, but beyond that there are no changes planned at this time.
