### ISSUE TITLE
Provide DevOps best practices for secrets management

### ISSUE THREAD

**Issue by jamestruitt** [MicrosoftDocs/bot-docs#797]
Since we are introducing a new place/way to store secrets in v4 we should, as part of deployment documentation, address typical DevOps flows for managing the secrets now present in the .bot file (and therefore the source code of a bot). What is the best practice for managing these secrets? How/when/by whom should they be encrypted? Can they be? How would different deployment environments be managed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41386916-1ae4-1a69-855a-c48f3804e673
* Version Independent ID: 180ca783-20c2-672c-303c-69cc8b42e71b
* Content: [Configure continuous deployment for Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-build-continuous-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-build-continuous-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
Agreed. That is the plan once we land the changes in the CLI tools.
