### ISSUE TITLE
Deployment documentation inaccurate

### ISSUE THREAD

**Issue by jamestruitt** [MicrosoftDocs/bot-docs#798]
No matter what I tried, deploying as this doc states does not work for BotBuilder v4 bots. The only approach I found that actually worked was to:
	• Create a Web App Bot
	• Open the App Service Editor for the resulting app service
	• Open the generated .bot file shown in the file list
	• Copy the contents to the .bot file in my local bot
	• Push to the Azure App Service created by the Web App Bot deployment
Using this workflow my bot worked both locally and in production, no other workflow I tried - docs or using my own Azure knowledge - worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your C# bot using Visual Studio - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0#next-steps)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
@jamestruitt - are you getting this error in the browser: _**An error occurred while starting the application**_.?

**Comment by Kaiqb** [comment]
In VS, if the .bot file properties aren't correct, the deployment also fails. Updated instructions to check the properties.
