### ISSUE TITLE
Not obvious how to manage state between waterfall steps

### ISSUE THREAD

**Issue by smich73** [MicrosoftDocs/bot-docs#799]
I was looking for information on managing state between waterfall steps.
The information that I was looking for (step.values) is mentioned on the 'Reuse Dialogs' page - https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=javascript  but it would be very useful if it was also mentioned on this 'managing state' page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1795c22-9e0f-8a69-a517-ffbe38a2cd30
* Version Independent ID: 9d2c1569-6d6f-97fa-881d-b4a0f61623a2
* Content: [Managing State - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
The concept topic on [Managing state](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-state) does not assume any knowledge of dialogs. However, information about the `Values` property is mentioned in a couple other places:
- In the **Dialogs library**, under **dialog types/waterfall dialogs/**[Waterfall step context properties](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-dialog#waterfall-step-context-properties)
- It's also used in these other how-to topics: [Gather user input using a dialog prompt](https://docs.microsoft.com/azure/bot-service/bot-builder-prompts), [Create advanced conversation flow using branches and loops](https://docs.microsoft.com/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow), and [Handle user interruptions](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-handle-user-interrupt).
