### ISSUE TITLE
How-to for integrating QnA Maker without relying on a sample

### ISSUE THREAD

**Issue by pkirch** [MicrosoftDocs/bot-docs#800]
Integrating the QnA Maker in my own bot using this article was difficult for me and my team because there is no description about what configuration and code are really necessary. It took some time to compare the sample code with my our own code. I would prefer to have only the steps necessary to include which do not rely on a sample. What took time here was to understand what the sample code does and what parts from the sample are necessary to call the QnA Maker. The sample could be referenced somewhere to study but the how-to should not rely on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Thanks for your feedback Peter,
The current article is indeed written with an assumption that the reader will be using the provided sample code. I will try adding additional information that highlights what is specifically required to access a separate user generated QnA Maker knowledgebase.

**Comment by DanDev33** [comment]
Article has been updated and will appear live on next update. Thanks for helping us make our docs better!
