### ISSUE TITLE
docs uses deprecated .generateAnswer() method -- should use getAnswers()

### ISSUE THREAD

**Issue by Zerryth** [MicrosoftDocs/bot-docs#801]
BotBuilder-Samples repo updated sample 11.qnamaker (node) to use getAnswers(), as in 4.2.0 generateAnswers() was deprecated since it didn't emit trace, didn't handle metadata, etc.

docs should be updated to use .getAnswers() for those using botbuilder versions 4.2.0 or later

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Thanks for catching this change. I'll update our docs.

**Comment by DanDev33** [comment]
You will see this change online when articles are next published.
