### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by mazhar1shaikh** [MicrosoftDocs/bot-docs#802]
Locally my bot work perfectly. But No matter how hard I tried to deploy my bot it doesn't work on Test in Web Chat.

I have created a bot using sdk v3 and publish it to azure.

After that I registered my bot on azure bot channel registration. And I followed the above deployment documentation step by step. 

But at a time of Test in Web Chat "couldn't send retry " "There was an error sending this message to your bot: HTTP status code Unauthorized" error is showing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your C# bot using Visual Studio - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-3.0)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
The deployment process is error prone. If you still need help, reach out to support engineering team on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework).

**Comment by mazhar1shaikh** [comment]
Can any one suggest why I am getting "There was an error sending this message to your bot: HTTP status code Unauthorized" why this error is showing?. 
I tried Stackoverflow but unfortunately it doesn't work for me.
