### ISSUE TITLE
az bot create requires additional device login

### ISSUE THREAD

**Issue by cloudguy-pro** [MicrosoftDocs/bot-docs#803]
Hi,
Currently the behaviour (at least for me) is after I have executed `az login` successfully is that if I run `az bot create ...` I get this message:

**Microsoft application id not passed as a parameter. Provisioning a new Microsoft application.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ..... to authenticate.**

My question is if there is a way to skip that login process or use a service principal instead of the need to login manually.
My idea is to integrate the bot resource creation in an Azure DevOps CI/CD pipeline and there is no way of login with that process...
Any help/ideas?

**Comment by ivorb** [comment]
@Kaiqb thoughts?

**Comment by Kaiqb** [comment]
This is by design. For this feature request, please open an issue in the Azure CLI repo: https://github.com/Azure/azure-cli.
