### ISSUE TITLE
Information on how to automate dispatch refresh

### ISSUE THREAD

**Issue by jjgriff93** [MicrosoftDocs/bot-docs#805]
It would be highly useful to have some instructions on performing dispatch refresh as part of a schedule, either as part of a CI/CD workflow (which incidentally is a missing topic from these docs at the moment) or as part of an automated Azure function etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a178d6a6-8037-940c-e8fb-aad548203b92
* Version Independent ID: 181758cf-3495-6848-5808-9dc8234140ab
* Content: [Enterprise Bot Customization - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-customize?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-customize.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-customize.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by darrenj** [comment]
Agreed - tracked on https://github.com/Microsoft/AI/issues/655

**Comment by Kaiqb** [comment]
It's been tracked in the solutions repo with the issue number listed above.
