### ISSUE TITLE
Difficult to switch from v3 to v4 docs

### ISSUE THREAD

**Issue by navzam** [MicrosoftDocs/bot-docs#807]
**Describe the bug**
If you're on a v3 doc that doesn't have a v4 equivalent, and you try to switch to v4 using the dropdown in the top left corner, you get the following error:

>  The requested page is not available for Azure Bot Service. You have been redirected to the newest product version this page is available for.

and stay on the v3 docs. The only way to get to the v4 docs from here is to find a doc that has a v4 equivalent (or go to the home page) and then use the version dropdown. This is a very frustrating experience.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-recognize-intent-luis?view=azure-bot-service-3.0 (a v3 doc)
2. Use the version dropdown in the top-left to switch to v4.
3. Observe the error.
4. Try to navigate to the v4 docs.

**Expected behavior**
I expected a clear path to the v4 docs, either to a similar v4 doc page or at least a link to the home page of the v4 docs.

**Comment by Kaiqb** [comment]
Unfortunately this the publishing platform's behavior.
