### ISSUE TITLE
Topic has section "Discard initial user input" which does not explain clearly how or why to do this

### ISSUE THREAD

**Issue by AndyCW** [MicrosoftDocs/bot-docs#810]
The text says "The following example watches for new conversation update activity, sends only one welcome message based on your user joining the conversation, and sets a Prompt status flag to ignore the user’s initial conversation input." The code snippets and linked sample does not show how to set a Prompt status flag to ignore the user's initial conversation input.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a16806-95d6-7c66-3b85-b2ace211f367
* Version Independent ID: c8565ece-392a-fb56-e911-8a5dd5555dee
* Content: [Send welcome message to users - Bot Service](https://docs.microsoft.com/en-gb/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&branch=live&tabs=csharp%2Ccsharpmulti%2Ccsharpwelcomeback#discard-initial-user-input)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DanDev33
* Microsoft Alias: **v-dashel**

**Comment by DanDev33** [comment]
Hi Andy,
Yes the original sample code that accompanied this article showed how to implement this, but the sample was later updated. I left the description because it addresses a real issue in how a bot acts differently based on different channels. Although that code is no longer in the sample, I will attempt to update this article to include code for doing this.

**Comment by DanDev33** [comment]
You will find this article updated to detail how the new sample code both skips the first connectionActivity and uses a flag DidBotWelcomeUser to ignore the initial user input when appropriate. This will go live with the next update. Thanks!
