### ISSUE TITLE
make code sample easier to read

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/bot-docs#811]
at first glance, it looks like this [code sample](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=javascript#working-with-the-recognition-results) are all from one file.  however, the comments show that they're snippets from different files.  

I think it's better to separate them into different snippets to make it more clear where these came from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=javascript#working-with-the-recognition-results)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by ivorb** [comment]
That's a fair point, it does appear they're all in one file until you read closer. I'll fix it, thanks!
