### ISSUE TITLE
Some JavaScript code samples in docs are actually TypeScript-based samples

### ISSUE THREAD

**Issue by kichinsky** [MicrosoftDocs/bot-docs#813]
Example above: public async getUserToken(context: TurnContext, code?: string): Promise&lt;TokenResponse|undefined&gt; {
    // Get the token and call validator
    const adapter: any = context.adapter as any; // cast to BotFrameworkAdapter
    return await adapter.getUserToken(context, this.settings.connectionName, code);
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by bw-kforce-ms** [comment]
Agree, TypeScript examples should be CLEAR.

**Comment by JonathanFingold** [comment]
The authentication article was rewritten, with new sample code for both JavaScript and C#.
