### ISSUE TITLE
Broken link to GitHub

### ISSUE THREAD

**Issue by madenwala** [MicrosoftDocs/bot-docs#814]
Link doesn't work. This happens in many pages. GitHub code links need to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc28a40-716e-22bc-8944-15f0a8b0d5c2
* Version Independent ID: 86252b0d-94e2-2ea6-ed17-fc32ae38e6fc
* Content: [Get notification from bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by ivorb** [comment]
Have you seen where other links are broken too? @Kaiqb we may want to scrub for certain links if the GitHub repo has changed, resulting in broken links

**Comment by Kaiqb** [comment]
Fixed.
