### ISSUE TITLE
Better proactive messaging sample needed

### ISSUE THREAD

**Issue by madenwala** [MicrosoftDocs/bot-docs#815]
This sample shows how you can update a list of "jobs" from within a bot. But what if you have an external process that needs to run and then send a message to an existing conversation?  The sample code should be updated to support this scenario...it's a common one that customers need.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc28a40-716e-22bc-8944-15f0a8b0d5c2
* Version Independent ID: 86252b0d-94e2-2ea6-ed17-fc32ae38e6fc
* Content: [Get notification from bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by ryanvolum** [comment]
@ivorb, @madenwala as an FYI, we had a team create a couple durable assets around a more fully-fledged proactive messaging samples. They're still active and being updated, but take a look at https://github.com/lucashuet93/botbuilder-proactivemessaging

**Comment by JonathanFingold** [comment]
The dev team has an updated proactive messaging sample that has been reduced in complexity to show just a trigger using a second controller and the proactive message received on the bot controller. The sample and updated article will go live in a few weeks. For a more complete proactive messaging sample, you'll need to request one from the dev team. To do so, open an issue in the [botbuilder-samples](https://github.com/Microsoft/BotBuilder-Samples) repo.

**Comment by Kaiqb** [comment]
The correct link to the new proactive sample is [here](https://github.com/Microsoft/BotBuilder-Samples/tree/samples-work-in-progress/samples/csharp_dotnetcore/16.proactive-messages).

**Comment by ryanvolum** [comment]
@Kaiqb I don't think the updated sample satisfies @madenwala's request. As with the current sample, the bot is invoking its own proactive message. Though this demonstrates the `ContinueConversation` API, it's effectively a reactive message. 

We've built a [multi-service sample](https://github.com/lucashuet93/botbuilder-proactivemessaging/tree/master/node#advanced-implementation) that exposes a new endpoint (`api/proactive`) for external services to invoke proactive messages from the bot. I'm happy to discuss the approach.

See GIF for full demonstration:
![Advanced Sample GIF](https://github.com/lucashuet93/botbuilder-proactivemessaging/raw/master/node/images/ProactiveMessage.gif)

**Comment by ryanvolum** [comment]
Actually, I'm seeing that you are using a second controller/endpoint in the C# sample, though the bot is still invoking its own proactive message. I'm not seeing this implemented in the [Node counterpart](https://github.com/Microsoft/BotBuilder-Samples/blob/samples-work-in-progress/samples/javascript_nodejs/16.proactive-messages/index.js).

I don't think we should be closing bugs until the fix has been merged into master _and_ is fixed across languages.

**Comment by madenwala** [comment]
Haven't had a chance to run this sample yet but @ryanvolum is right that there should also be a Node version of this

**Comment by EricDahlvang** [comment]
@madenwala The node sample does now have a /api/notify endpoint: https://github.com/Microsoft/BotBuilder-Samples/blob/samples-work-in-progress/samples/javascript_nodejs/16.proactive-messages/index.js#L57
