### ISSUE TITLE
Overview for communication between bot and bot channels registration

### ISSUE THREAD

**Issue by pkirch** [MicrosoftDocs/bot-docs#818]
Being a beginner in bot development it was quite confusing what I need the bot channels registration for and it still unclear to me how the communication looks like between my bot, the Azure Bot Channels Registration, and the different clients (Teams, Web Chat etc.). Would be very helpful if you have an overview diagram or at least some documentation you can provide or point to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0460109c-16ac-0b5c-8624-4d362122e8b4
* Version Independent ID: 2961c42d-695d-46f0-1c7b-9be929e3f88e
* Content: [Create a Bot Channels Registration with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-quickstart-registration.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart-registration.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by Kaiqb** [comment]
Here is a topic that provides an overview: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs.
