### ISSUE TITLE
Deployment options (Classic) doesn't exist

### ISSUE THREAD

**Issue by AskYous** [MicrosoftDocs/bot-docs#820]
I'm trying to go to this blade but I don't have it. I went to my bot, clicked "All App Service Settings," then looked for deployment options but couldn't find it. The closest I see deployment slots but it doesn't look the same when I click it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41386916-1ae4-1a69-855a-c48f3804e673
* Version Independent ID: 180ca783-20c2-672c-303c-69cc8b42e71b
* Content: [Configure continuous deployment for Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0#continuous-deployment-using-github)
* Content Source: [articles/bot-service-build-continuous-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-build-continuous-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
This doc was actually recently updated for several reasons, including yours, and we reference the link below for continuous deployment

https://docs.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment

See if that helps?

**Comment by DanDev33** [comment]
closed.
