### ISSUE TITLE
No docs for remote debugging a bot

### ISSUE THREAD

**Issue by navzam** [MicrosoftDocs/bot-docs#822]
This doc describes debugging a bot that is running locally, but there's no guidance on how to debug a deployed bot after following the ["deploy your bot" doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3691ca29-1a48-7842-8536-5f86d5ef0908
* Version Independent ID: 08ea18f3-3fe9-14a8-d08a-6bbc2b33b42d
* Content: [Debug a bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-bot?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-debug-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-debug-bot.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by DanteNahuel** [comment]
I agree about this.
I found this information useful:
https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/

**Comment by Kaiqb** [comment]
For now, added a link to the remote debugging blogpost in the additional resources section.
