### ISSUE TITLE
This section should be higher up as it's critical to development

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/bot-docs#823]
I think this section should be right below `How bots work` as it's pretty critical to development.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8cc826-fa2f-5521-ead7-b771ad527269
* Version Independent ID: 91bc6ab6-e909-e8da-74aa-4a178559c290
* Content: [Manage resources with a .bot file - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-file-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-file-basics.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
@mydiemho - we are working on simplifying the .bot file experience and will update the content when that is done.
