### ISSUE TITLE
Need better documentation on Directline

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/bot-docs#824]
We need documentation on

1. How directline works / what is it
    * I found the diagram under `What is the DirectLine Channel anyway?
` in this [blog post ](https://blog.botframework.com/2017/06/26/speech-to-text/) helpful 
1. What is the relationship between DirectLine & Webchat?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b093e81-4542-f9db-c79a-88b9b753d353
* Version Independent ID: dd976121-5f44-2205-826b-186f1ae2fa72
* Content: [Connect a bot to Direct Line - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directline?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-directline.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directline.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by EricDahlvang** [comment]
This came up on StackOverflow today too: https://stackoverflow.com/questions/54515066/directline-and-webchatdifference-and-similarities/54525419

**Comment by VijaySimhas** [comment]
Added directline channel in web app bot   azure.Request to provide documentation on integrate Luis.ai to directline

**Comment by Kaiqb** [comment]
New docs on Direct Line are [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline?view=azure-bot-service-4.0).
