### ISSUE TITLE
Missing documentation on how to properly work with LUIS and QnA models for different locales

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/bot-docs#825]
I'm missing guidance (documentation and samples) on how to properly work with localized LUIS and QnA apps.

I found the [Multilingual bot sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/17.multilingual-bot), but the user experience is lower with machine-translated content than with content written per locale.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by DanDev33** [comment]
Hi Hans, current versions of both QnA Maker and LUIS support multiple languages. You can find information/documentation on that here: https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/overview/language-support and here: https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-language-support . Guidance for incorporating this is not specifically discussed within our current bot documentation, but we will take it under consideration as a future enhancement.
