### ISSUE TITLE
Error: Invalid plugin type being added

### ISSUE THREAD

**Issue by 4h5j6For** [MicrosoftDocs/bot-docs#826]
When inserting additional classes like const{ ConversationState, MemoryStorage, CosmosDbStorage } = require('botbuilder')
and initialising the following code snippet, I receive the following error: 
Error: MiddlewareSet.use(): invalid plugin type being added.
at middleware.forEach (.../node_modules\botbuilder-core\lib\middlewareSet.js:58:23)
at Array.forEach (&lt;anonymous&gt;)
at MiddlewareSet.use (...\node_modules\botbuilder-core\lib\middlewareSet.js:50:20)
at BotFrameworkAdapter.use (...\node_modules\botbuilder-core\lib\botAdapter.js:31:53)
at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Additional code snippet:
// Add memory storage.
var storage = new MemoryStorage();
const conversationState = new ConversationState(storage);
adapter.use(conversationState);

Would be nice if you can provide help.
Best

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8f39f5-1a91-6fdb-3cc0-124b282e9806
* Version Independent ID: 701f9b3c-a893-dee1-d012-760e6f870ec4
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by Kaiqb** [comment]
You _might_ be missing npm packages. Try this [quickstart](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0) to see if you can build/run node a project from the start.

**Comment by 4h5j6For** [comment]
Yes, that works fine, I tried it several times, also all the samples are running and the bots are startable. 
It seems that the adapter.use(conversationState); statement is causing the problem. When removing at least I can write to CosmosDB.
Which packages could be causing this? Do you have any other explanation and help for it?

**Comment by 4h5j6For** [comment]
Any answer?

**Comment by neetibirla** [comment]
Any answer for this? I am also facing the same issue.

**Comment by EricDahlvang** [comment]
CosmosDbStorage is in botbuilder-azure https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-azure/src/cosmosDbStorage.ts

If the preference is to use CosmosDbStorage, it should be imported from the botbuilder-azure npm:
```js
 const{ CosmosDbStorage } = require('botbuilder-azure');
```
