### ISSUE TITLE
Direct Line API 3.0 Swagger file URL is 

### ISSUE THREAD

**Issue by hhcakir** [MicrosoftDocs/bot-docs#827]
Where can I find the Direct Line API 3.0 Swagger file swagger.json?
Link to https://docs.botframework.com/en-us/restapi/directline3/swagger.json is dead.
Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d7238a1-4d34-349b-e5cc-f7238c981892
* Version Independent ID: d5945944-58de-1221-d202-d14266bf7dc9
* Content: [Key concepts in the Bot Framework Direct Line API 3.0 - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-concepts?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-concepts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-concepts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
You don't need the swagger file to author bots. We use it internally as part of creating the SDKs. What problem are you running into?

**Comment by EricDahlvang** [comment]
The directline swagger file can now be found here: https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-protocol/directline-3.0.json

The path or filename might change in the future, so please make a copy if you are planning to use it at runtime.

**Comment by hhcakir** [comment]
> 
> 
> You don't need the swagger file to author bots. We use it internally as part of creating the SDKs. What problem are you running into?

I need the Swagger file for the application using DirectLine API, to connect a web client (browser using Websockets) to my BBv3 chatbot. The URL in the NodeJS code was pointing to https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-protocol/directline-3.0.json, which is not available anymore. Now this file is stored locally on the filesystem.

**Comment by angie4u** [comment]
I used this link [https://raw.githubusercontent.com/Microsoft/BotBuilder/master/specs/botframework-protocol/directline-3.0.json](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/specs/botframework-protocol/directline-3.0.json) to referencing the swagger.json file.
And I have another issue which is "mssing required param: tokenParameters". 
![image](https://user-images.githubusercontent.com/16282358/52607954-9da35580-2ebb-11e9-9bf2-61f152969241.png)
 Is there any change to this swagger.json file compare to the previous version?

**Comment by EricDahlvang** [comment]
@angie4u  This PR https://github.com/Microsoft/BotBuilder/pull/5289 sets tokenParameter required to 'false' in the Swagger file.  You can do this in your own copy too.  Please do not reference the version on GitHub, since it can change without notice and potentially break your bot.

The DirectLine sample has also been changed to load the swagger from a local file:

```js
var Swagger = require('swagger-client');
var open = require('open');
var directLineSpec = require('./directline-swagger.json');

// config items
var pollInterval = 1000;
var directLineSecret = 'DIRECTLINE_SECRET';
var directLineClientName = 'DirectLineClient';

var directLineClient = new Swagger(
    {
        spec: directLineSpec,
        usePromise: true,
    }).then((client) => {
        // add authorization header
        client.clientAuthorizations.add('AuthorizationBotConnector', new Swagger.ApiKeyAuthorization('Authorization', 'Bearer ' + directLineSecret, 'header'));
        return client;
    }).catch((err) =>
        console.error('Error initializing DirectLine client', err));
```
   
https://github.com/Microsoft/BotBuilder-Samples/blob/v3-sdk-samples/Node/core-DirectLine/DirectLineClient/app.js
