### ISSUE TITLE
Carousel limit in Teams 

### ISSUE THREAD

**Issue by steepho** [MicrosoftDocs/bot-docs#829]
Is there anyway to increase the limit on carousel adaptive cards in Teams from 10 to 20?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 607856cb-baae-c401-5b34-876b5018771d
* Version Independent ID: 77df1de7-7b2e-a546-1280-a66121039a94
* Content: [Add media to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-add-media-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-media-attachments.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
I'm not sure. That information _might_ be in Teams documentation.

**Comment by steepho** [comment]
It is in the documentation. It's 10. I am requesting it to be raised to 20. Who would I get connected with to make that happen?
