### ISSUE TITLE
Chatbot is not answering to other users

### ISSUE THREAD

**Issue by manisimunkova** [MicrosoftDocs/bot-docs#830]
I have a problem with a chatbot on Facebook page. I have connected MS Azure chatbot to FB Messenger. It correctly answers to me as a developer but no other FB users get the answer. What should I do? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acb1736e-f822-2374-fc91-60a13567966e
* Version Independent ID: 03a952ae-0752-9aeb-a214-981bbfaf3b91
* Content: [Connect a bot to Facebook Messenger - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-facebook.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-facebook.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **RobStand**

**Comment by ivorb** [comment]
Could you give us more information about the bot you're running? Is it a sample, or one that you wrote yourself? Can the other users successfully send it messages, and it just doesn't respond to them?

**Comment by manisimunkova** [comment]
It's my own. I have already fixed it. The problem was in Facebook for developers. I had to went through couple verifications.

**Comment by ivorb** [comment]
Glad it was fixed!
