### ISSUE TITLE
OECD Privacy Generator Link

### ISSUE THREAD

**Issue by jwiley84** [MicrosoftDocs/bot-docs#831]
The generator no longer exists and that link is invalid. I don't believe they came up with a substitute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2e431c-e5ab-e733-ef58-8d9c450c0d75
* Version Independent ID: c3bbe2ec-5b6a-71f8-e465-e0bd760b66d5
* Content: [Bot review guidelines - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-review-guidelines?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-review-guidelines.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-review-guidelines.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kaiqb**

**Comment by ivorb** [comment]
Correct. We have links to two other generators, or there are plenty with an internet search.
Removed link from doc, will be pushed shortly
