### ISSUE TITLE
Europe and Australia luis support

### ISSUE THREAD

**Issue by krajniak** [MicrosoftDocs/bot-docs#835]
**Describe the bug**
Attaching non-us luis resource in bot emulator is not possible

**To Reproduce**
1. create a luis model on eu.luis.ai or au.luis.ai
2. try to add new luis service in bot framework emulator
3. you will only see models from www.luis.ai

**Expected behavior**
There should be possibility to select different luis portals

**Comment by Kaiqb** [comment]
This issue is being tracked in the [emulator repo](https://github.com/Microsoft/BotFramework-Emulator/issues/1310).
