### ISSUE TITLE
turnContext should be used as parameter for qnaMaker.getAnswers 

### ISSUE THREAD

**Issue by MarekLani** [MicrosoftDocs/bot-docs#836]
getAnswers method should be called like this: await this.qnaMaker.getAnswers(turnContext) not with turnContext.activity.text as parameter. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Hi Marek,
Thank you for your feedback. Our sample code had been corrected to reflect this, but the NodeJS example in our documentation was not updated to reflect this change. I will correct it now and you will see the corrected call the next time we update the docs. Thanks for helping us make our documentation better!
