### ISSUE TITLE
How to validate Prompt

### ISSUE THREAD

**Issue by enKoding** [MicrosoftDocs/bot-docs#837]
Hi guys, in this case how can I validate "LOCATION_PROMPT" and reprompt if it fails ? Thank you !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72538432-fde5-22ab-7997-8a34b11aa24e
* Version Independent ID: c469fa5b-2590-ee16-1491-51b90c069204
* Content: [Gather user input using a dialog prompt - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-prompts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
[Custom validation](https://docs.microsoft.com/azure/bot-service/bot-builder-prompts#custom-validation) describes how to create a prompt that includes validation. (See [prompt types](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-dialog#prompt-types) for a list of the available prompt types.)
- If you're selecting a value from a list, consider using a ChoicePrompt, which has built-in validation.
- If your user can enter free-form text and you're using a TextPrompt, then you would need to attempt to resolve and normalize the input in the validator.
  - If validation fails, return false from the validator.
  - If validation succeeds, set the `PromptValidatorContext` object's _value_ property to the normalized value, and then return true from the validator.

**Comment by enKoding** [comment]
Do you have any example using PromptValidatorContext in "nodeJs" ? I do need  to validate a free-form text. Thank you !

**Comment by JonathanFingold** [comment]
See the [custom validation](https://docs.microsoft.com/azure/bot-service/bot-builder-prompts#custom-validation) section in the **gather user input using a dialog prompt** topic.

**Comment by JonathanFingold** [comment]
PS. promptContext.recognized.value should be a string for a TextPrompt validator.

**Comment by enKoding** [comment]
But again... they are not talking about free text... they are using predefined Prompt Types... (NumberPrompt, DateTimePrompt)

**Comment by JonathanFingold** [comment]
The TextPrompt accepts free text, and its validator works similarly to the other prompt types.

**Comment by Naveenbc** [comment]
@enKoding Did you find a way to validate free text? If yes can you please post an example?
