### ISSUE TITLE
"Enable speech in Web Chat" is not working

### ISSUE THREAD

**Issue by never610** [MicrosoftDocs/bot-docs#838]
Hi everyone, 
Browser-provided speech cannot support Cantonese, 
the speech API -cognitive-services are also not working with error below:

WebsocketMessageAdapter.ts:81 WebSocket connection to 'wss://speech.platform.bing.com/speech/recognition/interactive/cognitiveservices/v1?format=simple&language=en-US&Ocp-Apim-Subscription-Key=3b47ebc974a440918060d317b1c03a8e&X-ConnectionId=52002B4A1E6E4C839CC9EB1041A4D172' failed: HTTP Authentication failed; no valid credentials available

I have tried to open a local server to run the HTML file / even in an https server are also not working.

On the other hand, is there any method that can integrate Web Speech API into the Azure bot? Since there is a limitation in the speech options of the bot, which make the Web Speech API settings cannot fit into the bot and have the message like :
instance.speechIsAvailable is not a function

I have seen some site calming that the speech function is broken since the last update, can it be used right now?

Thank You!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4689475d-3454-3eb7-9211-453867a3a1ae
* Version Independent ID: 321658a5-145b-a72c-1fe4-60b5a707e5d4
* Content: [Enable speech in Web Chat - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat-speech?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-channel-connect-webchat-speech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-webchat-speech.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by ivorb** [comment]
There is a current effort to revamp our unified speech in response to many speech issues our users are experiencing, and that is still under development. Speech right now might not work as expected, but we will be pushing out that update as soon as we can. Thanks for your patience!
