### ISSUE TITLE
Update package name along with dotnet cmd

### ISSUE THREAD

**Issue by narulasrinivas** [MicrosoftDocs/bot-docs#841]
In C# project documentation, Instead of giving the step as "Add the Microsoft.Bot.Builder.AI.QnA NuGet package to your project.". It will be clear if it is updated with Run "dotnet add package Microsoft.Bot.Builder.AI.QnA" to your project. 

Though it is a small one, people like me moving from .net framework to .net core will be great help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by ivorb** [comment]
Hi @narulasrinivas, there are multiple ways to add packages to your project, and we don't require our users to do it in any one specific way so we leave the method of doing so up to them. If the dotnet CLI works best for you, great! Many other users prefer to use the NuGet package UI built into VS, so CLI commands don't help them much.
