### ISSUE TITLE
Broken URL to v4 documentation

### ISSUE THREAD

**Issue by madenwala** [MicrosoftDocs/bot-docs#842]
The top header section which asks you if you want to see the v4 documentation only takes you to the overall bot documentation landing page. I believe it should go to this URL instead:

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d80e0b-f1b7-175b-128d-0fb12f17ae36
* Version Independent ID: 1ed9006a-bf0b-9aaa-d180-9d2cb0c09524
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0)
* Content Source: [articles/bot-builder-tutorial-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tutorial-authentication.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **JonathanFingold**

**Comment by ivorb** [comment]
Each page doesn't correspond to the same page in each version, so we can't directly link to another page. That header is provided for a heads up and an easy way to switch to the V4 content. Additionally, the drop down on the left above the TOC allows you to switch between versions of our content, so if you want to see if the same page is available in the opposite version, you can try toggling it there
