### ISSUE TITLE
What happened to the swagger endpoint?

### ISSUE THREAD

**Issue by marvoh** [MicrosoftDocs/bot-docs#844]
We have a production Node.js application that relies on the spec definition on the link below.

https://docs.botframework.com/en-us/restapi/directline3/swagger.json

Our app is now dead because the the link redirects to https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0.

How can we update our code to ensure we get back live?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9e2e6-b901-9e27-d070-701922396a4c
* Version Independent ID: c29a68b2-886d-2cec-0ce7-c49c586d7ea8
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by ivorb** [comment]
Take a look here, seems the content just got moved - the bottom of the TOC section on left should link to the swagger file

https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-concepts?view=azure-bot-service-4.0
