### ISSUE TITLE
AuthenticationDialog

### ISSUE THREAD

**Issue by balikpinoy** [MicrosoftDocs/bot-docs#845]
Can you update the instructions with how to incorporate the AuthenticationDialog?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a178d6a6-8037-940c-e8fb-aad548203b92
* Version Independent ID: 181758cf-3495-6848-5808-9dc8234140ab
* Content: [Enterprise Bot Customization - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-customize?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-customize.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-customize.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by miojoffey** [comment]
i agree, been bangin my head on this one. 
@balikpinoy: have you figured out how to do this? thanks

**Comment by balikpinoy** [comment]
@miojoffey I basically ditched the dialogs example within the enterprise template and incorporated the Authentication Bot sample instead into the project.

**Comment by miojoffey** [comment]
@balikpinoy you're right, with its lack of documentation, sometimes its frustrating to go thru this. i somehow made it work but i'm not sure if this was the best approach, just saw this on an old repository and it worked anyway. hope MS updates their docs on how to properly integrate their built-in **AuthenticationDialog**. hope this helps others in dire need.

![auth-dialog](https://user-images.githubusercontent.com/14160919/54962981-f9c0c580-4fa1-11e9-937e-670b945948cf.png)

to the community, corrections and suggestions are much appreciated

**Comment by Kaiqb** [comment]
The content referenced here has been removed with VA templates.
