### ISSUE TITLE
Step 8 is missing

### ISSUE THREAD

**Issue by IAmBotmaker** [MicrosoftDocs/bot-docs#847]
Upon validation - we need to return to conversation in the bot.
As far as I checked - we need to use proactive messages or something like that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e652a2a-3815-9702-af48-e743f5ce7ebd
* Version Independent ID: 4e7a0462-8a8f-22aa-ee6e-4d9f8f0981e2
* Content: [Integrate your bot with a web browser - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-integrate-browser?view=azure-bot-service-4.0#generate-hyperlink)
* Content Source: [articles/bot-service-design-pattern-integrate-browser.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-pattern-integrate-browser.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by JonathanFingold** [comment]
@IAmBotmaker , with the updated sample and article, the flow should now be clearer and more complete.
