### ISSUE TITLE
CosmoDB with free subscription

### ISSUE THREAD

**Issue by Wendy-YongAiJing** [MicrosoftDocs/bot-docs#848]
While changing from MemoryStorage to CosmoDB storage, my bot doesn't work. Is that because I'm using free subscription?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8f39f5-1a91-6fdb-3cc0-124b282e9806
* Version Independent ID: 701f9b3c-a893-dee1-d012-760e6f870ec4
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp#memory-storage)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by DanDev33** [comment]
Hi Wendy - the free version of CosmosDB should work fine. You did not mention if you were building in C# or NodeJS. Each has a different method for saving the CosmosDB access information. One important thing both have in common is to select SQL as your implementation type when creating your CosmosDB storage. Can you please provide a few more details concerning the language you are working in, and how you have saved the CosmosDB access information? Thanks!

**Comment by Wendy-YongAiJing** [comment]
I'm building bot in C#. After I able to use memory storage, I update my code to use CosmoDB. I followed the instruction by changing this code
private static readonly MemoryStorage _myStorage = new MemoryStorage();
to
private static readonly CosmosDbStorage _myStorage = new CosmosDbStorage(new CosmosDbStorageOptions
        //{
            AuthKey = CosmosDBKey,
            CollectionId = CosmosDBCollectionName,
            CosmosDBEndpoint = new Uri(CosmosServiceEndpoint),
            DatabaseId = CosmosDBDatabaseName,
        });
There is no error showing in my coding but when I start my bot, it shows me message "Sorry, it looks like something went wrong."

When I create CosmoDB database account in Azure, I did chose SQL; same resource group and subscription; leave Geo-redundancy as default (enable) ; also leave Multi-region Write as default (disable)

Then I copy endpoint URL and PRIMARY KEY found in Key tab to my code there as :
private const string CosmosServiceEndpoint = "https://webprojectcosmodb.documents.azure.com:443/";
private const string CosmosDBKey = "1chn..............";
private const string CosmosDBDatabaseName = "bot-cosmos-sql-db";
private const string CosmosDBCollectionName = "bot-storage";

Much appreciation if u could help me!

**Comment by DanDev33** [comment]
Hi Wendy,
I was no longer able to use the sample, as outlined in our documentation, to write to CosmosDb. I am testing to see what has changed and will provide you with a working solution as soon as I have one. Thanks for helping us keep our documentation up to date with these ongoing changes!

**Comment by DanDev33** [comment]
Hi Wendy,
I was able to get this to work properly using sample 02.b.echo-with-counter from Botbuilder-Samples and then adding _myStorage first for memory and then for Cosmos DB. Looking at the code sample you pasted above I noticed the following:

CosmosDbStorageOptions
//{
AuthKey = CosmosDBKey,

The opening bracket following CosmosDBStorageOptions is commented out.
Could you please check that the call looks like this:

private static readonly CosmosDbStorage _myStorage = new CosmosDbStorage(new CosmosDbStorageOptions
        {
            AuthKey = CosmosDBKey,
            CollectionId = CosmosDBCollectionName,
            CosmosDBEndpoint = new Uri(CosmosServiceEndpoint),
            DatabaseId = CosmosDBDatabaseName,
        });

and then let me know if that resolves your problem.
Meanwhile, I will be revising the article to no longer have people start by using the Visual Studio VSIX file, but instead start from existing Botbuilder-Samples sample code.

**Comment by Wendy-YongAiJing** [comment]
Hi DanDev33, sorry for the late reply. Sorry for the typo of that part where { is commented out. I actually worked on this problem several time but still cannot solve it out. Please let me know if u have any solution. Thank you so much!

**Comment by ivorb** [comment]
@DanDev33 see linked issue above for some extra information, if needed

**Comment by Wendy-YongAiJing** [comment]
Please assist me if anyone does have a solution.

**Comment by DanDev33** [comment]
Hi Wendy,
This article is scheduled to finally update today - the JS code was outdated before and did not work. If you start from current C# sample 02.a <echoBot> and add the code provided, it should work for you and store data into CosmosDb. If this does work, please compare this it your current code that is not working to see where that differs. If it does not work, then the issue may actually be the free account itself (I hope that is not the case). Once the updated code in this article is available, please do try this and let us know if it resolves your issue.

**Comment by Wendy-YongAiJing** [comment]
Hi DanDev33,

Can you provide me the link to access C# sample 02.a?

**Comment by DanDev33** [comment]
This link is also called out in the article, but here it is Wendy: 
https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/02.a.echo-bot

**Comment by DanDev33** [comment]
Hi Wendy,
Closing this because it's really not a doc issue at this point. But I did hear from someone that unlike here in the US, there are other areas of the world where the "Free" version of Azure has less functionality than the "Developer Free" version. If you are still experiencing this issue, you may try using the developer free version of Azure instead to see if it resolves this for you. Hope this helps.

**Comment by Wendy-YongAiJing** [comment]
Hi, I currently using cosmodb emulator to test my code and save data in local storage. What I did is installed the cosmodb emulator and change the code to
private const string CosmosServiceEndpoint = "https://localhost:8081/_explorer/index.html";
private const string CosmosDBKey = "<the master key>";

So, I think the main problem is I'm using free subscription on Azure. Thank you so much for your help!
