### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by aeisenberg** [MicrosoftDocs/bot-docs#851]
Looks like the botbuilder repository has moved. The links to  Proactive Messages, simpleSendMessage, and startNewDialog are all broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a43a9bfa-a69a-ffb2-31a6-d06d78517671
* Version Independent ID: 6bcbbcbf-79f2-9b81-7d03-b9bd8d6286a1
* Content: [Send proactive messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-proactive-messages?view=azure-bot-service-3.0#send-an-ad-hoc-proactive-message)
* Content Source: [articles/nodejs/bot-builder-nodejs-proactive-messages.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-proactive-messages.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by DanDev33** [comment]
Hi Andrew,
Yes these samples have been deprecated and moved to repository: https://github.com/Microsoft/BotBuilder-V3

**Comment by DanDev33** [comment]
We will correct these links in the article and you should see this live the next time the article is published. Thanks for helping us keep our documentation accurate!

**Comment by DanDev33** [comment]
article links updated.
