### ISSUE TITLE
Starting a group chat

### ISSUE THREAD

**Issue by yahalawa** [MicrosoftDocs/bot-docs#852]
I am having trouble starting a group chat. Here is my request:

{
  "isGroupChat": true,
  "bot": {
    "id": "c57df800-a739-436e-beaa-d509dc0de6b0",
    "name": "Donut-Yaz"
  },
  "members": [
    {
      "id": "29:1Jz_wG-tR0TF8cHxi0cZL7d7tfqowjfKdWNA_4hWm0wEN5umbnqRZwrFmu2b-S_y0sWfjiKUGDMzWrnq5JgaGJg"
    },
    {
      "id": "29:1Rl8C8mqDsPez7uFnHJh2Gpti3UGnYTRHfSlxze7vktJu2E2ZtmWtzzEjvjXOFXQe3TJi9VvM-1i_yMOutQKUFQ"
    }
  ]
}

and the headers include the authorization header, the content type as json, and the user agent as the bot framework. I am getting the following as a response:

{
    "error": {
        "code": "BadSyntax",
        "message": "Incorrect conversation creation parameters"
    }
}

Now if I remove the second member from my request body and add a tenant id it works. So I am able to create a 1 on 1 chat but I cannot create a group chat and I am using 1.3 in the manifest version. Please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e47c9b6-a06c-caa8-9b8f-b50fdfa70109
* Version Independent ID: d24d686f-8d14-eb25-9fe9-112df8993ae4
* Content: [API reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#channelaccount-object)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
Sorry for the long delay. We've recently fixed some issues in the REST API reference, which should clarify what the proper JSON object should look like. Note that most channels do not currently support the ability for a bot to initiate a group chat.
