### ISSUE TITLE
Typo: Extraneous ) in https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant

### ISSUE THREAD

**Issue by ElizabethGreene** [MicrosoftDocs/bot-docs#853]
There is a typo on https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant

Updating your Virtual Assistant) -> Updating your Virtual Assistant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7338c62d-fdb3-5177-cf36-d37398c1d687
* Version Independent ID: c5cac0e9-fb71-6e2c-11df-5e940fd80fc8
* Content: [Virtual Assistant Overview - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-virtual-assistant-introduction?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-virtual-assistant-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-virtual-assistant-introduction.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by Kaiqb** [comment]
please open the bug in [this ](https://github.com/microsoft/botframework-solutions)repo.
