### ISSUE TITLE
Confusing Pattern

### ISSUE THREAD

**Issue by FaithZeroWigs** [MicrosoftDocs/bot-docs#855]
I can't really figure out why the pattern where the accessors are initialized outside the MultiTurnPromptsBotAccessors. Since the relevant objects are passed in as constructor parameters, the constructor can also initialize the IStatePropertyAccessor members as well. Unless there some particular reason for that the pattern is confusing and breaks the isolation of the MultiTurnPromptsBotAccessors class. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c5adf9-272a-e0f1-10f1-c8365e76035b
* Version Independent ID: 1982af41-5a06-4398-0e95-abcc50864e0d
* Content: [Implement sequential conversation flow - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
How the state pieces are handled in the samples is in flux. The current paradigm is understood to be confusing. We'll update the docs as the samples get updated. We're just not sure what that timing is yet.
