### ISSUE TITLE
Link to channel inspector is broken

### ISSUE THREAD

**Issue by neoashu** [MicrosoftDocs/bot-docs#856]
Tip

Use the Channel Inspector to see how suggested actions look and work on various channels.
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-inspector?view=azure-bot-service-3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b809442-7e1a-0186-e59b-0e4d587104ac
* Version Independent ID: 694d8c3e-37f8-100e-cffa-1634b883b3dc
* Content: [Add suggested actions to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-suggested-actions?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/nodejs/bot-builder-nodejs-send-suggested-actions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-send-suggested-actions.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Unfortunately, the team is not currently supporting the channel inspector.
- I've opened [PR 1311](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1311) to remove the **tip** and to link to the v3 samples repo in **Additional resources**.
- Changes should go live later in the week.
