### ISSUE TITLE
whats expected after a successful first deployment?

### ISSUE THREAD

**Issue by olufemig** [MicrosoftDocs/bot-docs#859]
On deploying the template for the first time after running the recipe, i got a 'Welcome to Bot Framework' screen with some learning options in the emulator.

On entering 'hi', i got a 'Sorry, it looks like something went wrong'.

With those responses, Its a bit hard to tell if my deployment was successful. Could anyone help clarify? Thanks

---
#### Sonraí doiciméid

⚠ *Ná cuir an rannán seo in eagar. Tá sé riachtanach le haghaidh docs.microsoft.com ➟ nascadh fadhbanna GitHub.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/ga-ie/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0#)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by sarikapal** [comment]
Hey... I am also getting the same error after entering "hi" on emulator

**Comment by Kaiqb** [comment]
This topic no longer exists in the docs.
