### ISSUE TITLE
Commiting the creds in bot file.

### ISSUE THREAD

**Issue by pesetskyps** [MicrosoftDocs/bot-docs#860]
"Open the .bot file you decrypted. Copy entries listed under the services section, and add them to your local .bot file."
" Commit your code into the repository."
This looks like committing the secure data to the repo. Is there way to do it right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by pesetskyps** [comment]
Looks liek the correct steps will be:
1. Encrypt bot file 
2. update the new secret in azure
Is it correct?
https://github.com/Microsoft/botbuilder-tools/blob/master/packages/MSBot/docs/bot-file-encryption.md

**Comment by JonathanFingold** [comment]
With the 4.3 release, we'll be moving away from using .bot files. We'll update the deployment topics at that time.

**Comment by mutanttech** [comment]
Thanks Jonathan for this update. From the very start this .bot file idea looked really odd to me. I could not really digest why even this way was pursued, can you please tell what's the new thing coming now.
Regards..

**Comment by JonathanFingold** [comment]
For 4.3, I think the suggestion will be to put the service information in appsettings.json (or .ENV for Javascript) or to use Asure Key Vault.

**Comment by mutanttech** [comment]
Using Key Vault is the best way to secure secret information. The only thing I would want to see improved ARM template to provision KeyVault and creating secrets. I had problems with using if conditions for creating secrets through ARM template.

**Comment by JonathanFingold** [comment]
I'll mention that to the dev team, which is looking into using ARM templates as a deployment approach.

**Comment by madenwala** [comment]
@pesetskyps  I was about to file a comment on the whole delete your botFileSecret comment...I didn't understand why that was recommended as a step...I left the botFileSecret as it was and to open the bot file through the emulator, I would just apply the secret when prompted by the emulator to decrypt the file (while in the emulator) and make any necessary changes.  This would prevent one from storing secrets into your repo.

**Comment by Kaiqb** [comment]
Issue seems to have been addressed.
