### ISSUE TITLE
Should this not mention that different URIs are supported?

### ISSUE THREAD

**Issue by willemodendaal** [MicrosoftDocs/bot-docs#863]
According to bot framework documentation (https://blog.botframework.com/2017/02/02/direct-line-performance-improvements/), it's possible to specify a region-specific directline uri. This article implies that only directline.botframework.com is supported.  Should this article not mention that region-specific urls can be specified as Baseuri?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd81692-76ae-f89f-19d8-d92845cc7dc9
* Version Independent ID: c26a44b5-6995-11e0-daa0-001a2716b9f1
* Content: [API reference - Direct Line API 3.0 - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-api-reference.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by YehezkielSaputra** [comment]
I have the same case and I'm trying to implement change the URL server domain connector :
(Refer to https://github.com/microsoft/BotFramework-DirectLineJS)

import { DirectLine } from 'botframework-directlinejs';

var directLine = new DirectLine({
    secret: /* put your Direct Line secret here */,
    token: /* or put your Direct Line token here (supply secret OR token, not both) */,
    domain: /* optional: if you are not using the default Direct Line endpoint, e.g. if you are using a region-specific endpoint, put its full URL here */
    webSocket: /* optional: false if you want to use polling GET to receive messages. Defaults to true (use WebSocket). */,
    pollingInterval: /* optional: set polling interval in milliseconds. Default to 1000 */,
});

is anyone has implemented it before? 
any sample or project that I can follow?

My case is I'm trying to try connecting my bot with another server connector instead of using DirectLine Server. Any response and help would be appreciated. 
Thanks in advance.

**Comment by CoHealer** [comment]
Re-applying support label for aggregation inclusion

**Comment by CoHealer** [comment]
@tdurnford, can you please assist?

**Comment by tdurnford** [comment]
@YehezkielSaputra How are you trying to connect to your bot?

**Comment by CoHealer** [comment]
Resolving, no customer response.
