### ISSUE TITLE
botframework-webchat libraries, why are they not in TypeScript

### ISSUE THREAD

**Issue by kevinclarkneudesic** [MicrosoftDocs/bot-docs#864]
I am looking into the botframework-webchat to see how I can integrate it in with my client web application and am wondering why it is written in vanilla js and not TypeScript.  Especially since it is 2019 and this is a Microsoft product!  TypeScript makes it a lot easier to understand a library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a95d02-732d-3324-37ce-d2c1a41131e0
* Version Independent ID: bc0366f3-8714-e758-ff02-07837a7751d0
* Content: [Connect a bot to the Web Chat channel - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-webchat.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-webchat.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Please log the issue in the [Microsoft/BotFramework-WebChat](https://github.com/Microsoft/BotFramework-WebChat) repository.

**Comment by JonathanFingold** [comment]
Please open this issue in the [Microsoft/BotFramework-WebChat](https://github.com/Microsoft/BotFramework-WebChat) repo.
