### ISSUE TITLE
question is not defined nodejs

### ISSUE THREAD

**Issue by sunnysharma03** [MicrosoftDocs/bot-docs#866]
Hi i am running the code samples which are provides in nodeJs and  i'm facing this issue. 
[onTurnError]: ReferenceError: question is not defined

and i'm not able to find conversationFlow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79129724-5f90-ac8d-6918-d5801a4e2001
* Version Independent ID: 08e19b7b-2ec6-95da-2f5a-d534e761f5da
* Content: [Create your own prompts to gather user input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-primitive-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-primitive-prompts.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
> [onTurnError]: ReferenceError: question is not defined

This indicates that the turn handler threw an uncaught exception.

The conversation flow property is used in **CustomPromptBot.cs** (C#) and in **bot.js** (JavaScript).

**Comment by sunnysharma03** [comment]
@JonathanFingold 
I know it throw an uncaught exception, I want to ask it ha been not defined in the sample code which is provided for  **Create your own prompts to gather user input**
and conversationFlow is also not defined anywhere in the sample, it is directly used inside **The bot's turn handler.**
can you please help to defined the question and conversationFlow.
Thanks.

**Comment by JonathanFingold** [comment]
I wasn't clear on what your original question was. The full code is linked to from the article. We try to include only the code that is most relevant to the article.

I'll add a mention that the instance property `conversationFlow` is set in the bot's constructor.

**Comment by JonathanFingold** [comment]
Sorry, I wasn't clear on what your original request was. I'll update the PR to mention that the `conversationFlow` instance property is set in the constructor. We link to the full sample code, but don't include all sample code in the article.
