### ISSUE TITLE
Inconsistency between this doc and the sample on initialisation of didBotWelcomeUser

### ISSUE THREAD

**Issue by martinkearn** [MicrosoftDocs/bot-docs#867]
There is an inconsistency between this doc and the sample in the first line of the `OnTurnAsync` function where the `didBotWelcomeUser` property gets set.

This document has 

`var didBotWelcomeUser = await _welcomeUserStateAccessors.DidBotWelcomeUser.GetAsync(turnContext, () => false);`

The 'welcome user' sample has

`var didBotWelcomeUser = await _welcomeUserStateAccessors.WelcomeUserState.GetAsync(turnContext, () => new WelcomeUserState());`

As far as I can tell, the sample is right and doc is wrong, but I may be wrong about that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a16806-95d6-7c66-3b85-b2ace211f367
* Version Independent ID: c8565ece-392a-fb56-e911-8a5dd5555dee
* Content: [Send welcome message to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DanDev33
* Microsoft Alias: **v-dashel**

**Comment by JonathanFingold** [comment]
The C# sample was updated in the samples repo, and we missed the change. The article is updated in [PR 1311](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1311) and should go live later this week.

**Comment by martinkearn** [comment]
Thanks @JonathanFingold, I have a follow-on question. As a general rule, are the samples more up to date than the docs generally speaking?

**Comment by JonathanFingold** [comment]
Unfortunately, it goes back and forth a bit. We're trying to work out the kinks in the process so everything is more consistently up to date sooner. We're also looking at tuning the list of samples in the samples repo.
