### ISSUE TITLE
Documentation on formatting prompts?

### ISSUE THREAD

**Issue by DanteNahuel** [MicrosoftDocs/bot-docs#869]
Hi
I can't find any information about formatting prompt's options.
i want to use PromptOptions because I want to use the integrated RetryPrompt. However I don't like the format of the ChoiceFactory.ToChoices (A numbered list).
Is there any way to format the list/choices to buttons like when using MessageFactory.SuggestedActions ?
I can't find any documentation about this.

**Comment by JonathanFingold** [comment]
We don't have any in depth documentation on this, and I haven't explored the options much, but the [`ChoiceFactory`](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs) class provides a lot of helper methods, including presenting the choices within a hero card.

**Comment by DanteNahuel** [comment]
Thank you Jonathan.
Maybe we can add this in time, along with ChoiceFactory formatting.

**Comment by DanteNahuel** [comment]
@JonathanFingold 
The .net documentation for adding cards in v4 is not there. Is this because there is no Adaptive Card support for v4? or is the doc missing?

**Comment by JonathanFingold** [comment]
I'll leave this issue open until we can add a section or article on using the ChoiceFactory.

With respect to cards and Adaptive cards, see the [rich media](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-add-media-attachments) how-to.

**Comment by JonathanFingold** [comment]
@DanteNahuel Sorry for the long silence. The reference documentation for [ChoiceFactory](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.choices.choicefactory) should get updated soon, when the 4.5 ref content goes live.
