### ISSUE TITLE
Adding botConfig to services twice?

### ISSUE THREAD

**Issue by ReinhardtJ** [MicrosoftDocs/bot-docs#871]
In the third code snipped, inside the `ConfigureServices` method there are two identical (?) calls for the `AddSingleton` method which add the `botConfig` (not considering the null check):

```CS
(....)
    // first call, with null check
    services.AddSingleton(sp => botConfig ?? throw new InvalidOperationException($"The .bot config file could not be loaded. ({botConfig})")); 

    var connectedServices = new BotServices(botConfig);
    services.AddSingleton(sp => connectedServices);
    services.AddSingleton(sp => botConfig); // second call, without null check
(....)
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Add natural language understanding to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Hi Jonas,
Thank you for your feedback catching this. While this doesn't affect the performance of the LUIS bot it is confusing to have the same singleton added twice. I will correct the example and post a request to have this extra call removed from our sample. You will see this change reflected live when this article is next published. Thanks again!

**Comment by DanDev33** [comment]
article updated.
