### ISSUE TITLE
Type unsafe choice for recognizerResult.Entities (C#)?

### ISSUE THREAD

**Issue by justinbarias** [MicrosoftDocs/bot-docs#873]
Understand this was just auto generated from a swagger rest api spec, and might be OK for JS.. But we might want a more type safe representation of the entities objects? Plus, the JSON schema for the entities isn't documented anywhere. 
Also, the example helper function also covers simple type/score checks.. No documentation on say, currency type entities or other builtin entity types..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Add natural language understanding to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs#optional---extract-entities)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
The corresponding sample code will be updated once 4.3 is released. I'll update this topic at that time, and use a strongly-typed class to receive the LUIS result.

**Comment by JonathanFingold** [comment]
Looks like the team is moving in this direction with respect to handling LUIS results:
```csharp
public static async Task<BookingDetails> ExecuteLuisQuery(IConfiguration configuration, ILogger logger, ITurnContext turnContext, CancellationToken cancellationToken)
{
    var bookingDetails = new BookingDetails();

    try
    {
        // Create the LUIS client from configuration.
        var luisService = new LuisService
        {
            AppId = configuration["Luis-Booking-AppId"],
            AuthoringKey = configuration["Luis-Booking-AuthoringKey"],
            Region = configuration["Luis-Booking-Region"],
        };

        var recognizer = new LuisRecognizer(new LuisApplication(
            luisService.AppId,
            luisService.AuthoringKey,
            luisService.GetEndpoint()));

        // The actual call to LUIS
        var recognizerResult = await recognizer.RecognizeAsync(turnContext, cancellationToken);

        var (intent, score) = recognizerResult.GetTopScoringIntent();
        if (intent == "Book_flight")
        {
            // We need to get the result from the LUIS JSON which at every level returns an array.
            bookingDetails.Destination = recognizerResult.Entities["To"]?.FirstOrDefault()?["Airport"]?.FirstOrDefault()?.FirstOrDefault()?.ToString();
            bookingDetails.Origin = recognizerResult.Entities["From"]?.FirstOrDefault()?["Airport"]?.FirstOrDefault()?.FirstOrDefault()?.ToString();

            // This value will be a TIMEX. And we are only interested in a Date so grab the first result and drop the Time part.
            // TIMEX is a format that represents DateTime expressions that include some ambiguity. e.g. missing a Year.
            bookingDetails.TravelDate = recognizerResult.Entities["datetime"]?.FirstOrDefault()?["timex"]?.FirstOrDefault()?.ToString().Split('T')[0];
        }
    }
    catch (Exception e)
    {
        logger.LogWarning($"LUIS Exception: {e.Message} Check your LUIS configuration.");
    }

    return bookingDetails;
}
```

**Comment by JonathanFingold** [comment]
For this sample. The dev team decided to use the raw entities from the LUIS result. The article has been updated to detail their approach. I'll track down links to additional information on consuming LUIS entity output and add them to the article.

**Comment by JonathanFingold** [comment]
Adding this to the article. Let me know if additon links to external content would help this article.

For information on how entity information appears in a LUIS result, see [Extract data from utterance text with intents and entities](https://docs.microsoft.com/azure/cognitive-services/luis/luis-concept-data-extraction).

**Comment by JonathanFingold** [comment]
Closing. Please open a new doc issue if you feel there is more we need to do in the docs to explain this pattern. You can also open an issue in the [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet) or [botbuilder-samples](https://github.com/Microsoft/BotBuilder-Samples) repos to request changes to the SDK or the samples, respectively.
