### ISSUE TITLE
Article needs to be updated

### ISSUE THREAD

**Issue by Souvik04** [MicrosoftDocs/bot-docs#875]
The solution explained here is different than what comes with the Bot Framework template and the details mentioned here- https://github.com/Microsoft/BotBuilder-Samples/issues/1080. The new Bot Framework (and its dependent) libraries and the solutions explained over the docs are not in sync for a while. I have experienced several issues recently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6606cce-8a4e-587b-ded2-bd775a4cd7c7
* Version Independent ID: 6f637bca-8cc0-a526-4cbd-9c5f9f94ca2b
* Content: [Create advanced conversation flow using branches and loops - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by DanteNahuel** [comment]
@Souvik04 interesting. So which way is the correct one? The docs are outdated but the examples aren't?

**Comment by JonathanFingold** [comment]
Many of the topics assume you are starting from the VSIX template. However, some explicitly updated how the accessors were registered in Startup.cs. All the topic code worked at the time of writing, and we're trying to keep up with the dev team as it makes changes to the SDK, tools, and templates.

**Comment by JonathanFingold** [comment]
PS. The recommendation for designing .NET bots is changing ASP.NET Core MVC. This will have an impact on the best practice for setting up state for your bots. Once 4.3 is released, we'll work on updating the docs. The dev team will be working on updating the samples, so there will be a little bit of churn until bot are up to date.
