### ISSUE TITLE
"Root Dialog"

### ISSUE THREAD

**Issue by paulio** [MicrosoftDocs/bot-docs#877]
Is this going to become a term in v4, it sounds very v3 like to me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ffdd2ea-8632-8608-b0a5-0f431c7bac83
* Version Independent ID: d36f286a-98ae-7566-4d1c-0f5db523edbc
* Content: [Design and control conversation flow - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-conversation-flow?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-design-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-conversation-flow.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
In general, the How-to/Design/ topics are not version-specific, at least for now.

**Comment by paulio** [comment]
But isn't 'root dialog' a V3 term?

**Comment by JonathanFingold** [comment]
Yes this article hasn't been rewritten yet; however, the main gist should still be relevant. I'll mark it as work we need to do.

**Comment by JonathanFingold** [comment]
Yes this article hasn't been rewritten yet; however, the main gist should still be relevant. I'll mark it as work we need to do.

**Comment by Kaiqb** [comment]
The term "main" or "root" just refers to the first dialog. Internally, we've used both terms for v4.

**Comment by paulio** [comment]
I'm sorry but that is VERY confusing. There isn't a dialog that starts everything. The Bot documentation is not known to be good, this is an example of why people find it difficult to understand. I'm happy that it's evolved over time and that why these old terms creep in but this is now v4, we shouldn't expect this now.
