### ISSUE TITLE
[Enhancement] Add info about UserState/ConversationState and Bot Accessors

### ISSUE THREAD

**Issue by DanteNahuel** [MicrosoftDocs/bot-docs#878]
Hi
I think more docs could be added explaining in depth both BotAccessors.cs and Startup.cs files, as well as stating what shouldn't be modified because it's required by the bot framework to function properly, like UserState and ConversationState objects.

**Comment by Kaiqb** [comment]
The new samples take a different approach to using accessors. You can see it in the [preview branch](https://github.com/Microsoft/BotBuilder-Samples/tree/samples-work-in-progress/samples/csharp_dotnetcore/45.state-management).
