### ISSUE TITLE
Docs are not properly displaying the list items with <see> tag

### ISSUE THREAD

**Issue by leolorenzoluis** [MicrosoftDocs/bot-docs#881]
**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.botframeworkadapter.continueconversationasync?view=botbuilder-dotnet-stable'
2. Scroll down to 'Remarks'
3. See list not displaying its list item it just displays the bullet

**Expected behavior**
Display the list items

**Comment by JonathanFingold** [comment]
Submitting a PR in the botbuilder-dotnet repo to fix this issue. The doc fix should go live shortly after the 4.3 NuGet packages are released.
