### ISSUE TITLE
misspelt Application as applicatin

### ISSUE THREAD

**Issue by sjoerdkersten** [MicrosoftDocs/bot-docs#883]
A middleware component combined with a wrapper class around the QnA Maker and LuisRecognizer SDK classes provides an elegant way to collect a consistent set of events. These consistent events can then be used by the Applicatin Insights tooling along with tools like PowerBI.

In the last sentence the word application is misspelt : "These consistent events can then be used by the " Application insights "tooling along with tools like PowerBi".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7096728b-fccc-a3c1-37a0-91969673afc6
* Version Independent ID: 32c06281-a201-9d5f-9478-5da5b874b156
* Content: [Detailed overview of the Enterprise Bot Template - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-overview-detail?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-overview-detail.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-overview-detail.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by ivorb** [comment]
will be pushed shortly
