### ISSUE TITLE
Misleading article title

### ISSUE THREAD

**Issue by ryanvolum** [MicrosoftDocs/bot-docs#885]
The title should be something like, "Send proactive notifications to users" to be consistent with other titles (e.g. "Send welcome message to users", "Prompt users for input"). As it stands the title sounds like it describes how to receive proactive messages (as if the reader were a client). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc28a40-716e-22bc-8944-15f0a8b0d5c2
* Version Independent ID: 86252b0d-94e2-2ea6-ed17-fc32ae38e6fc
* Content: [Get notification from bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by ivorb** [comment]
fixed in branch, will be published shortly
