### ISSUE TITLE
Automatic Greeting in Javascript on Webchat

### ISSUE THREAD

**Issue by Gariantroll** [MicrosoftDocs/bot-docs#886]
I am having trouble with getting the bot to make an initial greeting when on webchat.  I am using javascript. 

 It works in the Emulator, but I am stuck on getting it to work in the webchat.

Alexis 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a16806-95d6-7c66-3b85-b2ace211f367
* Version Independent ID: c8565ece-392a-fb56-e911-8a5dd5555dee
* Content: [Send welcome message to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DanDev33
* Microsoft Alias: **v-dashel**

**Comment by pekspro** [comment]
I’m having the same problem. It seems that this is a known issue:

https://github.com/Microsoft/BotBuilder-Samples/issues/1125

**Comment by DanDev33** [comment]
The issue you are describing stems from the fact that varying channels consume bot input in differing ways. The emulator has been built to always send an initial message to your user when they are initially connected, but other channels such as webchat will never send a message until the first user input has been received. As bot designers we somehow have to account for both types of channel behavior. This is the reason we added the section: 
https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md#discard-initial-user-input
to the Welcome User article. The suggested solution accounts for both types of behavior by not processing any received user input until you confirm that an initial Welcome message has been received by your user.

Hope this helps and Thanks for your feedback!

**Comment by B7A9F** [comment]
> The issue you are describing stems from the fact that varying channels consume bot input in differing ways. The emulator has been built to always send an initial message to your user when they are initially connected, but other channels such as webchat will never send a message until the first user input has been received. As bot designers we somehow have to account for both types of channel behavior. This is the reason we added the section:
> https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md#discard-initial-user-input
> to the Welcome User article. The suggested solution accounts for both types of behavior by not processing any received user input until you confirm that an initial Welcome message has been received by your user.
> 
> Hope this helps and Thanks for your feedback!

I just tried this solution for js https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md#discard-initial-user-input but it doesn't seem to work.
The welcome message is sent only after the user input,  is this normal?
There is no way for sdk4 to send a welcome message before the user input?
i am on web chat channel and i use "botbuilder": "^4.1.5"
Thank you

**Comment by pekspro** [comment]
I was able to solve this by following this example: https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event

**Comment by Gariantroll** [comment]
> I was able to solve this by following this example: https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event

Hey, it worked, but how do I edit that introduction.  Seems that code is sourced from the Cloud.

Alexis

**Comment by EricDahlvang** [comment]
@Gariantroll That WebChat sample is using MockBot, and the welcome message is from here: https://github.com/compulim/BotFramework-MockBot/blob/master/src/index.ts#L269

**Comment by Gariantroll** [comment]
> @Gariantroll That WebChat sample is using MockBot, and the welcome message is from here: https://github.com/compulim/BotFramework-MockBot/blob/master/src/index.ts#L269

Sorry about the confusion, but I didn't use the example above.  I thought your link was this example https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0 as this is the one I used.  It gives a default Introduction Card and I want to know how to edit it.
