### ISSUE TITLE
Need proper formtting for the bullet point

### ISSUE THREAD

**Issue by pkaushik23** [MicrosoftDocs/bot-docs#889]
For section "How the state property accessor methods work", proper bullet is missing for following
" -The accessor's set method:" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1795c22-9e0f-8a69-a517-ffbe38a2cd30
* Version Independent ID: 9d2c1569-6d6f-97fa-881d-b4a0f61623a2
* Content: [Managing State - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
Fix added to bot-docs-pr [PR 1323](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1323). Should go live next week.
