### ISSUE TITLE
options.State is marked obsolete

### ISSUE THREAD

**Issue by pesetskyps** [MicrosoftDocs/bot-docs#890]
Please change the example to fit v4 approach to state management

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900a193e-96cd-eb18-ca94-a4062517e5e9
* Version Independent ID: c1b6cf03-c236-cfbf-aa4b-96961b816bc3
* Content: [Persist user data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-persist-user-inputs?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-persist-user-inputs.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-persist-user-inputs.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by DanDev33** [comment]
Thank you for your feedback! We are actively working on this right now.
