### ISSUE TITLE
Options.State has been marked as obsolete 

### ISSUE THREAD

**Issue by MCKRUZ** [MicrosoftDocs/bot-docs#892]
options.State.OfType&lt;ConversationState&gt;().FirstOrDefault();

This line indicates that this code has been marked as obsolete in the framework.  It should be removed from the documentation to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf8a24b-7029-247b-3c5c-3902befe0ccf
* Version Independent ID: bcd01444-d332-29e6-2b81-5558bb2d576b
* Content: [How bots work - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-basics.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by DanDev33** [comment]
Thank you for your feedback! We are actively working on this right now.
