### ISSUE TITLE
docs.botframework.com links are dead

### ISSUE THREAD

**Issue by EricDahlvang** [MicrosoftDocs/bot-docs#893]
Many links on this page now redirect to https://docs.microsoft.com/en-us/azure/bot-service

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2698526b-6251-3832-85e6-e6ba41b74909
* Version Independent ID: f2109d38-c3cd-06b3-7c51-fefcf1367fb9
* Content: [Conduct audio calls - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-conduct-audio-calls?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-conduct-audio-calls.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-conduct-audio-calls.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by DanDev33** [comment]
Hi Eric,
Thanks for your feedback. You are correct that currently any link that previously pointed to the v3 SDK documentation currently redirects to https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0  I have asked that we provide a backup version of this documentation and if that becomes available, will correct these and similar links to point to that location instead. I will let you know the outcome of this request.

**Comment by dschuld** [comment]
Hi Eric, any news on this? As I see it, there is currently no documentation of any SDK online (neither v3 nor v4), which basically makes the SDK useless?!

**Comment by dkbhadeshiya** [comment]
Hi any updates on this? 
We are struggling to find the SDK references to v3.

**Comment by DanDev33** [comment]
Thanks Eric!
I came on here to let you know these were now available and you just pointed out their availability!
Thanks for your feedback.  Closing this now as a resolved issue.
