### ISSUE TITLE
Create Project

### ISSUE THREAD

**Issue by iTzanetos** [MicrosoftDocs/bot-docs#894]
Hello, Bot Framework Echo Bot V4 template is under Cloud-&gt;AzureBotService on creating a new project.
In the section Create Bot above it's under Bot Framework. Minor issue but it's a little confusing because v4 templates I installed in the past still show under Bot Framework. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Framework SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by martinkearn** [comment]
This is a significant point of friction for beginners. There are several templates and it is not clear which one to use for s simple new bot project.

**Comment by JonathanFingold** [comment]
The 4.3 update of the SDK is coming soon, with changes to the templates. Once that is released, we'll review these topics and align them with the correct template names and template code.

**Comment by JonathanFingold** [comment]
Updated the current screen shot for 4.2.2. Leaving open until the 4.3 release work is started.

**Comment by Kaiqb** [comment]
This is fixed for VS templates. The updates will go out at the beginning of May.
