### ISSUE TITLE
Specify the app setting to change for the bot filename

### ISSUE THREAD

**Issue by brandonh-msft** [MicrosoftDocs/bot-docs#896]
We call out the exact app setting to change for the bot secret, but don't actually tell users what app setting to change for the filename (step 5 under update app settings in azure)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0#1-prepare-for-deployment)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
We are moving away from the .bot file approach, and this topics has been updated to use appsettings.json or .env file.
