### ISSUE TITLE
'using Microsoft.Bot.Builder.Core.Extensions;' should not be in sample

### ISSUE THREAD

**Issue by AndyCW** [MicrosoftDocs/bot-docs#897]
The sample shows the using statement for Microsoft.Bot.Builder.Core.Extensions. This is obsolete and not used by the linked sample. If you try to add it to your code, the only match is for an alpha pre-release NuGet package that if added, breaks compilation of your app.
Remove this using statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53446ad1-6b8c-1ccb-6e78-2cb14358b1c3
* Version Independent ID: 8b0fcc34-e624-64a9-adc8-6c8fa3031f54
* Content: [Use button for input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-suggested-actions?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-add-suggested-actions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-suggested-actions.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
This article and the rich media article will be rewritten after the 4.3 release. I'll do a sanity check and fix snippets in these two topics.

**Comment by JonathanFingold** [comment]
Fix is in PR and should go live next week.
