### ISSUE TITLE
No RepromptDialogAsync docs

### ISSUE THREAD

**Issue by DanteNahuel** [MicrosoftDocs/bot-docs#898]
Hi!
I found there's a RepromptDialogAsync() method, but I can't find any docs about it or how to use it correctly.
Could this be added to the docs?

Best regards

**Comment by JonathanFingold** [comment]
We don't yet have documentation on how to derive from the abstract `Dialog` base class and is currently outside the scope of the documentation. However, the reprompt functionality is built into the prompt classes.

Sample 19 ([C#](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/19.custom-dialogs/Dialogs/SlotFillingDialog.cs)) shows one way to implement a custom dialog. It doesn't override `RepromptDialogAsync` (the custom dialog uses prompts to fill "slots"). However, this should give you the gist.

If you want to dive deeper, you can look at how this is implement for prompts: [Prompt.RepromptDialogAsync](https://github.com/Microsoft/botbuilder-dotnet/blob/398ec3a235fd49a3295719b7d1ce07a6f5fe046d/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs#L124-L129) and how a concrete prompt implements `OnPromptAsync`, such as [NumberPrompt.OnPromptAsync](https://github.com/Microsoft/botbuilder-dotnet/blob/398ec3a235fd49a3295719b7d1ce07a6f5fe046d/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberPrompt.cs#L25-L45)
