### ISSUE TITLE
'Update App Settings in Azure' intro sentance makes no sense

### ISSUE THREAD

**Issue by martinkearn** [MicrosoftDocs/bot-docs#899]
This sentence makes no sense at all:

"The local bot does not use an encrypted .bot file, but the Azure portal has an that you are deploying doesn't"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Thanks for your feedback! You'll see the corrected sentence the next time this article is published.
ps. This sentence was quite a jumble!
