### ISSUE TITLE
Shouldn't the bot file get re-encrypted before it gets added to the repository?

### ISSUE THREAD

**Issue by martinkearn** [MicrosoftDocs/bot-docs#900]
The steps are to `Decrypt the .bot file` then `Update your local .bot file` and then `Setup a repository
`.

It seems like we're missing a step to re-encrypt the bot file using https://github.com/Microsoft/botbuilder-tools/blob/master/packages/MSBot/docs/bot-file-encryption.md#encrypt-a-bot-file

Without this step, the secrets contained within the .BOT file are openly visible, which is especially bad if you're working on a public repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
One option is to use the **msbot** CLI to [re-encrypt the .bot file](https://github.com/Microsoft/botbuilder-tools/blob/master/packages/MSBot/docs/bot-file-encryption.md). In the next few weeks, we're adding links to [Key Vault](https://azure.microsoft.com/en-us/services/key-vault/).

**Comment by martinkearn** [comment]
The issue was more that the document does not call out that you should re-encrypt the file. If you follow the doc exactly, the .bot file remains decrypted and open. You can see my other issue ([902](https://github.com/MicrosoftDocs/bot-docs/issues/902)) for a more in-depth opinion on how I'd revise this doc to be easier, less steps and more secure.
