### ISSUE TITLE
Prompt attachment Dialog

### ISSUE THREAD

**Issue by Diro92** [MicrosoftDocs/bot-docs#901]
There is a way to prompt an attachment Dialog to gather file from user's pc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d405d76-b17a-dbe9-c2f2-734fa34b0e8b
* Version Independent ID: 3acc3fa8-b98d-a5f1-8bea-e823c3efec14
* Content: [Dialogs within the Bot Framework SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-concept-dialog.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-dialog.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @johnataylor
* Microsoft Alias: **johtaylo**

**Comment by JonathanFingold** [comment]
There's an `AttachmentPrompt` class for this. It's described briefly in the [prompt types](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-dialog#prompt-types) section of this article. However, it is up to the channel as to how it handles attachments as input from the user.

The **handling attachments** sample ([C#](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/15.handling-attachments), [JavaScript](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/15.handling-attachments)) shows a couple more ways to handle both sending and receiving attachments.

Please reopen this if you think we should have a separate how-to article about this.
