### ISSUE TITLE
A better approach is to change your local project to use the BOT file from Azure

### ISSUE THREAD

**Issue by martinkearn** [MicrosoftDocs/bot-docs#902]
The process for this doc is summarised as follows:
1) Create local bot project
2) Create Azure Bot Service
3) Get .BOT file from Build > Download Source Code in the Azure Bot Service
4) Decrypt .BOT file from Azure Bot Service
4) Copy and paste details from Azure Bot Service to the .BOT file you already have in your local bot project
5) Commit your new local decrypted .BOT file to source control (So we now have the .BOT file which contains secrets in clear text in source control?)
6) Publish your local project with the decrypted .BOT file
7) Remove the bot secret from your Azure App service as it is no longer needed to decrypt the .BOT file

A better, simpler and more secure approach is as follows:
1) Create local bot project
2) Create Azure Bot Service
3) Get .BOT file from Build > Download Source Code in the Azure Bot Service
(the same as the document so far, but here's where it changes)
4) Change your local project to use the .BOT file from the Azure Bot service by editing `AppSettings.json` or `.env`
5) Publish your local project with the encrypted .BOT file and keep the .BOT Application Settings intact and secure

This approach has been documented (based on updates to the existing MD file) here: https://github.com/martinkearn/Content/blob/master/Docs/bot-builder-deploy-az-cli.md

This approach is easier, does not require the .BOT file to be touched and keeps the .BOT encrypted. It also avoids the need to change any Azure Application Settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
The recommended deployment process is changing in the 4.3 release, and this article will be revised at that time. We will be moving away from using .bot files.

**Comment by martinkearn** [comment]
I think there would still be value in updating this article to reflect these suggested steps until the 4.3 release gets published. Developers are using this doc right now and it is leading them down a bad path.

**Comment by JonathanFingold** [comment]
Notes on how to re-encrypt the .bot are in PR and should go live next week. Note that we have them decrypt the .bot file to include any additional service information they need for the bot they developed locally.
