### ISSUE TITLE
Incorrect json property for knowledge base id

### ISSUE THREAD

**Issue by brandonh-msft** [MicrosoftDocs/bot-docs#903]
The doc says to use `kbId` but the json schema requires `KbId` (note capitalization)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
We were finding that the KbId wasn't working when implementing the sample, but kbId did. I'll look into it.

**Comment by ivorb** [comment]
Everything I can find points to kbId being the correct casing - both in testing of bots that use QnA, and in the QnAMaker API docs (for example, see the [delete API docs](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/knowledgebases_delete) and look at the casing in "Request Parameters"). If you're finding that "kbId" doesn't work, please do let us know.

**Comment by brandonh-msft** [comment]
@ikivanc, @msolhab do you recall specifics here? Any concrete Postman examples you could share that fail, prehaps?
