### ISSUE TITLE
Does not advise developer to add required NuGet package needed for code to compile

### ISSUE THREAD

**Issue by AndyCW** [MicrosoftDocs/bot-docs#905]
In the C# examples, code for the BotServices.cs file is shown. A developer new to using QnA Maker tries to follow these instructions is blocked because this article does not instruct them to add the Microsoft.Bot.Builder.AI.QnA NuGet package or the required 'using' statements needed to resolve references to objects in the code such as QnAMaker.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by VergilPrime** [comment]
I had to work around that by comparing the nuget packages in the examples with the ones in my bot downloaded from Azure Portal. It is definitely an oversight.

**Comment by JonathanFingold** [comment]
The samples are being rewritten for the 4.3 release. In the mean time, I'll call out the NuGet packages and namespaces needed if you are adding LUIS to a new bot.

**Comment by JonathanFingold** [comment]
Fix to the immediate issue is in PR and should go live next week.
