### ISSUE TITLE
BotServices.cs sample code not the same as that in the linked sample

### ISSUE THREAD

**Issue by AndyCW** [MicrosoftDocs/bot-docs#906]
There is no way to successfully get the code snippet for BotServices.cs in this article to compile because it calls the BotServices constructor which is not shown in the code snippet. If you refer to the linked sample code to try to figure this out, the implementation of BotServices.cs in the sample is difference from that shown in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
The samples are in the process of being updated for the 4.3 release. We'll update this topic once the corresponding code is available.

**Comment by Kaiqb** [comment]
The link to sample code is in the Pre-requisites section. We provide both C# and JS samples that you can download and use. The code in the article only show relevant pieces and that is why you are not able to run it. Hope that helps.
