### ISSUE TITLE
Inconsistency in the guidance docs

### ISSUE THREAD

**Issue by angie4u** [MicrosoftDocs/bot-docs#908]
The documentation start to creat account using "free plan" but suddenly changes to use "developer plan" (Screenshot). It might be not a big deal, but it can confuse a developer especially who use this first time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1543d25b-03af-18e1-4321-14ec5aa90874
* Version Independent ID: 1e033bb5-cf72-b189-92b2-c74ddab2e8c6
* Content: [Connect a bot to LINE - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-line?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-line.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-line.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
This has already been fixed. Thanks for reporting!
