### ISSUE TITLE
A quick thumbnail page for all the various card types would enable quick decision-making during conversational UI design

### ISSUE THREAD

**Issue by brandonh-msft** [MicrosoftDocs/bot-docs#910]
At present, the Bot Framework documentation doesn't provide a good set of visual representations of the various prompts and rich conversational UI options available to designers and developers. Instead users see the code to implement some of these message types, but are left to write and entire bot using the code in order to see what it actually looks like. It would be useful to both designers & developers alike to have a quick visual "gallery" showing the various message/prompt/button layouts in order to quickly discern the best approach for their conversation. These screenshots/representations could be shown using the Emulator's output at a minimum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 607856cb-baae-c401-5b34-876b5018771d
* Version Independent ID: 77df1de7-7b2e-a546-1280-a66121039a94
* Content: [Add media to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp#send-a-carousel-of-cards)
* Content Source: [articles/v4sdk/bot-builder-howto-add-media-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-media-attachments.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
The first link in the article directs to [Design the user experience](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-user-experience.md), which contains a set of thumbnails. Is that article incomplete, or are you looking for something else?

**Comment by brandonh-msft** [comment]
Good call. in the OpenHack the customer expressed a desire for this while they were looking through dialogs, prompts, etc and never arrived at that link. Perhaps it should be closer to the code? Many people click the link on the left that sounds like what they want, then the links on the right to jump to the subtopic of interest.

cc @DariuszPorowski

**Comment by JonathanFingold** [comment]
Ok. I'll try to make it more visible, and repeat the link in key places.

**Comment by JonathanFingold** [comment]
A fix is in PR and should go live next week.
