### ISSUE TITLE
"getAnswers" vs. "generateAnswer"

### ISSUE THREAD

**Issue by SarahSexton** [MicrosoftDocs/bot-docs#911]
The keyword "getAnswers" does not compile; it must instead be "generateAnswer" currently. This may be because the samples are in the process of being updated for the 4.3 release. Current documentation claims "generateAnswer" is deprecated, but it is still the only way that works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
Ugh, yes. `getAnswers` seems to be the new method that will go live with 4.3.

I'll add code comments to the snippets to clarify which calls to use for which version of the SDK.

**Comment by JonathanFingold** [comment]
I temporarily reverted this edit. The fix is in PR and should go live next week.
