### ISSUE TITLE
Misleading placeholder variable name: <BOT_FILE_NAME>

### ISSUE THREAD

**Issue by SarahSexton** [MicrosoftDocs/bot-docs#912]
It is misleading to document "QNA_CONFIGURATION = '&lt;BOT_FILE_NAME&gt;'; " as a placeholder variable, because the name actually being asked for is "qnamakerService", not their .bot file name. The user is most likely to enter the name of their .bot file in this place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=js)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Hi Sarah,
I see your point. I'll change this to something like <SERVICE_NAME_FROM_.BOT_FILE> to make it more clear. You'll see this change live the next time the updated doc file is merged.
Thanks for helping us improve our Docs!
