### ISSUE TITLE
There is a duplicate command in the documenation

### ISSUE THREAD

**Issue by jasondown** [MicrosoftDocs/bot-docs#913]
In the "Install the LUISGen tool" section, the shell command is shown twice in the documentation.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-ca/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0#prerequisites)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by Kaiqb** [comment]
This topic was removed.
