### ISSUE TITLE
Bot Handoff agent monitoring before conversation transfer c# sample

### ISSUE THREAD

**Issue by vishnu2017** [MicrosoftDocs/bot-docs#914]
I am working on a scenario where, I have implemented the Bot handoff to a human using C#.
I have watch, accept and reject etc., as built in commands.

I wanted a option where the agent just monitors the conversation before getting into a real conversation with a end user.

I don't see this functionality implemented in C# sample of the handoff, correct me if I am wrong.

Any ETA for this feature?

Is this already implemented in node.js sample?

**Comment by Kaiqb** [comment]
It's not in our plans, but you can reach out to support staff on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework).

**Comment by hshahbaz** [comment]
@vishnu2017 where did you get the  C# sample of the handoff? Is your bot capable of separating the human conversations if multiple of them are happening at the same time?

Can you guide me to this sample as I am working on one bot which has LUIS andQnA Maker and bot to human handoff.
