### ISSUE TITLE
Full SourceCode is not available.

### ISSUE THREAD

**Issue by snsrkrishna** [MicrosoftDocs/bot-docs#915]
Full sourcecode for this article is not available. It is little confusing here. I would be good if you can help with full code.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9577ff-cf56-e5de-84c3-bfe10aab5368
* Version Independent ID: b5d62753-f87b-4673-b09b-a5a3fd9360e8
* Content: [Reuse dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-compositcontrol.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-compositcontrol.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
The team is in the process or rewriting the samples. Once the sample for component dialogs has been update, I'll update this article and link to the sample code.

**Comment by snsrkrishna** [comment]
@JonathanFingold Thank you.

**Comment by MarekLani** [comment]
In the meantime I have put together working sample for component dialogs based on over stated bits: https://github.com/MarekLani/BotFrameworkV4ComponentDialogsSample

**Comment by ranjsund** [comment]
Hi,

Please update if the node js source code for the sample stated above is available to download.
Few questions:
In saveResult(), we are getting the values for table and alarm from step like 
step.result.table
step.result.alarm
Where have we set these values in step context in their respective dialog?

TIA

**Comment by MarekLani** [comment]
@ranjsund sorry for delayed response, I've put together only C# code

**Comment by JonathanFingold** [comment]
The samples and how-to articles have been updated. (This article now discusses the 05 sample from the samples repo.)
