### ISSUE TITLE
Word Mistake

### ISSUE THREAD

**Issue by juanfergc** [MicrosoftDocs/bot-docs#917]
These predifined buckets are scoped to a certain visibility, depending on the bucket:
Should be:
These predefined buckets are scoped to a certain visibility, depending on the bucket:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1795c22-9e0f-8a69-a517-ffbe38a2cd30
* Version Independent ID: 9d2c1569-6d6f-97fa-881d-b4a0f61623a2
* Content: [Managing State - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/bot-builder-concept-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-state.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
Fixed and will be live shortly. thanks!
