### ISSUE TITLE
Bot Channel Registration  

### ISSUE THREAD

**Issue by isathish** [MicrosoftDocs/bot-docs#919]
How to Bot channel registration using CLI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Service: **bot-service**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by Kaiqb** [comment]
The content referenced here no longer exists in docs.
