### ISSUE TITLE
How to select the bot framework template 

### ISSUE THREAD

**Issue by isathish** [MicrosoftDocs/bot-docs#920]
Hi Using Azure CLI I can create the bot and I need to select the bot framework template from my visual studio online repo. while creating the bot need to bring the template based on my bot framework template    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eac19e28-e37b-1496-4758-1b1638c311db
* Version Independent ID: 10df3cfc-fcec-411b-5d6d-796883bfb773
* Content: [Create bots with Azure CLi - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tools-az-cli?view=azure-bot-service-3.0)
* Content Source: [articles/bot-builder-tools-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tools-az-cli.md)
* Service: **bot-service**
* GitHub Login: @matthewshim-ms
* Microsoft Alias: **v-shimma**

**Comment by ivorb** [comment]
Hi @isathish it looks like what you're trying to do isn't something we normally do - the AZ CLI doesn't allow us to specify a template besides the basic template it uses during `az bot create`. If that standard template isn't what you need, you can create the bot through Visual Studio, and use the desired template, or through the [Azure Portal](https://ms.portal.azure.com/)
