### ISSUE TITLE
Where do I edit introduction Card in the Direct Line Token for Web chat?

### ISSUE THREAD

**Issue by Gariantroll** [MicrosoftDocs/bot-docs#922]
Can you point me where I can edit the introduction card on Direct Line Token? I can't seem to find it in my code.  Is this by any chance the default introduction and I have to override it somehow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a95d02-732d-3324-37ce-d2c1a41131e0
* Version Independent ID: bc0366f3-8714-e758-ff02-07837a7751d0
* Content: [Connect a bot to the Web Chat channel - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-webchat.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-webchat.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@Gariantroll I'm not sure I fully understand your question. If you're asking about how to generate a welcome message to the user, that happens in the bot code, as opposed to the Web Chat client code.

See how to [send a welcome message to users](https://docs.microsoft.com/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0)

**Comment by JonathanFingold** [comment]
Please reopen if you still have questions.
