### ISSUE TITLE
Cascading case 

### ISSUE THREAD

**Issue by Diro92** [MicrosoftDocs/bot-docs#923]
There is a way to make a Cascading case changing the parameters within the turncontext.?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79129724-5f90-ac8d-6918-d5801a4e2001
* Version Independent ID: 08e19b7b-2ec6-95da-2f5a-d534e761f5da
* Content: [Create your own prompts to gather user input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-primitive-prompts?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-primitive-prompts.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-primitive-prompts.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
@Diro92, What is the scenario you are trying to address?
- You can cascade within a switch statement using the [goto keyword](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/goto#example)?
- You can change some of the properties of the activity in the current turn context, such as its Text property.

**Comment by JonathanFingold** [comment]
@Diro92 Please reopen this issue with more information if your problem still exists.

**Comment by Diro92** [comment]
When passing the turncontext parametre through the methods it keeps the same values in the process.
The question is how to change the values that turncontext as an object has in any point.
For example: 
turncontext.activity.text is something that remains the same. I have been able to manipulate this value.
