### ISSUE TITLE
"Update the .bot file" section is missing production section

### ISSUE THREAD

**Issue by seaen** [MicrosoftDocs/bot-docs#924]
"Update the .bot file" section only contains endpoint=development, and does not work (500 Internal Server error) when deployed to production.  There needs to be a similar section for endpoint=production.

Other documents probably need to be updated as well across other examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2963321c-6720-be8f-aba6-225960eba1b3
* Version Independent ID: bff968a7-33a8-bc53-b08b-6c17d672c3cd
* Content: [Use QnA Maker to answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-qna.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment]
Starting with SDK 4.3 release, we are moving away from the .bot file approach to manage resources. We recommend that you either use appsettings.json or .env file. For information, refer to [manage bot resources](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp) and [deployment](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp) topics.
