### ISSUE TITLE
How the data is stored

### ISSUE THREAD

**Issue by krajniak** [MicrosoftDocs/bot-docs#925]
Since the attachments are stored somewhere in cloud in area in which nor user, nor but have governance of. It would be good to know, how where and for how long the data is stored. And also, if there is a possiblity to request deletion of the data. Especially in the era of GDPR rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e4dd44-9bfc-14b1-cfd4-d37d500b1877
* Version Independent ID: 965c2c94-8cf1-fbf0-c321-547a90449382
* Content: [Send an activity the bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-send-activity?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-send-activity.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-send-activity.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
For bots that were built using SDK v3, take a look at the [GDPR blog](https://blog.botframework.com/2018/04/23/general-data-protection-regulation-gdpr/). In SDK v4, we don't store user data.

**Comment by krajniak** [comment]
I disagree. When you send an attachment, from front end, the url to the attachment is generated by directline channel or not framework. On the backend I do not received binaries. Only the url. Ergo attachments are stored somewhere since I can download them

**Comment by aschemel** [comment]
Hi! @krajniak did you get more info on this? I have the same doubt, where are the attachments stored? 

@kaiqb any more comments on this??  Thanks!

**Comment by krajniak** [comment]
Nope

czw., 25 kwi 2019 o 11:13 aschemel <notifications@github.com> napisał(a):

**Comment by JonathanFingold** [comment]
The [Bot Framwork Activity](https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md) spec describes how attachments are represented in an activity object, either embedded or as a link to uploaded content. For uploaded content, it's up to the channel how to manage this resource. It's a separate issue what the bot does with the content once it has received it. Does that answer your questions?

**Comment by krajniak** [comment]
Not really. I'm talking about DirectLine channel. When you upload the attachment in the webchat component, directline itself saves the attachment somewhere in the cloud. Bot backend only receive a link to uploaded file.
Since the functionality is used in GDPR ready countries we need to know where DirectLine stores these attachments and if we have any control over deleting them

**Comment by JonathanFingold** [comment]
Thanks for the clarification. I've flagged this for our support team.

**Comment by CoHealer** [comment]
Re-applying support label for aggregation inclusion

**Comment by dmvtech** [comment]
Hi @krajniak 

Attachments for Direct Line are stored encrypted on Microsoft servers. The size limit currently is 20MB and the contents will be available for 24 hours. 

I don't know about being able to request them to be deleted. Off the top of my head, I don't believe so. @dandriscoll @EricDahlvang any ideas on that part?

**Comment by CoHealer** [comment]
Resolving as answered. If dmvtech's answer does not suffice please reopen.
