### ISSUE TITLE
Download Bot source code 

### ISSUE THREAD

**Issue by AlexanderTodorovic** [MicrosoftDocs/bot-docs#927]
Dear All, when I download the Bot source code I don't get an option to include settings (containing the keys and secrets). Also the files appsettings.json and .env do not exists. Can you please check this? Thanks, Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9e2e6-b901-9e27-d070-701922396a4c
* Version Independent ID: c29a68b2-886d-2cec-0ce7-c49c586d7ea8
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by DanDev33** [comment]
Hi Alexander,
I followed the quickstart steps:
1. opened my Azure portal
2. created a v4 C# Web App Bot - EchoBot
3. Tested it in Web Chat
4. Clicked Build, Download Bot Source Code... and this dialog appeared

![bot-build-download](https://user-images.githubusercontent.com/40217323/55115778-923e6f00-50a2-11e9-85ad-0882d34067a1.png)

I finished creating & downloaded the zip file. This contains a populated appsettings.json file.
Please follow these steps and see if it resolves your problem.
