### ISSUE TITLE
Code snippets with associated GitHub samples should link out directly to the samples

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/bot-docs#929]
**Describe the bug**

Currently, it is difficult to go between the docs and the samples and find which code snippets correspond to which parts of the samples. This also leads to doc snippets getting outdated and not matching the samples.

**To Reproduce**

For example, [in this guide](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=js), there's no indication on how to get to the code samples on GitHub. 

After going through the guide a few times, then you'll find a reference hidden in the `Test the Bot` section: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=js#test-the-bot

**Expected behavior**

any code snippets with associated GitHub samples should link out directly to the samples.

**Comment by ivorb** [comment]
If you look at the Prerequisite section, one of the items there mentions and points directly to the sample code used. This is consistent across all of our articles that refer to a sample.

If you feel that is not sufficient, please open a different issue explaining how you feel that would be improved.
