### ISSUE TITLE
Dispatch link

### ISSUE THREAD

**Issue by AlexanderTodorovic** [MicrosoftDocs/bot-docs#930]
Hi All, the Dispatch link (https://github.com/Microsoft/botbuilder-tools/tree/master/Dispatch) does not work. Thx, Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba8cc826-fa2f-5521-ead7-b771ad527269
* Version Independent ID: 91bc6ab6-e909-e8da-74aa-4a178559c290
* Content: [Manage resources with a .bot file - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-file-basics.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-file-basics.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Hi Alex,

Please try this link:  https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Dispatch
I will update this article to use this corrected link. Thanks for helping keep our documentation up to date!
