### ISSUE TITLE
FOLKS YOU DID NOT CREATE A SIMILAR PAGE LIKE THIS IN V4!! THERE IS NON!> YOU HAV ENOTHING REGARDING CAROUSELS IN V4 DOCUNEBTATION 

### ISSUE THREAD

**Issue by soniaang** [MicrosoftDocs/bot-docs#935]
This  PAGEE was NOT ported to VERSION 4 documentation ! 

NO Carousels  etc!  It cannot be found!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed5a1c8d-c61b-4130-1ecb-e25d7b8cc4ad
* Version Independent ID: ba796614-7173-b45f-f9eb-6a3c3fe55b09
* Content: [Add rich card attachments to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-rich-cards?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/nodejs/bot-builder-nodejs-send-rich-cards.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-send-rich-cards.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by JonathanFingold** [comment]
We changed how sections of the documentation are organized between v3 and v4, which means some of the v3 topics don't have an exact match in the v4 doc set.

For information on carousels and rich media in general, see [Add media to messages](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-add-media-attachments), specifically the [send a carousel of cards](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-add-media-attachments#send-a-carousel-of-cards) section.
