### ISSUE TITLE
How to register a new facebook page using C# (api code) ?

### ISSUE THREAD

**Issue by cosmaioan** [MicrosoftDocs/bot-docs#937]
client.Channels.Create("bots", "bot123", Microsoft.Azure.Management.BotService.Models.ChannelName.FacebookChannel,
                new Microsoft.Azure.Management.BotService.Models.BotChannel()
            { 
??????
            }
                );

The management library has no example or guidance how to add a new page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acb1736e-f822-2374-fc91-60a13567966e
* Version Independent ID: 03a952ae-0752-9aeb-a214-981bbfaf3b91
* Content: [Connect a bot to Facebook Messenger - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-facebook.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-facebook.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **RobStand**

**Comment by Kaiqb** [comment]
We don't have code examples in the docs, but you can reach out to support staff for help on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework).
