### ISSUE TITLE
repo in azure pipeline not Kudu

### ISSUE THREAD

**Issue by cxputcm** [MicrosoftDocs/bot-docs#938]
why is so difficult to publish a bot to azure. I have a bot repo in AzureDevops but I dont want to republish via Kudu or set up a new repo anywhere! .. should I just update the appsetting.json with the botfilesecret in devops directly and then enable continuous deployment ? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-gb/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
Updates are coming to the deployment story soon, so stay tuned!

**Comment by Kaiqb** [comment]
You don't have to use Kudu. This topic talks about using azure pipeline: https://docs.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment, which should also work.

**Comment by ivorb** [comment]
The deploy article was recently updated, and the continuous deployment topic linked above should solve your issue. If not, please open a new issue based on the new content. Thanks!
