### ISSUE TITLE
Link Not Working

### ISSUE THREAD

**Issue by AzureMSBotUser** [MicrosoftDocs/bot-docs#940]
The left had Nav  "Azure Bot Service Documentation" &gt; "Reference" &gt; "Node.js SDK v3"  hyperlink has the address "https://docs.botframework.com/en-us/node/builder/chat-reference/modules/_botbuilder_d_.html" but when you click on it , it takes you to Azure Bot Service for v4.. What happened to the documentation for Node.js SDKv3??? please fix it!!!! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06eee0a7-4c80-ddae-9024-7e6dec0a789d
* Version Independent ID: 768d536b-024a-3892-abf0-ab6008a376ea
* Content: [Bot Framework SDK for Node.js - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-overview?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/nodejs/bot-builder-nodejs-overview.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-overview.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by DanDev33** [comment]
Thanks for your feedback. We became aware that the V3 documentation was no longer in place and have an outstanding request to restore this information online. The team responsible for creating this build has acknowledged the issue and is working to restore the data. These links should once again work properly once the underlying documentation has been restored.
