### ISSUE TITLE
C# Code- Bot class is missing

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/bot-docs#941]
There is a class for `IStorageItem`, but its look like the `OnTurnAsync` is part of the `IStorageItem`, but I think it not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8f39f5-1a91-6fdb-3cc0-124b282e9806
* Version Independent ID: 701f9b3c-a893-dee1-d012-760e6f870ec4
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by JonathanFingold** [comment]
@baruchiro , in the first code snippet `public class UtteranceLog : IStoreItem` declares an inner class within the `MyBot` class. An updated topic is in the works, and will go live in a few weeks.

**Comment by JonathanFingold** [comment]
The samples and how-to articles have been updated. Let us know if the new article is still confusing.
