### ISSUE TITLE
blob storage - where to getstorage name and container name

### ISSUE THREAD

**Issue by Wendy-YongAiJing** [MicrosoftDocs/bot-docs#942]
// Storage configuration name or ID from the .bot file.
const string StorageConfigurationId = "&lt;STORAGE-NAME-OR-ID-FROM-BOT-FILE&gt;";

// Default container name.
const string DefaultBotContainer = "&lt;DEFAULT-CONTAINER&gt;";

For the code above, is it id from .bot file = subscriptionId?
&
is container name neccessary to be filled? coz for my case, I think I didn't create any container

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8f39f5-1a91-6fdb-3cc0-124b282e9806
* Version Independent ID: 701f9b3c-a893-dee1-d012-760e6f870ec4
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by DanDev33** [comment]
Hi Wendy,
Sorry your question sat for so long. This article will have changed quite a bit once our new documentation is updated. The new blob storage definition to connect to Azure Blob store looks like this:

private static readonly AzureBlobStorage _myStorage = new AzureBlobStorage("<your-blob-storage-account-string>", "<your-blobstorage-container-name>");

Where "your-blob-storage-account-string" comes from Settings, Access keys, key1.Connection string
and "your-blobstorage-container-name" is a name you create for your blob container. I've attached an image showing how you create a new container.

1. Open your Blob storage up using the Storage Explorer (preview).
2. Right click on "Blob Containers" and select "create blob container"
3. Name your new container and use this name for "your-blobstorage-container-name"

I hope this helps you out.

![create-blob-container](https://user-images.githubusercontent.com/40217323/55439969-05d8f400-555b-11e9-9f8e-60afbf0aa542.png)
