### ISSUE TITLE
VSIX Link still points to 4.2.2

### ISSUE THREAD

**Issue by martinkearn** [MicrosoftDocs/bot-docs#944]
The Prerequisites section says that you must install the Bot Framework SDK v4 template for C# from https://aka.ms/bot-vsix but that page still has the 4.2.2 template.

I got here by reading the https://azure.microsoft.com/en-us/blog/conversational-ai-updates-for-march-2019/ article which talks about the 4.3 release so I'd expect that the page would point to 4.3 templates.

Right now I don't know how to create a new 4.3 project.

Same applies to every page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1718fa-0745-3fee-6ef5-18e36b61fabf
* Version Independent ID: fd9ef97f-4540-e624-d459-c076e94a50ad
* Content: [Create a bot with the Bot Framework SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by DanDev33** [comment]
Hi Martin,
Thanks for your feedback. There a VSIX for version 4.3.x that is currently under development. When available, this will create a newer version of what you currently see under samples 02.a.echo-bot. It will be referenced in our upcoming document update and released as soon as it's available. Thanks for helping us keep our docs up to date.
