### ISSUE TITLE
Same token is used by multiple users

### ISSUE THREAD

**Issue by PheakOmi** [MicrosoftDocs/bot-docs#945]
When many users login they all are shared with the same token which created by the first user who logged in.
I want to get different tokens from different users who have logged in. 
Below is the snippet how I handle token after user has logged in:

async loginResults(step) {
    let tokenResponse = step.result;
    if (tokenResponse != null) {
      await step.context.sendActivity(Language[lang].loggedInSuccess);
      token = tokenResponse.token;
      // store token to call MS Graph API
      return await step.endDialog();
      // return await step.prompt(CONFIRM_PROMPT, 'Do you want to view your token?', ['yes', 'no']);
    }

    // Something went wrong, inform the user they were not logged in
    await step.context.sendActivity(Language[lang].loggedInFail);
    return await step.endDialog();
  }

Any suggestions is appreciated. Thanks beforehand!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by 01** [comment]
No sure if you are still looking for answer. But without the rest of your code unable to determine issue. Most likely you are calling  the authentication dialog within the same dialog context. In other words while you may be sending messages from what you perceive as different users. Try outputting the Turn Context as see if its indeed different "from" and recipient ids.

{ type: 'conversationUpdate',
  id: 'x',
  timestamp: 2019-03-19T20:56:35.274Z,
  serviceUrl: 'https://directline.botframework.com/',
  channelId: 'directline',
  from: { id: 'X', role: 'user' },
  conversation: { id: 'X' },
  recipient: { id: 'XXXXXX', name: 'XXXX' },
  membersAdded: [ { id: 'XXXXX' } ] }

**Comment by DanDev33** [comment]
I like Andrew's suggestion above. I've cut and pasted a bit of code that I've used to separate users based on turnContext during their initial connection. 

// This is call whenever a user is initially connected to your app.
if (turnContext.Activity.Type == ActivityTypes.ConversationUpdate)
{
    if (turnContext.Activity.MembersAdded != null)
    {
         // Iterate over all new members added to the conversation
         foreach (var member in turnContext.Activity.MembersAdded)
         {
               // turnContext.Activity.MembersAdded == turnContext.Activity.Recipient.Id indicates the
               // bot not a user, was added to the conversation - ignore that connection.
                if (member.Id != turnContext.Activity.Recipient.Id)
                {
                    // This is a newly connected user.
                    >> Do what you want to have happen once per connected user <<
                }
           }
      }
}

BTW. V4.3.x SDK has a new call: OnMembersAddedAsync( ) that essentially follows exactly this same logic.
