### ISSUE TITLE
What is the "dialog control"?

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/bot-docs#948]
> the `dialog control` library allows you to modularized your conversational flow logic

I can't find the `dialog control` library. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ffdd2ea-8632-8608-b0a5-0f431c7bac83
* Version Independent ID: d36f286a-98ae-7566-4d1c-0f5db523edbc
* Content: [Design and control conversation flow - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-conversation-flow?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-design-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-conversation-flow.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by DanDev33** [comment]
Hi Baruch,
I believe this sentence was trying to say the `dialog` library, as opposed to `dialog control` library
You can find more details on the various dialog types that are supported here:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs?view=botbuilder-dotnet-stable
