### ISSUE TITLE
This article does not work as one would expect: Please review and care to update 

### ISSUE THREAD

**Issue by xtianus79** [MicrosoftDocs/bot-docs#949]
This article, and I may be wrong in my thinking so please advise, makes you think that you can setup a luis.ai app via the reminders.json import and then setup the .bot file with the parameters from the LuisBot app and test it through the Bot Emulator framework.  

When loading the emulator one gets errors when entering any information.  Errors listen below.  

off the cuff I have 2 questions. 1. what or how should we enter in the endpoint.  that is totally not clear. 2. What is the ngrok thing and do we need to use this.  

Some guidance and concept understanding is needed in this article. thanks 

``` 
18:26:54]POST201directline.startConversation
[18:26:54]Emulator listening on http://localhost:54689
[18:26:54]ngrok listening on http://localhost:54689
[18:26:54]ngrok traffic inspector:
[18:26:54]Will bypass ngrok for local addresses
[18:27:02]-&gt;messagehello
[18:27:03]POST400dire

```

here is the full response from the json 

```
{
  "channelData": {
    "clientActivityID": "15528616220280.j6qsuo79yg",
    "state": "send failed"
  },
  "channelId": "emulator",
  "conversation": {
    "id": "c40e1ea1-4903-11e9-8fe3-5dfec8bc1e40|livechat"
  },
  "entities": [
    {
      "requiresBotState": true,
      "supportsListening": true,
      "supportsTts": true,
      "type": "ClientCapabilities"
    }
  ],
  "from": {
    "id": "f2ca045e-9add-4b3e-89b1-3c5a4b8e4b1d",
    "name": "User",
    "role": "user"
  },
  "id": "c92c6450-4903-11e9-97cc-7b939c9a16d2",
  "localTimestamp": "2019-03-17T18:27:02-04:00",
  "locale": "en-US",
  "recipient": {
    "id": "166",
    "name": "Bot",
    "role": "bot"
  },
  "serviceUrl": "https://5bac33fb.ngrok.io",
  "showInInspector": true,
  "text": "hello",
  "textFormat": "plain",
  "timestamp": "2019-03-17T22:27:02.037Z",
  "type": "message"
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Add natural language understanding to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by luisdiogo2071317** [comment]
Ngrok is only to test locally (I don't advise to use it) and you can use https://www.npmjs.com/package/luis-apis to put luis in the bot. There is many ways to setup a json for luis but I don't advise much to do that. Check this example https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/51.cafe-bot (has that example in C#). It has luis and qna maker and you just need to read really well the readme file to setup into azure both luis and qna maker. 
About the endpoint check it slowly this document and some youtube videos. Is easier to understand than just read documents. There is some examples of this like https://github.com/Microsoft/Cognitive-LUIS-Node.js/blob/master/luis_sdk/index.js and https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/12.nlp-with-luis (it has their version in C#).
I hope I have helped in something

**Comment by luisdiogo2071317** [comment]
And if you want to know where are the endpoints go to Manage/ Keys and Endpoints and check for Starter Keys below. There will be some keys. You just need to copy one of them or the url to luis configuration when/if needed. And just a warning there is a better way to use luis but I can't find where check in youtube or channel9 (is a Microsoft site that teach things of how to use Microsoft products)

**Comment by DanDev33** [comment]
To answer you second question first, ngrok is a utility that essentially creates a tunnel allowing you to locally test your application running on your localhost system. Recent versions of bot framework emulator (anything labeled v4.3.x) not sets this up internally and you not longer need to worry about ngrok.

You first question about Endpoints was answered by Luis in the comment above. You need the values obtained by following the steps in the section: 
"Retrieve application information from the LUIS.ai portal"
NOTE - I am changing the name here to match the instruction for updating you .bot file with endpoint information.

1. Select your published LUIS app from luis.ai.
2. With your published LUIS app open, select the MANAGE tab.
3. Select the Application Information tab on the left side, record the value shown for Application ID as <luis appid>.
4. Select the Keys and Endpoints tab on the left side, record the value shown for Authoring Key as <luis authoring key>. Note that your subscription key is the same as your authoring key.
5. Scroll down to the end of the page, record the value shown for Region as <luis region>.
6. Record the value shown for Endpoint as <luis endpoint>. THIS IS NOT NEEDED!

Now use these values as described in the article to "update the bot file".

These instructions have been modified, making them more simple and clear in a forthcoming update of the bot framework documentation. I hope this help until that update arrives.
