### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by tsahi** [MicrosoftDocs/bot-docs#950]
The links in the **Update the root dialog** section are broken:
"Implement sequential conversation flow" should link to https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0
"gather user input using a dialog prompt" should link to https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e377673-b61a-aa61-2015-8c65c528060d
* Version Independent ID: 2fc8e645-3497-5a4c-8307-37b2ffdc64a4
* Content: [Migrate an existing bot within the same .NET Framework project - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/migration/conversion-framework?view=azure-bot-service-4.0#convert-your-dialogs)
* Content Source: [articles/v4sdk/migration/conversion-framework.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/migration/conversion-framework.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by ivorb** [comment]
Fixed, will be live soon
