### ISSUE TITLE
Why GuestKey = nameof(CheckInDialog)?

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/bot-docs#952]
This will be a different value for each user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9577ff-cf56-e5de-84c3-bfe10aab5368
* Version Independent ID: b5d62753-f87b-4673-b09b-a5a3fd9360e8
* Content: [Reuse dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-compositcontrol.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-compositcontrol.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by baruchiro** [comment]
Or is it meant to distinguish between the root dialog and the current dialog?

**Comment by JonathanFingold** [comment]
No good reason for using that particular code. I think it may have been a bit of cruft from one refactoring or another that crept in. There is new sample code in the works for this article that will go out in a week or two.

The GuestKey constant is used by the dialog to save and retrieve the guest information the dialog collects.

Hope that helps clarify.
