### ISSUE TITLE
Error whencreating bot from template.

### ISSUE THREAD

**Issue by mapoitras** [MicrosoftDocs/bot-docs#953]
I'm trying to follow instructions and I get an error, early on.  

After I enter this command:
msbot clone services --name goc-bot-demo --luisAuthoringKey XXXX --folder "DeploymentScripts\en" --location westus

It creates almost everything, however I get this error when creating and importing LUIS.  I have verified the LUIS Authoring key.

Command failed: luis import application --region westus --appName "goc-bot-demo_General" --in DeploymentScripts\en\general.luis --authoringKey XXXXX --msbotgetaddrinfo ENOTFOUND westus.api.cognitive.microsoft.com westus.api.cognitive.microsoft.com:443

Any idea what might be causing this problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81426100-ac60-c692-0906-f9199deb2a6c
* Version Independent ID: f9aa4064-fe22-71c8-6ac3-93b0d0fa1bdd
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-getting-started?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-getting-started.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-getting-started.md)
* Service: **bot-service**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by Kaiqb** [comment]
This topic no longer exists. Closing.
