### ISSUE TITLE
Tightly coupling between steps

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/bot-docs#954]
It bothers me very much that the result of one step is handled in the next step.

In this way, I can not separate the steps and use them in whatever order I want, or wherever I want.

Step may also include a Handler function (although it does not really fit in with the source code), or StepContext will include lambda to handle the user's response (this can be done right now in a certain way).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c5adf9-272a-e0f1-10f1-c8365e76035b
* Version Independent ID: 1982af41-5a06-4398-0e95-abcc50864e0d
* Content: [Implement sequential conversation flow - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by DanDev33** [comment]
Hi Baruch,
Thanks for your feedback. Yes, this article focuses on the use of WaterfallSteps to control the flow of a conversation. That produces a very structured set of steps. It is equally possible to code your own control logic, evaluate each user input received, and branch control of your conversation based on what you just received. As a bot becomes more complex, this is often how it is coded. The capability is there to do this, it is just not discussed as part of this particular article.

**Comment by alokraj68** [comment]
Is there a doc where this custom method is specified?
