### ISSUE TITLE
Missing explanation about ReplaceDialogAsync

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/bot-docs#955]
What he does exactly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6606cce-8a4e-587b-ded2-bd775a4cd7c7
* Version Independent ID: 6f637bca-8cc0-a526-4cbd-9c5f9f94ca2b
* Content: [Create advanced conversation flow using branches and loops - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-complex-conversation-flow.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by Kaiqb** [comment]
It ends the active dialog and starts a new dialog in its place.

**Comment by ivorb** [comment]
@baruchiro I've added a quick explanation to the dialog concept, down in the "Repeating a dialog" section.
