### ISSUE TITLE
Where is the "Access token" field?

### ISSUE THREAD

**Issue by jjpepper** [MicrosoftDocs/bot-docs#956]
This is very confusing, the telegram side of things is clearly documented, but then what?  It says _Paste the token you copied previously into the **Accss Token** field and click **Submit**_ but there is no information where that field is or how to get to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abb43730-86de-40c5-08a2-4d8013065783
* Version Independent ID: 7fbf28b1-2fb1-58d9-188e-32cd59940c4f
* Content: [Create a bot for Telegram - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-telegram?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-telegram.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-telegram.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by DanDev33** [comment]
Hi Jesse,
I believe that this article assumes you are using an App called the Channel Inspector (referenced at the top) but that App no longer exists. So I'm afraid there is no clear answer to your question. This does not mean that Telegram bot service isn't functional, but this set of instructions is no longer applicable.
