### ISSUE TITLE
Unit-Testing?

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/bot-docs#957]
I guess you should just send an `Activity` object to the endpoint.
Is there a tool that produces activities? any Bot client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b24220ea-6a9f-2c17-e213-73fa577eb1fa
* Version Independent ID: dae9c683-5c77-c2c1-8dee-27a009487af5
* Content: [Testing and debugging guidelines - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-testing-debugging?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-testing-debugging.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-testing-debugging.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Hi Baruch,
I am unaware of a current tool that generates various activities for unit testing. (The test folks may have an internal utility I've not seen) In general, the bot emulator serves that purpose to locally provide user input back to your app. It also provides the capability to capture transcript files that preserve the interactions between your emulator and the app. 

Were you to want to write your own console app or similar to deliver a set of interactions, transcripts of these could be preserved within Blob transcript storage as describer here: 
https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md#blob-transcript-storage

**Comment by JonathanFingold** [comment]
There is also a `TestAdapter` that you can use to mock traffic from a channel.
