### ISSUE TITLE
Web App Bot from Existing App Service

### ISSUE THREAD

**Issue by juanfergc** [MicrosoftDocs/bot-docs#959]
Is it possible to create a web app bot using an existing app service? How can I see what app service a web app bot is using? just by having the same name? what is the relationship (in terms of files/resources) between a web app bot and an app service? If I publish a bot written in and directly from visual studio to a new app service, how can I create its web app bot so I can use the Test in Web Chat functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9e2e6-b901-9e27-d070-701922396a4c
* Version Independent ID: c29a68b2-886d-2cec-0ce7-c49c586d7ea8
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by DanDev33** [comment]
Hi Juan,
This repo is for bugs/issues found within our online documentation.
For a broader forum (monitored by bot framework support) please try asking your question on:
https://stackoverflow.com/questions/tagged/botframework
Thanks
