### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MCKRUZ** [MicrosoftDocs/bot-docs#961]
Can you give a better explanation about the "Suggestion" activity type and under what circumstances it might be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53617abe-a774-a211-390b-b2f0261c5bb6
* Version Independent ID: f1533f6c-f340-f838-d95b-ca5b6cd4b6dd
* Content: [Entities and activity types - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-activities-entities?view=azure-bot-service-4.0&tabs=cs#event)
* Content Source: [articles/bot-service-activities-entities.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-activities-entities.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
Take a look at the [section](https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-activity/botframework-activity.md#suggestion-activity) about this in the Activity Schema. (If it's not already there, I'll add a cross reference to the schema in the **Entities and activity types** article.

**Comment by JonathanFingold** [comment]
@MCKRUZ Please reopen if this did not answer your question.
