### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by git-mr** [MicrosoftDocs/bot-docs#962]
Just a small typo:
- Under header "Response event handlers" -&gt; Sentence "The handlers registered on a context object..." -&gt; phrase "manages the" is used twice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0103c5-0a27-4ce5-e5ad-f80631740f18
* Version Independent ID: ff562140-55c1-ea32-a4d2-6d1d3e12e1b4
* Content: [Activity processing - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-activity-processing?view=azure-bot-service-4.0#response-event-handlers)
* Content Source: [articles/v4sdk/bot-builder-concept-activity-processing.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-activity-processing.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by DanDev33** [comment]
Thanks for your feedback! this is fixed and the update will appear when our documentation is next refreshed.
