### ISSUE TITLE
Missing NuGet/npm package

### ISSUE THREAD

**Issue by ericfowler303** [MicrosoftDocs/bot-docs#963]
It should be mentioned in this documentation that Microsoft.Bot.Builder.ApplicationInsights needs to be add via nuget or botbuilder-applicationinsights via npm to make use of the initialization methods. I had to dig through github issues to finally figure this out as none of this was specified in the 4.2 release notes either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db892de5-e60e-1d4f-505b-11b1cdb73323
* Version Independent ID: f7263014-b8fa-9a20-71aa-e4217b2821ee
* Content: [Add telemetry to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-telemetry.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-telemetry.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Thanks for your feedback Eric. We are currently editing our docs for an update and I'll make sure we include this.

**Comment by DanDev33** [comment]
updated doc
