### ISSUE TITLE
The link behind "this GitHub repository" above is a bit deep

### ISSUE THREAD

**Issue by managedcoder** [MicrosoftDocs/bot-docs#964]
Just navigated to VA repo and that link takes me to the root of the src folder which is a bit deep for my likings.  I want to clone that repo (as I bet most everyone else does that clicks that link) and I had to pop up several levels to get to clone button and at a level where I get the full project (not just the src folder).  I would have preferred it take me to: https://github.com/Microsoft/AI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7338c62d-fdb3-5177-cf36-d37398c1d687
* Version Independent ID: c5cac0e9-fb71-6e2c-11df-5e940fd80fc8
* Content: [Virtual Assistant Overview - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-virtual-assistant-introduction?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-virtual-assistant-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-virtual-assistant-introduction.md)
* Service: **bot-service**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by ivorb** [comment]
We've found that various users like to do various things - you do need to be at the root to clone with the UI, but for those who are just interested in looking at the code this link takes them where they would want to be. Additionally, it's easier to go up a few levels to clone it than it is to know where to go deeper into. By taking you right to the src folder, you'll know where to start if you do decide to go up a few levels and clone.

Past that, a large number of users prefer to use command line to clone and manipulate their repos, so the link currently there provides what they're looking for to clone.
