### ISSUE TITLE
App Registration Requirements

### ISSUE THREAD

**Issue by reynoldsbd** [MicrosoftDocs/bot-docs#965]
After switching to a new deployment process, we ran into some requirements that are not documented here.

If you provide your own App ID and password (instead of letting the bot service create one automatically), the associated AAD registration must be [converged](https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-endpoint-comparison#who-can-sign-in).

Is it possible to document this requirement here or on some other page of these docs (such as in the How-To section)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9e2e6-b901-9e27-d070-701922396a4c
* Version Independent ID: c29a68b2-886d-2cec-0ce7-c49c586d7ea8
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by DanDev33** [comment]
I want to understand a bit more about the issue you encountered. Is this the problem you needed to solve? The App needed to be registered in a tenant to be sharable?

An application that wasn't registered in a tenant can only be managed by the account that registered it. It can’t be shared with other developers. This is the case for most apps that were registered using a personal Microsoft account in the App Registration Portal. 
If you’d like to share your app registration with multiple developers, register the application in a tenant using the App registrations (Preview) section of the Azure portal.

**Comment by reynoldsbd** [comment]
That's not the problem I'm trying to solve.

In order to use the Azure Bot Service to connect our bot to Teams or other channels, the provided app registration must accept sign-ins from all tenancies, not just our own. Internally, the service appears to be authenticating within some dedicated "botframework.com" tenancy rather than the customer's tenancy (i.e. mine).

Failure to provide such a "converged" application results in a bot that is effectively unusable outside of an emulator, because the Azure Bot Service cannot authenticate.

**Comment by DanDev33** [comment]
Thanks for the clarification. We are currently working through the authentication process for our doc update and will be sure to document/address this.

**Comment by JonathanFingold** [comment]
A new version of the authentication how to is live. As I understand it, converged apps are not a part of the new Azure app registration process. Please open a new issue if the new article has any flaws.
