### ISSUE TITLE
Adaptive Card code 

### ISSUE THREAD

**Issue by Rykimaruh** [MicrosoftDocs/bot-docs#967]
When I try the code in my local solution, there are a lot of errors such as Textblock, TextSize and TextWeight that say that they don't exit in the current context...where do you get them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c205b864-640c-a101-8468-6227d8f2e7cb
* Version Independent ID: a8c5bdba-01f3-46ec-1c73-a8fabd4ccf0f
* Content: [Add rich card attachments to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-rich-card-attachments?view=azure-bot-service-3.0)
* Content Source: [articles/dotnet/bot-builder-dotnet-add-rich-card-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-add-rich-card-attachments.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by DanDev33** [comment]
Does your adaptive card JSON include the following?
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
I believe that this schema should defines values such as Textblock, TextSize and TextWeight.

The best source for info on building and using adaptive cards is always found here:
     http://adaptivecards.io
The article you referenced points to this site several times.
