### ISSUE TITLE
Download code section appears to be incorrect or unclear

### ISSUE THREAD

**Issue by jaredfaris** [MicrosoftDocs/bot-docs#969]
It specifies that I'll need to update my `botFilePath` and `botFileSecret` entries in the .env file, but because I choose to include the keys that is unnecessary. This was a bit confusing, and I thought maybe there was an additional place I'd have to manually enter.

This should be broken down into two steps: if you click yes on including secrets, or if you click no.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9e2e6-b901-9e27-d070-701922396a4c
* Version Independent ID: c29a68b2-886d-2cec-0ce7-c49c586d7ea8
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by DanDev33** [comment]
Thanks for your feedback Jared. We are currently working on an update to our docs and will make this distinction clear. You will see this change the next time our documentation is updated.
