### ISSUE TITLE
Bot file needs to be unencrypted

### ISSUE THREAD

**Issue by jaredfaris** [MicrosoftDocs/bot-docs#971]
I had issues where my bot would fail to load, and state I needed to set my BotFileSecret. It turns out the .bot file is encrypted, and I had to run a command to unencrypt it to make these changes per the comment here: https://github.com/Microsoft/BotBuilder-Samples/issues/932#issuecomment-440039929

Please add better instructions to explain decrypting the bot file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by ivorb** [comment]
If you're using a .bot file, and it was created in Azure portal, it will be encrypted - so either decrypting it or using the botFileSecret is required.

Part of the listed Prerequisites in that article are the previous tutorial, which includes decrypting your .bot file as one of the steps. Assuming you had followed that, your bot file here would already be decrypted.

Will add mention to this article to decrypt it, if necessary, when adding the qna values.
