### ISSUE TITLE
Missing JS for Blob transcript storage

### ISSUE THREAD

**Issue by paalex** [MicrosoftDocs/bot-docs#972]
On https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript#feedback

Only instructions for C# exist for 'Blob transcript storage'. Missing instructions for Javascript

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8f39f5-1a91-6fdb-3cc0-124b282e9806
* Version Independent ID: 701f9b3c-a893-dee1-d012-760e6f870ec4
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by DanDev33** [comment]
Hi paalex,
Thanks for your feedback. Unfortunately, this is intentional. At the moment there are issues with the nodeJS implementation that keep bot Blob storage from working properly. We hope to provide this information once those issues are resolved.
