### ISSUE TITLE
Invalid syntax in BlobStorage initialization

### ISSUE THREAD

**Issue by paalex** [MicrosoftDocs/bot-docs#973]
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript#feedback

The instructions state:
`const mystorage = new BlobStorage({
   --your_containerName--,
   --your_storageAccountOrConnectionString--,
   --your_storageAccessKey--
})`

Should be:

`const mystorage = new BlobStorage({
   containerName: --your_containerName--,
   storageAccountOrConnectionString: --your_storageAccountOrConnectionString--,
   storageAccessKey: --your_storageAccessKey--
})`

*EDIT:*
From a lot of debugging apparently, this is the way it worked for me:
`const mystorage = new BlobStorage({
   containerName: --your_containerName--,
   storageAccountOrConnectionString: --your_ConnectionString--
})`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8f39f5-1a91-6fdb-3cc0-124b282e9806
* Version Independent ID: 701f9b3c-a893-dee1-d012-760e6f870ec4
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by DanDev33** [comment]
Hi paalex,
Thanks for your feedback!  Yes, our documentation changed the strings from actual values, but it would be more clear to retain label portions like "containerName:"  I will update our article to include your suggested improvement and you will see this change the next time our online articles are updated.
Thanks again for this feedback!

**Comment by DanDev33** [comment]
Hi paalex,
I double checked this against the way Azure Blob storage currently has us access storage.
A connection string can be found underneath Settings.Access Keys: "Connection string"
you can set this up to connect using the following:

private static readonly AzureBlobStorage _myStorage = new AzureBlobStorage("<your-blob-storage-account-string>", "<your-blob-storage-container-name>");

My Blob storage connects using:

private static readonly AzureBlobStorage _myStorage = new AzureBlobStorage("DefaultEndpointsProtocol=https;AccountName=mynewtestblobstorage;AccountKey=3CcwuOYi9t98LfvELKNy46lXVzpXXXXXXXnayY/R2ggqQrX5ismrZvFDhNVO4wssQSFm0aVLnC8Kux73A==;EndpointSuffix=core.windows.net", "mynewtestblobstorage");
(I XXX'd out some of my actual account access key) ;)

Notice that the string itself contains the labels AccountName= , AccountKey= &  EndpointSuffix=

This is how the updated documentation will show connection to Blob storage. If this doesn't work for you, please reopen this issue and show me the error message you are getting.
