### ISSUE TITLE
No HTML title attribute on https://dev.botframework.com/

### ISSUE THREAD

**Issue by LionOfJewdah** [MicrosoftDocs/bot-docs#974]
The page renders with title "https://dev.botframework.com/" as the title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1217f5b5-6736-e72c-c420-773fc968aff3
* Version Independent ID: 3a139655-6959-d8fd-a982-fe527db4d04a
* Content: [Additional support resources for the Bot Framework - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-links-help?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-resources-links-help.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-resources-links-help.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by DanDev33** [comment]
This appears to be fixed. Thanks!
