### ISSUE TITLE
What are the several other channels available?

### ISSUE THREAD

**Issue by juanpdelat** [MicrosoftDocs/bot-docs#976]
The [documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-4.0) says:
> You can connect to many popular services, such as Cortana, Facebook Messenger, Kik, and Slack, as well as several others.
>  
But there is no full list of those _"several others"_.

**Comment by Kaiqb** [comment]
The most accurate list is in the Azure portal. For details, see: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-channels?view=azure-bot-service-4.0.

**Comment by juanpdelat** [comment]
Looks like I pasted the wrong link but the quote is from that page you posted. In any case, what I am understanding is that I need to create an account to be able to see the most accurate up to date list, probably not the most optimal for people trying to asses if the framework is suitable for their project.
