### ISSUE TITLE
TranscriptLoggerMiddleware - how to see and list data

### ISSUE THREAD

**Issue by Mironiny** [MicrosoftDocs/bot-docs#977]
Hi, 

I implemented `TranscriptLoggerMiddleware` using `AzureBlobTranscriptStore` as you suggest in the documentation. 

Logging is working nicely and every single message is stored in Blob container. But there is one problem, I cannot filter or order logs by date. Which is really inconvenient. Imagine the situation, when you want to see logs from only one specific day. 

 On the image below is logs ordered by key. But there is no option (or maybe I just don't see one) how to order by date. Do you have any solution? Maybe add to key a timestamp?
![image](https://user-images.githubusercontent.com/14194813/54953248-0fa19c80-4f48-11e9-9ff0-b2e515d488b8.png)

**Comment by DanDev33** [comment]
hi Mironiny, Thanks for your suggestion.
I have encountered this same issue where I wanted to sort based on a date. I've added this as a suggested enhancement for our product.

**Comment by Kaiqb** [comment]
You can log feature request on the [Azure feedback site](https://feedback.azure.com/forums/34192--general-feedback).
