### ISSUE TITLE
Additional v3 vs v4 comments #966

### ISSUE THREAD

**Issue by leo-leong** [MicrosoftDocs/bot-docs#979]
additional differences based on migrating ContosoHelpdeskChatBot https://github.com/MicrosoftDocs/bot-docs/pull/966 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09f6b021-efb3-761f-6f00-cbd679e39dfc
* Version Independent ID: 72806cd3-23c7-6e60-d54d-3ecc0e4bc371
* Content: [Differences between the v3 and v4 SDK - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/migration/migration-about?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/v4sdk/migration/migration-about.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/migration/migration-about.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
Article is updated in a branch that will go live in a week or two.
