### ISSUE TITLE
Manage state data in SDK V4 Nodejs

### ISSUE THREAD

**Issue by vinayjayaram** [MicrosoftDocs/bot-docs#980]
Can we have Manage state data in SDK V4 using Nodejs? I currently have used in SDK V3 using the link below https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state?view=azure-bot-service-3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67435bf0-7a12-d321-4e32-1a05989edb89
* Version Independent ID: 2f9c7e9b-fd15-40cb-5b50-04a8e2d5b477
* Content: [Manage state data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-state.md)
* Service: **bot-service**
* GitHub Login: @ducvo
* Microsoft Alias: **v-ducvo**

**Comment by ivorb** [comment]
The articles have moved or changed titles, so there isn't a direct correlation - but the content should be available!

The content you're interested in I think would be here: [Save user and conversation data](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=javascript) but there are some other articles about state and writing to storage in the left hand TOC.

Our samples, linked to from the top of that article, provide good examples of using state
