### ISSUE TITLE
Prerequisites GitHub links broken

### ISSUE THREAD

**Issue by T4ssilo** [MicrosoftDocs/bot-docs#981]
Search.Azure, Search.Contracts and Search.Dialogs are all 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3bc8631-6157-a3aa-431a-fc65abc6c752
* Version Independent ID: d8d2de9c-082d-090f-f6d0-93e74555089e
* Content: [Create data-driven experiences with Azure Search - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-search-azure?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/dotnet/bot-builder-dotnet-search-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-search-azure.md)
* Service: **bot-service**
* GitHub Login: @matthewshim-ms
* Microsoft Alias: **v-shimma**

**Comment by JonathanFingold** [comment]
These projects can be found [here](https://aka.ms/v3-cs-search-demo) now. The links are fixed in a PR that should go live soon.

**Comment by msekkappan** [comment]
The links take to V3 bots, are there Azure search samples for v4 bots
