### ISSUE TITLE
The scope of the connection setting needs to have both openid and a resource in the Azure AD graph, such as Mail.Read.

### ISSUE THREAD

**Issue by cxputcm** [MicrosoftDocs/bot-docs#983]
can you clarify this ? am I supposed to create a custom scope here with the openid and a permission in it ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
You just need to add these delegated permissions. (This wording is confusing and I'm updating the doc.)

Does that answer your question?

**Comment by JonathanFingold** [comment]
The samples and how-to articles have been updated. Please let us know if the updated article is still confusing on this point.
