### ISSUE TITLE
Enterprise Bot.cs constructor and OnTurnAsync always fired twice on start

### ISSUE THREAD

**Issue by miojoffey** [MicrosoftDocs/bot-docs#984]
When creating an enterprise bot project, Bot.cs constructor and OnTurnAsync always gets fired twice on run. To replicate this, create an enterprise bot project and have this configured to run. Run locally for debugging, and you will notice this. 

I cannot find on the internet how to deal with this, and is a constant issue for me when doing enterprise bots

**Comment by Kaiqb** [comment]
Please refer to https://github.com/microsoft/botframework-solutions/tree/master/docs for latest docs on Virtual Assistant/Enterprise Bots.
