### ISSUE TITLE
.bot file missing

### ISSUE THREAD

**Issue by damienestewart** [MicrosoftDocs/bot-docs#985]
"The code you downloaded uses an encrypted .bot file", does that mean the downloaded code should've included a .bot file? If so, after creating the Web App Bot using the Echo template (Node.js) and then downloading the code, I'm noticing that there's no .bot file in the zip. Also, the downloaded .env file that came with the source code doesn't have botFilePath/botFileSecret. Instead it has MicrosoftAppId/MicrosoftAppPassword.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9e2e6-b901-9e27-d070-701922396a4c
* Version Independent ID: c29a68b2-886d-2cec-0ce7-c49c586d7ea8
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by pkaushik23** [comment]
+1

**Comment by ivorb** [comment]
This has been updated, with details added to [Manage bot resources](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp) and [Deploy your bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp).

The bot file is going away, and the rest of the changes for our samples and articles are coming shortly, but the links above should give you enough to go on for now.
