### ISSUE TITLE
No .bot file when trying to download the source code

### ISSUE THREAD

**Issue by pkaushik23** [MicrosoftDocs/bot-docs#986]
I am using personal account and using azure portal while i follow following instructions. But i don't get a .bot file int the zip file 
that is downloaded. 
I created the "Web app bot" with SDK language as c# and SDK version 4 . 

**Followed these steps:** 
1. In the Bot Management section, click Build.
2. Click on Download Bot source code link in the right-pane.
3. Follow the prompts to download the code, and then unzip the folder. (_i selected options to include the settings_)

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
This has been updated, with details added to [Manage bot resources](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp) and [Deploy your bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp).

The bot file is going away, and the rest of the changes for our samples and articles are coming shortly, but the links above should give you enough to go on for now.
