### ISSUE TITLE
Channel inspector is retired

### ISSUE THREAD

**Issue by msimecek** [MicrosoftDocs/bot-docs#988]
Since the channel inspector has been retired, the Tip at the top of this page should be removed (it points to BotBuilder samples, which is misleading).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac4d38d8-00f8-10f8-6641-9de10ff0c9eb
* Version Independent ID: 2af2a93a-b938-74d2-6709-f1b245af63be
* Content: [Add suggested actions to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-suggested-actions?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/rest-api/bot-framework-rest-connector-add-suggested-actions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-add-suggested-actions.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by DanDev33** [comment]
Thanks for your feedback Martin!
I'll remove this Tip that now links to nowhere.
You'll see this change the next time our docs are updated online.
