### ISSUE TITLE
How to Deploy Sample.AadV2Bot to Azure 

### ISSUE THREAD

**Issue by arunkumarperumal** [MicrosoftDocs/bot-docs#991]
Hi, 
After deploying to azure, can't test in the Web Chat, but the same when tested in using Bot Framework Emulator, works fine. 

Please let me know how to get it working in Web Chat. 

Same issue with using the  Bot on Teams, It does not work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d80e0b-f1b7-175b-128d-0fb12f17ae36
* Version Independent ID: 1ed9006a-bf0b-9aaa-d180-9d2cb0c09524
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0#feedback)
* Content Source: [articles/bot-builder-tutorial-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tutorial-authentication.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **JonathanFingold**

**Comment by Kaiqb** [comment]
If you are looking for auth content for SDK v4, take a look at this [topic ](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-authentication?view=azure-bot-service-4.0)and additional content that it links to.
