### ISSUE TITLE
need more clarification under "Send Activity"

### ISSUE THREAD

**Issue by pkaushik23** [MicrosoftDocs/bot-docs#993]
I was always getting a 500 internal server error, without any detail. The documentation missed an important point that the secret key cannot be used to send an activity. Kindly update the documentation accordingly. 
Please refer the issue 
https://github.com/Microsoft/BotBuilder/issues/4184#issuecomment-479117472
and solution/observation here 
https://github.com/Microsoft/BotBuilder/issues/4184#issuecomment-479123481

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e4dd44-9bfc-14b1-cfd4-d37d500b1877
* Version Independent ID: 965c2c94-8cf1-fbf0-c321-547a90449382
* Content: [Send an activity the bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-send-activity?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-send-activity.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-send-activity.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by pkaushik23** [comment]
@DanDev33 one question, why the label of v3 SDK and not v4?

**Comment by mmiele** [comment]
Added a note clarifying the reason for the 500 server error. You can find the change [here](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-send-activity?view=azure-bot-service-4.0#response).
