### ISSUE TITLE
Can't access the language reference for Node.js SDK v3

### ISSUE THREAD

**Issue by bankotsu** [MicrosoftDocs/bot-docs#994]
I'm writing a bot using SDK v3 for Node.js (I started it before v4 was released). Now I can't seem to access the language reference for this SDK and would appreciate if you can tell me how I can get access to it again. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ffe447d-f0a8-f4b6-d572-ba2c3bba4aab
* Version Independent ID: 6c1d9a6a-4cb3-f404-ce1f-940b443f0e34
* Content: [Azure Bot Service Introduction - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-overview-introduction.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-overview-introduction.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
This is a know issue. We're working on a fix.

**Comment by Kaiqb** [comment]
@bankotsu - You might want to read the v3 lifetime support info here: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0#bot-framework-sdk-version-3-lifetime-support.
