### ISSUE TITLE
Doc for welcoming users combines two unrelated ways of welcoming

### ISSUE THREAD

**Issue by navzam** [MicrosoftDocs/bot-docs#996]
The "Send welcome message to users" doc shows two ways of welcoming the user: on conversation update activities and on the first message activity. This is confusing for multiple reasons:

1) It isn't clear why you would ever use the 2nd way (i.e. waiting for a message activity), which would force the user to initiate the interaction
2) The 2nd way requires state, which complicates the doc and code sample
3) You can implement one of these ways without the other, but the doc shows them together (in the same code snippets) as if they are related

This is related to https://github.com/Microsoft/BotBuilder-Samples/issues/1201, which was closed for a reason not clear to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a16806-95d6-7c66-3b85-b2ace211f367
* Version Independent ID: c8565ece-392a-fb56-e911-8a5dd5555dee
* Content: [Send welcome message to users - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-send-welcome-message?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-send-welcome-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-send-welcome-message.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DanDev33
* Microsoft Alias: **v-dashel**

**Comment by DanDev33** [comment]
Hi Nafis,

Thanks for your feedback. I agree with you that using only the ConversationUpdate event would simplify this process, but unfortunately not all channels process and return user data in the same way. If a channel responds like the bot framework emulator (returning info when a user is initially connected) you can welcome the user and in that response request that they provide you with initial registration data. In that case, you can validate against the first returned user data to gather information such as a user's name if they are not previously registered. However, some external channels return no information related to a ConversationUpdate until after the user has previously sent an utterance to your bot. Were you to try validating this initial user input it would not contain useful data and would instead return an error. This is why we chose to show both the ConversationUpdate and an initial Activity.Message working together to produce a consistent user experience across multiple channels regardless of how they process initial data.

However, the Version 4.3 APIs have attempted to make this simpler by providing 2 new calls:
onMembersAddedAsync( ) - Called when a new member is added to a conversation. 
onMessageActivityAsync( ) - Called when a new message is received from your user.

The article you referenced is also being rewritten to make it easier to follow and implement. So while we still need to show welcome based on both of these events, we hear you and are trying to make this less complex.

I hope that this addresses your concern. And thanks for helping us make our documentation better.

-Dan

**Comment by navzam** [comment]
@DanDev33 In that case, in the rewritten version, I think it's really important to explicitly separate the two ways, and point out which channels do not send a `ConversationUpdate`

**Comment by DanDev33** [comment]
Closed awaiting document update.
