### ISSUE TITLE
Creating App Registrations has changed and needs better documentation.

### ISSUE THREAD

**Issue by bw-kforce-ms** [MicrosoftDocs/bot-docs#997]
1/ There are cases where you want to create the app registration first (for example, in an enterprise where IT admins own creating app ids and secrets.)
2/ In this case, you visit the AAD blade, and the App Registration (Preview) Blade
3/ Supported account types under "Authentication" must be "Accounts in any organizational directory"
4/ Edit your manifest and set "accessTokenAcceptedVersion": 2 (for AAD v2 auth)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0460109c-16ac-0b5c-8624-4d362122e8b4
* Version Independent ID: 2961c42d-695d-46f0-1c7b-9be929e3f88e
* Content: [Create a Bot Channels Registration with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-quickstart-registration.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart-registration.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by ivorb** [comment]
Take a look [at this part of the FAQ](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-3.0#app-registration) which should help. Additionally, the authentication topics have been updated to make things more clear, with more changes coming soon.

If that doesn't solve your issues, please open a new issue with more details on what exactly you would like to see. Thanks!
